### ISSUE TITLE
Missing parameter to printf does not create an error

### ISSUE THREAD

**Issue by mrdudz** [cc65/cc65#1001]
#include <stdio.h>

int main(void)
{
    printf("test",);    /* should be an error */
    return 0;
}

**Comment by greg-king5** [comment]
Fixed by commit 90a2edcfa2e759893a1df9f8108267b43f769faf.  Now, it says,
```
Error: Argument expected after comma
```

**Comment by oliverschmidt** [comment]
Thanks :-)

**Comment by mrdudz** [comment]
btw, how do we make testcases that are supposed to fail? (can we?)

**Comment by oliverschmidt** [comment]
https://github.com/cc65/cc65/tree/master/test/err

**Comment by mrdudz** [comment]
yay. test comitted (i totally forgot i can do this =))
