### ISSUE TITLE
[atari] how to use init ptr in __devhdl_t ?

### ISSUE THREAD

**Issue by tschak909** [cc65/cc65#1002]
In `_atarios.h`, there is the following struct:
```c
struct __devhdl {
    void *open;                 /* address of OPEN routine -1 */
    void *close;                /* address of CLOSE routine -1 */
    void *get;                  /* address of GET BYTE routine -1 */
    void *put;                  /* address of PUT BYTE routine -1 */
    void *status;               /* address of GET STATUS routine -1 */
    void *special;              /* address od SPECIAL routine -1 */
    void (*init)(void);         /* init routine (JMP INIT) */
    void *reserved;             /* unused */
};
```
The `init` field is supposed to be a full JMP instruction to an actual address, e.g. $4C $14 $23, how can I deal with this, from C? Is this struct in error?

For reference, here is a snippet from the Atari 850 handler sourcecode:
```asm
.BYTE 94,$31    ;RHOPEN-1
.BYTE 96,2      ;RHCLOS-1
.BYTE 98,2      ;RHGET-1
.BYTE 100,2     ;RHPUT-1
.BYTE 102,2     ;RHSTAT-1
.BYTE 104,2     ;RHSPEC-1
.BYTE $4C,118,3 ;JMP RINWRM
.BYTE 0
```

**Comment by tschak909** [comment]
oh for fsck's sake, I just found this buried in Atari's internal documentation. regarding cio init:
![image](https://user-images.githubusercontent.com/2759782/73142198-a13ed680-4051-11ea-8554-2ec8b0395684.png)

It's referenced on page 136 of this manual:
https://archive.org/details/bitsavers_atari40080mputerTechnicalReferenceNotes1982_20170986/page/n119/mode/2up

sigh. *bang-head-against-wall*

**Comment by polluks** [comment]
So fixing the OS, i.e. a new ROM, does not make any sense?

**Comment by dmsc** [comment]
I created a pull request to fix the struct definition.

**Comment by oliverschmidt** [comment]
Fixed with https://github.com/cc65/cc65/pull/1003.
