### ISSUE TITLE
[ca65] [65816] Far segments broken

### ISSUE THREAD

**Issue by ARM9** [cc65/cc65#1004]
Compiled ca65 from the latest commit on the master branch.

I tried building an old project that builds fine with some older build of ca65 and I get this error message:
```main.asm(6): Error: Invalid address size specification for current CPU```
from this line:
```.segment "SRAM_BSS" : far```

Test here: https://gist.github.com/ARM9/9ef95c030ecfaa52a47e8537f13583fe

**Comment by greg-king5** [comment]
Oops!  I typed a shortcut "and" (`&&`) where I should have typed a shortcut "or" (`||`) in commit 2e5fbe89cd3f67b06b292936dfdf4fdb104b7112.

Fixed by commit e2c664860781747eb247770bc766c7f0c5351a62.
