### ISSUE TITLE
ca65 - Question - struct and accessing hi/lo bytes as well as other questions

### ISSUE THREAD

**Issue by JustinBaldock** [cc65/cc65#1005]
Slowly teaching myself asm. Having a structure to group variables seems like a smart idea. 
```asm
.struct cursor
  pos_x .word
  pos_y .word
  frame .byte
  status .byte
.endstruct
```
I am correct about write/read value into .byte is via cursor::status.
```asm
lda #20 
sta cursor::status
```
But, how do I write/read a value in to the low and high bytes of pos_x .word?

I'm struggling with the documentation with regards to .struct and how to use them effectively. Is declaring them an instance? Or, is it the template, and I need to create objects from it? If so, how. A pointer to documentation / tutorial would be helpful and well received.

**Comment by Marrin** [comment]
Declaring a struct doesn't reserve memory it just defines the struct and its members as offset from the start of the structure.  To actually reserve memory use the .tag command.

cursor::status in your example is the offset into the structure.  So your code will write 20 to address 6.

Here is an untested example of reserving memory for the structure and put 20 into status and 1000 into pos_x:

    .struct cursor_t
        pos_x   .word
        pos_y   .word
        frame   .byte
        status  .byte
    .endstruct

    .code
    start:
        lda #20
        sta cursor + cursor_t::status
        lda #<1000
        sta cursor + cursor_t::pos_x
        lda #>1000
        sta cursor + cursor_t::pos_x + 1
        rts

    .bss
    cursor:
        .tag cursor_t

**Comment by JustinBaldock** [comment]
Thank you and that code appears to work.
