### ISSUE TITLE
SMB instruction not recognized on 65C816 ?

### ISSUE THREAD

**Issue by EtchedPixels** [cc65/cc65#1014]
This works

.pc02
smb0 tmp1

This errors

.p816
smb0 tmp1

**Comment by EtchedPixels** [comment]
Not a bug - .p816 is correctly not a superset of 65C02 in the assembler

**Comment by polluks** [comment]
Indeed, https://cc65.github.io/doc/ca65.html#ss11.82 says _SC_.
