### ISSUE TITLE
[telestrat][info] Step by step instructions on how to use and test

### ISSUE THREAD

**Issue by Fabrizio-Caruso** [cc65/cc65#1016]
@jedeoric 
Could someone please provide step by step instructions to explain how to use the `telestrat` binaries produce when compiling with the CC65 target `telestrat`?

I am willing to test the target.

**Comment by polluks** [comment]
Well, at least you need to convert the TAP file into a DSK one.

**Comment by Fabrizio-Caruso** [comment]
@polluks, how. Which emulator and options can I use. 
I am asking for a simple step by step guide.

I would like to test this target.

**Comment by polluks** [comment]
See http://forum.defence-force.org/viewtopic.php?p=2508&sid=771adc92f65b2e79075a116585c0b72c#p2508

**Comment by Fabrizio-Caruso** [comment]
@polluks , not clear to me whether I can just use tap2dsk and then use it with a Telestrat emulator.
It refers to an additional tool "old2mfm". There is no link to this tool. Do I need to use it?

How do I have to set the emulator? Do I need a Stratsed image?

What are the exact steps you perform to get a program to run into an emulated Telestrat?

**Comment by Fabrizio-Caruso** [comment]
@jedeoric could you please give me some more details?
I am very willing to help you test your code.

**Comment by jedeoric** [comment]
@Fabrizio-Caruso you should read the email i sent you (31/10/2018 at 12h02). It did not change since this email. As i said, telestrat target build both orix and stratsed binary. But, Orix header is added because i don't know any tool to build a stratsed disk.
