### ISSUE TITLE
Commander x16 r37 support

### ISSUE THREAD

**Issue by CJLove** [cc65/cc65#1020]
Version r37 of the Commander x16 rom and emulator is out.  I'm not aware of the full scope of changes needed for cc65, but things that I'm aware of:

1. Vera register and register map changes
2. Bank 0 RAM address changes affecting `waitvsync()`, etc.
3. Potential address changes for other kernal functions.
4. `vpoke()` and `vpeek()` no longer seem to be setting up VERA address registers in order to use `VERA.data0` for writing video RAM.

**Comment by msdos621** [comment]
Has anyone taken a look at this?

**Comment by oliverschmidt** [comment]
> Has anyone taken a look at this?

If no comment shows up here then likely not.

**Comment by CJLove** [comment]
I've created a fork of the cc65 repo and have started working on updates for r37.  I'm new to the cc65 code so this will be a work in progress...

**Comment by greg-king5** [comment]
I did the previous updates to the library.  I started on r37 (cx16.inc and cx16.h are finished), but got side-tracked.

I haven't looked at the `vpeek()` and `vpoke()` problem.  But, I'm surprised that they fail.  As far as I know, nothing was changed in that part of VERA.

**Comment by CJLove** [comment]
Not sure.  I'm just coming back to this after originally trying to port some code to r37 when it first came out.  There's now another bitfield in the VERA::CTRL register so I'm wondering the code in `vaddr.s` should no longer be zeroing out that register.

**Comment by CJLove** [comment]
Actually it looks like the increment field (top 4 bits of the VERA `ADDR_H` register) and DECR field (bit 3) are now getting zero'd out with each `vpoke()` or `vpeek()` call.  This register now only holds 1 bit of the VRAM address.  The following update to `vaddr0` works with an updated version of the cc65-sprite program from the x16 demo repo:

```
        .export         vaddr0

        .importzp       sreg
        .importzp       tmp1
        .include        "cx16.inc"


vaddr0: stz     VERA::CTRL      ; set address for VERA's data port zero
        ldy     sreg
        sta     VERA::ADDR
        stx     VERA::ADDR+1
        tya
        and     #$01            ; VERA ADDR_H now limited to bit 16
        sta     tmp1
        lda     VERA::ADDR+2    ; Load current register to preserve Address Increment and DECR fields
        ora     tmp1            ; incorporate high bit of address
        sta     VERA::ADDR+2
        rts
```

**Comment by greg-king5** [comment]
> Actually, it looks like the increment field (top 4 bits of the VERA `ADDR_H` register) and DECR field (bit 3) are now getting zeroed out with each `vpoke()` or `vpeek()` call. That register now holds only 1 bit of the VRAM address.

That doesn't matter.

- `vpeek()` and `vpoke()` access only one byte; therefore, what happens to the address afterwards doesn't matter.
- Any code that sets a VERA address also should set the address increment for that code's specific task.  Therefore, the increment field doesn't need to be preserved.

  - The same is true for the Display Composer.  Don't assume that the desired bank of registers was exposed by something else.  Explicitly choose it yourself.

I didn't need to change `vpoke()` for the sprite demo.  I needed to change only the addresses that are poked.

**Comment by CJLove** [comment]
Got it.  Just wondering...should I just wait for your r37 code changes to land at this point?

**Comment by CJLove** [comment]
Got the cc65-sprite demo working with the change to vaddr0.s reverted.

**Comment by oliverschmidt** [comment]
Am I correct in assuming that https://github.com/cc65/cc65/commit/cbf0c1d1dddc9d201ef3bf6ce9f3d5b54bc6e325 fixed this issue?

**Comment by CJLove** [comment]
Yes.  Thanks!
