### ISSUE TITLE
Take the challenge

### ISSUE THREAD

**Issue by polluks** [cc65/cc65#1024]
https://www.xtof.info/blog/?p=714
https://github.com/mysterymath/lcc6502#cc65

**Comment by dmsc** [comment]
> https://www.xtof.info/blog/?p=714
> https://github.com/mysterymath/lcc6502#cc65

```
void count_neighbours( uint8_t* cell, uint8_t* count ) {
    *count = *cell++; *count += *cell++; *count += *cell;
    cell += JUMP_BEGINNING_NEXT_LINE;
    *count += *cell; cell+=2 ; *count += *cell;
    cell += JUMP_BEGINNING_NEXT_LINE;
    *count += *cell++; *count += *cell++; *count += *cell;
}
```

What horrible piece of C code... It looks like the writer was really trying to obfuscate the code and slow down the algorithm.

IMHO, this is easier to understand, shorter, and produces much faster code by cc65:

```
typedef unsigned char uint8_t;
#define NEXT_LINE (40)

uint8_t count_neighbours( uint8_t* cell_ptr ) {
    register uint8_t * cell = cell_ptr;
    return cell[0] + cell[1] + cell[2]
          + cell[NEXT_LINE] + cell[NEXT_LINE+2]
          + cell[2*NEXT_LINE] + cell[2*NEXT_LINE+1] + cell[2*NEXT_LINE+2];
}
```

**Comment by oliverschmidt** [comment]
Looking at the generated assembly on https://www.xtof.info/blog/?p=714 I'm wondering if the optimizer was enabled at all...

**Comment by polluks** [comment]
Maybe the answer is an own clip? "cc65 strikes back"

**Comment by oliverschmidt** [comment]
Maybe I don't get the point... but so far I don't see any project challenging cc65 ;-) All projects I have seen didn't get beyond the point of complaining about cc65...

What I want to say: If there would be an actual alternative to cc65 then one could argue that there needs to be some marketing initiative to avoid users going for the "wrong" tool chain. But I don't see any alternative - so I personally would let "them" just say whatever they see fit.

**Comment by polluks** [comment]
Ok, we may re-open this ticket if lcc65 going to rule the world ;-)

**Comment by oliverschmidt** [comment]
ACK ;-)
