### ISSUE TITLE
--local-strings is broken for arrays

### ISSUE THREAD

**Issue by EtchedPixels** [cc65/cc65#1028]
Simple demo
```c
char *foo[2] = { "one", "two" };
```
```
cc65 --local-strings /tmp/6.c
```
End result is this nonsense:
```asm
.segment	"DATA"

_foo:

.segment	"RODATA"

L0002:
	.byte	$6F,$6E,$65,$00
	.addr	L0002
L0004:
	.byte	$74,$77,$6F,$00
	.addr	L0004
```
If the string output put the segment back, it would help; but, the `const char *foo[2] = ..` case would still be broken.

Oddly, the code version works correctly and does remember to change segment back.

Not a big deal to me: I found it by accident whilst working on a 6800 C compiler based on chunks of CC65.  The fix, I think, is to make `UseLiteral()` ignore the localstring stuff; but instead, call `OutputLiteralPool()` at the end of each function or static/global initializer if localstrings are set.

**Comment by oliverschmidt** [comment]
1. To me it seems that this issue isn't related to the array aspect of the demo. Rather it seems to be related to initializing a character pointer to an unnamed char string.

2. I don't understand what understand what '_the code version_' refers to.

**Comment by EtchedPixels** [comment]
2. If you emit code after the string then the compiler correctly puts it together so 

func("foo");

works properly. Hence it only seems to show up on arrays.

**Comment by oliverschmidt** [comment]
> code [...] func("foo");

I see.

> Hence it only seems to show up on arrays.

As already mentioned I can't see the relation to arrarys. As far as I see

`char *foo = "one";`

fails just as badly as your array example.

**Comment by EtchedPixels** [comment]
Ok I didn't try that example

**Comment by oliverschmidt** [comment]
Fixed by https://github.com/cc65/cc65/pull/1041.
