### ISSUE TITLE
Need to build an array of memory addresses

### ISSUE THREAD

**Issue by peteym5** [cc65/cc65#1032]
```c
unsigned char P000 [] = {
     0b00010000,  // $10  16
     0b00111000,  // $38  56
     0b00111000,  // $38  56
     0b01111100,  // $7C  124
     0b01111100,  // $7C  124
     0b01111100,  // $7C  124
     0b01111100,  // $7C  124
     0b00111000,  // $38  56
     0b00111000,  // $38  56
     0b00111000,  // $38  56
     0b00101000,  // $28  40
     0b00101000,  // $28  40
     0b00101000,  // $28  40
     0b00101000}; // $28  40

unsigned char P001[] = {
     0b00010000,  // $10  16
     0b00111000,  // $38  56
     0b00111000,  // $38  56
     0b01111000,  // $78  120
     0b01111000,  // $78  120
     0b01111100,  // $7C  124
     0b01111110,  // $7E  126
     0b00111010,  // $3A  58
     0b00111010,  // $3A  58
     0b00111000,  // $38  56
     0b00101000,  // $28  40
     0b00101100,  // $2C  44
     0b00100100,  // $24  36
     0b00100000}; // $20  32

unsigned char P002[] = {
     0b00011100,  // $1C  28
     0b00011100,  // $1C  28
     0b00001100,  // $0C  12
     0b00011110,  // $1E  30
     0b00111110,  // $3E  62
     0b00111110,  // $3E  62
     0b00011110,  // $1E  30
     0b00011100,  // $1C  28
     0b00011000,  // $18  24
     0b00011000,  // $18  24
     0b00011000,  // $18  24
     0b00011100,  // $1C  28
     0b00011100,  // $1C  28
     0b00010100}; // $14  20

unsigned char P003[] = {
     0b00010000,  // $10  16
     0b00111000,  // $38  56
     0b00111000,  // $38  56
     0b00111100,  // $3C  60
     0b00111100,  // $3C  60
     0b01111100,  // $7C  124
     0b11111100,  // $FC  252
     0b10111000,  // $B8  184
     0b10111000,  // $B8  184
     0b00111000,  // $38  56
     0b00101000,  // $28  40
     0b00101100,  // $2C  44
     0b00100100,  // $24  36
     0b00100000}; // $20  32

unsigned char P004[] = {
     0b00011100,  // $1C  28
     0b00011100,  // $1C  28
     0b00011000,  // $18  24
     0b00111100,  // $3C  60
     0b00111110,  // $3E  62
     0b00111110,  // $3E  62
     0b00111100,  // $3C  60
     0b00011100,  // $1C  28
     0b00001100,  // $0C  12
     0b00001100,  // $0C  12
     0b00001100,  // $0C  12
     0b00011100,  // $1C  28
     0b00011100,  // $1C  28
     0b00010100}; // $14  20

unsigned char spriteaddrlo[] = {&P000 & 0xff,P001 & 0xff,P002 & 0xff,P003 & 0xff,P004 & 0xff
};
  
unsigned CHAR spriteaddrhi[] = {P000 >> 8, P001 >> 8, P002 >> 8, P003 >> 8, P004 >> 8, P005 >> 8
};
```
I am trying to make a table that has the low and high byte of each sprite in CC65, but the compiler keeps reporting an error messages "Integer expression expected" or "Converting pointer to integer without a cast."  Going to need to know how to get address of "p000" to make this work. I tried to documentation, but there does not to be any answers within.

**Comment by mrdudz** [comment]
i'd use ((unsigned int)&P000[0])&0xff and ((unsigned int)&P000[0])>>8 .... the compilers error messages pretty much tell you what to do :=)

that said, if these are sprites, you probably want to put them at properly aligned addresses anyway, in an assembler file.

**Comment by peteym5** [comment]
Thankyou very much and I do combine assembly and higher programmer languages. I am looking into using C, Pascal, and Compiled Basic for alternatives to doing games all in assembly.

**Comment by peteym5** [comment]
If I use assembler for part of my program. How do I keep the pointers (memory addresses) available for the C part when I link the program together?

**Comment by mrdudz** [comment]
.export _foo
_foo: .byte 0

extern unsigned char _foo;

isnt this described in the docs somewhere? *shrug*

**Comment by polluks** [comment]
Indeed, it's part of the [intro](https://cc65.github.io/doc/intro.html).

**Comment by peteym5** [comment]
I can make a final master ASM file to use " .INCLUDE" 
 .INCLUDE "compiled-from-cc65..asm"
 .INCLUDE "ml_subs1.asm"
 .INCLUDE "data1.asm"

**Comment by oliverschmidt** [comment]
> [...] master ASM file to use " .INCLUDE"

I see this pattern regularly in cc65 projects - and every time I wonder where the point is. Don't we have a linker to combine object files?

**Comment by spiro-trikaliotis** [comment]
@oliverschmidt, not everyone is used to linkers. Especially in the retro szene, there are many people who never have had to deal with a linker.
Furthermore, there are many compilers and assemblers that do not even support a linker.

**Comment by mrdudz** [comment]
does ANY other 6502 assembler have one? :)

**Comment by oliverschmidt** [comment]
@spiro-trikaliotis: Thanks for Your feedback. So there's basically no point :-)

**Comment by spiro-trikaliotis** [comment]
@oliverschmidt, strictly speaking, you are right. But: People tend to use what they know.
@mrdudz, I remember some adds in some magazin (64'er? Happy Computer?) on a assembler with a linker. I remember it so good because at that time, I did not even know what a linker is. Once I read it, I did not know why one should use one.

Times have changed since then. ;)

**Comment by groessler** [comment]
> .export _foo
> _foo: .byte 0
> 
> extern unsigned char _foo;
> 
> isnt this described in the docs somewhere? _shrug_

isn't this wrong?
it should be
extern unsigned char foo;
shouldn't it?

**Comment by mrdudz** [comment]
correct, oops :=)

**Comment by peteym5** [comment]
I am use to direct 6502 assembly and only started to use compiled languages to help deal with some extra work load. I am also providing some extra samples of what I do here and link to my Facebook group. Are there any forums or groups that I can look stuff up, research, and ask questions if I need to?
I am programming games for the Atari 8-bit and not difficult to port to 5200. I may be assisting with 8 bit unity engine so I can port to additional systems.

**Comment by groessler** [comment]
> does ANY other 6502 assembler have one? :)

I think MAE had it back then. Don't find references on the internet right now, but I had it back then. Need to dig out the disk and docs....

**Comment by groessler** [comment]
> I think MAE had it back then.

And, yes, I found that strange at that time and almost never used it :-)
Only later when working on PCs I had learned that they are a "good thing" :-)

**Comment by polluks** [comment]
@mrdudz vasm with vlink
