### ISSUE TITLE
[info] Can I legally use stdint.h (as is) in the C cross-compiler LCC1802 for the RCA 1802?

### ISSUE THREAD

**Issue by Fabrizio-Caruso** [cc65/cc65#1033]
I would like to integrate CC65 stdint.h into LCC1802 (https://github.com/bill2009/lcc1802), which is a C cross-compiler for COSMAC RCA 1802 CPU. 

Can I do it legally by just keeping the comments that state the origin of the file?

**Comment by oliverschmidt** [comment]
I'm neither able nor interested to give legal advice. The only thing I can tell you is that won't hunt you down for doing so.

**Comment by Fabrizio-Caruso** [comment]
Thanks!
