### ISSUE TITLE
[info/bug?] What is the purpose of JOY_FIRE vs JOY_BTN_1? JOY_FIRE is not defined on all targets with JOY_BTN_1

### ISSUE THREAD

**Issue by Fabrizio-Caruso** [cc65/cc65#1036]
What is the purpose of JOY_FIRE vs JOY_BTN_1? 
JOY_FIRE is not defined on all targets with JOY_BTN_1.
It seems to be an alias for JOY_BTN_1 but not on all targets.
Is this a bug? A left-over from an old name?

**Comment by oliverschmidt** [comment]
There have been lots of discussions around the joystick interface. My take is that JOY_FIRE is present where the (ususal/default/only) joystick has a button that is clearly the fire button like this: https://en.wikipedia.org/wiki/The_Arcade_(joystick)#/media/File:The_Arcade_Turbo_Joystick.jpg

And that it isn't present where the (ususal/default/only) joystick is like this: https://asset.conrad.com/media10/isa/160267/c1/-/en/1893215_RB_01_FB/image.jpg

**Comment by Fabrizio-Caruso** [comment]
What should one then use to have portable code?
I would prefer JOY_FIRE to refer to the default or first fire key. It should compile for any target. I fear this is what it was meant to be in the beginning but someone forgot to provide it for one or two targets.

**Comment by oliverschmidt** [comment]
> What should one then use to have portable code?

Of course JOY_BTN_1.

> I would prefer JOY_FIRE to refer to the default or first fire key. It should compile for any target.

```
#ifndef JOY_FIRE
#define JOY_FIRE JOY_BTN_1
#endif
```

> I fear this is what it was meant to be in the beginning but someone forgot to provide it for one or two targets.

Hm, I thought I invested quite some effort in explaining to you why this isn't the case :-(

**Comment by Fabrizio-Caruso** [comment]
Thanks! Sorry I was thinking that BTN_1 only made sense if there are more buttons. I got it wrong.
