### ISSUE TITLE
[info] What is "Duplicate external identifier"? How can I silence it?

### ISSUE THREAD

**Issue by Fabrizio-Caruso** [cc65/cc65#1038]
I am getting the error:
Duplicate external identifier: '_loop'

Is this cause by declaring the same extern variable multiple times? 

From the CC65 source code 
https://github.com/cc65/cc65/blob/master/src/ld65/exports.c#L484
I see it could be silenced but I do not find the option to do it.

**Comment by oliverschmidt** [comment]
> Is this cause by declaring the same extern variable multiple times?

I think it's caused by **defining** the same variable multiple times.

> I see it could be silenced but I do not find the option to do it.

--allow-multiple-definition

BTW: I think a mail to the cc65 mailing list is a way more appropriate channel for questions about cc65 usage.

**Comment by greg-king5** [comment]
At least two of the source files for that program _exported_ the name "_loop".  That underscore suggests that they're the name "loop" in C sources.  If that's true, then you need to determine
1. if they're supposed to be local to each source file (then make them `static`);
2. or, if they're supposed to be shared by the files (then make all but one of them `extern`).

The Assembly equivalents are
1. don't `.export` the name "_loop";
2. or, `.export` one of them, and `.import` the others.

**Comment by Fabrizio-Caruso** [comment]
@greg-king5 I do not understand what you mean by making all but one extern. 
How can I debug and find where the double definition is?

I have this error:
ld65: Error: Duplicate external identifier: '_head_image_ptr'

I do only define `head_image_ptr `in one file and I always declare it as `extern `in the other files that include the file (`snake.h`) with the definition:
```
$ grep -r head_image_ptr ./*
./demos/snake/move_snake.c:extern Image* head_image_ptr;
./demos/snake/move_snake.c:            head_image_ptr = &HORIZONTAL_HEAD_IMAGE;
./demos/snake/move_snake.c:            head_image_ptr = &HORIZONTAL_HEAD_IMAGE;
./demos/snake/move_snake.c:            head_image_ptr = &VERTICAL_HEAD_IMAGE;
./demos/snake/move_snake.c:            head_image_ptr = &VERTICAL_HEAD_IMAGE;
./demos/snake/snake.c:extern Image* head_image_ptr;
./demos/snake/snake.c:    _XLIB_DRAW(snake[snake_head].x,snake[snake_head].y,head_image_ptr);
./demos/snake/snake.c:    head_image_ptr = &HORIZONTAL_HEAD_IMAGE;
./demos/snake/snake.h:Image *head_image_ptr;
```

**Comment by polluks** [comment]
Maybe it's a makefile rule like `cl65 snake.c snake.c`. Pretty sure it's not an issue.

**Comment by Fabrizio-Caruso** [comment]
@polluks @greg-king5 it is not an issue. It is an error on my side... Sorry guys.
I think the problem is that I am defining instead of declaring in header files...

**Comment by Fabrizio-Caruso** [comment]
@polluks @greg-king5 "Problem" fixed by avoiding definitions in .h header files. This is a stupid error. Sorry.
