### ISSUE TITLE
Building info-page for ca65 fails

### ISSUE THREAD

**Issue by Zirias** [cc65/cc65#1039]
I tried building the info pages on FreeBSD, using linuxdoc-tools-0.9.80 and texinfo-6.7_3,1. `makeinfo` fails on the output created by `linuxdoc` for `ca65.sgml` in the section 5.5 Available operators with all kinds of error messages about `@item` in a wrong context.

Filling all empty table cells in `ca65.sgml` with an explicit `&nbsp;` solves this problem, and the HTML output sill looks fine. But even then, the resulting info page is unreadable, it looks like this:

![image](https://user-images.githubusercontent.com/5891057/83340007-a21f9780-a2d3-11ea-8d14-5bfa5c8bce4e.png)

**Comment by oliverschmidt** [comment]
CI builds the info pages still fine...

**Comment by polluks** [comment]
Do you know which versions CI used? Just for the record.

**Comment by spiro-trikaliotis** [comment]
I can confirm this issue for Debian testing: https://build.opensuse.org/package/live_build_log/home:strik/cc65/Debian_Testing/x86_64 and Debian Unstable: https://build.opensuse.org/package/live_build_log/home:strik/cc65/Debian_Unstable/x86_64

With Debian Stable, it works: https://build.opensuse.org/package/live_build_log/home:strik/cc65/Debian_10/x86_64

So, it seems to be an issue with newer linuxdoc versions.

**Comment by oliverschmidt** [comment]
Thank for the info ;-) , reopening...

**Comment by greg-king5** [comment]
> I can confirm this issue for Debian testing: https://build.opensuse.org/package/live_build_log/home:strik/cc65/Debian_Testing/x86_64
> 
> With Debian Stable, it works: https://build.opensuse.org/package/live_build_log/home:strik/cc65/Debian_10/x86_64
> 
> So, it seems to be an issue with newer linuxdoc versions.

It might be that a newer version of makeinfo is less tolerant of the Linuxdoc bug.

**Comment by spiro-trikaliotis** [comment]
I just tried in on Debian Unstable:
It complains on the lines:
||~@
(ca65.sgml lines 625, 638, ...)

which are used as separators in the table for "available operators, sorted by precedence" between the precedence groups.

Unfortunately, changing this to something like
@<hline>
(in the previous line) removes the empty line completely. For this, I can just omit the <hline>.
Unfortunately, this is what was recommended int https://tldp.org/HOWTO/pdf/Linuxdoc-Reference.pdf.

The only solution I found so far is to replace it by:
.|.|~@

See the attached patch.

But this does not look good, as it creates "almost empty" lines that contain "." in the rows.
[linuxdoc-workaround.diff.gz](https://github.com/cc65/cc65/files/4932183/linuxdoc-workaround.diff.gz)

**Comment by oliverschmidt** [comment]
Can you please post an HTML file or screenshot? I'm not able to follow you :-(

**Comment by spiro-trikaliotis** [comment]
See attached. ca65_original.html is the output of the git, ca65_hline.html is adding the <hline> tag (which does nothing), and ca65_dotpipe.html is with the .|.|~@ pattern:
[ca65_html.zip](https://github.com/cc65/cc65/files/4932302/ca65_html.zip)

It's the table in section 5.5  After "built-in string functions" (precedence 0), you have an empty line in the original. This is not present in the _hline variant, and it is not completely empty in the .|.|~@ variant.

**Comment by oliverschmidt** [comment]
Thanks, the content of that zip was exactly what I was looking for :-)

As far as I see the empty lines "only" group the precedence. But that's given on every line anyhow. I consider the empty lines as expendable.

In case those dividers are considered obligatory: Is it possible to e.g. place a <hr> inside the three columns?

BTW: At the end of the table there's so ugly artifact rendered by Chrome. It would be nice to get rid of that when touching this area...

**Comment by spiro-trikaliotis** [comment]
The artifact is also available in Firefox. I already found it, it can be removed be removing the @<hline> in the last line. That's the lesser problem.

I found the solution for the other problem: Instead of 
||~@
we can use
~|~|~@

I will prepare a PR.

**Comment by spiro-trikaliotis** [comment]
@Zirias , I forgot about your output problem. At least here, on Debian, it looks ... well, not "readable", but at least better than on your machine:
![ca65 info](https://user-images.githubusercontent.com/5121168/87710793-8a7a7080-c7a6-11ea-91c6-99a35826723e.png)

The problem with info pages and tables is known, there is nothing we can do on it.

Are you running it on FreeBSD? You might have another toolchain than Debian which causes this problem.

And, I must admit that you already wrote the solution, explicitly adding the spaces. I only looked at this problem and forgot the previous one.

So, do you consider the bug fixed, or is it only partially fixed?

**Comment by Zirias** [comment]
@spiro-trikaliotis thanks for asking (and thanks for creating a sane patch). The patch is simple enough and builds fine with linuxdoc-tools 0.9.82. Unfortunately, the resulting display on FreeBSD is still like in my initial screenshot here. Packages that might be relevant are:
sgmls-1.1.91
texinfo-6.7
jade-1.2.1
groff-1.22.4

Anyways, I'm not sure a broken display of one info page is really a bug. It's a good thing the local patch can be removed from the FreeBSD package of cc65 in the next version!
