### ISSUE TITLE
Unresolved Externals.

### ISSUE THREAD

**Issue by peteym5** [cc65/cc65#1044]
I am getting unresolved externals. Not sure why. Tried several different things. Compiling on a Windows PC Command Prompt. Target Atari 8-bit computer. 

**in ASM**:
```asm
  .org $A400
_CHARSET_GAME:
  .incbin         "MINDFIELD.FNT"
      _CHARSET_GAME_HI = >_CHARSET_GAME
      _CHARSET_TITLE_HI = >_CHARSET_TITLE
      .export _CHARSET_GAME
      .export _CHARSET_TITLE
      .export _CHARSET_GAME_HI
      .export _CHARSET_TITLE_HI
```
in **C** program, have
```c
extern unsigned char  CHARSET_GAME;
extern unsigned char  CHARSET_TITLE;
extern unsigned char  CHARSET_GAME_HI;
extern unsigned char  CHARSET_TITLE_HI;        
```

**Comment by mrdudz** [comment]
try putting the .export lines before the others

**Comment by dmsc** [comment]
Hi!

> I am getting unresolved externals. Not sure why. Tried several different things. Compiling on a Windows PC Command Prompt. Target Atari 8-bit computer.
> 
> **in ASM**
> .org $A400
> _CHARSET_GAME:
> .incbin "MINDFIELD.FNT"
> _CHARSET_GAME_HI = >_CHARSET_GAME
> _CHARSET_TITLE_HI = >_CHARSET_TITLE
> .export _CHARSET_GAME
> .export _CHARSET_TITLE

This symbol is not defined in your example.

> .export _CHARSET_GAME_HI
> .export _CHARSET_TITLE_HI
> 


> in **C** program have
> extern unsigned char CHARSET_GAME;
> extern unsigned char CHARSET_TITLE;
> extern unsigned char CHARSET_GAME_HI;
> extern unsigned char CHARSET_TITLE_HI;

This works:

b1044-asm.s:
```asm
        .org $A400
_CHARSET_GAME:

; .incbin "MINDFIELD.FNT"
.byte 1,2,3

_CHARSET_GAME_HI = >_CHARSET_GAME
_CHARSET_TITLE_HI = >_CHARSET_TITLE

.export _CHARSET_GAME
.export _CHARSET_TITLE
.export _CHARSET_GAME_HI
.export _CHARSET_TITLE_HI

_CHARSET_TITLE:

.byte 4,5
```

b1044-c.c
```c
extern unsigned char CHARSET_GAME;
extern unsigned char CHARSET_TITLE;
extern unsigned char CHARSET_GAME_HI;
extern unsigned char CHARSET_TITLE_HI;

int main()
{
    CHARSET_GAME = 1;
    CHARSET_TITLE = 2;
    CHARSET_GAME_HI = 3;
    CHARSET_TITLE_HI = 4;
}
```

Compile with:
```
cl65 -tatari -o xx b1044-asm.s b1044-c.c
```

**Comment by polluks** [comment]
@peteym5 Better use the mailing list next time https://cc65.github.io/mailing-lists.html

**Comment by greg-king5** [comment]
> `  .org $A400`

`.org` doesn't do, in ca65, what it does in other assemblers.  It doesn't tell ca65 where to put some data.  Instead, it tells ca65 where _**to think**_ that the data will be put by something else (such as ld65 or the program itself).

The usual ca65 way to do what you want is to place the data in its own segment.  Then, use a configure file to tell ld65 where to put that segment:
```asm
.segment "GAMEFONT"
_CHARSET_GAME:
  .incbin  "MINDFIELD.FNT"

.segment "TITLEFONT"
_CHARSET_TITLE:
  .incbin  "title.fnt"

.code

_CHARSET_GAME_HI := >_CHARSET_GAME
_CHARSET_TITLE_HI := >_CHARSET_TITLE

      .export _CHARSET_GAME
      .export _CHARSET_TITLE
      .export _CHARSET_GAME_HI
      .export _CHARSET_TITLE_HI
```
You would put, somewhere in your configure file, some lines that look something like these:
```ini
MEMORY {
    ....
    GAMEFONT: start = $A400, size = $ .... ;
    TITLEFONT: start = $ ... , size = $ .... ;
    ....
}
SEGMENTS {
    ....
    GAMEFONT: load = GAMEFONT, type = ro;
    TITLEFONT: load = TITLEFONT, type = ro;
    ....
}
```

**Comment by oliverschmidt** [comment]
Hm, the OP hasn't reacted in any way on the help received by several members of the cc65 community (thanks!) - closing...

BTW: @polluks is of course right.
