### ISSUE TITLE
Postincrementing is optimized wrong in some cases

### ISSUE THREAD

**Issue by mrdudz** [cc65/cc65#1045]
In my project the following line of code is optimized wrong... see how the readpos post increment turns into a preincrement:

```c
#define FILECOPY_BLOCKADDR 0x04c8
unsigned short readcnt;
unsigned char readpos;
;
; ((u8*)FILECOPY_BLOCKADDR)[readcnt++] = ((u8*)0xd702)[readpos++];
;
L0272:
    ; load readcount to a/x
    lda     _readcnt
    ldx     _readcnt+1
    ; save a/x
    sta     regsave
    stx     regsave+1
    ; inc a/x by one
    jsr     incax1
    ; store incremented value in readcount
    sta     _readcnt
    stx     _readcnt+1

    ; add saved value to 0x04c8 and store in sreg
    lda     #$C8
    clc
    adc     regsave
    sta     sreg
    lda     #$04
    adc     regsave+1
    sta     sreg+1
    
    ; increment readpos
    inc     _readpos
    ; add readpos to 0xd702 and store in ptr1
    ldx     #$D7
    lda     #$02
    clc
    adc     _readpos
    bcc     L0333
    inx
L0333:    
    sta     ptr1
    stx     ptr1+1
    
    ldy     #$00
    lda     (ptr1),y
    sta     (sreg),y
```
i compile using the following options:

```
DEFS=--add-source
DEFS+=--local-strings
OPTS=-Or
OPTS+=-Oi
OPTS+=-Os
OPTS+=--codesize 180
OPTS+=-W const-comparison,no-effect,struct-param,unknown-pragma,unused-label,unused-param,unused-var
```

leaving out the --codesize option "fixes" it, ie that is the source of the wrong optimization

Since i know for sure that it worked like this a while ago, i will start binsearching for the offending commit.... stay tuned :)

**Comment by mrdudz** [comment]
found
~~~
$ git bisect bad
767f093ff86604314a9ee42c25842c79905f3248 is the first bad commit
commit 767f093ff86604314a9ee42c25842c79905f3248
Author: Lauri Kasanen <cand@gmx.com>
Date:   Sat May 6 13:20:55 2017 +0300

    Add fast path for char postinc

 src/cc65/expr.c | 37 +++++++++++++++++++++++--------------
 1 file changed, 23 insertions(+), 14 deletions(-)
~~~
guess that needs some fixing then :)

**Comment by clbr** [comment]
That does not look at all like what the codegen commit produces, so I think it's some optimization pass that has the bug. There was some option to output the code between every opt pass, try that.

**Comment by mrdudz** [comment]
awesome! 
i will make a test program that checks all kind of postincrementing that fails atm :) (after dinner.... =P)

**Comment by mrdudz** [comment]
mmmmh i don't see any option like that... any hints? :)

**Comment by mrdudz** [comment]
.... and --disable-opt OptStackOps makes the problem go away (and results in quite surprisingly different code).

what now? :)

**Comment by mrdudz** [comment]
oh and, #784 actually looks like a symptom of the same problem. we should really try to fix this. @acqn ? :)

**Comment by mrdudz** [comment]
.... and the option to show the code for each optimizer step is --debug-opt-output

is there a good reason for why this one does not appear in the --help output? @oliverschmidt  ? else i will add it :)

**Comment by oliverschmidt** [comment]
Given that cc65 is open source I certainly don't see any point whatsoever in hiding a cmdline option from the user. From that perspective I'd appreciate the doc addition in question.

**Comment by mrdudz** [comment]
ok, done :)

**Comment by oliverschmidt** [comment]
As far as I see https://github.com/cc65/cc65/blob/master/doc/cc65.sgml asks to be adjusted accordingly.

**Comment by mrdudz** [comment]
interestingly... it was already there. adjusted the --help output to match what was already in the docs instead :)

**Comment by oliverschmidt** [comment]
Ah, now I see - thanks for pointing out!

**Comment by polluks** [comment]
By the way should we change to the SGML's short form? `<tt/typewriter font/`

**Comment by mrdudz** [comment]
the what?

**Comment by polluks** [comment]
SGML is more flexible than HTML, we could save all `</tt>`.

**Comment by mrdudz** [comment]
get cracking! (not sure how this belongs here...)

**Comment by oliverschmidt** [comment]
> what now? :)

So https://github.com/cc65/cc65/commit/767f093ff86604314a9ee42c25842c79905f3248 changed the code generator in a way that makes the code optimizer fail - is that a correct description of the issue?

In that case I only see the two obvious ways to move forward:

1. Adjust the code optimizer to work with the changed code generator
2. Revert the code generator to the previous state

Unfortunately I personally can't assess the drawbacks of 2.) well as the commit log in question only says "Add fast path for char postinc".

**Comment by mrdudz** [comment]
> So 767f093 changed the code generator in a way that makes the code optimizer fail - is that a correct description of the issue?

not really... it only - under certain conditions - exposes a bug in OptStackOps.... the bug is unrelated and will get triggered also by other things. see #784

**Comment by clbr** [comment]
Right, there are several other bugs open on the same OptStackOps pass. Reverting my char commit would hide this specific bug, but it would also decrease generated code speed/increase size a lot.

**Comment by mrdudz** [comment]
@acqn apparently worked a bit on this, perhaps he can chime in?

For a temporary "fix" it might be useful to add a pragma to enable/disable individual optimizer steps - that should at least help to not screw up existing code too much by disabling something globally (eg my project will no more work when disabling OptStackOps - the binary is becoming too large).

**Comment by clbr** [comment]
You could put that func into its own file, and compile just that file with the pass disabled? Make lets you add per-file flags.

**Comment by mrdudz** [comment]
sure - but that gets a bit messy when you have more than a few files (~100 in my case). it would also make it easier to see what happens when its defined in the sourcefile on top of the affected code.

**Comment by oliverschmidt** [comment]
> Right, there are several other bugs open on the same OptStackOps pass.

Thanks, now even I see ;-)

> For a temporary "fix" it might be useful to add a pragma to enable/disable individual optimizer steps

I'd be willing to merge a change doing so. I'd also be willing to merge a change doing this only for OptStackOps.

But I'd of course prefer very much to merge an OptStackOps fix (@acqn: hint hint).

**Comment by mrdudz** [comment]
cool, since godbolt has made cc65 support public now, here is the link: https://godbolt.org/z/tQeVJk :)

**Comment by oliverschmidt** [comment]
Ah, so I'm not the only one who didn't know about the cc65 support in the Compiler Explorer ;-)

"Now" isn't exactly true btw: https://github.com/compiler-explorer/compiler-explorer/commit/06b8f51edbdf0271dd0df4ba03f74572911996d0

**Comment by mrdudz** [comment]
yeah, but it wasnt available on the website for the general public until recently

**Comment by acqn** [comment]
Indeed I made a fix for the postinc bug but then I retracted it since it revealed some other bugs in the optimizers that also need be fixed. Then I stepped further in improving the optimizers and made quite some changes. The original fix now crashes the compiler in tests when merged with the current codebase and the new fixes depend on some other stuff that I haven't fininished (and no way to finish anytime soon). So, do you want some seemingly random piles of commits that happen to fix this, or an updated hackish fix dedicated to this?

**Comment by mrdudz** [comment]
I much prefer a proper fix. Preliminary dirty hacks tend to stay forever :)

**Comment by oliverschmidt** [comment]
> I much prefer a proper fix. Preliminary dirty hacks tend to stay forever :)

1. I interpret _"So, do you want some seemingly random piles of commits that happen to fix this, or an updated hackish fix dedicated to this?"_ as a "proper fix" not being a viable option. So I can't follow you in much prefering it.

2. I interpret https://github.com/cc65/cc65/pull/1053 as the decision already made.

@mrdudz: Can you please validate that https://github.com/cc65/cc65/pull/1053 fixes the issue at hand? The PR in in question puts a question mark behind the reference.

**Comment by mrdudz** [comment]
I wasnt exactly sure how to interpret it, so you may take it as a more general statement =) I'll check (perhaps not today though)

**Comment by oliverschmidt** [comment]
> I wasnt exactly sure how to interpret it,

Me too ;-)

> I'll check (perhaps not today though)

Thanks :-)

**Comment by mrdudz** [comment]
checked, see my comment in #1053

**Comment by oliverschmidt** [comment]
Great!

**Comment by oliverschmidt** [comment]
Fixed with https://github.com/cc65/cc65/pull/1053.
