### ISSUE TITLE
[feature request] char bitfields

### ISSUE THREAD

**Issue by jmr** [cc65/cc65#1047]
Given the importance of keeping data as small as possible, it would be nice if char bitfields were supported, even though they are an extension. [Most](https://godbolt.org/z/ASMuuU) [compilers](https://godbolt.org/z/CyjbA6) [support](https://godbolt.org/z/y-9PjW) [them](https://godbolt.org/z/c7XMKd).

```
struct s {
    unsigned char x : 2;
    unsigned char y : 3;
};

int f(void) { return sizeof(struct s); }
```

[This currently produces](https://godbolt.org/z/o5Es6Y):
```
<source>(2): Error: Bit-field has invalid type
<source>(3): Error: Bit-field has invalid type
```

**Comment by jmr** [comment]
I'm working on this. It doesn't look too difficult. The compiler is really nice and understandable.

**Comment by oliverschmidt** [comment]
Hm, are you aware that changing the code into
```
struct s {
    unsigned int x : 2;
    unsigned int y : 3;
};

int f(void) { return sizeof(struct s); }
```
gives you exactly what you desire?

**Comment by jmr** [comment]
Now I know that, but I didn't when I filed the bug.

It would still be better to support char so existing code can work without modification. C99 also requires `_Bool : 1` bit-fields to be supported, but that doesn't currently work since char bit-fields aren't supported and `_Bool` is `typedef`ed to `unsigned char`.
