### ISSUE TITLE
[feature request] packed enums

### ISSUE THREAD

**Issue by jmr** [cc65/cc65#1050]
Because of the "use the shortest data type and preferably unsigned" recommendation, it would be nice if enums did this.

```
enum e { k };
int f(void) { return sizeof(enum e); }
```

[`sizeof(enum e)` is currently 2](https://godbolt.org/z/bmg8YY). 

[gcc and clang support `-fshort-enums`](https://godbolt.org/z/FwMERm) and `__attribute__((__packed__))` to make it 1.

**Comment by acqn** [comment]
With PR #1121 merged, cc65 now always "pack" the enum variables by using the smallest integral underlying type preferring unsigned. Would we consider this resolved?

**Comment by jmr** [comment]
I consider it fixed. I just added a test case in #1151 .
