### ISSUE TITLE
bit-fields inconsistently packed

### ISSUE THREAD

**Issue by jmr** [cc65/cc65#1054]
This isn't necessarily a bug, but is a bit strange. Bit-fields are padded to 2 bytes when another field comes after them, but only one byte when the last field in a struct.
```c
struct s {
  unsigned int x : 4;
};

struct t {
  unsigned int x : 4;
  unsigned int y;
};

int sizeof_s(void) { return sizeof(struct s); }
int sizeof_t(void) { return sizeof(struct t); }
```
[`sizeof(struct s)` is 1, but `sizeof(struct t)` is 4, not 3.](https://godbolt.org/z/qJQobe)

**Comment by oliverschmidt** [comment]
I second that discrepancy is strange. However, I'd rather state:

`sizeof(struct t)` is 4, but `sizeof(struct s)` is 1, not 2.

**Comment by jmr** [comment]
I can agree with that, too. I was thinking things should be packed by default since there are no alignment requirements, but it's really an orthogonal issue.

**Comment by oliverschmidt** [comment]
After checking what compilers for "usual" targets do when called with `-fpack-struct` I now fully agree with you that

* sizeof(struct s) is 1 
* sizeof(struct t) is 3

is the result to be expected. I now consider this issue a bug and appreciate that you provided a fix with https://github.com/cc65/cc65/pull/1055.

**Comment by jmr** [comment]
This is ready to merge. I had planned on #1063 being merged first, then updating this with the new test results, but it's not necessary to do in that order.

**Comment by oliverschmidt** [comment]
> This is ready to merge.

Now you lost me. It seems that your comment is on an issue, not a pull request.

**Comment by jmr** [comment]
Sorry, I put the comment here by accident instead of on #1058 . Comment updated.
