### ISSUE TITLE
CPYRIGHT.LCC is missing

### ISSUE THREAD

**Issue by jmr** [cc65/cc65#1061]
Many test files reference `CPYRIGHT.LCC`, but it looks like it wasn't added in ca30082 when most of the tests were added.

https://github.com/cc65/cc65/blob/master/test/ref/8q.c#L4

**Comment by polluks** [comment]
https://raw.githubusercontent.com/drh/lcc/master/CPYRIGHT

**Comment by oliverschmidt** [comment]
Fixed with https://github.com/cc65/cc65/commit/5277ea0b73c75ce2dae034dff3c1f7a325f2563d.
