### ISSUE TITLE
Placing Arrays into zero page?

### ISSUE THREAD

**Issue by WartyMN** [cc65/cc65#1062]
I don't know that this is possible, but I've tried all kinds of things, and before I give up I thought I better ask. 

**Goal:** reduce code size
**Background:** I have arrays of structs, 9 for monsters, 9 for treasure, 18 for player's inventory. I have moved some singleton pointers in ZP (pointer to player object, pointer to level object, etc.), and they have saved quite a few bytes. I'd like to move 36 pointers, in 3 arrays, into ZP. I can't quite get it working. 
**How I had the arrays set up originally:**
Object* global_level_monsters[LEVEL_MAX_MONSTERS];
Object* global_level_objects[LEVEL_MAX_OBJECTS];
Object* global_player_objects[PLAYER_MAX_OBJECTS];
**Typical usage example**
		this_object = global_level_monsters[i];
That actually requires quite a bit of 6502 instructions to pull off. ZP-based indirect addressing can really save a lot of bytes here. 

**Setup:** 
Target: C128
memory config (relevant bits):
	ZP_LK1:   file = "", define = yes, start = $001C,                   size = $0073;
    ZEROPAGE_LK1:			load = ZP_LK1,   type = zp, define = yes;

**ZP globals as defined in ASM and imported to .c:**
.segment "ZEROPAGE_LK1" : zeropage

_zp_index_lookup:	;// 0x1c.  way to get an "index" to a ZP "fake" array: do this[i] to get i*2
	;//.byte 0,2,4,6,8,10,12,14,16,18,20,22,24,26,28,30,32,34
	.res 18,$00
_zp_global_level_monsters:	;// 0x2e
	.res 18,$00
_zp_global_level_objects:	;// 0x40
	.res 18,$00
_zp_global_player_objects:	;// 0x52
	.res 36,$00
_global_player:
	.res 2	;// 2 bytes for the pointer to the player object itself
_global_player_sub:
	.res 2	;// 2 bytes for the pointer to the Player class
_global_level:
	.res 2	;// 2 bytes for the pointer to the Level

(ignore the _zp_index_lookup for now)

**How imported to .c:**

extern Object* global_player;
#pragma zpsym ("global_player");

extern Object* zp_global_level_monsters;
#pragma zpsym ("zp_global_level_monsters");

This works great for the global_player, but less so for zp_global_level_monsters, because I can't use it as an array of pointers. If I try to define zp_global_level_monsters as an array in .c, it won't get matched up against the imported ZP label, and will end up getting defined in absolute (non-zp) space. 

I also tried not reserving the space in ASM, and instead defining it in the .c, something like this:
#pragma bss-name (push,"ZEROPAGE_LK1")
Object* zp_global_level_monsters[LEVEL_MAX_MONSTERS];
#pragma bss-name (pop)
#pragma zpsym ("zp_global_level_monsters"); 

Tried various variants here, no luck. Various reasons. 

I can do some contortions with macro definitions, and get the addresses into the right spots in ZP, but the contortions pretty much eat any savings. eg:
#define ZP_INDEX_LOOKUP		0x1C	// 18 bytes for 18 slots for pointer math (0,2,4,6, etc)
#define global_zp_array_index(index)		*(char*)(ZP_INDEX_LOOKUP + (index))
#define ZP_LEVEL_MONSTERS	0x2E	// 18 bytes for 9 monster (object) pointers
#define global_zp_level_monsters(index)		*(Object**)(ZP_LEVEL_MONSTERS + (index))
Usage example:
global_zp_level_monsters(global_zp_array_index(i)) 
as replacement for:
global_level_monsters[i]

Am I missing anything obvious? 

Err, and I'm trying too avoid completely redesigning to use structs of arrays, no function parameters, etc. But we'll see how desperate I get here for a few more bytes...

**Comment by oliverschmidt** [comment]
This might be something better asked on the cc65 Development mailing list (https://cc65.github.io/mailing-lists.html#cc65-devel).

**Comment by WartyMN** [comment]
I'll cross-post there.
