### ISSUE TITLE
[bug] Latest CC65 build breaks both my games (Cross Chase and Cross Shoot, both built with CrossLib)

### ISSUE THREAD

**Issue by Fabrizio-Caruso** [cc65/cc65#1071]
The problem occurs with any target (tested C16, C64, Vic20) and with both games.
The binaries are fine if compiled with previous versions.

My library and games are found in:
https://github.com/Fabrizio-Caruso/CROSS-CHASE/blob/master/docs/SNAPSHOTS.md
They are compiled with:
make c16 (for Cross Chase)
make c16 -f Makefile.Shoot (for Cross Shoot)

The issue is that the enemies do not move. So it looks like either the random number generator is wrong or some variables are not initialized correctly.

I have included OK and KO versions (C16 target) with the latest nightly build as today (2020/07/03) and a previous working snapshot.

[CrossLibExamples.zip](https://github.com/cc65/cc65/files/4869248/CrossLibExamples.zip)

**Comment by mrdudz** [comment]
You might want to strip it down to an actual Testcase. It would also help if you could name the exact GIT commit that broke it (use git bisect)

**Comment by Zirias** [comment]
Just found this by accident, sharing my thoughts:

From the description, it's unclear whether this is indeed a problem with the compiler or some hidden UB in your code that wasn't triggered with previous versions. Given the size of your code, it would be nice if you could analyze that, as you're the one who knows your own code best.

As you seem to have an idea what's causing the problem, I would suggest that you compile to assembly and look at the assembly code of the functions you suspect to be the cause. It might also help to compare with the assembly generated by earlier versions of cc65. Maybe it's obvious at first glance that way .. if not, vice has a nice monitor for debugging :)

**Comment by Fabrizio-Caruso** [comment]
@Zris my game works fine with 12 other cross compilers. This is not a mathematical proof of correctness but it makes a bug in my code unlikely. It is still possible though.
I am not very familiar with Assembly. I code in C to cover all 8-bit architectures. My knowledge of any specific Assembly is minimal.

**Comment by Fabrizio-Caruso** [comment]
@mrdudz  It is not clear how to find the bad commit. With other cross compilers I just use different builds but CC65 only provides the latest one. I have asked to provide more than just one build but my request was turned down.
How do I know which latest commit has the working snapshot I have on my computer?

**Comment by mrdudz** [comment]
you use GIT for that and have to build be able to build the compiler yourself. "git bisect" helps you with finding the exact commit that broke it

**Comment by mrdudz** [comment]
Oh and as said - the first step would be to strip down the code to something smallish that fails on compiler and works on the other. Once you have that, i am willing to jump in and do the bisect to find out what exactly broke it.

**Comment by jmr** [comment]
I'll try to do the bisect tonight. I'm a little worried my struct layout changes (#1055 #1066 ) could have broken something.

@Fabrizio-Caruso What does `cc65 --version` say for the working and broken versions?

**Comment by oliverschmidt** [comment]
@mrdudz: Thanks for your offer!

**Comment by acqn** [comment]
I won't be surprised if it's the compiler. There were more than a dozen of bugfixes held back in my repository. However, it would be helpful if you could find out which piece of the code of your game is affected.

**Comment by Fabrizio-Caruso** [comment]
@jmr 
KO version: cl65.exe V2.18 - Git 0f8b587

OK version: cl65.exe V2.18 - Git 8b5a2f1

**Comment by acqn** [comment]
For Cross Chase I think it's ghost.c that gets miscompiled. I'll investigate later on.

**Comment by jmr** [comment]
@Fabrizio-Caruso can you make an automated test case for sim65 that prints PASS/FAIL or returns 0/1 or something? That would make it easier. If not, I can try running the whole game, but I'm not sure I'll figure it out.

**Comment by acqn** [comment]
I've found the cause: the same old operand tracking flaw when Opt_tossubax is involved. It gets triggered with the changes in my recently pushed 517d2a0.
A quick fix that prevents any similar issues in this family Opt_tos can be implemented, though that could create slightly slower code with the current optimizer steps.

The universal fix depends on the same changes that held other fixes back. Nonetheless it isn't a problem if those were applied.

**Comment by oliverschmidt** [comment]
Thanks for the super-quick analysis :-)

That type of bug triggered in faulty code triggered by innocent code is unfortunately not as seldom as one would hope for :-( I guess that's why unit tests have been invented...

From what you say it seems to me that this "quick fix" potentially causing somewhat slower code would be desirable. From your contributions so far I deduct that we don't have to fear that you'll forget to remove it again in case that "universal fix" should become available at some point.

**Comment by acqn** [comment]
I decided to fix the issue in a different way that is eaiser to merge with other "intermediate" changes. I tested Cross Chase with the fix and it looks like to be working, but can't test Cross Shoot for now.

**Comment by Fabrizio-Caruso** [comment]
@acqn If it is fixed for one game, it is most probably fixed for the other.
In case you want to build Cross Shoot, you just need to do  make <target> -f Makefile.Shoot, with target vic20, c64 or c16

**Comment by oliverschmidt** [comment]
> [...] It might take more time.

Thanks for the intermediate feedback.

**Comment by mrdudz** [comment]
@Fabrizio-Caruso will you *please* still try to create a stripped down test case so we can make sure to include a test in the repo and not break the same thing again?

**Comment by Fabrizio-Caruso** [comment]
@mrdudz I can try but I don't know what is failing.
@acqn Could you please point me to the failing expression in ghost.c?

**Comment by oliverschmidt** [comment]
> will you please still try to create a stripped down test case

Full ACK.

> I can try but I don't know what is failing.

I've done that with "something" failing in Contiki. So I know what I'm talking about when I ask you to do it...

As far as I understand it's a problem with the optimizer. So you can use pragmas to turn optimization on/off on a per-function level in order to isolate the function that makes the optimizer fail. Then you have to create a main program calling that function and checking if it worked as expected. Finally you try to remove as much code as possible from the function in question while still retaining the issue.

Good luck, Oliver

**Comment by acqn** [comment]
> 
> 
> @mrdudz I can try but I don't know what is failing.
> @acqn Could you please point me to the failing expression in ghost.c?

Sorry I was busy lately. It was the returned expression in computeGhostSlowDown() in ghost.c, which I think is now fixed in my 
cdf3e54.

**Comment by mrdudz** [comment]
here is a crude testcase: http://hitmen.c02.at/temp/struct-bug.zip

**Comment by acqn** [comment]
> 
> 
> here is a crude testcase: http://hitmen.c02.at/temp/struct-bug.zip

Thanks. The fix seems right. If nothing is wrong I'll make a PR later.

**Comment by mrdudz** [comment]
Don't forget to include the test :)

**Comment by oliverschmidt** [comment]
@Fabrizio-Caruso: Please verify if https://github.com/cc65/cc65/pull/1076 fixes this issue as advertised.

**Comment by Fabrizio-Caruso** [comment]
The issue is fixed for me. Thanks a lot for the quick fix!

**Comment by acqn** [comment]
> 
> 
> Don't forget to include the test :)

I am not confident where new tests should be added since I got it wrong last time. Nor am I good at the Makefile stuff (I can't even know its syntax). Maybe that should be done by someone else rather than me....

**Comment by mrdudz** [comment]
For this type of test (which return 0 when passed and anything else on failure) its very easy - just add them to the test/val dir. You don't have to touch the makefile or anything else.

**Comment by oliverschmidt** [comment]
@Fabrizio-Caruso: Thanks for the confirmation.
