### ISSUE TITLE
[cc65] Wrong code: a non-array constant address with a non-constant subscript

### ISSUE THREAD

**Issue by acqn** [cc65/cc65#1077]
So I find a codegen bug when a non-array constant address is accessed with a non-constant subscript when I was attempting to fix #1075. Example:
```c
#include <stdio.h>

int main(void)
{
    int a = 0;
    (&a)[a] = 42;  
    printf("%d", a);

    return a != 42;
}
```
Current output: out-of-range madness.
Expected output: 42

**Comment by mrdudz** [comment]
Seems to be a Stackpointer misalignment, doing this only prints ONE value before it exits:

~~~
#include <stdio.h>

int test1(void)
{
    int a = 0;
    (&a)[a] = 42;  
    return a;
}
int test2(void)
{
    int a = 0;
    int b = 0;
    (&a)[b] = 42;  
    return a;
}

int main(void)
{
    int res, ret = 0;
    res = test1();
    printf("%d\n", res);
    if (res != 42) ret = 1;
    res = test2();
    printf("%d\n", res);
    if (res != 42) ret = 1;

    return ret;
} 
~~~

**Comment by acqn** [comment]
This can be fixed along with #1075 as they share some common part of code logic. An independent fix only for this is possible but requires more work (-arounds).

**Comment by oliverschmidt** [comment]
Thanks for the intermediate feedback!

**Comment by oliverschmidt** [comment]
There's a test for this issue at https://github.com/cc65/cc65/blob/master/test/todo/bug1077.c

**Comment by mrdudz** [comment]
testcode/strdup-test.c does also fail to compile with an error, this could be related perhaps?

$ cl65 -t sim6502 -o test.prg strdup-test.c 
strdup-test.c(27): Error: Incompatible pointer types at 'Unknown'
strdup-test.c(37): Error: Incompatible pointer types at 'Unknown'

~~~
extern unsigned _hfirst;        /* First free block in list */
...
    unsigned Count = 0;
    unsigned** P = (unsigned**) _hfirst;
    while (P) {
        ++Count;
        P = P[1]; <- this gives the error
    }
~~~

**Comment by acqn** [comment]
It is unrelated to this one. The pointer types are indeed incompatible, although the diagnostic level (error instead of warning, well...) and message ('Unknown') may have issues.

**Comment by mrdudz** [comment]
OK.

**Comment by oliverschmidt** [comment]
Fixed with https://github.com/cc65/cc65/pull/1099.
