### ISSUE TITLE
Some source files have incorrectly set the executable bit on Unix

### ISSUE THREAD

**Issue by Compyx** [cc65/cc65#1086]
I've noticed that some source files have their executable bit set on Unix while they're bog standard text files. This is most likely due to Windows users committing changes or using Windows tools to edit files.
It would be nice if this didn't happen. In my own git projects I managed to make sure that files in commits from Windows are translated from LF/CR to LF using ,gitattributes, I'm guessing something similar can be done to avoid the executable bit.

**Comment by oliverschmidt** [comment]
> I've noticed that some source files have their executable bit set on Unix while they're bog standard text files.

Thanks for pointing out.

> I'm guessing something similar can be done to avoid the executable bit.

I guessed that too but my search came up empty :-(

**Comment by oliverschmidt** [comment]
Fixed with https://github.com/cc65/cc65/commit/bcb8b4990726e9add92ae54d70204e49977f50e5.
