### ISSUE TITLE
testcode/strdup-test.c fails to compile with strange error message

### ISSUE THREAD

**Issue by mrdudz** [cc65/cc65#1089]
testcode/strdup-test.c fails to compile with an error, which may or may not be what we want - in any case the error message is strange:

$ cl65 -t sim6502 -o test.prg strdup-test.c 
strdup-test.c(27): Error: Incompatible pointer types at 'Unknown'
strdup-test.c(37): Error: Incompatible pointer types at 'Unknown'

~~~
extern unsigned _hfirst;        /* First free block in list */
...
    unsigned Count = 0;
    unsigned** P = (unsigned**) _hfirst;
    while (P) {
        ++Count;
        P = P[1]; <- this gives the error
    }
~~~

**Comment by acqn** [comment]
Other C89 compilers e.g. GCC and Clang (--std=c89) give a warning instead of an error on incompatible pointer assignment. While I think the example code is indeed problematic, the error may be overly strict, not to mention the missing expression ('Unknown' is just a fallback) from the message.

**Comment by acqn** [comment]
There are two issues here:
- Strange diagnostic message.
- Incompatible pointer assignment generates an error instead of a warning in cc65.

Is the second issue a problem? Should cc65 make only issue warnings instead of errors on this?

**Comment by oliverschmidt** [comment]
> Should cc65 make only give warnings instead of errors on this?

I can see arguments for both. Therefore I'm personally perfectly fine with both behaviors. So from my POV: Please go ahead as you see fit.

**Comment by jmr** [comment]
I think it should only be a warning. It's just annoying for people if otherwise valid code doesn't compile with cc65. It also seems like it shouldn't be hard to change it to a warning.

**Comment by oliverschmidt** [comment]
> It's just annoying for people if otherwise valid code doesn't compile with cc65.

I wouldn't exactly call it 'valid' ;-)

**Comment by jmr** [comment]
> I wouldn't exactly call it 'valid' ;-)

Should I call it "legal" instead? gcc/clang/msvc all just warn for this. It seems a bit unlikely they all have the same bug.

**Comment by oliverschmidt** [comment]
> Should I call it "legal" instead?

The term 'legal' fits perfectly.

> It seems a bit unlikely they all have the same bug.

Please note the `;-)`above.

**Comment by acqn** [comment]
Thanks for the comments. I'll change the errors into warnings.

**Comment by oliverschmidt** [comment]
Fixed with https://github.com/cc65/cc65/pull/1154.
