### ISSUE TITLE
[cc65] Nested struct/union initializers don't compile

### ISSUE THREAD

**Issue by acqn** [cc65/cc65#1094]
A messy code example originally intended for showing multiple bitfield problems doesn't (while it should) compile at all:
```c
#include <stdio.h>
#include <stddef.h>
#include <stdlib.h>
#include <stdint.h>

typedef uint16_t u16;
typedef uint8_t u8;

struct WW {
    int a : 4;
    struct {
        unsigned int b : 4;
        unsigned int c : 8;
    } x[2];
} wwqq = { 0, {2, 5, {3, 4}}, };

typedef struct {
    u16 quot;
    u16 rem;
} udiv_t;

typedef struct {
    u16 quot;
    u16 rem;
    char m[8];
} big_t;

union U {
    struct {
        signed int a : 3;
        signed int b : 3;
        signed int c : 3;
    };
    int u;
};

union U g = { 5, 3, 1 };

struct S {
    struct {
        unsigned int a : 3;
        unsigned int b : 3;
        unsigned int c : 3;
    };
};

struct S h = { 5, 3, 1 };

union X {
    struct {
        uint16_t a : 3;
        union {
            struct {
                uint16_t b : 3;
                uint16_t c : 3;
            };
            uint16_t d;
        };
    };
    uint16_t e;
} x = { 4, {5, 6} };


udiv_t div3(udiv_t u)
{
    udiv_t v = {};

    u.quot = 341 + u.quot;
    u.rem = 1 + u.rem;

    v = u;

    return v;
}

int main(void)
{
    udiv_t v = { 141, 32 };
    big_t  b = { 141, 32 };

    v = div3(*(udiv_t*)&b);

    printf("%d %d %d\n", (int)wwqq.a, wwqq.x[0].b, wwqq.x[0].c);
    printf("%d %d %d\n", (int)wwqq.a, wwqq.x[1].b, wwqq.x[1].c);
    printf("quot = %u, rem = %u\n", div3(v).quot, div3(v).rem);
    printf("quot = %u, rem = %u\n", v.quot, v.rem);
    printf("quot = %u, rem = %u\n", b.quot, b.rem);
    printf("g.a = %u, g.b = %u, g.c = %d\n", g.a, g.b, g.c);
    x.e = 1467;
    printf("x.a = %d, x.b = %d, x.c = %d\n", x.a, x.b, x.c);
    printf("(long)x.b = %ld, sizeof(x) = %u, sizeof((long)x.a) = %u\n", (long)x.b, sizeof(x), sizeof((long)x.a));
    printf("-x.d = %d, (long)(-x.c + 1) = %ld\n", -x.d, (long)(-x.c + 1));
    printf("h.a = %u, h.b = %u, h.c = %u\n", h.a, h.b, h.c);

    return 0;
}
```
Side note: there is an internal check failure: Field->V.Offs + Size <= SIZEOF_LONG, file 'cc65/expr.c', which is fixed altogether with the passing-by-value structs in my working copy.

**Comment by acqn** [comment]
I've got this to compile with a few fixes. The correctness of the runtime results is yet to be questioned.

**Comment by acqn** [comment]
There is a missing-padding-bits problem with non-end-aligned-at-byte bit-fields at the the end of an struct. I fixed it altogether with the initializers. Now I think the issues leftover are all related to type conversions.

**Comment by jmr** [comment]
> There is a missing-padding-bits problem with non-end-aligned-at-byte bit-fields at the the end of an struct.

Can it be triggered without nested structs?

**Comment by acqn** [comment]
> 
> 
> > There is a missing-padding-bits problem with non-end-aligned-at-byte bit-fields at the the end of an struct.
> 
> Can it be triggered without nested structs?

I didn't test that, but I think it's most likely to be triggered when the "leftover" bit-offset slips on to other bit-fields in the same struct.

**Comment by oliverschmidt** [comment]
Fixed with https://github.com/cc65/cc65/pull/1132.

**Comment by mrdudz** [comment]
added the above test, and recognized it does now trigger ICE
~~~
$ cc65 -t sim6502 -o foo bug1094.c && sim65 -t sim6502 foo
bug1094.c(40): Warning: Implicit truncation from 'int' to 'int : 3' in bit-field initializer changes value from 5 to 5
cc65: Check failed: (Entry->Type->C & T_MASK_SIGN) == T_SIGN_SIGNED || IsTypeChar (Entry->Type), file 'cc65/symtab.c', line 878
~~~

**Comment by jmr** [comment]
Do you know what the minimal example for the ICE is and the minimal example for the strange warning?

**Comment by mrdudz** [comment]
strange warning:
~~~
union U {
    struct {
        signed int a : 3;
    };
};
union U g = { 5 };
~~~

**Comment by mrdudz** [comment]
ICE:
~~~
#include <stdint.h>
union X {
    struct {
        uint16_t a : 3;
    };
} x;
~~~

**Comment by jmr** [comment]
Thanks. Actually, these both reproduce without nesting, so I'll open other bugs.

**Comment by acqn** [comment]
PR #1132 did fix the issue in the OP. The new two issues are not about this topic but about bit-fields instead. So I think it's appropriate to track them in the new specific issues and keep this one closed.
