### ISSUE TITLE
[cc65] Why are 'signed int' bit-fields unsigned in cc65?

### ISSUE THREAD

**Issue by acqn** [cc65/cc65#1095]
I suppose 'int' bit-fields may have implementation-defined signedness, but 'signed int' bit-fields should always be signed.

**Comment by polluks** [comment]
Have a got a test case?

**Comment by acqn** [comment]
A quick test case:
```c
#include <stdio.h>

struct S {
	signed int a : 3;
	signed int b : 3;
	signed int c : 3;
};

int main(void)
{
	struct S s = { -1, -1, -1 };

	printf("%d %d %d %d", s.a, s.b, s.c, (s.a > 0 || s.b > 0 || s.c > 0));
	return s.a > 0 || s.b > 0 || s.c > 0;
}

```

**Comment by polluks** [comment]
By the way sim65 prints three spaces..?

**Comment by jmr** [comment]
@acqn Is this one of the issues you're working on?

**Comment by greg-king5** [comment]
Does cc65 even see a difference between `"int"` and `"signed int"`?

**Comment by acqn** [comment]
@jmr No.

**Comment by acqn** [comment]
@jmr Are you working on this? The changes in #1121 could impact this due to the changes of the "integer types".

**Comment by jmr** [comment]
Sort of, but I didn't get very far yet since I was working on `static_assert` (#1124 ). I'll get back to this after #1121 is merged.

**Comment by jmr** [comment]
I have the `signed int` bit-fields working. Now I just need to switch `int` back to `unsigned int`.
