### ISSUE TITLE
[cc65] Definitons of 0-size structs/unions are treated as pure declarations

### ISSUE THREAD

**Issue by acqn** [cc65/cc65#1096]
The example uses only structs but the situation would be similar with unions:
```c
struct S {
};

size_t z = sizeof(struct S); // (?) Error: Size of data type is unknown

struct S s;                  // (?) Error: Variable 's' has unknown size

struct S {
};                           // should be an error: redefinition of 'struct S'
```
I suppose it's UB to use 0-size structs/unions, but it's strange that their definitions are treated as declarations which means they may be "redefined" somewhere else.

EDIT: I've made a working by making the empty struct type definitions definitions and no longer declarations in a private branch.

**Comment by greg-king5** [comment]
As I remember it, cc65 uses a size of zero to indicate an "incomplete" declaration.  That's why we see those error messages.  And therefore, that second `"struct S {};"` is a continuation of the first one, not a redefinition.
```c
struct S;
struct S { }; // Same as line above

unsigned z = sizeof (struct S); // Error: Size of data type is unknown
struct S s;                     // Error: Variable 's' has unknown size

struct S {
    int m;                      // struct defined here
};

struct S { };                   // Not definition!
struct S {
    int m;
};                              // Error: Multiple definition for 'S'

char a[];
unsigned b = sizeof a;          // Error: Size of data type is unknown
```

**Comment by greg-king5** [comment]
The C Standard doesn't allow an empty "struct-declaration-list" between the braces.  Therefore, `struct { }` should not be a definition.  Either it should be flagged as a syntax error, or we should keep the current behavior.

**Comment by acqn** [comment]
> 
> 
> The C Standard doesn't allow an empty "struct-declaration-list" between the braces. Therefore, `struct { }` should not be a definition. Either it should be flagged as a syntax error, or we should keep the current behavior.

The current behavior is strange if you see it as an "extension". Empty structs are not rarely used as an extension in real world code. IIRC, it was even used in the Linux kernel code or something. Probably due to the fact that C++ allows that with defined behavior.

BTW, I might be long confused with the terminology in C++. In C, these are not called "type _definitions_". Thankfully people got what I meant.

**Comment by jmr** [comment]
`struct S {};` as a declaration equivalent to `struct S;` is surprising to me. Was this really intended, or just a side-effect of how things happen to be implemented? Supporting empty structs as an extension would be more useful and consistent with other compilers.

**Comment by greg-king5** [comment]
> `struct S {};` as a declaration equivalent to `struct S;` is surprising to me. Was this really intended, or just a side-effect of how things happen to be implemented? Supporting empty structs as an extension would be more useful and consistent with other compilers.

It's a side-effect of how "object_size == 0u" is handled.

By the way, if we try to create an empty array (`char arr[0]`), then cc65 complains -- and gives it a fake size of one byte.

**Comment by acqn** [comment]
We have enough info to distinguish "incomplete typed (unknown sized)", "0 sized" and "tentative" declarations. I think we can fix this, and leave 0-size structs/unions support as a separate issue.

**Comment by oliverschmidt** [comment]
Sounds great :-)

**Comment by oliverschmidt** [comment]
Fixed with https://github.com/cc65/cc65/pull/1165.
