### ISSUE TITLE
[cc65] Empty enumerator-list?

### ISSUE THREAD

**Issue by acqn** [cc65/cc65#1098]
```c
enum {
};
```
This is a bit different from empty struct/union type issue. I think the C standard requires the enumerator-list in an enum definition, and the example should be ill-formed.

**Comment by jmr** [comment]
This is related to #1048 . I can work on it.

**Comment by acqn** [comment]
> 
> 
> This is related to #1048 . I can work on it.
Thanks for affording help, but I've already fixed it based on the fix for #1048 in my working copy. I am afraid that a fix on the current code base could lead to some merge conflicts.

**Comment by jmr** [comment]
Can you mention in the issues if you're working on them? That would avoid duplicate work and show which really need attention.

**Comment by acqn** [comment]
> 
> 
> Can you mention in the issues if you're working on them? That would avoid duplicate work and show which really need attention.

OK, good idea.

**Comment by greg-king5** [comment]
> ```c
> enum { };
> ```
> This is a bit different from the empty struct/union type issue. I think the C standard requires the enumerator-list in an enum definition, and the example should be ill-formed.

No!  It's the same.  The C Standard requires something between the braces for `enum`, `struct`, and `union`.

**Comment by acqn** [comment]
> 
> No! It's the same. The C Standard requires that something exists between the braces for `enum`, `struct`, and `union`.

True. Though it seems to be a popular extension to allow empty structs/unions.
