### ISSUE TITLE
cbmcvt does not handle some petscii codes correctly

### ISSUE THREAD

**Issue by mrdudz** [cc65/cc65#1100]
What the topic says. PETSCII has the weird property that some codes exist twice, ie $61-$7a and $c1-$da both produce the uppercase A-Z. cbmcvt does not handle this correctly. Some other codes also seem to be handled in a strange unexpected way (eg the "arrow left" is usally expected to convert to an underscore, pound to backslash etc).

Fixing this would certainly sacrifice the ability to convert arbitrary files forth and back and get the exact same file (which is ALSO broken!), because then we can not have those duplicated codes. However, if the intend of this tool is to be able to convert arbitrary PETSCII encoded textfiles to ASCII, then we must support them.

Before i am looking at a fix - what exactly do we expect this tool to do? (My vote is clearly on converting "textfiles", and being able to convert files forth and back isnt important.)

**Comment by Compyx** [comment]
I you want straight translation, why not use VICE's charset.c? Or use the dual table approach I used in an unfinished/dead project: https://github.com/Compyx/cbmfm/blob/master/src/lib/base/petasc.c

**Comment by mrdudz** [comment]
I know how to fix it (and yes, double table is most likely needed)

**Comment by greg-king5** [comment]
> Before i am looking at a fix - what exactly do we expect this tool to do? (My vote is clearly on converting "textfiles", and being able to convert files forth and back isnt important.)

I don't know what people want, now, from the program; but originally, Uz wanted simply to convert from "host computer" files to "CBM" files.  The scope of the utility was limited; it wasn't intended to handle PetSCII duplicates -- only the "standard" subset (as returned by the GETIN Kernal function).

**Comment by mrdudz** [comment]
the more i think about it -the more i am asking myself: why does this tool even exist? other tools (eg petcat) do the job already

my vote is on simply deleting it from the tree

**Comment by polluks** [comment]
Well, just poor man's petcat, nothing more.

**Comment by oliverschmidt** [comment]
Please remove it right away - and move forward to way more interesting topics!

**Comment by mrdudz** [comment]
For me it is, petcat can do it all (and more) better and correctly :)

**Comment by oliverschmidt** [comment]
Fixed with https://github.com/cc65/cc65/commit/ee208aecd6285848a8470d42ce2a7213fcf63e90.

**Comment by polluks** [comment]
@mrdudz How about a hint in the documentation? "If you are looking for the utility cbmcvt use petcat instead."

**Comment by mrdudz** [comment]
The time it took you to write that Question would have been better spent on actually doing it =P

**Comment by polluks** [comment]
The time it took you to write that Answer would have been better spent on actually doing it =P

**Comment by oliverschmidt** [comment]
I don't need this type of discussion here!

**Comment by polluks** [comment]
just kidding
