### ISSUE TITLE
Incorrect definition of EMULATOR in cx16.h

### ISSUE THREAD

**Issue by MCPEmaniac** [cc65/cc65#1111]
In cx16.h I believe
#define EMULATOR        (*(volatile struct __emul)0x9FB0)
should be 
#define EMULATOR        (*(volatile struct __emul *)0x9FB0)
similar to
#define VERA    (*(volatile struct __vera *)0x9F20)

Why do some of the asterisks not show up in the definitions above in the preview window?

Also, shouldn't cx16.h define an enum type for EMULATOR.echo?

**Comment by polluks** [comment]
BTW backticks are your friend for code in markdown :-)

**Comment by greg-king5** [comment]
> ... should be
> ```c
> #define EMULATOR (*(volatile struct __emul *)0x9FB0)
> ```

Yes.
> Also, shouldn't `<cx16.h>` define an enum type for `EMULATOR.echo`?

There are many things that need to be added to the C header (look at https://github.com/cc65/cc65/blob/master/asminc/cx16.inc).

**Comment by oliverschmidt** [comment]
Fixed with https://github.com/cc65/cc65/commit/b60b303c5d24f718b0c14022b47ca1a838112ceb.
