### ISSUE TITLE
OptStackOps producing invalid optimization?

### ISSUE THREAD

**Issue by bbbradsmith** [cc65/cc65#1112]
While working on a test for #1107 I ran into a strange behaviour. The code in question is here:

https://github.com/cc65/cc65/blob/b8ff117646df8d859680b6c95619b068f24628ba/test/val/rand.c#L42

When I use the `static-locals` pragma with -O the behaviour of this `ref_rand()` function becomes invalid.

```
#pragma static-locals (on)
int ref_rand()
{
	uint16_t output;
	/* seed follows the LCG sequence * 0x01010101 + 0xB3B3B3B3 */
	seed = seed * 0x01010101UL + 0xB3B3B3B3UL;
	/* output uses the top two bytes (reversed) XOR with bottom two bytes */
	{
		uint16_t s0 = (seed >>  0) & 0xFF;
		uint16_t s1 = (seed >>  8) & 0xFF;
		uint16_t s2 = (seed >> 16) & 0xFF;
		uint16_t s3 = (seed >> 24) & 0xFF;
		uint16_t o0 = s3 ^ s1;
		uint16_t o1 = s2 ^ s0;
		output = o0 | (o1 << 8);
	}
	return (int)(output & 0x7FFF);
}
```

Excerpt from resulting assembly showing the problem. Look at the o0 calculation:
```
; command line: cc65 -t sim6502 -O --debug-opt-output --add-source -o rand.c.s rand.c

;
; uint16_t o0 = s3 ^ s1;
;
	.dbg	line, "rand.c", 53
	lda     L0019
	ldx     L0019+1
	eor     sreg+1
	sta     L0022
	stx     L0022+1
;
; uint16_t o1 = s2 ^ s0;
;
	.dbg	line, "rand.c", 54
	lda     L0016
	eor     L001C
	sta     L0024
	lda     L0016+1
	eor     L001C+1
	sta     L0024+1
```

The offending optimization step is `OptStackOps` turning this:
```
;
; uint16_t s3 = (seed >> 24) & 0xFF;
;
	lda     _seed+3
	sta     sreg+1
	lda     _seed+2
	sta     sreg
	ldx     _seed+1
	lda     _seed
	ldx     #$00
	lda     sreg+1
	stx     sreg
	stx     sreg+1
	ldx     #$00
	stx     sreg+1
	stx     sreg
	sta     L001F
	stx     L001F+1
;
; uint16_t o0 = s3 ^ s1;
;
	jsr     pushax
	lda     L0019
	ldx     L0019+1
	jsr     tosxorax
	sta     L0022
	stx     L0022+1
```
Into this:
```
;
; uint16_t s3 = (seed >> 24) & 0xFF;
;
	lda     _seed+3
	sta     sreg+1
	lda     _seed+2
	sta     sreg
	ldx     _seed+1
	lda     _seed
	ldx     #$00
	lda     sreg+1
	stx     sreg
	stx     sreg+1
	ldx     #$00
	stx     sreg+1
	stx     sreg
	sta     L001F
	stx     L001F+1
;
; uint16_t o0 = s3 ^ s1;
;
	lda     L0019
	ldx     L0019+1
	eor     sreg+1
	sta     L0022
	stx     L0022+1
```

So it bizarrely replaces `tosxorax` with `eor sreg+1`? I have no idea how that happens. I am not sure whether the `static-locals` has anything directly to do with it, but without it the generated code appears to be functioning correctly.

**Comment by acqn** [comment]
Investigating....

**Comment by bbbradsmith** [comment]
Oh no! My appologies. When I clicked "edit" on the GitHub website to begin that branch, it took 216105f6df0f24ee656de3cf3abca4591ed3723d as the branch point. I thought it was branching from the current version, but apparently I have been working with something from last October. Whatever bug this was seems to be gone now. Sorry for the spurious report!

**Comment by acqn** [comment]
Never mind. Glad that it works.
