### ISSUE TITLE
[cc65] Compiler crashes when calling functions "redefined" as other types

### ISSUE THREAD

**Issue by acqn** [cc65/cc65#1113]
```c
void f() {}

int f;

int main(void)
{
    f();
    return 0;
}
```
Output:
```
1113.c(3): Error: Conflicting types for 'f'
1113.c(3): Error: Global variable 'f' already was defined in the '' segment.
*crash*
```
It has the cause: caller of `AddGlobalSym()` tampers its return value when the symbol to add has already existed, which is similar to that of Issue #728.

I fixed/worked around this in my working copy by returning a "bogus" symbol entry to "deceive" the caller when it fails to add a symbol due to redefinition errors. It could also help to work around https://github.com/cc65/cc65/issues/728#issuecomment-426887640 better without eagerly aborting compiling.

**Comment by acqn** [comment]
Fixed in my working copy (unfortunately with dependency on the enum type fix as part of the overhauled checking mechanism)

**Comment by oliverschmidt** [comment]
Fixed with https://github.com/cc65/cc65/pull/1133.
