### ISSUE TITLE
Legacy "CC65_HOME" env interferes with building tests and samples from the cloned working copy

### ISSUE THREAD

**Issue by acqn** [cc65/cc65#1116]
I've come across errors with wrong libraries linked several times when running the testsuit with rebuilt working copy _and rebuilt libraries_ after pulling some new library and testsuit changes. I suppose there be such an issue in the `Makefile`s but I am not familiar with them. Any idea?

**Comment by mrdudz** [comment]
Not sure i understand correctly what you mean... what did change when you pulled changes, and what did not get rebuild correctly? Using what "make" command exactly? (I think a "make" in the root of the tree is always required before you can run the tests)

**Comment by oliverschmidt** [comment]
@acqn: In general I have the very same questions @mrdudz already asked.

Apart from that there are two known areas where dependencies are deliberately missing:
1. The libraries are not dependent on the binaries. So if a changed compiler generates different code then the (rather few) parts of the libraries written in C will no get automatically rebuilt.
2. The tests are not dependent on anything.

**Comment by mrdudz** [comment]
btw, is there a reason why the toplevel makefile has no "test" target? with that we could easily do "make clean all test"

**Comment by oliverschmidt** [comment]
As far as I remember there's no strong reason. It's primarily a question of style.

All other Makefiles are rather clean Makefiles following the expert system approach of defining the desired result and leaving it up to make how to orchestrate the process.

In contrast the test Makefiles are rather shell scripts in disguise. That's sort of natural as they have no desired result. Rather they do something just for the sake of doing it (in order to find out if it works).

So the test Makefile don't fit well enough into the overall build system to "deserve" an entry in the top level Makefile ;-)

**Comment by mrdudz** [comment]
OK *shrug*

**Comment by oliverschmidt** [comment]
As you put so much effort into the cc65 tests you have a free wish: https://github.com/cc65/cc65/commit/5df2de06290e9b7181c03eeb311f7687ef469b80

**Comment by mrdudz** [comment]
thanks :)

**Comment by acqn** [comment]
There's an installed release of CC65 with CC65_HOME env set. The working copy of the project clone is separated from it. When I use the `Make` to build in the working copy directory, it does build the executables and libraries with the update-to-date sources. But then, when I use `Make -C test`, it builds the testwork with the newly built executables and links with the old libraries from the old installation in CC65_HOME, which causes errors such as test failures with `test/val/rand.c`.

**Comment by oliverschmidt** [comment]
> There's an installed release of CC65 with CC65_HOME env set.

Why do you set CC65_HOME for a "normal" cc65 installation?

**Comment by acqn** [comment]
> 
> 
> > There's an installed release of CC65 with CC65_HOME env set.
> 
> Why do you set CC65_HOME for a "normal" cc65 installation?

That's what every tutorial and project I came across back then did with a manual installation. The CC65 documentation didn't mention what consequence that would cause though.

**Comment by oliverschmidt** [comment]
I see. "back then" was cc65.org. This is cc65.github.io - and its https://cc65.github.io/getting-started.html says nothing about wanting CC65_HOME. In https://cc65.github.io/getting-started.html#Windows it even says _Note: If you have used cc65 before then you need to make sure to remove all environment variables related to cc65 (like CC65_HOME)._

**Comment by polluks** [comment]
@oliverschmidt Indeed, CC65_HOME was bad design.
It was like AmigaDOS where every application wants its own assign. Later "PROGDIR:" was introduced but I stop going off-topic.

**Comment by oliverschmidt** [comment]
> A normal installation works as soon as the binaries are in $PATH.

Actually not even that is necessary. I added code to cl65 which makes it find cc65 and friends without relying on $PATH. So you can have as many cc65 instances on your system as you like and use them without interference by just calling them as /path/to/the/cc65/cl65|cc65|ca65|ld65.

**Comment by mrdudz** [comment]
Yes of course - my point is that a "normal" install would usually involve having the binaries in $path, and they work without needing CC65_HOME (unlike ages ago)

**Comment by polluks** [comment]
@mrdudz Maybe the installer should remove this env.

**Comment by mrdudz** [comment]
Installer? And no, you dont want to open that can of worms =)

**Comment by acqn** [comment]
If CC65_HOME is something that can do "bad" behind the scences, what about... documenting a bit more clearly about it?

**Comment by polluks** [comment]
At least cl65 also uses CC65_HOME which is not documented.

**Comment by mrdudz** [comment]
I'd prefer to just nuke it from existance - if there isn't a good reason not to do so

**Comment by oliverschmidt** [comment]
> I'd prefer to just nuke it from existance - if there isn't a good reason not to do so

The primary reason from my POV: https://github.com/cc65/cc65/commit/7024e2789d3b673578e67bbbd731a8925eb77376

Secondary reasons may be special test setups.

Presuming that my primary reason is considered "good enough" I'm closing this issue...
