### ISSUE TITLE
Bit Fields Don't Work

### ISSUE THREAD

**Issue by sci4me** [cc65/cc65#1117]
So I was trying to create a struct to represent a 65(c)22 VIA, and it worked fine until I tried to make bit fields for the individual DDR and OR/IR bits. When I assign any of the "single-bit" values, the byte they are contained within gets set to 1, no matter which bit I tried to set.

Here's the struct definition I came up with:
```c
typedef struct {
	union {
		struct {
			volatile u16 prb0 : 1;
			volatile u16 prb1 : 1;
			volatile u16 prb2 : 1;
			volatile u16 prb3 : 1;
			volatile u16 prb4 : 1;
			volatile u16 prb5 : 1;
			volatile u16 prb6 : 1;
			volatile u16 prb7 : 1;
		};
		volatile u8 prb;
	};
	union {
		struct {
			volatile u16 pra0 : 1;
			volatile u16 pra1 : 1;
			volatile u16 pra2 : 1;
			volatile u16 pra3 : 1;
			volatile u16 pra4 : 1;
			volatile u16 pra5 : 1;
			volatile u16 pra6 : 1;
			volatile u16 pra7 : 1;
		};
		volatile u8 pra;
	};
	union {
		struct {
			volatile u16 ddrb0 : 1;
			volatile u16 ddrb1 : 1;
			volatile u16 ddrb2 : 1;
			volatile u16 ddrb3 : 1;
			volatile u16 ddrb4 : 1;
			volatile u16 ddrb5 : 1;
			volatile u16 ddrb6 : 1;
			volatile u16 ddrb7 : 1;
		};
		volatile u8 ddrb;
	};
	union {
		struct {
			volatile u16 ddra0 : 1;
			volatile u16 ddra1 : 1;
			volatile u16 ddra2 : 1;
			volatile u16 ddra3 : 1;
			volatile u16 ddra4 : 1;
			volatile u16 ddra5 : 1;
			volatile u16 ddra6 : 1;
			volatile u16 ddra7 : 1;
		};
		volatile u8 ddra;
	};
	volatile u8 t1cl;
	volatile u8 t1ch;
	volatile u8 t1ll;
	volatile u8 t1lh;
	volatile u8 t2cl;
	volatile u8 t2ch;
	volatile u8 sr;
	volatile u8 acr;
	volatile u8 pcr;
	volatile u8 ifr;
	volatile u8 ier;
	volatile u8 _pra;
} __VIA;
```

And here's the definitions (macros) I used to access the VIAs in my computer:
```c
#define VIA1 (*(__VIA*)0x7F20)
#define VIA2 (*(__VIA*)0x7F40)
```

Finally, an example of what's going on:
```c
VIA1.ddra4 = 1;
acia_put_hex_byte(VIA1); // prints `01` to the serial port; should be `10`
```

**Comment by mrdudz** [comment]
did you check the generated code? it may actually be correct - but not behave as you expect

**Comment by groessler** [comment]
I'm never using bit fields to describe the bits of a hardware register.

I'm using defines.

With bitfields, it's not defined where bit #0 starts (at the left or at 
the right). Compiler dependent.

regards,
chris

**Comment by sci4me** [comment]
> did you check the generated code? it may actually be correct - but not behave as you expect

This:
```c
void test(void) {
    VIA1.pra4 = 1;
    VIA1.pra6 = 1;
}
```
Generates this:
```
.segment	"CODE"

.proc	_test: near

.segment	"CODE"

	lda     #$01
	sta     $7F21
	stz     $7F21+1
        sta     $7F21
	stz     $7F21+1
	rts

.endproc
```

The first thing that stands out to me is that it's writing to twp bytes, presumably because I declared the bits as u16s; unsigned int is the only type that will actually compile, so... :( 
And then, well, obviously it's just not generating code that would actually set bit 4 and 6...


@groessler Fair point, though, that wouldn't cause the issue I'm experiencing since setting _any_ of the bits always gives the same result.

**Comment by mrdudz** [comment]
did you do this with an up to date build? there were a bunch of related fixes recently... but they are not entirely done yet i think, see issue #1094 for example

**Comment by sci4me** [comment]
> did you do this with an up to date build? there were a bunch of related fixes recently... but they are not entirely done yet i think, see issue #1094 for example

Ah, my apologies; should've specified. I am on V2.18 (18246278c) currently. Also, I suspect this may be related or the same as #1094; not sure yet.

**Comment by acqn** [comment]
This is fixed if my #1094 solution is applied, which gives (with all optimization steps disabled):
```
;
; VIA1.pra4 = 1;
;
	ldx     #$00
	lda     $7F21
	ora     #$10
	sta     $7F21
;
; VIA1.pra6 = 1;
;
	ldx     #$00
	lda     $7F21
	ora     #$40
	sta     $7F21
;
; }
;
	rts
```
The optimization may be enabled if you'd like to have it, but keep mind that cc65 doesn't respect `volatile` well at present, and the best you can work around with that is to disable the optimization steps that elide loads/stores in the wrong way.

**Comment by oliverschmidt** [comment]
@acqn: Thanks for the analysis!

**Comment by mrdudz** [comment]
> The optimization may be enabled if you'd like to have it, but keep mind that cc65 doesn't respect volatile well at present, and the best you can work around with that is to disable the optimization steps that elide/re-arrange loads/stores in the wrong way.

I'd still advice against using C for accessing hardware registers... unless its trivial Stuff (eg colors) and you know exactly what you are doing - because you dont really have any control about how the accesses happen, and subtle bugs may appear. Eg in this case, loading the output latch reflects the actual status of the port, not what was written to it - which might result in something you dont expect.

**Comment by polluks** [comment]
@acqn A volunteer for volatile? ;-)

**Comment by acqn** [comment]
As @mrdudz says (and what you may conclude from the `EDIT` section of https://github.com/cc65/cc65/issues/971#issuecomment-569552219), C standard `volatile` isn't enough for accessing hardware registers, especially when "one operation" involves read+write (such as writing to bit-fields, +=, ++ etc.). Some more proper (AKA non-standard) facilities are needed if we really want to support that in C.

**Comment by oliverschmidt** [comment]
I really don't see cc65 making any commitment regarding the usability of the generated code for accessing h/w registers that are sensitive to certain types of access like multiple accesses or alike.

Either the users uses the (inline) assembler or he checks the generated code for usability - and is aware that any new cc65 revision may generate different code. Been there, done that:
https://github.com/cc65/ip65/blob/master/apps/w5100.c#L47-L50
https://github.com/cc65/ip65/blob/master/apps/w5100.c#L95-L99

**Comment by mrdudz** [comment]
> Some more proper (AKA non-standard) facilities are needed if we really want to support that in C

well, not really - bitfields simply dont work for this, you have to access the registers directly as a whole, like in

```
*(volatile char*)0x1234 = ((*(volatile char*)0x1234) & MASK) | BITS
```

that will work as expected

**Comment by acqn** [comment]
> 
> 
> > Some more proper (AKA non-standard) facilities are needed if we really want to support **that** in C
> 
> well, not really - bitfields simply dont work for this, you have to access the registers directly as a whole, like in
> 
> ```
> *(volatile char*)0x1234 = ((*(volatile char*)0x1234) & MASK) | BITS
> ```
> 
> that will work as expected

I was referring to "accessing hardware registers", not "one operation". I neither said that one should use `volatile` to do that. Just to stay clarified.

**Comment by oliverschmidt** [comment]
Fixed with https://github.com/cc65/cc65/pull/1132.
