### ISSUE TITLE
[cc65] Declarations of variables of incomplete types?

### ISSUE THREAD

**Issue by acqn** [cc65/cc65#1118]
So... anyone enlighten me please?
```c
struct S s; /* Question: is this allowed? GCC: Yes; Clang: Yes; MSVC: No;  CC65: No */
enum E e;   /* Question: is this allowed? GCC: No;  Clang: Yes; MSVC: Yes; CC65: Yes (No with my #1093 solution) */

struct S {
    int a;
};

enum E {
    Z
};
```

**Comment by polluks** [comment]
````
1118.c:2:6: warning: ISO C forbids forward references to 'enum' types [-Wpedantic]
    2 | enum E e;   /* Question: is this allowed? GCC: No;  Clang: Yes; MSVC: Yes; CC65: Yes (No with my #1093 solution) */
      |      ^
````
vbcc: Yes
vbcc: Yes

**Comment by jmr** [comment]
What does your "allowed" mean? No warning? No error? Do GCC and clang agree with `-pedantic-errors`?

I'm surprised the struct is allowed, but I couldn't find anything to disallow it.

**Comment by acqn** [comment]
Thanks for the info. @polluks @jmr 

I consider it's "allowed" if it is compiled without an error. GCC and Clang both warn about the `enum` case with `-pedantic`, but only GCC generates an error eventually.

A better question would be: "Should CC65 support these?"

**Comment by oliverschmidt** [comment]
> Should CC65 support these and/or emitting warnings/errors on them?

Sorry for my ignorance, but... If the usual suspects among the compilers have a different opinion on something then I consider the scenario rather esoteric. And for esoteric scenarios I'd always go for the approach with the least effort to implement and/or resulting in the code to maintain best.

**Comment by jmr** [comment]
I'm  seeing gcc compile it without error.

https://godbolt.org/z/7n15vv

As for cc65, the struct should be accepted since it's apparently valid C. I only checked C99 though. 

The enum is a common and useful extension.  If it doesn't cause you any problems,  it seems good to support. Better if there's also a way to get a warning /error that it's an extension.

**Comment by acqn** [comment]
It turns out that it would require way less change for making this work like GCC (version 10+)/Clang than I anticipated. Sure the C standards were somehow specified keeping "usually not too hard for implememntations" in mind.

BTW this is closely related to Issues #975 and #1096 (but not so #1098, as an "empty enum" is still of an integer type and can't be 0-size).
