### ISSUE TITLE
test/misc instructions?

### ISSUE THREAD

**Issue by acqn** [cc65/cc65#1122]
https://github.com/cc65/cc65/blob/81d3dedb4109cd3da845ec77b1fddcc3f83c5aa3/test/readme.txt#L28-L30

Shouldn't this be
>  When this happens, the PR fixing the issue should also "invert" the 
> failing condition in the makefile by **adding a** $(NOT) before the 
> offending line (or removing it when it is already there), which will 
?

**Comment by mrdudz** [comment]
yes, oops :)

**Comment by acqn** [comment]
Then, it still makes me wonder why the currently "broken" status of a test case is _required_ for CI to pass.

**Comment by mrdudz** [comment]
That way we notice when a PR fixed a certain test, which is why the same PR should also move/fix the test

**Comment by oliverschmidt** [comment]
Exactly - or to phrase it somewhat differently:

Every time a PR fixing a bug passes CI without a modification in test/ this shows that there's no regression test present.

**Comment by acqn** [comment]
I see. Thanks for the explanation.

**Comment by acqn** [comment]
Could these special tests be separated from the "normal tests"? That would make it clearer what is the problem.

> Every time a PR fixing a bug passes CI without a modification in test/ this shows that there's no regression test present.

This is however, uh, conterintuitive: the test passes when there is something missing and fails when a bug is fixed.

**Comment by acqn** [comment]
Could these special tests be separated from the "normal tests"? That would make it clearer what is the problem.

> Every time a PR fixing a bug passes CI without a modification in test/ this shows that there's no regression test present.

This is however, uh, conterintuitive: the test passes when there is something missing and fails when a bug is fixed.

**Comment by acqn** [comment]
Could these special tests be separated from the "normal tests"? That would make it clearer what is the problem.

> Every time a PR fixing a bug passes CI without a modification in test/ this shows that there's no regression test present.

This is however, uh, conterintuitive: the test passes when there is something missing and fails when a bug is fixed.

**Comment by mrdudz** [comment]
Why, you notice it, then you fix the condition. "never write a line of code you dont have a failing test for" :)

**Comment by oliverschmidt** [comment]
> This is however, uh, conterintuitive: the testsuit passes when there is something missing and fails when a bug is fixed.

Would you prefer the testsuite failing until all known issues have been solved? ;-)

**Comment by acqn** [comment]
> "never write a line of code you dont have a failing test for" :)

That's about unit test, and we don't really have it. I provided demo code for every issue I reported. They just need some work to be made into test cases. Am I supposed to do all the jobs?

**Comment by acqn** [comment]
> 
> 
> > This is however, uh, conterintuitive: the testsuit passes when there is something missing and fails when a bug is fixed.
> 
> Would you prefer the testsuite failing until all known issues have been solved? ;-)

No. What I suggested here is to have them in a separated report when the test fails _due to a bug fixed_.

**Comment by mrdudz** [comment]
> I provided demo code for every issue I reported. They just need some work to be made into test cases. Am I supposed to do all the jobs? I am frustrated enough.

Well, ideally, yes. However it's not required, and i happily go after it (i cant fix the compiler). It was just a lame joke

> have them in a separated report when the test fails due to a bug fixed.

that would be nice - i dont think the travis CI can do this however

**Comment by acqn** [comment]
@mrdudz `test/misc/bug264.c` is actually working and should be moved to `test/val`. The weird part related here is that it doesn't seem to change result of the test work if a `$(NOT)` is added or not.

**Comment by mrdudz** [comment]
The rule in test/misc/Makefile only checks if it compiled... if it compiles now it should fail when you add a NOT *shrug*

**Comment by greg-king5** [comment]
> https://github.com/cc65/cc65/blob/master/test/misc/bug264.c actually is working, and should be moved to `test/val`.
> 
> EDIT: For a struct-passing/returning-by-value compiler error test, should a struct larger than 4 bytes be used instead?

Both things should be done.

1. That test is useful; it compares two similar functions-returning-struct, one written in Assembly, and the other one written in C.  It should be given a different name.
2. `test/err/bug264.c` should test functions that try to pass structs and unions that are too big.

**Comment by oliverschmidt** [comment]
I think by now this issue is best classified as 'enhancement' (of the test code). @mrdudz: Given that you are the major contributor to the test code you may want to take care of this issue...

**Comment by mrdudz** [comment]
cheers :)

**Comment by oliverschmidt** [comment]
Thanks :-)
