### ISSUE TITLE
"Result of comparison is constant" warning in constant expressions

### ISSUE THREAD

**Issue by jmr** [cc65/cc65#1123]
`int x[0 == 0];` [gives the warning](https://godbolt.org/z/v3f45d):
```
<source>(1): Warning: Result of comparison is constant
```

This isn't a useful warning, since the expression here has to be a constant.

**Comment by acqn** [comment]
This was on my TODO list as a "codegen improvement" but at low priority.

**Comment by acqn** [comment]
I got a hold on the old work and completed the part needed for this and #250. It looks to be working and resolved. Unfortunately it was on a very different branch and might need quite some modifications to be rebased onto the current stream.

**Comment by acqn** [comment]
Fixed in #1220. It is also improved that the warnings now tell the result values (`true` or `false`).
