### ISSUE TITLE
"make test" does not work

### ISSUE THREAD

**Issue by mrdudz** [cc65/cc65#1125]
Oliver was so kind to add a "test" target in the toplevel makefile... the problem is, it doesnt work
~~~
$ make test
make[1]: *** Keine Regel, um „test“ zu erstellen.  Schluss.
make: *** [Makefile:24: test] Fehler 2
~~~
I am staring at the Makefile but i dont get it. It should work just fine =)

**Comment by oliverschmidt** [comment]
Fixed with https://github.com/cc65/cc65/commit/4316242d7ee3d1471bfdbef6469cee5a2190336a.

@mrdudz: Sorry!
