### ISSUE TITLE
[feature request] long bit-fields

### ISSUE THREAD

**Issue by jmr** [cc65/cc65#1131]
Same as #1047 except for long. This requires slightly more code to be added.

**Comment by acqn** [comment]
Are there testcases for this feather?

**Comment by mrdudz** [comment]
probably not :)

**Comment by mrdudz** [comment]
I have to admit... i have no idea. I hardly ever use(d) them, so i wouldnt even know what is common. Is this something not defined in the standard?

**Comment by acqn** [comment]
The standard (even as of C17/C18) only supports `int` ranked bit-fields. The standard integer promotion rules would result in loss of bits for long bit-fields of bit-widths > int bit-width if applied as-is:
> If an int can represent all values of the original type (as restricted by the width, for a bit-field), the
> value is converted to an int; otherwise, it is converted to an unsigned int. These are called the
> integer promotions.)
