### ISSUE TITLE
[ATARI] consol missing in struct __gtia_read 

### ISSUE THREAD

**Issue by pfeuh** [cc65/cc65#1137]
consol should be present in struct __gtia_read. It is used to read the extra keys OPTION SELECT START. in my opinion lines like these ones are missing at the end of the structure, after the last unsigned char named pal:

    unsigned char   unused01;
    unsigned char   unused02;
    unsigned char   unused03;
    unsigned char   unused04;
    unsigned char   unused05;
    unsigned char   unused06;
    unsigned char   unused07;
    unsigned char   unused08;
    unsigned char   unused09;
    unsigned char   unused10;
    unsigned char   consol; /* access to OPTION SELECT START */

**Comment by oliverschmidt** [comment]
You seem to look at a pretty old cc65: https://github.com/cc65/cc65/commit/ae4e9fab8c1156a15b6db2250ad23356f1909611

Consider to update.
