### ISSUE TITLE
[cc65] Multiple storage class specifiers in one declaration?

### ISSUE THREAD

**Issue by acqn** [cc65/cc65#1143]
Split from Issue #1142 (with some addition):
```c
static static void* y[1];   /* duplicate storage class allowed? */
extern static int a;        /* error */
extern typedef int A;       /* error */
```
cc65 currently doesn't allow duplicate storage class to be specified (if that should be allowed, I suppose).
The error messages with conflicting storage classes could be reduced a bit.
Anyways, the fix is easy and I have already made a working revision. Just to comfirm the issue here first.

**Comment by oliverschmidt** [comment]
> Anyways, the fix is easy and I have already made a working revision.

:-)

**Comment by oliverschmidt** [comment]
Fixed with https://github.com/cc65/cc65/pull/1146.
