### ISSUE TITLE
[cc65] How far do we extend support for `void` type family of objects?

### ISSUE THREAD

**Issue by acqn** [cc65/cc65#1144]
Split from Issue #1142 (with modifications):
```c
void ex0    = { 0x1234, (char)12 };     /* our extension */
void ex1[1] = { {0x1234, (char)12} };   /* initialized 'void []', OK or not? */
extern void z[];                        /* forward declaration of 'void []'? */
```
Do we support `void`  object beyond the simplest `void` object? Do we support `void []`?

There are instances of usage of forward declarations of `void []` in the library code. So I suppose we at least support that too? But is that a real array of `void` elements, or just some pointer to `void` objects in disguise?

**Comment by jmr** [comment]
Am I missing something about what this extension can do? Does it just save a bit of typing? It seems like it could be deleted and extensions aren't required.

```
struct {
    int a;
    char b;
} ex0 = { 0x1234, 12 };
```

or just


```
int exa = 0x1234;
char exb = 12;
```

https://godbolt.org/z/9obWc6

**Comment by oliverschmidt** [comment]
> There are instances of usage of forward declarations of `void []` in the library code.

I can't find them. Please name/list them.

> But is that a real array of void elements, or just some pointer to void objects in disguise?

My idea of `void` stems from `void *`: Such a pointer references something I don't want to make statements about regarding its structure. Especially there's no element size defined and therefore no valid pointer arithmetic. With pure C it's afaik impossible to define a `void`. But given that cc65 has an interface between C and asm it is appropriate that cc65 allows `void` declarations (presuming the definitions being done in asm).

That's at least how I have used `void` declarations so far. And from the POV I can't see what semantic an array of void elements should have.

**Comment by acqn** [comment]
https://github.com/cc65/cc65/blob/adda28f5c5ce8de5a7a778723361b36545dcf92e/include/apple2.h#L171-L176
https://github.com/cc65/cc65/blob/adda28f5c5ce8de5a7a778723361b36545dcf92e/include/apple2enh.h#L99-L104

Not sure if there are more of them.

**Comment by oliverschmidt** [comment]
> And from the POV I can't see what semantic an array of void elements should have.

That proves perfectly that my statements should not be given much weight as I was the very person introducing those `void []` back then ;-))

The idea was simply to allow in e.g. https://github.com/cc65/cc65/blob/master/samples/tgidemo.c#L203 to write
```
tgi_install (tgi_static_stddrv);
```
instead of
```
tgi_install (&tgi_static_stddrv);
```
which would be necessary if the declarations in question were straight `void`. The tgi_install formal parameter is - as expected - typed as `void *` (https://github.com/cc65/cc65/blob/master/include/tgi.h#L85).

If it's not causing significant problems I'd ask to support that pattern for compatibility reasons with existing user code outside the cc65 repo.

**Comment by acqn** [comment]
No problem allowing `extern void array[]`.

**Comment by oliverschmidt** [comment]
:-)

**Comment by acqn** [comment]
So I decided to support arrays of `void` as long as they are initialized with data of consistent size for each "row".
