### ISSUE TITLE
[cc65] Internal error with function type object

### ISSUE THREAD

**Issue by acqn** [cc65/cc65#1145]
```c
void f()
{
    f = 0; /* internal error */
}
```
Output:
```
Error: Invalid lvalue in assignment
Error: Incompatible types
Error: Size of data type is unknown
Internal compiler error:
Invalid type in CF flags: 0140, type = 0
```
Cause:
https://github.com/cc65/cc65/blob/e1043fac12151cdec415e76d78e23114d8f0b070/src/cc65/datatype.c#L735
`g_call()`, `g_callind()` and `g_enter()` are abusing this `CF_<FLAG>` "code generator type flag" for passing a special `CF_FIXARGC` parameter, which causes errors when other `CF_<FLAG>` users meet this unexpected flag. A fix is ready.

**Comment by oliverschmidt** [comment]
Fixed with https://github.com/cc65/cc65/pull/1147.
