### ISSUE TITLE
[feature request] compile for embedded system  ROM (no OS)

### ISSUE THREAD

**Issue by pfeuh** [cc65/cc65#1148]
It should be nice to be able to use cc65 generated code for embedded system, I mean in ROM: With custom definition of getchar/putchar and size of the ROM. Most of the compilers for microcontrolers and microprocessors offer this feature.

**Comment by mrdudz** [comment]
I dont see the problem - all you need is a custom linker config and the respective library code

**Comment by polluks** [comment]
Indeed, we already have your type of target, see Gamate.

**Comment by pfeuh** [comment]
I agree, I had a look at https://cc65.github.io/doc/customizing.html ... But I haven't the skills to do it by myself. OK, let's have a look to ... Gamate? 

OK, I compile a hello.c with
cl65 -O -t gamate hello.c -o a
and I get a 32k file. I suppose it's a 32k rom 8000-8FFF . Thanks a lot, I hope I can get some info on this by myself. Thanks a lot.

**Comment by oliverschmidt** [comment]
Apart from the ROM-question I don't see that someone should/would/could implement custom getchar/putchar. Those are part of the shared high level I/O function family.

**Comment by pfeuh** [comment]
If you talk about the DIY world, I agree. But in industrial world,  it's the rule. Often when you buy a C compilation tool chain like the Keil one for 8031 family (the CPU heart is in public domain, there is a lot of children of this heart), You don't even know what will exactly be your ios. In the principle, you redefine getcar & put car, all the stdio library will follow, inherits from your 2 functions. You can also buy a library like a fat16 or fat32 one, no matter your hardware, you define getsector and putsector, it's the same. Keil has compilers for a lot of microcontrollers/microprocessors families with this feature. Idem for Raisonance, IAR or  even SDDC... Which is an open source project. Microchip has a compiler inherited from gcc with this feature, even if they didn't develop it by themselve. Concerning 6502, you're the one and only team I know working on a C compiler.

**Comment by mrdudz** [comment]
The functions follow the same pattern as in the "industrial world" really

**Comment by pfeuh** [comment]
Nice to hear that. It motivates me. I will examine cc65 documentation concerning this feature.
