### ISSUE TITLE
Add Windows build to travis-ci

### ISSUE THREAD

**Issue by jmr** [cc65/cc65#1150]
Twice recently I've broken the Windows build.

Apparently travis-ci supports windows:

https://docs.travis-ci.com/user/reference/windows/
https://stackoverflow.com/questions/61874708/how-can-i-build-visual-studio-2019-projects-on-travis-ci

I don't know anything about Windows, but it would be good if someone added this. (Maybe someone who keeps getting broken -- @acqn )

**Comment by acqn** [comment]
I don't know anything about CI....

**Comment by jmr** [comment]
If you tell me the windows commands to do the equivalent of `make ; make test`, I can try to add it to the `.travis.yml`.

**Comment by oliverschmidt** [comment]
Thanks for your offer, but I don't see .travis.yml as a typical target for PRs. I'll evaluate this myself.

**Comment by acqn** [comment]
> 
> 
> If you tell me the windows commands to do the equivalent of `make ; make test`, I can try to add it to the `.travis.yml`.

Hmm, the thing that got broken was "MSVC project build", not exactly the same as "Windows build". I actually use mingw-w64 GCC to build for Windows for my personal usage.

That's to say, the thing to check is to build with the *.sln/*.vcxproj files, which I think should use `MSBuild.exe` according to the link you provided (https://stackoverflow.com/questions/61874708/how-can-i-build-visual-studio-2019-projects-on-travis-ci). I am not familliar with that either, as `nmake` has been for a long time the only "make equivalent for MSVC" that I have ever run on Windows besides `mingw32-make`.

**Comment by oliverschmidt** [comment]
> Hmm, the thing that got broken was "MSVC project build", not exactly the same as "Windows build". I actually use mingw-w64 GCC instead of MSVC to build for Windows for my personal usage.

Exactly, and that's what the CI does too - which ist the reason why MSVC build breaks don't make the CI fail.

> Anyways, the thing to check is to build with the *.sln/*.vcxproj files, which I think should use MSBuild.exe according to the link you provided (https://stackoverflow.com/questions/61874708/how-can-i-build-visual-studio-2019-projects-on-travis-ci).

Exactly, and as I already wrote I'll take care of this. No need to further invest into the topic here...

**Comment by oliverschmidt** [comment]
The MSVC support in Travis-CI is pretty far from optimal but with some ugly hacking I got it finally working. Last commit: https://github.com/cc65/cc65/commit/c831f40e9b1c2bcc3d1fdb5c5dfff5d51524447a
