### ISSUE TITLE
[test] bdiff on Windows

### ISSUE THREAD

**Issue by acqn** [cc65/cc65#1159]
Raised from https://github.com/cc65/cc65/pull/1158#issuecomment-667709124
> The cause of the consistent failure with the test/misc/goto.c and test/misc/limits.c for me is just unexciting: CRLF vs LF.

The text output on Windows uses CRLF instead of LR, which causes failure when the output files are compared to the `.ref` files with `bdiff.exe`.

Should `bdiff.exe` be able to deal with that? Or should we use some alternative `.ref` files on Windows? Or just keep the _status quo_?

**Comment by oliverschmidt** [comment]
As I wrote in https://github.com/cc65/cc65/pull/1158#issuecomment-667727571 I'd appreciate if...

* bdiff silently ignores line ending differences of any kind
* bdiff is renamed diff

**Comment by acqn** [comment]
> 
> 
> As I wrote in [#1158 (comment)](https://github.com/cc65/cc65/pull/1158#issuecomment-667727571) I'd appreciate if...
> 
>     * bdiff silently ignores line ending differences of any kind
> 
>     * bdiff is renamed diff

Will we need to do strict binary comparison of the output someday? If not then I think that's all right.

**Comment by oliverschmidt** [comment]
> Will we need to do strict binary comparison of arbitrary output someday? If not then I think that's all right.

That thought was the base of my suggestion.

**Comment by oliverschmidt** [comment]
@mrdudz: Can you imagine to take care of this issue? To summarize the fix:

* Have bdiff consider the following 3 as identical:
  1. 1 byte: 0x0D
  2. 1 byte: 0x0A
  3. 2 bytes: 0x0D, 0x0A

* Rename bdiff to diff

**Comment by mrdudz** [comment]
i can try... wouldnt it be a good idea though to use a less ambiguous name than "diff" (which is a standard unix tool)?

**Comment by oliverschmidt** [comment]
> i can try...

:-)

> wouldnt it be a good idea though to use a less ambiguous name than "diff" (which is a standard unix tool)?

My proposal to rename it was purely driven by the fact that b(inary)diff isn't true anymore if it handles line ending differences gracefully. What name do you have in mind?

**Comment by mrdudz** [comment]
Thats a really good question :) since its not even "diff"ing anyway, perhaps something like "isequal"?

**Comment by oliverschmidt** [comment]
Good idea!

**Comment by mrdudz** [comment]
fixed in 1a92368a
