### ISSUE TITLE
[cc65] Distinct char type?

### ISSUE THREAD

**Issue by acqn** [cc65/cc65#1163]
Well, in the ISO C the `char`, `signed char` and `unsigned char` types are 3 different types from each other. So the following should fail in cc65 (but currently it doesn't):
```c
char a;
unsigned char a;         /* should fail as 'char' is not the same type as 'unsigned char' */

void f(char *);
void f(unsigned char *); /* should fail for the same reason as above */
```
Would we fix this?

**Comment by mrdudz** [comment]
its a good idea to fix it IMHO

**Comment by groessler** [comment]
Please show the relevant section of the standard. I thought, it's just not defined whether "char" is "signed" or "unsigned".

**Comment by jmr** [comment]
There are three character types.

https://port70.net/~nsz/c/c89/c89-draft.html#3.1.2.5
https://port70.net/~nsz/c/c99/n1256.html#6.2.5p15

**Comment by groessler** [comment]
interesting...

**Comment by oliverschmidt** [comment]
> I thought, it's just not defined whether "char" is "signed" or "unsigned".

Me too...

> interesting...

Indeed!

**Comment by oliverschmidt** [comment]
Just some random discussion: https://stackoverflow.com/questions/16503373/difference-between-char-and-signed-char-in-c

**Comment by oliverschmidt** [comment]
> its a good idea to fix it IMHO

I'm rather unsure. I could imagine that there's quite some code out there which uses `unsigned char` and `char` presuming that it's interchangeable. E.g. @groessler and me didn't know til now that this isn't appropriate...

**Comment by acqn** [comment]
The `char` type was overloaded with 3 meanings in C/C++:
- A `character` type.
- An `integer` type.
- A `byte` type (with regards to representations of the values, or you may think of `memcpy`, type punning etc.).

Then it is realized that this is not a good design, and _they tried_ to reduce the problems by making `char` a distinct `character` type from `signed char` and `unsigned char` as the standard integer types. Unfortunately it didn't resolve the problems at all.

C++ inherited the problems but at least tried harder to fix them, by making character constants really of `char` type (in C they are of `int` type if you haven't been aware of that), adding new dedicated `std::byte` and `char8_t` types etc. C is moving a bit too slowly on this.

**Comment by oliverschmidt** [comment]
Thanks for the background info :-)

However, I'm personally still very unsure how to proceed. Do the others have a (strong) preference?

**Comment by mrdudz** [comment]
For the case shown in the first post, i'd prefer an error

**Comment by oliverschmidt** [comment]
Given that there's no strong opinion towards the current behavior combined with the fact that the standard make a precise statement it seems desirable to change the current behavior.

**Comment by acqn** [comment]
I experimented this and it seems to work fine. However, is there need for a "legacy-compatible" mode?

**Comment by oliverschmidt** [comment]
> However, is there need for a "legacy-compatible" mode?

I don't think so.

**Comment by mrdudz** [comment]
:+1:
