### ISSUE TITLE
[cc65] Function prototypes?

### ISSUE THREAD

**Issue by acqn** [cc65/cc65#1167]
Besides the issue mentioned in #1142 and #1162, there are several other issues with function declarations in cc65:
```c
int f1(int (*)(char *), int (*)[]);
int f1(int (*)(), int (*)[3]);          /* BUG cause:  This simply replaces the previous function descriptor */
int f1(int (*)(int), int (*)[]);        /* BUG result: Compiles. Should be an error */

int f2(int (*)(), int (*)[3]);
int f2(int (*)(char *), int (*)[]);     /* BUG cause:  This simply replaces the previous function descriptor */
int f2(int (*)(char *), int (*)[2]);    /* BUG result: Compiles. Should be an error */

int f3(void);
volatile int f3(void);                  /* Question: Is this OK? */

void f4(int);
void f4(volatile int);                  /* Question: Is this OK? */
```
The second prototypes of `f1` and `f2` simply replace the previous ones.

**Comment by acqn** [comment]
More:
```c
void scope1()
{
    extern void f(int (*)[1]);
}

void scope2()
{
    extern void f(int (*)[2]); /* UB */
}
```

**Comment by oliverschmidt** [comment]
```
int f3(void);
volatile int f3(void);                  /* Question: Is this OK? */

void f4(int);
void f4(volatile int);                  /* Question: Is this OK? */
```
Yet again being naive: Is there a potentially useful meaning for those? I guess 'no'. I don't see why someone would have written that or why it should be allowed to write that.

**Comment by oliverschmidt** [comment]
```
void scope1()
{
    extern void f(int (*)[1]);
}

void scope2()
{
    extern void f(int (*)[2]); /* UB */
}
```
I just don't know enough about C: Those two are declarations referring to definitions done somewhere else, right? Are such declarations in general allowed inside functions? Is this scenario special in that the declarations are functions? <...>?

**Comment by polluks** [comment]
@oliverschmidt because of symmetry

**Comment by acqn** [comment]
I got some answers from https://en.cppreference.com/w/c/language/function_declaration.

> 
> 
> ```
> int f3(void);
> volatile int f3(void);                  /* Question: Is this OK? */
> 
> void f4(int);
> void f4(volatile int);                  /* Question: Is this OK? */
> ```
> 
> Yet again being naive: Is there a potentially useful meaning for those? I guess 'no'. I don't see why someone would have written that or why it should be allowed to write that.

I don't know if they are useful. The ISO C allows the `f3` case, but I don't know if it allows the `f4` case. GCC and Clang both allow that. As to what good purpose that may serve, I don't know. Maybe to allow some results from macros?

> 
> 
> ```
> void scope1()
> {
>     extern void f(int (*)[1]);
> }
> 
> void scope2()
> {
>     extern void f(int (*)[2]); /* UB */
> }
> ```
> 
> I just don't know enough about C: Those two are declarations referring to definitions done somewhere else, right? Are such declarations in general allowed inside functions? Is this scenario special in that the declarations are functions? <...>?

Yes, `extern` declarations are accepted inside functions. They just work as a "function-scope" version of the file-scope function declaration. Function declarations are not special inside function scopes except they can't be declared with any storage class other than `extern`.

**Comment by acqn** [comment]
```c
struct S;
void foo(struct S);                /* BUG: should be OK */
void foo(struct S { int a;});      /* BUG: should be error due to type conflict (#1168) */
void foo(struct S);                /* BUG: should be OK */
void bar(struct T);                /* BUG: should be OK */
```

**Comment by greg-king5** [comment]
> ```c
> /* Note: new types declared inside a parameter list are local to the function and not visible outside */
> ```

Where does the C standard say that?
> ```c
> void bar(struct T);            /* BUG: should be OK, not "Size of type 'struct T' is unknown" */
> void bar(struct T);            /* BUG: should conflict with the above (#1168) */
> ```

Why should they conflict while the two `void foo(struct S);` shouldn't conflict?

**Comment by acqn** [comment]
https://port70.net/~nsz/c/c99/n1256.html#6.2.1p4:

> If the declarator or type specifier that declares the identifier appears inside a block or within the list of parameter declarations in a function definition, the identifier has **block scope**, which _terminates at the end of the associated block_. If the declarator or type specifier that declares the identifier appears _within the list of parameter declarations in a function prototype (not part of a function definition), the identifier has **function prototype scope**, _which terminates at the end of the function declarator_.

Therefore, the identifiers (including the tag types) declared in a parameter list of a function prototype (or definition) is only in that one "function prototype scope" (or that "function definition block scope") and not visible out of it.

In the example, the two `void foo(struct S);` function prototypes are not declaring a local `struct S`, but are just referring to the global `struct S` declared in the file scope earlier. On the contrary, the two `void bar(struct T);` function prototypes are each declaring a local `struct T` that are invisible outside, which are considered incompatible to each other.

**Comment by acqn** [comment]
BTW the current `DoCompare()` function got this wrong:

https://port70.net/~nsz/c/c99/n1256.html#6.7.2.3p5:
> 5 Two declarations of structure, union, or enumerated types _which are in different scopes or use different tags declare **distinct types**_. Each declaration of a structure, union, or enumerated type which does not include a tag declares a distinct type.

It is currently comparing the types field-by-field... It might the consequence of confusing the rules for that in separated translation units.

**Comment by acqn** [comment]
As to `f3` and `f4` in the example code poseted above, I can't find where in the standard they are forbidden. The current behavior of cc65 is to allow `f3` and disallow `f4`, which I think is fine.

**Comment by oliverschmidt** [comment]
@acqn: Yet again I can only follow on the process, not on the topic. So my questions is: Do you actually wait for feedback here?

**Comment by acqn** [comment]
I've got a tentative solution while I am waiting for the feedback.

**Comment by oliverschmidt** [comment]
Please go ahead with your tentative solution.

**Comment by oliverschmidt** [comment]
@acqn: Is this issue still to be considered as open?

**Comment by acqn** [comment]
@oliverschmidt Yes. The fix for the remaining part hasn't been pushed yet.
