### ISSUE TITLE
[cc65] Local enums/structs/unions types are wrongly judged in comparison

### ISSUE THREAD

**Issue by acqn** [cc65/cc65#1168]
At the moment, cc65 does track ESU types in the correct scopes where they are declared/defined, but when comparing these types, it ignores the scopes and just assume they be identical if their tag names and field names match.

```c
struct X {
    int a;
} x, *px;

int main(void)
{
    struct X y, *py;

    /* Local 'struct X' shadows global 'struct X' and is an incompatible type */
    struct X {
        int a;
    } z, *pz;

    x  = y;     /* OK, same type */
    px = py;    /* OK, same type */
    x  = z;     /* BUG: Should issue an error */
    px = pz;    /* BUG: Should issue a warning */
    y  = z;     /* BUG: Should issue an error */
    py = pz;    /* BUG: Should issue a warning */

    return 0;
}
```
Cause: the current `DoCompare()` function gets wrong with:

https://port70.net/~nsz/c/c99/n1256.html#6.7.2.3p5:
> 5 Two declarations of structure, union, or enumerated types _which are **in different scopes** or use different tags declare **distinct types**_. Each declaration of a structure, union, or enumerated type which does not include a tag declares a distinct type.

It is currently ignoring the scope requirement and comparing the types field-by-field... which might the consequence of confusing the rules for that in separated translation units.

A fix for this is done.

**Comment by oliverschmidt** [comment]
> A fix for this is done.

:-)
