### ISSUE TITLE
Struct handling somewhat broken...

### ISSUE THREAD

**Issue by IrgendwerA8** [cc65/cc65#1178]
Code prints '0' for 'a' and 'b'. If you comment the struct member 'e', the expected values '42' and '11' are displayed.

```
#include <stdio.h>

typedef struct
{
	unsigned char a;
	unsigned char b;
	unsigned char c;
	unsigned char d;
	unsigned char e;
}
TestStruct;

TestStruct StructArray[2];
TestStruct test;

void
main(void)
{
	test.a = 42;
	test.b = 11;

	StructArray[0] = test;

	printf ("Contents: %d, %d\n", (int)StructArray[0].a, (int)StructArray[0].b);

	while(1);
}
```

**Comment by IrgendwerA8** [comment]
The case with more than 4 bytes utilizes `memcpy()`, but I think the compiler generates wrong addressing for this case:
```
	lda     _StructArray
	ldx     _StructArray+1
	jsr     pushax
	lda     _test
	ldx     _test+1
	jsr     pushax
	ldx     #$00
	lda     #$05
	jsr     _memcpy
```

Shouldn't that be
```
	lda    #(<_StructArray)
	ldx     #(>_StructArray)
	jsr     pushax
	lda     #(<_test)
	ldx     #(>_test)
	jsr     pushax
```
?

**Comment by acqn** [comment]
True. It was using the facility assuming the old lvalue/rvalue semantics and was somehow missing the adaption to the new facility with changed semantics. Will fix soon.

**Comment by acqn** [comment]
There is a obscure bug with struct/union assignments, which never worked. I decide to leave it out and just have this issue fixed.

**Comment by oliverschmidt** [comment]
@IrgendwerA8: Thanks for the detailed report.

@acqn: Thanks for the quick fix.

**Comment by IrgendwerA8** [comment]
@acqn: Thanks!

Just for completeness, in the direct copy case (up to 4 bytes), the code is quite horrible:

```
	lda     _test+3
	sta     sreg+1
	lda     _test+2
	sta     sreg
	ldx     _test+1
	lda     _test
	sta     _StructArray
	stx     _StructArray+1
	ldy     sreg
	sty     _StructArray+2
	ldy     sreg+1
	sty     _StructArray+3
```

Icing on the cake would be an output like this:
```
	lda _test+3
	sta _StructArray+3
	lda _test+2
	sta _StructArray+2
	lda _test+1
	sta _StructArray+1
	lda _test
	sta _StructArray
```

- if this is reach anyhow...

**Comment by acqn** [comment]
@IrgendwerA8 I was aware of that. In my ~~vapoware~~ "optimization" branch the optimizer can make it (to some degree):
```asm
;
; StructArray[0] = test;
;
	lda     _test+3
	sta     _StructArray+3
	lda     _test+2
	ldx     _test+1
	sta     _StructArray+2
	lda     _test
	sta     _StructArray
	stx     _StructArray+1

```
