### ISSUE TITLE
CI should test building the libraries

### ISSUE THREAD

**Issue by mrdudz** [cc65/cc65#1179]
While bisecting for a bug i found, i stumbled about the fact that certain revisions in the repo cant even build cleanly (by that i mean compiler and libraries). That is really annoying when doing a bisect, and probably shouldnt be the case. I'd expect every single revision to be able to build compiler, libraries, samples, and tests of course :)

(the commit in question is 21084895230d137db87f8a4febac8a9359e8e548 - which also happens to be the one that breaks my testcase, but that is unrelated to this ticket, i still have to make a simple one :))

That said, perhaps this already happens in the head revision?

**Comment by acqn** [comment]
> I'd expect every single revision to be able to build compiler, libraries, samples, and tests of course :)

In that case, known bug-fixing commits like https://github.com/cc65/cc65/pull/1169/commits/db1f09ea8518af835aa3cabd3cec52470edb587b would have to be collapsed onto the first commits that fix them, or those commits would fail the test.

**Comment by oliverschmidt** [comment]
> I'd expect every single revision to be able to build compiler, libraries, samples, and tests of course :)

GitHub provides several options to merge pull requests. So far I used:

_**Rebase and merge**
The <n> commits from this branch will be rebased and added to the base branch._

Do I understand you right in that you want me/us to rather use:

_**Squash and merge**
The 4 commits from this branch will be combined into one commit in the base branch._

Am I right to presume that you'll consider this issue fixed if I/we do so from now on? Or do you expect the Git history to be rewritten?

> That said, perhaps this already happens in the head revision?

I can't follow you here. Please elaborate on what 'this' refers to.

**Comment by mrdudz** [comment]
'this' as in 'the libraries are compiled by CI'

and can't tell anything about the git stuff, i have no idea how that works or what the implications are (or what the explaination even is supposed to tell me =P). it just would be nice if bisect didnt fail because some commit causes a failing compilation (compiler and libs). it's fine for me that whatever is required is done from now on, no need to retroactively fix the repo.

**Comment by oliverschmidt** [comment]
> 'this' as in 'the libraries are compiled by CI'

The libraries for all targets are being built by CI from day one. So there's no difference between compiler and libraries whatsoever. Maybe you aren't aware that the cc65 Windows snapshot .ZIP is produced by CI...

> it's fine for me that whatever is required is done from now on, no need to retroactively fix the repo.

Good :-)

Presuming that no one opposes...

The three mergers

* @oliverschmidt 
* @greg-king5 
* @mrdudz 

from now one use the 'Squash and merge' GitHub PR merge option. In combination with only merging PR with positive CI result this is supposed to make most revisions work. 'most' istead of 'all' as I now and then manage to break things with direct commits ;-)

**Comment by acqn** [comment]
I'd oppose it.
Wouldn't that make bisecting harder if you are just looking up one specific bug?

**Comment by mrdudz** [comment]
> In combination with only merging PR with positive CI result

It's the only thing i ever do, so thats fine for me :=)

**Comment by acqn** [comment]
I'd put it this way: squashing commits would make it easier to do bisection, but harder to debug.

**Comment by mrdudz** [comment]
I agree, if that will really make debugging harder, dont do it.

**Comment by acqn** [comment]
Thank you for your understanding. I might exaggorated the potential difficulty with that approach. Nonetheless, it was indeed a nightmarish experience the last time I had to debug a "squashed" mega commit that modified a lot of lines among a lot of files.

BTW, I think the CI can be simply "abused" to check for every commit in a PR, by just appending the commits one by one to it.

**Comment by oliverschmidt** [comment]
@mrdudz wrote:

> I agree, if that will really make debugging harder, dont do it.

I'm happy to see that there's an agreement on how to move forward :-)

@acqn wrote:

> I'd rather fix every commit for building (only the compiler/library part) instead of squashing them into one.

Thanks for your investment :-)

> I think the CI can be simply "abused" to check for every commit in a PR, by just appending the commits one by one to it.

I totally agree. I guess this approach makes it necessary that you notify us somehow, that you added all commits you intended to add.

**Comment by acqn** [comment]
What will happen if a new commit is appended while CI is still checking?

**Comment by oliverschmidt** [comment]
Travis CI allows to automatically cancel running jobs, if new jobs are scheduled. I deliberately did **_not_** activate that option. From that perspective I'd presume that it works as desired for our use case.

**Comment by oliverschmidt** [comment]
It seems to me that it is appropriate to consider this issue closed...

**Comment by greg-king5** [comment]
> I totally agree. I guess that approach makes it necessary that you notify us, somehow, that you added all commits you intended to add.

[Draft PRs](https://docs.github.com/en/github/collaborating-with-issues-and-pull-requests/about-pull-requests#draft-pull-requests) are supported by this repository.

**Comment by oliverschmidt** [comment]
Thanks for the hint :-)
