### ISSUE TITLE
[libsrc] "Lvalue cast" used in _scanf.c?

### ISSUE THREAD

**Issue by acqn** [cc65/cc65#1186]
https://github.com/cc65/cc65/blob/8197e3c7cdeb373ae69ce80f368eb76ada6d6102/libsrc/common/_scanf.c#L275

There are several instances like this, which aren't allowed in ISO C.

EDIT: The appropriate way is
```c
__AX__ = (unsigned int) JumpBuf; 
```

**Comment by oliverschmidt** [comment]
@acqn: It seems to me that you have a precise idea on how to fix those issues. Given that you are extremely active in contributing to cc65: Is there a reason why you want someone else to fix them? Or do you intend to take care of them yourself sometime later?
