### ISSUE TITLE
[cc65] _Static_assert without a message?

### ISSUE THREAD

**Issue by acqn** [cc65/cc65#1188]
It would be a nice addition to "backport" this C2X feature into cc65:
`_Static_assert ( expression );`
https://en.cppreference.com/w/c/language/_Static_assert

**Comment by mrdudz** [comment]
i thought that was already added not so long ago?

**Comment by acqn** [comment]
The recently added `_Static_assert` feature requires the message part to be provided.

**Comment by mrdudz** [comment]
AH! yes, ok
