### ISSUE TITLE
Function declarations not recognized properly, causing errors at compile time.

### ISSUE THREAD

**Issue by SvenMichaelKlose** [cc65/cc65#1216]
Declaration

`extern void __fastcall__ event_handler_passthrough (struct obj *, struct event *);`

for function

`void __fastcall__
event_handler_passthrough (struct obj * obj, struct event * event)
{
}`

now gives

`event.c(19): Error: Conflicting function types for 'event_handler_passthrough'`.

To be seen in [https://github.com/svenmichaelklose/ingle/](url).

Also weird error messages like this now occur:

Incompatible pointer assignment to 'struct obj *' from 'struct obj *'

**Comment by acqn** [comment]
Is there a `struct obj` declaration before the function declarations?

**Comment by SvenMichaelKlose** [comment]
No, there isn't.

**Comment by acqn** [comment]
Then the two function declarations are indeed incompatible as they each declare a new local `struct obj` tag type that are only visible inside themselves and incompatible to each other inspite of the same tag name.

See https://github.com/cc65/cc65/issues/1167#issuecomment-670668700

**Comment by SvenMichaelKlose** [comment]
That makes no sense. Pointers(!) are all of the same size; only their identity is required, allowing for encapsulation and otherwise unresolvable circular dependencies. Works on every C compiler I know since the '90s.

**Comment by acqn** [comment]
At least not on GCC or Clang.
https://godbolt.org/z/dqGT75

**Comment by SvenMichaelKlose** [comment]
GCC not doing it leaves me a little bit confused. And gone is a great feature! Must be confusing something with C++. i rest my case.

**Comment by SvenMichaelKlose** [comment]
Now even with all declarations beforehand I get the same mess.

**Comment by SvenMichaelKlose** [comment]
OK, here's the correct solution: Just add a `struct obj;` instead of the include file and it works as expected.

**Comment by acqn** [comment]
So the incomplete type bug was fixed in the HEAD revision? I wasn't aware of that. That's good news.
