### ISSUE TITLE
Poor post-increment codegen when value not needed

### ISSUE THREAD

**Issue by jmr** [cc65/cc65#1229]
```
static unsigned int si = 0;
void postinc_static_int(void) { si++; }
```

```
.proc   _postinc_static_int: near

.segment        "CODE"

        lda     _si
        ldx     _si+1
        jsr     incax1
        sta     _si
        stx     _si+1
        rts

.endproc
```

This could just be
```
        inc     _si
        bne     L000C
        inc     _si+1
L000C:  rts
```

https://godbolt.org/z/fPYoT4

It's probably not too hard to pass in a bool to the codegen indicating whether the value is actually needed. It's not needed for statements, the first operand of `,`, and probably other places.

**Comment by acqn** [comment]
```asm
;
; File generated by cc65 v 2.18 - N/A
;
	.fopt		compiler,"cc65 v 2.18 - N/A"
	.setcpu		"6502"
	.smart		on
	.autoimport	on
	.case		on
	.debuginfo	off
	.importzp	sp, sreg, regsave, regbank
	.importzp	tmp1, tmp2, tmp3, tmp4, ptr1, ptr2, ptr3, ptr4
	.macpack	longbranch
	.export		_postinc_static_int

.segment	"DATA"

_si:
	.word	$0000

; ---------------------------------------------------------------
; void __near__ postinc_static_int (void)
; ---------------------------------------------------------------

.segment	"CODE"

.proc	_postinc_static_int: near

.segment	"CODE"

	inc     _si
	bne     L0003
	inc     _si+1
L0003:	rts

.endproc
```
It's a resolved (in a different way) problem in my "optimizer" branch.

**Comment by jmr** [comment]
How close is that to being a PR?

**Comment by acqn** [comment]
The core implementation only depends on an earlier version of #1220. It could be rebased onto the current HEAD. The relevent optimizer part (to eliminate some unnecessary backups/restores of the original value of the expressions for post-inc/dec operations) depends on some facility still far away, unfortunately.

**Comment by acqn** [comment]
But yeah, since we have made it possible to pass the evaluation flags around, the method suggested in your OP could be easier to implemented.
