### ISSUE TITLE
spurious warning with latest cc65 version

### ISSUE THREAD

**Issue by groessler** [cc65/cc65#1234]
I'm getting this warning now:

```
$ cl65 -t atari -o /tmp/color.com color.c
color.c(73): Warning: Expression result unused
$

```

regards,
chris

[color.zip](https://github.com/cc65/cc65/files/5164942/color.zip)

**Comment by greg-king5** [comment]
That's an old, old issue.  (The warning used to be about "dead code".)

You must cast your macro expansion to `(void)` because of the `_textcolor()` macro in <atari.h>.

**Comment by groessler** [comment]
Thanks. Stupid me...
