### ISSUE TITLE
[question] How to (ab)-use "correctly" cprintf on Atari in mode1?

### ISSUE THREAD

**Issue by Fabrizio-Caruso** [cc65/cc65#1241]
On the Atari target I am doing:
```
#include <stdint.h>
#include <conio.h>

void _GOTOXY(uint8_t x, uint8_t y)
{ 
	if((y)&1) 
	{ 
		gotoxy(x+20,(y)/2);
	} 
	else 
	{ 
		gotoxy(x, (y)/2);
	} 
};

void PRINT(uint8_t x, uint8_t y, char * str)
{ 
    _GOTOXY(x,y);
    cprintf(str); 
};
```
which sort of works but also displays a blank character at random positions.
![atari_bug](https://user-images.githubusercontent.com/29057615/92281698-762c3780-eefc-11ea-9c10-2fd07618115f.jpg)

Is this a bug or just a side-effect of the (ab)-use of cprintf in mode1?

**Comment by groessler** [comment]
isn't this the same problem where I once sent you a `disable_setcursor.s` alternative `setcursor` implementation?

**Comment by Fabrizio-Caruso** [comment]
I thought we had fixed it for good. I need to check I have not removed your fix by mistake.

**Comment by Fabrizio-Caruso** [comment]
@groessler It looks like your fix is not fixing all cases as I see `disable_setcursor` in my Makefile:
```
atari_color: $(ASSETS_PATH)/8x8_chars.h
	$(CC65_PATH)$(MYCC65) $(INCLUDE_OPTS) -O -t atari \
	-DREDEFINED_CHARS \
	-DINITIAL_SLOWDOWN=31500 \
	-DANIMATE_PLAYER -DFULL_GAME -DATARI_MODE1 -DSOUNDS -DBETWEEN_LEVEL -DEND_SCREEN \
	--config $(CFG_PATH)/cc65/atari_mode1_redefined_chars.cfg \
...
	$(CROSS_LIB_PATH)/display/alt_print/atari_mode1_alt_print.c \
	$(CROSS_LIB_PATH)/display/init_graphics/cc65/atari/disable_setcursor.s \
	$(CROSS_LIB_PATH)/display/init_graphics/cc65/atari/atari_mode1_redefined_chars_init_graphics.c \
	$(CROSS_LIB_PATH)/sound/cc65/pokey/pokey_sounds.c \
	$(FULL_FILES) \
	-o $(BUILD_PATH)/FULL_X$(GAME_NAME)_atari_color.xex
```

**Comment by Fabrizio-Caruso** [comment]
@groessler I see the issue appear the second time I run the code that is supposed to print the text. Could your fix be only fixing the first occurrence? I am trying to guess what is wrong...

**Comment by groessler** [comment]
Can you provide a simple program to reproduce the issue?

**Comment by Fabrizio-Caruso** [comment]
@groessler if I leave the code that displays the planes and the message in a simpler example, the error no longer occurs....
The current smallest example is the tiny game Cross Bomber (you need to remove line 538 in `main.c` ):
https://github.com/Fabrizio-Caruso/CROSS-CHASE/tree/master/src/games/bomber

The problem occurs in:
https://github.com/Fabrizio-Caruso/CROSS-CHASE/blob/master/src/games/bomber/main.c#L539

I will try to simplify it in other ways. So far no luck.

**Comment by Fabrizio-Caruso** [comment]
@groessler The bug is cursor-related because if I clear the screen I see the character the was hidden before.
![Atari_bug2](https://user-images.githubusercontent.com/29057615/92417927-2b612880-f165-11ea-8d53-6fd03837f7f9.jpg)

**Comment by Fabrizio-Caruso** [comment]
I am closing this because I found that the problem is caused by the way I clear the screen... For some reason poking into video memory is leaving a character... If I use clrscr from conio, it seems to work.

**Comment by Fabrizio-Caruso** [comment]
@groessler I have not a simpler test that shows how a character appears just after `cgetc()`?
Could `cgetc()` be the culprit?

The code is:
```
        gotoxy(0,0);
        for(y=2;y<YSize-1;++y)
        {
            for(x=1;x<XSize-2;++x)
            {
                cprintf("X");
            }
        }
        cgetc();
        PRINT(3,9,"game over");
        cgetc();
        CLEAR_SCREEN(); SLEEP(1);
        cgetc();
```

where PRINT is defined as:
```
#include <stdint.h>
#include <conio.h>

void _GOTOXY(uint8_t x, uint8_t y)
{ 
	if((y)&1) 
	{ 
		gotoxy(x+20,(y)/2);
	} 
	else 
	{ 
		gotoxy(x, (y)/2);
	} 
};

void PRINT(uint8_t x, uint8_t y, char * str)
{ 
    _GOTOXY(x,y);
    cprintf(str); 
};
```
and
CLEAR_SCREEN is just poking the value 0 into video memory:
```
If I use clrscr from conio.h, I see the whole screen cleared and I do not see the X character reappear.
If I use my own CLEAR_SCREEN I see the whole screen cleared BUT I do see the X character reappear when I run `cgetc()`.
```

**Comment by Fabrizio-Caruso** [comment]
@groessler 
I see the problem appear if I use `cgect()`.
I now have an simple example to be compiled with `disable_setcursor:`
```
#include <stdint.h>
#include <conio.h>
#include <unistd.h>
void _GOTOXY(uint8_t x, uint8_t y)
{ 
	if((y)&1) 
	{ 
		gotoxy(x+20,(y)/2);
	} 
	else 
	{ 
		gotoxy(x, (y)/2);
	} 
};

void PRINT(uint8_t x, uint8_t y, char * str)
{ 
    _GOTOXY(x,y);
    cprintf(str); 
};
#define BASE_ADDR_VALUE (PEEK(88)+PEEK(89)*256)
#define _delete(i,j) POKE(BASE_ADDR_VALUE+i+j*20,0)
#define _draw(i,j) POKE(BASE_ADDR_VALUE+i+j*20,'x'+192)
#include <peekpoke.h>
void CLEAR_SCREEN(void)
{
    uint8_t i;
    uint8_t j;
    
    for(i=0;i<20;++i)
    {

        for(j=0;j<24;++j)
        {
            _delete(i,j);
        }
    }
}

int main(void)
{
    uint8_t i;
    uint8_t j;
    
	_graphics(1+16);
	
	_setcolor_low(0, TGI_COLOR_RED);
	_setcolor_low(1, TGI_COLOR_WHITE);
	_setcolor_low(2, TGI_COLOR_CYAN); 	
	_setcolor_low(3, TGI_COLOR_BROWN);
	_setcolor_low(4, TGI_COLOR_BLACK);
    
    while(1)
    {
        CLEAR_SCREEN();
        PRINT(2,7,"hello world 1");
        sleep(1);
        
        gotoxy(0,0);
        for(i=0;i<20;++i)
        {
            for(j=0;j<24;++j)
            {
                _draw(i,j);
            }
        }
        cgetc();
        sleep(1);
        CLEAR_SCREEN();
        sleep(1);
        
        PRINT(2,9,"hello world 2");
        sleep(1);
        CLEAR_SCREEN();
        PRINT(2,5,"hello world 3");
        sleep(2);
        
    }
    return 0;
}
```

**Comment by groessler** [comment]
in your `CLEAR_SCREEN` write a 0 to `OLDCHR` (address 0x5d).
`*(unsigned char *)0x5d = 0;`

**Comment by Fabrizio-Caruso** [comment]
@groessler it does not work as you can see here (top left corner with no "X"). If I remove `cgetc()`, I see the correct picture below.
It looks like `cgetc()` is displaying a cursor.

You can look at the minimal test with the problem in:
https://github.com/Fabrizio-Caruso/CROSS-CHASE/blob/master/src/games/bomber/tests/atari_test1.c

It just needs to be compiled and linked to yours disable_setcursor.s (https://github.com/Fabrizio-Caruso/CROSS-CHASE/blob/master/src/cross_lib/display/init_graphics/cc65/atari/disable_setcursor.s)

The makefile target (atari_test1) is found in:
https://github.com/Fabrizio-Caruso/CROSS-CHASE/blob/master/src/Makefile.bomber

![image](https://user-images.githubusercontent.com/29057615/92509343-66696780-f20a-11ea-9e91-f2ecfae96cb8.png)
