### ISSUE TITLE
[question/bug?] 19 extra bytes in produced binary vs July 2020

### ISSUE THREAD

**Issue by Fabrizio-Caruso** [cc65/cc65#1255]
When compiling my game I get a bigger binary now compared to July (snapshot from July 15th).

I see this for the Vic 20 but it could happen on other targets, as well.

I have attached two binaries produced with two different snapshots on the very same source code.

[Sept12th.zip](https://github.com/cc65/cc65/files/5213118/Sept12th.zip)
[July15th.zip](https://github.com/cc65/cc65/files/5213119/July15th.zip)

You can reproduce and rebuild it manually from my repo (https://github.com/Fabrizio-Caruso/CROSS-CHASE) with
`make vic20_unexpanded_no_gfx`

**Comment by mrdudz** [comment]
Thats pretty normal, some fixes will improve the binary size, some will make the binary a bit larger. If you really think it's a regression, you should create a minimal testcase :)

**Comment by Fabrizio-Caruso** [comment]
@mrdudz I can try to build a smaller testcase. My game worked before with no issue. It is now bigger by 19 bytes which is a little issue on an unexpanded Vic 20 but, indeed, if it is a bugfix, there is no bug in the extra bytes.

**Comment by polluks** [comment]
Maybe you can find the difference in the map files.

**Comment by acqn** [comment]
Probably caused by the fixes to integer promotion.
