### ISSUE TITLE
Memory leak on c128

### ISSUE THREAD

**Issue by cyberfoxIT** [cc65/cc65#1262]
Hello,

I'm having a problem with a program I'm doing for C128.
I usually store in a variable the amount of heap available and compare it after has called a function, in order to understand if there something I've not freed.
Usually it works well, but I've a case where there are always 716 bytes missing!
This code look for a particular file name in the directory of a disk; once found, show it's contents.
I've noticed that the problem appear only when the file is found, so inside the `if` with the `strcmp()`, if the file name is not found on the disk, no memory leakage.
I've verified the functions `readCluster()`, `readFATEntry()`, and `readDirectoryEntry()`, and they doesn't leak any memory.
They're used in other parts of the pgm., and they work just fine.
Do you know if is a know issue, or do you find something wrong in the code below?
The piece of code is this:
```c
	struct DiskInfo *diskInfo = NULL;
	unsigned char rc = 0;

	if (paged){
		printf("Insert disk in drive '%i:' and press any key...\n", source->number);
		cgetc();
	}

	rc = cbm_open(15, source->number, 15, "");

	diskInfo = queryDisk(15);
	if (diskInfo != NULL){
		int idx = 1, nextCluster = 0;
		char *trimmed = NULL, *cluster = NULL;
		struct DirItem *dirItem = NULL;
		bool found = false;

		while ((dirItem = getDirectoryItem(15, idx)) != NULL && !found){
			trimmed = strlower(trim(dirItem->fileName));
			if (strcmp(source->name, trimmed) == 0 &&
				strcmp(source->ext, dirItem->fileExt) == 0){
				long shown = 0, window = 0, lidx = 0;

				found = true;
				nextCluster = dirItem->cluster;
				do {
					char *cluster = readCluster(15, nextCluster);
					window = 1024;
					if ((dirItem->fileSize - shown) < 1024)
						window = dirItem->fileSize - shown;
					for (lidx = 0; lidx < window; lidx++)
						printf("%c", *(cluster + (int)lidx));
					shown += window;
					free(cluster);
					nextCluster = readFATEntry(15, nextCluster);
				} while (nextCluster < 4088 || nextCluster > 4095);
			}
			free(dirItem->fileName);
			free(dirItem->fileExt);
			free(dirItem->fdate);
			free(dirItem->ftime);
			free(dirItem);
			free(trimmed);
			idx++;
		}

		if (!found)
			printf("File '%s' not found on drive %i:\n", source->fullName, source->number);
		else
			printf("\n");

	}	
	if (diskInfo != NULL)
		free(diskInfo);

	cbm_close(15);
```
Thank you.

**Comment by polluks** [comment]
Please tell us about the solution.

**Comment by cyberfoxIT** [comment]
Hi, 

thank you for your reply, unfortunately I've no solution at the moment, I've closed the issue because I've found some bugs here and there, and I want to repeat some test before reopen it.
I don't think what I found is the problem, anyway I'll do some test today hopefully...

Thank you

**Comment by cyberfoxIT** [comment]
Hello,

I've made some test tonight, the problem disappear only if:
 - The program doesn't enter in the if statement
 - I remove part of the condition of the while (!found) so the while became like this:
		while ((dirItem = getDirectoryItem(15, idx)) != NULL){
 - I've tried to change the while condition to :
		while ((dirItem = getDirectoryItem(15, idx)) != NULL && nextCluster != 0){

Seem something related to the condition of the while statement with boolean conditions, but I've no idea!

It's strange, I've used boolean many many times without any problem at all...
Any help is really appreciated!

**Comment by mrdudz** [comment]
the first thing to do is creating a minimal self contained test case to reproduce the problem. i'd start with making "fake" versions of getDirectoryItem, readCluster etc and see if the problem persists.

**Comment by greg-king5** [comment]
That `while` line tests two conditions. _Either one_ can stop the loop.  If it's the second one that stops the loop, then `dirItem` still exists -- you don't free it outside of the loop.

You must swap the order of those tests.  If the file was found in the previous `dirItem`, then another one doesn't need to be created.

**Comment by cyberfoxIT** [comment]
> That `while` line tests two conditions. _Either one_ can stop the loop. If it's the second one that stops the loop, then `dirItem` still exists -- you don't free it outside of the loop.
> 
> You must swap the order of those tests. If the file was found in the previous `dirItem`, then another one doesn't need to be created.

I think I must pay you a beer or two!!
You are right!
I've just tried and all work as it should!

Thank you again!!

**Comment by MonteCarlos** [comment]
From a more general perspective, i would suggest to split the code into
several functions with each beeing not longer than 10 lines.
Then you would have a chance to test the functions one by one instead of
tapping in the dark.
I would guess, the code contains more subtle bugs. It would be worth to
do a little refactoring to improve the structure.
