### ISSUE TITLE
misadjusted stack from unprototyped function call

### ISSUE THREAD

**Issue by jmr** [cc65/cc65#1265]
Calling an unprototyped function results in the stack pointer being decremented by 2. 

```
#include <stdio.h>

int main (void) {
  int x;

  printf ("%p\n", &x);
  f (x);
  printf ("%p\n", &x);

  return 0;
}

int f (int x) { return 1; }
```

```
% cl65 --standard c89 -t sim6502 foo.c -o foo && sim65 foo
0xffea
0xffe8
```

@acqn any insight here?

**Comment by mrdudz** [comment]
mmh, i was going to add the following as a test program:

~~~
/* bug #1265 - misadjusted stack from unprototyped function call */

#include <stdio.h>
#include <string.h>

int failures = 0;

char str1[10];
char str2[10];

int f2 (int x) { return x == 2345 ? 23 : -1; }

int main (void) {
  int x, n;

  sprintf (str1, "%p\n", &x);
  puts(str1);
  x = 1234;
  n = f1 (x);
  sprintf (str2, "%p\n", &x);
  puts(str2);
  
  if (strcmp(str1, str2)) {
      puts("not equal");
      failures++;
  }
  if (n != 42) {
      puts("f1 returns wrong value");
      failures++;
  }

  sprintf (str1, "%p\n", &x);
  puts(str1);
  x = 2345;
  n = f2 (x);
  sprintf (str2, "%p\n", &x);
  puts(str2);
  
  if (strcmp(str1, str2)) {
      puts("not equal");
      failures++;
  }
  if (n != 23) {
      puts("f2 returns wrong value");
      failures++;
  }

  return failures;
}

int f1 (int x) { return x == 1234 ? 42 : -1; }
~~~

... but it fails to compile using the CI makefiles, apparently C89 is required.

how do we handle this? (why doesnt this work in "cc65" standard, which is the default?)

**Comment by polluks** [comment]
@mrdudz At least your code is okay.
We have no std pragma, so the makefile needs an extra rule.

**Comment by mrdudz** [comment]
> why doesnt this work in "cc65" standard, which is the default?

this is the key, the answer is "because std=cc65 is kindof std=c99, which makes calls to non prototyped functions illegal".

so yes, it needs a custom rule. too bad :)

**Comment by acqn** [comment]
> @acqn any insight here?

Some accient bug (from the first revision) I guess:
https://github.com/cc65/cc65/blob/47ee1792732def69c8ba6255a3078f0492e4ddd3/src/cc65/datatype.c#L464

(https://port70.net/~nsz/c/c89/c89-draft.html#3.3.2.2)
> If the expression that precedes the parenthesized argument list in a function call consists solely of an identifier, and if no declaration is visible for this identifier, the identifier is implicitly declared exactly as if, in the innermost block containing the function call, the declaration
```c
         extern int  identifier();
```

The "implicit declaration" should not be variadic.

**Comment by mrdudz** [comment]
calling variadic functions without prototype works only by accident even in "big" compilers, i could totally live with that generating an error (but not silently generating broken code)

**Comment by jmr** [comment]
> calling variadic functions without prototype works only by accident even in "big" compilers

I could be wrong, but my impression is it works because the caller usually cleans up, as opposed to the callee in cc65.

**Comment by mrdudz** [comment]
depends on the architecture, the number of parameters passed to variadic args, optimization options etc etc :)

**Comment by acqn** [comment]
What to do now?

**Comment by oliverschmidt** [comment]
I don't see the need to support undeclared variadic functions.

**Comment by polluks** [comment]
Yeah, no support for walking on thin ice ;-)

**Comment by acqn** [comment]
Should we ban the explicit but wrong prototype case?
```c
extern int printf();
printf("1234 == %d\n", 1234); 
```

**Comment by oliverschmidt** [comment]
If we don't ban this: Will we end up with a misadjusted stack?
* If yes: Please ban it.
* If no: If have no strong opinion.

**Comment by acqn** [comment]
It will: We will.

**Comment by jmr** [comment]
> Should we ban the explicit non-variadic declaration case?

It can't be banned for `--standard c89` or `c99` since it's part of the standard. I warning would be good, since it's really easy to make a mistake.

Banning it for `cc65` seems entirely reasonable since empty parentheses in function declarators are an obsolescent feature.

https://port70.net/~nsz/c/c89/c89-draft.html#3.9.4

**Comment by acqn** [comment]
Fortunately, C89 doesn't allow variadic functions to be declared with empty parameter lists, so that we can at least do:
```c
int main(void)
{
    f (x); /* Warning: Call to undeclared function */
    g (x); /* Warning: Call to undeclared function */
}

int f (int x) { return x; } /* OK */
int g (int x, ...) { return x; } /* Error: Conflicting function types for 'g' */
```
