### ISSUE TITLE
ca65: Error: Constant expression expected on macro using .if >(param)

### ISSUE THREAD

**Issue by frranck** [cc65/cc65#1266]
Hello,
If I'm using this macro
```
.macro TEST_MACRO param
.if >(param)
	NOP
.endif
.endproc
```
I'm getting an error if I call it like this:
```
TEST_PARAM = 42
TEST_MACRO param
```
_Error: Constant expression expected_
But I'm not getting any error on:
```
TEST_MACRO 42
```

**Comment by mrdudz** [comment]
What tells you that it should work in the first place? Seems to behave as expected :)

**Comment by frranck** [comment]
sorry I meant:
```
TEST_PARAM = 42
TEST_MACRO TEST_PARAM
```
doesnt work
```
TEST_MACRO 42
```
works. but both argument seem to be a constant for me.

**Comment by mrdudz** [comment]
~~~
.macro TEST_MACRO param
.if >(param)
	NOP
.endif
.endmacro ;<--------!!!

TEST_PARAM = 42
TEST_MACRO TEST_PARAM
~~~
works here :)

**Comment by frranck** [comment]
oh that was another typo.  I meant .endmacro

**Comment by frranck** [comment]
oups this small example is working fine you're right... brb

**Comment by frranck** [comment]
okey
```
START_Y = 16
DELTA_Y = 42
SET_NEXT_DECAL_Y = 2

TEST_MACRO (START_Y + DELTA_Y * 0 + SET_NEXT_DECAL_Y)
```
is giving me the  _Error: Constant expression expected_ error

**Comment by oliverschmidt** [comment]
```
.macro TEST_MACRO param
.if >(param)
	NOP
.endif
.endmacro

START_Y = 16
DELTA_Y = 42
SET_NEXT_DECAL_Y = 2

TEST_MACRO (START_Y + DELTA_Y * 0 + SET_NEXT_DECAL_Y)
```
works for me with the current head. Please re-open if you have come up with an example that actually exposes the issue you see.
