### ISSUE TITLE
HuC6280 TAM opcode issue

### ISSUE THREAD

**Issue by tvoybro** [cc65/cc65#1275]
TAM opcode produces wrong code. According to the pceasm, popular PC Engine asm compiler, this code:
```asm
tam #0; tam #1; tam #2; tam #3; tam #4; tam #5; tam #6; tam #7;
```
after compilation, should look like this:
```asm
tam #1; tam #2; tam #4; tam #8; tam #16; tam #32; tam #64; tam #128.
```
But, ca65 produces wrong code:
```asm
tam #0; tam #1; tam #2; tam #3; tam #4; tam #5; tam #6; tam #7;
=
tam #0; tam #1; tam #2; tam #3; tam #4; tam #5; tam #6; tam #7;
```
Since the mapper registers are named MPR0-MPR7, it stands to reason the programmer should use bank numbers instead of a bitmasks, so let me see if I have my facts straight.

**Comment by greg-king5** [comment]
ca65 uses a different syntax.  The operands of `TAM` and `TMA` must be bitmasks.  If you want to name a mapping register by its number, then you must use a mnemonic that has that number in it:
```asm
tam #%00100001  ; Transfer Accumulator into two Memory Page Registers
tam0
tam1
tam2
tam3
tam4
tam5
tam6
tam7

tma #%00001000
tma0
tma1
tma2
tma3
tma4
tma5
tma6
tma7
```
