### ISSUE TITLE
Can't use zero length structs

### ISSUE THREAD

**Issue by slembcke** [cc65/cc65#1279]
In my code I use empty structs as opaque types for a couple things:

* Data defined in / passed to assembly routines, such as music. ex: https://github.com/slembcke/critical-match/blob/master/src/shared.h#L13
* Sentinel types for state machine functions. (This forces tail calling to another state machine function that also returns the same sentinel type. ex: https://github.com/slembcke/critical-match/blob/master/src/main.c#L51 )

Apparently cc65 doesn't allow either usage anymore, and gives errors like the following.

```
src/shared.h(13): Error: Empty struct type '$anon-struct-000F' is not supported
src/shared.h(14): Error: Array of 0-size element type 'const struct $anon-struct-000F'
src/main.c(92): Error: Returning 'struct $anon-struct-0011' of this size by value is not supported
```
I'm relatively certain that empty structs are allowed by the spec, and using them as opaque types for symbols is pretty useful. On the other hand, I would understand if somebody rolled their eyes at my state machine code since tail calls are not guaranteed by the C spec anyway.

Git-bisect seems to implicate this commit, though I haven't looked into it any further yet or made a simple replication.

https://github.com/cc65/cc65/commit/9f67b45ea0abd003a42b241d86bc763ef51b60bc

**Comment by jmr** [comment]
`struct-declaration-list` can't be empty: https://port70.net/~nsz/c/c89/c89-draft.html#3.5.2.1

You could add `char _;` in your structs.

**Comment by acqn** [comment]
We could add support for empty structs some day, as it is a popular extension. The problem as I see is, what size should an empty struct have, 0 (as in many C compilers) or 1 (as in C++)?

**Comment by jmr** [comment]
> In my code I use empty structs as opaque types for a couple things:
> 
> * Data defined in / passed to assembly routines, such as music. ex: https://github.com/slembcke/critical-match/blob/master/src/shared.h#L13

I think this one can just be a forward declaration.

> * Sentinel types for state machine functions. (This forces tail calling to another state machine function that also returns the same sentinel type. ex: https://github.com/slembcke/critical-match/blob/master/src/main.c#L51 )

Does this really do something different from returning void?

**Comment by mrdudz** [comment]
pardon my ignorance, but whats the point of using an empty struct? in almost 3 decades of C programming i never used this, and i wouldn't know why i want it either *shrug*

**Comment by polluks** [comment]
@mrdudz Linux kernel style https://stackoverflow.com/q/24685399/1430535

**Comment by mrdudz** [comment]
That doesnt make it clear to me either, sorry :)

**Comment by oliverschmidt** [comment]
Maybe I'm missing the point but in code only intended for cc65 the cc65-extension `void` might be a replacement for empty structs.

**Comment by greg-king5** [comment]
> > In my code, I use empty structs as opaque types for a couple things:
> > 
> > * Data defined-in/passed-to Assembly routines, such as music, ex: https://github.com/slembcke/critical-match/blob/master/src/shared.h#L13
> 
> I think this one can just be a forward declaration.

Nope, cc65 won't let us declare _arrays_ of most incomplete types -- even if they're external, and the number of elements isn't specified.  (cc65 doesn't care that the size doesn't need to be known in that kind of declaration.)

> 
> > * Sentinel types for state machine functions. (That forces tail-calling to another state machine function that also returns the same sentinel type, ex: https://github.com/slembcke/critical-match/blob/master/src/main.c#L51 )
> 
> Does that really do something different from returning `void`?

If the function has automatic variables, then returning `void` will let cc65 tail-call a run-time library function that removes those variables from the C-stack.  But, returning "through" a call to another function might force cc65 to tail-call that other function instead.

However, making those functions return the `u8` type (instead of some opaque type) works just as well, and is simpler.

**Comment by slembcke** [comment]
Looking into it more, other compilers only seem to support them as an extension. So there's that...

> > In my code I use empty structs as opaque types for a couple things:
> > 
> > * Data defined in / passed to assembly routines, such as music. ex: https://github.com/slembcke/critical-match/blob/master/src/shared.h#L13
> 
> I think this one can just be a forward declaration.

Hmm. Actually you are right. I had declared them as arrays so that I had the address of the data and not an (opaque) value. In retrospect, I can still take the address of a forward declared struct explicitly. So maybe this is a non-use-case after all.

> > * Sentinel types for state machine functions. (This forces tail calling to another state machine function that also returns the same sentinel type. ex: https://github.com/slembcke/critical-match/blob/master/src/main.c#L51 )
> 
> Does this really do something different from returning void?

Not really. Like I said, it was just a way to get the compiler to force the convention of tail calling other state machine functions. Like I said, feel free to roll your eyes at my silly abuse of (mostly) undefined tail call behaviours.

After thinking on it for a while, I'm tempted to close this. My first use case turned out to be easy to work around, and the second is not a very good use case for adding them as an extension.
