### ISSUE TITLE
Referencing static locals in inline assembly is broken.

### ISSUE THREAD

**Issue by slembcke** [cc65/cc65#1280]
In the following function:
https://github.com/slembcke/critical-match/blob/master/src/grid.c#L69

I'm defining a  static local array and passing it to inline assembly using %v. This was working in the past, however now it seems to be passing the wrong symbol to the generated assembly and causing a link error. `asm("lda %v+0, x", ROW_ADDRS);` becomes `lda     L0001+0,x` when the symbol in the generated assembly for ROW_ADDRS is M0001.

I haven't had time to run a git bisect on this yet.

**Comment by acqn** [comment]
It's a bug in the asm parser. Will fix soon.
