### ISSUE TITLE
Problem w/ custom config

### ISSUE THREAD

**Issue by snhirsch** [cc65/cc65#1287]
I'm working on some fixes and additions to the CBM Commander application, which has compile flavors for all CBM system types.  Because of limited memory, I need to use overlays.  This seems to have opened Pandora's box.  I adapted the existing 'c64-overlay.cfg' for use with CBM (smaller memory) and named it 'pet-overlay.cfg' (in same directory as sources).  It seems you cannot use both -t and -C as args to cl65, but when I use '-C pet-overlay.cfg' some very odd things start happening:

- Something from the depths of cc65 starts insisting that OVL1.. through OVL9.. segments must exist.  I only need four, and that's all that are defined in my cfg file.

- Something, somewhere is now defining macros for every single CBM target.  The code has #ifdef conditionals all over it and expects exactly one of, e.g. __PET__, __C64__, etc.

What am I missing here?  How can I get the compiler pass to see the same defines that are brought in by '-t pet' while having the linker (a) use my custom cfg file and (b) link the appropriate CC65 runtime (e.g. pet.lib)?

**Comment by greg-king5** [comment]
**ld65** doesn't allow `-t` and `-C` at the same time.  But, **cl65** does allow them (it knows where to steer them).  In fact, **cl65** requires both of them for your Pet overlay project (**cl65** defaults to the C64 when `-t` isn't used).

P.S., The official upstream repository for CBM-Command is https://github.com/CBM-Command/CBM-Command.

**Comment by snhirsch** [comment]
Thanks, Greg. I'll re-check the steps I went through, but things really didn't seem to work properly when using -t and -C.  And, thanks for the pointer to the GitHub repository!  Very confusing situation with regard to upstream on this application.  Would have saved me a lot of work if I knew that was there :-).

Your reply didn't address the issue where CC65 seemed to require nine overly segments.  How can I work around that?

**Comment by mrdudz** [comment]
> Your reply didn't address the issue where CC65 seemed to require nine overly segments. 

That sounds like user error - i am using overlays extensively and no segment is even named "OVL..." :)

**Comment by snhirsch** [comment]
Thanks, Bob.  I struggled to find a _complete_ example of overlay implementation.  There are many out there, but all of them seem to miss one minor point or another.  Apparently, Payton Byrd published a comprehensive Blog article but it's not available anymore.  Would you mind sharing the cfg file and build commands you are using?  Another problem I encountered:  The cc65 linker is placing a load address of $6BF3 as the first two bytes of the overlay binary - and - using the same address as the entry point of the first function within it.  That doesn't seem correct.  Shouldn't it be loading at $6BF1 in order to properly locate the entry point?  I'll review things carefully, but this has been a frustrating exercise so far.  I appreciate your and Greg's willingness to help and I'm sure I'll get there eventually.

**Comment by mrdudz** [comment]
Eww, i dont think my cfg is very useful as an example... it's for a ROM image, uses banked memory and some other quirky things. Whats wrong with the existing overlay example?

**Comment by polluks** [comment]
@snhirsch Just for the record http://web.archive.org/web/20120519194205/http://www.paytonbyrd.com:80/BlogEngine.Web/post/2012/01/22/CC65-Using-Overlays.aspx

**Comment by snhirsch** [comment]
I modified the existing overlay example for CBM Pet, loading like this:
`    cbm_open(4, 8, 4, name);
    if (cbm_read(4, _OVERLAY1_LOAD__, _OVERLAY1_SIZE__) == 0) {
        log ("Loading overlay file failed");
        return 0;
    }
    cbm_close(4);
`
It does not work - just crashes into the monitor.

**Comment by greg-king5** [comment]
> Your reply didn't address the issue where CC65 seemed to require nine overlay segments.

I forgot about https://github.com/cc65/cc65/blob/master/libsrc/cbm/overlayaddr.s.  You're supposed to use it as a template.

Make a copy, and remove the segments that you don't need.  Put it in `"CBM-Command/cc65/cbm/"`.  Add this line to the list of `LIBFILES` in the Makefile:
```
cc65/cbm/overlayaddr.s \
```

**Comment by oliverschmidt** [comment]
> [...] You're supposed to use it as a template.

Hm, at least the C64 overlay sample doesn't do so...

**Comment by greg-king5** [comment]
I will try to make a `pet` library version of `cbm_load()` (and later, `cbm_save()`).  It will do pretty much what you tried to do with `cbm_read()`.

**Comment by snhirsch** [comment]
I'm having no luck whatever in getting that simple overlay demo to work on a PET (Vice emulation for now).

Attached are the cfg file (modified from c64-overlay.cfg and source I'm using.  Built this way (via Makefile):

[ovrldemo.tar.gz](https://github.com/cc65/cc65/files/5380939/ovrldemo.tar.gz)

cc65  -Ors --codesize 500 -T -g -t pet overlaydemo.c
overlaydemo.c(109): Warning: Converting pointer to integer without a cast
overlaydemo.c(118): Warning: Parameter 'name' is never used
ca65 overlaydemo.s
ld65  -o ovrldemo -C pet-overlay1.cfg -m ovrldemo.map overlaydemo.o pet.lib

It appears to succeed in loading the overlay, but crashes when the 'foo()' routine is called.

**Comment by snhirsch** [comment]
> > [...] You're supposed to use it as a template.
> 
> Hm, at least the C64 overlay sample doesn't do so...

Actually, it does produce overlay 1-9, with the last six being empty.  Defining __OVERLAYADDR__ in the cfg file pulls in overlayaddr.s.  Took a bit of deep searching to work that out.  And, as I mentioned above, the linker appears to be placing the wrong load address in the overlay binary.  Unless I throw away the address bytes the overlay entry point ends up two bytes higher than it should.

**Comment by snhirsch** [comment]
> @snhirsch Just for the record http://web.archive.org/web/20120519194205/http://www.paytonbyrd.com:80/BlogEngine.Web/post/2012/01/22/CC65-Using-Overlays.aspx

Thanks VERY much for that link.  Payton's article is helpful.

**Comment by snhirsch** [comment]
Still trying to work through some confusion about overlay location.  My attempt at adding overlays to CBM Commander has gotten a bit further, but still is not working.  The overlay loads into the correct place - if I stop the program after the read and dump the overlay range to binary from VICE monitor it's correct and intact.  However, the program crashes miserably when it's called.  Don't want to create a lot of noise here until I've carefully reviewed every assumption, but I am still puzzled about one thing:  Some early (2012) postings from Oliver appear to suggest that CBM overlays must be located _below_ the application (which I am not doing, since none of the examples did so).  Is that obsolete advice?  There was mention made of ".. runtime library assumptions".

Today I'll dip further into tracing and debugging using the VICE monitor.  Am I correct in assuming there's no way to do C-language source level debug?  And, maybe I'm still missing something, but I cannot find any way to generate a full listing showing the linked code locations.  Very difficult to figure out how the overlay code relates to original C source.

**Comment by oliverschmidt** [comment]
>>> [...] You're supposed to use it as a template.

>> Hm, at least the C64 overlay sample doesn't do so...

> Actually, it does produce overlay 1-9, with the last six being empty.

Jep. My understanding is that as long as you are willing to throw away those empty files there no need to fiddle with a custom `overlayaddr.s`.

**Comment by oliverschmidt** [comment]
> Some early (2012) postings from Oliver appear to suggest that CBM overlays must be located below the application (which I am not doing, since none of the examples did so). Is that obsolete advice? There was mention made of ".. runtime library assumptions".

Please consider

* https://github.com/cc65/cc65/blob/master/samples/overlaydemo.c
* https://github.com/cc65/cc65/blob/master/cfg/c64-overlay.cfg

as my only relevant statements regarding C64 overlays. https://github.com/cc65/cc65/blob/master/cfg/c64-overlay.cfg#L11 puts the overlays "above" the program.

**Comment by oliverschmidt** [comment]
> And, maybe I'm still missing something, but I cannot find any way to generate a full listing showing the linked code locations. Very difficult to figure out how the overlay code relates to original C source.

That's exactly what a map file is for.

**Comment by snhirsch** [comment]
> > And, maybe I'm still missing something, but I cannot find any way to generate a full listing showing the linked code locations. Very difficult to figure out how the overlay code relates to original C source.
> 
> That's exactly what a map file is for.

Sorry to be dense, but the map file I'm looking at has only public symbols.  There's no clear way I can see to relate addresses or assembly listings to individual lines of C code.  It's helpful, but single-stepping through hundreds of opcodes in search of where it blows up is a recipe for carpal tunnel syndrome.  But, again, I may be missing something obvious.

**Comment by snhirsch** [comment]
> > Some early (2012) postings from Oliver appear to suggest that CBM overlays must be located below the application (which I am not doing, since none of the examples did so). Is that obsolete advice? There was mention made of ".. runtime library assumptions".
> 
> Please consider
> 
>     * https://github.com/cc65/cc65/blob/master/samples/overlaydemo.c
> 
>     * https://github.com/cc65/cc65/blob/master/cfg/c64-overlay.cfg
> 
> 
> as my only relevant statements regarding C64 overlays. https://github.com/cc65/cc65/blob/master/cfg/c64-overlay.cfg#L11 puts the overlays "above" the program.

Ok, got it.  Thanks, Oliver!  I'm just trying to bound my problem as best I can.  From what I can see I'm doing everything right, but still it doesn't work.  I'll review absolutely every step and assumption I'm making (again) and post the relevant bits here if I continue to hit a brick wall.  Be assured that behind every concern or question I voice here is a big chunk of time spent on Google search and reading through online conversation.

**Comment by snhirsch** [comment]
> Nevermind... Too many hours going in circles. I have the demo working. Attached are the cfg file (modified from c64-overlay.cfg and source I'm using. Built this way (via Makefile):
> 
> [ovrldemo.tar.gz](https://github.com/cc65/cc65/files/5380990/ovrldemo.tar.gz)
> 
> cc65 -Ors --codesize 500 -T -g -t pet overlaydemo.c
> ca65 overlaydemo.s
> ld65 -o ovrldemo -C pet-overlay1.cfg -m ovrldemo.map overlaydemo.o pet.lib
> 
> As I thought, the linker is placing an incorrect address at the start of the overlay. It should be 0x7AF1, not 0x7AF3. I can work around that by reading and discarding the first few bytes.

The light finally went on...  I'm guessing the post-PET 'LOAD' routine does exactly this under the covers - reading and throwing away the first two bytes.  So, yes, it would be good to have a PET version implemented in terms of the open/read/close functions that do exist.

**Comment by greg-king5** [comment]
Here is another "I forgot" (I wonder how many other important things I've overlooked).  The `pet` and `c64` targets have very different start-up environments.  The `pet` start-up doesn't use the BSS/ONCE overlay scheme.  Therefore, you can't use "c64-overlay.cfg" as a starting-point for your cfg. file.  You must start with "pet.cfg", then add overlay support to it.

**Comment by snhirsch** [comment]
> Here is another "I forgot" (I wonder how many other important things I've overlooked). The `pet` and `c64` targets have very different start-up environments. The `pet` start-up doesn't use the BSS/ONCE overlay scheme. Therefore, you can't use "c64-overlay.cfg" as a starting-point for your cfg. file. You must start with "pet.cfg", then add overlay support to it.

Believe me I understand.  There's a limit to how much fine detail one can keep in the front of one's brain.  I'm just happy that folks are so good about responding here!

**Comment by snhirsch** [comment]
And... success!  I had been chasing my tail for so long and trying so many things that it proved best to go back to square one and start over.  This time, based on advice from Greg, Oliver and others, I based the configuration on pet.cfg and for whatever reason it does appear to be working now.  Thanks to everyone who chimed in and suffered through my endless questions.  

Now I have enough elbow room to add features to CBM Commander. First on the list is the ability copy REL files out to SEQ and vice-versa.  There are a handful of utilities for this purpose, but most were in BASIC - very slow and not ergonomic to use.  The only slick interfaces I saw were explicitly for C64 and C128.  Soon the PET will be able to get in on the act.

**Comment by oliverschmidt** [comment]
:-)

**Comment by groessler** [comment]
So, if you "diff" the old non-working config file to the new one you/we might learn what was wrong....

**Comment by snhirsch** [comment]
> So, if you "diff" the old non-working config file to the new one you/we might learn what was wrong....

In theory, but I literally tossed the work out and started over with a fresh Git checkout.  It was one of two things: I may have had the calculation wrong for determining start of overlay - and/or was trying to work with too small a stack setting.  At one point I was seeing overflow of BSS and stack was the only thing I could cut bytes from.  Either way the problem was between the chair and the keyboard.  Is there a Wiki for CC65 anywhere?

**Comment by polluks** [comment]
https://github.com/cc65/wiki/wiki/Home
