### ISSUE TITLE
No support for cbm_load() on PET?

### ISSUE THREAD

**Issue by snhirsch** [cc65/cc65#1288]
By default, it's not possible to successfully compile an application for CBM PET that uses 'cbm_load()' to read in overlays.  The symbol 'LOAD' (ROM entry point) is explicitly not available due to conditionals in asminc/cbm_kernal.inc.  According to the PET ROM disassembly, this entry point is very much present.  So, I modified the kernal defines and rebuilt the compiler.  After generating the program I discovered that it doesn't work, but I'm not sure why.  I call cbm_load( "myfile", 8, 0 ), which should bring in 'myfile' at the load address in its header.  However, when run I get 'press play on tape #10' displayed on the console.  Is this supposed to work?  If not, why not?  The ROM sources appear to have the ability to load from devices on the IEEE bus.

**Comment by polluks** [comment]
So which entry point do you use, will it work with BASIC 2 _and_ 4?

**Comment by oliverschmidt** [comment]
Fixed with https://github.com/cc65/cc65/commit/a25b28a9726c0e0c8c9c5201dcad2e00ba0f6a5d.

**Comment by snhirsch** [comment]
When the caller specifies an address, is throwing away the first two bytes still desired behavior?  I find it a bit unexpected.

**Comment by mrdudz** [comment]
the LOAD kernal function works that way, there generally is a 2 byte load address, and you can only tell it to override it (and in that case the first two bytes are "thrown away"),

**Comment by silverdr** [comment]
It might be unintuitive but that's the way LOAD works - the first two bytes of a LOADable file must not contain actual data. Therefore when supplying one's own LOAD address, whatever is in those two bytes has to be discarded.

**Comment by snhirsch** [comment]
Ah, ok.  Yes, it's a bit unintuitive.  Thanks for the clarification!

**Comment by greg-king5** [comment]
The `size` attribute sets the _maximum limit_ for a memory area.  The actual size, after linking, can be smaller.  The usual Pet BASIC stub has "SYS1037" which uses 12 bytes.  But, someone might want to move the start of BASIC RAM to a higher place (he might want to put something special in lower RAM).  Therefore, it's possible that the `SYS` address could need five digits (a header size of 13 bytes).  In "pet-overlay.cfg", I set 13 as the maximum size, put `"define=yes"` in the header definition, and started the next area at `"__HEADER_LAST__"`.  That means that `main` will start at the very next address, no matter what size the header happens to be.

"pet.cfg" is a very old-style configuration file; it hasn't been updated to any of the newer styles (notice that it doesn't have `STARTADDRESS:` in it).
`$7BF3` is a memory area _size_.  Adding that size to the start address (`$040D`) gives the high address limit of `$8000`.
"pet-overlay.cfg" calculates that number from parts of two expressions: `"HIMEM - __HEADER_LAST__"`.

**Comment by snhirsch** [comment]
Terrific explanation and quite helpful.  Thanks again, Greg.  I wasn't sure what __HEADER_LAST__ represented. Is there a master listing of linker-assigned suffixes?  I now know about 

- _LOAD__
-  _SIZE__
- _LAST__
- _RUN__
- _START__
- _LAST__

Are there more?  The documentation could benefit from a unified summary of generated suffixes that was independent of the individual topics.
