### ISSUE TITLE
GEOS, dio.h, and dio_open()

### ISSUE THREAD

**Issue by xlar54** [cc65/cc65#1289]
Using the code below, I get oserror 13 (Function not implemented):

    InitForIO();
    handle = dio_open(8);
    enabled = (_oserror == 13 ? 1 : 0);
    DoneWithIO();

(enabled = 1 after this).   According to the documentation dio.h functions are compatible with GEOS?

**Comment by polluks** [comment]
Pay attention the first device is zero, better getcurrentdevice(), because dio's numbering scheme has to be system independent. This hint should be part of the documentation.

**Comment by xlar54** [comment]
makes sense, thanks
