### ISSUE TITLE
o65 drivers should be USR type

### ISSUE THREAD

**Issue by polluks** [cc65/cc65#1290]
There's no load address, therefore no PRG.

**Comment by oliverschmidt** [comment]
Looking at

* https://github.com/cc65/cc65/blob/master/libsrc/cbm/filetype.s#L13
* https://github.com/cc65/cc65/commit/511b826dfd5f282c9de1539002d1090820807dee
* https://github.com/oliverschmidt/contiki/blob/master/tools/6502/Makefile#L430-L436

I favor SEQ over USR.

**Comment by mrdudz** [comment]
I fail to see how the filetype matters - either will work. In practise, anything that isnt prg in the directory just complicates things needlessly, imho.

**Comment by oliverschmidt** [comment]
Fixed with https://github.com/cc65/cc65/commit/095de4ea52c2b488182645fda8ae0b4f7ac5e1c8.

**Comment by polluks** [comment]
@mrdudz it's a simple protection "don't load me"
