### ISSUE TITLE
How to get complete listing file?

### ISSUE THREAD

**Issue by snhirsch** [cc65/cc65#1291]
Gentlemen:  I'm very sorry about the flurry of postings, but again I'm running into something that (a) doesn't seem to be doing what it's supposed to and (b) has no online discussion that I'm able to locate.  The docs indicate that placing, e.g. '-l list.txt' in the cl65 command line should be generating a listing file.  And, it does.  But unfortunately it contains only one library file and nothing else.  What am I not understanding?

**Comment by mrdudz** [comment]
Hard to tell without seeing exactly what you are doing.

perhaps  
`-Ln name                      Create a VICE label file`
is what you are looking for?

**Comment by snhirsch** [comment]
I was hoping for a listing of assembled output for alll modules in the project, but I'm guessing it only applies -l to the last (or first?) file processed by the make recipe.  It turns out that I needed to compile and assemble modules individually without using the cl65 driver.  And, the ability to add code as comments is exactly what I had been looking for.  Documentation for this could be improved - it says "..not typically needed", so I skipped by it thinking it was for CC65 developers rather than users.  

Please understand I'm not complaining :-).  If there is an active cc65 wiki, I'd be glad to fill in some of these blanks and help others avoid what has, so far, been an extremely steep learning curve.

**Comment by polluks** [comment]
Well, a listing file is for debug purposes. So you want to debug the whole project at once?

**Comment by shazz** [comment]
Hi, I think my question related.
When I'm using the `-l` it generates a listing for each segment but at this time the labels are not resolved so the bytecode looks like:
````
000005r 1  20 rr rr     start_perf:   jsr depack                    ; #6 - 3
````

I did not find a way to generate the listing AFTER linking, get the `rr` replaced and then to be sure the generated bytecode is the good one.
Anyway to do that ?

Thanks!

**Comment by oliverschmidt** [comment]
As far as I know there's no way to do that.

**Comment by shazz** [comment]
Ok so I need to use da65 I guess. Could it be a feature request ?

**Comment by oliverschmidt** [comment]
> Could it be a feature request ?

For sure. But I can't imagine it ever being implemented. The assembler doesn't know about the final locations (by design) and the linker doesn't know about the assembled source (by design).

**Comment by VladyslavKulichenko** [comment]
Hi, I have encountered a related issue.

I've tried to generate a handfull of output files for learning via this command:
```
cl65 -d -vm -t none -g -C config.cfg -l test.lst -Ln test.sym -m test.map -o test.bin test.s wrapper.s
```
Debug result is:
```
ca65 -v -g -l test.lst -t none -o test.s.8572.0.o test.s 
ca65 -v -g -l test.lst -t none -o wrapper.s.8572.1.o wrapper.s
ld65 -v -vm -Ln test.sym -m test.map -o test.bin -C config.cfg test.s.8572.0.o wrapper.s.8572.1.o none.lib
```
From what I understand, the modules` object files are dynamically named. And also the listing file is being constantly rewriten by the last (main file) of the buld process.

Two main suggestions:
- Let ca65 generate listing files the same dynamic way as the names of .o files.
- Fix cl65 listing file operations, so it would be a compilation of a temp ca65 listing files.

Please let me know if I am mistaken somewhere. Or there is a reason for listing to work this way? Could not find anything in the docs.
