### ISSUE TITLE
prefixed installation

### ISSUE THREAD

**Issue by norayr** [cc65/cc65#1292]
hello,
i did not find a way to use prefix, as usually with --prefix and did not find a prefix like variable in makefile.
i compiled the binaries, and afraid to do 'make install' because i'd like to not mix the package manager installed files and files compiled by me.
would you hint me how to make it and may be add to documentation?

**Comment by spiro-trikaliotis** [comment]
Hello,

* On Thu, Oct 15, 2020 at 11:22:48PM -0700 Norayr Chilingarian wrote:

> i did not find a way to use prefix, as usually with --prefix and did not find a
> prefix like variable in makefile.
> i compiled the binaries, and afraid to do 'make install' because i'd like to
> not mix the package manager installed files and files compiled by me.
> would you hint me how to make it and may be add to documentation?

both PREFIX and DESTDIR exist 

Have a look how it is done for the Debian packages (lines 44 to 46):
https://build.opensuse.org/package/view_file/home:strik/cc65/debian.rules?expand=1


Note that there are snapshot RPM and DEB of cc65 available, if you want
to make sure you do not mess with the package manager:

https://build.opensuse.org/package/show/home:strik/cc65 (click on
"Download package" on the upper right).

Regards,
Spiro.

-- 
Spiro R. Trikaliotis
https://spiro.trikaliotis.net/

**Comment by polluks** [comment]
The prefix option is part of configure but cc65 uses plain make.

**Comment by norayr** [comment]
yes, i know, i was downloading binary builds before.
also i don't use debian/ubuntu and my repos have no cc65.
so i have the options: to compile myself, or to download a binary build.
i was downloading binary builds before, but imagine i use some weird architectures, i'd like to compile the binaries on them, and install in /opt/cc65-version, as i do with all my custom packages.

ok thank you i managed to compile and install it to /opt/cc65 prefix.

**Comment by norayr** [comment]
i thought to write here how to make a prefixed build for others:
```
make PREFIX=/opt/cc65
sudo make PREFIX=/opt/cc65 install
```
