### ISSUE TITLE
Documentation issue : ChkDskGEOS() named incorrectly

### ISSUE THREAD

**Issue by xlar54** [cc65/cc65#1294]
Documentation says "**ChkDskGEOS**()"  while function is actuall called **ChkDkGEOS**(). (no 's')

The later is what it should be called per official documentation.

https://cc65.github.io/doc/geos.html#ss3.5

**Comment by oliverschmidt** [comment]
Fixed with https://github.com/cc65/cc65/commit/947dd9aca040076b3b073ce43951875a31dc48da.
