### ISSUE TITLE
[atari] wait_v_sync for the Atari target?

### ISSUE THREAD

**Issue by Fabrizio-Caruso** [cc65/cc65#1297]
I have not found `wait_v_sync` in https://github.com/cc65/cc65/tree/master/libsrc/atari
Is there a particular reason why it is absent?

I am not an Atari expert. 
Wouldn't a simple 
```
STA $D40A;  WSYNC $D40A Write
RTS
```
do the magic?

If an Atari expert here confirms it is a clean solution, I can do a PR with it.

**Comment by mrdudz** [comment]
Doesnt that wait for horizontal blank?

**Comment by Fabrizio-Caruso** [comment]
@mrdudz sorry I am a noob. You are right. Is there an easy solution for the vertical blank?

**Comment by Fabrizio-Caruso** [comment]
Probably waiting for $D40B (VCOUNT) to be zero?
@mrdudz would this be a clean acceptable solution for us?

**Comment by mrdudz** [comment]
I have no idea :) @groessler is the atari guy iirc

**Comment by Fabrizio-Caruso** [comment]
I am bad at Assembly.

Maybe something like?
```
LOOP: LDA $D40B     ;VCOUNT
          CMP #$C0      ;192
          BCC LOOP 
          RTS
```

**Comment by mrdudz** [comment]
if that is actually the "current rasterline" register, perhaps something like
```
bit $d40b
bcc *-3
bit $d40b
bcs *-3
```
...but as said, i am not into ataris, no idea if that makes sense

**Comment by Fabrizio-Caruso** [comment]
@mrdudz My code is crap indeed but shouldn't the vertical blank start just at the beginning of the lower border?
So I guess after line 192 but the value in $d40B is probably higher than 192 at line 192 as there is also an upper border...

**Comment by mrdudz** [comment]
The c64 function waits for rasterline 0 at least

**Comment by Fabrizio-Caruso** [comment]
@mrdudz I may be missing imoortant details. Why wait for the top screen if you can use the whole bottom border? Isn't a wait for vsync meant to tell you when you can start to modify the screen content? Let us say I have many elements to uodate on the screen and I want to do it in the same frame. I would start to do it after the last foreground line to have the most time.

**Comment by mrdudz** [comment]
vsync means to wait for the vertical blank, which is at the bottom of the entire screen. the WSYNC above doesnt wait for the start of the right border either for the same reason, but for the start of the next rasterline.

**Comment by polluks** [comment]
At least 192 is a bad idea because in NTSC the last line is 130 ;-)
"Vertical sync (VSYNC) occurs during the fourth through sixth lines of vertical blank (VCOUNT hex 7D through 7F). This tells the TV set where each frame starts."
http://krap.pl/mirrorz/atari/homepage.ntlworld.com/kryten_droid/Atari/800XL/atari_hw/antic.htm#General

**Comment by mrdudz** [comment]
PAL vs NTSC was also the reason for why the C64 function waits for line 0 rather that line 300 or whatever it is (on PAL). In any case, waiting for the start of the border is always wrong and unexpected. A simple screen flasher (like in my tetris thing) will look broken then :)

**Comment by mrdudz** [comment]
PS: maybe we can introduce a different function that by definition does what you want there. that function would have to handle PAL/NTSC differences, and probably other details (position/size of text window on vic20, for example).

**Comment by Fabrizio-Caruso** [comment]
@mrdudz you are perfectly correct: wait_v_sync should do what is supposed to do and wait for the start of the screen.
On the other hand, having a (possibly cross-target) function that tells you when you have just completed drawing the foreground would be practical in many use-cases.

**Comment by groessler** [comment]
A vertical blank creates a VBI (vertical blank interrupt) which in turn increments the RTCLOK ZP variable.
So a typical soution is

```
     LDA RTCLOK+2
L01: CMP RTCLOK+2
     BNE L01
```

This waits for the RTCLOK value to change. (Note that RTCLOK is a 3-byte variable which is stored in big-endian format.)

**Comment by Fabrizio-Caruso** [comment]
Thanks for the solution?
The Atari conio code lacks this function. Could we have it in the Atari conio lib as with most of the other targets?

**Comment by groessler** [comment]
I will add it...

**Comment by oliverschmidt** [comment]
We're talking about waitvsync() here, right?

> I will add it...

From my POV especially nice as together with https://github.com/cc65/cc65/commit/37107174c61425915b02c5f327cdfe9335da2cae this turns waitvsync() into an "often" available function.

**Comment by Fabrizio-Caruso** [comment]
@groessler I guess a similar solution is not possible for detecting when the (default size/no overscan) foreground has been drawn.
I see an even more common use-case for a function that detects the end of the foreground, i.e. start of lower border.
Let us say we are updating the positions of some objects on the screen and we do not want to miss a movement in a frame. A common solution is to update the screen memory when the raster reaches the start of the lower border.

**Comment by groessler** [comment]
@oliverschmidt: `waitvsync()`, yes
@Fabrizio-Caruso: It is possible by testing `VCOUNT` being bigger than (I guess)  (192 + 24)/2.

**Comment by Fabrizio-Caruso** [comment]
@oliverschmidt Sorry if I am introducing a different, yet similar, topic here.
Could wait_lower_border() be a new multi-target function in CC65?
Isn't it about a common use-case?

**Comment by oliverschmidt** [comment]
> Could wait_lower_border() be a new multi-target function in CC65?

I'm afraid there aren't enough targets allowing to implement such a function in order to make it attractive. However, I might be wrong. The only thing I can say for sure is that in the Apple II world already waitvsync() is a stretch (it's only avail for apple2enh, not apple2).

**Comment by Fabrizio-Caruso** [comment]
@oliverschmidt All Commodore except Pet and CBM610 should be able to do it, as well as Atari. I suppose nearly most consoles have something similar.

**Comment by groessler** [comment]
`waitvsync()` for Atari: PR #1309

**Comment by oliverschmidt** [comment]
Fixed with https://github.com/cc65/cc65/pull/1309.
