### ISSUE TITLE
[feature request, cl65] Passing -Dname=val automatically to assembler

### ISSUE THREAD

**Issue by YouDirk** [cc65/cc65#1301]
Hi me again :)

if I´m using CC65 such like `$> cl65 -c -DDEBUG -o interrupt.o interrupt.S` then the `-D` option does not have any effect. It does only work if the argument `-Wa` is prepended, such like `$> cl65 -c -Wa -DDEBUG  -o interrupt.o interrupt.S`. Then `.ifdef DEBUG` will be true inside interrupt.S.

It would be a nice feature, if the first version will be working too :)

**Comment by mrdudz** [comment]
That cant work... -D passes a define to the compiler, which will in turn generate a symbol for the assembler (with prepended underscore). So either use _DEBUG in your assembler code, or -Wa -D to pass the symbol to the assembler directly.

**Comment by YouDirk** [comment]
`_DEBUG` does not work. Neither as constant in `.ifdef` nor as a symbol in an argument of an instruction :/

**Comment by mrdudz** [comment]
If the compiler is not involved at all, use

```
 --asm-define sym[=v]          Define an assembler symbol
```

**Comment by YouDirk** [comment]
Another question: Is there a way to share constants between C and assembler files. With other compilers it is possible to use `#define` in header files and `#include` them. But `ca65` does not support preprocessing. What is a common practice to unique define constants? If have not found any well solution, only that I must define them twice: as *.h file and as *.inc file.

**Comment by mrdudz** [comment]
There is no "official" way to do this. I use a bit of sed magic in my makefile to generate .inc from .h

**Comment by YouDirk** [comment]
Yeah, the all-round tool `sed`. The powerfulst and compatiblest tool of the world :)
