### ISSUE TITLE
Getting rid of PREFIX on Linux outside of 'make install' (?)

### ISSUE THREAD

**Issue by oliverschmidt** [cc65/cc65#1303]
As far as I can see the PREFIX variable is outside of the `install` target only (?) necessary because we "bake" absolute paths into the binaries (like e.g. gcc does):

https://github.com/cc65/cc65/blob/master/src/Makefile#L23-L30
https://github.com/cc65/cc65/blob/master/src/Makefile#L65-L66

This is necessary to have the binaries find the headers and libraries. BTW: In former times also the absolute paths to cc65 and friends had to be given to cl65. But I changed that with https://github.com/cc65/cc65/commit/912b0d9e93876364e92909efc843dca0e9cb11a5. 

I'm not sure that everybody is aware this does **_NOT_** happen on Windows. Why? Because on Windows we have:

https://github.com/cc65/cc65/blob/153bb295010e2dc75ffd544d7091870ff563338d/src/common/searchpath.c#L162-L205

It uses `GetModuleFileName` (https://docs.microsoft.com/en-us/windows/win32/devnotes/-getmodulefilename) to determine the absolute path of the currently running binary. And based on that the absolute paths to the headers and libraries are built. That means you can copy a Windows cc65 directory tree where every you want and it'll just work. No env var or anything needed. If you are fine with calling cl65 with an absolute path there's no need to add any cc65 binary to the Windows PATH env var.

Why do we have this behavior only on Windows? Because in the *IX world there's no common way to determine the absolute path to the currently running binary. However, about everybody isn't using "some" *IX but Linux - and on Linux we for sure have `"/proc/self/exe"`. So given the popularity of Linux it might be worth to consider to expand the Windows approach to Linux.

As far as I can see that would result in the PREFIX variable to by only relevant for the `install` target.

As everybody knows I'm a Windows guy. So I'm not interested enough to do the above myself (if I would be, it would have been done years ago). However, I'm perfectly willing to merge a PR implementing it, however:

* The PR must (of course) match the usual "quality rules"
* I'm **_NOT_** interested in having this approach extended to "every" OS. Rather just Windows and Linux.

**Comment by mrdudz** [comment]
I don't see the point in this to be honest - you dont "copy around" binaries like that on *nix, they belong to their install location.

**Comment by mrdudz** [comment]
closing this - the way it is now makes this obsolete :)
