### ISSUE TITLE
surprising constant expression evaluation

### ISSUE THREAD

**Issue by jmr** [cc65/cc65#1310]
`255 * 255 == -511` is false. I guess this is standard-compliant, since it involves signed integer overflow, but it would be nicer if it (1) gave a warning (2) also evaluated to true, since `int x = 255; x * x == -511` and `int y = 255 * 255; y == -511;` are both true.

```
#include <stdio.h>

static unsigned char failures = 0;

int main (void)
{
    const int two_fifty_five = 255;
    const int two_fifty_five_squared = 255 * 255;

    if (255 * 255 != -511) {
        fprintf (stderr, "Expected 255 * 255 == -511, got: %d\n", 255 * 255);
        failures++;
    }
    if (two_fifty_five * two_fifty_five != -511) {
        fprintf (stderr, "Expected two_fifty_five * two_fifty_five == -511, got: %d\n",
                 two_fifty_five * two_fifty_five);
        failures++;
    }
    if (two_fifty_five_squared != -511) {
        fprintf (stderr, "Expected two_fifty_five_squared == -511, got: %d\n",
                 two_fifty_five_squared);
        failures++;
    }
    printf ("failures: %u\n", failures);
    return failures;
}
```

Gives:
```
Expected 255 * 255 == -511, got: -511
failures: 1
```

**Comment by acqn** [comment]
The LHS of the comparison has the mathematically correct result value `65025`, but the comparison itself ignores its type `int`. I think that suggests that the comparison should be fixed, right?

**Comment by jmr** [comment]
That might be one way, but seems like a patch in a place not related to the source of the problem.  Wouldn't it be cleaner if the constant evaluation stored the C correct int value of -511 rather than the mathematically correct value?

**Comment by jmr** [comment]
`1024U * 1024U` has similar problems and is not UB.

**Comment by acqn** [comment]
> 
> 
> That might be one way, but seems like a patch in a place not related to the source of the problem. Wouldn't it be cleaner if the constant evaluation stored the C correct int value of -511 rather than the mathematically correct value?
You have a good point. It looks clean (and even easier) just to cast the result value of the calculation to the type of the expression.
