### ISSUE TITLE
GEOSLib - end of directory / y reg 

### ISSUE THREAD

**Issue by xlar54** [cc65/cc65#1313]
When calling `Get1stDirEntry()` or `GetNxtDirEntry()`, the `y` register should contain if the end of the directory has been reached, but it doesnt appear this register is preserved:
```asm
_GetNxtDirEntry:
        jsr GetNxtDirEntry
        stx __oserror
        lda r5L
        ldx r5H
        rts
```
Here's info on the Assembly return values:

Returns:
- `x` error ($00 = no error).
- `r5` pointer to next directory entry within `diskBlkBuf`.
- `y` non-zero if end of directory reached.

Alters: `diskBlkBuf` directory block.
Destroys: `a`, `y`, `r1`, `r4`.

How can I access the `y` reg. value?  Or, does this need to be changed?

**Comment by xlar54** [comment]
_oserror doesnt appear to be impacted at end

**Comment by xlar54** [comment]
temp workaround:

curFileHandle = GetNxtDirEntry();
asm("sty $02");
eof = PEEK(2);

**Comment by greg-king5** [comment]
This might work:
```c
curFileHandle = GetNxtDirEntry();
asm("tya");
eof = __A__;
```

**Comment by polluks** [comment]
@greg-king5 Seems to be a hint for https://cc65.github.io/doc/geos.html#ss3.6

**Comment by oliverschmidt** [comment]
Maybe I'm missing the point, but...

What value has R5, when Y is non-zero? I presume that the author of _GetNxtDirEntry presumed that it would be zero.

In case his presumption was wrong, I suggest to change _GetNxtDirEntry so that it checks Y and loads AX with zero instead of the content of R5 when Y is non-zero. Wouldn't that cause _GetNxtDirEntry to behave as intuitively expected?

BTW: The same question/answer maybe/likely holds true for _Get1stDirEntry.

**Comment by polluks** [comment]
_Get1stDirEntry does not return Y.
However dealing with registers if we already have a C function is... suboptimal.
````
4:	jsr GetNxtDirEntry
	bnex @7
	tya
	beq @1
	ldx #FILE_NOT_FOUND
...
````
https://github.com/geos64128/geos/blob/2090bca64fc2627beef5c8232aafaec61f1f5a53/kernal/files/files6c.s#L92

**Comment by oliverschmidt** [comment]
> However dealing with registers if we already have a C function is... suboptimal.

Please elaborate what you want to express with your statement. Didn't I already suggest a way to stay clean from register access and instead encapsulate the aspect in the C function ?!?

**Comment by polluks** [comment]
@oliverschmidt no no, full acknowledge

**Comment by oliverschmidt** [comment]
Okay, so we're left with the question I asked above. What value has R5 after reaching the end of the directory with GetNxtDirEntry? Zero?

**Comment by greg-king5** [comment]
> Okay, so we're left with the question I asked above: What value has `R5` after reaching the end of the directory with `GetNxtDirEntry()`? Zero? Does anybody know? Can someone test?

It's invalid (it points beyond the directory buffer).

**Comment by oliverschmidt** [comment]
Thanks for the info. So do we agree that

```
_GetNxtDirEntry:
        jsr GetNxtDirEntry
        stx __oserror
        tya
        beq :+
        lda #$00
        tax
        rts
:       lda r5L
        ldx r5H
        rts
```

is to be considered the appropriate fix?

**Comment by polluks** [comment]
...or `jmp return0` and save a byte?

**Comment by greg-king5** [comment]
Yes, but when either .X or .Y is non-zero.

**Comment by oliverschmidt** [comment]
Hm, but then the check for X should be made in _Get1stDirEntry too for consistency reasons, shouldn't it?

**Comment by greg-king5** [comment]
> Hm, but then the check for X should be made in _Get1stDirEntry too for consistency reasons, shouldn't it?

Yes.

**Comment by xlar54** [comment]
thanks guys for review.  good to see geoslib gets attention.  im working on (what I consider to be) an ambitious project, and cc65 + geoslib has made it great to work with

**Comment by oliverschmidt** [comment]
Supposed to be fixed with https://github.com/cc65/cc65/commit/d8e6fa61bbcbb86c7bcf287a988f42246f22376f. However, totally untested - so I'd really appreciate feedback.

**Comment by oliverschmidt** [comment]
> thanks guys for review. good to see geoslib gets attention. im working on (what I consider to be) an ambitious project, and cc65 + geoslib has made it great to work with

Thanks for the nice feedback. I personally think that cc65 GEOS support rather suffers from usage than from attention.

Is your project open source? If yes, please report back when it is finalized. It would go into https://github.com/cc65/wiki/wiki/Applications-written-in-C-or-C-with-assembler and I personally might get interested in trying to port it to Apple II GEOS.

**Comment by xlar54** [comment]
Sure.  Its basically a recreation of 64's DESK TOP in cc65:  https://github.com/geos64128/geos-desktop2.1-master

**Comment by polluks** [comment]
@oliverschmidt I made a ticket especially for you ;-) https://github.com/geos64128/geos-desktop2.1-master/issues/3
We need a real world application beside `samples/geos/`...

**Comment by oliverschmidt** [comment]
;-)

**Comment by greg-king5** [comment]
> Supposed to be fixed with d8e6fa61bbcbb86c7bcf287a988f42246f22376f. However, totally untested -- so, I'd really appreciate feedback.

The branches were backwards.  Therefore, EOF was tested only if there was a disk error.
I fixed the fix, and expanded the GEOSLib document: aad17a6f057dc57424c010c0d832e1f49592f044.

**Comment by oliverschmidt** [comment]
Thanks a lot!

**Comment by oliverschmidt** [comment]
@xlar54: Could you please acknowledge that this issue is to be considered as fixed?

**Comment by xlar54** [comment]
Yep, thank you all
