### ISSUE TITLE
Certain 1 character label names complain "Error: Unexpected trailing garbage characters"

### ISSUE THREAD

**Issue by christetreault** [cc65/cc65#1317]
Hi, I'm seeing an issue with certain one character label names. If I assemble a file that contains (as a minimal example)

```
; foo.s
f:
```

```
$ ca65.exe --cpu 65816 foo.s -o foo.o
foo.s(2): Error: Unexpected trailing garbage characters
```

However, if I rename the label, sometimes it works. Playing around with it a bit, (in 65816 mode) I've had `g` work, but `a`, `s`, `f`, and `z` do not. Adding extra characters to the label (such as changing `s` to `sad`) works. The set of bad names seems to change based on the value passed to `--cpu`. You can use `s` with `--cpu 6502` but not `--cpu 65816`.

This is tested using a Windows 10 machine. I've tried it using both the cygwin shell and powershell, and see the same behavior.

```
$ ca65.exe --version
ca65.exe V2.18 - Git 03b37cf
```

Thanks!

**Comment by oliverschmidt** [comment]
As far as I can see the question has been answered in quite some detail so it's appropriate to close this issue.

@mrdudz: Maybe you want to open an enhancement issue regarding your proposal.

**Comment by christetreault** [comment]
Thanks for the confirmation. My assumption was that something like this was happening, but I did not want "to tell the doctor how to do their job"

I'll open an enhancement request to add better handling for this.
