### ISSUE TITLE
Question re: character encoding on CBM

### ISSUE THREAD

**Issue by snhirsch** [cc65/cc65#1323]
I'm currently working on some enhancements to CBM Commander and am coding a feature that reads out the contents of a REL file to SEQ, adding a header holding the original file name, record size and record count.  A complementary feature reads this back using the header information to create the target REL file.  It's all working as intended with one exception.  I have a REL file named 'os9 drive a'.  CBM Commander obtains this name by reading a directory scan and holds it in a data structure.  I write that string to the file header.  Examining the resulting file under Linux, I find it in uppercase 'OS9 DRIVE A'.  This makes sense since it was originally in PETSCII.  Here's the problem:  On the return trip I read this string in and use it to create the target REL file.  That file ends up in _uppercase_ when created on the CBM media!  Why is it not being recreated in the original lower case?  I'm performing no explicit conversion at any point and am simply letting CC65 manage it.  Would appreciate any insights!

**Comment by mrdudz** [comment]
you got to give a complete example... where are you reading the filename from ? it sounds like you read it from a native directory (using VICE)?

**Comment by snhirsch** [comment]
Fair enough.  I'll cook up a small test case and post it.  No native directory involved, though.

**Comment by snhirsch** [comment]
Blast.  A small standalone test case that's nominally performing all the same operations does not show the issue.  Color me confused.  Let me go back to the code in context and see if there's something going on I hadn't noticed.

**Comment by snhirsch** [comment]
Apologies to all for the extraneous noise.  This was a dumb error on my part that I must have looked at a dozen times and didn't see.

**Comment by mrdudz** [comment]
:) closing then :)
