### ISSUE TITLE
Atari: can set_chbase (chargen_reloc) be skipped when __CHARGEN_SIZE__ is 0?

### ISSUE THREAD

**Issue by 8bit-Dude** [cc65/cc65#1327]
This one is for Chris again.

I am implementing a charmap mode in 8bit-Unity (Graphics 12/ANTIC 4), and using a DLI to swap between CharSets.

But I have an issue with the atarixl_largehimem config: the chargen_reloc function is interferring with me trying to set the CharSet address.

Would it be possible to add a couple of lines that checks __CHARGEN_SIZE__, and skips reloc if it is 0?

Cheers,
Tony

**Comment by groessler** [comment]
Hmm. I think you're anyway recompiling/(building a custom runtime lib.

Doesn't it work if you just don't define `CHARGEN_RELOC`?

**Comment by 8bit-Dude** [comment]
Yes that is what I did, and it works. 
But I think it would be nice to have a single lib that supports all possible scenario:
  - Standard atarixl config
  - Largehimem config (relocated chargen)
  - Largehimem config (no chargen)

**Comment by groessler** [comment]
I prefer compile time knobs instead of runtime tests which take space and time.

I seen that you changed the subject of this issue. I'm afraid, I think there is no way to do this automatically at link time. Testing for zero or not would need to be done at runtime, introducing space and speed overhead.

**Comment by oliverschmidt** [comment]
As far as I see this issue is sort of between a question and a proposal. @groessler answered the question and argued against the proposal. So from my POV this issue is 'done'.

**Comment by 8bit-Dude** [comment]
Fair enough.  I will compile and use 2 different libs in 8bit-Unity, it is not a big deal.
