### ISSUE TITLE
[question][conio][screen codes] How can I use conio to display specific characters?

### ISSUE THREAD

**Issue by Fabrizio-Caruso** [cc65/cc65#1333]
I am (also) using CONIO to display some user-defined characters which I can display by poking their screen codes into video memory.

How can I use CONIO to display them? It seems CONIO is doing some conversion.
Can I display all of them? e.g., srceen code 0? screen code 27?

**Comment by mrdudz** [comment]
conio does implicit conversion, eg on C64 it takes petscii as input, and puts screencodes on the screen - you can't put arbitrary (nor all) screencodes on screen with it.

**Comment by oliverschmidt** [comment]
> you can't put arbitrary (nor all) screencodes on screen with it.

The details depend obviously on the target at hand. On the Apple II you can since https://github.com/cc65/cc65/commit/f8c6c58373426551eed096dcfab4eab137fc0430 put about everything on the screen using CONIO.

**Comment by oliverschmidt** [comment]
The question seems to be answered.

**Comment by mrdudz** [comment]
> > you can't put arbitrary (nor all) screencodes on screen with it.
> 
> The details depend obviously on the target at hand. On the Apple II you can since [f8c6c58](https://github.com/cc65/cc65/commit/f8c6c58373426551eed096dcfab4eab137fc0430) put about everything on the screen using CONIO.

sure, but then it is target specific behaviour and nothing you should rely on in a portable program - and in a non portable program, there is likely a better way for direct video memory access.

**Comment by oliverschmidt** [comment]
In general for sure. However, at least on the Apple II CONIO is a VERY attractive screen I/O option even for Apple II-only programs.

**Comment by Fabrizio-Caruso** [comment]
For example, for the CBM targets, how are screen codes mapped to characters I can print with cputc?
Let us say I redefined screen code X, which character should I use to print it with cputc?

**Comment by polluks** [comment]
I don't see much conversion in c64/cputc.s beside mrdudz's friend 𝜋.

**Comment by mrdudz** [comment]
oh please.

the long answer is, you cant directly print all screencodes with cputc. half of the screencodes are inverted characters, which you must print in revers mode. some others (like pi) are mapped in a weird non logical way.

here is a table (i have not verified if it is correct): https://www.c64-wiki.de/wiki/PETSCII-Tabelle

as redefining characters is already very target specific territory, i would totally drop conio and make my own print routines that work completey based on screencodes

**Comment by greg-king5** [comment]
Try this macro:
```c
#define cputdirect(sc) \
    asm ("lda #%b", (unsigned)(sc)); \
    asm ("jsr cputdirect")
```
