### ISSUE TITLE
C99 code

### ISSUE THREAD

**Issue by polluks** [cc65/cc65#1335]
gcc 4.2.1
````
cc65/datatype.c: In function ‘GetFullTypeNameWestEast’:
cc65/datatype.c:127: error: ‘for’ loop initial declaration used outside C99 mode
cc65/datatype.c: In function ‘PrintFuncSig’:
cc65/datatype.c:605: error: ‘for’ loop initial declaration used outside C99 mode
````

**Comment by oliverschmidt** [comment]
You need to elaborate on this issue in order to allow me to classify it.

**Comment by polluks** [comment]
Well, these are the only C99 declarations (inside of a for loop) of the whole project. I suppose we don't want this dependency.

**Comment by oliverschmidt** [comment]
So you are saying that those two locations keep the cc65 codebase from being compatible with pre-C99 compilers, right?

**Comment by oliverschmidt** [comment]
Fixed with https://github.com/cc65/cc65/commit/116682c19022ff6d7e314569c62b15cb31fd4215.
