### ISSUE TITLE
CI results not reported in PRs

### ISSUE THREAD

**Issue by jmr** [cc65/cc65#1338]
It looks like travis-ci has been partially switched over to github actions, but it looks like no tests are actually running.

https://github.com/cc65/cc65/pull/1331/checks

`Workflow runs completed with no jobs.`

**Comment by oliverschmidt** [comment]
> t looks like travis-ci has been partially switched over to github actions

What makes you think so? Travis-CI and GitHub actions are totally unrelated.

> but it looks like no tests are actually running

What makes you think so? The tests are still triggered and are still running. The only thing being unreliable from my POV in the recent past is reporting back of test results into PRs.

> https://github.com/cc65/cc65/pull/1331/checks

What makes you think you could see something interesting here?

**Comment by jmr** [comment]
> > https://github.com/cc65/cc65/pull/1331/checks
> 
> What makes you think you could see something interesting here?

I thought this is where I used to look to see the travis-ci results, but I was apparently wrong about that. There's a completely unrelated "show all checks" link that's no longer appearing in the PRs. What happened to it?

**Comment by oliverschmidt** [comment]
> There's a completely unrelated "show all checks" link that's no longer appearing in the PRs. What happened to it?

I've seen that disappear and later reappear in the past. I presume that a migration to GitHub Actions is due in the long run. I've looked into that task and it seemed more than complex enough to be put off.
