### ISSUE TITLE
[bug/info][creativision] Frozen screen with graphics glitches with initialization in main but OK with global initialization

### ISSUE THREAD

**Issue by Fabrizio-Caruso** [cc65/cc65#1339]
There may be a problem with array initialization with the creativision target (same code OK on other targets)

In:
https://github.com/Fabrizio-Caruso/CROSS-LIB/blob/master/src/games/bomber/main.c

I get a working binary if I use:
```
const Image *building_images[] = {
    &WALL_1_IMAGE, &WALL_2_IMAGE, 
    &TWO_WINDOW_WALL_1_IMAGE, &TWO_WINDOW_WALL_2_IMAGE, 
    &THREE_WINDOW_WALL_1_IMAGE, &THREE_WINDOW_WALL_2_IMAGE, 
    &SMALL_TWO_WINDOW_WALL_1_IMAGE, &SMALL_TWO_WINDOW_WALL_2_IMAGE
    };

int main(void)
{        
    ...
```

I get a frozen and corrupted screen for the Creativision (but not for other targets) if I move the init inside main:
```
int main(void)
{ 

const Image *building_images[] = {
    &WALL_1_IMAGE, &WALL_2_IMAGE, 
    &TWO_WINDOW_WALL_1_IMAGE, &TWO_WINDOW_WALL_2_IMAGE, 
    &THREE_WINDOW_WALL_1_IMAGE, &THREE_WINDOW_WALL_2_IMAGE, 
    &SMALL_TWO_WINDOW_WALL_1_IMAGE, &SMALL_TWO_WINDOW_WALL_2_IMAGE
    };
       
    ...
```
(removing `const` gives a black screen with initialization in the `main` function)

I have attached the binaries and the map files for the two cases:
[KO_INIT_IN_MAIN_mapfile.txt](https://github.com/cc65/cc65/files/5545314/KO_INIT_IN_MAIN_mapfile.txt)
[OK_GLOBAL_INIT_mapfile.txt](https://github.com/cc65/cc65/files/5545315/OK_GLOBAL_INIT_mapfile.txt)
[test.zip](https://github.com/cc65/cc65/files/5545316/test.zip)

![image](https://user-images.githubusercontent.com/29057615/99235563-4d76c700-27f6-11eb-9430-e36090672c02.png)

**Comment by groessler** [comment]
I don't know the rest of your program (memory usage), but I guess this is more or less expected. The Creativision just has ~512 byte for stack and heap and (writable) program data altogether.

**Comment by Fabrizio-Caruso** [comment]
@groessler you are right. Sorry for this non-issue.
It is fixed by increasing the stack size.

**Comment by groessler** [comment]
I don't understand why you want to put it inside main(). I gives worse code.

**Comment by Fabrizio-Caruso** [comment]
@groessler the reason is that lcc1802 cannot currently compile it correctly for the RCA COSMAC 1802 targets with roms such as Cidelsa arcade boards or RCA Studio...
The problem is to tell LCC on how to store in ROM something that the init code has to copy into ram afterwords.

**Comment by polluks** [comment]
@Fabrizio-Caruso You may check for __CC65__ and support both compilers individual.

**Comment by Fabrizio-Caruso** [comment]
@polluks My universal library already does __CC65__ but my code has to use the abstraction. I do not want to have #if defined(__CC65__) inside the code. It would not longer be universal. 
The problem I have with LCC is that for ROM targets it is not generating globabl initialization code that goes into the ROM and that it is copied into RAM at start-up.
How is CC65 doing this? Is the crt0.c taking care of copying global initialization from ROM into RAM?

**Comment by oliverschmidt** [comment]
> [...] generating globabl initialization code [...]

There seems to be a misunderstanding. A C compiler (in contrast to a C++ Compiler) doesn't generate global initialization __*code*__. All global initialization happens a compile time and the resulting __*data*__ is stored in the binary.

> Is the crt0.c taking care of copying global initialization from ROM into RAM?

That depends on the target. As you already know that it is supposed to be done in crt0 you might try to find the answer yourself. Doesn't

```
; Copy data from ROM to RAM
jsr     copydata
```

from https://github.com/cc65/cc65/blob/master/libsrc/creativision/crt0.s#L37-L38 promising?

**Comment by greg-king5** [comment]
That `copydata` subroutine imports some symbol names from ld65.  This line exports those names:
https://github.com/cc65/cc65/blob/b65981fc3a0d4a7903c9b2800b03959c9f368b89/cfg/creativision.cfg#L13

**Comment by groessler** [comment]
> My universal library already does CC65 but my code has to use the abstraction. I do not want to have #if defined(CC65) inside the code. It would not longer be universal.

I think it could still be "universal". Provide a consistent interface, but do things differently under the hood.

**Comment by Fabrizio-Caruso** [comment]
@groessler  indeed my lib does different things under the hood but the game code cannot do things like that
