### ISSUE TITLE
[question] Why are some bytes at the end of the binary corrupted?

### ISSUE THREAD

**Issue by Fabrizio-Caruso** [cc65/cc65#1343]
I don't understand why the memory aread CHARMEM (at the end of the binary) has a couple of corrupted bytes at its very end. Is CC65 using the end of its binary to store something?
I am placing the stack before CHARMEM just after MAIN.
I use CHARMEM to store some user-defined characters whose definitions are linked from an Assembly file (with just `.byte` directives).
 
Is there something clearly wrong in my cfg file?
```ini
SYMBOLS {
    __LOADADDR__:  type = import;
    __EXEHDR__:    type = import;
    __STACKSIZE__: type = weak, value = $0040;
    __UDC_START__: type = weak, value = $3E08;
    __MAIN_START__: type = weak, value = __UDC_START__ - $100D;
}
MEMORY {
    ZP:       file = "", define = yes, start = $0002, size = $001A;
    LOADADDR: file = %O,               start = $0FFF, size = $0002;
    HEADER:   file = %O,               start = $1001, size = $000C;
    MAIN:     file = %O,               start = $100D, size = __MAIN_START__ - __STACKSIZE__, fill = yes;
    DUMMY:    file = %O,               start = __UDC_START__ - __STACKSIZE__ - 1, size = __STACKSIZE__, fill = yes;
    CHARMEM:  file = %O, define = yes, start = __UDC_START__, size = $01F8, type = rw;
}
SEGMENTS {
    ZEROPAGE: load = ZP,       type = zp;
    LOADADDR: load = LOADADDR, type = ro;
    EXEHDR:   load = HEADER,   type = ro;
    STARTUP:  load = MAIN,     type = ro;
    LOWCODE:  load = MAIN,     type = ro,  optional = yes;
    ONCE:     load = MAIN,     type = ro,  optional = yes;
    CODE:     load = MAIN,     type = ro;
    RODATA:   load = MAIN,     type = ro;
    DATA:     load = MAIN,     type = rw;
    INIT:     load = MAIN,     type = bss;
    BSS:      load = MAIN,     type = bss, define   = yes;
    UDCCHAR:  load = CHARMEM,  type = ro, define = yes, optional = no;
}
...
```

**Comment by greg-king5** [comment]
ld65 puts into the file only what you explicitly tell it to put there.  Any corrupted bytes are coming from `UDCCHAR:`.  Check your sources.  Find every mention of the `UDCCHAR` segment.  Maybe, more than one place in your sources is stuffing things into that segment.

`__MAIN_START__` is a confusing name (it's a size, not an address).  `__MAINSIZE__` is a better spelling.

If you don't put anything into `DUMMY:`, then its start address doesn't matter; you may as well use `$0000`.  (Its filled size is what matters to `CHARMEM:`.)

**Comment by groessler** [comment]
@Fabrizio-Caruso, do you talk about the binary file/rom-image where some bytes are corrupted, or at run-time?

In the run-tme case, it could very well be that the stack is too small and overflows ("underflows") into MAIN.

**Comment by Fabrizio-Caruso** [comment]
@groessler  I was getting two corrupted bytes at the end of CHARMEM. There is nearly no stack used in the code. Moreover the stack is below CHARMEM and the stack is supposed to grow downwards. The stack is in DUMMY and may touch MAIN. I am now trying to reproduce it... GRRRR......

**Comment by Fabrizio-Caruso** [comment]
@groessler I get the problem ONLY on a 16K C16.
Are the last couple of bytes of available RAM on the C16 used for something by the kernel?

![image](https://user-images.githubusercontent.com/29057615/99434719-61fab280-290f-11eb-8ba0-9533cdc8280b.png)

**Comment by mrdudz** [comment]
> Are the last few couple of bytes of available RAM on the unexpanded C16 used for something by the kernel?

the last couple bytes in BASIC memory are used by the kernal to store the filename for LOAD. it could be that perhaps? you should be able to use the VICE monitor to find out what ends up there afterall.

i'd swap your DUMMY and STACK area around, so stack lives at the memory top

**Comment by groessler** [comment]
Is it correct that you see the problem at runtime only?

Then, as @mrdudz said, it should be easy. Set a breakpoint in VICE when to one of the bad bytes is written to.

**Comment by Fabrizio-Caruso** [comment]
The problem is that the kernal is writing there. Disabling interrupts may work but it breaks the keyboard routines...
