### ISSUE TITLE
More consistent configs

### ISSUE THREAD

**Issue by polluks** [cc65/cc65#1345]
Maybe
start → offset
VECTOR → VECTORS
````
grep VECTOR cfg/*
cfg/atari2600.cfg:    VECTORS:  load = ROM,            type = ro,                                start = $FFFA;
cfg/creativision.cfg:    VECTORS:  load = ROM, run = RAM, type = rw,  define = yes;
cfg/nes.cfg:    VECTORS:  load = ROMV,            type = rw;
cfg/pce.cfg:    VECTORS:  load = ROM,             type = ro,  start = $FFF6;
cfg/supervision-128k.cfg:    VECTOR:   load = ROM,      type = ro,                  offset = $3FFA;
cfg/supervision-16k.cfg:    VECTOR:   load = ROM,            type = ro,  offset   = $3FFA;
cfg/supervision-64k.cfg:    VECTOR:   load = ROM,      type = ro,                  offset = $3FFA;
cfg/supervision.cfg:    VECTOR:   load = ROM,            type = ro,  offset   = $7FFA;
````

**Comment by greg-king5** [comment]
> ```
> $ grep -rF "VECTOR" cfg
> cfg/atari2600.cfg:    VECTORS:  load = ROM,            type = ro,                                start = $FFFA;
> cfg/creativision.cfg:    VECTORS:  load = ROM, run = RAM, type = rw,  define = yes;
> cfg/nes.cfg:    VECTORS:  load = ROMV,            type = rw;
> cfg/pce.cfg:    VECTORS:  load = ROM,             type = ro,  start = $FFF6;
> cfg/supervision-128k.cfg:    VECTOR:   load = ROM,      type = ro,                  offset = $3FFA;
> cfg/supervision-16k.cfg:    VECTOR:   load = ROM,            type = ro,  offset   = $3FFA;
> cfg/supervision-64k.cfg:    VECTOR:   load = ROM,      type = ro,                  offset = $3FFA;
> cfg/supervision.cfg:    VECTOR:   load = ROM,            type = ro,  offset   = $7FFA;
> ```

I agree with `VECTOR → VECTORS`.  But, I think that `offset → start` makes more sense.  Those vectors sit at fixed hardware-dictated addresses.

**Comment by oliverschmidt** [comment]
> I agree with VECTOR → VECTORS.

+1

> But, I think that offset → start makes more sense. Those vectors sit at fixed hardware-dictated addresses.

+1

`offset` rather means relative to some base (that might change) while we have an absolute value here.

@polluks: Given that you (or rather your alter ego) recently provided a pull request I'd appreciate if you would provide another one for `VECTOR → VECTORS` & `offset → start`.

**Comment by polluks** [comment]
@oliverschmidt I will tell it to my sockpuppet.
