### ISSUE TITLE
When will the next release be made?

### ISSUE THREAD

**Issue by krischik** [cc65/cc65#1347]
V2.18 is almost 1½ years old. The documentation already describes new functionality (like `.org` in `.struct`). So I wonder when the next release will be published so one can start using the new features.

**Comment by mrdudz** [comment]
Whats stopping you from using the new features now?

**Comment by krischik** [comment]
The lack of a tar.gz file to download:

![image](https://user-images.githubusercontent.com/685853/99686806-3f3dda80-2a84-11eb-8524-d1f7805a3f9d.png)

To be used in a package manager:

https://github.com/macports/macports-ports/pull/8629
https://github.com/macports/macports-ports/blob/40083342a4f499a65587406d8e6087c666ff4988/lang/cc65/Portfile

**Comment by spiro-trikaliotis** [comment]
I know that MacPorts for OpenCBM uses the git repository of github directly. Thus, a source code archive is not necessary.

**Comment by polluks** [comment]
Maybe after #1308 and #1310 it's time for version 3.0 because of the massive internal changes.

**Comment by oliverschmidt** [comment]
I certainly don't see the current HEAD as a candidate for a new release. In contrast to all recent years this year has seen significant work at the C compiler. From my perspective this is current 'work in progress'.

However, I could imagine very well to tag https://github.com/cc65/cc65/commit/555282497c3ecf8b313d87d5973093af19c35bd5 from May 30 2020 as 2.19:

* That is just before the loads of compiler commits began.

* That includes four compiler commits which I believe can be considered clean (and thus desirable) fixes:
  * https://github.com/cc65/cc65/commit/dc5114b0713fd4a8294e81dab83b8ecb59813d41
  * https://github.com/cc65/cc65/commit/6d530931bfc58c925107d2cae10bc2ebe067217b
  * https://github.com/cc65/cc65/commit/9559625ee874434dff7a015191cb14e2303b96b3
  * https://github.com/cc65/cc65/commit/5b11eb4bb95a9982f33f2c580318202afc0b0882

* That happens to be exactly one year after 2.18.

Open for comments...

**Comment by krischik** [comment]
@spiro-trikaliotis True, MacPorts can use a git repository directly. But that is considered a “last resort” and you would still need a tag or commit-id to get a stable version.

@oliverschmidt sounds good to me. I would not want to update MacPorts with a unstable “work in progress” C compiler.

**Comment by oliverschmidt** [comment]
I just created the Git tag and the GitHub release - https://github.com/cc65/cc65/releases/tag/V2.19

I added the following text to the release:

__*NOTE*__: The programs in release __V2.19__ report their version as `V2.18 - Git 55528249`.

**Comment by spiro-trikaliotis** [comment]
The OpenSUSE ..DEB and .RPM with the new version number are just building on https://build.opensuse.org/package/show/home:strik/cc65...

**Comment by oliverschmidt** [comment]
@spiro-trikaliotis: Thanks :-)

**Comment by polluks** [comment]
released http://aminet.net/package/dev/cross/cc65-morphos

**Comment by krischik** [comment]
@polluks @spiro-trikaliotis 

Did you build the optional documentation as well? Because I have problems with the documentation. I'm tempted to release the MacPorts version anyway but I like to hear your experiences first.

**Comment by spiro-trikaliotis** [comment]
@krischik , yes, the documentation is there, too, in the package cc65-doc.
You can see it in the build log at https://build.opensuse.org/package/live_build_log/home:strik/cc65/Debian_10/x86_64 (look out for the lines that contain "Processing file ../doc/".

But it is tricky to get it working.
What are the problems you are encountering?

**Comment by polluks** [comment]
I use a simple LinuxDoc viewer, no perfect solution.

**Comment by krischik** [comment]
@polluks @spiro-trikaliotis These kind of problems:

```log
:info:build fmt_info::postASP: Failed to run makeinfo. Aborting ...
:info:build make[1]: *** [../info/ca65.info] Error 25
:info:build make: *** [doc] Error 2
:info:build make: Leaving directory `/opt/local/var/macports/build/_Users_Shared_Work_MacPorts_dports_lang_cc65/cc65/work/cc65-2.19'
:info:build Command failed:  cd "/opt/local/var/macports/build/_Users_Shared_Work_MacPorts_dports_lang_cc65/cc65/work/cc65-2.19" && /usr/bin/make -w bin lib doc PREFIX=/opt/local CC="/usr/bin/clang" CXX="/usr/bin/clang++" OBJC="/usr/bin/clang" OBJCXX="/usr/bin/clang++" INSTALL="/usr/bin/install -c" 
:info:build Exit code: 2
:error:build Failed to build cc65: command execution failed
:debug:build Error code: CHILDSTATUS 29337 2
:debug:build Backtrace: command execution failed
:debug:build     while executing
:debug:build "system {*}$notty {*}$nice $fullcmdstring"
:debug:build     invoked from within
:debug:build "command_exec build"
:debug:build     (procedure "portbuild::build_main" line 8)
:debug:build     invoked from within
:debug:build "$procedure $targetname"
:error:build See /opt/local/var/macports/logs/_Users_Shared_Work_MacPorts_dports_lang_cc65/cc65/main.log for details.```

And here the complete log:

[main.log](https://github.com/cc65/cc65/files/5582286/main.log)

**Comment by spiro-trikaliotis** [comment]
As far as I see, you have the same, or at least similar warnings that I have, too, on ca65.sgml:
warning: @item should not appear in @item 
@item outside of table or list
(multiple times)

While I get
warning: @item missing argument

However, your build system seems to take these warnings as errors, stopping the build, while my just proceeds, ignoring them.

IIRC, the problem is in a table in ca65.sgml (after <sect1>Available operators) that does not conform to the LinuxDoc spec.
I have never found a solution for it.

You might get a workaround by adding a "-" to the lines cc65/doc/Makefile, lines 37:
        @-cd ../html && linuxdoc -B html -s 0 -T $(TOC_LEVEL) -H ../doc/header.html ../doc/$<
and 43:
        @-cd ../info && linuxdoc -B info ../doc/$<

(note the "-" between the "@" and the "cd")

That minus should ignore the error from the command, if there is any.

However, this is untested.

**Comment by oliverschmidt** [comment]
> IIRC, the problem is in a table in ca65.sgml (after Available operators) that does not conform to the LinuxDoc spec. I have never found a solution for it.

I seem to remember that we discussed that table already. I'm personally willing to accept workarounds to get rid of the issues. I don't know the actual problem but if it would be e.g. the empty rows separating the precedence classes one could have individual tables - one for each class...

**Comment by krischik** [comment]
MacPorts done as well: https://github.com/macports/macports-ports/pull/9281

**Comment by krischik** [comment]
In case someone here uses VIM I updated the syntax bundle.

https://github.com/krischik/vim-asm_ca65/network

**Comment by GorillaSapiens** [comment]
> Whats stopping you from using the new features now?

many downstream folks want the assurance that what they're getting is tested and stable.  they often have to support other less knowledgeable people further downstream.  they don't want to waste their time on buggy software causing support headaches.  for this reason, just grabbing the most recent whatever from git isn't good enough.  they want an "official release" that has had some level of testing.

official releases are also a sign of a healthy project.  if a project hasn't made a release in FIVE YEARS, there's good reason to suspect the project is either not active, not healthy, or both.

releases also help recruit interest and new blood to a project.  if someone sees "CC65 Compile Makes First Release In Five Years" on slashdot, they might come by to check it out.  they might even feel nostalgic and contribute...

**Comment by GorillaSapiens** [comment]
> Whats stopping you from using the new features now?

More reasons...

Official releases give users a stable point-in-time snapshot. It makes writing tutorials, bug reports, and documentation cleaner. everyone knows exactly what version is being discussed. Telling someone to "git clone main" is a moving target.

Linux distros, package managers and mirrors often won’t touch a project unless there’s a tagged release. If you want your software shipped and discoverable, you need to tag it.

Security-conscious orgs need to track known vulnerabilities by version. That’s impossible when there are no versions. No release == no CVE ID == no formal fix tracking. This raises red flags for enterprise use.

Even if a project is active, a lack of releases looks like abandonware to casual observers, managers, and non-dev stakeholders. A recent release can tip the perception from "dead project" to "sleeping giant waking up."

Making a release provides a sense of closure and accomplishment for contributors. It sets a natural cadence. Without it, the project can just feel like a never-ending grind of commits with no finish line.

**Comment by GorillaSapiens** [comment]
oops, i should have made these comments in #2281

**Comment by oliverschmidt** [comment]
@GorillaSapiens: Posting it here had me read it as I happen to be still subscribed to this issue. Nobody has asked me for my opinion, but here it is nevertheless:

* Yes, it is approriate to ask the maintainer to create release tags in a (sort of) regular fashion. That is necessary to trigger package build processes that happen elsewhere. At least during the time I maintained cc65, my policy was that this GitHub repo is "only" a raw upstream repo, but it doesn't contain anything related to package building.

* No, it is not appropriate to ask the maintainer to do any kind of additional quality insurrance whatsoever before creating a release tag. The job of maintaining cc65 isn't exactly popular. I've never whitnessed in all those years I'm part of the cc65 community that anybody came up and said that he can do better and that he should do it. Additionally there has afaik never been a fork of cc65 intended to become the new defacto upstream repo. Coming from there, everybody should be VERY prudent to explain to the maintainer what he needs to do how. If you overdo it, you may end up with an unmaintained project. Just saying.

* Totally independent from the facts layer, I personally believe that the communication style of especially _they don't want to waste their time on buggy software causing support headaches. for this reason, just grabbing the most recent whatever from git isn't good enough. they want an "official release" that has had some level of testing_ is more than questionable because it implies that "their" time is more valuable than the maintainers time. Given that we're talking about a free offering I don't see where this should come from. Yes, you can claim that if those additional qualities were present, then cc65 might become more popular. But I've never seen any statement here that the ultimate goal of this project would be to become as popular as possible.

**Comment by krischik** [comment]
Well, I manage to create releases for my projects just fine. Including the free one. Including those I expect no one will ever download. I have scripts prepared to do that and it usually takes me a few minutes. And with Github it's even easier. `git tag …` and then `git push --tags`. Done.

It's not like I'm asking for something i don't do myself on a regular basis.

**Comment by GorillaSapiens** [comment]
> * No, it is not appropriate to ask the maintainer to do any kind of additional quality insurrance whatsoever before creating a release tag. The job of maintaining cc65 isn't exactly popular. I've never whitnessed in all those years I'm part of the cc65 community that anybody came up and said that he can do better and that he should do it. Additionally there has afaik never been a fork of cc65 intended to become the new defacto upstream repo. Coming from there, everybody should be VERY prudent to explain to the maintainer what he needs to do how. If you overdo it, you may end up with an unmaintained project. Just saying.

the nature of release tagging naturally leads to a level of quality assurance above the noise floor, even if it is minimal.  i would not, for example, expect the maintainer to tag a release mere moments after merging a large invasive commit.  a rational maintainer would wait for some time to pass and bug reports to flow in before tagging a release or release candidate.

**Comment by colinleroy** [comment]
Hi,

> Well, I manage to create releases for my projects just fine. Including the free one. Including those I expect no one will ever download. I have scripts prepared to do that and it usually takes me a few minutes. And with Github it's even easier. `git tag …` and then `git push --tags`. Done.
> 
> It's not like I'm asking for something i don't do myself on a regular basis.

I suppose you could contribute a PR :-)

**Comment by krischik** [comment]
> I suppose you could contribute a PR :-)

Sure I can make you some ZShell-script to tag a version for you. I can even whip up a VIM-script to automatically set the version number inside version.c. Then it's just `Release_Version.zsh 4.0` and you are done.

Problem here is that you need to be a project admin to actually execute the script.

**Comment by mrdudz** [comment]
As said in the other ticket - a release means more than a tag - for example making a windows binary package available (and please lets have the discussion in that one ticket only)

**Comment by colinleroy** [comment]
> > I suppose you could contribute a PR :-)
> 
> Sure I can make you some ZShell-script to tag a version for you. I can even whip up a VIM-script to automatically set the version number inside version.c. Then it's just `Release_Version.zsh 4.0` and you are done.
> 
> Problem here is that you need to be a project admin to actually execute the script.

Oh, sorry, I thought you meant you were doing Github Actions to create your own project's releases.
