### ISSUE TITLE
wrongly optimized integer promotion in comparison

### ISSUE THREAD

**Issue by mrdudz** [cc65/cc65#1348]
I just noticed it by coincedence... both the "plasma" and the "fire" sample look broken with the current version of the compiler. trying to find out now what the problem is

**Comment by mrdudz** [comment]
```
; if ((rand() & 0xFF) > s) {
	jsr     _rand
	cmp     M0005
	bmi     L0016
	beq     L0016
```
this looks kinda wrong =P

**Comment by mrdudz** [comment]
another
```
if ((rand() & 0xFFU) > s) {
```
this also works as intended (like with the cast), while
```
if ((rand() & 255) > s) {
```
does not. i find this *very* irritating. something is screwed up there

**Comment by spiro-trikaliotis** [comment]
What about:
if ((rand() & 255u) > s) {

**Comment by mrdudz** [comment]
that works the same as 0xFFu. in (much) older cc65 (the one on godbolt) those both give the (working as expected) result, btw

**Comment by greg-king5** [comment]
It's not screwed up.  It's just that we, now, _always_ must write our programs with the C Standard's rotten "automatic int promotion" rule in mind.
```c
if ((rand() & 0xFF) > s) {
```
promotes to a `(signed int)` comparison.  While
```c
if ((rand() & 0xFFu) > s) {
```
promotes to an `(unsigned int)` comparison.
The optimizer doesn't know about the new rule.  Therefore, it still squeezes both comparisons down to `char`, but they retain their signedness!  Therefore, the first version compares two _signed_ chars -- not what you want!

**Comment by mrdudz** [comment]
> The optimizer doesn't know about the new rule. Therefore, it still squeezes both comparisons down to char, but they retain their signedness! Therefore, the first version compares two signed chars -- not what you want!

or in other words: screwed up (it indeed seems to work with all optimizations disabled)

will make a testcase

**Comment by jmr** [comment]
@acqn 

7553b60ef07a53c797974a73627cd6bebcc8e8fe is the first bad commit
```
commit 7553b60ef07a53c797974a73627cd6bebcc8e8fe
Author: acqn <acqn163@...>
Date:   Thu Jan 23 06:53:52 2020 +0800

    Improved OptStackOps for optimizating further when operands have equal hi-bytes.
```

**Comment by jmr** [comment]
Here's the diff in the output:

```
@@ -157,9 +157,7 @@
 ; if ((notrand() & 0xff) > s) {
 ;
        jsr     _notrand
-       jsr     pusha0
-       lda     _s
-       jsr     tosicmp0
+       cmp     _s
        bmi     L003E
        beq     L003E
 ;
```

**Comment by oliverschmidt** [comment]
@greg-king5: What's your perspective on this issue?

I seem to understand from your last comment that there's a inconsistency between the (changed) code generator and the (unchanged) optimizer. Do you agree that there's a regression in the overall user experience? Do you agree to consider this a bug?

Do you have ideas on how to fix this issue? Or do you think we need to consider to revert the code generator to the/some previous state?

**Comment by jmr** [comment]
> I seem to understand from your last comment that there's a inconsistency between the (changed) code generator and the (unchanged) optimizer. Do you agree that there's a regression in the overall user experience? Do you agree to consider this a bug?

That was a guess, but I think not the right one. It looks like it was an optimizer change that broke this: 7553b60. That's what I got from `git bisect`.

> Do you have ideas on how to fix this issue? Or do you think we need to consider to revert the code generator to the/some previous state?

Easiest would be to revert the optimizer change (7553b60) and re-merge when there's a fixed version.

**Comment by greg-king5** [comment]
> > I seem to understand from your last comment that there's a inconsistency between the (changed) code generator and the (unchanged) optimizer. Do you agree that there's a regression in the overall user experience? Do you agree to consider this a bug?
> 
> That was a guess, but I think not the right one. It looks like it was an optimizer change that broke this: 7553b60ef07a53c797974a73627cd6bebcc8e8fe. That's what I got from `git bisect`.

It's an _incomplete_ optimizer change.  Look at your example:
```asm
@@ -157,9 +157,7 @@
 ; if ((notrand() & 0xff) > s) {
 ;
        jsr     _notrand
-       jsr     pusha0
-       lda     _s
-       jsr     tosicmp0
+       cmp     _s
        bmi     L003E   ; <- this line, also, should be changed (to "bcc")
        beq     L003E
 ;
```
> 
> > Do you have ideas on how to fix this issue? Or, do you think we need to consider to revert the code generator to the/some previous state?
> 
> Easiest would be to revert the optimizer change , and re-merge when there's a fixed version.

I haven't looked at that optimizer code yet, but it should be easy enough to include that branch instruction in the optimization step.

**Comment by oliverschmidt** [comment]
@greg-king5: You wrote

> I haven't looked at that optimizer code yet, but it should be easy enough to include that branch instruction in the optimization step.

Did you have a chance to look at the code in the meantime? Do you see yourself capable/willing to make the necessary changes in the near future?

**Comment by greg-king5** [comment]
> > I haven't looked at that optimizer code yet, but it should be easy enough to include that branch instruction in the optimization step.
> 
> Did you have a chance to look at the code in the meantime? Do you see yourself capable/willing to make the necessary changes in the near future?

Yes, I have a plan for it.

**Comment by oliverschmidt** [comment]
Great - and thanks for the quick feedback :-)

**Comment by oliverschmidt** [comment]
Wow, that's what I call a Christmas present :-))
