### ISSUE TITLE
X Macros don't work with C preprocessor

### ISSUE THREAD

**Issue by sci4me** [cc65/cc65#1357]
I am trying to use the unspeakably-useful "X macro" idiom with cc65 but the preprocessor is producing completely incorrect output.

Here's an example; the following code:
```c
#define OPCODES(X) \
    X(PUSHNIL) \
    X(PUSHTRUE) \
    X(PUSHFALSE)

enum {
#define X(op) op,
OPCODES(X)
#undef X
    N_OPS
};
```
When preprocessed `cc65 -E test.c -o test.c.pre` produces:
```c
enum {
X #undef X };(PUSHNIL) };(PUSHTRUE) };(PUSHFALSE)
```
But it should produce something like this:
```c
enum {
PUSHNIL,
PUSHTRUE,
PUSHFALSE,
    N_OPS
};
```

**Comment by jmr** [comment]
I get
```
enum {
X #undef X N_OPS(PUSHNIL) N_OPS(PUSHTRUE) N_OPS(PUSHFALSE)
};
```
which is still wrong.

`cc65 V2.18 - Git 037a806`

**Comment by sci4me** [comment]
> I get
> 
> ```
> enum {
> X #undef X N_OPS(PUSHNIL) N_OPS(PUSHTRUE) N_OPS(PUSHFALSE)
> };
> ```
> 
> which is still wrong.
> 
> `cc65 V2.18 - Git 037a806`

I forgot to mention the commit I was using in the issue but I have since updated to the latest tag (2.19) and am getting this same result.

**Comment by acqn** [comment]
I can get this with my attempt to fix some other PP problems:
```c
enum {

PUSHNIL, PUSHTRUE, PUSHFALSE,

N_OPS
};
```

While simple cases like this can be fixed without a PP-tokenizer, a PP conforming to the standard would require that.
