### ISSUE TITLE
C128: OPEN

### ISSUE THREAD

**Issue by polluks** [cc65/cc65#1359]
On the C128, drive must be UNTALKed before OPEN to avoid
a bug that causes a byte to be lost from a channel that is currently open.
See https://github.com/jkotlinski/durexforth/issues/95#issuecomment-745013835

**Comment by greg-king5** [comment]
It's not a cc65 issue.  The bug was in DurexForth.

**Comment by polluks** [comment]
Are you sure it's not kernal related? Probably x128 will not reproduce it.
