### ISSUE TITLE
[info] Zero Page locations used by CC65

### ISSUE THREAD

**Issue by Fabrizio-Caruso** [cc65/cc65#1360]
I am not 100% sure I understand which specific ZP locations are used on each target by CC65 libraries, generated code and as "register" variables?

Does 
` ZP:       file = "", define = yes, start = $0002, size = $001A;`
 mean that on this target, $02, $03, .... $1B are reserved by CC65? 
 All the rest is available to the user (if not used by the O.S.)?

**Comment by oliverschmidt** [comment]
* Please use https://github.com/cc65/cc65/discussions for such topics in the future.

* You assumption is perfetly right.

**Comment by Fabrizio-Caruso** [comment]
@oliverschmidt  Thanks and sorry for this non-issue. I have started a discussion at #1361.
