### ISSUE TITLE
*minor* cc65 -W parameter not recognized

### ISSUE THREAD

**Issue by mzattera** [cc65/cc65#1367]
Parameter "-W Suppress warnings" is documented but seems not to be recognized.

**Comment by mzattera** [comment]
Ok, I see it is probably me not providing the right syntax as here https://www.cc65.org/doc/cc65-2.html it is documented without parameters while here https://cc65.github.io/doc/ca65.html#ss2.1 and here https://cc65.github.io/doc/ca65.html#ss2.1 it is using a level or a name respectively.

Doing some more tests.

**Comment by oliverschmidt** [comment]
https://www.cc65.org/ isn't relevant for anything regarding https://github.com/cc65/cc65 and https://cc65.github.io/.

**Comment by mzattera** [comment]
* -W option for cc65 is explained in detail in https://cc65.github.io/doc/cc65.html#ss2.2 and works as documented.
* It also work in the same way for cl65, as documented under https://cc65.github.io/doc/cl65.html

So, it was just my bad not reading the documentation through; I am closing this.

**Comment by oliverschmidt** [comment]
Thanks for the clarification.

**Comment by chironb** [comment]
Could someone please provide a literal concrete example? Thanks in advance!
