### ISSUE TITLE
ld65 claiming segment overflow but listing disagrees

### ISSUE THREAD

**Issue by jfoucher** [cc65/cc65#1369]
I have the following memory area defined : `ZP:         start = $0000, size = $00F2, type = rw;`
which corresponds to this segment : `ZEROPAGE:      load = ZP, type = zp;`
When linking ld65 claims that : `Segment 'ZEROPAGE' overflows memory area 'ZP' by 26 bytes`
But the listing file shows the following at the end of the `ZEROPAGE` segment:
```
...
0000E2r 2               
0000E2r 2  xx           Decss: .res 1;             = $EF       ; number to decimal string start
0000E3r 2  xx xx xx xx  Decssp1: .res 15;           = Decss+1   ; number to decimal string start
0000E7r 2  xx xx xx xx  
0000EBr 2  xx xx xx xx  
0000F2r 2               
0000F2r 2
0000F2r 2               
0000F2r 2               
0000F2r 1                   .segment "NEXT"
...
```

Why is there this disagreement? How can I solve it?
Thanks

**Comment by oliverschmidt** [comment]
If you create a map file you'll likely see that you link another module that puts things into the ZEROPAGE segment. Likely it's `zeropage.s`.

**Comment by jfoucher** [comment]
Thanks for the hint, it was actually `copydata.s` doing it.

Closing this now.
Cheers
