### ISSUE TITLE
CBM ASCII code $FF should map to screen code $5E (π), not $7F

### ISSUE THREAD

**Issue by ariand** [cc65/cc65#1372]
As the title says. Both `cbm_screen_charmap.h` and `cbm.mac` gets it wrong.

![](https://i.imgur.com/ghSGRRI.png)

**Comment by polluks** [comment]
Please see #988.

**Comment by mrdudz** [comment]
He is correct. Someone should come up with a variation of the test program from that ticket that uses the mentioned include files :)

**Comment by ariand** [comment]
(Sees #988, regrets it.)

**Comment by mrdudz** [comment]
cbm_screen_charmap.h btw is a slightly different issue... this one defines the mapping from actual ascii (not petscii) to screencodes

**Comment by mrdudz** [comment]
Ok so, after some playing around ... i have to correct myself - it's a totally different issue :) 

cbm_screen_charmap.h and cbm_petscii_charmap.h change the mapping from the *host* environment to the target memory. so its a ascii to screencode (or petscii respectively) conversion. and since no "pi" symbol exists in the ascii set, the mapping for it is pretty arbitrary (and not very useful, imho).

I'd still be interested in what your usecase looks like, how you expect it to work, and why - there might be a better way to do it.

**Comment by polluks** [comment]
@mrdudz Indeed, we don't need mapping of identical or undefined chars at all. Maybe Greg wanted a "copy and paste template".

**Comment by greg-king5** [comment]
> Maybe Greg wanted a "copy and paste template".

Ah ha, you're psychic!  That explains alot. :wink:

**Comment by ariand** [comment]
@mrdudz, no use-case here. I was just getting familiar with the assembler, and noticed that the mappings do not work the way CBM BASIC does, and the way the CBM manuals describe the mapping.

Hm, yeah, if you are mapping US ASCII to screen codes, then the upper 128 codes are…whatever you want them to be. I missed the part about ASCII, even though the header file mentions it.

`cbm.mac`, on the other hand, only states that it converts “characters to screen codes”. Then ca65.html says the `scrcode` macro “takes a string as argument and places this string into memory translated into screen codes”. I was under the impression that you can use it to convert PETSCII to screen codes— the documentation is not clear about this. *If it does* that conversion, then code 255 has to map to screen code 94.

In any case, it would help to avoid confusions like this if the documentation (and the include file, perhaps even the header file) was more explicit about what exactly gets mapped to what. Perhaps also adding a warning like *hey, this is not the conversion you might think it is*; again, to avoid confusions like this. ;-)

**Comment by mrdudz** [comment]
Those all take Ascii as input, indeed. And it is exactly what i'd expect too :) How would you produce petscii string literals in the first place? :=)

**Comment by polluks** [comment]
The header is talking about 8859-1, so it doesn't work with 8859-2?

**Comment by ariand** [comment]
@mrdudz, yeah, my bad. I was totally focused on the target machine, and forgot about the host. You go from host encoding(s?) to target string *or* screen encoding, and then perhaps even want to convert on the target itself between string and screen encodings. Life proves again that handling character encodings is a dirty business. Then again, it is easy for you to have certain assumptions, what with your insider knowledge and everything. :-P

I am closing this. Thanks four all your input, everybody.
