### ISSUE TITLE
#pragma charmap works in unexpected ways

### ISSUE THREAD

**Issue by mrdudz** [cc65/cc65#1373]
Issue #1372 made me extend targettest/cbm/petscii.c to also test cbm_screen_charmap.h and cbm_petscii_charmap.h ... and i stumbled over an unexpected issue. At least unexpected to me :)

```
#include <conio.h>
#include <stdio.h>

extern unsigned char mappedA[5];

/* abAB in ascii   -> $61,$62,$41,$42,$00 */
/* abAB in petscii -> $41,$42,$c1,$c2,$00 */

unsigned char notmappedA[5] = { "abAB" };

int main(void)
{
    clrscr();
    puts("abAB");       /* cbAB (NOT expected */
    puts(mappedA);      /* cbAB (expected */
    puts(notmappedA);   /* abAB (expected */
    return 0;
}

#pragma charmap (0x61, 0x43)

unsigned char mappedA[5] = { "abAB" };
```

I guess that the issue is that the Compiler emits string literals "later". Its really not what i expect to happen though, this way it is very hard to control what strings get the default mapping and which the custom one.

As i sidenote, i'd like to request a pragma that resets the charmap to the default - because putting that at the bottom of the code would be a convenient way to circumvent this problem.

**Comment by greg-king5** [comment]
That behavior is one of the reasons why Uz added the `--local-strings` command-line option and the `local-strings` pragma.

**Comment by mrdudz** [comment]
which is still a workaround, not a fix :) it should be well possible to attach an encoding flag to every string the moment it is parsed and make this work correctly.

**Comment by mrdudz** [comment]
could someone suggest a good place to put this testcase? right now its in targettest/cbm in my local copy - would that be ok? @oliverschmidt ?

**Comment by acqn** [comment]
Is `#pragma charmap` expected to affect the strings used in `asm` statements?

**Comment by mrdudz** [comment]
> Is `#pragma charmap` expected to affect the strings used in `asm` statements?
> 
> EDIT: Well. I think the most intituitive answer is that only the literals appeared in `asm` as arguments get charmapped.

Most "expected" to me would be that all strings/literals that appear in the source between #pragma charmap is then translated by that charmap. No more no less :)

**Comment by acqn** [comment]
You mean this?
```c
#pragma charmap (0x61, 0x41) /* 'a' -> 'A' */
asm("lda #%b", 'a');         /* to get "ldA #$41", seriously? */
```
I would expect only the optional arguments (to be formatted, in the case above, just `'a'`) to be charmapped.

**Comment by mrdudz** [comment]
> I would expect only the optional arguments (to be formatted, in the case above, just 'a') to be charmapped.

oh yes, sure. NOT the actual asm line of course, that would be super odd (but surely a fun source for mysterious bugs =P)
