### ISSUE TITLE
Bad code generated when optimization is enabled.

### ISSUE THREAD

**Issue by sidneycadot** [cc65/cc65#1374]
The following code correctly prints "89ab" when optimization is disabled, but "ab" when optimization is enabled with the -O flag.

Seems something goes wrong with the evaluation of the right-hand side of the assignment to z.
```c
#include <stdint.h>
#include <stdio.h>

void main(void)
{
    uint8_t x = 0x89;
    uint8_t y = 0xab;
    uint16_t z = (x << 8) | y;

    printf("%x\n", z);
}
````

**Comment by spiro-trikaliotis** [comment]
My psychic debugging powers tell me that this might be related to the latest changes which optimized away the int promotion in some cases. Thus, I assume that the (x << 8) is done with an unsigned char type (which makes this effectively a zero), and then the OR is executed.

**Comment by polluks** [comment]
At least cc65-2.19/bin/sim65 says `89ab`.

**Comment by sidneycadot** [comment]
@polluks : I'm using a recent daily build for Windows, V2.19 - Git d90cd11.

Are you sure you had optimization enabled? The -O flag needs to go before the C file.

**Comment by sidneycadot** [comment]
On my Debian V2.17 (standard stable package of cc65), the bug is not present. So it seems more or less recent.

**Comment by mrdudz** [comment]
reproduced it with git head... will come up with a test program

**Comment by sidneycadot** [comment]
> Thus, I assume that the (x << 8) is done with an unsigned char type (which makes this effectively a zero), and then the OR is executed.

@spiro-trikaliotis: that's plausible, but the strange thing is that if you remove the binary or, the problem disappears, and you get 0x8900 as expected.

**Comment by mrdudz** [comment]
Thats a good hint... so the OR is wrong

**Comment by sidneycadot** [comment]
> Thats a good hint... so the OR is wrong

You'd think so, but this works correctly:

```
#include <stdint.h>
#include <stdio.h>

int main(void)
{
    uint16_t x = 0x8900;
    uint8_t y = 0xab;
    uint16_t z = x | y;
    printf("%x\n", z);
    return 0;
}
```

So looks like some kind of interaction between the implicit type promotion and the or operator.

**Comment by mrdudz** [comment]
ah! sounds like simply some optimization step is wrong then

**Comment by oliverschmidt** [comment]
@mrdudz: You wrote '*[...] will come up with a test program*'. I hope this is still valid...

@all: It would be very nice of someone would "donnate" the information, which change is actually responsible for the regression (e.g. by bisecting).

@greg-king5: You thankfully fixed the recent regressions. You have an opinion on this one?

Note to myself: This regression shows once more how naive I'm still are regarding the coverage of our test suite :-(

**Comment by sidneycadot** [comment]
I could have a go at bisecting somewhere in the next few days.

**Comment by greg-king5** [comment]
> I'm writing (yet another) TCP stack; it will be useful to have this kind of thing working, so I can re-enable optimizations.

If you need a work-around, swapping the terms seems to avoid the bug:
```c
uint16_t z = y | (x << 8);
```

**Comment by oliverschmidt** [comment]
@mrdudz: Thanks for https://github.com/cc65/cc65/commit/084621967259fc7bb185913adbe48f8a456c262a.

**Comment by jmr** [comment]
@acqn 41cee0e

```
41cee0eb44de6f98910ca98255244f1d4731352d is the first bad commit
commit 41cee0eb44de6f98910ca98255244f1d4731352d
Author: acqn <acqn163@...>
Date:   Thu Jan 23 06:54:34 2020 +0800

    Extended support for more addressing modes in tos* optimizations.
```

**Comment by sidneycadot** [comment]
I did the bisect, as far as I can tell the commit shown by Jmr is the last one where the problem does not occur. The very next commit is where the compiler starts misbehaving if optimizations are enabled:

```
commit 4e4e4c2d2194c2c1f73d8c4503b4c6c56e1aa9a7
Author: Jesse Rosenstock <jmr@google.com>
Date:   Sun Aug 30 20:47:25 2020 +0200

    Allow char bit-fields
    
    These are not required to be supported (only int, signed int, and
    unsigned int are required), but most compilers support it.
    
    https://port70.net/~nsz/c/c89/c89-draft.html#3.5.2.1
    https://port70.net/~nsz/c/c89/c89-draft.html#A.6.5.8
    
    For consistency with other integral types, plain `char` bit-fields
    are unsigned, regardless of the `--signed-chars` option.
    
    Fixes #1047
```

**Comment by sidneycadot** [comment]
Quite remarkable, since the issue doesn't seem to be related to bitfields.

**Comment by jmr** [comment]
I think something is messed up with your bisect. When I ran bisect, 41cee0e was the culprit. 41cee0e~ == 1cde952 works.  4e4e4c2 is after both of those.

**Comment by sidneycadot** [comment]
I re-checked, seems you are right. 41cee0eb44de6f98910ca98255244f1d4731352d is the first bad one, 41cee0eb44de6f98910ca98255244f1d4731352d is still ok.
