### ISSUE TITLE
cbm_open on peripheral 2 (RS-232) on VIC-20

### ISSUE THREAD

**Issue by sblendorio** [cc65/cc65#1375]
Trying to render in CC65 this simple BASIC loop:

    10 open 5,2,3,chr$(6): rem chr$(6) = 300 baud
    20 get#1,a$ : print a$; : get a$ : print #1,a$;
    30 goto 20

But it happens that **cbm_open** fails. This code...

    int code;
    char *str = "x";
    str[0] = 6;
    code = cbm_open(5,2,3,str);

...returns an error (code != 0), so that next commands like **cbm_read** get stuck.

Here is a C program that tries (and fails) to implement that:
https://github.com/sblendorio/victerm300/blob/translate_c/victerm.c#L63

How can I open RS232 peripheral successfully?

Thanks in advance

**Comment by spiro-trikaliotis** [comment]
The RS232 implementation in the KERNAL is a little bit tricky. Look up OPEN ($FFC0) and the error code 240.
That's because RS232 needs additional buffers for the input and output buffer of length 256 byte each.

Thus, this error code is not a real error, but it tells you to make sure that you keep the buffer area ($9E00-$9FFF on the C64) as reserved space.

In the case of BASIC, it changes the END-OF-BASIC pointers and does a CLR afterwards (cf. BASIC OPEN at $E1BE and the error handling in case of RS232 at $E0F9).

If you keep that RAM area unused, you can ignore the error code 240.

**Comment by sblendorio** [comment]
I just ignore the error code, and it happens that the next **cbm_read** commands hangs up the program. It's stuck after executing **cbm_read**.

Note: I'm targeting VIC-20 UNEXPANDED using the command line:

    cl65 -t vic20 --config vic20-unexpanded.cfg -Cl -O -o victerm.prg victerm.c

File "vic20-unexpanded.cfg" is here: https://github.com/sblendorio/victerm300/blob/translate_c/vic20-unexpanded.cfg

**Comment by mrdudz** [comment]
Like spiro said, you have to setup the buffers first. By default it will use the last 512 bytes of basic memory - which also happens to be used by the software stack of cc65, so this will probably not work. (IF that cbm_open call will even result in the buffer pointers being initialized at all)

**Comment by sblendorio** [comment]
I updated the cfg file with this:

        MAIN:     file = %O, define = yes, start = $100D, size = $0BF3 - __STACKSIZE__;

(it was $0DF3)
The result is the same, the program hangs up after calling **cbm_read**.

**Comment by sblendorio** [comment]
Since it's not an issue, I'm closing it. I just opened discussion #1380

**Comment by sblendorio** [comment]
@spiro-trikaliotis @mrdudz Solved. I used a custom version of **cbm_read(),** using **cbm_k_getin()** instead of **cbm_k_basin()**, checking accumulator **__A__** instead of checking **cbm_k_readst()**:

    int __fastcall__ cbmread (unsigned char lfn, void* buffer, unsigned int size)
    {
        static unsigned int bytesread;
        static unsigned char tmp;
        unsigned char oserror;
        if (oserror = cbm_k_chkin(lfn)) return -1;
        bytesread = 0;
        while (bytesread<size && !cbm_k_readst()) {
            tmp = cbm_k_getin();
            if (__A__ == 0) break;
            ((unsigned char*)buffer)[bytesread++] = tmp;
        }
        cbm_k_clrch();
        return bytesread;
    }

**Comment by oliverschmidt** [comment]
The return value of `cbm_k_getin()`__*IS*__ the accumulator (https://github.com/cc65/cc65/blob/master/libsrc/cbm/c_getin.s). There's just no point in accessing the accumulator via `__A__` right after returning from `cbm_k_getin()`.

**Comment by sblendorio** [comment]
@oliverschmidt  So it's not the solution... how can I detect the lack of receive after calling **cbm_k_getin()** ?

**Comment by sblendorio** [comment]
I  need to distinguish "received a byte, with value zero" from "not received anything"

**Comment by oliverschmidt** [comment]
I can't tell you anything regarding how the cbm_... functions work as I have about no knowledge about CBM machines - if I could I would have commented before. However, I know very well how 6502 asm code and C code interact in cc65 - and from that I could tell you what I wrote above.

**Comment by greg-king5** [comment]
The RS-232 device makes a status byte that's different from the status created by other devices.  And, `READST` from that device is broken on the VIC-20.  They are why `cbm_read()` doesn't work with that device.

See https://www.pagetable.com/c64ref/kernal/#READST.

**Comment by polluks** [comment]
I see. How about patching _cbm_k_readst?

**Comment by spiro-trikaliotis** [comment]
@greg-king5, good catch. I even documented it myself at http://cbmrom.trikaliotis.net/full/vic20.a65.full.html#ABZJ, but I forgot about it.
@polluks, you mean an own implementation of cbm_k_readst? I don't think it is a good idea to add overhead for a case that next to no one uses. Did you ever see someone doing RS232 on the VIC20?

**Comment by groessler** [comment]
I'm with @polluks. If it's possible in cbm_k_readst to know that device 2 (serial) is the one, do the workaround and read from the other status byte. Just in the vic20 version of course.
A few cycles spent in a "read status" routine shouldn't be that harmful.

**Comment by Fabrizio-Caruso** [comment]
Just a little off-topic, but are you guys aware of what all of this is for? 
Thanks to @sblendorio we now have a cool 8-bit BBS:
http://www.sblendorio.eu/Commodore/Web
which is accessed by 8-computers.
The BBS started as an Italian BBS but it is now targeting world-wide retro-enthusiasts.

I think it deserves some support in CC65 because it could encourage other people start similar projects.

**Comment by spiro-trikaliotis** [comment]
The code is simple:

```
15266:  iREADST:
15267:          lda     zFA                     ; get device address
15268:          cmp     #FILE_RS232             ; is it a RS232 device?
15269:          bne     iREADST_Normal          ; no, return regular status
15270:  
15271:          ; here, we have a RS232 device.
15272:          ; return the special status of the RS232 device
15273:          ; (not documented in the KERNAL description above!)
15274:  
15275:          lda     lRSSTAT                 ; get RS232 status
15277:          pha                             ; make sure to remember RS232 status; this is missing on the VIC-20
15278:  
15279:          ; Leaving this out for the VIC 20 is obviously a severe bug, which
15280:          ; makes iREADST for RS232 completely useless on it
15281:  
15283:          lda     #$00                    ; clear RS232 status
15284:          sta     lRSSTAT
15286:          pla                             ; get the RS232 status back; this is also missing on the VIC-20
15287:  
15288:          ; Leaving this out for the VIC 20 is obviously a severe bug, which
15289:          ; makes iREADST for RS232 completely useless on it
15290:  
15292:          rts

15332:  iREADST_Normal:
15333:          lda     zSTATUS
15334:  SetStatus:
15335:          ora     zSTATUS
15336:          sta     zSTATUS
15337:          rts
```

with zFA := $BA, FILE_RS232 := 2, lRSSTAT := $0297 and zSTATUS := $90. Of course, iREADST_Normal can be replaced by a JMP to READST ($FFB7) in the Kernal.

Another solution might be a special function which just returns the value of lRSSTAT. I would believe that most people who use RS232 might know when they are reading from that one, and use that function instead. Or, this could be done even without a function.

I am not against a solution, but for me, patching for function wastes too many bytes for a case that is not used very often (as I strongly believe).

**Comment by sblendorio** [comment]
I solved this way:

    int __fastcall__ cbmread(unsigned char lfn, unsigned char* buffer, unsigned int size)
    {
        static unsigned int bytesread;
        if (cbm_k_chkin(lfn)) return -1;
        bytesread = 0;
    
        while (PEEK(667)!=PEEK(668) && bytesread<size)
            buffer[bytesread++] = cbm_k_getin();
    
        cbm_k_clrch();
        return bytesread;
    }

(I called the function **cbmread** without underscore, it should be better use a different name like **cbm_get** maybe).

Here is the code: https://github.com/sblendorio/victerm300/blob/translate_c/victerm.c

This is an example of the application (CNN news feed):

[![Vic20 BBS](https://img.youtube.com/vi/FUiph56sWFo/0.jpg)](https://www.youtube.com/watch?v=FUiph56sWFo)

**Comment by groessler** [comment]
@spiro-trikaliotis, the code is really simple. One apparently has to clear the status byte afterwards. But this can be implemented in a better way. And the code after "SetStatus" seems to be irrelevant.

**Comment by spiro-trikaliotis** [comment]
@groessler, I copied the original code. SetStatus is not needed, as this is the entry for another kernal function. I did not think about it correctly.

The status is cleared when reading the RS232 status, but it is not cleared when reading a "normal" status. The PHA/PLA are there in the original code because the function guarantees to leave the X and Y registers. This might not be needed, as IIRC, the cc65 ABI does not have this requirement, right?

@sblendorio, you are not interested in the reason why the read failed?

**Comment by sblendorio** [comment]
Yes, I'm interested. I was used to read ST ($90) value while reading (i.e.) from disk.

In the original cbm_write function it's read after calling **cbm_k_basin**, but it's blocking so I replaced it with **cbm_k_getin**, and it does not change $90 (ST) value.
