### ISSUE TITLE
Detect cbm_k_readst() change after calling cbm_k_getin()

### ISSUE THREAD

**Issue by sblendorio** [cc65/cc65#1383]
Hi, I need to call **cbm_k_getin()** function and detect if the "stream" is finished. Using **cbm_k_basin()** the status **cbm_k_readst()** can be checked like this:

    if (cbm_k_readst() & 0xBF) break; // "stream" is finished

Using **cbm_k_getin()** this condition doesn't work. What is the right check to do?

Thanks in advance.

**Comment by sblendorio** [comment]
Solved: **cbm_k_getin()** sets the accumulator to zero if there is no communication, so the correct check is:

    if (__A__ == 0) break; // "stream" is finished

**Comment by oliverschmidt** [comment]
The return value of `cbm_k_getin()`__*IS*__ the accumulator (https://github.com/cc65/cc65/blob/master/libsrc/cbm/c_getin.s). There's just no point in accessing the accumulator via `__A__` right after returning from `cbm_k_getin()`.
