### ISSUE TITLE
cc65/shiftexpr.h:36:9: error: 'SHIFTEXPR_H'

### ISSUE THREAD

**Issue by rchennau** [cc65/cc65#1387]
In file included from cc65/expr.c:32:
cc65/shiftexpr.h:36:9: error: 'SHIFTEXPR_H' is used as a header guard here, followed by #define of a different macro [-Werror,-Wheader-guard]
#ifndef SHIFTEXPR_H
        ^~~~~~~~~~~
cc65/shiftexpr.h:37:9: note: 'SHIFTEXPT_H' is defined here; did you mean 'SHIFTEXPR_H'?
#define SHIFTEXPT_H
        ^~~~~~~~~~~
        SHIFTEXPR_H
1 error generated.
make[1]: *** [../wrk/cc65/expr.o] Error 1
make: *** [all] Error 2

**Comment by oliverschmidt** [comment]
This issue was solved 7 years ago with https://github.com/cc65/cc65/commit/db42af3f20b49e5c63d66a6c8630e5bcc1f0b094
