### ISSUE TITLE
[question/bug?/ca65] Branch opcode doesn't assemble with absolute address

### ISSUE THREAD

**Issue by shazz** [cc65/cc65#1389]
Hi,

Forgive me if my understanding of 6502 is limited :)
On the other cross-assembler I'm using I can do:
````asm
lda #0
bcc ok                                      
lda #1
ok:    nop
````

or
````asm
lda #0
bcc $0807                                     
lda #1
ok:    nop
````

which assembles to:
````
0801: A9 00                       LDA #$00
0803: 90 02                       BCC $0807
0805: A9 01                       LDA #$01
0807: EA                          NOP
````

but with ca65, `bcc $0807` raises the error: `Error: Range error`

why ?

Thanks !

**Comment by mrdudz** [comment]
Most other 6502 assemblers always work in "absolute" mode, ie you set the program counter manually, and the assembler will output code to absolute addresses. In that case the above can work.

However, ca65 is different, it only over outputs object files, and the default is to output object code with relocation info - in that case the assembler does not know where the resulting code goes to, and it cant produce the code for the above.

what you CAN do is use the .org directive and make it assemble code in absolute mode. however, i do NOT recommend doing this, as it is most likely not behaving like you expect.

Just use symbolic labels - it wont make your code worse :=)

**Comment by shazz** [comment]
Ok, that makes sense. I have the issue because my assembly code is generated not human typed :)

In the case the targeted label is in another file/segment, the label won't be resolved (and same question for not relative addresses). What is the best way to help cl65 to resolve the labels ? Having an include which define global (means across segments) labels ?
