### ISSUE TITLE
wrong MEMORY block definition caused 26GB file to be created on disk

### ISSUE THREAD

**Issue by shazz** [cc65/cc65#1390]
Hi,

As I'm generating the memory configuration file by code, I made a mistake which created a funny behavior with cl65.
If the MAIN memory section was declared like this:

`MAIN:     file = %O, start = %S,     size =  - %S,   fill = yes;`

it creates a file of at least 26GB on disk :)

**Comment by groessler** [comment]
The bug is in your cfg file.

**Comment by mrdudz** [comment]
Should probably still error out after a reasonable maximum size :)

**Comment by shazz** [comment]
I agree the configuration is faulty but that's not a good reason to fill my disk :)

**Comment by greg-king5** [comment]
ld65 saw that attribute as
```c
size = (unsigned long)(0L - (long)S)
```
I agree with @mrdudz.  ld65 should reject negative sizes before it casts them to `unsigned`.

**Comment by mrdudz** [comment]
closed via #1996
