### ISSUE TITLE
serial drivers not working

### ISSUE THREAD

**Issue by sblendorio** [cc65/cc65#1398]
I compiled for C64:

    $ cl65 -t c64 targettest/ser-test.c -o ser-test.prg

this file, present in the repo (`./targettest/ser-test.c`):

    #include <stdio.h>
    #include <stdlib.h>
    #include <serial.h>
    #include <conio.h>
    #include <dbg.h>
    
    #if defined(__C64__)
    #define DRIVERNAME      "c64-swlink.ser"
    #elif defined(__C128__)
    #define DRIVERNAME      "c128-swlink.ser"
    #elif defined(__PLUS4__)
    #define DRIVERNAME      "plus4-stdser.ser"
    #elif defined(__CBM610__)
    #define DRIVERNAME      "cbm610-std.ser"
    #elif defined(__APPLE2ENH__)
    #define DRIVERNAME      "a2e.ssc.ser"
    #elif defined(__APPLE2__)
    #define DRIVERNAME      "a2.ssc.ser"
    #elif defined(__ATARIXL__)
    #define DRIVERNAME      "atrxrdev.ser"
    #elif defined(__ATARI__)
    #define DRIVERNAME      "atrrdev.ser"
    #else
    #define DRIVERNAME      "unknown"
    #error "Unknown target system"
    #endif

    static const struct ser_params Params = {
        SER_BAUD_1200,      /* Baudrate */
        SER_BITS_8,         /* Number of data bits */
        SER_STOP_1,         /* Number of stop bits */
        SER_PAR_NONE,       /* Parity setting */
        SER_HS_NONE         /* Type of handshake to use */
    };
    
    static void CheckError (const char* Name, unsigned char Error)
    {
        if (Error != SER_ERR_OK) {
            fprintf (stderr, "%s: %d\n", Name, Error);
            exit (EXIT_FAILURE);
        }
    }
    
    int main (void)
    {
        char Res;
        char C;
        CheckError ("ser_load_driver", ser_load_driver (DRIVERNAME));
        CheckError ("ser_open", ser_open (&Params));
        while (1) {
            if (kbhit ()) {
                C = cgetc ();
                if (C == '1') {
                    break;
                } else {
                    CheckError ("ser_put", ser_put (C));
                    printf ("%c", C);
                }
            }
            Res = ser_get (&C);
            if (Res != SER_ERR_NO_DATA) {
                CheckError ("ser_get", Res);
                printf ("%c", C);
            }
        }
        CheckError ("ser_unload", ser_unload ());
    
        return EXIT_SUCCESS;
    }

I just put "SER_BAUD_1200" and "SER_HS_NONE" to match my WiFi modem's parameters.

What happens is alwas this error:

    ser_load_driver: 2

How could I make it work?

Thanks in advance

**Comment by mrdudz** [comment]
you'll have to put the driver on the disk so it can actually be loaded (or link it statically - see the documentation)

also, the driver for c64 requires swithlink - a userport driver does not exist iirc

**Comment by polluks** [comment]
We should include up2400.ser in the future...
https://github.com/nanoflite/c64-up2400-cc65
https://github.com/tschak909/platoterm64/blob/master/dist.c64/c64-up2400.ser

**Comment by sblendorio** [comment]
Thank you. How do I compile including it?

**Comment by mrdudz** [comment]
> We should include up2400.ser in the future...

definately ... we just need someone to clean it up and test it :)

**Comment by oliverschmidt** [comment]
https://github.com/cc65/wiki/wiki/Reminders#CBM_library - present since 8 years.

**Comment by polluks** [comment]
> Thank you. How do I compile including it?
See https://www.cbmstuff.com/forum/printthread.php?tid=353

**Comment by sblendorio** [comment]
I put this after includes

    #define DRIVERNAME "c64-up2400.ser"

I removed other #defines from the source

I put c64-up2400.ser in the same directory of the source

I compiled with

    $ cl65 -t c64 ser-test.c -o ser-test.prg

but the result is the same: "error 2". What do I do wrong?

**Comment by sblendorio** [comment]
right. I should put it ON the D64 image. Now it starts!

Is there a way to make it work also with Plus/4 ?

**Comment by sblendorio** [comment]
Yes. There is the proper driver in the repo :)

**Comment by sblendorio** [comment]
Is there a way to compile **statically** the driver within the PRG executable?
