### ISSUE TITLE
adding numeric value to address is multiplied by 2

### ISSUE THREAD

**Issue by peteym5** [cc65/cc65#1421]
When I create a memory pointer that is imported from an ASM file, and try offsetting by numeric value to it, the address of the offset is multiplied by 2. This is very weird. Any suggestions of what may be causing this to happen? 

(PMMEMORY = $9000)  <- External declared in Assembly file. Unsigned Integer.
```c
memset(&PMMEMORY + 90 , 63 , 20); 
```
Should find 63 written to $905A, but finding it at $90B4. I tried to change the values to hex, same result.

**Comment by greg-king5** [comment]
What's the exact `extern` declaration that you use to import that name into your C program?

**Comment by oliverschmidt** [comment]
Let me guess: An int pointer...

**Comment by peteym5** [comment]
extern unsigned int PMMEMORY

I changed it to and it corrected the problem. Some of the CC65 documentation is a little misleading. I am very accustomed to assembly and Basic and adding a number to a memory address usually has the amount exact. 
extern unsigned char PMMEMORY

**Comment by oliverschmidt** [comment]
Sorry, but this has nothing, really NOTHING to do with cc65 nor its documentation. It has only to do with your (lack of) knowledge of the C programming language. The cc65 documentation has no ambition whatsoever to teach the C programming language!
