### ISSUE TITLE
enum declaration in struct does not compile

### ISSUE THREAD

**Issue by mrdudz** [cc65/cc65#1437]
Playing around with FUZIX... stumbled about this one:

```
struct nodelist {
	struct nodelist *nextnode;
	struct predlist *inedges;
	char *name;
	enum { DEAD, LIVE, ONCE, TWICE } live;
} firstnode = {
NULL, NULL, NULL, DEAD};
```
does not compile:
```
tsort.c(24): Error: Undefined symbol: 'DEAD'
tsort.c(24): Error: Constant expression expected
```
rewriting it like this makes it work:
```
enum nodestate { DEAD, LIVE, ONCE, TWICE };

struct nodelist {
	struct nodelist *nextnode;
	struct predlist *inedges;
	char *name;
	enum nodestate live;
} firstnode = {
NULL, NULL, NULL, DEAD};
```

this is with pr #1435 merged locally, did not check yet if it is related

**Comment by acqn** [comment]
It wasn't clear to me whether the enumerators of `enum`s inside a `struct`/`union` are visible outside or not and I assumed the same behavior as in C++... But now I see from the C11 standard that it's clearly required to be true.
