### ISSUE TITLE
String Array Help

### ISSUE THREAD

**Issue by peteym5** [cc65/cc65#1443]
I am writing up a Black Jack for the Atari 8-bit computer. I am trying to create a string array to store the hand result for each player with something that looks like this.

char *PLAYERNMESSAGE[5] = {};

I initially set the string with 
char *PLAYERNMESSAGE[Player_Number] = strcat("T:",utoa(PLAYERNTOTAL[Player_Number],BUFFER,10));

When I go and display more than one player, I get accumulated numerals for each player. Player 1 will have 12, 2 will have 14. But for player 2, we see "T:1214" as if player 1 information was kept inside that buffer. Is there a function that clears and resets the buffer?

**Comment by oliverschmidt** [comment]
A cc65 issue isn't the right format and location for this type of question. This is a general C programming question not specific to cc65. I suggest that you find a forum regarding C programming like e.g. https://cboard.cprogramming.com/c-programming/?s=caa0055458d672cf44c7751c2969b647 or https://stackoverflow.com/questions/tagged/c and place the question there.
