### ISSUE TITLE
Cannot Clear String

### ISSUE THREAD

**Issue by peteym5** [cc65/cc65#1445]
I am trying to create a string with several possible options. I start the string with 
`mystr = ("");`
Then depending on some logic I add various options with STRCAT
`strcat(mystr, " Option1");`
`strcat(mystr, " Option2");`
`strcat(mystr, " Option3");`
but when I call the routine again, the text for some of the options are still present, even after I cleared them with mystr = ("");
I tried writing 0s to the memory location, and did not fix the issue.  I need a way to clear the string and reset the length back to 0. But seems to be acting goofy at times.

**Comment by mrdudz** [comment]
As someone said before in another issue, this isnt a problem with cc65 - its a problem with your understanding of the C language in general. The cc65 issues are the wrong place for this - use a generic c-programming forum.
