### ISSUE TITLE
Apple II: How to get a program working with driver?

### ISSUE THREAD

**Issue by griffin9k** [cc65/cc65#1450]
In fact, I'm working on compiling the samples\tgidemo.c on Windows.
I changed the startaddress to $4000 in apple2.cfg and cl65 tgidemo.c to tgidemo, then use AppleCommander -as to add it to a .DSK image, but when I BRUN TGIDEMO on AppleWin, the program says: this program needs tgi driver on disk, so I use ciderpress to add \target\apple2\drv\a2.hi.tgi to the DSK image, but when I BRUN TGIDEMO again, it said: cannot load driver.
There must be somthing wrong, how can I add the driver to a DSK image that will be recognized by the main program?

**Comment by oliverschmidt** [comment]
1. There's no need to load the driver as file. Almost all of the time you don't want to do that. Check out https://github.com/cc65/cc65/blob/master/samples/tgidemo.c#L11-L13. Simply define DYN_DRV as 0 e.g. from the cmd line and you're good to go.
2. If you want to load the driver as file, use AppleCommander's option -p to add it to the .DSK image. See e.g. https://github.com/cc65/cc65/blob/master/samples/Makefile#L297

**Comment by griffin9k** [comment]
Thanks for your comment, I've tried solution-1, it's simple and works great, but 2. is still the same result, here is the command line I use to add tgi driver: ac -p hello.dsk a2.hi.tgi rel 0 < a2.hi.tgi, is that correct? by the way, the DSK image is DOS 3.3 format.

**Comment by oliverschmidt** [comment]
> by the way, the DSK image is DOS 3.3 format.

Adding that piece of information means that you were already thinking in the right direction. Just add a bit of documentation reading and ... ;-)

https://cc65.github.io/doc/apple2.html#ss8.1

**Comment by griffin9k** [comment]
Wow, it works on ProDOS finally, thanks a lot my friend :+1:
