### ISSUE TITLE
align not working correctly.

### ISSUE THREAD

**Issue by BJury** [cc65/cc65#1456]
It looks like, when using `align` in the .cfg file, the data is aligned correctly; but, the references in code are not adjusted.

eg:
```ini
SEGMENTS {
    ZEROPAGE: load = ZP,       type = zp;
    EXTZP:    load = ZP2,      type = zp, optional = yes; # OK if BASIC functions not used
    LOADADDR: load = LOADADDR, type = ro;
    EXEHDR:   load = MAIN,     type = ro, optional = yes;
    CODE:     load = MAIN,     type = ro;
    LOWCODE:  load = MAIN,     type = ro, optional = yes;
    RODATA:   load = MAIN,     type = ro;
    DATA:     load = MAIN,     type = rw;
    DATA256:  load = MAIN,     type = rw, align = $100; # NOTE ALIGN
    BSS:      load = MAIN,     type = bss,                define = yes;
}
```
and the following code

```asm
  .org $0801                  ; Assembled code should start at $0801
                                ; (where BASIC programs start)
                                ; The real program starts at $0810 = 2064

; 10 SYS 2064
    .byte $0C, $08              ; $080C - pointer to next line of BASIC code
    .byte $0A, $00              ; 2-byte line number ($000A = 10)
    .byte $9E                   ; SYS BASIC token
    .byte $20                   ; [space]
    .byte $32, $30, $36, $34    ; $32="2",$30="0",$36="6",$34="4"
    .byte $00                   ; End of Line
    .byte $00, $00              ; This is address $080C containing
                                ; 2-byte pointer to next line of BASIC code
                                ; ($0000 = end of program)
    .byte $00, $00              ; Padding so code starts at $0810
    cld

    stp
    lda testdata
    rts

.segment "DATA256"
testdata:
    .byte $01, $02, $03, $04
```
produces:
![image](https://user-images.githubusercontent.com/1936876/114208628-98d07400-9955-11eb-9863-2218add65a12.png)

You can see $0816 is used, which is incorrect. (Or I'm doing something wrong!)

Maybe better images here:
https://stackoverflow.com/questions/66950892/cl65-doesnt-adjust-addresses-when-using-align

**Comment by greg-king5** [comment]
Don't use the `.org` directive.  (The configure file sets that address: `STARTADDRESS: default = $0801`.)

Also, it tells the assembler to tell the linker, "don't relocate the following code".  That prevents the `.segment` directive from doing what we expect it to do.

**Comment by BJury** [comment]
Makes sense. Well kinda, as what it produces isn't right as the code doesn't point to the data regardless of the config being bad. Feels like an error state, so should at least produce a warning?

**Comment by oliverschmidt** [comment]
Hm, we could remove the `.org` control command. Would you consider this an improvement?

**Comment by mrdudz** [comment]
> Hm, we could remove the .org control command.

wat. are you suggesting to use a linker config for every little thing?

**Comment by oliverschmidt** [comment]
If it causes severe issues...

**Comment by groessler** [comment]
I think there are uses of .org.

I don't see a problem in the OP's post. Isn't 01 02 03 04 at the correct place?

**Comment by mrdudz** [comment]
the problem is that the address of the LDA testdata is wrong - it should be $0100, not $0816.

to achive what was intended either the .org must be removed and the linker config adjusted as needed, or there must be a .reloc after the code (before the .segment)

that said, i'd suggest to make .reloc implicit for .segment - i cant imagine a usecase where you wouldnt want this and would like this slightly surprising result instead.

**Comment by oliverschmidt** [comment]
Maybe `.feature org_per_seg` is what you're looking for...
