### ISSUE TITLE
[cc65] Bit-fields are still broken

### ISSUE THREAD

**Issue by acqn** [cc65/cc65#1462]
It seems to me that bit-field is still broken with '++/--' and '@='...

Demo:
```c
#include <stdio.h>

typedef struct {
    signed int a : 3;
    signed int b : 3;
    signed int c : 3;
} T;

int failures = 0;

void test()
{
    T a = {2, 5, -1};
    T b = {1, 4, -1};
    T m[1] = {{6, 3, -1}};
    T *p = &a;

    a.c += b.a;
    p->c += b.b;
    m->c += b.c;

    if (a.c != -4) {
        ++failures;
    }
    printf("%d\n", a.c);

    if (p->c != -4) {
        ++failures;
    }
    printf("%d\n", p->c);

    if (m->c != -2) {
        ++failures;
    }
    printf("%d\n", m->c);

    ++a.a;
    p->b++;
    m->c--;

    if (a.a != 3) {
        ++failures;
    }
    printf("%d\n", a.a);

    if (p->b != -2) {
        ++failures;
    }
    printf("%d\n", p->b);

    if (m->c != -3) {
        ++failures;
    }
    printf("%d\n", m->c);

    printf("Failures: %d\n", failures);
}

int main(void)
{
    test();
    return failures;
}
```

**Comment by polluks2** [comment]
Do you have some test cases? I'm pretty sure mrdudz will include them.

**Comment by oliverschmidt** [comment]
I imagine that @jmr might be pretty interested in some test cases too. So providing some here would kill two birds with one stone.

**Comment by acqn** [comment]
Added.

**Comment by oliverschmidt** [comment]
Thanks :-)

@jmr: Do you think you will be able to take care of theese issues?

**Comment by jmr** [comment]
Using that test case and running `git bisect` on `cl65 -t sim6502 bug1462.c` gives:

```
5b11eb4bb95a9982f33f2c580318202afc0b0882 is the first bad commit
commit 5b11eb4bb95a9982f33f2c580318202afc0b0882
Author: acqn <...>
Date:   Tue Dec 31 15:55:51 2019 +0800

    Corrected check in OptTransfers2 for register usage. Fixed Issue 992.
```

5b11eb4

It appears to never have worked with `-O`, or at least I couldn't find a revision. I only tried back to Jan 2020.

**Comment by jmr** [comment]
@acqn Can you make these into separate test cases, so if one fails, it doesn't cause the ones after it to fail?

**Comment by jmr** [comment]
From my own test case:

```
;
; a.c += 3;
;
        ldy     #$00
        ldx     #$00
        lda     #$03
        jsr     addeqysp
```

So it looks like += doesn't treat this as a bit-field. Will need to look more into if bit-fieldness is being checked / where it's being dropped later.

**Comment by acqn** [comment]
The `=` assignment take special care to handle writes to bit-fields correctly, but the other modifying operators don't.
For '@=' it's `addsubeq()` and `opeq()`.
For inc/dec it's `PreInc`, `PreDec`, `PostInc`, `PostDec`, DeferredInc` and `DeferredDec` .

**Comment by oliverschmidt** [comment]
@jmr: Just to avoid misunderstandings - is it reasonable to assume that you'll provide a fix for this issue in the foreseeable future?

**Comment by acqn** [comment]
I made a working experimental fix on my "separate parser/codegen WIP" branch. It could be back-imported to the trunk but would require quite some effort due to the complexity introduced along with the current status of the parser/codegen mixture.

**Comment by acqn** [comment]
BTW, even the `=` operation is buggy in certain ways:

```c
#include <stdio.h>

typedef struct {
    signed int a : 3;
    signed int b : 3;
    signed int c : 3;
} T;

int failures = 0;

T *f(T *t)
{
    t->a = 0;
    t->c = 0;
	return t;
}

void test(void)
{
    T a = { 7, 0, 7 };
    T *p = &a;

    a.b = f(p)->a;

    if (a.a != 0) {
        ++failures;
    }
    printf("%d\n", a.a);

    if (p->b != 0) {
        ++failures;
    }
    printf("%d\n", p->b);

    if ((&a)->c != 0) {
        ++failures;
    }
    printf("%d\n", (&a)->c);

    printf("Failures: %d\n", failures);
}

int main(void)
{
    test();
    return failures;
}
```

**Comment by oliverschmidt** [comment]
Sorry, for the naive question: What do you think is the best way forward (under the presumption that @jmr doesn't contribute anymore) ?

**Comment by acqn** [comment]
I could give this a shot.

**Comment by oliverschmidt** [comment]
I appreciate your effort !!

**Comment by acqn** [comment]
More test on "op= expression result value" that a naive fix might fail with:
```c
#include <stdio.h>

typedef struct {
    signed   int a : 3;
    unsigned int b : 3;
    signed   int c : 3;
    unsigned int d : 3;
} T;

int failures = 0;

void test(void)
{
    T a = { 3, 3, 3, 3 };
    int i;

    i = a.a += a.b + a.c;
    if (i != 1) {
        ++failures;
    }
    printf("i = %d, a.a = %d\n", i, a.a);

    i = a.b *= -1;
    if (i != 5 || a.b != 5) {
        ++failures;
    }
    printf("i = %d, a.b = %d\n", i, a.b);

    i = a.c * -1;
    if (i != -3) {
        ++failures;
    }
    printf("i = %d, a.c = %d\n", i, a.c);

    i = a.d ^= -1;
    if (i != 4 || a.d != 4) {
        ++failures;
    }
    printf("i = %d, a.d = %d\n", i, a.d);

    printf("Failures: %d\n", failures);
}

int main(void)
{
    test();
    return failures;
}

```

**Comment by acqn** [comment]
Well, the fix (will be a PR) is done for the upstream, but it is taking me more time already attempting to rebase the previous fix on my branch onto this pending fix...

**Comment by oliverschmidt** [comment]
Thanks for the intermediate feedback.

As far as I see there's currently no open upstream PR from you - so there's nothing I can do to simplify things for you, right?

**Comment by acqn** [comment]
The fix revealed a hidden bug in `OptStackOps` (yeah, for the xxxth time). Maybe that should be fixed prior to this.

**Comment by oliverschmidt** [comment]
There's no reason to hurry in closing this issue. It's for sure best to do things in the order that minimizes the effort and/or maximizes the quality.
