### ISSUE TITLE
Update Visual Studio projects to use shared settings from a props file

### ISSUE THREAD

**Issue by vrubleg** [cc65/cc65#1466]
I propose to make a few updates to the vcxproj files.

First of all, I propose to move all the shared project settings to the [Directory.Build.props](https://docs.microsoft.com/en-us/visualstudio/msbuild/customize-your-build?view=vs-2019) or a custom props file. So, you change a setting in the props file, and it is used in all projects automatically. It is much better than when all the settings are duplicated for every project and project configurations.

According to project defaults, I propose three variants of better defaults.

Variant A (if we want to make it buildable on default VS2019):
1. Switch toolkit to v142 (VS2019).
2. Switch SDK version to 10.0. So, it will automatically choose the latest available SDK, no need to install specific version:
```
<WindowsTargetPlatformVersion>10.0</WindowsTargetPlatformVersion>
```
_(This method of selection of the latest SDK version is not supported by older VS2017, so it is VS2019 only.)_

Variant B (if we want to support XP):
1. Switch toolkit to v141_xp.
2. Use dynamic linking with `msvcrt.dll` to make files much smaller without requirement to install VS runtime libraries (but it will require to push a lib file from the Microsoft WDK7 to this repo).

Variant C (if we want to make it buildable on both VS2017 and VS2019):
1. Leave toolkit at v141 (VS2017).
2. Use this trick to select latest available Windows 10 SDK (so, at least you won't be enforced to install an older SDK version):
```
<WindowsTargetPlatformVersion>$([Microsoft.Build.Utilities.ToolLocationHelper]::GetLatestSDKTargetPlatformVersion('Windows', '10.0'))</WindowsTargetPlatformVersion>
```
_(It should be compatible with both VS2017 and VS2019.)_

What do you think about it?

**Comment by oliverschmidt** [comment]
Hi,

Please note that there's no intention to ever deliver cc65 built with VS. The VS project files are a convenience for VS users - like e.g. me.

So far my experience was/is that "upgrading" the project files from older VS versions to newer ones is a matter of a few clicks - while the opposite isn't possible. From that perspective I like to keep the project files at older versions - if that approach doesn't introduce issues!

Apart from that: Are you aware that we have a Travis-CI build based on the project files? Currently Travis-CI has VS2017 installed. See: https://github.com/cc65/cc65/blob/master/src/msbuild.cmd and https://github.com/cc65/cc65/blob/master/.travis.yml#L26

Therefore from what you write above, variant C appeals most to me. The "trick" is what is described at https://developercommunity.visualstudio.com/t/WindowsTargetPlatformVersion-makes-it-im/140294#T-ND190992 - correct?

Is what you describe above with property files also possible with VS2017? Does such a property file allow the update-with-a-few-clicks to VS2019? Does it work with msbuild?

If the answers to the three questions above are 'yes' then I'd consider a centralized build setting management a welcome improvement.

**Comment by vrubleg** [comment]
Props files are supported from at least VS2010, it is a part of MSBuild. Automatic inclusion of the Directory.Build.props is supported since VS2017. So, if we want to use a different file name of the props file, or we want to support even older VS versions like VS2010, we'll need to include our custom props file explicitly from the project file.

Actually, this mechanism is flexible enough to have different default settings for all versions of Visual Studio, so it is possible make it buildable in the VS2010-VS2019 by default without changing any settings at all. There is basically a simple XML-based scripting language which allows to implement any logic of choosing default settings.

> The "trick" is what is described at https://developercommunity.visualstudio.com/t/WindowsTargetPlatformVersion-makes-it-im/140294#T-ND190992 - correct?

Yeah, but it is not required to make it that complicated as in that example.

**Comment by oliverschmidt** [comment]
Thanks for the explanation :-)

So it seems to me we want:
* a Directory.Build.props (VS2017 + VS2019)
* that SDK version workaround

Are you willing/able to create a PR providing those?

**Comment by vrubleg** [comment]
Yeah, will do, but a bit later =)

**Comment by oliverschmidt** [comment]
Great :-)

**Comment by vrubleg** [comment]
Making the file. Noticed that the project has an issue with charsets. It is not UTF-8. As the result, it looks like this:
```
/* (C) 2001-2005  Ullrich von Bassewitz                                      */
/*                RцmerstraЯe 52                                             */
```
Definitely it wasn't intended to be like this. Visual Studio 2017+ supports UTF-8 perfectly fine. It is possible to configure it to always save source code as UTF-8, it is also possible to configure it to treat narrow string literals as UTF-8 strings. I can add these settings also. What do you think?

**Comment by vrubleg** [comment]
`Directory.Build.props` looks not so consistent with other filenames in the directory. I can import the props file explicitly, in this case I can name it `cc65.props`. If a new project will be added, it will require to add just one line of code into the project file manually. What do you think?

**Comment by oliverschmidt** [comment]
> Directory.Build.props looks not so consistent with other filenames in the directory. I can import the props file explicitly, in this case I can name it cc65.props. If a new project will be added, it will require to add just one line of code into the project file manually. What do you think?

You are right, that's the preferable approach. Thanks.

**Comment by oliverschmidt** [comment]
> [...] UTF-8 [...]

I must admit that you lost me here.

Maybe it helps when I state that opening any exsisting cc65 source file, changing let's say a single char and saving it, definitively mustn't change anything in the source file beside that single char.

Beyond that I don't understand the differences between the different proposals.

**Comment by vrubleg** [comment]
Currently, source code is in an ANSI charset, the narrow strings during execution of programs are also ANSI.

There is an option to convert all source code into UTF-8, so all the comments with non-ASCII characters will be displayed fine for all people. It is also possible to switch execution encoding for narrow strings from ANSI to UTF-8, but in case if all the strings in the project are ASCII, it won't make any difference, and I guess it is the case. So, I propose to use UTF-8 for source code only (without changing execution encoding, so all the strings will remain ANSI as they are now), just to make sure that all the comments and the code is displayed properly for everybody.

Since it implies conversion of all source files into UTF-8, it can be done in a separate commit and a separate PR. Only those lines which have non-ASCII characters will be updated by such conversion, so it won't break history of every line.

**Comment by mrdudz** [comment]
I'd rather propose to configure the editor so it doesnt screw up the encoding of the files :)

**Comment by vrubleg** [comment]
You can't configure Visual Studio to use non-system charset for ANSI files, and won't ever be, because it is a legacy thing which is already resolved by support of UTF-8.

There are just two options:
1. ANSI encoding, which depends on system charset used by the OS of a developer. So, people from any country with non-Latin system charset will see not what was intended.
2. UTF-8, which is displayed properly everywhere, regardless of a country of a developer.

**Comment by Marrin** [comment]
That sounds like a severe limitation of Visual Studio and I have a hard time believing this.

**Comment by vrubleg** [comment]
@Marrin what are you talking about?

**Comment by vrubleg** [comment]
@oliverschmidt so, can you build the solution on the VS2017 with these changes?

**Comment by oliverschmidt** [comment]
As I wrote in https://github.com/cc65/cc65/pull/1469#issuecomment-822044723 that was already proved by Travis-CI.

**Comment by Marrin** [comment]
@vrubleg I can't believe that it's not possible to tell Visual Studio the source code is encoded as Windows-1252/CP1252 or ISO-8859-1 but just UTF-8 or the one byte encoding code page used by the system, whatever that may be.  Almost any simple text editor can do that.  I'm a bit surprised. :open_mouth:

**Comment by spiro-trikaliotis** [comment]
@Marrin, Windows editors usually rely on the BOM to recognise UTF-8 (cf. https://en.wikipedia.org/wiki/Byte_order_mark#UTF-8). I expect VS to do the same.
