### ISSUE TITLE
misleading operator

### ISSUE THREAD

**Issue by polluks** [cc65/cc65#1478]
https://github.com/cc65/cc65/blob/4acdc9ced9ded4c37e46d2bc531bea31894c1ccc/libsrc/pce/joy/pce-stdjoy.s#L74
If the function returns char, you don't need ">JOY_COUNT" for any driver.

**Comment by mrdudz** [comment]
It still must return 0 in X

**Comment by polluks** [comment]
Indeed, I said "misleading", I would like to replace all ">JOY_COUNT" with "0".

**Comment by oliverschmidt** [comment]
My opinion is the very opposite. There's nothing saying that X has to be zero. Writing that in code is 100% misleading. However, there's something saying that every function has to at least return an `int`. So the ONLY thin that makes sense is to see JOY_COUNT as 16 bit value.

**Comment by groessler** [comment]
I agree with @oliverschmidt

**Comment by oliverschmidt** [comment]
See https://github.com/cc65/cc65/discussions/1480.
