### ISSUE TITLE
[bug?][conio][pce] Graphics glitches with -Or option

### ISSUE THREAD

**Issue by Fabrizio-Caruso** [cc65/cc65#1483]
The root cause of this bug is the -Or option.
This bug report is about graphics glitches (usually at the right of the character/tile I am supposed to display).

The first picture below shows some "holes" on the right walls. It looks like the CONIO code is writing something and sometimes an empty space slips into the next character or a space character is displaced instead of the correct character (see second picture).

I will try to reproduce this with a smaller example.

![image](https://user-images.githubusercontent.com/29057615/116759131-ec445800-aa11-11eb-9e62-70869e116d3a.png)

![image](https://user-images.githubusercontent.com/29057615/116759347-6a086380-aa12-11eb-9602-923da571bef5.png)

**Comment by Fabrizio-Caruso** [comment]
@greg-king5 @oliverschmidt feel free to close this issue if it is not a real issue for you. I am not sure what to do.

**Comment by greg-king5** [comment]
I want it to stay open until I find out why register pointers don't work.
