### ISSUE TITLE
Macro using __AX__ gets wrong data from pointer in cc65 2.19; works in cc65 2.18

### ISSUE THREAD

**Issue by demesos** [cc65/cc65#1489]
I experienced an issue with cc65 V2.19 where a macro using the `__AX__=` syntax got the wrong data when fed a `char *`.
This example program works when compiled cc65 V2.18  - Git 1074d35 by outputting "hello world" to the screen on the C64 target:
```C
#include <stdint.h>

// convert the printable characters from ASCII to screen code (simplified, incomplete version)
#define toscreencode(C) (__AX__ = (C),   \
                         asm("and #$3f"),\
                         __AX__)   

void main (void)
{
  char *p = "hello world";
  uint16_t scaddr=1024+11*40;	//output to line 11 on the screen

  while (*p != 0) {
    (*(unsigned char *)(scaddr++)=(toscreencode(*p)));
    p++;
  }    
}
```
But when compiled with  cc65 V2.19  - Git 216bb22, the macro receives the values `B9 BA BB BC` and so on, which looks like index values instead of the actual data.

**Comment by greg-king5** [comment]
In order to allow better optimization, post-increment and post-decrement operations are delayed until cc65 reaches a C "sequence point".  Normally, that's at a semicolon.  But, the comma operator also is a sequence point.  Therefore, the increment of `scaddr` is done _after_ `(C)` is loaded, and _before_ the Assembly instruction -- the value in `__AX__` becomes invalid.

You can avoid that problem by making an extra sequence point before loading into `__AX__`:
```c
#define toscreencode(C) (__AX__, __AX__ = (C),   \
                         asm("and #$3f"),\
                         __AX__)

    (*(unsigned char *)(scaddr++)=(toscreencode(*p)));
```
(cc65 2.18 didn't delay post-counts.)

**Comment by oliverschmidt** [comment]
Thanks for the analysis and explanation :-)

**Comment by demesos** [comment]
Thanks for the explanation, but why is *p considered a post-decrement/post-increment operation? The post-decrement operation on scaddr++ is not the part that fails.

**Comment by demesos** [comment]
Thanks for digging into it and for the explanation. The code fix works, but it would require the coder to know about this issue any time a macro is written that potentially can be used with a post-x operation before. Would it make sense and be possible to have the compiler introducing an automatic sequence point before every __A__= and __AX__=? Not sure if this can cause other issues though.

**Comment by oliverschmidt** [comment]
At least to me personally the use of `__A__` or `__AX__` is a major hack in the firstr place that makes all kinds of assumptions. The only improvement I personally see is to remove them altogether ;-)

**Comment by polluks** [comment]
A warning would have been enough.

**Comment by mrdudz** [comment]
The general Idea is: if you use inline assembler, you better know exactly what you are doing - all bets are off. You shouldnt be doing it in the first place.

**Comment by oliverschmidt** [comment]
As discussed (too) many times: Inline asm doesn't result in anything predictable when combined with the C optimizer. However, the very use case of inline asm (small portions of asm within large portions of C) requires the C optimizer. As a result inline asm is pretty much useless.

**Comment by mrdudz** [comment]
> As a result inline asm is pretty much useless.
I wouldnt go that far, i still use it in some rare cases. I wouldnt use it in a case like the one above in the original post though :)

**Comment by demesos** [comment]
Guys, please note that I constructed the presented example in order to show that there is a discrepancy. It was not meant as an example of when to use inline assembler. My aim was to inform that the  `__AX__=(c)` syntax does not work anymore in the presented case. Since this syntax is part of the cc65 documentation, I thought I let the developers know. I didn't post here because I needed the program fixed, I already had a solution where the post increment is in a different line. And, no, I didn't mean to ask for people's opinions on using inline assembler. Probably I should have made the latter more clear, I'm sorry that the comments on this issue got diverted in that way.
