### ISSUE TITLE
Output errors so emacs can parse the line number

### ISSUE THREAD

**Issue by audetto** [cc65/cc65#1494]
Currently errors are written to console like this
```
hello.c(5): Error: Unexpected newline
hello.c(6): Error: ')' expected
```
which emacs does not parse.

Most compilers output it as 

```hello.c:5: Error: Unexpected newline
hello.c:6: Error: ')' expected
hello.c:6: Error: ';' expected
```

which can be clicked on emacs easily.
Change is trivial and I am happy to propose a PR, but I wonder if this has already been discussed in the past.

**Comment by oliverschmidt** [comment]
Apart from the line number notation... Are you specifically talking about `Unexpected newline` or is this an example for a certain class of error messages?

**Comment by audetto** [comment]
yes, just the `file:line` notation that emacs accepts by default.
I am sure one can configure emacs to parse `file(line)` but patching `error.c` seems much simpler and portable solution.

https://github.com/cc65/cc65/blob/5d84a4ba137e32163390ccd058c32ad169b4ca94/src/cc65/error.c#L130

I see other tools with the same syntax (`ca65`), but I have only used `cc65` so far.

**Comment by oliverschmidt** [comment]
As far as I understand you'd like to see cc65 conforum (more) to https://www.gnu.org/prep/standards/html_node/Errors.html

I'm personally open for a change - but it needs to include all parts of the cc65 tool chain.

**Comment by audetto** [comment]
yes, I agree on both points.

**Comment by oliverschmidt** [comment]
I suggest that we wait a bit if there are strong opposite opinions. If there aren't, I'm willing to merge a PR consistently changing the syntax.

**Comment by mrdudz** [comment]
This has been bothering me recently as well, my editor of choice also likes file:line better - so +1 for changing it :)

**Comment by spiro-trikaliotis** [comment]
vim recognizes both formats (just tested), so I have no objections. :)

**Comment by audetto** [comment]
Thank you guys.
This is done now,
