### ISSUE TITLE
Darwin has some trouble to compile cc65

### ISSUE THREAD

**Issue by polluks2** [cc65/cc65#1496]
````
BUILD_ID: Git ab9db5b
cc65/asmcode.c
In file included from cc65/codeseg.h:51,
                 from cc65/asmcode.c:41:
cc65/symentry.h:126: error: redefinition of typedef 'SymEntry'
cc65/datatype.h:57: error: previous declaration of 'SymEntry' was here
make[1]: *** [../wrk/cc65/asmcode.o] Error 1
make: *** [all] Error 2
````

**Comment by oliverschmidt** [comment]
https://github.com/cc65/cc65/blob/master/src/cc65/symentry.h#L126 says `typedef struct SymEntry SymEntry;`.
https://github.com/cc65/cc65/blob/master/src/cc65/datatype.h#L57 says `typedef struct SymEntry SymEntry;` too.

**Comment by polluks2** [comment]
Indeed, ask cc65
````
int main()
{
typedef int foo;
typedef int foo;
return 0;
}
````
````
> cl65 a.c
a.c(4): Error: Multiple definition for 'foo'
````

**Comment by mrdudz** [comment]
That's a different thing. This works fine in cc65 (and gcc):
```
typedef struct foo1 foo1;
typedef struct foo1 foo1;
struct foo1 {
    int bar;
};


typedef struct foo2 foo2;
struct foo2 {
    int bar;
};
typedef struct foo2 foo2;

int main(void)
{
    return 0;
}
```

**Comment by polluks2** [comment]
Easy: It was part of Xcode. Homebrew should be no requirement.

**Comment by mrdudz** [comment]
You should probably update the title to say what flavour of macOS (which is not Darwin) you are using. 

Chances are the answer is still "update the toolchain" because gcc 4.4.5 is super outdated (it was released over 10 years ago).

**Comment by polluks2** [comment]
Well, `uname` say Darwin, cc65 does not require any part of macOS.
Apple does not support any update because of their marketing department ;-)
BTW in January I was able to compile `cc65 V2.19 - Git 5fa7b90`.

**Comment by groessler** [comment]
And, are you related to @polluks ? :-)

**Comment by dmsc** [comment]
This is a patch that allows compilations with very old gcc versions (tested with gcc-3.3)

```patch
diff --git a/src/cc65/funcdesc.h b/src/cc65/funcdesc.h
index e065c7602..2d5710f83 100644
--- a/src/cc65/funcdesc.h
+++ b/src/cc65/funcdesc.h
@@ -37,6 +37,8 @@
 #define FUNCDESC_H
 
 
+/* cc65 */
+#include "datatype.h"
 
 /*****************************************************************************/
 /*                              struct FuncDesc                              */
@@ -61,7 +63,6 @@
 #define WRAPPED_CALL_USE_BANK   0x0100U /* WrappedCall uses .bank() */
 
 /* Function descriptor */
-typedef struct FuncDesc FuncDesc;
 struct FuncDesc {
     unsigned            Flags;           /* Bitmapped flags FD_...            */
     struct SymTable*    SymTab;          /* Symbol table                      */
diff --git a/src/cc65/symentry.h b/src/cc65/symentry.h
index 56d884bb6..aee867c9f 100644
--- a/src/cc65/symentry.h
+++ b/src/cc65/symentry.h
@@ -123,7 +123,6 @@ struct DefOrRef {
 };
 
 /* Symbol table entry */
-typedef struct SymEntry SymEntry;
 struct SymEntry {
     SymEntry*                   NextHash; /* Next entry in hash list */
     SymEntry*                   PrevSym;  /* Previous symbol in dl list */
```

**Comment by greg-king5** [comment]
That's the right idea, but the wrong direction.  It's "datatype.h" that must be changed.  "funcdesc.h" and "symentry.h" provide the base declarations.  _They_ should be #included where those declarations are needed.

**Comment by dmsc** [comment]
Hi!

> That's the right idea, but the wrong direction. It's "datatype.h" that must be changed. "funcdesc.h" and "symentry.h" provide the base declarations. _They_ should be #included where those declarations are needed.

Tried that, did not work. The problem is that `symentry.h` already includes `datatype.h`, so if we are going to change `datatype.h`, the changes are fairly large.

Another possible solution is to move *all* typedefs to a "types.h" (or "basetypes.h")  file, and include it from funcdesc, symentry and datartpe. This would be cleaner, as all users could drop the "struct" word from the declarations.

**Comment by polluks** [comment]
Some background information https://stackoverflow.com/q/6526322

**Comment by groessler** [comment]
Understand I this correctly, that a "typedef" for a "struct <something>" before the definition of "struct <something>" was an error in older versions?

If yes, this seems intuitive to me.

And, again that's probably just me, I don't like typedefs for structs (or typedefs in general). One has to type a little bit less, but with typedefs you never know what you have unless you look up the type.

`struct blah my_blah`
vs.
`blah my_blah'

In the latter case you don't know what `blah` could ever be unless you search the code. In the former case you already know that it's a struct. And hiding pointer variables inside a typedef makes everything more opaque.

Ok. Enough ranting... :-)

**Comment by dmsc** [comment]
Hi!

> Understand I this correctly, that a "typedef" for a "struct " before the definition of "struct " was an error in older versions?
> 

No. Prior versions (before C11) did not allow redefining a typedef.

But C11 added (from http://www.open-std.org/jtc1/sc22/wg14/www/docs/n1548.pdf , 6.7, paragraph 3):

  If an identifier has no linkage, there shall be no more than one declaration of the identifier
  (in a declarator or type specifier) with the same scope and in the same name space, **except
  that a typedef name can be redefined to denote the same type as it currently does**

This was changed in GCC 4.6.

**Comment by polluks** [comment]
Indeed, it makes no sense to avoid C99 but use C11 features.

**Comment by greg-king5** [comment]
I see that problem when I use `-ansi -pedantic` with gcc 10.

Commit e5813cfb1ab7069c063d0a1a8a9fd14e58a3a1a9 should fix it.

**Comment by oliverschmidt** [comment]
Thanks :-)
