### ISSUE TITLE
cprintf does no format conversion when -t is missing in compile...

### ISSUE THREAD

**Issue by fachat** [cc65/cc65#1502]
I have a small program that includes
`cprintf("Hello %s (%d)!\n\r", s->name, strlen(s->name));`
The compile is running with out "-t pet", so as to use ASCII strings etc (this is for a TCP/IP stack).
The linker stage is using "-t pet" to get the right memory configuration.
However, then the output has the problem that NO format conversion is done, the output is simply
`hELLO ()!`
(with caps change due to PETSCII/ASCII, which is ok in this case, but not ok is that the string and also the integer are not substituted in the output.

I am running cc65 V2.17 (which I have obviously installed myself under /usr/local as I note only now, so pls forgive me if this is way too old...)

**Comment by mrdudz** [comment]
you can try using -t none and -C pet.cfg. -t does not only select the linker config, but also the target library, the character encoding, and perhaps other things i forgot. those things should match in all stages involved. to use only a certain linker config, use -C

**Comment by mrdudz** [comment]
Oh i forgot, in that case you might need to link the startup code (crt0) for pet manually

**Comment by mrdudz** [comment]
Oh wait, you'll also loose a lot of library functions, such as screen i/o and kernal stuff - so thats probably not what you want.

The cleanest solution would certainly be to use -t pet for compiling, assembling and linking, If you mix targets in any of those steps, unexpected side effects will happen. So the question is, why arent you doing this in the first place?

If you are fine with dealing with those side effects, you could also try using %S and %D in the format string, that may work

**Comment by fachat** [comment]
I am build basically a telnet server based on the uIP stack. So all strings should be ASCII. Except when printing output to the console - but that I can convert manually if need be.
What do %S and %D do?

**Comment by oliverschmidt** [comment]
I imagine that (building with -t pet combined with)`#include <ascii_charmap.h> does what you want.

**Comment by fachat** [comment]
Hm, using %S and %D seem to do the trick, together with "-C pet.cfg" in the linker stage instead of "-t pet". 
These format codes are cc65-specific, right?

**Comment by mrdudz** [comment]
> So all strings should be ASCII. Except when printing output to the console - but that I can convert manually if need be.

You can change the character encoding with #pragma CHARMAP at compile time, or to change the complete mapping include one of the provided header files or this (you'll probably have to update the toolchain for this).

> What do %S and %D do?

it's simply %s and %d in uppercase :) since you are mixing files with ascii and petscii encoding, you may be able to trick it into recognizing those that way.

**Comment by mrdudz** [comment]
Oh btw, not using -t pet for compiling, assembling and linking is a bad idea, i am certainly not recommending this :)

**Comment by fachat** [comment]
This is how it is working currently: 
```
cc65 -g -I../uip -I.  -I../apps/hello-world ../apps/hello-world/hello-world.c -o obj/hello-world.s
ca65   -o obj/hello-world.o obj/hello-world.s
ar65 a apps.a obj/hello-world.o
ld65  -C pet.cfg obj/main.o obj/clock-arch.o obj/enceth.o apps.a uip.a /usr/share/cc65/lib/pet.lib -o uip
rm obj/hello-world.s
```

**Comment by fachat** [comment]
btw, I'm now on cc65 V2.18  - Ubuntu 2.18-1, and same faulty behaviour.

**Comment by mrdudz** [comment]
> edit: but only using %S and %D. And that I would consider a bug anyway. Completely ignoring %d and %s should not happen.

It's not a bug. It happens because you are mixing files with different character encodings.

**Comment by fachat** [comment]
So what is the difference between %S and %d regarding character encoding, so that one works and the other doesn't? Why does %d not work even though it's all just about digits that are the same in both char encodings?

**Comment by oliverschmidt** [comment]
> ld65  -C pet.cfg [...] /usr/share/cc65/lib/pet.lib

That's exactly what ld65 -t pet is for.

**Comment by fachat** [comment]
> > ld65  -C pet.cfg [...] /usr/share/cc65/lib/pet.lib
> 
> That's exactly what ld65 -t pet is for.

Not sure about that. If I just use "ld65 -t pet" and leave out the pet.lib, it does not link due to missing symbols.
Otherwise the behaviour is exactly the same either with "-t pet" or "-C pet.cfg".

Indeed, it looks like the only difference to fix the problem at the start is to use %S and %D instead of %s and %d. (why?)

**Comment by mrdudz** [comment]
> So what is the difference between %S and %s regarding character encoding, so that one works and the other doesn't? 

The library is compiled for pet, and thus uses petscii encoding. So printf functions expect the format string being in petscii encoding. You are compiling the code that contains the format string without -t pet, so the string is in ascii. And uppercase vs lowercase uses different encoding in ascii and petscii.

**Comment by fachat** [comment]
> > So what is the difference between %S and %s regarding character encoding, so that one works and the other doesn't?
> 
> The library is compiled for pet, and thus uses petscii encoding. So printf functions expect the format string being in petscii encoding. You are compiling the code that contains the format string without -t pet, so the string is in ascii. And uppercase vs lowercase uses different encoding in ascii and petscii.

Yes, thanks, that makes indeed sense! Now I got it.

**Comment by fachat** [comment]
#include <ascii_charmap.h> does not find the file.

For #pragma charmap, do I really have to map each and every character?

**Comment by mrdudz** [comment]
> For #pragma charmap, do I really have to map each and every character?

yes. I recommend updating to the git head revision at this point, its really worth it :)

**Comment by fachat** [comment]
I have been looking around, there is no current release download? And I did not find build instructions (except for the obvious "make", "make install" - is it that simple? where does it install?

**Comment by mrdudz** [comment]
just check out the git head, and yes

**Comment by greg-king5** [comment]
Modularity is the solution!

Put your console and file I/O code in a different source file.  Compile it with `-t pet`.  Compile your telnet code with `-t none`.  Link them with `-t pet`.

**Comment by mrdudz** [comment]
yes, that could work - of course that still means the code compiled with -t none can not use printf (or other functions that rely on petscii encoding)

**Comment by fachat** [comment]
As pet.lib is pre-compiled, my assumption is that it is using PETSCII anyway, no matter if I use ascii_chartable or not, right? So all the *printf are using PETSCII anyway when interpreting the format string, right?

So then indeed modularity seems to be the solution. Use "-t none" or ascii_chartable for ASCII-code (i.e. e.g. telnet, internet stuff), and call a separate function in another file that is using "-t pet", and has the format string compiled in, or something similar). 

I'll check it out, and close this issue for now.

Many thanks!

**Comment by spiro-trikaliotis** [comment]
> I have been looking around, there is no current release download? And I did not find build instructions (except for the obvious "make", "make install" - is it that simple? where does it install?

If you are on a Debian style or OpenSUSE style Linux, you could also try https://build.opensuse.org/package/show/home:strik/cc65 and especially the download link https://software.opensuse.org//download.html?project=home%3Astrik&package=cc65
These should be daily builds from the git head (if I do not mess it, like I did for some months now).
