### ISSUE TITLE
[cc65] Some compilation failures

### ISSUE THREAD

**Issue by acqn** [cc65/cc65#1504]
```c
#include <stdio.h>

int main(void)
{
    int i = 0, *p = &i;
    switch (i) case 0: case 1: i = 21;  /* Should be OK but fails */
    p++[0] += 21;                       /* Should be OK but fails */
    printf("%d\n", i);
    return i != 42;
}
```
Expected output:
```
42
```

This currently fails to be compiled with cc65.

**Comment by oliverschmidt** [comment]
@mrdudz: It would be great if you could (yet again) create a regression test from the code above. Please let me know if you want me to delay merging https://github.com/cc65/cc65/pull/1505 until you have done so - or if you prefer the opposite sequence.

**Comment by mrdudz** [comment]
please merge, then i can add the test locally, confirm it fails, pull and confirm it works :)

**Comment by oliverschmidt** [comment]
Will do - thanks for the feedback :-)

**Comment by mrdudz** [comment]
@acqn BTW - how are you finding such obscure cases? Are you using some testcase generator tool or sth like that?

**Comment by oliverschmidt** [comment]
I presume that working with the cc65 source code makes him sometimes notice code smell - and that by the time he writes the test source code, he already knows which type of source code will fail...

**Comment by acqn** [comment]
Yeah.
