### ISSUE TITLE
supervision sample does not compile

### ISSUE THREAD

**Issue by mrdudz** [cc65/cc65#1506]
samples/supervisionhello.c fails to compile (link) with:
```
../bin/ld65   -o supervisionhello -t supervision -m supervisionhello.map supervisionhello.o supervision.lib
ld65: Warning: /home/groepaz/Desktop/cc65/github-current/cc65/cfg/supervision.cfg:41: Segment 'VECTORS' does not exist
ld65: Error: Missing memory area assignment for segment 'VECTOR'
```

**Comment by Fabrizio-Caruso** [comment]
It definitely compiled when I wrote it. :-(

**Comment by greg-king5** [comment]
The Supervision configure files were redesigned.  The `VECTOR` segment was renamed to `VECTORS`.  But, "crt0.s" wasn't adjusted for that change.

**Comment by mrdudz** [comment]
This is the problem when the samples are not part of the CI - they *will* break over time.

In any case, please fix - wouldnt know how to confirm it still works

**Comment by oliverschmidt** [comment]
> This is the problem when the samples are not part of the CI - they will break over time.

Yep. https://github.com/cc65/cc65/issues/1495 is just 9 days back and fell into the same category. It's out of question that it is desirable to build at least some "Hello, World" on all/most targets as part of the CI !

**Comment by mrdudz** [comment]
<corporate voice> we are working on it

:)

**Comment by Fabrizio-Caruso** [comment]
In case you are testing under Windows, the simplest emulator to use is the Wataroo.
