### ISSUE TITLE
pointer mismatch in tgi header

### ISSUE THREAD

**Issue by mrdudz** [cc65/cc65#1507]
While going through (and trying to fix) warnings produced by the samples i stumbled about this:

in tgi.h there is
```
/* The address of the static standard tgi driver for a platform */
extern const void tgi_static_stddrv[];
```
and then
```
void __fastcall__ tgi_install (void* driver);
/* Install an already loaded driver. */
```
and as a consequence, this produces a warning when doing
```
    /* Install the graphics driver */
    tgi_install (tgi_static_stddrv);
```
so... as i see it, the tgi_install function should take ```const void*``` instead of ```void*```, correct? or am i missing something?

**Comment by mrdudz** [comment]
same problem seems to exist with joy_install

**Comment by oliverschmidt** [comment]
I follow your perspective that changing the ..._install function prototype(s) (incl. all others beside tgi and joy) is the correct fix.

**Comment by mrdudz** [comment]
ok, will do

**Comment by mrdudz** [comment]
..and done :)

**Comment by mrdudz** [comment]
oops, forgot to close :)
