### ISSUE TITLE
pointer mismatch in geos/ggraph.h ?

### ISSUE THREAD

**Issue by mrdudz** [cc65/cc65#1508]
This looks also kindof suspicious and wrong in one way or another. The geos "getid" sample does
```
const graphicStr Table = {
    NEWPATTERN(0), MOVEPENTO(0, 0), RECTANGLETO(320, 199), GSTR_END };
GraphicsString(&Table);
```
in ggraph.h there is
```
void __fastcall__ GraphicsString(char *myGfxString);
typedef void graphicStr;
#define MOVEPENTO(x,y) (char)1, (unsigned)(x), (char)(y)
#define LINETO(x,y) (char)2, (unsigned)(x), (char)(y)
#define RECTANGLETO(x,y) (char)3, (unsigned)(x), (char)(y)
#define NEWPATTERN(p) (char)5, (char)(p)
#define FRAME_RECTO(x,y) (char)7, (unsigned)(x), (char)(y)
#define PEN_X_DELTA(x) (char)8, (unsigned)(x)
#define PEN_Y_DELTA(y) (char)9, (char)(y)
#define PEN_XY_DELTA(x,y) (char)10, (unsigned)(x), (char)(y)
#define GSTR_END (char)NULL
```
this generates a warning - and i'd expect that.

So should the prototype of the function be changed? why is graphicStr void? shouldnt either the function take void* or the type be char?

**Comment by greg-king5** [comment]
The macros initiate elements with two data types.  That needs cc65's void array extension.  The prototype is wrong.

**Comment by mrdudz** [comment]
so it should be 
```
void __fastcall__ GraphicsString(void *myGfxString);
```
?

**Comment by greg-king5** [comment]
> so it should be
> ```c
> void __fastcall__ GraphicsString(void *myGfxString);
> ```
> ?

Yes.

**Comment by mrdudz** [comment]
wait - shouldnt it be "const void*" actually? :)

**Comment by mrdudz** [comment]
ah well, pushed the change. all warnings in samples gone :)
