### ISSUE TITLE
Compiling errors when using the command

### ISSUE THREAD

**Issue by WilliamWangPeng** [cc65/cc65#1516]
HI dear author,  
    It's truly a honor to write a letter to you,  I'm building your project nowadays and found the error when building as following, I wonder if there is a chance that you know the reason? :)

![image](https://user-images.githubusercontent.com/51076736/119221422-eda10600-bb21-11eb-916b-75ba4d95ebec.png)

thank you  
best regards to you  
William

**Comment by Marrin** [comment]
Well, the immediate reason is, that there is no floating point support.  See the documentation about the [Differences to the ISO standard](https://cc65.github.io/doc/cc65.html#s4).

If it had floating point support, the next problem would be the missing support for the OpenGL API on most, if not all cc65 target system. 😉

I think you are a bit confused about the scope of this project: cc65 is a cross compiler that produces binaries for 6502 based systems.  Without giving a system at the command line, it defaults to the [Commodore 64](https://en.wikipedia.org/wiki/Commodore_64) (C64) as target.

**Comment by polluks** [comment]
Sorry, too late for April Fool's Day :)
