### ISSUE TITLE
AppleSingle Header: Wrong entry length

### ISSUE THREAD

**Issue by Pixinn** [cc65/cc65#1522]
I assembled a program which features the following segments:

```text
Segment list:
-------------
Name                   Start     End    Size  Align
----------------------------------------------------
NULL                  000000  000000  000000  00001
ZEROPAGE              000000  000000  000000  00001
EXEHDR                0007C9  000802  00003A  00001
CODE                  000803  001D2E  00152C  00001
CODE2                 006000  0060EF  0000F0  00001
RODATA                006100  006B43  000A44  00100
DATA                  006C00  008497  001898  00100
BSS                   008500  00910A  000C0B  00100
```

In order for this program to work, it requires CODE, CODE2, RODATA and DATA to be loaded in memory.
Accounting for the padding inserted to get the memory alignment of both data sections, this represents **$39C4** bytes.
(*These segments are relocated to their final location when the program is run*)

Unfortunately the length field of the "data fork" entry in the header is only **$15C2**, which correspond to the sole *CODE* segment. Thus AppleCommander produces a file that is truncated at $15C2.

Here the header from the linked binary file:
```text
00 05 16 00 00 02 00 00 00 00 00 00 00 00 00 00
00 00 00 00 00 00 00 00 00 02 00 00 00 01 00 00
00 3A 00 00 15 2C 00 00 00 0B 00
```

If I manually patch the header in the binary to replace $152C by $39C4, the file is not truncated by AppleCommander anymore and my program executes flawlessly.

Unless I am missing something, the length of the first entry should be the size of all code and initialized data segments which is the size of the produced binary minus $3A

**Comment by oliverschmidt** [comment]
The value in question is computed at https://github.com/cc65/cc65/blob/010eea12a2fe03d6fd41aca307076aed8d1299c0/libsrc/apple2/exehdr.s#L15

Your linker config file is structured in a way that the assumption made by the code linked above isn't true. Either you change your linker config to match that assumption or you provide your own variant of exehdr.s.

**Comment by polluks** [comment]
Maybe some kind of assert can help?

**Comment by oliverschmidt** [comment]
If an assert were possible, it would be possible as well to do it always right in the first place.

**Comment by Pixinn** [comment]
I understand that I was mistaken in my usage of the segments, which was not apparent to me as I was using V2.16.
Now I avoid placing code and data into the "HGR hole" using the "load" and "run" properties of the segments, and MAIN can encompass all the relevant segments.
Thanks for the answer.

**Comment by oliverschmidt** [comment]
Regarding the HGR hole management you might be interested in https://github.com/cc65/cc65/blob/master/targettest/apple2/hgrtest.c (primarily in the referenced linker config).

**Comment by Pixinn** [comment]
Thanks. But if I understand well, loading the HGR segment in main will inflate the resulting binary as zeros will be included in it. Although it will spare relocating the segment placed after HGR.

**Comment by oliverschmidt** [comment]
And as a general remark: The linker configs allow for a huge amount of flexibility. But you can use that flexibility only if you only link your own code. As soon as you link in thing like the C startup code, parts of the C library (or just some exe header) you have to adhere to assumptions made by those codes regarding the linker config used.
However, the assumptions made depend on many aspects and are sometimes pretty subtile, so it's basically impossible to document those things.
And to make things worse, those assumptions change over time. So project-specific linker configs tend to break with later cc65 versions. This situation is for sure sub-optimal. The only workaround I know of is to deliver many linker configs (additionally customizable via cmdline variables) with cc65, making project-specific ones less necessary.

**Comment by oliverschmidt** [comment]
Yes, the idea is to embed a splash/welcome screen into the binary. Alternatively you can use Exomizer to compress the zeros. Exomizer has by now nice Apple II support incl. direct support for Apple Single files :-)

**Comment by Pixinn** [comment]
I did not know about Exomizer: I will read about it. Thanks.
