### ISSUE TITLE
[feature] More nested #if directives

### ISSUE THREAD

**Issue by Fabrizio-Caruso** [cc65/cc65#1523]
I know my project Cross-Lib (universal cross-dev-kit retro-hardware abstraction layer: https://github.com/Fabrizio-Caruso/CROSS-LIB) is pushing the pre-processors of cross-compilers a bit, but I am hitting a limit only with CC65. 
No problem with Z88DK (SDCC, SCCZ80), GCC, ACK, CMOC, LCC1802, etc.
I get this error:
` Error: Too many nested #if clauses `

Could you please increase the number of nested `#if` directives?

**Comment by mrdudz** [comment]
Could you create a testcase? :)

**Comment by Fabrizio-Caruso** [comment]
@mrdudz my test case is Cross-Lib. I have re-arranged it so that it still compiles but I am still close to CC65 limit.
I can build an artificial smaller case.
It is just a long list of 
```
#if
#elif
#elif
...
#endif
```

**Comment by spiro-trikaliotis** [comment]
@Fabrizio-Caruso, your example is not a nested list. I don't see why such an #if/#elif sequence should have a limit. Are you sure that this is the case? (That's why a minimal testcase is needed).

**Comment by Fabrizio-Caruso** [comment]
@spiro-trikaliotis I will try to provide a simple example but my example is a nested if. 
Maybe some indentation makes it more appaent:
```
#if ...
...
#elif
    ...
    #elif
        ...
       #elif
           ...
```

**Comment by mrdudz** [comment]
This is not nested :) This is:
```
#if
 #if
  #if
   #if
   #endif  
  #endif
 #endif
#endif
```

**Comment by Fabrizio-Caruso** [comment]
`#elif` is clearly a nested construction as it applies only if the previous` #elif` is not entered. 
A sequence of `#elif` is not like a sequence of `#if`. 
You need a stack to evaluate` #elif` as for any other nested construction.

Anyway, this is not the point. CC65 calls it nested `#if` when it complains about the error.

The error is triggered by a trivial sequence of `#elif` as in the attached trivial example
[foo.zip](https://github.com/cc65/cc65/files/6565364/foo.zip)

The error is triggered when compiled with:
`cl65.exe -D__FOO29__ foo.c -o foo.prg`

**Comment by mrdudz** [comment]
> You need a stack to evaluate #elif as for any other nested construction.

no. there are no nesting "levels", its one #if after the other, you can evaluate one #if after the other, there is no need to stack anything, it can be done by simple forward parsing+evaluating (which is basically what spiro hinted).

now i really wonder how this is implemented, as spiro said, this kind of thing should have no limit :)

**Comment by Fabrizio-Caruso** [comment]
@mrdudz It seems CC65 is interpreting as a nested structure and it is hitting a stack limit.
It should interpret it in a stack-less way but it is probably not doing it.

**Comment by greg-king5** [comment]
cc65 implements `#elif` as `#else #if`.  It _is stacked_ (but, it doesn't need a matching `#endif`)!  The current limit is 64 nested `#if`, `#ifdef`, `#ifndef`, and `#elif`.

I can increase the limit to 256.  (Can you type enough to need more than that? :smiling_imp:)

**Comment by Fabrizio-Caruso** [comment]
Thanks @greg-king5, I think 256 is a safe (for the moment). I could hit the 256 limit one day. 
I am already considering more than 200 targets but many of them can be grouped together. 
If I were to write some nested #if for each single target I would be very close to 256. If I hit the limit, I could re-think the way I use the directives. I could always do it in a very ugly way with #undef and no nested #if.

@mrdudz, @spiro-trikaliotis  The easy, natural and most generic way to interpret #elif is as a nested #if. 
This is how CC65 interprets it in all cases. 
Your interpretation would be a nice optimization because there is no strict need for a stack in this very specific case but in order to do it without a stack you would need to have an optimizer for the pre-processor. Since the pre-processor works offline, it is not so bad.

**Comment by mrdudz** [comment]
> But in order to do it without a stack you would need to have an optimizer for the pre-processor.

Ehrm. No. Just simple forward parsing.

**Comment by Fabrizio-Caruso** [comment]
@mrdudz ok, it would be simple but it would be an optimization because it does not change the semantics. It is just a simple optimization. If someone knows how to do it, it would be nice to have but it is not so important because it is done offline anyway.
My very long sequence of nested #if is evaluated very quickly despite the use of the stack.

**Comment by mrdudz** [comment]
Not sure why you insist on calling it an "optimization" :) To me what it does now is just an ugly hack, probably tacked on as an afterthought.

**Comment by Fabrizio-Caruso** [comment]
@mrdudz ok, I think #if #elif = #if #else #if, so it is just an #if inside the #else statement. CC65 is just interpreting #elif as #else #if inside an #if. So the same code used for nested #if is also used in this case. It is just the simplest, yet, not the best way to interpret a sequence #elif. It is general (not super efficient) approach. I am not sure 100% as I have not seen the code but that is how I would implement it if efficiency were not important.
