### ISSUE TITLE
.ifdef bug?

### ISSUE THREAD

**Issue by frranck** [cc65/cc65#1533]
hello,

If I do
```
COLOR_PATCH = 1

.ifdef COLOR_PATCH
		LDX #COLOR_PATCH
		LDY #$0f
		LDX #$f0
		LDY #$0f
.else 
doesnt get included
.endif

.ifdef COLOR_PATCH
doesnt get included
.endif

```

If I remove "LDX #COLOR_PATCH"
then the second block gets included.
Am I missing something obvious?

ca65 V2.18 - Git beaa77d2d

**Comment by greg-king5** [comment]
That version is more than a year old.  The bug seems to be fixed.  The current version is
ca65 V2.19 - Git 1c16e46f2369306fa7397dbde8750aad3b824816.
It works as expected.
