### ISSUE TITLE
cl65 not capable of changing directories with -o

### ISSUE THREAD

**Issue by Kaleidio** [cc65/cc65#1550]
It will just spit out the file in the same directory as the source, which is the default.  no matter what directory path I put on -o, it will always do the default path.

cl65 -O -c src/game.c -o obj/game.o was the command used.  The .o ended up in src/game.o instead of the expected obj/game.o

all makefiles that attempt this behave the same as well, which is where I discovered this.

**Comment by greg-king5** [comment]
> `cl65 -O -c src/game.c -o obj/game.o`

cl65 is a _simple_ driver program.  It's very sensitive to the order of the objects on the command line.  It walks the line left to right.  It compiles/assembles source files as soon as it sees their names.  Therefore, if you want to control how a file is handled, then you must put those options on the left side of the name.  This line works as you wish:
```
cl65 -O -c -o obj/game.o src/game.c
```
