### ISSUE TITLE
Trivial program with "none" config generates unhelpful ld65 error

### ISSUE THREAD

**Issue by willisblackburn** [cc65/cc65#1551]
My program is this:

```
// main.c
int main(int argc, char* argv[]) {
    return 0;
}
```

I'm compiling and linking like this:

```
C:\project>cc65 --version
cc65 V2.19 - Git fcda94f

C:\project>cc65 main.c
main.c:4: Warning: Parameter 'argc' is never used
main.c:4: Warning: Parameter 'argv' is never used

C:\project>ca65 main.s

C:\project>ld65 -v -t none main.o none.lib
ld65: Error: 1 unresolved external(s) found - cannot create output file
```

If I replace "none" in both places with "c64" then it runs and generates a file.

The bug I'm reporting is that ld65 doesn't tell me what the unresolved external actually is. If I knew that, the problem with my program would be easier? to fix.

**Comment by willisblackburn** [comment]
Removing argc and argv fixes the problem, presumably by removing ".forceimport initmainargs" from main.s. I don't need argc and argv, I'm just used to always including them. Possibly "none" doesn't support args.

I think ld65 should have reported the missing initmainargs symbol, that would have led me right to the solution.

**Comment by greg-king5** [comment]
```c
$ cat test-none.c
extern void foo(void);

void main(int, char **)
{
    foo();
}

$ cl65 -t none test-none.c
test-none.s:28: Error: Unresolved external '_foo'
ld65: Error: 2 unresolved external(s) found - cannot create output file
```
When ld65 tells us that an import is missing, it gives us the line number in the Assembly source file where that symbol name first is accessed.  But, the idea of `.forceimport` is to request an import even when the name isn't accessed.  Therefore, there usually is no line number for a message.  ld65 currently doesn't give us a message in that case.

We need to make ld65 produce a diagnostic anyway!

**Comment by willisblackburn** [comment]
Could you just record the number of the line with the .forceimport statement?

**Comment by mrdudz** [comment]
Just found myself chasing ghosts because of the mentioned problem - so i fixed it in the linker, which now gives an error message now. I don't know if or even how it is possible to record the line number though - right now it will just dump the non resolved symbols without line number too - hoping this doesnt result in a spill of useless messages in some other situation i couldnt think of right now.
