### ISSUE TITLE
cc65-master, cc65 compiler crashes.

### ISSUE THREAD

**Issue by NollKollTroll** [cc65/cc65#1552]
Running Linux Mint 20.1, compiling Fuzix latest with cc65 latest gives the following:
cl65 -c -t none -O -D__STDC__ -c -O -I/home/adam/work/FUZIX/Library/include -I/home/adam/work/FUZIX/Library/include/6502 stak.c
cl65 -c -t none -O -D__STDC__ -c -O -I/home/adam/work/FUZIX/Library/include -I/home/adam/work/FUZIX/Library/include/6502 string.c
cl65 -c -t none -O -D__STDC__ -c -O -I/home/adam/work/FUZIX/Library/include -I/home/adam/work/FUZIX/Library/include/6502 word.c
cl65 -c -t none -O -D__STDC__ -c -O -I/home/adam/work/FUZIX/Library/include -I/home/adam/work/FUZIX/Library/include/6502 xec.c
cl65: Subprocess 'cc65' aborted by signal 11
make[2]: *** [Makefile.6502:26: xec.o] Error 1
make[2]: Leaving directory '/home/adam/work/FUZIX/Applications/V7/cmd/sh'
make[1]: *** [Makefile:16: sh] Error 2
make[1]: Leaving directory '/home/adam/work/FUZIX/Applications'
make: *** [Makefile:99: apps] Error 2

Running with cc65 release V2.19 works correctly.

More details in https://github.com/EtchedPixels/FUZIX/issues/862

**Comment by mrdudz** [comment]
I am trying to make a minimal testcase from this atm.... first observation is that it doesnt crash without -O

@NollKollTroll could you try building fuzix with git head and -O removed?

**Comment by mrdudz** [comment]
So here it is: 

```

/*
    bug #1552 - crash in fuzix xec.c

    cc65 -t none -O bug1552.c
*/

#include <stdio.h>

typedef struct trenod *TREPTR;
typedef struct whnod *WHPTR;

struct trenod {
    int tretyp;
};

struct whnod {
    int whtyp;
    TREPTR whtre;
};

int execute(TREPTR argt, int execflg, int *pf1, int *pf2)
{
    register TREPTR t;
    int type;
    switch (type) 
    {
        case 6:
        {
            while ((execute(((WHPTR) t)->whtre, 0, NULL, NULL) == 0) == (type == 5)) {

            }
            break;
        }
    }
    return 0;
}
```
@acqn perhaps have a look? :)

**Comment by mrdudz** [comment]
´´´
4d5fe3854033b1b24d20fa4eb40e38dbf34c7cc9 is the first bad commit
commit 4d5fe3854033b1b24d20fa4eb40e38dbf34c7cc9
Author: acqn <acqn163@outlook.com>
Date:   Fri Sep 18 20:23:03 2020 +0800

    Fixed OptStackOps when the stuff pushed on stack top is accessed before the op.
´´´

**Comment by NollKollTroll** [comment]
Just tried cc65-head with Fuzix-head and it does not crash anymore, BUT it does not work correctly.
Using cc65-2.19 completes "make all" without any problem.
Using cc65_head fails and shows this at the end, which I interpret as the new version of cc65 still not liking xec.c for some reason:

cl65 -c -t none -O -D__STDC__ -c -O -I/home/adam/work/PZ1-laptop/FUZIX_head/Library/include -I/home/adam/work/PZ1-laptop/FUZIX_head/Library/include/6502  xec.c
cl65: Subprocess 'cc65' aborted by signal 11
make[2]: *** [Makefile.6502:26: xec.o] Error 1
make[2]: Leaving directory '/home/adam/work/PZ1-laptop/FUZIX_head/Applications/V7/cmd/sh'
make[1]: *** [Makefile:16: sh] Error 2
make[1]: Leaving directory '/home/adam/work/PZ1-laptop/FUZIX_head/Applications'
make: *** [Makefile:103: apps] Error 2

**Comment by mrdudz** [comment]
? That looks pretty much like the original issue and crash (there were no fixes since your last try)

What would help is if you edit out the -O from the makefile and see if it works then (if it does, the problem is in the optimizer somewhere)

**Comment by NollKollTroll** [comment]
Right you are, sorry about that. Brain fart...
Yes, removing -O from the rules.6502 in Applications -> "make all" correctly executes using cc65_head.

**Comment by mrdudz** [comment]
Fine - so lets hope @acqn wakes up soon :)

**Comment by acqn** [comment]
> 
> 
> [4d5fe38](https://github.com/cc65/cc65/commit/4d5fe3854033b1b24d20fa4eb40e38dbf34c7cc9) is the first bad commit
> commit [4d5fe38](https://github.com/cc65/cc65/commit/4d5fe3854033b1b24d20fa4eb40e38dbf34c7cc9)
> Author: acqn [acqn163@outlook.com](mailto:acqn163@outlook.com)
> Date: Fri Sep 18 20:23:03 2020 +0800
> 
> ```
> Fixed OptStackOps when the stuff pushed on stack top is accessed before the op.
> ```

As usual, the bug was somewhere else... Hope this fix it: f0f5224cb884690c8316591160b545f65a9fa221

**Comment by oliverschmidt** [comment]
@mrdudz: As always I'd appreciate if you would create a regression test from your minimal testcase in https://github.com/cc65/cc65/issues/1552#issuecomment-913669111 - thanks in advance!

**Comment by mrdudz** [comment]
I am on it. If only github didnt decide to not let me log in again, and git itself is playing tricks on my to prevent that from ever happening again =P

**Comment by mrdudz** [comment]
@NollKollTroll perhaps you can try fuzix with head again? :)
