### ISSUE TITLE
Memory Overflow on the vic20

### ISSUE THREAD

**Issue by KenwoodFox** [cc65/cc65#1555]
Hello! Im trying to get started with cc65 and I think I'm doing something wrong, I'm trying to follow this tutorial: https://cc65.github.io/doc/intro.html#ss6.5

I'm using the example code found in `/usr/share/cc65/samples/tutorial/` and I've copied it to a directory to do the code compilation.

I'm following the instructions along but when I try and build for the vic20 I get this error:
```
cl65 -O -t vic20 hello.c text.s
ld65: Warning: /usr/share/cc65/cfg/vic20.cfg(10): Segment 'DATA' overflows memory area 'MAIN' by 65 bytes
ld65: Error: Cannot generate most of the files due to memory area overflow
```

Am I doing this incorrectly? Thanks so much for reading!

**Comment by groessler** [comment]
works for me:

```
[~/atari/cc65/samples/tutorial]$ cl65 -O -t vic20 hello.c text.s
[~/atari/cc65/samples/tutorial]$ cl65 --version
cl65 V2.19 - Git 974d505d9
[~/atari/cc65/samples/tutorial]$ ls -l
total 16
-rw-r--r-- 1 chris chris 1814 Jun 15 17:58 Makefile
-rw-r--r-- 1 chris chris 2624 Aug 30 13:00 hello
-rw-r--r-- 1 chris chris  163 Feb 15  2021 hello.c
-rw-r--r-- 1 chris chris   63 Feb 15  2021 text.s
[~/atari/cc65/samples/tutorial]$ 
```

**Comment by KenwoodFox** [comment]
Hm, 
```
❯ cl65 -O -t vic20 hello.c text.s
ld65: Warning: /usr/share/cc65/cfg/vic20.cfg(10): Segment 'DATA' overflows memory area 'MAIN' by 65 bytes
ld65: Error: Cannot generate most of the files due to memory area overflow 
❯ cl65 --version
cl65 V2.18 - Git ece63f0
```

**Comment by KenwoodFox** [comment]
Looks like updating to your version fixed it, thanks so much~ Sorry for being dumb.

The solution is always to check for updates duh!

```
❯ cl65 -O -t vic20 hello.c text.s
❯ cl65 --version
cl65 V2.19 - Git 52e438792
```

**Comment by Fabrizio-Caruso** [comment]
What I do is simply have the charset in the binary at the right place. So when you load the binary, the charset is already there. This is done by having a linker config file that does just that.
I have done this on different Vic 20 configurations, as well as the C16.
For examlple: 
In
https://github.com/Fabrizio-Caruso/CROSS-LIB/blob/master/src/makefiles.chase/Makefile.cc65_targets#L967
I use:
https://github.com/Fabrizio-Caruso/CROSS-LIB/blob/master/src/cross_lib/cfg/cc65/vic20-8k_GFX.cfg

My config files are not the cleanest nor the best possible but they may give you an idea on how to do it for your case.
