### ISSUE TITLE
how to build for c64?

### ISSUE THREAD

**Issue by RodrigoDornelles** [cc65/cc65#1559]
i managed to builder my project for apple][ following the tutorial. but i didn't find anything on the wiki about commodore, how can i package the c64 binary to an image file loadable by emulators?

**Comment by polluks** [comment]
You may use c1541.

**Comment by polluks2** [comment]
See https://github.com/cc65/cc65/blob/65c640d2cf1059e97e518feb3a3a348a70a95636/samples/Makefile#L88

**Comment by mrdudz** [comment]
note that if you do not have more than one file, you don't have to put it into a disk image at all, most emulators can run plain binaries (in cbm .prg format, which the toolchain produces by default).

c1541 is in the VICE package, you use it like

c1541 -format "foo,00" d64 foobar.d64 -write myprog.prg "myprog" -write mydata.prg "mydata"

**Comment by oliverschmidt** [comment]
https://cc65.github.io/doc/intro.html#ss6.5

**Comment by RodrigoDornelles** [comment]
thank you so much for your attention, i'm ready to start now! 👍
