### ISSUE TITLE
Example for conditional assembling in CA65

### ISSUE THREAD

**Issue by skeetor** [cc65/cc65#1561]
Is there somewhere an example how to use the '.if' command to conditionally assemble some block? The documentation is very terse and just says it has to evaluate to true or false but no example or anything else.

I wanted to assemble this

```
.if ((_EntryPoint / 10000) .mod 10)
. out "is not 0"
.else
. out "is 0"
.endif
```

but I get an error 

> hello_world.s(49): Error: Constant expression expected
> hello_world.s(52): Error: Unexpected trailing garbage characters

**Comment by skeetor** [comment]
Hmm. I figured it out now. _EntryPoint is not known at the time this is assembled, because the label comes later. Seems I have to find something else to achieve this.

**Comment by greg-king5** [comment]
It's worse than that!  `_EntryPoint` is a "relative" label.  Its address isn't known by the assembler.  That address is set by ld65 later (long after the assembly has finished).  Therefore, ca65 cannot test that label (no matter where it sits in the source file).

**Comment by skeetor** [comment]
> It's worse than that! `_EntryPoint` is a "relative" label. Its address isn't known by the assembler. That address is set by ld65 later (long after the assembly has finished). Therefore, ca65 cannot test that label (no matter where it sits in the source file).

Thanks for the clarification. You are right, I should have thought of that. :p But __LOADADDRESS__ should be known, so maybe it is possible to calculate it fro that?

**Comment by greg-king5** [comment]
> But, **LOADADDRESS** should be known, so maybe it is possible to calculate it from that?

Yes.  If you decide before assembly what the load address will be, then you can tell ca65 where `_EntryPoint` will be.  That constant value can be tested.
