### ISSUE TITLE
cc65 generates incorrect code for logical expression with -O

### ISSUE THREAD

**Issue by willisblackburn** [cc65/cc65#1562]
The following program illustrates the issue. Removing -O or adding parentheses fixes the problem.

Context: I'm parsing a string and want to stop at the last double-quote, as long as it's not immediately followed by another double-quote.

Possibly cc65 is losing track of the higher precedence of `&&` over `||` during the optimization process. Or maybe it doesn't get the precedence right in general, and the result is coincidentally correct without -O.

```
#include <stdio.h>
#include <string.h>

char input[256];

#define DEBUG(x) printf("%s=%d\n", #x, (x))

int main(void) {
    char* r;
    strcpy(input, "\"XYZ\"");
    r = input+4;
    DEBUG(*r != '"');       // = false
    DEBUG(*r == '"');       // = true
    DEBUG(*(r+1) == '"');   // = false
    // Next answer should be false because
    // (false || true && false) is false, but it is true with -O.
    DEBUG(*r != '"' || *r == '"' && *(r+1) == '"');
    // Adding parens fixes it even with -O.
    DEBUG(*r != '"' || (*r == '"' && *(r+1) == '"'));   
    return 0;
}
```

**Comment by acqn** [comment]
I think this old bug has been fixed in the current head revision (28b1687aafc4c124cbb6664d20d4b0759125d350) already since  few months ago.

**Comment by mrdudz** [comment]
yes, this is working in head

**Comment by polluks** [comment]
Are we ready to release 2.20?
