### ISSUE TITLE
Apple //e SSC driver: ser_open() with SER_HS_NONE unexpectedly returns SER_ERR_NO_DRIVER

### ISSUE THREAD

**Issue by jeremyvisser** [cc65/cc65#1568]
I would like to use the `a2e_ssc_ser` driver, and wanted to use it in a situation where I anticipated no hardware or software flow control being available.

However, specifying `SER_HS_NONE` as a parameter causes `ser_open()` to unexpectedly fail with error code 1 (apparently "`SER_ERR_NO_DRIVER`" but the driver is otherwise loaded fine).

The following program illustrates the issue:

```c
// cl65 -t apple2enh -C apple2enh-system.cfg ser.c -o ser

#include <stdio.h>
#include <apple2enh.h>
#include <serial.h>

struct ser_params params = {
  SER_BAUD_9600,
  SER_BITS_8,
  SER_STOP_1,
  SER_PAR_NONE,
  SER_HS_NONE  // <-- "ser_open: 1"
  //SER_HS_HW  // <-- "ser_open: 0"
};

void main() {
  ser_install(a2e_ssc_ser);
  ser_apple2_slot(2);
  printf("ser_open: %d\n", ser_open(&params));
}
```

It’s possible that flow control is required by the SSC and this is just a sanity check. If so, making this more explicit in the documentation would be good. Also, returning `SER_ERR_INIT_FAILED` (8) instead of `SER_ERR_NO_DRIVER` (1) would significantly reduce confusion.

I can work around the issue by using hardware flow control but was curious whether this was intended behaviour.

**Comment by oliverschmidt** [comment]
> It’s possible that flow control is required by the SSC and this is just a sanity check.

That's exactly how it is.

> Also, returning SER_ERR_INIT_FAILED (8) instead of SER_ERR_NO_DRIVER (1) would significantly reduce confusion.

Hm, looking at https://github.com/cc65/cc65/blob/master/libsrc/apple2/ser/a2.ssc.s#L202-L206 and https://github.com/cc65/cc65/blob/master/libsrc/apple2/ser/a2.ssc.s#L265-L268 I'd say it already does the very thing you propose...

> I can work around the issue by using hardware flow control but was curious whether this was intended behaviour.

Always good to check :-)

**Comment by jeremyvisser** [comment]
Thank you for that information. You are absolutely right that the implementation is already correct.

In fact, now I realise the bug that was misleading me. When pasting my reproduction code into the above, I had edited it for brevity, but in fact my original reproduction code used this instead:

```
if (err = ser_open(&ser_params) != SER_ERR_OK) {
  printf("ser_open failed: %u\n", err);  // "ser_open failed: 1"
}
```

A classic order of operations bug. If I edit it to:

```
if ((err = ser_open(&ser_params)) != SER_ERR_OK) {
```

Then I can definitely confirm the result is 8, which is correct.

I apologise for this error: very embarrassing on my part.

Thanks for the link to the source code, and for confirming SER_HS_HW is the only supported option.

Though the docs only implicitly suggest only hardware flow control is supported, I think if I had not had that bug, I would have been clued into the fact that a parameter was wrong.

So I apologise again for this, and thank you for your work.

**Comment by oliverschmidt** [comment]
> [...] the docs only implicitly suggest only hardware flow control is supported [...]

I fully agree with you - https://github.com/cc65/cc65/commit/28b1687aafc4c124cbb6664d20d4b0759125d350

**Comment by jeremyvisser** [comment]
That’s fantastic — thank you very much for the doc updates!  :-)
