### ISSUE TITLE
videomode on unenhanced Apple //e

### ISSUE THREAD

**Issue by ryandesign** [cc65/cc65#1572]
The [documentation](https://cc65.github.io/doc/funcref.html#videomode) says:

> The [videomode] function is specific to the Commodore 128, the enhanced Apple //e, and the Commander X16.

Why is this function not available on an unenhanced Apple //e?

**Comment by oliverschmidt** [comment]
There are quite some Apple II models.

If we had only one target for all Apple II models, it would either be "the IIgs in 8bit mode" and would show a lot of undefined behavior when being used on another machine. Or it would be the original ][ and would have a lot of missing features.

If we had an individual target for each Apple II model, we would end up with "too many" targets - in whatever metric introduced by whomever.

So the compromise is to have more than one target for the Apple II models - but not a lot. I ended up with defining two targets:
* A low end target compatible with every Apple II having AppleSoft.
* A high end target having a) consistent lower case support (incl. inverse lower case screen output) and b) the 65C02 instructions.

The unenhanced //e is an unfortunate habitant of this setup. It would be able to support many features of the cc65 high end target, but not a) and b) above. Therefore the high end features it could support aren't available to it.
