### ISSUE TITLE
__LINE__ macro seems to not work, at least not with concatenation operator

### ISSUE THREAD

**Issue by PrinnyCanBeHero** [cc65/cc65#1573]
Trying to use a static assertion macro to check things at compile time e.g. array sizes. It uses __LINE__ and the ## concat operator to generate a unique typename. 

```
#define CASSERT(predicate, file) _impl_CASSERT_LINE(predicate,__LINE__,file)

#define _impl_PASTE(a,b) a##b
#define _impl_CASSERT_LINE(predicate, line, file) \
    typedef char _impl_PASTE(assertion_failed_##file##_,line)[2*!!(predicate)-1];
```
    
For some reason __LINE__ doesn't get evaluated, though it's in the list of preprocessor supported macros...

> $ make
> cl65 -t cx16 -O hello.c character.c d6radix.c dice.c memory.c text.s
> character.c:18: Error: Size of array 'assertion_failed_character_c___LINE__' is invalid
> 1 errors and 0 warnings generated.
> make: *** [Makefile:2: hello] Error 1

**Comment by acqn** [comment]
```c
#define CONCAT(a,b) _impl_CONCAT(a,b)
#define _impl_CONCAT(a,b) a##b
char CONCAT(ident,__LINE__)[0+__LINE__];
char CONCAT(ident,__LINE__)[0+__LINE__]; // Error in cc65
```
Output:
```
Error: Conflicting array types for 'ident__LINE__[]'
```
Apparently, `__LINE__` is not working in cc65 with concatenation operator.
