### ISSUE TITLE
Mixing too many segments leads to invalid addresses.

### ISSUE THREAD

**Issue by skeetor** [cc65/cc65#1579]
In my code I wanted to include library routines. Since I need the library routines to be at a certain address the main code has an .ORG statement and afterwards I do 'include "function_xx.s".

The included function basically looks like this:
```
.segment "CODE"

... code ...
.include "lib1.s"
.include "lib2.s
...
.segment "DATA"
```

Each of the library files can have also data so the often look like this as well:
```
.segment "CODE"
... code ...
.segment "DATA"
... data..
```

This means that the final source looks like this to the assembler:
```
.segment "CODE"
...
.segment "DATA"
...
.segment "CODE"
...
.segment "DATA"
...
.segment "CODE"
...
.segment "DATA"
...
```

Now I have the problem that the address of some code was overwritten with labels and data from one DATA segment. When I removed all the segment commands in the libfiles it works, so that the code is correct and there is only one CODE and one DATA segment instruction.

I was thinking that the linker will merge all the DATA segments into a single chunk.

**Comment by groessler** [comment]
Best would be to have a startup routine to copy these functions to their final location. So you don't need to add fill bytes to the EXE.

And, you can use "run=" linker directive, then there is no need for .org.

**Comment by greg-king5** [comment]
How many segments did you use?

**Comment by skeetor** [comment]
Sorry for the long delay, but I wanted to finish my main goal first. I now started to learn about the cfg files and now I understand why I don't need to use .org here and make proper use of segments instead. It seems that this was the root cause of my above problem, so this issue can be closed.
