### ISSUE TITLE
Cannot rerun programs

### ISSUE THREAD

**Issue by ryandesign** [cc65/cc65#1581]
I find myself surprised that I can only run an Apple II program once after being loaded from disk. If I try to run it a second time, it crashes to the Monitor.

test.c:

```
#include <conio.h>

int main(void) {
    cprintf("Hello\r\n");
    return 0;
}
```

Compile:

```
cl65 -t apple2 test.c -o test
```

Load and run in emulator:

```
]BLOAD TEST
]CALL 2051
```

Output:

```
HELLO
```

Try to run again:

```
]CALL 2051
```

Output:

```
1015-    A=08 X=FF Y=03 P=B4 S=f9
*
```

**Comment by spiro-trikaliotis** [comment]
This is a known limitation, cf. #936, for example.
