### ISSUE TITLE
[bug?][NES] Hello world example fails

### ISSUE THREAD

**Issue by int-72h** [cc65/cc65#1583]
For some reason, trying to compile the hello.c example in samples fails on the latest git revision and the last version.
The tools seem to make c64 programs fine, so it all appears to be sane, but this happens when using cl65 with -t NES (note this also happens manually with cc65):

```
test.s:138: Error: Unresolved external '_cgetc'
ld65: Error: 1 unresolved external(s) found - cannot create output file
```

However, if I remove the cgetc line, it still doesn't work. Testing with mednafen and another emulator to confirm it wasn't an issue there, it seems that the border just flickers rapidly with no text in the centre. I'll try and get a photo.
System is Arch Linux.

**Comment by int-72h** [comment]
OK with these build commands my original code still doesn't work... needs a bit more testing

**Comment by mrdudz** [comment]
this should be documented - options are strictly processed from left to right, so the -t has to come before any source files or they will use the default (c64) target.
