### ISSUE TITLE
Small error for strncpy in documentation

### ISSUE THREAD

**Issue by sharkatw** [cc65/cc65#1601]
https://www.cc65.org/doc/funcref-201.html#strncpy

The example at the bottom of the page shows "strcpy" instead of "strncpy".

strcpy (hello, "Hello world!\n", sizeof (hello) - 1);
^^^^

It should be:
strncpy (hello, "Hello world!\n", sizeof (hello) -1);

**Comment by mrdudz** [comment]
https://cc65.github.io/doc/funcref.html#ss3.254

it's already fixed. don't use the documentation at cc65.org, it is outdated :)
