### ISSUE TITLE
Pass by value being used instead of pass by reference

### ISSUE THREAD

**Issue by AlchemicRaker** [cc65/cc65#1614]
I've encountered a bug in cc65, where it is being interpreted as "pass by value" instead of "pass by reference".

One would expect these two code snippets to have the same behavior, however they do not:

`void write_ppu_data_nam(char *souce);`

**A:**
```
extern char* demoscene_nt_data;
...
write_ppu_data_nam(demoscene_nt_data);
```

**B:**
```
extern char demoscene_nt_data[];
...
write_ppu_data_nam(demoscene_nt_data);
```

Observing the generated assembly from cc65:

**A** asm:
```
;
; write_ppu_data_nam(demoscene_nt_data);
;
	.dbg	line, "src/debug.c", 11
	lda     _demoscene_nt_data
	ldx     _demoscene_nt_data+1
	jsr     _write_ppu_data_nam
```

**B** asm:
```
;
; write_ppu_data_nam(demoscene_nt_data);
;
	.dbg	line, "src/debug.c", 11
	lda     #<(_demoscene_nt_data)
	ldx     #>(_demoscene_nt_data)
	jsr     _write_ppu_data_nam
```

Perhaps my understanding of C is wrong, in which case I welcome correction. Otherwise, this is a bug in cc65.

**Comment by spiro-trikaliotis** [comment]
There is no concept of "call by reference" in C. It is **always** "call by value".
Thus, the generated code is correct.

However, you should get a diagnostic ("warning" or "error") on it for B, as you are shooting yourself in the foot:

In fact, my cc65 creates a diagnostic:

`main.c:6: Warning: Converting integer to pointer without a cast`

Don't you get one?

My cc65 version:
cc65 V2.19 - Git 6a76d6d90

**Comment by groessler** [comment]
Where is there an integer converted to pointer?

Both variants appear valid. A has a pointer var pointing to char, B takes the address of a char array. Or am I blind?

**Comment by AlchemicRaker** [comment]
Let me extend on the code I posted above just slightly, to provide additional context.
```
demoscene_nt_data:
.export demoscene_nt_data
.export _demoscene_nt_data = demoscene_nt_data
.incbin "demoscene.nam"
```

You see, demoscene_nt_data is a label exported by ca65, pointing to a large amount of char data. It may be described as a pointer to an array of characters, but it's a "pointer" that only exists while linking. It's not a C pointer.

Building with both the **A** and **B** variants in my original report, there are zero errors and zero warnings.


Here are a few more variants, along with their behaviors:

**C**, generates "Warning: Incompatible pointer conversion to 'char *' from 'char **'", but outputs my desired assembly (listed as **B** asm in the top post)
```
extern char* demoscene_nt_data;
...
write_ppu_data_nam(&demoscene_nt_data);
```


**D**, generates zero errors, zero warnings, and outputs my desired assembly (listed as **B** asm in the top post)
```
extern char demoscene_nt_data;
...
write_ppu_data_nam(&demoscene_nt_data);
```


I suppose the takeaway here is that `demoscene_nt_data` is an array of data, _not_ a pointer to an array of data, therefore describing it with `(char*)` may be incorrect.

**Comment by spiro-trikaliotis** [comment]
> Where is there an integer converted to pointer?
> 
> Both variants appear valid. A has a pointer var pointing to char, B takes the address of a char array. Or am I blind?

Sorry, I misread variant B. I completely overlooked the parenthesis for the array.

@AlchemicRaker, that's why it is always a good idea to provide full examples, not just snippets... This way, it is much more unlikely that the person looking at it will test something different (in my case: "extern char demoscene_nt_data") instead of what you had in mind.

This also applies to the data that is referred to externally. That would be part of the full compiling example.

And: Yes, it seems your analaysis is correct. Keep in mind that in C, an array and a pointer are not the same! Many people believe so - most probably because in parameters, an array is passed as a pointer to its first entry, so they are used to have it synonymous. However, this is not true outside of parameter passing.
