### ISSUE TITLE
Optimizer bug (broken C library)

### ISSUE THREAD

**Issue by oliverschmidt** [cc65/cc65#1615]
Hi,

```
#include <stdio.h>

int test(size_t alignment)
{
    /* Test alignment: is it a power of two? There must be only one bit set. */
    if (alignment & --alignment) {
        return 1;
    }
    return 0;
}

void main(void)
{
    printf("%d\n", test(2));
}
```

```
cl65 -t sim65c02 test.c
sim65 test
0
cl65 -t sim65c02 -O test.c
sim65 test
1
```

This bug is especially annoying as the expression in question is used in https://github.com/cc65/cc65/blob/master/libsrc/common/pmemalign.c#L78 and posix_memalign() is used via https://github.com/cc65/cc65/blob/master/libsrc/apple2/iobuf.s#L10 in https://github.com/cc65/cc65/blob/master/libsrc/apple2/open.s#L82. This results in Apple II file I/O being completely broken :-(

**Comment by spiro-trikaliotis** [comment]
Please note that "alignment & --alignment" does **not** contain a sequence point (cf. C99: http://www.open-std.org/jtc1/sc22/wg14/www/docs/n1256.pdf, 5.1.2.3 or Annex C), and thus, is not quaranteed to work!

For example, the compiler is free to evaluate the right side and then the left side.

**Comment by mrdudz** [comment]
so this is actually just a bug in the library code and should be sth like
```
 if (alignment & (alignment - 1)) {
```
?

**Comment by oliverschmidt** [comment]
@spiro-trikaliotis: Thanks for the hint :-)

**Comment by greg-king5** [comment]
When I wrote that code, I saved a few bytes by combining two operations.  Unfortunately, sometimes cleverness doesn't survive progress.

Oliver's PR broke the function by dropping one of those operations.  PR #1617 put it back.

**Comment by polluks** [comment]
@greg-king5 How about a new test case?
