### ISSUE TITLE
Paravirt functions not returning properly

### ISSUE THREAD

**Issue by mdsteele** [cc65/cc65#1625]
I'm using `sim65` V2.18 on macOS (installed via [`homebrew`](https://formulae.brew.sh/formula/cc65)).  Whenever I `jsr` to a paravirt function (other than `PVExit`), the paravirt function works, but then doesn't seem to return to the correct address.  `sim65` eventually terminates with something like `Error: Illegal opcode $03 at address $10000`, presumably after the PC wanders off into oblivion.

Looking at [paravirt.c](https://github.com/cc65/cc65/blob/5d84a4ba137e32163390ccd058c32ad169b4ca94/src/sim65/paravirt.c), I suspect the problem is with the last line of `ParaVirtHooks()`:

```c
/* Simulate RTS */
Regs->PC = Pop(Regs) + (Pop(Regs) << 8) + 1;
```

If I'm not mistaken, evaluation order of arguments within an expression like that is unspecified in C, and I think what's happening is that on my machine/OS, the two `Pop()` calls are happening in the wrong order, leading to setting the PC to e.g. `$3412` instead of `$1234`.  If my guess is correct, then I believe the fix would be to force the correct pop order by changing that line to something like:

```c
/* Simulate RTS */
unsigned lo = Pop(Regs);
unsigned hi = Pop(Regs);
Regs->PC = lo + (hi << 8) + 1;
```

**Comment by polluks** [comment]
Well, https://en.wikipedia.org/wiki/Operators_in_C_and_C%2B%2B#Operator_precedence
says
Function call Left-to-right

BTW my "brew info cc65" says 2.19...

2022-01-06 12:56 GMT+01:00, Matthew D. Steele ***@***.***>:

**Comment by mrdudz** [comment]
Operator precedence has nothing to do with it. The compiler can optimize that line into something that evaluates Pop(Regs) twice in any order (or perhaps even only call it once and reuse the value, not sure). In any case this is not safe to do this way, the proposed fix should work, i think. please make a PR :)

**Comment by groessler** [comment]
On 1/7/22 12:00 AM, Bob Andrews wrote:
> Operator precedence has nothing to do with it. The compiler can optimize 
> that line into something that evaluates Pop(Regs) twice in any order (or 
> perhaps even only call it once and reuse the value, not sure). In any 
> case this is not safe to do this way, the proposed fix should work, i 
> think. please make a PR :)

Yep. There is no "sequence point" 
(https://en.wikipedia.org/wiki/Sequence_point) in this line, so the 
compiler is free to use any order it likes...

regards,
chris

**Comment by mdsteele** [comment]
Thanks, I'm putting together a PR.  It turns out that my first guess was incorrect—even on my machine, the two `Pop()`s in `ParaVirtHooks()` are happening in the correct order.  (Though we should probably still sequence those calls explicitly.)

The actual problem was:
1. The little assembly program that I was running on `sim65` never initialized the stack pointer, so it started out at `sim65`'s default of `$00`.
2. When the program JSR'ed to the paravirt function, the JSR implementation in `6502.c` correctly handled stack pointer wrapping, so the return address was correctly placed at `$0100` and `$01ff`.
3. When the paravirt function tried to return, the `Pop()` function in `paravirt.c` was *not* correctly handling stack pointer wrapping, so `ParaVirtHooks()` was incorrectly reading the return address from `$0100` and `$00ff`.

The solution, which I've confirmed fixes the problem I'm seeing, is to change `Pop()` in `paravirt.c` to handle stack pointer wrapping just like the `POP()` macro in `6502.c` does:

```c
static unsigned char Pop (CPURegs* Regs)
{
    return MemReadByte (0x0100 + (++Regs->SP & 0xFF));
    // Was previously:
    // return MemReadByte (0x0100 + ++Regs->SP);
}
```

**Comment by polluks** [comment]
Maybe Regs->SP should be an unsigned char?
