### ISSUE TITLE
How do you get LD65 to automatically link required Libary/Object files?

### ISSUE THREAD

**Issue by ProxyPlayerHD** [cc65/cc65#1628]
Here's what i tried:
i have a folder called "Include" which has a few custom libraries (as .lib) in them each with their corresponding .h file that declare the functions of that library.
I added that Folder to LD65's search path by having the `-L Include` option in it's command, and i confirmed multiple times that the path is correct, i tried it with both a relative and absolute path.

but still when linking a compiled C source file that includes a .h file from that folder i'm getting unresolved external errors for the symbols that it should be able to find in one of the .lib files. (it is able to find the .h file)

here the C file called "test.c":
```
#include "FTSerial.h"
#ifdef FT_SERIAL // for testing
int main(){
	
	ftprints("Hello World!\n");
	
	return 0;
}
#endif
```
here part of the .h file:
```
#ifndef FT_SERIAL
#define FT_SERIAL

	void __fastcall__ ftprintc (char value);
	
#endif
```
and here the command i use to link everything:
SBC.cfg, SBC.lib, exehdr.o, and Interrupt.o are for my custom target.
`LD65 -C Config\SBC.cfg -m test.map -v -o test.bin Config\exehdr.o Include\Interrupt.o Temp\test.o -L Include Config\SBC.lib`
when i specifically point the linker to FTSerial.lib it works perfectly fine:
`LD65 -C Config\SBC.cfg -m test.map -v -o test.bin Config\exehdr.o Include\Interrupt.o Temp\test.o Include\FTSerial.lib Config\SBC.lib`
So why is it not able to find the library on it's own when i give it the path to it?
And if it doesn't support this, then what's the purpose of the `-L` option?

**Comment by mrdudz** [comment]
The purpose of the search path is that you dont have to give the full path on the commandline - you still have to tell the linker what to link, of course

**Comment by ProxyPlayerHD** [comment]
awww :(

oh well, is there a limit for how many parameters you can give LD65?
if not i might just adjust my batch file to go through the whole folder and add each .lib file it finds to a string which it then adds to the LD65's command.
it's functionally the same as if it were to do it on it's own, just with more work on the user side.

**Comment by mrdudz** [comment]
now i wonder why you have so many library files - if you want to link them all anyway, why not produce one library?

**Comment by ProxyPlayerHD** [comment]
i don't have a lot right now, but i want to plan for having multiple libraries in the future.
i could throw everything into one file, sure. but that would get messy and i like to have everything neatly sorted into their respective lib file.
for example have one for Serial communication, one for graphics, one for interfacing with an SD Card, etc.
plus if i ever were to get a library from online i would need to extract all object files from it and add them to the mega-lib which would be annoying

when writing a program i want to be able to just have to include the .h file and have the library work without having to adjust my batch file on a per-program bases (as different programs can use different libraries), so including everything just seems like the easiest option without creating a mega-lib file.
though i guess an alternative would be to either learn make (for Windows) or have a seperate per-program text file that lists all the lib files to include so i wouldn't need to go through the whole folder.

**Comment by mrdudz** [comment]
i can only advice against this idea - there are good reasons for why this is not how you normally do it (not only with cc65) :) you'll run into problems sooner or later with this approach, the order of linking matters, different libraries may define the same symbols, etc

In any case, i consider this solved :)

**Comment by ProxyPlayerHD** [comment]
i try to have the name of the library within any symbol it uses to avoid it clashing with other libraries.
and yea i'll likely not link everything in the Include folder.
but i still have to think of something that allows me to specify what library files to link on a per-program bases without having to manually change the command each time.

**Comment by ProxyPlayerHD** [comment]
how would a makefile do that without looking into the C source file to see what .h files are getting included?
plus i have no idea how to even use make, it looks really versatile but i would first need to learn it
