### ISSUE TITLE
Incorrect cursor behaviour on Atmos Platform

### ISSUE THREAD

**Issue by 8bit-Dude** [cc65/cc65#1632]
I found a rather strange bug affecting only the Atmos platform.

After using gotoxy(x,y) to set the cursor, some functions like cprintf() work correctly but others like scanf() and putchar() seem to ignore the Y cursor value (they print at some other Y location that appears however to recognize line feeds)...

**Comment by polluks2** [comment]
Snippet please...

**Comment by polluks** [comment]
Snippet please...

**Comment by 8bit-Dude** [comment]
`
char buffer[40];
clrscr();
gotoxy(0,2); cprintf("Session ID: "); 
gets(buffer); sscanf(buffer, "%i", &ID);  
gotoxy(0,3); cprintf("Session PASS: "); 
gets(buffer); sscanf(buffer, "%i", &PASS);  
`

**Comment by 8bit-Dude** [comment]
The message Session ID and actual input line are different

**Comment by polluks** [comment]
gets is stdio, mixing stdio and conio is undefined behaviour, sorry.

**Comment by 8bit-Dude** [comment]
Ok. So what would be a "stdio only" or "conio only" way to obtain the same results?

**Comment by polluks** [comment]
Please study the headers, for example gets() can be implemented by cgetc().

**Comment by greg-king5** [comment]
```c
unsigned int ID, PASS;
clrscr();
gotoxy(0,2); cprintf("Session ID: ");
cscanf("%u", &ID);
gotoxy(0,3); cprintf("Session PASS: ");
cscanf("%u", &PASS);
```

**Comment by 8bit-Dude** [comment]
Sorry for a late reply, I forgot to monitor this thread!
Thanks for posting an example, I understand the idea.
