### ISSUE TITLE
Very odd (wrong) error message

### ISSUE THREAD

**Issue by mrdudz** [cc65/cc65#1643]
test.c containing just two lines:
```
#include <conio.h>
#include <string.h> 
```
and then compile like
```
$ cc65 -t geos-apple geosapple.c
geosapple.c:8: Error: Include file '(*(unsigned*)0x53).h' not found
1 errors and 0 warnings generated.
```
now isn't that one interesting? :)

**Comment by polluks** [comment]
Alas, after 20 years our cpp seems not to be bulletproof.

**Comment by acqn** [comment]
Looks like a preprocessor bug:
```c
#define string 1234
#include <string.h> /* Error: Include file '1234.h' not found */
```

**Comment by acqn** [comment]
IMO the preprocessor should really do the translation phases as the C standard says instead of line-by-line "tokenization" as it is doing at present. That would help with this as well as other preprocessor-related issues such as #760 and #1373.

**Comment by mrdudz** [comment]
That'd make a lot of things easier, indeed. Sounds like a lot of work though :)
