### ISSUE TITLE
"Illegal escaped character" should be a warning

### ISSUE THREAD

**Issue by polluks** [cc65/cc65#1660]
I suppose the backslash should be dropped, it's too strict.

**Comment by mrdudz** [comment]
???

**Comment by polluks** [comment]
I checked three compilers, everyone declares "illegal escaped character" as warning.
We should not more strict than ANSI.

**Comment by mrdudz** [comment]
I have no idea what you are talking about. What is the sitation that creates this error and why is the current behaviour wrong? And what exactly does the standard say about this situation?

**Comment by mrdudz** [comment]
> What is the sitation that creates this error and why is the current behaviour wrong?

**Comment by mrdudz** [comment]
So this is about illegal escape sequences in string literals?

And what is the problem with the current behaviour of the compiler? (what other compilers do is a hint at what is allowed at best). This is most certainly an error in the program, so why shouldnt this produce an error?

**Comment by polluks** [comment]
You got it.
Well, it's an error if the standard says it's an error. Easy, eh?
For example \a in C89 is undefined therefore a simple warning.

**Comment by mrdudz** [comment]
> Well, it's an error if the standard says it's an error. Easy, eh? For example \a in C89 is undefined therefore a simple warning.

**Comment by mrdudz** [comment]
I am tempted to just close this if you cant tell what the actual problem is here. There are many places where a compiler is allowed to either generate a warning or an error, and there are other cases where cc65 choose to generate an error when other compilers generate a warning.
So why is this behaviour a problem that needs to be fixed?

**Comment by polluks** [comment]
ok ok
