### ISSUE TITLE
__CC65__ version number is incorrect

### ISSUE THREAD

**Issue by gorlik** [cc65/cc65#1667]
According to the docs the macro __CC65__ contains the compiler version.
the MSB should contain the major version number.
In src/common/version.c this is defined as:
return ((VER_MAJOR * 0x100) + (VER_MINOR * 0x10));

This will alter the major version number when VER_MINOR is >15 (currently 19)

**Comment by mrdudz** [comment]
urks, thats unfortunate. if we fix it like
```
return ((VER_MAJOR * 0x100) + (VER_MINOR));
```
(which to me seems more like what it should do), then we will break things. *shrug*

The only way to me to fix this without breaking anything would be doing the above, AND bump the major version.

**Comment by groessler** [comment]
bump major by 2, since it's already "bumped by the bug"

**Comment by mrdudz** [comment]
Oh sh*t, indeed

**Comment by polluks** [comment]
We had
2.15
2.16, internal 3.0
2 17, internal 3.1
2.18, internal 3.2
2.19, internal 3.3

**Comment by mrdudz** [comment]
There is no such thing as "internal" version number. Both are exposed to the "outside" - and right now there are two different version numbers exposed, one by GetVersionAsString() (the correct one) and one by GetVersionAsNumber() (the wrong one). The later is used for the macros defined in cc65 and ca65 (the other is the version string shown on the commandline).

**Comment by mrdudz** [comment]
And just we do not forget, the docs need to be updated too
```
__CC65__
This macro is always defined. Its value is the version number of the compiler in hex. For example, version 2.14 of the compiler has this macro defined as 0x02E0.
```

**Comment by polluks** [comment]
I don't know, why Uz was not choosing BCD ;-(
Maybe I should have intervened.

**Comment by mrdudz** [comment]
> Nobody decodes that macro. The only question that programs ask is, "Is __CC65__ defined?"

Well, do you know for sure? It CAN be used to check for a specific version of the compiler :)

Although i agree that its valid to think that whoever does so shouldnt do this and the answer is "update the code for the latest compiler"

**Comment by gorlik** [comment]
> > Nobody decodes that macro. The only question that programs ask is, "Is **CC65** defined?"

I did. This is how I found the bug. :-)
Perhaps I should have used GetVersionAsString instead. In any case I am happy to update my code once the bug is fixed.

**Comment by mrdudz** [comment]
Yeah. "nobody does this" is always a wrong assumption :)

**Comment by polluks** [comment]
It's against Murphy's Law :)

2022-02-19 23:27 GMT+01:00, Bob Andrews ***@***.***>:

**Comment by mrdudz** [comment]
Fixed in f67fb3b326b01c404c05edcb77783be19e0554c6, documented in 1b73ffb8ae8e096453c4acb7a09d802a50fca245 and a sample that shows how to compare the values of __CC65__ in 8062f8d029a11fd5b6c9fbc4408da3b0e8294872 (although still not recommended).

@gorlik @greg-king5 please have a look - i hope i didnt screw it up :)

**Comment by polluks** [comment]
Maybe we should bump right now to avoid 2.19 and 2.19-git confusion.

**Comment by mrdudz** [comment]
> Maybe we should bump right now to avoid 2.19 and 2.19-git confusion.

what confusion?

**Comment by mrdudz** [comment]
no more complaints, closing
