### ISSUE TITLE
Inconsistent result on divide with a negative numerator and a constant or variable denominator

### ISSUE THREAD

**Issue by mrdudz** [cc65/cc65#169]
When dividing a negative integer numerator by a constant number, or by a variable containing that same number, the compiler generates different results.

This sample code illustrates, and will erroneously print "Not Equal":

``` C
#include <stdio.h>
void main(void)
{
    int a = -1, b = 8;
    if ((a/8) == (a/b))
        printf("Equal\n");
    else
        printf("Not Equal\n");
}
```

Looking at the generated code, it's easy to see where the error lies. The compiler substituted a shift operation for the divide-by-a-constant. The shift operation doesn't yield the same answer as the divide if the numerator is negative.
For the case above, -1 >> 3 = -1 and -1 / 8 = 0.

``` assembly
;
; if ((a/8) == (a/b))
;
    ldy     #$03
    jsr     ldaxysp
    jsr     asrax3      ; use >> 3 to divide by 8
    jsr     pushax
    ldy     #$05
    jsr     ldaxysp
    jsr     pushax
    ldy     #$05
    jsr     ldaxysp
    jsr     tosdivax    ; use divide code to divide by 8
```

The optimizer switched to using asrax3 for the constant division; and, used tosdivax for the division by the variable, resulting in -1/8 not giving a consistent result, depending on whether the 8 is used as a literal or in a variable.

**Comment by acqn** [comment]
Are there test cases for this? I came up with 3 different ways to fix this and couldn't decide which one should be finally taken.

**Comment by mrdudz** [comment]
probably not... i can create some :) what else other than variants of the above program (using different types) would be useful?

**Comment by acqn** [comment]
> 
> 
> probably not... i can create some :) what else other than variants of the above program (using different types) would be useful?

Perhaps also with various combinations of the data sizes (how big the number is, not just padding with the sign-bit) of the both the numerator and the denominator.

**Comment by mrdudz** [comment]
something like this? http://hitmen.c02.at/temp/bug-div.zip (will add more...)

**Comment by acqn** [comment]
> 
> 
> something like this? http://hitmen.c02.at/temp/bug-div.zip (will add more...)

Thank you! It looks good (and already helps), though I think typedef or the stdint.h stuff would be better for the reference compiler.

**Comment by mrdudz** [comment]
hrm. i knew something is fishy. yeah i should rewrite it in decimal, the extra hex rule is just confusing :)

**Comment by mrdudz** [comment]
ok, update the zip, using decimals now, and usied stdint types. also added a test using longs ... the later confuses me, although i used -m32 for the reference check, i dont get the same sign "problem" as with the 8/16 bit types. not sure what exactly happens there :) please check

**Comment by acqn** [comment]
Thank you for the updates. I modified them a bit to test negative/negative as well and forgoe testing with +128, +32768 and +2147483648 when these numbers exceed the corresponding ranges of the tested signed data types.

The new 32-bit signed long testing got me with -2147483648L and it seemed similar to the hexidemical unsigned promotion. As the integer promotion rule is confusing to me too, even with the decimal constants, I investigated it a bit more, and it surprised me that, there are no "negative integer constants", but just "negated integer constants".

For example, you can't have an instant integer constant "(-128)", but just a "-(128)", which is a negation expression of the positive integer constant 128.

As this negation is carried out after the compiler has determined the data type, it could give some surprise when the constant is so large that it is promoted to unsigned, whose negation still gives an unsigned constant. In C89/90, 2147483648L is unsigned long (but signed long long in later standards), so -2147483648L is still unsigned long in C89/90 (and signed long long in later standards) and is actually (unsigned long)-2147483648UL . To get a real -2147483648, you have to cast the expression to signed long (if you can't use the long long type/LL postfix). Yeah another pitfall in C.

I'll check if there're anything that I still overlooked with the test.

**Comment by acqn** [comment]
I modified the test made by mrdudz a bit more:
[bug-div.zip](https://github.com/cc65/cc65/files/4854877/bug-div.zip)
It currently only tests some denominators that are positive or negative power-of-2 so that cc65 generates shifting code instead of divding code with them, but non-power-of-2 cases can be added easily if desired.

**Comment by mrdudz** [comment]
i'd be very reluctant with adding fast code pathes that blow up the code size... code size is almost always the bigger problem :)

**Comment by acqn** [comment]
> 
> 
> i'd be very reluctant with adding fast code pathes that blow up the code size... code size is almost always the bigger problem :)
The multiplication/division replacements with shift tranform can be enabled/disabled depending on the code size factor settings.

BTW, I think cc65 should warn about promoting an unsigned integer constant into a signed long. That would help avoiding some nasty surprises such as the -2147483748L constant being unsigned long despite it has apparently a "negative sign" (though technically not) and not a "U"/"u" suffix at all.

**Comment by acqn** [comment]
I got the wrong commits in the repository so I retracted them.... Will examine and repush them.

Comments about the test:

The equality checks between divided-by-constant and divided-by-variable (the TEST_B's) seem superfluous as the actual examination on division correctness is done with individual checks against the expected results (the TEST_A's).

Something interesting I found in the testing was that GCC (version 8.1.0) considers the expression:
```c
(int32_t)(2 * -2147483648) == 0
```
to be false even with -O0. It's not a bug as signed integer overflow is still UB in C as of today if I understand the standard correctly. Still we'd like this to be true, wouldn't we?

**Comment by oliverschmidt** [comment]
> i'd be very reluctant with adding fast code pathes that blow up the code size... code size is almost always the bigger problem :)

I second that.

**Comment by mrdudz** [comment]
pushed testcase to the repo

**Comment by oliverschmidt** [comment]
Thanks :-)
