### ISSUE TITLE
Optimizer Bug

### ISSUE THREAD

**Issue by oliverschmidt** [cc65/cc65#1690]
Source:
```c
#include <stdio.h>

void main(void)
{
  register unsigned int x = 0x200;
  register unsigned int y = 0;

  do
  {
    ++y;
  }
  while (--x);

  printf("0x%X\n", y);
}
```
Correct:
```
cl65 -t sim65c02 -O test.c
sim65 test
0x200
```
Wrong:
```
cl65 -t sim65c02 -Or test.c
sim65 test
0x100
```

**Comment by mrdudz** [comment]
is "register" what breaks it?

**Comment by polluks** [comment]
Yep, see the option.

**Comment by mrdudz** [comment]
oops /o\

**Comment by acqn** [comment]
This was a known (but not reported) bug in `OptCmp1` with labelled code entries and fixed with enhancement in my optimizer branch. The fix wasn't pushed as the enhancement part depends on utility not finalized yet. I can still try to "port" the fix here.
