### ISSUE TITLE
Wrong arithmetic function being called when mixing data types

### ISSUE THREAD

**Issue by ProxyPlayerHD** [cc65/cc65#1701]
basically i had this scenario where i was multiplying a 16-bit variable with an 8-bit literal, and storing the result into an 16-bit variable. but when running the code the numbers didn't go as high as they should've.

`16-bit = 16-bit * 8-bit`

after some testing i found out that cc65 chooses to call the 8-bit arithmetic function (mul, div, mod) despite the fact that one of the input parameters is 16-bit wide. And i feel like this shouldn't happen as it leads to incorrect results, and not even casting seems to work.

here a piece of example code i made to test it:
```
uint16_t in;
uint16_t out;

uint8_t test8 = 255;
uint16_t test16 = 255;

out = in * 255;			// calls "tosumula0"
out = in * (uint16_t)255;	// calls "tosumula0"
out = in * test8;		// calls "tosumula0"
out = in * (uint16_t)test8;	// calls "tosumula0"
out = in * test16;		// calls "tosumulax"
```
here the actual output assembly:

```
.proc	_main: near
.segment	"CODE"

	jsr     decsp4
	lda     #$FF
	jsr     pusha
	jsr     pusha0
	ldy     #$08
	jsr     pushwysp
	lda     #$FF
	jsr     tosumula0	; out = in * 255;
	ldy     #$03
	jsr     staxysp
	ldy     #$08
	jsr     pushwysp
	lda     #$FF
	jsr     tosumula0	; out = in * (uint16_t)255;
	ldy     #$03
	jsr     staxysp
	ldy     #$08
	jsr     pushwysp
	ldy     #$04
	lda     (sp),y
	jsr     tosumula0	; out = in * test8;
	ldy     #$03
	jsr     staxysp
	ldy     #$08
	jsr     pushwysp
	ldy     #$04
	lda     (sp),y
	jsr     tosumula0	; out = in * (uint16_t)test8;
	ldy     #$03
	jsr     staxysp
	ldy     #$08
	jsr     pushwysp
	ldy     #$03
	jsr     ldaxysp
	jsr     tosumulax	; out = in * test16;
	ldy     #$03
	jsr     staxysp
	ldx     #$00
	txa
	jmp     incsp7

.endproc
```
besides just using a 16-bit variable is there some way around this using literals that are smaller than 256?

**Comment by mrdudz** [comment]
could you make a complete example that compiles? does it happen also when "in" is initialized to something that isnt 0 or 1? seems weird this would happen and not catched by the existing tests

**Comment by ProxyPlayerHD** [comment]
initializing "in" to any number does not change the function being called, even when it is above 255.

```
int main(){
	uint16_t in = 1000;
	uint16_t out = 0;
	
	uint8_t test8 = 255;
	uint16_t test16 = 255;
	
	out = in * 255;
	out = in * (uint16_t)255;
	out = in * test8;
	out = in * (uint16_t)test8;
	
	out = in * test16;
	
	return 0;
}
```

`CC65 -t none -O --cpu 65C02 -o test.a65 test.c`

**Comment by mrdudz** [comment]
This really surprises me... @acqn any idea?

**Comment by greg-king5** [comment]
There's no bug.  All values of `in` above 257 simply overflow!

Both `tosumula0` and `tosumulax` give 16-bit results.

**Comment by ProxyPlayerHD** [comment]
interesting, does that mean `tosumula0` takes in 16-bit parameters like `tosumulax`?
i assume so because otherwise `in = 256;` would be truncated to `0`, breaking the result.

on another note, it still uses `tosumula0` when i change `out` to be 32-bits wide. which causes the result to be incorrect.

```
int main(){
	uint16_t in = 1000;
	uint32_t out = 0;
	
	out = in * 255; // 1000 * 255 = 255000
	
	printf("%lu", out); // value in out is 58392 though
	
	return 0;
}
```
testing the same code with an online C compiler, it works fine there.

**Comment by greg-king5** [comment]
Decompose the names:
- `tos umul ax`
first (16-bit) operand is on Top Of the Stack,
Unsigned MULtiplication,
second operand is in CPU registers, low byte in .A, high byte in .X
- `tos umul a0`
Ditto, except that the high byte of the second operand is known to be zero

In fact, `tosumulax` will use `tosumula0` when it discovers that _either_ one of its operands is less than 256.

Assignment and multiplication are separate operations.  They don't affect each other.  You must promote one of the factors in order to force a 32-bit multiply:
```c
out = in * 255uL;
```

**Comment by greg-king5** [comment]
cc65 is a 16-bit compiler.  That online compiler is 32 bits or 64-bits.  Its multiply operator implicitly is wider.

**Comment by ProxyPlayerHD** [comment]
>Decompose the names

Yea I did know about the names being made up of what they do, mul, div, mod, a0, ax, 0ax, eax, etc.
But I didn't know that TOS meant "top of the stack", neat.

>Assignment and multiplication are separate operations. They don't affect each other.

Technically that shouldn't matter, as 16\*16 and 16\*8 Multiplcation should give a 32-bit wide result.
But after doing some reading on the C standard, it apparently doesn't work like that... which honestly surprised me.
The standards says that input parameters of arithmetic functions are automatically promoted to `int` if they are a lower data type, or to `long` if atleast 1 of the 2 input parameters is also `long`.
It doesn't say anything about promoting the output.

So in the end, the compiler is correct and I'm just dumb, dammit.

**Comment by spiro-trikaliotis** [comment]
> But after doing some reading on the C standard, it apparently doesn't work like that...

It's even more complicated than that....
N1256, § 5.1.2.3 Nr. 3 states (the so-called "as-if-clause"):

"In the abstract machine, all expressions are evaluated as specified by the semantics. An
actual implementation need not evaluate part of an expression if it can deduce that its
value is not used and that no needed side effects are produced (including any caused by
calling a function or accessing a volatile object)."

There are even examples in No 10ff, in which the standard says what optimizations can be done (and when promotions can be ommitted if the implementation can guarantee that the result is the same).

**Comment by acqn** [comment]
So 16-bit `int` is standard-compliant (ie. not a `bug`) but could bring surprises to people who are used to 32-bit `int`. I don't know what can be done here....

**Comment by groessler** [comment]
16bit `int` was also used in MS-DOS compilers and the "original" PDP-11 compiler. So nothing special here...

**Comment by mrdudz** [comment]
Imho this is not a bug - and nothing can be done about it. Using a 16bit compiler always will give surprising results at times if you are used to 32bit compilers only :)

**Comment by mrdudz** [comment]
So we can close this?

**Comment by ProxyPlayerHD** [comment]
seems like it.
