### ISSUE TITLE
Git HEAD hash missing from Win32 snapshot ZIP.

### ISSUE THREAD

**Issue by oliverschmidt** [cc65/cc65#1702]
In former times, the Win32 snapshot ZIP had a comment containing the Git HEAD hash. This was done with:

```
echo $(TRAVIS_COMMIT) | zip -z cc65
```

See https://github.com/cc65/cc65/blob/master/Makefile.travis#L33

I'd appreciate, if this feature could be brought back. Maybe with an approach similar to the one I took with IP65:

```
ZIPCOMMENT := $(shell git rev-parse --short HEAD 2>$(NULLDEV))
ifeq ($(words $(ZIPCOMMENT)),1)
  ZIPCOMMENT := https://github.com/cc65/ip65/commits/$(ZIPCOMMENT)
else
  ZIPCOMMENT := N/A
endif
```

See https://github.com/cc65/ip65/blob/main/Makefile#L9-L14

**Comment by greg-king5** [comment]
Commit b2ae73879bdf4148963b3df80cc200dd95ec2b64 puts it in the snapshot ZIPs.

**Comment by oliverschmidt** [comment]
Thanks :-)
