### ISSUE TITLE
[atari7800] conio

### ISSUE THREAD

**Issue by karrika** [cc65/cc65#1710]
The Atari 7800 has only 4k of RAM so most of times you don't need anything like conio. But it would be useful for testing stuff to have a minimal conio implementation. What I had in mind is a 40x28 character display using the 320A mode of the Atari 7800. The font would be in a separate vga.s file that would allow you to swap it for your own font as in other systems.

The choice of 28 lines comes from the fact that this is the maximum number of lines we can show on a NTSC console is 224. On a PAL we show the same amount and draw a blank border at the bottom of the screen. 

Due to very limited RAM the text colour could only be changed on a line-by-line basis. You can also change the colour for the left and the right half of the line. The background can also have a defined colour but it affects the entire screen.

I would like to implement a basic system first to output text and assign colours. No scrolling or blinking cursor in the first version. Perhaps there is a way to have these functions in separate files to minimize memory footprint if they are not needed in the application.

The goal would be to run Hello World from the samples directory. Perhaps you could even run some character mapped games on it.

Comments?

**Comment by Fabrizio-Caruso** [comment]
That is cool! So, there is no way to assign a single foreground color to each character? 
How are all the existing colorful games possible? Do they rely on sort of sprites as the Lynx? 
Having a replaceable VGA.s is nice. My framework implements an abstraction layer for single per-character tile graphics. So it is perfect for me except maybe the lack of per-character color.

**Comment by karrika** [comment]
There is a way to assign a single foreground color to every character. But that needs a separate zone structure for every character. I would like to have one zone for 20 characters. The downside is less colours.
You won't like the VGA.s as all characters needs to be upside-down and interleaved by 256 bytes. So the block is 256 characters 8x8 bits. Single bit per pixel. There is no way to have an abstraction layer for single per-character tile graphics. You need to compile all your characters into a block and put it in memory aligned to 256 bytes. So one 8x8 sprite for index 0 has its bytes like:
0 - row 7
256 - row 6
512 - row 5
768 - row 4
1024 - row 3
1280 - row 2
1536 - row 1
1792 - row 0

The next character in the font, index 1 would be
1 - row 7
257 - row 6
513 - row 5
769 - row 4
1025 - row 3
1281 - row 2
1537 - row 1
1793 - row 0

and so on up to index 255 in the font. The same is true to all graphics in Atari 7800.

**Comment by Fabrizio-Caruso** [comment]
@karrika I will implement the abstraction layer as long as I understand how it is structured.

I wonder how all the existing colorful games are coded despite the 4k limit. Does the video have to use a buffer in normal RAM?
If that is the case 2k of RAM could be used for colors and characters and 2k would still be left for variables, stack and zero page. Some targets have less RAM memory and are usable. For example the Creativision has very little memory but the video buffer is not in (normal) RAM.

**Comment by Fabrizio-Caruso** [comment]
Maybe having the same color set only on a row level, would not be consistent with other CONIO targets.
Maybe just monochromatic to save memory and a second CONIO implementation with per character color as all other color-enabled CONIO targets. 
I don't know how feasible my proposal is.

**Comment by karrika** [comment]
> @karrika I will implement the abstraction layer as long as I understand how it is structured.
> 
> I wonder how all the existing colorful games are coded despite the 4k limit. Does the video have to use a buffer in normal RAM? If that is the case 2k of RAM could be used for colors and characters and 2k would still be left for variables, stack and zero page. Some targets have less RAM memory and are usable. For example the Creativision has very little memory but the video buffer is not in (normal) RAM.

There is no video buffer in Atari7800. The rendering happens directly to screen. Having a separate frame buffer is something I thought to have for testing mainly.

The way to go is to manually plan for the display lists to create the game. But this idea fits poorly to tgi. You could create block graphics to achieve what you want. But my guess is you end up with a 40 x 28 pixel display to mimick tgi.

**Comment by karrika** [comment]
> Maybe having the same color set only on a row level, would not be consistent with other CONIO targets. Maybe just monochromatic to save memory and a second CONIO implementation with per character color as all other color-enabled CONIO targets. I don't know how feasible my proposal is.

A monochrome white text on black background would be ok with me.

It is fairly easy to override these modules with your own tuned variants at compile time.

**Comment by karrika** [comment]
For creating really colorful graphics I used 16x32 bit tiles. The height is twice the width due to aspect ratio.
Every tile can then  have its own palette. But each tile can only have 3 colours + transparent in this  mode. And you can only have 7 different palettes of 3 colors.
So it is far from a generic solution.
![Wizzy7800](https://user-images.githubusercontent.com/6996727/159675695-1f680831-5e23-47d5-a108-be9542e598ad.png)

**Comment by Fabrizio-Caruso** [comment]
In my case, I will have to figure out how to implement a conio-like with per-character single foreground color and common background color with 8x8 tiles statically defined by VGA.s. I do not mind much about pixel ratio. Plain 160x224 would be perfect. My games look better with this ratio.

**Comment by Fabrizio-Caruso** [comment]
@karrika is memory the reason why you are not considering a full color CONIO implementation?
Would a monochromatic CONIO be easy to extend to full color in C without Assembly and no DLI or worse by chasing the raster (like on a VCS)?
My (maybe crazy) proposal for a memory saving full color CONIO implementation would be to do something like the 64 5-color text mode available on the Atari 8-bit and Atari 5200. Each byte on the buffer stores 6 bits to index 64 tiles and 2 bits to index 4 foreground colors with a common background. This would take about 0.5k for 160x225 or 1k for 320x225 and it would provide easy to use color, which couple with VGA.s, would allow a trivial implementation of tile based graphics for games. The user would just have to provide its own VGA.s and use standard CONIO APIs. Memory usage for the buffer would be as low as about 500 bytes.

**Comment by Fabrizio-Caruso** [comment]
Sorry I don't understand but it is just my lack of knowledge.
I was just proposing a simplistic approach to store the minimum in the buffer in ram.
One byte per character is enough to index 64 tiles and 4 foreground colors (same color for the foreground pixels of one character as mode 1 on the Atari 5200 or A8).
I have no idea how the characters are displayed. I understand there is no framebuffer and so the buffer is a software one. I don't understand where the 4 or 5 bytes per characters come from.

**Comment by karrika** [comment]
Please read the http://7800.8bitdev.org/index.php/7800_Software_Guide
It explains the way the console works.

I also did a mockup of a monochrome screen with some character graphics using the vga font.
![island](https://user-images.githubusercontent.com/6996727/159788027-b44aa5bd-e782-4df7-9e4b-ffe69bf9d8c8.png)

**Comment by karrika** [comment]
Perhaps I could test to see what kind of conio would be possible in 4k that would allow setting colours on every character. It might be an idea to create the font as 4-colour bitmaps to be individually coloured by 7 colours. The font could be 16 by 32 bits that looks like 8x8 pixels. So the screen would by 10 characters per line and 7 lines. Would it be big enough?

**Comment by Fabrizio-Caruso** [comment]
@karrika I understand that the real limit is the RAM left. If possible please leave at least 500-600 bytes life for the hardware stack, zero page and variables. 
I think 7 lines is not much. What do you mean by "looks like 8x8"? I guess you mean 1:1 aspect ratio.

Aren't 4 colors already encoded in the bitmap in 160x2 mode with 2 bits per pixel that can (statically) encode 4 colors. 
If implementing run-time per-tile color with too many tiles is impossible to achieve for something like 400 tiles, wouldn't  a single palette for all tiles be easier and so just have the 4 colors that are encoded by the bitmap (with colors sort of hard-coded in the tiles). I don't know if 160x4 mode can be used.
Many 8-bit systems do not enforce 1:1 aspect ratio in all screen modes. The most commonly used screen modes in games on the Commodore 64, Atari 8-bit, Atari 5200, Amstrad CPC all use 160x200 with rectangular pixels.
So even 8 pixel x 8 pixel  tiles in 160x224 would be OK and they would look like mode 1 on the Atari 8-bit/5200 and provide 20x28 tiles where each tile can have up to 4 colors (selected statically by the data in the tile bitmap).

Sorry for any stupidity I might have written. I am reading the doc you mentioned above but maybe I am not understanding all the details.

**Comment by karrika** [comment]
The stack, C-stack and zp are already taken care of by the way the ram is splitted up by the hw.

It would be possible to use 160 A mode for conio. This means we need two fonts. One with pixel value 1 and another with value 2. So we would have 7 bit characters using the highest bit as colour. The screen might have 20 x 28 characters that are very wide.

**Comment by Fabrizio-Caruso** [comment]
128 characters in 3 colors (+background?) is ok and having a 2:1 pixel ratio is the same as in other computers and consoles of the era. A user could use it to have colorful text or provide his own VGA.s to do create some tiles. More advanced graphics would require a user-defined DLL anyway. 128 tiles is ok. I don't understand why we lose one bit and cannot have 256 but 128 is OK.

**Comment by Fabrizio-Caruso** [comment]
So colors are totally encoded in the bitmap in this case.  More colors could be possible if we use 4 bits per pixels but the problem with 4 bits per pixels is that there won't be enough tiles to cover all color and shape combinations. A developer who needs more colors will have to write their own display list. Probably yours can be used as an example to start with.
CONIO Is a compromise. It is meant for text but with your suggested solution it could be used for simple games with 3 colors + transparency/background.

**Comment by karrika** [comment]
I did some thinking about what would be the most useful conio for a beginner. While the 256 char monochrome would be the best choice for text games it actually eats up most of the RAM.

The 4 colour 160A mode conio use a really minimal amount of RAM leaving most of it for your experiments.

I was thinking about the font also. The index 0 could be blank for all colours and index 127 could be a fixed cursor '_' that can move on top of any character on screen.
The remaining indices (128 - 2) / 3 = 42 characters.
1234567890
ABCDEFGHIJ
KLMNPQRSTU
VWXYZ.....
..

So it leaves 7 characters marked as '.' above. Any desires of which characters to include?
".,?$![heart][8x8 coloured block]"?
Or something else?

**Comment by Fabrizio-Caruso** [comment]
It would be nice to have a way to disable the cursor display?
If possible please implement `cursor` (https://www.cc65.org/doc/funcref-89.html#cursor).

For the remaining 7 tiles, I would choose the most common punctuation marks and/or bars (horizontal, vertical and maybe some shapes to be used for the angles) to do draw some windows:
```
/----------------------------\`
|                                           |`
|                                           |`
`\---------------------------/`
```
Maybe something four line shapes `-`, `|`, `\`, `/` (that could be used to draw bars that can be connected) and 3 punctuation marks `.`, `,`,:`.

For the bar shapes there may be a convention for their names in CONIO as shown in
https://github.com/cc65/cc65/blob/master/include/nes.h

**Comment by karrika** [comment]
What about this font?
![font160](https://user-images.githubusercontent.com/6996727/161333051-7174a203-a11f-45b6-b749-d53a773d67ff.png)

**Comment by Fabrizio-Caruso** [comment]
It is ok for me. The corners may not be fully consistent with what other conio-enabled targets offer but I am not sure if there is any rule on the shapes of these characters in conio. I am not sure but maybe some targets with few available characters use a simple cross symbol. Anyway, this is a detail, you and the maintainers decide.
The resolution does not look what I was expecting. I thought it would be 160x224 (20x28 characters). 
The picture here looks more like 320x224.

**Comment by karrika** [comment]
Ok. The picture was too wide by a factor 2. If you cut it in half you have the correct screen. Let's see what it looks like in real life.

**Comment by karrika** [comment]
I also made a mistake in number of characters. There is only 6 characters outside the letters and numbers. So I ditched the question mark.

Here is the font source as a 2 bit per character image. You need to flip it vertically and output it as raw data. After that turn the bytes to asm by a script.
![font160](https://user-images.githubusercontent.com/6996727/161366875-23feccf6-faea-4105-b1c8-41ba266cb7a4.png)

I add the source font as png for easier editing to your own characters. This source font could be added as a starting point in the repository also.

**Comment by karrika** [comment]
I created a very brief conio target. Actually it only has the screen buffer and the clrscr() function so far. But at least it is a start.

Here is the source code for accessing it:
```
#include <atari7800.h>
#include <conio.h>

extern unsigned char screen[];

void main() {
        unsigned int i, ch;

        clrscr();
        for (i = 0, ch = 0; i < 20 * 28; i++, ch += 2) {
                screen[i] = ch;
        }
        while (1) ;
}
```

To compile it you need to type:
cl65 -t atari7800 -o conio.a78 --force-import __EXEHDR__ -m conio.map main.c -l atari7800

This works on both the NTSC and the PAL target. So there is no need for separate targets.
![testconio](https://user-images.githubusercontent.com/6996727/161370267-a1df5003-959f-4864-9908-84bf7493296c.png)

**Comment by Fabrizio-Caruso** [comment]
Could you release the script you used to edit and convert to the format that the Atari 7800 needs.

**Comment by Fabrizio-Caruso** [comment]
Maybe it would be better to have white as one of the default colors.

**Comment by karrika** [comment]
Sure. Here is a small example with white instead of blue.
![testconio](https://user-images.githubusercontent.com/6996727/161376045-af32e1c9-93f8-4814-af20-94298f9d6b0d.png)

The code for writing text is pretty complicated. Perhaps we need some printc stuff.
```
#include <atari7800.h>
#include <conio.h>

extern unsigned char screen[];

#define RED 0
#define GREEN 42
#define WHITE 84

void main() {
        unsigned int i, ch;

        clrscr();
        for (i = 0, ch = 0; i < 128; i++, ch += 2) {
                screen[i] = ch;
        }
        screen[4 + 10*20] = 2 * (17 + 'H' - 'A' + RED);
        screen[5 + 10*20] = 2 * (17 + 'e' - 'a' + GREEN);
        screen[6 + 10*20] = 2 * (17 + 'l' - 'a' + WHITE);
        screen[7 + 10*20] = 2 * (17 + 'l' - 'a' + RED);
        screen[8 + 10*20] = 2 * (17 + 'o' - 'a' + GREEN);
        screen[9 + 10*20] = 2 * (1 + '!' - '!' + WHITE);
        while (1) ;
}

```

**Comment by karrika** [comment]
> Could you release the script you used to edit and convert to the format that the Atari 7800 needs.

Have a look at the repository. The way I did it was to start with font160.png. Then I choose FlipVertically and end up with font160flipped.png. I export the data as font160.data. It is a raw format where only the bytes are exported. After that I run my python program with:

python3 buildfont160.py

This script reads the file font160.data and exports it as font160.s

**Comment by Fabrizio-Caruso** [comment]
Very minor thing: for text-based games, one could just use your default fonts with no modification. In this use case and other cases where the interface asks for the user's input the question mark may be more commonly needed than the exclamation mark.

**Comment by karrika** [comment]
> Very minor thing: for text-based games, one could just use your default fonts with no modification. In this use case and other cases where the interface asks for the user's input the question mark may be more commonly needed than the exclamation mark.

Good point. I will swap the question mark with the exclamation mark.

**Comment by karrika** [comment]
I was looking at the other targets and it appears that scrolling the screen is not implemented. The newline at the end of the screen just moves the cursor to the top of the screen.

Somehow I don't think it is a good solution. As the screen is so tiny I feel that scrolling is the way to go.

**Comment by mrdudz** [comment]
CONIO does not scroll, and the behaviour when printing across the limits is undefined. STDIO must scroll, of course.

For scrolling there was a discussion somewhere about implementing some kind of API that allows to scroll sections of the screen, but it didnt get much momentum (which doesn't surprise me to be honest, you dont really need scrolling often)

**Comment by karrika** [comment]
I removed the scrolling.

Currently you can use colours like:

red = 0
green = 1
white = 2

textcolor(0)
gotox(unsigned char x)
gotoy(unsigned char y)
cputc('H')

The characters recognized are:
' ' *?,-.|
0123456789
ABCD...Z
abcd...Z
newline '\n'

There may be some other methods that work. But these are the one I have been working with.

The lines swap to next line when writing. The screen swaps from bottom to top.

**Comment by karrika** [comment]
Thank you!

If we can get the [atari7800] stdjoy pull request merged then you could use the joystick for testing the conio-stuff. Otherwise you have to merge these two pull requests by yourself.

**Comment by Fabrizio-Caruso** [comment]
So maybe your gotoxy should just be a macro that invokes gotox and gotoy because it should work with cputc in order to be CONIO compliant.

**Comment by karrika** [comment]
It looks like this:
```
;-----------------------------------------------------------------------------
; Set cursor to desired position (X,Y)
;
        .proc   _gotoxy

        jsr     _gotoy
        jsr     popax
        jsr     _gotox
        rts
        .endproc
```

**Comment by Fabrizio-Caruso** [comment]
Maybe I misunderstood you. Can I use in C gotoxy followed by cputc? Or is gotoxy not meant to be used with cputc?

**Comment by karrika** [comment]
You can use gotoxy(). There may be other routines that also could work that are built onto these primitives. wherex(), wherey(), cursor(on/off). Perhaps something else also...

**Comment by Fabrizio-Caruso** [comment]
By the way, CONIO in CC65 (and other 8-bit dev-kits) differently from some MS-DOS variants use 0 as first index for the cursor. I don't know how you have implemented it.

**Comment by karrika** [comment]
I am a bit puzzled about the word "index" here.

cursor(0) hides the cursor
cursor(1) makes the cursor visible

gotoxy(column, row) moves the cursor to some place on the screen. The range is:
column 0..19
row 0..27
The left top of the screen is (0,0)
The bottom right of the screen is (19,27)

**Comment by Fabrizio-Caruso** [comment]
What you have done is consistent with CC65 for me.
I asked because the range does not always start at 0 on other CONIO implementations (e.g., some but not all MS-DOS versions start at 1).
On CC65, Z88DK and other 8-bit dev-kits the range starts at 0.

**Comment by karrika** [comment]
You can now also use the std 2 button joystick for testing conio. Thanks @mrdudz for merging the stdjoy.

**Comment by karrika** [comment]
This conio is seriously broken. I found out that the cputc() produces different results depending on the build. No clue of why yet...

**Comment by karrika** [comment]
It took a while to find the reason. I was using shared resources that I should not have used at all (mul8).

**Comment by karrika** [comment]
The conio implementation is now ready for review. So please have a look at it.
There is also a blinking cursor now.

**Comment by karrika** [comment]
I assume that we have now everything required for the Atari 7800 implemented.

The last thing is reading the switches. I was thinking about using kbhit() and cputc() but as there is both mechanical switches and push buttons it is better to just access the port directly.

RIOT.swchb has the content:
0x80 = P1 difficulty '1' advanced
0x40 = P0 difficulty '1' advanced
0x08 = Pause '0' pressed
0x02 = Game select '0' pressed
0x01 = Start '0' pressed

So you have to poll this location to see if any bits have changed. Ok?

**Comment by Fabrizio-Caruso** [comment]
@karrika I see that the code has been merged. I can compile my games and produce .xex files but I don't know how to load them into an emulator. From the doc I see in the first PR about this target, CC65 is already inserting a header for the default cartridge configuration. So, in theory, the .xex should run on an emulator. I read the encryption is not required by emulators.

I have tried to load the xex image with the A7800 but it didn't like the format. So I am doing something wrong.
Which emulator should I use?

I have attached the binary I have created
[Xshoot_atari7800_no_color.zip](https://github.com/cc65/cc65/files/8550051/Xshoot_atari7800_no_color.zip)

**Comment by karrika** [comment]
I have no clue of what a .xex is. For the Atari 7800 you need to create .a78 files.

```
cl65 -t atari7800 --force-import __EXEHDR__ game.c -o game.a78
sign7800 -w game.a78
```
You only need to sign the binary if you want it to run on a real NTSC Atari 7800 machine.
The emulators and the PAL machines do not require signed programs.

**Comment by Fabrizio-Caruso** [comment]
I was compiling it with the standard compile (almost same as yours but no  "--force-import __EXEHDR__").
In this case cl65 produces a .xex file (same as for the Atari 8-bit target).
I am going to try with the correct option.

**Comment by Fabrizio-Caruso** [comment]
@karrika it works!

**Comment by karrika** [comment]
> @karrika it works!

Congrats!!!

**Comment by karrika** [comment]
If you need to make a monochrome binary with 40 chars per line add atari7800-mono.o to the cl65 line:

```
cl65 -t atari7800 --force-import __EXEHDR__ atari7800-mono.o game.c -o game.a78
sign7800 -w game.a78
```

**Comment by Fabrizio-Caruso** [comment]
Thanks to you, I am now able to add support to the Atari 7800 in Cross-Lib.
So, 5 new homebrews for the Atari 7800 are now built by Cross-Lib with no need of new code.
For sound I need to work a bit but I only a few short need beeps and burps.
For real graphics I just need to create a script that generates the font file from my hardware agnostic asset files.

**Comment by karrika** [comment]
Have a look at my sfx.s
It is a sound player for TIA sound chips. There is also a sound library with 100+ sounds you can use.
https://bitbucket.org/karri/piratecove/src/main/7800/

**Comment by Fabrizio-Caruso** [comment]
Can I steal a couple of your sound effects and maybe modify them? If I do, I will cite you as the original author of the sound effects.

**Comment by Fabrizio-Caruso** [comment]
@karrika I might have found a bug with color 2 (red). In my games, it is always displayed as color 3 (white).
I will try to write a minimal example to make sure it is not a problem in my code.

**Comment by karrika** [comment]
> Can I steal a couple of your sound effects and maybe modify them? If I do, I will cite you as the original author of the sound effects.

The TIA sound library is from here https://atariage.com/forums/topic/301293-7800-tia-sfx-library-sound2tia/

**Comment by karrika** [comment]
> @karrika I might have found a bug with color 2 (red). In my games, it is always displayed as color 3 (white). I will try to write a minimal example to make sure it is not a problem in my code.

The colour indices start from 0 (red)
https://atariage.com/forums/topic/332834-atari7800-target-is-now-officially-in-cc65/?do=findComment&comment=5047101

**Comment by Fabrizio-Caruso** [comment]
Thanks! This fixed my problem. 
This means that the conio (and TGI) color macro definitions in https://github.com/cc65/cc65/blob/master/include/atari7800.h are wrong, though.

**Comment by karrika** [comment]
The TGI colours are not the same as textcolor() colors. Or should they be?

**Comment by Fabrizio-Caruso** [comment]
Indeed TGI colors (TGI_COLOR_WHITE, ....) can be different from conio colors. 
I do not see a TGI lib for the Atari 7800, so I wonder whether they should be defined.

The conio colors (COLOR_WHITE, COLOR_BLACK, etc...) are wrong IMHO. They should be consistent with the default colors of the target (which are also different colors and so also the names are wrong).
