### ISSUE TITLE
[atari7800] stdjoy

### ISSUE THREAD

**Issue by karrika** [cc65/cc65#1711]
There seems to be 2600 and 7800 joysticks that are commonly used with the Atari 7800 console. The fire buttons are detected in different registers for these joysticks. There is a nice piece of code that can adapt itself to both types of joysticks automatically. It would be a good candidate for a stdjoy driver.
The 7800 joysticks come with 2 buttons while the 2600 joysticks have just one fire button.

Would it be better to create a smaller single joystick driver? Or is it best to go directly with a dual joystick driver? Opinions?

**Comment by polluks** [comment]
How about two drivers? An atari7800-stdjoy and an atari7800-2600joy.

**Comment by karrika** [comment]
> How about two drivers? An atari7800-stdjoy and an atari7800-2600joy.

That would require two separate releases of the binary. I rather have one game that works with the joysticks we support.

**Comment by karrika** [comment]
Currently I want to have to just one standard driver  As we are making a driver for 7800 I assume that a dual 2 button joystick is the logical choice.

**Comment by groessler** [comment]
Can you explain how different the 2-button driver would be compared to the 1-button 2600 driver?

**Comment by mrdudz** [comment]
> You can link both drivers to the same binary. But there would need to be a selection which one.
really? how does that work? is this documented somewhere? :) i always hated how such simple/short drivers must be loaded from disk :)

**Comment by groessler** [comment]
see for example targettest/mouse-test.c which does the same for mouse drivers

**Comment by karrika** [comment]
> Can you explain how different the 2-button driver would be compared to the 1-button 2600 driver?

The direction switches are identical. But the buttons are read from different registers for the one button and the 2 button joysticks. The 2-button version also needs to set two pins on one port to outputs while the one button has them as inputs.

**Comment by karrika** [comment]
I believe the easiest and most practical driver would support 1 button and 2 button joysticks in the same driver.

**Comment by mrdudz** [comment]
If its transparent and automatic, and doesnt involve a lot of overhead, that seems the best solution indeed.

However, as said, it would be good to invent an API that allows the program to determine how many buttons are available :) something like getnumberofbuttons(joysticknumber)

**Comment by groessler** [comment]
> > Can you explain how different the 2-button driver would be compared to the 1-button 2600 driver?
> 
> The direction switches are identical. But the buttons are read from different registers for the one button and the 2 button joysticks. The 2-button version also needs to set two pins on one port to outputs while the one button has them as inputs.

Still, I'm curious: Since the 2-button 7800 controllers work on (1-button expecting) Ataris (and probably C64s), isn't it just that the "other button" is somehow different? So a 1-button driver would work with the 2-button controller and the two buttons are just the same?

**Comment by mrdudz** [comment]
The extra buttons use the POT inputs. on the C64 the two extra buttons just pull the POT line to VCC, so its just an extension, and the regular button still works. On the 7800 afaik the regular "FIRE" line becomes an output and is connected to either POT line via the extra buttons and a resistor, so the regular button will no more work.

**Comment by karrika** [comment]
Good explanation. I wrote a rough idea of what a 7800/2600 joystick driver could look like. The joystick starts as a 7800 joystick. If it detects a 2600 it turns itself into a 2600 driver. In the 2600 mode we report only button JOY_BTN_1 (left). I am not ready for a pull request yet.
[https://github.com/karrika/cc65/blob/atari7800stdjoy/libsrc/atari7800/joy/atari7800-stdjoy.s](url)

**Comment by karrika** [comment]
One question. When I have a 7800 dual button joystick in 2600 mode then both buttons work as FIRE. But when I have it in dual button mode I wonder which button should we have as JOY_BTN_1 left or right?

**Comment by groessler** [comment]
What's the main button on typical 7800 games? I think left (I have two 7800s, but didn't play on them the last 20 years)

**Comment by karrika** [comment]
Thanks! I also got some positive comments from AtariAge. The driver works as it should. I did compile "Robot finds kitten" to use this driver and allow to use 2 joysticks in the game. So no more changes afaik.

**Comment by karrika** [comment]
Thank you!
