### ISSUE TITLE
[Commander X16 r39] conio not pointing to updated text frame buffer? 

### ISSUE THREAD

**Issue by bobbyjim** [cc65/cc65#1712]
Apparently, the text frame buffer for the CX16 "r39" is now $1:B000.

This is probably why conio doesn't output characters or strings anymore.

It might be why cgetc() also doesn't work?

**Comment by ZeroByteOrg** [comment]
This has been corrected, or so it would seem to me - I'm using conio without any issues now...

**Comment by bobbyjim** [comment]
Works!

**Comment by bobbyjim** [comment]
Agreed.
