### ISSUE TITLE
[bug][gamate][conio] On this target conio non-black characters have transparency (not solid background except for black)

### ISSUE THREAD

**Issue by Fabrizio-Caruso** [cc65/cc65#1714]
CONIO on the Gamate is not consistent with other targets.
For instance COLOR_WHITE behaves as transparent. Printing on top of a some black text has no effect.
By the way only two colors are defined (COLOR_BLACK, COLOR_WHITE) with values 0 and 3 but two more "colors" (grey levels) also work as expected (in terms of luminocity) but also suffer from the same problem.

This is reproduced by the following minimal example:
```


#include <conio.h>
#include <unistd.h>

int main(void)
{
    clrscr();
    gotoxy(2,2);
    textcolor(COLOR_BLACK);
    cprintf("hello");
    sleep(1);
    textcolor(COLOR_WHITE);
    gotoxy(2,2);
    cprintf("ciao!");
    
    while(1){};
    return 0;
}
``` 

An ugly and probably inefficient fix that seems to work for me is to delete with a "black space character" before displaying a character in a different color.

**Comment by Fabrizio-Caruso** [comment]
@polluks, @mrdudz  Do you know who has worked on this target?

I am not very fluent in Assembly but the `putchar` code looks fishy:
https://github.com/cc65/cc65/blob/master/libsrc/gamate/cputc.s#L66

It skips updating some bit-planes depending on the text color.
Skipping is not enough if you don't want any transparency (as it is the case with CONIO).
It should clear the bit-planes it currently skips.
So maybe removing the checks on colors and branches to skip, may fix the issue.

**Comment by Fabrizio-Caruso** [comment]
Very minor thing: for text-based games, one could just use your default fonts with no modification. In this use case the question mark may be more commonly needed than the exclamation mark.

**Comment by Fabrizio-Caruso** [comment]
@mrdudz I have just made a tentative pull request that seems to both fix the bug and make all grey levels work.
I am a *very poor* Assembly coder. Could someone please review it?

**Comment by polluks** [comment]
@Fabrizio-Caruso I made a quick review.
Assembler? No problem. For a long time I was struggling with git (keys and so on), now it works somehow.

**Comment by mrdudz** [comment]
btw

> Do you know who has worked on this target?

Just click on the "history" link in the file view - it will tell you that i came up with this code :)

And it does not surprise me at all that this code is "fishy" - when it was made, a friend of mine just reverse engineered the gamate (he wrote the MAME implementation) and there was close to zero documentation about it :)

**Comment by Fabrizio-Caruso** [comment]
The code below shows a problem with the current code, which is fixed with the newest pull-request:
```
#include <conio.h>
#include <unistd.h>
#include <joystick.h>
#include <stdint.h>

void waitForJoy(void) {
    while(!(JOY_BTN_1(joy_read(0)))){};
}

void display_3_rows(uint8_t x_offset, uint8_t y_offset) {
    uint8_t i;
    uint16_t j;
    for(i=0;i<3;++i) {
        gotoxy(x_offset,y_offset+i);
        textcolor(1+i);
        cprintf("hello");
        for(j=0;j<10000;++j){};
        waitForJoy();
    }
}

int main(void) {
    uint8_t i;
    joy_install((void *)joy_static_stddrv);    
    while(1) {
        clrscr();
        for(i=0;i<3;++i) {
        display_3_rows(2+i,2+i);
        waitForJoy();
        }
        for(i=0;i<3;++i) {
        display_3_rows(2+5*i,9+i);
        waitForJoy();
        }
        sleep(1);
    }
    return 0;
}
```
