### ISSUE TITLE
Two bugs in the string output functions

### ISSUE THREAD

**Issue by greg-king5** [cc65/cc65#172]
1. `sprintf()`, `snprintf()`, `vsprintf()`, and `vsnprintf()` might crash if `NULL` (0) is used as the first (buffer pointer) argument.
2. `snprintf()` and `vsnprintf()` always return zero when the second (buffer-length) argument is zero.  They should return the same value that they do return when the buffer length isn't zero (i.e., the length of the string that the format produces).

P.S. Assign me to this one.

**Comment by oliverschmidt** [comment]
@greg-king5 Thanks for the fix :-)
