### ISSUE TITLE
Can't use Unity unit testing framework with cl65

### ISSUE THREAD

**Issue by elderling** [cc65/cc65#1723]
I'm attempting to use [Unity Test](https://github.com/ThrowTheSwitch/Unity) unit testing framework with cc65 and am getting unexpected results. Unity expects that some target platforms may not support floats so it has the following settings:

    #define UNITY_EXCLUDE_MATH_H
    #define UNITY_EXCLUDE_FLOAT
    #define UNITY_EXCLUDE_FLOAT_PRINT
    #include "Unity/src/unity.h"

    void setUp(void)
    {
        return;
    }
    
    void tearDown(void)
    {
        return;
    }
    
    void test_ok(void);
    
    void test_ok(void)
    {
        TEST_ASSERT_EQUAL_STRING("ok", "ok");
    
        return;
    }
    
    int main(void)
    {
        UNITY_BEGIN();
    
        RUN_TEST(test_ok);
    
        return UNITY_END();
    }

but when I try to compile I get:

    cl65 less_test.c Unity/src/unity.c
    Unity/src/unity_internals.h(19): Error: Include file 'math.h' not found
    Unity/src/unity.c(337): Fatal: Floating point type is currently unsupported

When I look at the `unity.c` source I see that the code cl65 is complaining about is surrounded with ( see [exact source](https://github.com/ThrowTheSwitch/Unity/blob/b9e9268d92e5339e8cdd251c880429ce30ff7a11/src/unity.c#L328) for details):

    #ifndef UNITY_EXCLUDE_FLOAT_PRINT
    // other nested if macro statements and C source
    #endif /* ! UNITY_EXCLUDE_FLOAT_PRINT */

cl65 appears to be ignoring or not recognizing the `#ifndef` directive completely and then complaining that it doesn't support what the macro directive(s) are intentionally excluding.

**Comment by jmr** [comment]
The error is compiling `unity.c`, so `#define`s in `less_test.c` don't do anything.

Try `cl65 -DUNITY_EXCLUDE_MATH_H -DUNITY_EXCLUDE_FLOAT -DUNITY_EXCLUDE_FLOAT_PRINT less_test.c Unity/src/unity.c`.
