### ISSUE TITLE
Comodo rejects co65.exe

### ISSUE THREAD

**Issue by Robbie3** [cc65/cc65#1746]
Since a while cc65-snapshot-win32.zip\bin\co65.exe is reported by Comodo as MalCrypt.Indus!@105441913
Situation exists in file downloaded from https://sourceforge.net/projects/cc65 on date 2022-05-17 GMT 17:50 (Project Activity: update "3 hours ago")
Could be a false positive of course but why then is it reported?

**Comment by mrdudz** [comment]
No idea, you should ask Comodo (whatever that is)

**Comment by mrdudz** [comment]
I am closing this, its a false positive. If in doubt, use virustotal.com to see what other scanners are reporting.

**Comment by polluks** [comment]
@Robbie3 https://forums.comodo.com/av-false-positivenegative-detection-reporting-b154.0/
