### ISSUE TITLE
Wrong encoding of CR and LF in conio for the osic1p target

### ISSUE THREAD

**Issue by smuehlst** [cc65/cc65#1747]
According to ASCII code 0x0A is LF and code 0x0D is CR.

As an example the c64 conio implementation handles CR and LF like this:

https://github.com/cc65/cc65/blob/93ee91fb4b339337fae6ea99e025858a48acc988/libsrc/c64/cputc.s#L23-L30

Compare that for example to the implementation for nes:

https://github.com/cc65/cc65/blob/93ee91fb4b339337fae6ea99e025858a48acc988/libsrc/nes/cputc.s#L31-L38

It looks like the c64 conio library implements an incorrect encoding of CR and LF.

The following targets have this problem: c128, c16, c64, cbm510, cbm610, osic1p, pet, plus4, vic20

**Comment by greg-king5** [comment]
CBMs are different from other machines.
`'\n'` means new-line.  Other machines use `0x0A` as new-line.  But, CBMs use `0x0D` as new-line.

cc65 handles that by swapping the encodings of `\n` and `\r`.  Conio swaps the characters in order to match the compiler.

**Comment by mrdudz** [comment]
> '\n' means new-line. Other machines use 0x0A as new-line. But, CBMs use 0x0D as new-line.

to make that more clear: in petscii 0x0d is CRLF, there are no seperate codes for jusr CR or just LF

**Comment by smuehlst** [comment]
So do I understand it correctly that for CBM targets the literal `\n` compiles to `0x0D` and `\r` compiles to `0x0A`? Where is that defined in the compiler?

**Comment by mrdudz** [comment]
All string- and character literals are translated to the target character set, yes. Don't recall where in the compiler it happens exactly. @greg-king5 do you?

**Comment by polluks** [comment]
https://github.com/cc65/cc65/blob/93ee91fb4b339337fae6ea99e025858a48acc988/src/common/target.c#L114

**Comment by smuehlst** [comment]
Ok, I see. Then this issue is reduced to a problem in the osic1p target. The osic1p target uses the ASCII encoding of CR and LF, but when I implemented the osic1p version of conio I used the implementation of the cbm target as a blueprint. I copied the cbm implementation without realizing the different mappings.

I guess there was never a negative impact because as long as "\r\n" is used with conio's `cprintf()` it doesn't matter if the meaning of CR and LF is switched...

**Comment by smuehlst** [comment]
This is a test program that demonstrates the bug with the switched semantics of '\n' and '\r' in the osic1p target:

```
/*
 * Test program for https://github.com/cc65/cc65/issues/1747.
 * 
 * It shows that the meaning of '\n' and '\r' is switched.
 * 
 * The text "was \\n" overwrites the start of the current line,
 * while the text should appear in the next line.
 * 
 * The text "was \\r" appears in the next line, while it
 * should overwrite the start of the current line.
 */

#include <conio.h>

int main(void)
{
    clrscr();

    gotoxy(0, 1);

    cputs("next char is \\n");

    while (!kbhit());
    cgetc();

    cputc('\n');
    cputs("was \\n");

    while (!kbhit());
    cgetc();

    gotoxy(0, 5);
    cputs("next char is \\r");

    while (!kbhit());
    cgetc();

    cputc('\r');
    cputs("was \\r");

    while (!kbhit());

    return 0;
}
```
