### ISSUE TITLE
Bug in decimal (base 10) number evaluation

### ISSUE THREAD

**Issue by Movax12** [cc65/cc65#175]
ca65 allows 'a' or 'A' to be included after a leading decimal digit. It is evaluated as if it was the digit 10.

example:
```
; foo == 20 (decimal)
foo = 1a
```
This line needs to be changed: 
https://github.com/cc65/cc65/blob/master/src/ca65/scanner.c#L1014
to:

```C
    if (DVal >= Base) {
                Error ("Invalid digits in number");
                CurTok.IVal = 0;
                break;
     }
```

**Comment by Movax12** [comment]
https://github.com/cc65/cc65/pull/181

**Comment by oliverschmidt** [comment]
@Movax12 Thanks for the fix :-)
