### ISSUE TITLE
[ca65] warning for unused labels

### ISSUE THREAD

**Issue by jeffythedragonslayer** [cc65/cc65#1751]
Can there be an optional warning for unused labels?

**Comment by kugelfuhr** [comment]
"-W n" with n >= 2 will output a warning for unused symbols:

```bash
$ cat test.s
foo:
$ ca65 -W 2 test.s
test.s(1): Warning: Symbol 'foo' is defined but never used
```

**Comment by jeffythedragonslayer** [comment]
Oh cool thanks.  Is there an exhaustive list of warnings anywhere?
