### ISSUE TITLE
What happened to "cl65 --print-target-path"?

### ISSUE THREAD

**Issue by audetto** [cc65/cc65#1754]
I used to follow the pattern

`java -jar $(AC) -p  $@ program.system sys < $(shell cl65 --print-target-path)/apple2enh/util/loader.system`

in Apple][ makefiles.

Now I get

`/share/cc65/target` rather than an absolute path.

Bisection lands here: https://github.com/cc65/cc65/commit/8669710c0f9909f8b3b825e3d0693b98563979fd

This seems to be broken too:

https://github.com/oliverschmidt/A2Stream/blob/main/Makefile

How is it supposed to work now?

**Comment by rofl0r** [comment]
> /share/cc65/target

this looks like an absolute path to me. what did you get before that ?

**Comment by audetto** [comment]
I mean, before it was

`/path/to/cc65/share/cc65/target`

now `/path/to/cc65` has desappeared.

**Comment by rofl0r** [comment]
did you set `PREFIX=` (empty) when building ?

**Comment by audetto** [comment]
I have always only run `make` on the checkout, and added cc65's `bin` folder to the path.

I guess that this is unsupported now and I need to properly install it?
With `PREFIX=` it works.

**Comment by rofl0r** [comment]
> EDIT 2: Works now. One must pass PREFIX both to make and make install

and what PREFIX did you set ?

> and it better be the same

the whole point of it...

> Should make refuse to run without?

that's what it did prior to that commit, it disallowed setting an empty prefix, even though it's technically valid.

otoh, i still dont understand your usecase. you usually just run make, and then execute from builddir, or how did you install it ?

**Comment by audetto** [comment]
My is not really a use case, it was just the way i used to build it. Just make with no prefix whatsoever and it used to work from the build dir, no install needed.

From now on, I will install properly.

**Comment by Compyx** [comment]
Out of curiosity I checked my install of cc65, and indeed: I have `/share/cc65` as well. I'd expect `make` to either fail when `PREFIX` isn't set, or default to `/usr/local/`. Using `/` as the prefix for an install is certainly not something I'd want, if I wanted that I'd use `PREFIX=/` :)

**Comment by rofl0r** [comment]
> Using / as the prefix for an install is certainly not something I'd want, if I wanted that I'd use PREFIX=/

some distros don't use a prefix, which means /bin is /bin and there's no /usr involved. using PREFIX=/ as a hack would result in //bin when you concat $PREFIX and /bin

> I'd expect make to either fail when PREFIX isn't set, or default to /usr/local/.

indeed /usr/local is the default PREFIX on 99% of build systems. but PREFIX= doesn't mean "not set" it means "set to empty"

**Comment by Compyx** [comment]
Well, in my case I don't have PREFIX as an environment variable at all, so perhaps `make` should fail if `PREFIX` doesn't exist in the environment.

**Comment by spiro-trikaliotis** [comment]
According to https://www.gnu.org/prep/standards/html_node/Directory-Variables.html, https://askubuntu.com/questions/891835/what-does-prefix-do-exactly-when-used-in-configure, and many, many other sources in the net, the default for prefix should be /usr/local.

**Comment by rofl0r** [comment]
@Compyx `make PREFIX=whatever`

**Comment by rofl0r** [comment]
instead of arguing over the PREFIX, i looked at the code and found the actual problem, which was that cl65 adds a number of paths to look for target, but then just returns the first entry in the list rather than actually checking whether the path exists. with that change, the "don't install, run from builddir" usecase should work again.
