### ISSUE TITLE
[ca65] warning when reserving before .segment

### ISSUE THREAD

**Issue by jeffythedragonslayer** [cc65/cc65#1763]
Can there be a warning when `.res` is used before a segment is defined (and thus CODE is the default segment?)  I think this is more likely to be a newbie mistake than intentional.

If someone is trying to reserve blank space then I propose `.resempty` which wouldn't need this warning suppressed (and is hard to type by accident if you are trying to create a variable).

**Comment by polluks2** [comment]
Well, if you don't know how to type a directive you should avoid assembler, it's not a language for newbies IMHO.

**Comment by bbbradsmith** [comment]
Reserving space in CODE is valid. It should not be a warning.

**Comment by jeffythedragonslayer** [comment]
@polluks2 the proposed warning is not about not knowing how to type directives, it's about accidentally reserving space in the default CODE segment.  A newbie may know how to type `.segment` directives without knowing the details of what happens if you don't have any in your asm source, and may be editing a project in location that doesn't have a `.segment` declared before it.

@bbbradsmith it sounds like there are more uses for this than I originally though.  Could you share some of them?

**Comment by bbbradsmith** [comment]
On many platforms CODE is R/W, not ROM. It's perfectly normal to reserve uninitialized space there. However, it's also perfectly valid to use .res to pad empty space in RO segments as well. Lots of people do this.

Even if you wanted to distinguish these cases the assembler doesn't know whether a segment is RW or RO.

It's always an error to type code or date or anything into the wrong segment. There is nothing special about "CODE" in this respect. It is simply the default segment, and plenty of existing and very valid code relies on it being the default segment.

So: I don't think there is a valid warning to apply here.

**Comment by mrdudz** [comment]
closing, this is really too much of a valid thing to do to justify a warning
