### ISSUE TITLE
Missing diagnostics: "invalid constant"

### ISSUE THREAD

**Issue by pmor13** [cc65/cc65#1765]
Consider this code:
```
int x = 0xe+1;
```
Expected diagnostics:
```
invalid constant
```
Actual diagnostics:
```
<nothing>
```

**Comment by groessler** [comment]
What's wrong with that?

It's perfectly OK. 0xe + 1 = 0xf = 15.

**Comment by pmor13** [comment]
Conversion of preprocessing token `0xe+1` into a token (translation phase 7) results in invalid token (invalid constant).

**Comment by groessler** [comment]
Show the text of the standard, please. I don't see anything wrong.

**Comment by groessler** [comment]
Ok Sorry. You're right.
This should give an error.

**Comment by greg-king5** [comment]
Why should it give an error?  What's wrong with it?

**Comment by greg-king5** [comment]
If you change the `'e'` to any other hexadecimal letter, then you won't see a diagnostic.

Some compilers are broken, cc65 is correct.

**Comment by Compyx** [comment]
If you follow the standard then it's actually cc65 which is broken, see 6.4.8 in the C99 standard about pp-numbers. I do agree however that it's a silly corner case that results in an unexpected diagnostic (in clang, gcc at least).

**Comment by pmor13** [comment]
C11, 5.1.1.2 Translation phases, 7:
> Each preprocessing token is converted into a token.

C11, 6.4 Lexical elements, Syntax, 1:
```
preprocessing-token:
    header-name
    identifier
    pp-number
    character-constant
    string-literal
    punctuator
    each non-white-space character that cannot be one of the above
```

C11, 6.4.8 Preprocessing numbers, Syntax, 1:
```
pp-number:
    digit
    . digit
    pp-number digit
    pp-number identifier-nondigit
    pp-number e sign
    pp-number E sign
    pp-number p sign
    pp-number P sign
    pp-number .
```

The `0xe+1` is pp-number, which is an instance of preprocessing-token. Hence, preprocessing token `0xe+1` is required to be converted into a token `0xe+1`, which is invalid token (invalid constant). A conforming implementation shall produce at least one diagnostic message.

**Comment by spiro-trikaliotis** [comment]
This is not a pp-constant (we are not in the preprocessing state!), but an integer-constant (6.4.4.1) which consists of a hexadecimal-prefix ('0x') and one hexadecimal-digit ('e'), and after this integer-constant, there is the "+" and the new constant "1".

**Comment by Compyx** [comment]
It's the preprocessing stage, an integer constant is created from preprocessor tokens. The preprocessor just sees what appears to be a pp-number, it doesn't have to do any conversion into a valid value and it should be able to concatenate tokens with ##.

**Comment by spiro-trikaliotis** [comment]
I should not have answered in the first place, because my memory was not complete. ;)

You are right, we are in the pp-number part, but I think the definition of pp-number is ambigious. (I only have n1548 here, btw, which is a draft of C11).

I also read https://stackoverflow.com/questions/49543516/why-doesnt-0xe1-compile, for example.

However, why do I think it is ambiguous?

The "e" can be either the "e" in the rule "pp-number 'e' sign", OR it can be a non-digit in "pp-number identifier-nondigit". (identifier-nondigit -> nondigit -> 'e'. In the latter case, the '+' is not part of the pp-number anymore.

In the standard, I do not see how this ambiguity has to be resolved. Thus, from my point of view, both interpretations should be acceptable (which is not good).

**Comment by Compyx** [comment]
I suspect the standards committee never expected this weird corner case to happen. :)

I'm using n1256, the final draft of C99, I'll see if I can find any more modern drafts, but seeing how gcc and clang both issue a diagnostic for this even in their default, quite liberal, mode I don't think any newer standard has much to say about this ambiguity.

I wonder if there's any language about the "greedyness" of the parser, specifically of the preprocessor, that might provide a hint?

**Comment by pmor13** [comment]
Rationale for C (emphasis added):
> For example, `0x123E+1` is a **single token under the rules**.

**Comment by polluks2** [comment]
Any conclusion? Maybe we should still ignore it in --standard cc65 for compatibility :-)

**Comment by pmor13** [comment]
@spiro-trikaliotis FYI: Now cc65 accepts invalid code w/o diagnostics. This is not conforming. It may lead to multiple consequences.

**Comment by mrdudz** [comment]
While i am generally totally pro following the standard... i am not convinced its super important to fix this particular issue - because what exactly is the problem that could arise from it. Ie the only difference would be emitting a warning or not, the code will still be the same and work fine as it does now.

That is something to fix for someone who is really really bored :)

**Comment by acqn** [comment]
Well, I just fixed this by the way when I was working on a preprocessor fix.
Before fix:
```c
int a1 = 0xE+1;     /* WRONG: no error? */
int a2 = 0xP-1;     /* BAD: endless errors */
int a3 = 0xP1;      /* Error: ';' expected */
int b1 = 0x;        /* WRONG: no error? */
int b2 = 0b;        /* WRONG: no error? */
int c1 = 08;        /* Error: Numeric constant contains digits beyond the radix */
int c2 = 0b12;      /* BAD: endless errors */
int d1 = 0xEP-1.1;  /* BAD: endless errors */
int d2 = 0xEP;      /* Error: ';' expected */
int d3 = 0007f;     /* Error: ';' expected */
int d4 = 7f.;       /* Error: Invalid suffix "f." on integer constant */
int d5 = 0008.;     /* OK */
```
After fix:
```c
int a1 = 0xE+1;     /* Error: Invalid suffix "+1" on integer constant */
int a2 = 0xP-1;     /* Error: Invalid suffix "xP-1" on integer constant */
int a3 = 0xP1;      /* Error: Invalid suffix "xP1" on integer constant */
int b1 = 0x;        /* Error: Invalid suffix "x" on integer constant */
int b2 = 0b;        /* Error: Invalid suffix "b" on integer constant */
int c1 = 08;        /* Error: Invalid digit "8" beyond radix 8 constant */
int c2 = 0b12;      /* Error: Invalid digit "2" beyond radix 2 constant */
int d1 = 0xEP-1.1;  /* Error: Invalid suffix ".1" on floating constant */
int d2 = 0xEP;      /* Error: Floating constant exponent has no digits */
int d3 = 0007f;     /* Error: Invalid suffix "f" on integer constant */
int d4 = 7f.;       /* Error: Invalid suffix "f." on integer constant */
int d5 = 0008.;     /* OK */
```
