### ISSUE TITLE
[Feature Request] gensym

### ISSUE THREAD

**Issue by jeffythedragonslayer** [cc65/cc65#1773]
Common Lisp has a function called gensym that creates a unique symbol that can be used inside macros, so the generated symbol doesn't clash with other uses of that same macro.  I don't know of any easy way to do this in ca65.  This reduces the need to make up lots of arbitrary names.

http://clhs.lisp.se/Body/f_gensym.htm

**Comment by greg-king5** [comment]
We use [`.local`](https://cc65.github.io/doc/ca65.html#.LOCAL).
