### ISSUE TITLE
[ca65] nop with immediate operand

### ISSUE THREAD

**Issue by jeffythedragonslayer** [cc65/cc65#1775]
Can `nop` be made to be able to take an immediate operand to mean "this many nops" like in asar?

**Comment by groessler** [comment]
```
.repeat 6
  nop
.endrepeat
```

**Comment by jeffythedragonslayer** [comment]
I guess I can turn that into a macro

**Comment by mrdudz** [comment]
as for the original question - no, certainly not. since "nop #imm" is actually a valid (yet undocumented) instruction.

**Comment by jeffythedragonslayer** [comment]
How is "nop #imm" valid already? On V2.19 - Git dcdf7ad, the line:

`nop #ff`

produces an "Error: Illegal addressing mode" for me

**Comment by Compyx** [comment]
Use `--cpu 6502x` to enable undocumented opcodes. Here's a list of undocumented NOPs: https://www.masswerk.at/6502/6502_instruction_set.html#NOPs

**Comment by Compyx** [comment]
With "undocumented" I mean not documented in the original official datasheets, also called "illegal" opcodes. Of course they're documented now.

**Comment by mrdudz** [comment]
Yes, its an undocumented opcode - NOP actually exists in most address modes.
