### ISSUE TITLE
[ca65] warning about missing .endproc

### ISSUE THREAD

**Issue by jeffythedragonslayer** [cc65/cc65#1780]
This is related to #1779.
Can there be a warning when you forget to end a .proc block with .endproc?
If nested procedures are supported, then can this be an opt-in warning?
I hardly ever use nested procedures.

**Comment by bbbradsmith** [comment]
This ends up being entangled with #1779 because a proc is just a scope + label combo internally. #1998 assumes that if there is a label it was a proc, so the error will say so.

**Comment by mrdudz** [comment]
fixed via #1998
