### ISSUE TITLE
Microsoft Defender Antivirus found threats in cc65-master.zip

### ISSUE THREAD

**Issue by pmor13** [cc65/cc65#1795]
![image](https://user-images.githubusercontent.com/4587883/179215545-ccab2c39-ca5f-4bb6-8cbb-2bf962d26e6e.png)

**Comment by mrdudz** [comment]
https://www.virustotal.com/gui/file/1d1b1a6548a5e8e02727b8afb5feb8808bad900b10f8b8e23035ce0f7448233a/detection

and

https://answers.microsoft.com/en-us/protect/forum/all/defender-shows-that-our-software-contains/10572dee-514e-4716-90cb-cdc54e1c03c3

Looks like another false positive to me which we can do nothing about

**Comment by polluks2** [comment]
No doubt, the virus is written in 6502 🙈
