### ISSUE TITLE
C preprocessor questions about included files

### ISSUE THREAD

**Issue by acqn** [cc65/cc65#1804]
I failed to figure out whether standard C allows this:
```c
/* Main source file */

/* Q1: Is this OK? */
#include "h1.h"
/* to pair with the #if in "h1.h" */
#endif

/* Q2: Is this OK? */
#include "h2.h"
/* to pair with the left parenthesis in "h1.h" */
)
```
```c
/* File "h1.h" */
#if 1
/* no terminating #endif */
```
```c
/* File "h2.h" */
#define F()
F(
/* no terminating right parenthesis */
```
While GCC/Clang/MSVC all reject the code above, I can't find any standard text forbidding this. Did I miss anything?

**Comment by polluks** [comment]
I suppose the built-in preprocessors are always restricted... a 80/20 solution.

**Comment by pmor13** [comment]
https://stackoverflow.com/a/32848097/1778275:
> This precludes having a `#if` in one file and the corresponding `#endif` in another.

**Comment by pmor13** [comment]
https://stackoverflow.com/a/70136710/1778275:
> 6.10.3/4 ... There shall exist a ) preprocessing token that terminates the invocation.

**Comment by pmor13** [comment]
Overall: this program contains:
- one syntax violation (6.10 Preprocessing directives, Syntaex, 1), and
- one constraint violation (6.10.3 Macro replacement, Constraints, 4)

A conforming implementation is required to produce at least one diagnostic message.
