### ISSUE TITLE
Wrong definition of errno

### ISSUE THREAD

**Issue by pmor13** [cc65/cc65#1811]
Compiling this program:
```
#include <errno.h>	
int f(void)
{
    struct { int x; } _errno;
    return errno;
}
```
leads to:
```
<source>:5: Error: Converting to 'int' from 'struct $anon-struct-0001'
```
while it does not violate any syntax rule or constraint.

**Comment by mrdudz** [comment]
looks like another case where prepending underscores to identifiiers is needed... also some ifdefs around non standard things (in errno.h)

**Comment by mrdudz** [comment]
started fixing this and other similar problems in #1844 - please have a look and help finding other related problems
