### ISSUE TITLE
[cc65] Extension: predefined macro __COUNTER__

### ISSUE THREAD

**Issue by acqn** [cc65/cc65#1812]
`__COUNTER__` is a commonly supported predefined macro in many major C compilers (eg. [GCC](https://gcc.gnu.org/onlinedocs/cpp/Common-Predefined-Macros.html)), which has well-established and understood behavior (except when involved with precompiled headers, maybe) and been used in practice.

For those who might be unfamiliar with it: `__COUNTER__` is a "magical" macro that evaluates to an integer literal whose value is starting from 0 and increased by one every time it is found in a source code text. It is a convenient way to provide a unqinue identifier in conjunctions with the `##` operator.

Is this feature desired for cc65?

**Comment by mrdudz** [comment]
we HAVE __LINE__, no?

**Comment by acqn** [comment]
> we HAVE **LINE**, no?

Actually, I come up with this topic when I was working on a fix for #1573.

**Comment by mrdudz** [comment]
feel free to implement this :) and please add a test - this sounds like something that could be easily screwed up in a non trivial situation.
