### ISSUE TITLE
[cc65] Redefined macros cannot be all undefined with a single #undef?

### ISSUE THREAD

**Issue by acqn** [cc65/cc65#1822]
```c
#define F 1
#define F 1
#define F 1

#undef F
#if defined F
#error #undef F fails!
#endif

#define F 0

#include <stdio.h>

int main(void)
{
    printf("%d\n", F);
    return F;
}
```
currently fails.

The cause is that every macro definition entry even with the same name is added to the macro table whilst only one of them can be removed with a single `#undef`.

A fix is done. Should it come in #1817 or a separate PR?

**Comment by mrdudz** [comment]
seperate PR, including that test program, would be awesome :)
