### ISSUE TITLE
POSIX defines NULL as ((void *)0)

### ISSUE THREAD

**Issue by alejandro-colomar** [cc65/cc65#1823]
https://github.com/cc65/cc65/blob/4de40a20cb641a80de9b03222a0c686443178d43/include/stddef.h#L57

Hi,

POSIX defines `NULL` as `((void *)0)` (it doesn't require the outer parentheses, but they're safer, and most implementations, including glibc, use them), which is safer than `0` because it is a pointer type and makes it easier to detect issues in code:

```
int i = NULL;
```

Would you mind redefining NULL to be of type `void *`?

<https://pubs.opengroup.org/onlinepubs/9699919799/basedefs/stddef.h.html>

**Comment by rofl0r** [comment]
see also: http://ewontfix.com/11/

tl;dr - posix and C are at odds here.

**Comment by alejandro-colomar** [comment]
That article recommends not using `NULL` by programmers for a reason: ISO C defines it in an unsafe way.

All of what that article says seems to be fixed by POSIX's definition, which requires that NULL is of a pointer type (`void *`).

Then, the article continues by saying that in C++, due to the rules around `void *`, that's not possible.  That a non-issue in C; we didn't make `void *` an unusable type.  That's why most C libraries have a different definition of NULL for C and C++.

BTW, musl libc changed the definition of NULL after that article was written, and they now use `void *` again for C.

**Comment by alejandro-colomar** [comment]
Recommending your users to not use NULL at all is not incompatible with defining it in a better way.  I don't think that defining NULL in one of the worst ways that it can be defined, just because it's allowed by ISO C, and force users to not use it at all because it's broken is a good thing to do.

In fact, it's what is motivating ISO C to develop yet another null pointer constant `nullptr`, which doesn't add anything good.

**Comment by mrdudz** [comment]
Not sure how the current way is a problem though - could you show a simple test case where it is?

**Comment by alejandro-colomar** [comment]
The article here shows one example: <http://ewontfix.com/11/>  It requires you to cast `NULL` when passing it to a vararg (...) function.  POSIX `NULL` doesn't need to be casted, since the alignment and bit representation of `void *` and `char *` are the same.

Another simpler one is that the compiler can't detect broken code such as:

```
int i = NULL;
```

Of course the above is so broken that no humans in their right mind would write it, but another more reallistic case would be passing NULL to a function accepting an integer.  It's not that the code is not going to work --it will work--, but the compiler should probably warn about it.

**Comment by mrdudz** [comment]
I see. Please make a PR :)

**Comment by alejandro-colomar** [comment]
Do you support C++?  I.e., should I write a conditional on `__cplusplus` to have a different definition?

**Comment by mrdudz** [comment]
Nah - by the time "we" support C++ none of us will write 6502 anymore =)

**Comment by mrdudz** [comment]
closed via #1826
