### ISSUE TITLE
Unable to link binary

### ISSUE THREAD

**Issue by felipebalbi** [cc65/cc65#1839]
Hi,

I'm trying to setup a dev environment with CA65 + LD65 for C64 assembly only programming. Following the documentation it's stated that I should assemble with `-t c64` and link with `-C c64-asm.cfg`, however, when I try to do that I get the following error:

```
$ ca65 -t c64 hello.s
$ ld65 -C c64-asm.cfg hello.o
ld65: Warning: /usr/share/cc65/cfg/c64-asm.cfg(21): Segment 'LOADADDR' does not exist
Unresolved external '__LOADADDR__' referenced in:
  /usr/share/cc65/cfg/c64-asm.cfg(5)
ld65: Error: 1 unresolved external(s) found - cannot create output file
```

How can I sort this out? For reference, using `cl65` directly works just fine:

```
$ cl65 -t c64 -C c64-asm.cfg hello.s
$ echo $?
0
```

Versions:

```
$ cl65 --version
cl65 V2.19 - Git 86053939534f
$ ca65 --version
ca65 V2.19 - Git 86053939534f
$ ld65 --version
ld65 V2.19 - Git 86053939534f
```

**Comment by mrdudz** [comment]
When linking manually with ld65, you must also link against c64.lib (which contains the load address segment)

**Comment by felipebalbi** [comment]
That worked fine :-) Thank you
