### ISSUE TITLE
CA65, LD65: issues working together in a simple enviroment

### ISSUE THREAD

**Issue by willie68** [cc65/cc65#1841]
Let me just start with the enviroment. I'm building a simple 6502 SBC. (https://github.com/willie68/w6502sbc)
The memory map is very easy. $0000-$7FFF ist RAM ,$C000-$DFFF ext. ROM, $E000-$FFFF is the bios ROM (thats what i have to develop), $B000-$BFFF IO Space
I want to write the complete bios for this sbc. My Flash is starting at $E000. At the end of the ROM should be a jump table for different Bios routines, which later can be used from the ext ROM. At the very end of the ROM there are the CPU Vectors, too.
So, the bios looks something like this:

==== bios.asm ==== (had to do this, because the markdown code blocks dosent work on this.)
.PC02
.org $E000
.include "io2.asm" 

;----- constant definitions -----
;constants for board specifig
JIFFY_VIA_TIMER_LOAD = 20000   ; this is the value for 1MHZ / 50 ticks per second
; constants for LCD
LCD_E  = %10000000
LCD_RW = %01000000
LCD_RS = %00100000
...
;----- macros -----
.macro msg_out msg
...
;----- bios code -----
do_reset: ; bios reset routine 
	sei
        ldx #$ff ; set the stack pointer 
   	txs 

	;jsr do_ioinit
	jsr do_scinit
	jsr lcd_clear
	msg_out message_w6502sbc
...
	cli
main_loop:
	jmp main_loop
...
;----- jump table for bios routines -----
jump_table: 
.segment "JUMPTABLE"

	.org $FF00 ; STROUT output string, A = high, X = low
	jmp do_strout

	.org $FF81 ; SCINIT Initialize "Screen output", (here only the serial monitor)
	jmp do_scinit
	
	.org $FF84 ; IOINIT Initialize VIA & IRQ
	jmp do_ioinit

	.org $FF87 ; RAMTAS RAM test and search memory end
	jmp do_ramtas

	.org $FF8A ; RESTOR restore default kernel vectors
	jmp do_restor 

	.org $FFD2 ; CHROUT Output an character
	jmp do_chrout
...
;----- cpu vectors -----
.segment "VECTORS"
	.org  $FFFA
	.word   do_nmi
	.word   do_reset
	.word   do_irq

As you can easily see, the individual jumps are not continuously connected. 
My config looks like this:

==== w6502sbc.cfg ====
MEMORY 
{ 
    ZP: start=$0, size=$100, type=rw, define=yes; 
    RAM: start=$200, size=$7fff, type=rw, define=yes; 
    ROM: start=$e000, size=$2000, type=rw, fill=yes, fillval=$ea, file=%O; 
} 
 
SEGMENTS 
{ 
    ZEROPAGE: load=ZP, type=zp; 
    CODE:     load=ROM, type=ro;
	VECTORS:  load=ROM, start= $fffa, type= overwrite;
	JUMPTABLE:  load=ROM, start= $ff00, type= overwrite;
}

However, everything is correct in the asm generated list file. 

==== bios.lst ====
00E20E  1               jump_table:
00E20E  1               .segment "JUMPTABLE"
00E20E  1               
00E20E  1               	.org $FF00 ; STROUT output string, A = high, X = low
00FF00  1  4C 6E E1     	jmp do_strout
00FF03  1               
00FF03  1               	.org $FF81 ; SCINIT Initialize "Screen output", (here only the serial monitor)
00FF81  1  4C F0 E0     	jmp do_scinit
00FF84  1               
00FF84  1               	.org $FF84 ; IOINIT Initialize VIA & IRQ
00FF84  1  4C 36 E0     	jmp do_ioinit
00FF87  1               
00FF87  1               	.org $FF87 ; RAMTAS RAM test and search memory end
00FF87  1  4C 50 E0     	jmp do_ramtas
00FF8A  1               
00FF8A  1               	.org $FF8A ; RESTOR restore default kernel vectors
00FF8A  1  4C 80 E0     	jmp do_restor
00FF8D  1               
00FF8D  1               	.org $FFD2 ; CHROUT Output an character
00FFD2  1  4C 82 E1     	jmp do_chrout
...
00FFF6  1               ;----- cpu vectors -----
00FFF6  1               .segment "VECTORS"
00FFF6  1               	.org  $FFFA
00FFFA  1  98 E1        	.word   do_nmi
00FFFC  1  00 E0        	.word   do_reset
00FFFE  1  A4 E1        	.word   do_irq
00FFFE  1               

But in the linker generated bin file, the jumps are merged together, the 1st jump is placed correctly, but the others specified with ` .org` are not. 

==== bios.bin ====
Offset(h) 00 01 02 03 04 05 06 07 08 09 0A 0B 0C 0D 0E 0F
...
00001EE0  00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00  ................
00001EF0  00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00  ................
00001F00  4C 6E E1 4C F0 E0 4C 36 E0 4C 50 E0 4C 80 E0 4C  LnáLðàL6àLPàL€àL
00001F10  82 E1 4C C4 E0 4C CD E0 4C D6 E0 4C A9 E0 4C BF  ‚áLÄàLÍàLÖàL©àL¿
00001F20  E0 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00  à...............
...
00001FE0  00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00  ................
00001FF0  00 00 00 00 00 00 00 00 00 00 98 E1 00 E0 A4 E1  ..........˜á.à¤á
00002000  EA EA EA EA EA EA EA EA EA EA EA EA EA EA EA EA  êêêêêêêêêêêêêêêê
...
000020D0  EA EA EA EA EA EA EA EA EA EA EA EA EA EA EA     êêêêêêêêêêêêêêê

The vectors are placed correctly but the file is long. 
So I suspect that the linker is not configured correctly here. How do I set this up correctly?

**Comment by willie68** [comment]
Tried, working, beside the holes in the jump table. What should i do with them?
Defining an extra segment for every jump? or filling the gaps with 0 bytes? 
For me it's easier to do this with .org, as i only need to define the jumps, i need. As far as i understand, the asm is doing this right. The list file shows the right jumps on the right addresses. 
Why does the linker scramble them?

**Comment by mrdudz** [comment]
> Defining an extra segment for every jump? or filling the gaps with 0 bytes?

That of course raises the question why there are gaps in a jumptable :) but yes, either will work. i'd probably just use dummy bytes.

> For me it's easier to do this with .org, as i only need to define the jumps, i need. As far as i understand, the asm is doing this right. The list file shows the right jumps on the right addresses.
Why does the linker scramble them?

As said before, ```.org``` is unrelated to memory placement, it only changes the program counter. The linker is doing the memory placement, and the linker doesnt know or care about the program counter. When looking at the list file, the adresses do NOT refer to where it actually goes in memory, it can go anywhere. The adresses only tell you that the code is generates "as if" it was placed at this address.

**Comment by ProxyPlayerHD** [comment]
you can fill the gaps with 0's.

you can use `.res <amount of bytes>, <fill value>` to push the jumps apart without having to mess with extra segments.
also your "jump_table" label should likely be located after the segment statement as otherwise it will be part of the previous segment instead.

```
.segment "JUMPTABLE"
	jump_table:
	JMP do_strout ; $FF00 - STROUT output string, A = high, X = low
	.res 129, $EA
	JMP do_scinit ; $FF81 - SCINIT Initialize "Screen output", (here only the serial monitor)
	.res 3, $EA
	JMP do_ioinit ; $FF84 - IOINIT Initialize VIA & IRQ
	.res 3, $EA
	JMP do_ramtas ; $FF87 - RAMTAS RAM test and search memory end
	.res 3, $EA
	JMP do_restor ; $FF8A - RESTOR restore default kernel vectors

```
alternatives, you can also fill all jumps in but make the ones you don't need point to some default error handler. that would also make it easier to add additional functions later as you don't need to redo the math on the `.res` directives

```
.segment "JUMPTABLE"
	jump_table:
	JMP do_strout ; $FF00 - STROUT output string, A = high, X = low
	JMP def_error
	JMP def_error
	JMP def_error
	JMP def_error
	JMP def_error
	JMP def_error
	JMP def_error
	JMP def_error
	JMP def_error
	JMP def_error
	JMP def_error
	JMP def_error
	JMP def_error
	JMP def_error
	JMP def_error
	JMP def_error
	JMP def_error
	JMP def_error
	JMP def_error
	JMP def_error
	JMP def_error
	JMP def_error
	JMP def_error
	JMP def_error
	JMP def_error
	JMP def_error
	JMP def_error
	JMP def_error
	JMP def_error
	JMP def_error
	JMP def_error
	JMP def_error
	JMP def_error
	JMP def_error
	JMP def_error
	JMP def_error
	JMP def_error
	JMP def_error
	JMP def_error
	JMP def_error
	JMP def_error
	JMP def_error
	JMP def_error
	JMP do_scinit ; $FF81 - SCINIT Initialize "Screen output", (here only the serial monitor)
	JMP def_error
	JMP do_ioinit ; $FF84 - IOINIT Initialize VIA & IRQ
	JMP def_error
	JMP do_ramtas ; $FF87 - RAMTAS RAM test and search memory end
	JMP def_error
	JMP do_restor ; $FF8A - RESTOR restore default kernel vectors
```
but obviously it's a lot more bulky.

**Comment by willie68** [comment]
OK, thanks for your explanation. I'll keep this in mind.

**Comment by polluks2** [comment]
By the way you could use BRK with a function call parameter, it's more flexible than a jump table.

**Comment by mrdudz** [comment]
> By the way you could use BRK with a function call parameter, it's more flexible than a jump table.

In practise its not very useful and has several drawbacks (more cycles, clutters irq handler)

**Comment by polluks2** [comment]
I know, but the $Cxxx jump table of GEOS was a bad decision.
