### ISSUE TITLE
65816 mode JSR (abs, X) gives inappropriate range error

### ISSUE THREAD

**Issue by bbbradsmith** [cc65/cc65#1846]
The JSR (abs, X) instruction available in 65816 mode seems to give an inappropriate range error.

We can work around this with .loword but I can't think of why it would be producing a range error? The instruction takes a 16-bit address, in the current K bank. I'd expect that if table was a far-address or known to be in a different bank, maybe this should be able to produce a range error (possibly not until link time), but I don't understand the simple case below:

```
.p816
	ldx #0
	jsr label ; no range error
	jsr (table,X) ; range error?
	jsr (.loword(table),X) ; requires .loword?
table:
	.word .loword(label)
label:
	rts
```

[65816_jsr_abs_x_range_error.zip](https://github.com/cc65/cc65/files/9457740/65816_jsr_abs_x_range_error.zip)

**Comment by mrdudz** [comment]
I'm not familiar with 65816... can you tell if jsr(abs,x) also exists as jsr(zp,x)? Will it always produce the same binary opcode regardless of the value of abs?

**Comment by bbbradsmith** [comment]
[JSR/JMP/JSL](http://www.6502.org/tutorials/65c816opcodes.html#5.5) don't have any ZP / direct page addressing modes, no.

[(abs, X)](http://www.6502.org/tutorials/65c816opcodes.html#5.5) is only used with JSR and JMP, and is intended for jump tables, which is why it always takes the K bank rather than B, so the tables can be placed alongside the code. There's only one opcode with this addressing for each of JSR and JMP.

[JMP (abs)/JMP [abs]](http://www.6502.org/tutorials/65c816opcodes.html#5.4) both use a pointer via a 16-bit address, always in bank 0. These are intended for a 2 or 3 byte pointer in RAM, which is why it's bank 0 rather than K or B. (This is sort of the equivalent to ZP/direct page addressing for JMP.)

So, possibly the range error came about as accidentally treating (abs, X) like the JMP (abs) case, which does need an address in bank 0?

65816 addressing modes have a few surprising notes like this, which I didn't think were obvious at all, but once I saw where they fit in the context of the whole machine their purpose seemed to make sense.

**Comment by mrdudz** [comment]
please try the next snapshot and see if that works as expected

**Comment by bbbradsmith** [comment]
It does work as expected for the test I gave. I tried a few cases of using it with "far" and did find that it correctly rejects the far address. I believe it's doing the right thing now.

**Comment by mrdudz** [comment]
sounds good! cheers :)
