### ISSUE TITLE
Strange results when using the arrow operator on a structure pointer

### ISSUE THREAD

**Issue by dungeonkim** [cc65/cc65#1847]
I get strange results when using the arrow operator on a structure pointer.

```C
#include <stdio.h>

struct TestStruct {
    char a;
    char b;
};

struct TestStruct s1[2];
struct TestStruct* s1Ptr;


int main() {
    s1[1].b=2;
    s1Ptr=s1;
    printf("%x\n",s1[1].b);
    printf("%x\n",s1Ptr[1].b);
    printf("%x\n",(&s1[1])->b);
    printf("%x\n",(&s1Ptr[1])->b);
    printf("%x\n",(&s1[1])->b);
    printf("%x\n",(&(s1Ptr[1]))->b);
    return 0;
}
```

The result of this should be as below.
```
2
2
2
2
2
2
```

When I run it on cc65 I get:
```
2
2
2
99cd
2
99cd
```
99cd is the same as &(s1[1].b) .
It worked fine before, but it seems to be a recent bug.

**Comment by greg-king5** [comment]
You aren't using the arrow operator on a structure pointer.  You're using it on the _address of_ the pointer!
That's "address of address of structure".

**Comment by dungeonkim** [comment]
It looks complicated, but isn't it true that there is no problem in using it like that? 
And it worked fine in previous builds. 
(I don't know when exactly it was built)

Executing from REPL and cc65 output different results.
[https://replit.com/@dungeonkim/WholeIllustriousNetbsd#main.c](https://replit.com/@dungeonkim/WholeIllustriousNetbsd#main.c)

**Comment by mrdudz** [comment]
I changed the program a bit:
```
#include <stdio.h>

struct TestStruct {
    int a;
    short b;
    char c;
};

struct TestStruct s1[2];
int a,b,c;
struct TestStruct* s1Ptr;


int main() {
    s1[1].b=2;
    s1Ptr=s1;
    printf("%x\n",s1[1].b);
    printf("%x\n",s1Ptr[1].b);
    printf("%p %x\n",(&s1[1]),(&s1[1])->b);
    printf("%p %x\n",(&s1Ptr[1]),(&s1Ptr[1])->b);
    printf("%p %x\n",(&s1[1]),(&s1[1])->b);
    printf("%p %x\n",(&(s1Ptr[1])),(&(s1Ptr[1]))->b);
    return 0;
}
```
using GCC the result is
```
2
2
0x563cb6afb048 2
0x563cb6afb048 2
0x563cb6afb048 2
0x563cb6afb048 2
```
using cc65:
```
2
2
0xbc8 2
0xbc8 bca
0xbc8 2
0xbc8 bca
```

so indeed the pointer is correct, the -> lookup goes wrong for some reason

**Comment by mrdudz** [comment]
@dungeonkim it would be really helpful if you could try older versions of the compiler and try to narrow down when it broke

**Comment by dungeonkim** [comment]
I used 2022-2-26 windows snapshot and it seems to work fine with that version.

**Comment by mrdudz** [comment]
@dungeonkim please try again with next snapshot :)

**Comment by dungeonkim** [comment]
It works fine. thank you!

**Comment by mrdudz** [comment]
thank @acqn :)
