### ISSUE TITLE
Regression on inline assembly expression evaluation

### ISSUE THREAD

**Issue by oliverschmidt** [cc65/cc65#1853]
```
void main(void)
{
  __asm__("lda 1");
  __asm__("lda 1 + 1");
}
```
compiles with e.g. Git 2f4e2a3 to the expected
```
	lda     1
	lda     1 + 1
	rts
```

However, with the current HEAD, it compiles to
```
	lda     1
	lda
	rts
```

**Comment by acqn** [comment]
Introduced on https://github.com/cc65/cc65/commit/6096a24f1dea135e0d435d72df0c714ff5b0b828.

**Comment by mrdudz** [comment]
Darn :)

**Comment by mrdudz** [comment]
should work now, please check

**Comment by oliverschmidt** [comment]
The one who made me aware of the issue told me that the code in question now works again. I was asked to tell you, that the quick fix is appreciated.
