### ISSUE TITLE
CRLF files causing git troubles

### ISSUE THREAD

**Issue by clbr** [cc65/cc65#1858]
In today's master, there are several files that were commited as CRLF, and this is hitting some git bug
https://marc.info/?l=git&m=154490757105272&w=2

Meaning that with the affected git versions, pull/merge/stash/etc are all bork, git reset --hard, git checkout, etc don't help. Please fix the line endings on these files:
```
        modified:   test/val/bug1408.c
        modified:   test/val/bug1451-struct-ptr-to-local.c
        modified:   test/val/bug1643.c
        modified:   test/val/bug1643.h
        modified:   test/val/bug1690.c
        modified:   test/val/bug1822-pptest.c
        modified:   test/val/bug1838.c
        modified:   test/val/bug1847-struct-field-access.c
        modified:   test/val/const-side-effect.c
        modified:   test/val/counter.c
        modified:   test/val/counter.h
        modified:   test/val/opsize.c
        modified:   test/val/pr1833.c
        modified:   test/val/uneval.c
```

Also, what happened with the git history? There were hundreds of commits from early this year and late 2021 that appeared at least four times. Someone screwed up several merges?

**Comment by mrdudz** [comment]
fixed the line endings.

i might be guilty for some of the history mess. git and me like each other equally =P

please close if it works now

**Comment by clbr** [comment]
All fixed. Thanks!

**Comment by rofl0r** [comment]
> There were hundreds of commits from early this year and late 2021 that appeared at least four times. Someone screwed up several merges?

this usually happens when one merges PRs that contain merge commits themselves, like "merge master into some_branch". these PRs need to be edited on command line with git rebase to flatten out the branch history before merge, or contributors advised to use git rebase instead of merging master branch into their branch.

**Comment by polluks** [comment]
Maybe we should use `text eol=lf`?
See https://docs.github.com/en/get-started/getting-started-with-git/configuring-git-to-handle-line-endings
