### ISSUE TITLE
ca65: Can't use negative values with .byte and .word

### ISSUE THREAD

**Issue by furrykef** [cc65/cc65#186]
Code that used to assemble and run just fine with older (pre-github) versions of ca65 now break because .byte and .word can't accept negative values anymore. Trying it raises error messages such as "Error: Range error (-1020 not in [0..65535])".

This is using the latest Windows snapshot.

**Comment by mrdudz** [comment]
On Tuesday 28 July 2015, 18:58:53 Kef Schecter <notifications@github.com> 
wrote:
> Code that used to assemble and run just fine with older (pre-github)
> versions of ca65 now break because .byte and .word can't accept negative
> values anymore. Trying it raises error messages such as "Error: Range error
> (-1020 not in [0..65535])".
> 
> This is using the latest Windows snapshot.

iirc this is by design (and has also been like that for a while in Uz's 
version)

-- 

http://www.hitmen-console.org    http://magicdisk.untergrund.net
http://www.pokefinder.org        http://ar.pokefinder.org

**Comment by furrykef** [comment]
But is it a *good* design?

I've discovered that I can fix it by using ".feature force_range". But shouldn't the default settings be backward compatible with old code except in really compelling cases? I also don't see why not make the range -128..255 and -32768..65535. That way you can keep range checking but still allow negative numbers.

**Comment by oliverschmidt** [comment]
As `force_range` is already mentioned there's basically nothing more to say.

**Comment by furrykef** [comment]
Really? There's nothing to say about keeping out-of-the-box backward compatibility, or extending the range?

**Comment by greg-king5** [comment]
There was some talk about that issue, on the mailing list: https://sourceforge.net/p/cc65/mailman/message/32234634/

**Comment by mjreed-turner** [comment]
But If I have a positive value like $07 and negate it with ~ then I get a negative value. That should not be the case if we're forcing unsigned bytes.
