### ISSUE TITLE
Test suite expected status?

### ISSUE THREAD

**Issue by clbr** [cc65/cc65#1872]
I ran "make test", and got 115 failures. I do see some issues open where tests are expected to fail currently, but wondering what's the expected number?

**Comment by mrdudz** [comment]
That is the output of a single test program (some printf thing iirc) - it does not refer to the testbench as such.

If some test gives a different result than expected, "make test" will fail, ie "make" will report an error and the testbench will stop. If you are not sure, run "make test" again when its done - in case of a problem it will fail again.
