### ISSUE TITLE
cc65: Div by zero in dead code - no output

### ISSUE THREAD

**Issue by kugelfuhr** [cc65/cc65#1887]
The compiler refuses to generate output if there's a division by zero in code that is never called. Even if the code would have been removed if the compiler would process the input further.

```C
#include <stdio.h>

static int never_called(int a)
{
    return a / 0;
}

int main(void)
{
    printf("Hello world\n");
    return 0;
}
```

Strictly speaking the compiler is correct since division by zero triggers ub. So it's not a bug. But I don't think it's a good idea either.

**Comment by mrdudz** [comment]
I dont think this can be changed, due to how the compiler works (it doesnt know the code is never called at the time it is generated)

**Comment by kugelfuhr** [comment]
Why not make the error a warning? That would alert the user without having above mentioned problems.

```
$ gcc -Wall -o test test.c
test.c: In function ‘never_called’:
test.c:5:14: warning: division by zero [-Wdiv-by-zero]
    5 |     return a / 0;
      |              ^
At top level:
test.c:3:12: warning: ‘never_called’ defined but not used [-Wunused-function]
    3 | static int never_called(int a)
      |            ^~~~~~~~~~~~
```
