### ISSUE TITLE
cc65: Overflow in enumerator value is not detected

### ISSUE THREAD

**Issue by kugelfuhr** [cc65/cc65#1890]
The following code compiles without problems. The numeric overflow of the enumerator value 'b' is not detected and the variable 'c' has the value zero:

```C
#include <limits.h>
enum { a = ULONG_MAX, b } c = b;
```

**Comment by acqn** [comment]
ad7c5a66174feeb7a1c409c6224cc83789dd36d4 does detect this and gives two warnings at least for me:
```
1893.c:2: Warning: Enumerator 'b' overflows the range of 'unsigned long'
1893.c:2: Warning: Enumerator 'b' (value = 0) is of type 'int'
```
The first warning could probably best be converted to an error and the second warning is a superfluous result of the wrap-around.

**Comment by kugelfuhr** [comment]
> [ad7c5a6](https://github.com/cc65/cc65/commit/ad7c5a66174feeb7a1c409c6224cc83789dd36d4) does detect this and gives two warnings at least for me:

Another chapter from the book <How to say "I'm using Windows" without saying "I'm using Windows">  :smile: 

It works for Windows but not on other platforms because the code for the overflow check is not portable. It uses the "long" datatype which is 32 bit on Windows and 64 bit on most other operating systems.

You can use this patch for a quick fix:

```diff
--- a/src/cc65/declare.c
+++ b/src/cc65/declare.c
@@ -620,7 +620,8 @@ static SymEntry* ParseEnumDecl (const char* Name, unsigned* DSFlags)
             */
             EnumVal = (long)((unsigned long)EnumVal + 1UL);
 
-            if (UnqualifiedType (MemberType->C) == T_ULONG && EnumVal == 0) {
+            if (UnqualifiedType (MemberType->C) == T_ULONG && 
+                (EnumVal & 0xFFFFFFFF) == 0) {
                 /* Warn on 'unsigned long' overflow in enumeration */
                 Warning ("Enumerator '%s' overflows the range of '%s'",
                          Ident,
```

A probably better solution would be to consequently use fixed size integer types (int32_t/uint32_t) for values that mimic anything that is actually an expression on the target platform.
