### ISSUE TITLE
Amiga support

### ISSUE THREAD

**Issue by polluks** [cc65/cc65#192]
Amiga support is broken since the new makefiles. Anyway you can simply control it inside the source:

--- ./src/cl65/main.c.bak       2015-06-25 08:19:35 +0000
+++ ./src/cl65/main.c   2015-06-26 01:29:55 +0000
@@ -148,7 +148,7 @@

 #if defined(NEED_SPAWN)
-#  if defined(SPAWN_AMIGA)
+#  if defined(_AMIGA)
 #    include "spawn-amiga.inc"
 #  else
 #    include "spawn-unix.inc"

**Comment by oliverschmidt** [comment]
Hi if you already know the solution then it might be more appropriate to create a pull request instead of an issue.

**Comment by oliverschmidt** [comment]
As Stefan hasn't created a pull request so far I add the 'help wanted' tag...

**Comment by spektro** [comment]
Defining the SPAWN_AMIGA in the command line should work:

    gmake USER_CFLAGS=-DSPAWN_AMIGA=1

**Comment by oliverschmidt** [comment]
There's seems to be
* no momentum for a pull request
* a viable workaround
