### ISSUE TITLE
Tests should also run on windows with cmd.exe

### ISSUE THREAD

**Issue by mrdudz** [cc65/cc65#1920]
The github actions should perform a full build/test also when running on windows - that is to make sure the makefiles all keep working with cmd.exe (which we just restored... hopefully).

**Comment by mrdudz** [comment]
I tried a bunch of things in #1937 but couldnt get it to work - seems GHA is always using msys bash, not cmd.exe

**Comment by bbbradsmith** [comment]
Has this been resolved now with #2108 and is #1937 still relevant or should it be closed?

**Comment by mrdudz** [comment]
Those 3 interconnected PRs are still confusing me :)

I think the original issue is solved. Kind of - i am not really comfortable with the CI partially running via cron instead of the PR trigger though, since that means failing checks won't be noticed eventually and something merged that shouldn't be... (not sure if all ppl who can merge would even see the result) it's a bit besides the point of having CI for PRs ;)

**Comment by bbbradsmith** [comment]
Well, the only reason I suggested the manual/cron version was that it adds another 20 minutes to the windows job. If that's accceptable, though, you could definitely move the test into the PR/snapshot jobs.

**Comment by mrdudz** [comment]
closed via #2401
