### ISSUE TITLE
setjmp shorter

### ISSUE THREAD

**Issue by polluks** [cc65/cc65#193]
<pre>--- ./libsrc/common/setjmp.s.bak        2015-06-25 08:19:35 +0000
+++ ./libsrc/common/setjmp.s    2015-08-05 00:57:35 +0000
@@ -6,6 +6,7 @@

         .export         __setjmp
         .importzp       sp, ptr1
+        .import         return0

 __setjmp:
         sta     ptr1            ; Save buf
@@ -44,9 +45,4 @@

 ; Return zero

-        lda     #0
-        tax
-        rts
-
-
-
+        jmp     return0</pre>

**Comment by oliverschmidt** [comment]
You might want to elaborate on what you want to state here but as far as I can see you're proposing an optimization. Please consider creating a pull request with your proposal.

**Comment by oliverschmidt** [comment]
As Stefan hasn't created a pull request so far I add the 'help wanted' tag...
