### ISSUE TITLE
As of 11/26/2022 - build fails with MINGW?

### ISSUE THREAD

**Issue by mrdudz** [cc65/cc65#1933]
### Discussed in https://github.com/cc65/cc65/discussions/1929

<div type='discussions-op-text'>

<sup>Originally posted by **xlar54** November 27, 2022</sup>
Hello, Im getting the following when trying to build the current master branch:

```
apple2 - apple2/targetutil/convert.c
cc65.exe: Internal error: Invalid format specifier in xvsnprintf, file 'common/xsprintf.c', line 616
make[2]: *** [apple2/targetutil/Makefile.inc:5: ../libwrk/apple2/convert.o] Error 1
make[1]: *** [Makefile:119: apple2] Error 2
make: *** [Makefile:7: all] Error 2
```

Is this a known issue? </div>

**Comment by xlar54** [comment]
Ityped the following:

make clean
git pull
make

**Comment by mrdudz** [comment]
What kind of setup is it? 32 or 64 bit? What windows version? bash or cmd.exe?

The snapshot is built with mingw and that seems to work - so i wonder what you are doing differently there.

**Comment by mrdudz** [comment]
Are you using cmd.exe by any chance? I am playing with testing that in the github actions right now - and i am getting the same error! see https://github.com/cc65/cc65/actions/runs/3560655016/jobs/5980841299

**Comment by mrdudz** [comment]
I tracked it down to the recent printf-specifier hack in codegen.c. This is really super annoying :(

**Comment by mrdudz** [comment]
should be fixed, please try again

**Comment by xlar54** [comment]
works like a champ, thank you!

**Comment by bbbradsmith** [comment]
Should this be closed?

**Comment by mrdudz** [comment]
indeed, thx for the reminder
