### ISSUE TITLE
[bug][65sc02, 65c02, HuC6280] Compiler produces broken Assembly (129 operand for `bne`)

### ISSUE THREAD

**Issue by Fabrizio-Caruso** [cc65/cc65#1936]
When compiling my game Horde, recent versions of CC65 produce an Assembly file with a broken `bne` with a 129 operand.
I am getting this error only when building my "universal" game Cross Horde for the PCE target. I do not see it otherwise. This issue is not reproduced with a CC65 version from the end of April.

2022/11/28 -> KO
2022/08/10 -> KO

2022/04/24 -> OK

I have attached the broken Assembly file. The error is in line 1849.
[main.zip](https://github.com/cc65/cc65/files/10099450/main.zip)

I can reproduce it with my Cross-Lib framework by running from inside the `src` directory
`
xl horde pce
`

**Comment by mrdudz** [comment]
Well, we'll need the C code to reproduce the problem.... a minimal snippet ideally :)

**Comment by Fabrizio-Caruso** [comment]
@mrdudz Finding a minimal snipets won't be easy. 
The problem only shows up with the PCE in only one game, which is compiled together with my full Cross-Lib framework:
https://github.com/Fabrizio-Caruso/CROSS-LIB

I am building the very same game with the very same game code for practically all CC65 targets (and other non MOS6502 targets).  
The very same code has no problem for all other targets.

It can be reproduced by simple running `xl horde pce` insde `src` in Cross-Lib.

I can try to reduce the code and see if I find where it fails... for the PCE but I fear it may be hard.

**Comment by mrdudz** [comment]
Well, without a C snippet to reproduce the problem, it is impossible to find out whats wrong. You might want to start with compiling with --add-source and then narrow it down. It should be possible to reduce the problem to the function the problematic branch occurs in (since branches never go outside the current function)

**Comment by Fabrizio-Caruso** [comment]
@mrdudz I will try that. A different approach would be to use git bisect. It may also tell us which commit broke it because we know when it was (probably) working. It was ok in April and it was bad in August. Unless it was broken before April and the problem does not show up easily.

**Comment by mrdudz** [comment]
I find it very strange that this would only break on PCE target - that function doesnt seem to have PCE specific things in it at all (and no PCE specific code seems to be generated).

It might help to compare against the asm output compiled for a different target

**Comment by Fabrizio-Caruso** [comment]
@mrdudz It works fine if I compile without `-O`. Could a  peep hole substitution be the culprit?

**Comment by Fabrizio-Caruso** [comment]
@mrdudz supervision has the same issue (with the same code)

**Comment by mrdudz** [comment]
It could be anything - which is why a testcase is needed :)

**Comment by Fabrizio-Caruso** [comment]
@mrdudz Not a minimal case yet but the problem seems to be here:
https://github.com/Fabrizio-Caruso/CROSS-LIB/blob/master/src/games/horde/main.c#L1415

I have attached a new main.s file with the source code.
[main.zip](https://github.com/cc65/cc65/files/10136805/main.zip)

**Comment by Fabrizio-Caruso** [comment]
@mrdudz 
I now have a minimal example that only fails when compiled for either `pce` or `supersion` with `-O -Cl` options.
[minimal_source.zip](https://github.com/cc65/cc65/files/10143673/minimal_source.zip)

You can reproduce the problem by running the following command (or the same command with `-tsupervision`)
```
$ cl65.exe -O -Cl --add-source -tpce main.c
```
which should produce
```
main.c:34: Warning: Control reaches end of non-void function [-Wreturn-type]
main.c:34: Warning: Parameter 'itemArray' is never used
main.c:39: Warning: Parameter 'item' is never used
main.c:39: Warning: Parameter 'max_counter' is never used
main.s:106: Error: Range error (129 not in [-128..127])
```

I have also included the broken Assembly file
[asm_main.zip](https://github.com/cc65/cc65/files/10143685/asm_main.zip)

**Comment by Fabrizio-Caruso** [comment]
So the problem seems to be in the optimizing code for CPUs like 65c02, 65sc02, HuC6280, etc.

**Comment by mrdudz** [comment]
so... first, the generated code is exactly the same for all/both cpus (i compared c64 and pce)
```
	ldx     #$00
	lda     _powerUpItem
	jsr     bnega
	jeq     L0003
```
but it is optimized into different code, this is the (working) c64 code - it produces the common "long branch" construct:
```
	lda     _powerUpItem
	beq     L001E
	rts
L001E:
```
however, for PCE the snippet is optimized into this:
```
	lda     _powerUpItem
	bne     L0016
```

**Comment by Fabrizio-Caruso** [comment]
@mrdudz Why is the wrong optimizer's rule only triggered on non-standard 6502 variants?
The wrong Assembly does not appear to use non-standard opcodes...

The bug in the optimizer was end of April and beginning of October, does this ring a bell to you?

**Comment by mrdudz** [comment]
You could try bisecting it... but iirc only the order of some optimizing steps were fixed/changed, so its probably a bug that was always lurking in there.

**Comment by Fabrizio-Caruso** [comment]
@mrdudz substitution is not always commutative. So a mere change in the applications of two rules could break the optimizer.
Rule 1: A changed to B
Rule 2: B changed to C
If I apply these rules in different order to “ABC“ i I get different results:
CCC or BCC.

**Comment by mrdudz** [comment]
Sure. But if that breaks the result, then there has been a bug before and it only worked by chance. Any combination or order of optimization steps should always result in working code. (And to make sure things like your example do not matter, certain optimization steps are applied twice).

**Comment by Fabrizio-Caruso** [comment]
I mean two rules in a given order may not break the range because their application in a given order is preserving or reducing a range. So the bug itself may be the order. This is only a possibility and, as you say, the bug may have been just concealed by the previous order  My Assembly skills are not great... So I hope that someone who has worked on the optimizer could help us with this bug. 
Can we assume that the intermediate rule is using some non standard opcode?

**Comment by mrdudz** [comment]
There are checks that make sure the branch doesnt end up being too far - in every single step. There has to be, because you never know if the next step is going to be applied.

And yes, of course, there has to be a 65c02 opcode in some intermediate step, which then triggers different behaviour in another step.

**Comment by Fabrizio-Caruso** [comment]
So a check must have failed. Is the broken code correctable in an automatic fashion by replacing overflowed short jumps (beq, bene, ...) with long jumps (jmp) ?

**Comment by mrdudz** [comment]
Sure, the optimizer also does that as one of the last steps.

**Comment by Fabrizio-Caruso** [comment]
@mrdudz So you are implying that the code that is supposed to fix overflowed branches is the culprit (or at least one of the culprits) or it is not invoked for some reason.
Who among the core devs could we ask for help and tag them here?

**Comment by mrdudz** [comment]
It could be. And i have no idea :)

**Comment by mrdudz** [comment]
try this patch
```
diff --git a/src/cc65/codeopt.c b/src/cc65/codeopt.c
index 440b10751..fae43ab5b 100644
--- a/src/cc65/codeopt.c
+++ b/src/cc65/codeopt.c
@@ -850,6 +850,8 @@ static unsigned RunOptGroup7 (CodeSeg* S)
     C += RunOptFunc (S, &DOptJumpCascades, 1);
     C += RunOptFunc (S, &DOptBranchDist2, 1);
 
+    C += RunOptFunc (S, &DOptBranchDist, 3);
+
     Changes += C;
     /* If we had changes, we must run dead code elimination again,
     ** since the changes may have introduced dead code.
```

**Comment by acqn** [comment]
So it's the "`bra`->`jmp` fixer (65c02 only)" that increases the code size and breaks the branches that should eventually be fixed...

**Comment by mrdudz** [comment]
> So it's the "bra->jmp fixer (65c02 only)" that increases the code size and breaks the branches that should eventually be fixed...

Not necessarily... it could also be any other pass that (for whatever reason) increases code size (between the branch and the branch target). Generally speaking that is, i havent even tried to track down what the actual problem is in this case.

> So in theory, could there still be code with branches that require more than 3 (or some arbitary number) passes of OptBranchDist to get spotted and fixed by any chance?

Yes, totally. It might actually be a good idea to run the entire optimizer more than once. (Or perhaps only a selected set of rules). The Problem with this is though, that this tends to start "oscillating", so you cant just run it again until it does no more changes.

We really need a way to feed arbitrary code to the optimizer for that matter - so we can test it properly, in particular edge cases like this one. Relying on compiler generated code for this is terrible :(

**Comment by Fabrizio-Caruso** [comment]
@mrdudz sorry if I ask a stupid question, can't we make a quick temporary maybe sub-optimal fix by just running the check on overflowed relative branches? Optimization is less important than correct code.

**Comment by mrdudz** [comment]
Did you try that patch?

**Comment by Fabrizio-Caruso** [comment]
No, I didn't. I am going to do it asap. So it is just one in a file. I need to clone the repo.

**Comment by mrdudz** [comment]
comitted the fix - please reopen if the problem persists
