### ISSUE TITLE
[sp65] 1BPP pixel sprite generation buggy In Atari Lynx sprites

### ISSUE THREAD

**Issue by karrika** [cc65/cc65#1957]
I just tried to help a friend to convert his old sources to the latest cc65 and found out that the sp65 is really buggy in the current sp65.
![Buggy](https://user-images.githubusercontent.com/6996727/210056909-4d9cc3ec-e51e-46bd-9c1d-cb133f8c497d.png)
I have been developing the sp65 for my own work and the generation of optimized sprites is a really complex thing. The solution I have is still far from optimal - but a lot better than the current version we have. It does not produce a better version than optimizing by hand but it does produce a correct version.
![Fixed](https://user-images.githubusercontent.com/6996727/210057123-a49c0405-9cc8-4c1a-b60a-3310c7ff5424.png)
Anyway, I plan to bring up the code to a working level and make a pull request.

**Comment by mrdudz** [comment]
again, this can be closed by #1958 - correct? (if you make an issue and a related PR, please reference one from the other)

**Comment by karrika** [comment]
Yes.

**Comment by mrdudz** [comment]
closed by #1958
