### ISSUE TITLE
[sp65] extract palette from bitmap. New feature

### ISSUE THREAD

**Issue by karrika** [cc65/cc65#1959]
When dealing with bitmaps one of the tedious things is to extract the palette colours used on the bitmap and insert them into the target build. To make my life easier I implemented a new keyword for extracting the palette.
sp65 -r bitmap.pcx -p lynx-palette,pal.c
The command above would extract the palette and output it in Lynx format to a file pal.c
This feature could be implemented for other platforms as well by providing the proper palette generating code.

**Comment by mrdudz** [comment]
this can be closed by #1960 - right? :)

**Comment by karrika** [comment]
Yes. I am a bit newbie in how people want to handle pull requests...

**Comment by mrdudz** [comment]
closed by #1960
