### ISSUE TITLE
Pre-commit check dangling spaces

### ISSUE THREAD

**Issue by marianodominguez** [cc65/cc65#1963]
Hello.

I double checked and removed all trailing spaces in the PR.

https://github.com/cc65/cc65/pull/1962/files

however it still marking I have spaces in sound.s
are the spaces to comments counting as dangling ?
Thanks

**Comment by Compyx** [comment]
There's a trailing space on line 14 in atari.s:
~~~
        sta STORE1      ;save distortion 
~~~

Configure your editor to show trailing whitespace, or use grep to find them:
~~~
$ grep -n '\s\+$' libsrc/atari/sound.s
$ 14:        sta STORE1      ;save distortion
~~~
Any decent editor should be able to show trailing whitespace, in Vim for example you can put this in `.vimrc`:
~~~
set list listchars=tab:»-,trail:~
~~~
and to delete all trailing whitespace you can use `:%s/\s\+$//`

**Comment by marianodominguez** [comment]
thanks ! pr is passing now
