### ISSUE TITLE
Bit-fields on 8bits members won't compile

### ISSUE THREAD

**Issue by cgimenez** [cc65/cc65#1976]
May be I'm missing something, but in the documentation (https://cc65.github.io/doc/cc65.html), I read this statement : 

> cc65 supports bit-fields of any integral type that is int-sized or smaller, and enumerated types with those types as their underlying type. (Only int, signed int, and unsigned int are required by the standard.) 

But, compiling this part of code 

```
typedef struct {
    uint8_t x, y;
    uint8_t dirty : 1;
} position_t;
```
Generate a compile time error :

`Error: Bit-field has invalid type`

And there's no problem with uint16_t members.

**Comment by mrdudz** [comment]
could you post a complete minimal example?

crazy that the regression tests would still not catch this :)

**Comment by cgimenez** [comment]
Sure !

With 

`cc65 V2.19 - N/A`

```
typedef struct {
	unsigned char dirty: 1;
};

int main(void) {
   return 0;
};
```
```
cl65 -O -t sim6502 main.c -o main.prog
```
Produces error

```
main.c(2): Error: Bit-field has invalid type
```

Because I had an uptodate Ubuntu VM, I give a try with
`cc65 V2.18 - Ubuntu 2.18-1`

Same error

That means that few people uses bitfields, and even fewer with 8bits members, except lazy coders like me ;-)

**Comment by polluks** [comment]
Well, cc65 V2.19 - Git 0f98e59b5 works...

**Comment by cgimenez** [comment]
Fine ! Tried with `ca65 V2.19 - Git 901f35075`, all green !

**Comment by mrdudz** [comment]
so we can close this?
