### ISSUE TITLE
Linker problem with set_irq

### ISSUE THREAD

**Issue by spektro** [cc65/cc65#198]
I wrote the following short program to test interrupts on Plus/4:
```c
#include <6502.h>
#include <plus4.h>

#define TEMP_STACK_SIZE 2048

void main ( void );
unsigned char f_IntRoutine ( void );

unsigned char aucTempStack [ TEMP_STACK_SIZE ];

void main ( void ) {
    SEI ();
    set_irq (
        &f_IntRoutine,
        aucTempStack, TEMP_STACK_SIZE
    );
    CLI ();

    for ( ;; ) { }
}

unsigned char f_IntRoutine ( void ) {
    ++TED.bordercolor;

    return ( IRQ_NOT_HANDLED );
}
```

When I compile and link the program with cl65, I get these two warnings:

d65: Warning: cc65:cfg/plus4.cfg(22): Segment `BSS' with type `bss' contains initialized data

ld65: Warning: Address size mismatch for `__ZP_START__': Exported from cc65:cfg/plus4.cfg(7) as `absolute', import in interrupt.o, common/interrupt.s(11) as `zeropage'

If I run the program, it doesn't work: Plus/4 encounters a break instruction which stops the execution.

The target system is 'plus4' and I'm using the default linker configuration file for the Plus/4.

**Comment by oliverschmidt** [comment]
@spektro Thanks for filing the bug here.

@greg-king5 You seem to have analyzed the issue already. Therefore I presume that you'll provide a fix for it. Please let me know if my presumption is wrong - and I'll add the 'help wanted' tag.
