### ISSUE TITLE
jmp (abs) on a page boundary should be an error on 6502 rather than a warning because of the well known CPU bug

### ISSUE THREAD

**Issue by bbbradsmith** [cc65/cc65#2005]
I had originally implemented with as part of PR #1999 thinking it was an uncontroversial add-on, but after some resulting debate about it, felt it was inappropriate baggage for that PR. I felt I should raise it as its own issue rather than let it block that PR.

New PR for just this change: #2006 

I will try to summarize the debate had at #1999 but please read for full context.

On the 6502:
```
jmp (label)
```

This can jump to an unexpected location, if the linker happens to place _label_ on a page boundary. E.g. if label is $80FF it will jump to the addressed fetched from $80FF,$8000 rather than $80FF,$8100. Guides for 6502 programming seem to universally describe this as a bug of the CPU, and the 65C02 and later revisions indeed treated it that way and corrected it. Example: [NMOS 6502 Opcodes: JMP](http://www.6502.org/tutorials/6502opcodes.html#JMP) article in bold states "AN INDIRECT JUMP MUST NEVER USE A VECTOR BEGINNING ON THE LAST BYTE OF A PAGE".

We have a warning for this. My PR promoted this warning to an error, but also made the exception that 65C02 and other processor variations that don't have this bug won't produce the error.

I felt it should be an error because it produces invalid code that will crash the program, in a way that the programmer can't predict because it was the linker's job to place the label. The user who opened issue #1563 implied they felt it should be an error as well, but was more explicitly requesting ```--warnings-as-errors```, which as a general solution can promote this warning to an error. Of course that promotes all other warnings as well, and we don't have very good warning filtering/suppression control on this assembler to begin with.

Some points from mrdudz:

> It's valid code in the sense that is syntactically correct - and thus should be accepted by the assembler.
> I'd say its the expected behaviour (and every other assembler i know works like this)
> To me this is no different than eg lda($ff),y - when i write this, i don't want the assembler to produce an error.

Some comments from groessler:

> why is the warning not sufficient?
> I don't think it's the job of the toolchain to outwit the user.
> If such a jmp is by mistake, the warning should suffice.
> If it's deliberate, the user should be allowed to do it.

My feeling is that the we should validate more than just syntax in this case. I would also argue that ```lda (zp), Y``` should have an error against the similar wrap, but I consider it a much less severe case. I would accept that ```lda ($FF), Y``` does look deliberate but I feel that ```lda (label), Y``` is the normal case.

I don't believe there is any valid use for this behaviour aside from writing a specific test of the CPU, and the needs of users to catch the error far outweighs the inconvenience for those who might want to do it deliberately. I would honestly like to see any example of code that wants to rely on this behaviour, because it would help me understand why we should allow the linker to produce a known problem like this with only a warning.

I do think a CPU test for the behaviour is valid, but is extremely specific, and only something very expert users would need, which does not need to be accomodated to the detriment of less-expert users who might not be familiar with the bug or understand that this "warning" indicates a problem as serious as it is.

If the error does need suppression, here are two existing ways to get around it:
```
; 1. manual assembly to suppress the error
.byte $6C, $FF, $80 ; jmp ($80FF)

; 2. selecting a CPU without the bug to suppress the error
.pc02
jmp ($80FF)
```

If there's no consensus/agreement that it should just be an error, I could also propose it alternatively as a ```.feature``` to either demote it to warning or promote it to error, but I strongly recommend that it should be an error by default, at least. (Though, maybe this discussion indicates a more general need to have addressible warnings/errors that we can ignore or promote from the command line or with a command directive, as can be done in some other compilers.)

**Comment by Movax12** [comment]
I would like to just say that I _do_ think this should be an error. I understand the argument that the assembler/linker shouldn't stop someone from using what is valid syntax, but the problem that results is so severe, I don't see any issue with an error. If I see the warning, I know the build is useless, and if I don't see the warning, possibly I'm troubleshooting for some time before I realize why my program is crashing. If one wants to test or use this behavior in some way they will likely know how to use .byte or .pc02. A feature to turn it off sounds like a good idea as well, but by default it should be on.

**Comment by oliverschmidt** [comment]
@bbbradsmith: I totally agree with you.

**Comment by mrdudz** [comment]
After letting it sink in for a while... i changed my mind and i agree that we want
- an error by default
- a .feature and cmdline option to make it a warning

As always it would be nice to have tests as well :)

**Comment by bbbradsmith** [comment]
It seems unusual to want to use `.feature` to demote an error to a warning? As mentioned any CPU target other than 6502 (e.g. `.pc02`) [will suppress it](https://github.com/cc65/cc65/commit/016b03e3562666db24e5364b8034ad07314a96fc), so we do already have a way both as an an assembler directive and command line to do that. If someone doesn't want an error for this case, what would make a warning useful?

I'll add a test case to the PR.

**Comment by mrdudz** [comment]
i'd at least like to see a commandline option that makes it a warning.... i have no strong opinion on .feature. i'd go the way of what is least surprising :) how is it done for other similar cases (are there any)?

**Comment by bbbradsmith** [comment]
We have no similar cases. There is no precedent for using the command line (or a feature) to change an error to a warning, but feature can be used on the command line.

I don't really understand why you want command line to make this a warning though? If you don't have a use for the jmp error, what did you need a warning about it for? What will the warning diagnose for you that is useful?


In a more general sense, out of scope of this discussion, I would love to see a way to disable and/or promote/demote every specific warning, from the command line and also as assembly directives or pragmas, but doing this would require us to add an ID to every warning.

It would feel very odd to add a whole special-case command line option just to demote the page-crossing jmp (abs) bug error to a warning though. What is the point of such a thing?

**Comment by mrdudz** [comment]
> We have no similar cases. There is no precedent for using the command line (or a feature) to change an error to a warning, but feature can be used on the command line.

actually we do:

> **--relax-checks**
Relax some checks done by the assembler. This will allow code that is an error in most cases and flagged as such by the assembler, but can be valid in special situations.
>
> Examples are:
> - Short branches between two different segments.
> - Byte sized address loads where the address is not a zeropage address.

Feels totally sane to add this thing here - please make it so :)

**Comment by bbbradsmith** [comment]
`--relax-checks` is not changing an error into a warning, it is [disabling exactly one error](https://github.com/cc65/cc65/blob/39619b629d3614f6b284865f5c254ebda5272f2b/src/ca65/segment.c#L410). It's actually not even disabling the error for branches between segments like it documents. It seems that --relax-checks needs some maintenance, of its documentation if nothing else...

As mentioned, the error can already be suppressed, from the command line or in code. This check was not part of --relax-checks before, and it feels very arbitrary to suddenly add it now?

I understand that you're saying you want a command line option to turn this particular error into a warning, what I'm having trouble understanding is why you would ever use such a thing. What goal will deliberately demoting it to a warning help you accomplish? Why should we add add a bunch of extra command line or feature code for something, unless there is a need to use it?

The use case for making it an error is that my code will crash if I don't catch it. I've already run into this problem in my real work. I was disturbed to find that my bug was being caught by the compiler yet only reported as an error, as was the case with [this user](https://github.com/cc65/cc65/issues/1563). I've already made the case for this above.

On the other side, I still don't understand the want of a warning instead. I cannot come up with one myself, and I keep asking for an example. Can you show some code that uses this deliberately in some meaningful way? Do you have 6502 codes that uses it? Do you know anyone that does? What use case is being advocated for?

**Comment by spiro-trikaliotis** [comment]
> On the other side, I still don't understand the want of a warning instead. I cannot come up with one myself, and I keep asking for an example.

If someone wants to actually use this feature, for example, for obfuscation, or for testing the processor, he would not be able to do it (other than issuing a .byte $6c, .word addr "by hand").
This might be rare, but it is a valid use case.

**Comment by bbbradsmith** [comment]
> If someone wants to actually use this feature, for example, for obfuscation, or for testing the processor, he would not be able to do it (other than issuing a .byte $6c, .word addr "by hand"). This might be rare, but it is a valid use case.

The error can also be suppressed with `.pc02`. I'm asking what the use of a warning is. If you're doing it deliberately, why do you want a warning?

**Comment by bbbradsmith** [comment]
I added `--relax-checks` to the PR #2006 as an alternative way to suppress this, if that was needed.

**Comment by spiro-trikaliotis** [comment]
> The error can also be suppressed with .pc02.

No, this does not supress the error, it lies to the assembler if I am doing NMOS 6502 programming.
This would have some other implications which I might not want to have.

> I'm asking what the use of a warning is. If you're doing it deliberately, why do you want a warning?

I do not want a warning. ;) However, I feel it could help someone who does not deliberately want to have this (broken) behaviour.

**Comment by bbbradsmith** [comment]
Well the context is that it should be an error, not a warning, for the standard use case where someone wants to produce valid working code.

We already had a warning, my PR changes it to an error. mrdudz was asking for a way to turn it back to a warning, and that's what I don't understand the point of. If you care about the thing it warns... I think you want an error. If you are deliberately forcing it, I don't think you want a warning?

Like I definitely understand wanting a way to force it... but there is no purpose for a warning in that case. We only need a way past the error.

Though, if your point is a CPU test or obfuscation I feel like you're probably already deep into using direct .byte for illegal instructions anyway... macros are often useful in situations like that. I do get the point that `.pc02` isn't exactly semantically what you want, though it really changes very little about code generation, and you can also use `.p02` to change back directly after the relevant code.

I did now add it to `--relax-checks`, though not as a warning, just as a disable. That provides a different way to disable it via the command line.

I feel like the reason it was a warning in the first place instead of an error was probably just because it was applying to all CPUs instead of just 6502, but I fixed that so it only applied to 6502 now (in the related PR that was already accepted months ago).

**Comment by mrdudz** [comment]
> Though, if your point is a CPU test or obfuscation I feel like you're probably already deep into using direct .byte for illegal instructions anyway... macros are often useful in situations like that.

Actually, not quite. Being able to avoid those ugly hacks is the whole point. (ca65 supports the undocumented instructions for that matter)

However, merged the PR now. Cheers!
