### ISSUE TITLE
cc65: Structs with duplicate fields do not cause errors

### ISSUE THREAD

**Issue by kugelfuhr** [cc65/cc65#2015]
cc65 happily compiles structs with duplicate fields:

```c
struct x {
    int a;
    int a;
} x;
    
void f(void)
{
    x.a = 3;
}
```

If one of the fields has its type changed to char (for example), it complains about "conflicting types, 'char' vs 'int'".

**Comment by bbbradsmith** [comment]
Seemed very simple to fix. PR #2075
