### ISSUE TITLE
cc65: Compiler accepts structs with flexible members as struct fields

### ISSUE THREAD

**Issue by kugelfuhr** [cc65/cc65#2016]
cc65 allows struct fields that are structs with flexible array members:

```c      
typedef struct x {
    int a;
    int b[];    /* Ok: Flexible array member can be last */
} x;
    
struct y {
    x   x;      /* Not ok but accepted: Contains flexible array member */
    int a;
};
```

**Comment by bbbradsmith** [comment]
#2017 is closely related

**Comment by acqn** [comment]
Could there be any value supporting this as an extension like gcc's/clang's? Or should an error be raised?

**Comment by kugelfuhr** [comment]
I don't see a real use for it and it complicates things a lot. How, for example, would `struct y` be statically initialized? Not supporting it is cleaner and easier to implement.

**Comment by mrdudz** [comment]
I agree, it would need a lot of tests for the cases that don't (can't) work and as a result be very confusing.
