### ISSUE TITLE
cc65: Compiler allows arrays of structs with flexible array members

### ISSUE THREAD

**Issue by kugelfuhr** [cc65/cc65#2017]
The following is illegal according to the standard but accepted by cc65:

```c
struct x {
    int a;
    int c;
    int b[];
};

struct x y[3];          /* Should be an error */
````

**Comment by bbbradsmith** [comment]
#2016 is closely related

**Comment by acqn** [comment]
Could there be any value supporting this as an extension like gcc's/clang's? Or should an error be raised?
