### ISSUE TITLE
cc65: Compiler has problems with switch statements

### ISSUE THREAD

**Issue by kugelfuhr** [cc65/cc65#2019]
Type promotion in switch statements seems to be broken.

```c
unsigned char c = 0xFF;
void func(void)
{
    switch (c) {
        case (signed char)0xFF: ;
        case (unsigned char)0xFF: ;
    }
}
```
Gives:
```
test.c:5: Error: Range error
test.c:6: Error: Duplicate case label
```

But both errors are wrong. The first one is simply a label that is never jumped to and the second one is not a duplicate of the first.

ISO/IEC 9899:1999 (E) 6.8.4.2p5 says: "The integer promotions are performed on the controlling expression. The constant
expression in each case label is converted to the promoted type of the controlling expression. If a converted value matches that of the promoted controlling expression, control jumps to the statement following the matched case label."

It seems that this is not done by the compiler. The controlling expression is not promoted to int, and in turn the case label expressions are kept as is, in which case the are identical. If they were correctly promoted to int, they would be different.

This is a problem even without any casts. The following does also give a range error:

```c
signed char c = 0xFF;
void func(void)
{
    switch (c) {
        case 0x80: ;
    }
}
```

**Comment by GorillaSapiens** [comment]
this one is really bugging me, because in my sandbox i've fixed #2172, which causes the test case for this one to break.

<pre>
unsigned char c = 0xFF;
void func(void)
{
    switch (c) {
        case (signed char)0xFF: ;
        case (unsigned char)0xFF: ;
    }
}
</pre>

"The constant expression in each case label is converted to the promoted type of the controlling expression. "

the "controlling expression" here is "unsigned char".  the constants get converted to "unsigned char".  in which case this **IS** a duplicate case label.

**Comment by mrdudz** [comment]
but "The integer promotions are performed on the controlling expression. The constant expression in each case label is converted to the promoted type of the controlling expression."

"promoted type" being the key here

**Comment by GorillaSapiens** [comment]
> but "The integer promotions are performed on the controlling expression. The constant expression in each case label is converted to the promoted type of the controlling expression."
> 
> "promoted type" being the key here

are you saying all char should be promoted to int?  doesn't that seem wasteful?  if they all get promoted to int, then what's the point of all the Depth=1 code in the SwitchStatement() and g_switch() functions?

[edit:]  a'ight, looks like you're right.  i need to keep working on this one.  thank you.
