### ISSUE TITLE
cc65: Returning structs by value generates invalid code

### ISSUE THREAD

**Issue by kugelfuhr** [cc65/cc65#2022]
The following code:
        
```c
struct x { int a; char b; };
    
struct x f(void)
{
    struct x x = { 1, 2 };
    return x;   /* Returned in eax with high byte = junk */
}

int main(void)
{
    struct x x;
    x = f();    /* Overwrites x with 4 bytes */
    return 0;
} 
```

Looks like this after translation with "-Oirs -T":

```
; ---------------------------------------------------------------
; struct x __near__ f (void)
; ---------------------------------------------------------------

.segment        "CODE"

.proc   _f: near

.segment        "CODE"

;
; struct x x = { 1, 2 };
;
        jsr     decsp3
        ldy     #$02
L0002:  lda     M0001,y
        sta     (sp),y
        dey
        bpl     L0002
;
; return x;   /* Returned in eax with high byte = junk */
;
        jsr     ldeax0sp
;
; }
;
        jmp     incsp3
 
.segment        "RODATA"

M0001:
        .word   $0001
        .byte   $02
        
.endproc

; ---------------------------------------------------------------
; int __near__ main (void)
; ---------------------------------------------------------------

.segment        "CODE"

.proc   _main: near

.segment        "CODE"

;
; x = f();    /* Overwrites x with 4 bytes */
;
        jsr     decsp3
        jsr     _f
        jsr     steax0sp
;
; return 0;
;
        ldx     #$00
        txa
;
; }
;
        jmp     incsp3
 
.endproc
```

As you can see, the struct is 3 bytes in size but is handled by eax which causes one additional byte to be read/written. The write might cause erratic behavior or program crashes.

**Comment by bbbradsmith** [comment]
According to the documentation [cc65 cannot return structs by value](https://github.com/cc65/cc65/blob/805e98a7aa6fbd2b419de5192163f7d47c1f3beb/doc/cc65.sgml#L809), but apparently this is not true?

Was this feature (including the noted bug) added at some point without documenting it? Is there a past version which rejects any struct return with an error?

**Comment by mrdudz** [comment]
Unfortunately there was a time when feature additions were accepted without requiring to update documentation accordingly - i think you are correct in all points (however there are still certain restrictions regarding the size of the structs that work when passing into and returning from a function. not documented of course ;/)

**Comment by bbbradsmith** [comment]
I think this capability may have been added in #1102

**Comment by bbbradsmith** [comment]
I created PR #2072 which simply disables the problematic 3-byte case. I also documented the feature, and added a simple test case for it.

**Comment by kugelfuhr** [comment]
> According to the documentation [cc65 cannot return structs by value](https://github.com/cc65/cc65/blob/805e98a7aa6fbd2b419de5192163f7d47c1f3beb/doc/cc65.sgml#L809), but apparently this is not true?
> 
> Was this feature (including the noted bug) added at some point without documenting it? Is there a past version which rejects any struct return with an error?

cc65 has a `div()` function in stdlib.h for ages. `div()` returns a struct. So it wasn't exactly a secret that cc65 accepts struct returns. The paragraph in the docs is probably old and should be fixed.

**Comment by bbbradsmith** [comment]
[21 years??](https://github.com/cc65/cc65/commit/55baa52735573a3754d7f7b23535f781502fa1f1) That's pretty old. :S

Anyway, my pull request does include an update to the doc with a note about the supported struct sizes.

**Comment by rofl0r** [comment]
rather than just documenting it, i'd prefer if the compiler errors out on returning unsupported struct sizes, so a user which didn't read that paragraph doesn't get surprisingly broken binaries.

**Comment by mrdudz** [comment]
> rather than just documenting it, i'd prefer if the compiler errors out on returning unsupported struct sizes, so a user which didn't read that paragraph doesn't get surprisingly broken binaries.

I agree! But isnt that the case now? @bbbradsmith ?

**Comment by kugelfuhr** [comment]
Just for the sake of completeness: 66ecc0e52cc61e5969efc22c0045a739c7f6f9f3 added the erroneous code, and 9f67b45ea0abd003a42b241d86bc763ef51b60bc actually introduced the problem by using this code.

I'm not sure if disabling 3 byte structs completely is a good idea, since the comments say "use memcpy for larger structs". So disabling 3 byte structs would mean that all structs work for passing parameters with just this exception.

**Comment by mrdudz** [comment]
Another idea: for the time beeing, couldnt it use memcpy also for 3 byte structs? (perhaps emit a warning that says that it does this) Thats of course terribly inefficient - but i'd prefer "working" over "broken" in any case :)

**Comment by kugelfuhr** [comment]
> Another idea: for the time beeing, couldnt it use memcpy also for 3 byte structs? (perhaps emit a warning that says that it does this) Thats of course terribly inefficient - but i'd prefer "working" over "broken" in any case :)

This is how it worked before the cited changes.

**Comment by mrdudz** [comment]
doh. I knew why i push ppl to provide tests :(

**Comment by bbbradsmith** [comment]
> rather than just documenting it, i'd prefer if the compiler errors out on returning unsupported struct sizes, so a user which didn't read that paragraph doesn't get surprisingly broken binaries.
That's exactly what I did in #2079.



> doh. I knew why i push ppl to provide tests :(
I provided a test in #2079. I recommend re-insating it for now, but I left a clear place in that test to add the 3-byte struct case when it has a revised safe implementation.

**Comment by mrdudz** [comment]
I was referring to the commits @kugelfuhr referred to, not yours - yours was fine :)

**Comment by mrdudz** [comment]
closing, i dont think there is an open issue here
