### ISSUE TITLE
cc65: Regression in diagnostic output

### ISSUE THREAD

**Issue by kugelfuhr** [cc65/cc65#2023]
The latest compiler version doesn't handle error recovery as gracefully as version 2.18. For this one liner

```c
void f(_Bool b);
```

the version 2.18 compiler recovers from the error after a few error messages. The current git version repeatedly outputs "Error: Mixed declarations and code are not supported in cc65" until the maximum error count is reached.

**Comment by acqn** [comment]
The example code in recent revisions of cc65 results in more diagnostic messages than before, but no more the infinite "Error: Mixed declarations and code are not supported in cc65" messages. I think this means that the issue goes away. Perhaps some of my commits fixed it by chance.

**Comment by kugelfuhr** [comment]
Well, the current cc65 version outputs:

```
test.c:1: Error: Type specifier missing
test.c:1: Warning: Implicit 'int' is an obsolete feature
test.c:1: Error: ')' expected
test.c:1: Error: Expected ',' or ';' after top level declarator
test.c:1: Warning: Implicit 'int' is an obsolete feature
test.c:1: Error: ';' expected
test.c:1: Error: Identifier expected
test.c:1: Warning: Implicit 'int' is an obsolete feature
5 errors and 3 warnings generated.
```

which is quite a lot of noise. This is what gcc outputs (with "_Bool" replaced by "foo" since gcc does of course know _Bool):

```
test.c:1:8: error: unknown type name ‘foo’
    1 | void f(foo b);
      |        ^~~
```

But you're right in that the "Error: Mixed declarations and code are not supported in cc65" is gone.

**Comment by acqn** [comment]
With PR #2272 you can now get just:
```
test.c:1: Error: Unknown type name '_Bool'
1 errors and 0 warnings generated.
```
