### ISSUE TITLE
using "static" to declare forward reference doesnt work

### ISSUE THREAD

**Issue by mrdudz** [cc65/cc65#204]
this basically describes what should happen: http://infocenter.arm.com/help/topic/com.arm.doc.faqs/ka9772.html

in my code i have something like this:

``` C
 typedef struct _DIRMENU
 {
     char *name;
     struct _DIRMENU *dest;
 } DIRMENU; 

 extern DIRMENU rmenu; /* <-- this currently "works" but gives a warning, GCC gives an error */
 /* static DIRMENU rmenu; */ /* <-- this SHOULD work, but gives an error in cc65 */

 static DIRMENU lmenu = {
     "left",
     &rmenu
 };

 static DIRMENU rmenu = {
     "right",
     &lmenu
 };
```

**Comment by greg-king5** [comment]
One part of cc65 recognizes that the second definition is a duplicate; it doesn't put the name into the symbol table twice.  But, another part doesn't notice it; cc65 generates an assembly object each time that it sees a definition.

ca65 hates to see two objects with the same name.

A second work-around:
Declare the object as `extern` both times.  cc65 won't show a message (and, gcc will give only a warning).
But, both work-arounds have the side-effect of making the object be public (exported).
