### ISSUE TITLE
imports in o65 format config lead to "ld65: Internal Error: Invalid address size: 0"

### ISSUE THREAD

**Issue by ghost** [cc65/cc65#2044]
ld65 returns an internal error when using the "import" directive in the o65 format section in the config file.

Here's a tarball with the repro case.
[repro.tar.gz](https://github.com/cc65/cc65/files/11109936/repro.tar.gz)

```
$ make
ca65 -o test.o test.s
ld65 -m test.map -C firmware.cfg -o test.o65 test.o
ld65: Internal Error: Invalid address size: 0
make: *** [Makefile:7: test.o65] Error 1
```

**Comment by mrdudz** [comment]
closed via #2497
