### ISSUE TITLE
Error in running "make install"

### ISSUE THREAD

**Issue by wyatt-wong** [cc65/cc65#2061]
I run `make` to build the source but then when I run `make install`, I got the following errors:

wyattwong@WyattsMacBookPro cc65 % make install
BUILD_ID: Git e5f4ca6b8
install -d /bin
install: chmod 755 /bin: Operation not permitted
install ../bin/* /bin
install: /bin/ar65: Operation not permitted
make[1]: *** [Makefile:115: install] Error 71
make: *** [Makefile:6: install] Error 2
wyattwong@WyattsMacBookPro cc65 % 

What am I missing ?

**Comment by wyatt-wong** [comment]
> I run `make` to build the source but then when I run `make install`, I got the following errors:
> 
> wyattwong@WyattsMacBookPro cc65 % make install BUILD_ID: Git [e5f4ca6](https://github.com/cc65/cc65/commit/e5f4ca6b898bf581751901fd5792764adfb7730a) install -d /bin install: chmod 755 /bin: Operation not permitted install ../bin/* /bin install: /bin/ar65: Operation not permitted make[1]: *** [Makefile:115: install] Error 71 make: *** [Makefile:6: install] Error 2 wyattwong@WyattsMacBookPro cc65 %
> 
> What am I missing ?

I found out the answer from [https://github.com/cc65/wiki/wiki/OS-X](url). However I found the Getting Started URL [http://cc65.github.io/cc65/getting-started.html](url) is incorrect. The new URL should be [https://cc65.github.io//getting-started.html](url). Unfortunately I have no idea how to create a pull request to update the link in [https://github.com/cc65/wiki/wiki/OS-X](url)

**Comment by mrdudz** [comment]
I fixed the link... the way github wiki works is a bit annoying, you cant make it editable for the public.

Thanks!

**Comment by rofl0r** [comment]
> install -d /bin

this looks wrong, i'm pretty sure MacOS uses another prefix. maybe the getting started for OSX should mention to run make with the correct prefix (whatever it is).
btw, the getting started for linux mentions to run `make avail` instead of `make install` which is probably not what the average user wants.

**Comment by wyatt-wong** [comment]
> > install -d /bin
> 
> this looks wrong, i'm pretty sure MacOS uses another prefix. maybe the getting started for OSX should mention to run make with the correct prefix (whatever it is). btw, the getting started for linux mentions to run `make avail` instead of `make install` which is probably not what the average user wants.

Yes. But according to [https://cc65.github.io/getting-started.html](url), the correct command is `sudo make avail`. I have to run `sudo make unavail` first in order to removes the existing cc65 before executing `sudo make avail`

However, the usual command to install should be `make install` (without sudo), I have no idea while for Linux (should also mentioned macOS) use the command `sudo make avail`

**Comment by rofl0r** [comment]
make install always needs to be done with root privileges for a system-wide install, which is the default.

**Comment by wyatt-wong** [comment]
> make install always needs to be done with root privileges for a system-wide install, which is the default.

I tried with `sudo make install` and it also failed. And in my past experiences, I built and installed more than 10 packages in macOS and none of them require using `sudo` to perform a `make install`

You may follow the steps below in macOS and see if you are able to perform it without any errors:

[https://cc65.github.io/getting-started.html](url)

'git clone https://github.com/cc65/cc65.git'
'cd cc65'
'make'

'sudo make install'
