### ISSUE TITLE
ca65: support BRK with optional immediate byte

### ISSUE THREAD

**Issue by vrubleg** [cc65/cc65#2064]
In 6502, `BRK` actually behaves like a two-byte instruction. It starts execution of the IRQ vector, but the following `RTI` will return to [one byte after](http://www.6502.org/tutorials/6502opcodes.html#BRK) `BRK`.

I propose to add an optional argument for BRK.

```
BRK    ; bytes: 00
BRK #1 ; bytes: 00 01
```

It won't break existing code, but will allow to conveniently pass an argument that could be read from IRQ handler if needed.

If you are OK about this idea, I can make a PR with required changes.

**Comment by mrdudz** [comment]
wasnt that already added a while ago? :)

**Comment by vrubleg** [comment]
Oh, probably I need to update my local version. I'll check it this evening after work and close this ticket if it is already implemented.

**Comment by vrubleg** [comment]
Oh, I see, it was added quite recently.

The only thing, it would probably be more logical if it were required to use this syntax:
```
brk #$60
```
And this should not be allowed because it is semantically wrong (and generates the same output):
```
brk $60
```

**Comment by mrdudz** [comment]
Hihi we had the exact same discussion before

**Comment by bbbradsmith** [comment]
Well, that's why I added additional support for # while I was generalizing the 65816 implementation to all CPU targets. It's clear that many people prefer it with #. It's also clear that many prefer it without. See #2010 for more detailed information.
