### ISSUE TITLE
ca65 exits with internal error instead of giving a proper error message when a non existing label is used as .constructor

### ISSUE THREAD

**Issue by mrdudz** [cc65/cc65#212]
what the topic says, test.s:
```assembler
        .constructor foo
bar: rts
```

 $ ./bin/cl65 -o test.prg test.s
ca65: Precondition violated: Index < C->Count, file `common/coll.h', line 155

**Comment by mckaygerhard** [comment]
since are happend this? from wat commit? for programers can help need MANY more info

**Comment by greg-king5** [comment]
That bug has existed since 2011-08-18 (commit c52916f4).  Fortunately, it is a simple bug (the line number for the error message is saved into the wrong place).
