### ISSUE TITLE
Malware in Windows Snapshot

### ISSUE THREAD

**Issue by thred** [cc65/cc65#2121]
According to Windows Defender, the most recent Windows Snapshot contains Win32/Wacatac.B!ml trojan.

The exact name is "Trojan:Win32/Wacatac.B!ml" and it is contained in the "ld65.exe".

**Comment by mrdudz** [comment]
This is most definitely a false positive - please upload it to virustotal.com and have a look.

**Comment by thred** [comment]
Even if it is a false positive, Windows put's the file into quarantine, everytime I try to download it or to extract it. Is there someone else, that can confirm this? I'm using Windows 10 with the most recent version of Windows Defender ...

**Comment by mrdudz** [comment]
My usual recommendation is: disable the heuristics of the scanner. You can probably also make exceptions for that file somehow (but i dont know how, i am not using Windows)

**Comment by thred** [comment]
VirusTotal is, in fact, reporting issues: https://www.virustotal.com/gui/file/7e337e1318d3f4c2902f8718d4d85d92a61d78a378753d2c8d21aa98e1658be5/detection

**Comment by vrubleg** [comment]
It's a false-positive. AV software often make mistakes. It's an issue on their side, not cc65.

**Comment by thred** [comment]
I don't want to compain, you are all doing a great job and you are helping me to spend my sparetime with something really amazing like coding a 40 year old computer. I'm just concerned.
While not having a lot experience with C coding/compiling (despite of playing around with my C64), I still have managed to compile cc65 with MinGW-w64 ... wasn't that difficult since this project is well maintained and easy to build. 
My observation is that the executables are smaller, but this depends on compiler settings and the version of gcc and other things. And they do not cause any issues or false-positives (see https://www.virustotal.com/gui/file/6276e47d3d2c7e9c67d03fed6a925aa61970b820256c94da49df3dbc2c0dfb5e). As you are sure, that this is a false positive, I will close this issue, now.
