### ISSUE TITLE
ca65: Unnamed labels should allow to use @

### ISSUE THREAD

**Issue by vrubleg** [cc65/cc65#2128]
I propose to allow optional `.LOCALCHAR` (`@` by default) in unnamed labels, just to make them a bit more visible. Also, the `:-` and `:+` could have `@-` and `@+` as more visible synonyms, or even `@<` and `@>` that is even more noticeable.

For example, now:

```
:	BIT PPU_STATUS
	BPL :-
```

After the change:

```
@:	BIT PPU_STATUS
	BPL @<
```

**Comment by bbbradsmith** [comment]
I think the idea of allowing `@:` is not a bad one, but I had other concerns which I left on the associated PR. Quoting them here so that they aren't lost from the discussion.

From [my comment on the PR](https://github.com/cc65/cc65/pull/2132#issuecomment-1682523476):
> I don't think adding new aliases `<` and `>` for `-` and `+` have the same utility, and also they should not be special case for `@:` only. Either we should have them for both `:` and `@` or neither. (My vote is neither.)
> 
> Another question I have is whether `@-` searches the preceding local scope for _any_ label beginning with `@`, or whether it only includes `@:` or does it also include `:`?
> 
> I think intuitively I would expect `@-` to include all `@` labels, anonymous or not, and exclude the anonymous `:` that doesn't start with `@`, and correspondingly `:-` should include only `:` as it does currently, and not attach to `@:` as well. What does this PR do for these cases?
