### ISSUE TITLE
[ca65] Impossible to use .cpu in ".byt"

### ISSUE THREAD

**Issue by jedeoric** [cc65/cc65#2136]
Hello,

I would like to add cpu type into a binary header : https://github.com/cc65/cc65/blob/master/libsrc/telestrat/orixhdr.s#L25

In that case, i am trying this : 

` .byte   .cpu                   ; Cpu type`

In that case, for any cpu value from commande line, this byte is always equal to 2

cl65 -ttelestrat --cpu 65C02 hello.c -> value in the header : 2
cl65 -ttelestrat --cpu 6502 hello.c -> value in the header : 2
cl65 -ttelestrat --cpu 65816 hello.c -> value in the header : 2

I don't see what i am missing...

I think that .cpu is the wrong way to do that, because .cpu is already built when telestrat.lib is generated, and cpu is known at link stage, but i don't see others tricks to do that ( except using an external program to set the right value.)

**Comment by mrdudz** [comment]
did you find the solution? :)
