### ISSUE TITLE
cc65: Maximum parameter size is not checked for variadic functions

### ISSUE THREAD

**Issue by kugelfuhr** [cc65/cc65#2144]
The compiler generates invalid assembler code if a variadic function is called with a total parameter size > 255:

```C
void a(...) {}

void b()
{
    a(1L, 1L, 1L, 1L, 1L, 1L, 1L, 1L, 1L, 1L, 1L, 1L, 1L, 1L, 1L, 1L,
      1L, 1L, 1L, 1L, 1L, 1L, 1L, 1L, 1L, 1L, 1L, 1L, 1L, 1L, 1L, 1L,
      1L, 1L, 1L, 1L, 1L, 1L, 1L, 1L, 1L, 1L, 1L, 1L, 1L, 1L, 1L, 1L,
      1L, 1L, 1L, 1L, 1L, 1L, 1L, 1L, 1L, 1L, 1L, 1L, 1L, 1L, 1L, 1L,
      1L, 1L, 1L, 1L, 1L, 1L, 1L, 1L, 1L, 1L, 1L, 1L, 1L, 1L, 1L, 1L);
}
```

This generates

```
        ldy     #$140           ; <==
        jsr     _a
        rts
```

in the assembler code. 

While it is currently quite unlikely that anybody runs into this problem, it may become less unlikely with #2127.

**Comment by acqn** [comment]
>While it is currently quite unlikely that anybody runs into this problem, it may become less unlikely with https://github.com/cc65/cc65/issues/2127.

It's likely that such large structs will be accessed via pointers under the hood.
