### ISSUE TITLE
Confusing errors with mixed declarations and code

### ISSUE THREAD

**Issue by clbr** [cc65/cc65#216]
```
void foo() {
        int a;
        a = 5;
        int b;
}

produces

foo.c(4): Error: Expression expected
foo.c(4): Warning: Statement has no effect
foo.c(4): Error: `;' expected
foo.c(4): Error: Undefined symbol: `b'
foo.c(4): Warning: Statement has no effect
```

It does not claim full C99 support, but it would be nice to have a clearer warning, like gcc's "ISO C90 forbids mixed declarations and code". The current warnings make it really unclear what is the problem.

**Comment by spiro-trikaliotis** [comment]
Hello,

* On Mon, Oct 05, 2015 at 06:54:52AM -0700 clbr wrote:
> void foo() {
>         int a;
>         a = 5;
>         int b;
> }
> 
> produces
> 
> foo.c(4): Error: Expression expected
> foo.c(4): Warning: Statement has no effect
> foo.c(4): Error: `;' expected
> foo.c(4): Error: Undefined symbol: `b'
> foo.c(4): Warning: Statement has no effect
> 
> It does not claim full C99 support, but it would be nice to have a clearer
> warning, like gcc's "ISO C90 forbids mixed declarations and code". The current
> warnings make it really unclear what is the problem.

The problem with a warning like the one from gcc: In order to be able to
issue such a warning, the compiler has to understand that construct -
that is, it must support the c99 way of declaring variables.

If someone extends the compiler to accept this, there is not that much
reason why the warning should be emitted at all anymore. For gcc, it is
different, as it tries to teach the user the differences between these
versions to allow him to create programs that use only features of one
language variant. I doubt anyone will use cc65 for this, though.

Regards,
Spiro.

-- 
Spiro R. Trikaliotis
http://www.trikaliotis.net/

**Comment by oliverschmidt** [comment]
@spiro-trikaliotis: Thanks for the explanation.

I fully agree with Spiro and presume it's okay to have this one closed.

**Comment by GeekOnSkates** [comment]
Hey guys, I know this is an old issue, and it sounds you have a significantly deeper understanding of how things work under the hood, but what exactly does this jumbled mess of errors mean to us mere mortals? :)

I'm getting it from this:

`#include <stdio.h>

int main() {
    printf("This works fine.\n");
    char x = getchar();
    printf("You typed %d!\n", x);   // This gives exactly the same errors/warnings/Mumbo McJumbo :)
    return 0;
}
`

AFAIK there's nothing particularly incorrect or invalid about this code, at least not from a 2019 GCC perspective.  Do all variables have to be global or something?  Static maybe?  To those of us who haven't started contributing to the project yet, the errors are kind of logic-defying nonsense.

But don't get me wrong - I think it's totally AWESOME that this program exists at all, and I really appreciate all your hard work on it.  Yes I find weirdisms like this frustrating, but thanks for all you do.  Just the fact that I can even USE any variant of C to code for these 8-bit systems is AMAZING! :)

**Comment by groessler** [comment]
Please read up differences btw. c89 and c99....

**Comment by oliverschmidt** [comment]
> AFAIK there's nothing particularly incorrect or invalid about this code [...]

As @groessler already hinted at, this assumption is unfortunately wrong. Read e.g. https://stackoverflow.com/questions/6488503/c89-mixing-variable-declarations-and-code

One way to deal with it is to introduce additional blocks, like I did e.g. at https://github.com/cc65/ip65/blob/master/apps/wget65.c#L499-L510
