### ISSUE TITLE
cc65: Compiler accepts invalid variable declarations (regression)

### ISSUE THREAD

**Issue by kugelfuhr** [cc65/cc65#2162]
The following - invalid - code is accepted by the compiler:

```C
int main()
{
    extern  int i;
    int i = 42;
    return i;
}
```

First, there should be a diagnostic because the declaration is invalid. Next, as can be seen from the assembly, the compiler omits the initialization of i completely and treats i as an imported variable, so the compiler will not even create code that corresponds to what the programmer might expect.

Please note that this is a regression. Version 2.18 of the compiler didn't accept the input:

```
test.c(4): Error: Multiple definition for 'i'
``` 

BTW, this is what gcc outputs:

```
test.c: In function ‘main’:
test.c:4:9: error: declaration of ‘i’ with no linkage follows extern declaration
    4 |     int i = 42;
      |         ^
test.c:3:17: note: previous declaration of ‘i’ was here
    3 |     extern  int i;
      |                 ^
```

**Comment by polluks** [comment]
FYI
ISO/IEC 9899:1999 (E), 6.2.2p7 "Linkages of identifiers": "If, within
a translation unit, the same identifier appears with both internal and
external linkage, the behavior is undefined."

**Comment by kugelfuhr** [comment]
> Looks like #2111

No, this one is different. The definition in line 4 has no linkage. So it's not external vs internal linkage but external vs no linkage. Which means that ISO/IEC 9899:1999 (E), 6.2.2p7 does not apply.

**Comment by acqn** [comment]
Trickier case:

```c
static int i; // We do allow redeclaration of i as extern int
int main()
{
    extern int i; // So, should this prevent the following line from working?
    int i = 42;
    return i;
}
```
