### ISSUE TITLE
ser_get() issue on apple2

### ISSUE THREAD

**Issue by varna9000** [cc65/cc65#2165]
Hi, I'm struggling to get the below minimal example to work. It doesn't work both on real hardware and on Virtual ][ emulator (with file pipe serial emulation).

Using default SSC slot 2 doesn't work either. I'm able to send chars from apple2 to the other end, but I'm unable to receive chars into the apple2 i.e. `ser_get()` doesn't seem to work. Am I doing something wrong?

```
#include <stdlib.h>
#include <serial.h>
#include <apple2.h>
#include <stdio.h>
#include <conio.h>

  struct ser_params params = {
    SER_BAUD_1200,
    SER_BITS_8,
    SER_STOP_1,
    SER_PAR_NONE,
    SER_HS_HW
  };


void main(void)
{
  char Res, ch;

  ser_install(a2_ssc_ser);
  ser_apple2_slot(4);
  ser_open(&params);
 
    while (1){
      Res = ser_get(&ch);
      if (Res != SER_ERR_NO_DATA) {
        printf ("%c", ch);
        }
      if (kbhit())
        {
          ch=cgetc();
          ser_put(ch);
        }
    }
}
```

**Comment by polluks2** [comment]
Did you try samples/terminal.c?

**Comment by varna9000** [comment]
yes, but I just add the apple2 serial driver. i.e. I replace  `check ("ser_install", ser_install (ser_static_stddrv));`
with 
```
    check ("ser_install", ser_install (a2_ssc_ser));
    check ("ser_apple2_slot", ser_apple2_slot(4));
```
and include apple2.h on top.

It's the same result. I can send chars with ser_put() but can't receive anything with ser_get(). The serial card and connection are working fine because in BASIC after I do in#4 (card is in slot4) I can receive chars in BASIC just fine.

**Comment by colinleroy** [comment]
Can you show the other side of the code?

**Comment by varna9000** [comment]
@colinleroy There's no really code on the other side. In Virtual ][, I'm using [virtual serial with unix file pipes](https://www.virtualii.com/VirtualIIHelp/virtual_II_help.html). Alternatively, on real hardware, the SCC is hooked via null modem to my Macbook Pro, where I'm using [Serial2](https://www.decisivetactics.com/products/serial/) terminal to send/receive chars for testing. Both test yield same result - I can send chars from Apple2 but can't receive any.

**Comment by colinleroy** [comment]
On emulation : is your tty correctly setup when you echo... > /dev/ttyUSB0? Check with stty - F or an equivalent.
On real hardware, same question, and does your cable support hardware handshake?

**Comment by colinleroy** [comment]
Maybe give a look to https://github.com/colinleroy/a2tools, maybe it could help.
interesting code is in src/lib/simple_serial.c, mostly simple_serial_open, where there's the Apple 2 implementation and a posix implementation for the other side.
I remember getting the other side right was hard.

**Comment by varna9000** [comment]
The real hardware connection is fine. As I've described in my [comment here](https://github.com/cc65/cc65/issues/2165#issuecomment-1686852893) I can do bi-directional communication in Basic just fine, so cable is definitely ok. Null modem takes care of the handshake (apple2 handshakes with itself)

I've seen your a2tools code, but not in too much details. I'll have a good look again and revert here. Thanks!

**Comment by colinleroy** [comment]
If I remember correctly, when I did bidirectional communication in basic, the PC was set to 7n1, or something. I should have documented my difficulties more thoroughly...

**Comment by varna9000** [comment]
> Can you show the other side of the code?
> Also try at 9600bps, maybe.
> And, when it works using Basic, do you do PR#4 / IN#4? Do both ways work in Basic?
> What speed do you use in Basic? (with Ctrl-i)

yes, it works both ways. I'm using 1200bps, to be on the safe side. I have a small Basic program which receives strings and if I run it above 1200bps it is not working properly (missing chars)

**Comment by varna9000** [comment]
> If I remember correctly, when I did bidirectional communication in basic, the PC was set to 7n1, or something. And had to change to 8n1 once using cc65's driver. I should have documented my difficulties more thoroughly...

Yes, I remember something similar when I was using "screen" to log in via SSC. I had to set it to 7bit 1 stop bit , parity Space. I'll have to try this in the cc65 code.

**Comment by colinleroy** [comment]
> > If I remember correctly, when I did bidirectional communication in basic, the PC was set to 7n1, or something. And had to change to 8n1 once using cc65's driver. I should have documented my difficulties more thoroughly...
> 
> Yes, I remember something similar when I was using "screen" to log in via SSC. I had to set it to 7bit 1 stop bit , parity Space. I'll have to try this in the cc65 code. However, does this make sense if I'm sending just fine with 8n1?

No, not really. Btw just to be sure, what's your cc65 --version ?

**Comment by colinleroy** [comment]
FYI, I just copy-pasted your example code as-is, ran it and 
1) it fails at 1200bps (I receive data, but it's shitty, '~' instead of 'd' for example, even with the serial device at 1200bps, the ser2net at 1200bps, and MAME's serial settings at 1200bps.)
2) it works at 9600bps

![image](https://github.com/cc65/cc65/assets/1016317/69b93a35-ae81-4ef7-94b5-f18a075f30c2)

### about emulation
I've looked at Virtual]['s documentation and a few things come to mind:
"The options that can not be changed by the Apple II software are communications / printer mode and interrupt mode".
Do you have "Enable interrupts" checked ? You need to: the cc65 serial driver is irq-driven.

Finally, In the Mac's serial device options, I'd test to check "Force DSR input line to be on" and maybe CTS too. DSR is "Data Send Ready" and CTS is "Clear To Send"

### On real hardware
I didn't ask what your real hardware is? Mine is an Apple //c where the SSC has no hardware switch and everything is software-configurable. Hence, the cc65 driver can activate interrupts. If yours is different and you have an SSC card with DIP switches, you should configure it with interrupts enabled. That may be a good lead, because in BASIC, the ROM SSC driver doesn't do interrupts, as far as I know.

So I'd check three things:
a) 9600bps
b) enable interrupts via DIP switch
c) the DSR/CTS signal
HTH!

**Comment by colinleroy** [comment]
> Ok, so it's one big facepalm for me :)
> 
> The real hardware now works fine (even on 1200bps). Switch 2-6 on SSC was OFF (i.e. interrupts were off), when I switched it on, receiving is now working with both my code and the terminal.c example.
> So I had left it off, assuming if it works in Basic, it should work with cc65 too. I have Apple IIe clone (not enhanced), which apparently handles interrupts because now it works.

Good news! 
 
> The emulator is still a mystery since I have switched the checkbox for using interrupts (it was recommended in the help page) also I've checked all boxes for DTR DSR CRS (again as recommended by the manual)

Yeah, serial emulation is a pain in the bottom indeed. I'm using MAME on Linux, which does serial emulation via TCP, so I need a ser2net running, and a tty2tty kernel module to create dummy serial devices, and all of them have to be configured correctly for anything to go through :laughing: 
 
> Having in mind the above, does this mean that cc65 serial code won't work on Apple II and II+ since they don't handle interrupts? I have a II+ clone and will check in the next few days.

Indeed. It could be nice to have a non-interrupt-driven serial driver, but it would probably lose bytes all over the place as soon as you try to do anything else than receive bytes in a loop.

> Thank you for taking your time to help me on this, I really appreciate it!

You're welcome!

**Comment by colinleroy** [comment]
> The real hardware now works fine (even on 1200bps). 

By the way, using C you can safely push to 9600bps **if** your hardware cable / your emulation chain safely handles flow control **or** if you buffer and batch input.

Only thing not working for me is scrolling the screen while receiving, on the emulator. On bare metal it works flawlessly.

(I'm trying hard to push things to 19.2kbps but so far I have no success, and the deeper I dive the more I think I won't be able to).

**Comment by varna9000** [comment]
I have to compile your app and try it on my hardware. Since I got the comm working now, I'll explore all options and make a small app myself :)
I'll close this now. Thanks again!

**Comment by oliverschmidt** [comment]
> Switch SW2-6 controls forwarding of interrupts to Apple II. Since Apple II and II+ do not handle interrupts, set SW2-6 to OFF.

You misinterpret that that statement. It was written at a time when there were no other Apple II's than the ][ and ][+. Interrupt handling simply became only later "a thing" on the Apple II. The way the cc65 serial driver uses interrupts works on all Apple II's.
