### ISSUE TITLE
Commit 2431fb7d85b8aa74153e6e8343bb577e28cc8832 breaks AppleSingle binaries

### ISSUE THREAD

**Issue by colinleroy** [cc65/cc65#2179]
Maybe this is an issue for AppleCommander... But 2431fb7d85b8aa74153e6e8343bb577e28cc8832 from PR #2163 breaks copying AppleSingle binaries to disk images:
```
java.lang.ArrayIndexOutOfBoundsException: arraycopy: last source index 10928 out of bounds for byte[10899]
	at java.base/java.lang.System.arraycopy(Native Method)
	at io.github.applecommander.applesingle.AppleSingleReader.readAt(AppleSingleReader.java:32)
	at io.github.applecommander.applesingle.Entry.create(Entry.java:29)
	at io.github.applecommander.applesingle.AppleSingle.asEntries(AppleSingle.java:188)
	at io.github.applecommander.applesingle.AppleSingle.asEntries(AppleSingle.java:176)
	at io.github.applecommander.applesingle.AppleSingle.read(AppleSingle.java:159)
	at io.github.applecommander.applesingle.AppleSingle.read(AppleSingle.java:147)
	at com.webcodepro.applecommander.ui.ac.putAppleSingle(ac.java:374)
	at com.webcodepro.applecommander.ui.ac.putAppleSingle(ac.java:366)
	at com.webcodepro.applecommander.ui.ac.main(ac.java:168)
	at java.base/jdk.internal.reflect.DirectMethodHandleAccessor.invoke(DirectMethodHandleAccessor.java:104)
	at java.base/java.lang.reflect.Method.invoke(Method.java:577)
	at org.springframework.boot.loader.MainMethodRunner.run(MainMethodRunner.java:49)
	at org.springframework.boot.loader.Launcher.launch(Launcher.java:108)
	at org.springframework.boot.loader.Launcher.launch(Launcher.java:58)
	at org.springframework.boot.loader.JarLauncher.main(JarLauncher.java:88)
```
@oliverschmidt, what do you think? is #2163 wrong for Apple2 or is AppleCommander expecting things it shouldn't ?
Thanks! 

PS: The binaries generated with 2431fb7d85b8aa74153e6e8343bb577e28cc8832 crash on real hardware after being transferred over serial (a tried and working process for me). They're also 156 bytes bigger.

**Comment by bbbradsmith** [comment]
Could you give more information about what command you are running here on what inputs?

**Comment by colinleroy** [comment]
Applesingle is the format of apple 2 binaries. You generate them with cl65 - o program.bin
And put it on a disk image with AppleCommander with
java - jar applecommander.jar - as floppy.dsk program < program.bin

**Comment by colinleroy** [comment]
But mostly, the generated binary itself is wrong since that change.

**Comment by bbbradsmith** [comment]
Can you provide a link to a sample program to be compiled into a program.bin?

**Comment by colinleroy** [comment]
Here's a reproducer:
```
#Build a sample program
cd cc65/samples/apple2
cl65 -t apple2 --start-addr 0x4000 hgrshow.c -o hgrshow

#Move it to /tmp
cp hgrshow /tmp
cp *.hgr /tmp
cd /tmp

#Get a basic floppy image
wget https://github.com/colinleroy/a2tools/raw/master/disks/basic-empty.dsk

#Get appleCommander
wget https://github.com/AppleCommander/AppleCommander/releases/download/1.8.0/AppleCommander-ac-1.8.0.jar

#Add the program to the disk (this is where it fails with the aforementioned commit)
java -jar AppleCommander-ac-1.8.0.jar -as basic-empty.dsk hgrshow < hgrshow

#Add a picture to the disk
java -jar AppleCommander-ac-1.8.0.jar -p basic-empty.dsk astronaut.hgr bin 0x2000 < astronaut.hgr

#Install mame
sudo apt-install mame

#Get an apple2 ROM (google "mame rom apple2c0.zip")

#Put it in place
mkdir ~/mame/roms/
mv ~/Downloads/apple2c0.zip ~/mame/roms/

#Launch the emulator
mame apple2c0 -window -flop1 basic-empty.dsk -resolution 560x384
```

Once booted, choose "BASIC" from the menu, then type BRUN HGRSHOW.

If you need to do multiple tests, drop the floppy image and refetch it, multiple calls to AppleCommander puts multiple copies of the file on the image.

**Comment by bbbradsmith** [comment]
Okay, so the difference between INIT type=bss and type=rw is that the bss doesn't emit bytes to the output, however there is no warning or error about this. Curiously if you generate a map file (-m) it's identical between the two.

Apologies for this. I had belived it was adding the reserved space to the ouput because of the lack of error.

I feel the header change was still correct, but it's exposed a problem with the linker. It should be reserving that space because it's explicitly in an output MEMORY region. So, I think the fix is a change to the linker.

Alternatively, if we feel that the linker should _not_ be able to emit bss 0 bytes to a file, in that case the headers should be reverted, but in this case the linker must give an error for this case instead of allowing it as it currently does.

I'll see if I can prepare a PR supporting the former option.

**Comment by bbbradsmith** [comment]
Hrm, while the linker changes are simple, reading the docs I don't think I can take either option without violating the way it's documented: https://cc65.github.io/doc/ld65.html

It specifically gives an example where "RAM" memory regions are not given an explicit file="" and instead type=bss on all its included segments prevents them from taking up space in the file.

I think this is very error prone and confusing behaviour, but unless we want to declare that example invalid, I can neither change bss to be able to output to a file, nor can I change bss to give an error if placed in a MEMORY region that outputs to a file. :(

Guess I will have to walk the CFG changes back then for the apple 2 targets.

**Comment by bbbradsmith** [comment]
Okay I submitted the PR correcting my mistake.

**Comment by colinleroy** [comment]
Thanks, this is fixed for apple2 :)

**Comment by oliverschmidt** [comment]
@colinleroy: Thanks for providing the bug report!
