### ISSUE TITLE
Windows defender deletes ld65.exe from Windows Snapshot because of security issues/trojan

### ISSUE THREAD

**Issue by unbisss** [cc65/cc65#2184]
Its the first time that Im using github. Im also not sure if this goes under this topic.
Now I downloaded the Windows Snapshot at Github that shows this link: https://sourceforge.net/projects/cc65/files/cc65-snapshot-win32.zip
Compiling my project I noticed that ld65.exe was deleted. Later I tried again and saw that Windows defender was deleting it because of security issue. As workaround Im using an older version. So either the link should be changed or the download itself. Thanks.

**Comment by polluks2** [comment]
You are welcome! Just exclude this false positive
https://support.surfshark.com/hc/en-us/articles/4764589001746-How-to-bypass-the-Windows-Defender-false-alarm-

**Comment by mrdudz** [comment]
> So either the link should be changed or the download itself.

Sorry, no. There is nothing wrong with the download - its the broken AV that needs fixing.

**Comment by unbisss** [comment]
Thank you for the fast answer and for the Link how to exclude.
