### ISSUE TITLE
Wrong array indexing when index comes from bit-field

### ISSUE THREAD

**Issue by wendelscardua** [cc65/cc65#2186]
When debugging some weird behavior on a NES game I was making, I found this issue; then I've written this short `sim65`-targeted code which demonstrates the problem:

```c
#include <stdio.h>

typedef struct {
  char flag : 1;
  char index : 7;
} weird_type;

const char array[] = { '6', '5', '0', '2' };

weird_type data;

int main() {
  data.flag = 1;

  data.index = 0;
  putchar(array[data.index]);

  data.index = 1;
  putchar(array[data.index]);
  
  return 0;
}

```

Running this code I get:

```
$ cl65 test.c -t sim6502 -o test; sim65 test
52
```

... when the expected output is `65`.

Looking at the assembly code, apparently almost everything dealing with the bit-fields work correctly (although strangely it places the `flag` at the end of the byte instead of at the beginning).

But when the `.index` field is used as an array index, the assembly code is just loading the whole `data` byte on `Y` and using it to index on `array` (i.e. `ldy _data; lda _array, Y`). Because of the flag at the end of the byte, this is basically the same as accessing the position `2 * data.index + data.flag`. 

I tried this with and without optimizations, both on the version I had before ( `cc65 V2.19 - Git c2e593772` ) and the current master I just installed (`cc65 V2.19 - Git 043590c97`)

**Comment by kugelfuhr** [comment]
```diff
diff --git a/src/cc65/expr.c b/src/cc65/expr.c
index 9460569ed..82c5ddc92 100644
--- a/src/cc65/expr.c
+++ b/src/cc65/expr.c
@@ -2968,8 +2968,9 @@ static void parseadd (ExprDesc* Expr, int DoArrayRef)
             }
 
             if (!AddDone) {
-                if (ED_IsLocQuasiConst (&Expr2) &&
-                    rscale == 1                 &&
+                if (ED_IsLocQuasiConst (&Expr2)  &&
+                    !IsTypeBitField (Expr2.Type) &&
+                    rscale == 1                  &&
                     CheckedSizeOf (rhst) == SIZEOF_CHAR) {
                     /* Change the order back */
                     RemoveCode (&Mark);
```

**Comment by kugelfuhr** [comment]
Might work, but do your own checks.

**Comment by acqn** [comment]
Other codegen optimizations involving `ED_IsLocConst` / `ED_IsLocQuasiConst` could be affected as well....

**Comment by kugelfuhr** [comment]
It might be useful to refactor the `parseadd` function. It has 300 lines and is quite complex. No wonder this problem slipped through.
