### ISSUE TITLE
[cc65] asm expression is incorrectly named 'statement' in the doc

### ISSUE THREAD

**Issue by acqn** [cc65/cc65#2191]
The document (https://cc65.github.io/doc/cc65.html#s5) says:
>The compiler allows to insert assembler statements into the output file. The syntax is
>`            asm [optional volatile] (<string literal>[, optional parameters]) ;`
>or
>`            __asm__ [optional volatile] (<string literal>[, optional parameters]) ;`

which suggests that the `asm` extension can only be used as a single-line statement that is terminated with a semicolon.

However, the document says not so far from the above:

>There are three pseudo variables named __A__, __AX__ and __EAX__. They all refer to the primary register that is used by the compiler >to evaluate expressions or return function results. __A__ is of type unsigned char, __AX__ is of type unsigned int and __EAX__ of type >long unsigned int respectively. The pseudo variables may be used as lvalue and rvalue as every other variable. They are most useful >together with short sequences of assembler code. For example, the macro
```
            #define hi(x)           \
                (__AX__ = (x),      \
                 asm ("txa"),       \
                 asm ("ldx #$00"),  \
                 __AX__)
```
>will give the high byte of any unsigned value.
which uses `asm()` in a (nested) comma expression, which suggests `asm()` itself is also an expression, which clearly is not-a-statement and violates the syntax required on the top.

Similarly, later on (https://cc65.github.io/doc/cc65.html#s9) the document tells about the same syntax
>`            asm [optional volatile] (<string literal>[, optional parameters]) ;`
>or
>`            __asm__ [optional volatile] (<string literal>[, optional parameters]) ;`

But then immediately
>Please note that the result of an inline assembler expression is always of type void.

So, is `asm()` actually supposed to be an expression therefore we can do:
```c
asm("duh") ;                             // not limited to this form
pros++, asm("what"), foo(), asm("well"); // probably the original motivation to implement it as an expression

// why not?
if (asm("cool"), 1) {
    int i = ((void)asm("stuff"), 1);
    cond ? asm("foo") : asm("bar");
}
```
?

**Comment by kugelfuhr** [comment]
I'm not sure that I understand the problem. The docs talk about "expression" and "statement", but this is obviously a sloppiness and "statement" is wrong, while "expression" is correct.

Your last example (with correct assembler instructions inserted) is translated by the compiler, so the actual implementation supports exactly what is described in the docs, once you fix the wording from "statement" to expression.

But as said above, I don't understand fully what you are aiming for. Is this just a clarification? Then yes, you're right. The docs should be fixed and no changes to the code are necessary.

**Comment by acqn** [comment]
> But as said above, I don't understand fully what you are aiming for. Is this just a clarification? Then yes, you're right. The docs should be fixed and no changes to the code are necessary.

That's it.

**Comment by kugelfuhr** [comment]
In this case I would suggest to change the issue title to something like "cc65: asm expression is incorrectly named 'statement' in the docs" or something like that.

Maybe I'm the only one, but I had problems understanding the issue when it is expressed as a question.

**Comment by acqn** [comment]
Related issue: #1489

**Comment by mrdudz** [comment]
fixed the docs as suggested - closing this ticket :)
