### ISSUE TITLE
Minor issue with the libdefs.h file in cc65/src/common/

### ISSUE THREAD

**Issue by peteArnt** [cc65/cc65#2197]
The definition for the LibHeader struct in libdefs.h is not stable across platforms and compilers.  

Extract from libdefs.h follows:
/* Header structure for the library */
typedef struct LibHeader LibHeader;
struct LibHeader {
    unsigned long       Magic;          /* 32: Magic number */
    unsigned            Version;        /* 16: Version number */
    unsigned            Flags;          /* 16: flags */
    unsigned long       IndexOffs;      /* 32: Offset to directory */
};

The sizes for the fields are not stable across C compilers and OS platforms.
This may not be a problem for those that rebuild everything from a fresh repo cloning from Github.  It may be a problem for those that directly import and use archives that were build on a different platform and/or using a different compiler tool chain.
On my 64-bit Linux workstation, "unsigned" is 32 bits not 16.  "unsigned long" is 64 bits, not 32.
I have not done a deep dive or exhaustive search as to the broader implications of this.
If others deem this to be of significant priority, I might be willing to evaluate this in more detail and report back.
Regards,
-Pete

**Comment by peteArnt** [comment]
Upon further investigation, ar65 uses a special codec for unsigned integers.  This codec is used to read/write values from/to the target archive.  Cross platform portability of archives should not be impacted.  I'll let this issue marinate for a few days to see if others would like to chime in.  I'll close it out in a few days.

**Comment by kugelfuhr** [comment]
Even if these types would be `uint16_t` and `uint32_t` the code would not be portable if the data would be written to the file as is (read: "byte order"). It is a common misconception to assume that code is portable whenever it uses fixed size integers. Often enough this creates more problems than it solves.

**Comment by peteArnt** [comment]
Your point is well taken.
This is fastly becoming a non-issue.

**Comment by peteArnt** [comment]
Yes.  I forgot about 68K.  Also, from ChatGPT:
IBM Power PC
SPARC
MIPS (big & little endian)
IBM System Z (runs Linux)
PA-RISC
--------------------------------------
After more of a deep dive on this, I think there is still something to be considered here:
Here is a snippet from fileio.c within the ar65 directory:
```
void Write32 (FILE* F, unsigned long Val)
/* Write a 32 bit value to the file */
{
    Write8 (F, (unsigned char) Val);
    Write8 (F, (unsigned char) (Val >> 8));
    Write8 (F, (unsigned char) (Val >> 16));
    Write8 (F, (unsigned char) (Val >> 24));
}
```
So, on a x86-64 Linux platform the bytes for Val would be written to the file in little endian (LE) order.
Now, if an archive generated on this system is ported over directly to a big endian (BE) dev platform, that system will be reading the 32-bit value using the corresponding read32 function in fileio.c:
`` 
unsigned Read16 (FILE* F)
/* Read a 16 bit value from the file */
{
    unsigned Lo = Read8 (F);
    unsigned Hi = Read8 (F);
    return (Hi << 8) | Lo;
}

unsigned long Read32 (FILE* F)
/* Read a 32 bit value from the file */
{
    unsigned long Lo = Read16 (F);
    unsigned long Hi = Read16 (F);
    return (Hi << 16) | Lo;
}
``
So, to me it looks like a BE development system would  re-assemble a 32-bit value backwards.

Some questions come to mind: 
1. Is anyone using cc65 on a BE platform?  Perhaps: Amiga? Maybe SPARC?
2. Will users of BE dev systems be exchanging archives with users developing on LE systems?
As for myself, I would never do this as I always like to rebuild libraries(archives) from source.
3. Does this warrant a bug fix or limited re-design?
Perhaps not.  It does seem to be a bit obscure.  Moreover, there are probably more important issues to address within the cc65 toolchain.

Admittedly, I am a bit of a newbie here.  I merely want to bring what I think is a valid issue to the core contributors to this forum.
Respectfully,
-P.

**Comment by mrdudz** [comment]
Remember bit shifts in C always equal division or multiplication - they work the same on BE and LE platforms

**Comment by peteArnt** [comment]
Shifts and other bit-wise operations do not matter and are carried out with expected results regardless of BE or LE.  The only effect that does matter is when 16 or 32 bit values get written to memory, the sequence is sensitive to the endianness of the platform.  If that sequence of bytes is transferred directly to an LE platform (or vice versa) the destination will pick up the wrong byte order.  This is addressed in the network world with functions like htons(), htonl().
How these values get written to memory is key:  If one uses write() or fwrite() with a pointer to a 16 or 32-bit value, the in-memory sequence is copied (read: preserved).  Therein lies the rub.   Fortunately the algorithms used in ar65 do not do this.  Values of these types are broken down byte-by-byte and then written to a file.  This sequence should always be Little Endian because that is the sequence we see in the C code.  When this sequence of bytes is read, the reverse operation is used to rebuild the original integer value on the other system.  Regardless of BE or LE, we have end-to-end symmetry.
This is all just a bit esoteric and I've had to do a fair amount of research.  Originally I thought there might be a problem with the code.  After further analysis and helpful comments from others, I believe there is no longer cause for concern.  I'd like to close this issue for now.
Cheers,
-P.
