### ISSUE TITLE
[65SC02][optimizer][bug] operator &= has no effect 

### ISSUE THREAD

**Issue by Fabrizio-Caruso** [cc65/cc65#2210]
Tested on the Supervision (which has a 65C02) with -Cl (static locals).
Symptoms: `&=` has no effect (e.g., `i&=3` does not change `i`) while `&` works (e.g., `i&3` is correctly computed)  
This bug does not occur on C64, VIC20, C16, ATARI, etc. and not even on the Atari_Lynx.

On a target with conio support (not the Supervision target nor the Atari Lynx), this should be reproducible with:
```
#include <conio.h>
int main()
{
   unsigned char i;
   unsigned char j; 
   for(i=0;i<=10;++i)
   {
	gotoxy(0,i);
	cprintf("%d %d", i, i&3);
	j=i;
	j&=3;
	gotoxy(8,i);
	cprintf("%d", j);
   }
   while(1){};
   return 0;
}
```

Given the lack of standard libraries for the Supervision I have only been able to reproduce it on the Supervision with Cross-Lib:
```
#include "cross_lib.h"
int main(void)
{        
   unsigned char i = 0;
   _XL_INIT_GRAPHICS();
   _XL_CLEAR_SCREEN();
   _XL_SET_TEXT_COLOR(_XL_WHITE);
   while(1)
   {
	++i;
	_XL_PRINTD(0,YSize-4,2,i);
	_XL_PRINTD(0,YSize-3,2,i&3);	
	i&=3;
	_XL_PRINTD(0,YSize-2,2,i);
	_XL_SLEEP(1);
   }
   return 0;
}
``` 

In case you want to reproduce it with Cross-Lib, you can do the following:
- `xl create foo`  (to create a new project)
- edit the main.c inside `projects/foo`
- `xl foo supervision` (to build it for the supervision)

**Comment by Fabrizio-Caruso** [comment]
It seems that the CPU to be used is 65C02 but CC65 compiles for the 65SC02 ([cc65/src/common/target.c](https://github.com/cc65/cc65/blob/12193790e5f8238ed9dad0fd007903bf77fca4aa/src/common/target.c#L187))

The code of the most accurate emulator assumes it is a 65C02
https://github.com/alekmaul/potator

Online documentation is contradictory.
In lack of definitive answer I would change target.c to use 65C02.

**Comment by mrdudz** [comment]
did you compare the generated code of the two variants? seems somewhat unlikely that AND works different on the two CPUs

**Comment by Fabrizio-Caruso** [comment]
@mrdudz I don't think the generated code without peep-holes is different as it works in both cases.
I am not an Assembly coder. So I did not check but I am going to do that. For that I would ask an expert to tell me what is wrong.
For me a probable cause is target.c vs potator code (which mentions 65C02 and not 65SC02).

I suppose that a peep-hole might be using some 65SC02 specific opcode or opcode behavior that is not implemented in the Supervision (or the emulated Supervision, which does not emulate the 65SC02 as is the case for Potator emulator).

**Comment by mrdudz** [comment]
Not sure what you are trying to say, but the CPU being wrong for the target is a completely different problem than the peephole optimizer not working correctly (maybe).

So before changing the CPU for the target, we should look at the generated code and find out what actually goes wrong, and fix that.

According to google, the difference between the 65C02 and the 65SC02 is that the 65SC02 doesn't have the BBR, BBS, RMB and SMB instructions. That basically means if the compiler produces 65SC02 code, it will work fine on the 65C02 - the other way around would be a potential problem :)

The first step to debugging this, would be making a simple self contained test program that doesn't use any external libraries. Or at least remove as much as possible from the above program that would still show the problem. Then it can be compiled for different CPUs (or targets) and we can check the generated code for problems

**Comment by mrdudz** [comment]
Oh btw - you could locally modifiy the makefiles for the tests to use 65SC02 and run the tests and see if some tests break that way. Actually we should probably add 65SC02 there, so all CPUs are tested.

**Comment by Fabrizio-Caruso** [comment]
I got some confirmation from an expert that we should change the CPU to 65C02 from 65SC02 for the Supervision.
The proof he provides is this:
https://twitter.com/furrtek/status/1487084478921068550?t=Pc7u9QccSnTLwE1Z7xr7rA&s=19&fbclid=IwAR3VGYu9I05Y9zBMyP2UgmpX0X9siEhIi9WLOSnEps4IZTRJMOU6j3R2cfU

So it is a KS5360, which is a 65C02 and not a 65SC02.

**Comment by Fabrizio-Caruso** [comment]
@mrdudz 
My main assumptions is probably wrong :-(
I recompiled cc65 with 65C02 as CPU for the Supervision and I still get the same error under Potator emulator.
It may be an issue with the emulator itself.

It is not my code as the problem also appears in the minimal example above.

The CPU sub-type may still be the wrong one but not for the reason I suspected.

I also made an error. My bad.
The problem also occurs with `-Cl`.

I have included the binaries of the minimal test compiled with 65C02 for both the Supervision and the Atari Lynx.

[Xtest_supervision_atari_lynx_gfx.zip](https://github.com/cc65/cc65/files/12839410/Xtest_supervision_atari_lynx_gfx.zip)

**Comment by mrdudz** [comment]
Please be more systematic... those binaries don't help, nor does testing in a random emulator. What we need is the problematic code compiled with cc65 (not cl65) and --add-source, so we can look at the generated code and check if there is a bug in it.

**Comment by Fabrizio-Caruso** [comment]
@mrdudz I have tested the very same minimal case under the Waterloo emulator and it works fine.

I am closing this issue here even though the CPU may be the wrong one.

I will open an issue at the GitHub page of the Potator emulator.

**Comment by polluks** [comment]
There's no bug in common/target.c, it's the wording of KS5360:
"The [This] 65C02 core doesn't support RMB, SMB, BBR, BBS, WAI, or STP."
http://tailchao.com/Wataroo/EQU_WATARA.asm

**Comment by mrdudz** [comment]
The real problem here is that not all "65C02" are the same, even when they are called "65C02". In the common case, 65C02 supports those instructions (and 65SC02) does not. We might have to add a cpu type for KS5360 that supports exactly the instructions this particular implementation supports.
