### ISSUE TITLE
.REFERTO, .REFTO not implemented?

### ISSUE THREAD

**Issue by geowar1** [cc65/cc65#2221]
According to the documentation at: [.REFERTO, .REFTO](https://cc65.github.io/doc/ca65.html#ss11.93)
These commands should be implemented. However when I attempted to use them in the following code I got an error:
```

;================================================================================
        .ifref  hex4out         ;if someone used this subroutine
        .refto  ConOut          ;ensure that ConOut will be included        <<== this is error line 56
;
;output lsnibble of acc as hexadecimal
;
hex4out:
        AND     #%00001111      ;mask lsnibble
;
        CMP     #10             ;greater than or equal to 10?
        BCC     @skip           ;(no)
;
        ADC     #'f'            ;convert for 'A' thru 'F'
;
@skip:  EOR     #'0'            ;convert to ascii
;
        .endif  ;.ifref  hex4out
;
;fall thru to...
;--------------------------------------------------------------------------------
        .ifref  ConOut          ;if someone used this subroutine
;;      .if     .ref(ConOut) | .ref(hex4out)    ;if .refto doesn't work... use this instead
;
;output to console. if IOByte is zero then serial else video
;
ConOut: PHA                     ;push character        <<== this is error line 79
        LDA     IOByte          ;get I/O BYTE
        BEQ     @10             ;(serial console)
;
        PLA                     ;pull character
        JMP             VIDOUT          ;output to video console
;
@10:    PLA                     ;pull character
        JMP     SerOut          ;output to serial console
;
IOByte: .byte   0               ;z=serial, nz=video
;
        .endif  ;.ifref  ConOut
;================================================================================

```
../Console.asm(56): Error: '.REFTO' is not a recognized control command
../Console.asm(56): Error: ':' expected
../Console.asm(79): Error: Symbol 'ConOut' is already defined
../Console.asm(79): Error: Symbol '.size' is already defined

Commenting out the .refto line fixes these errors.

I also tried ".REFERTO" with the same results.

Note: I uninstalled and reinstalled cc65 via both homebrew and via port. 
Both said they were installing 2.19 and "cc65 --version" returns "cc65 V2.19 - N/A" for both.

**Comment by mrdudz** [comment]
the 2.19 release is many years old - the docs that are online refer to the current git version.

You could check if you can install the git head version with homebrew.

**Comment by geowar1** [comment]
>>>You could check if you can install the git head version with homebrew.
FYI:Both brew and post install 2.18… brew --HEAD installed 2.19… verified the issue is fixed there.
Thanks for the comment and suggestion.
 I'll close this issue.
