### ISSUE TITLE
Error: Array of incomplete element type 'const char[]'

### ISSUE THREAD

**Issue by RodrigoDornelles** [cc65/cc65#2250]
This error happened on my work PC where I installed cc65, a more recent version **2.19**, I'm still going to see what version is on my personal PC because this problem didn't occur on it.

```c
static const char foo[2][] = {
 {1, 2},
 {3, 4}
}
```

**Comment by mrdudz** [comment]
What error? Also the recent version is still 2.19 ...

**Comment by RodrigoDornelles** [comment]
> What error? Also the recent version is still 2.19 ...

I gave the wrong command, my version is `cc65 V2.19 - Git 5b47def16`

thats works:

```c
static const char [2][2] = {
 {1, 2},
 {3, 4}
}
```

thats raise an error

```c
static const char [2][] = {
 {1, 2},
 {3, 4}
}
```

**Comment by groessler** [comment]
Sure, because that's invalid.

**Comment by mrdudz** [comment]
```
$ LANG="en" gcc --std=c89 test.c
test.c:1:19: error: array type has incomplete element type 'char[]'
    1 | static const char foo[2][] = {
      |                   ^~~
test.c:1:19: note: declaration of 'foo' as multidimensional array must have bounds for all dimensions except the first
```
(it doesnt work without --std=c89 either)

**Comment by RodrigoDornelles** [comment]
> apparently until not so long ago that construct was actually accepted without error - but that was a compiler bug

@mrdudz 

You're right, it was a compiler bug and I thought it was standard, now it's correct and I noticed the error, it's a shame it was an interesting feature but not standard. :disappointed:
