### ISSUE TITLE
UB in xvsnprintf when using %n

### ISSUE THREAD

**Issue by pm100** [cc65/cc65#2292]
Spotted during work on making msvc x64 work.
```
static void StoreOffset (PrintfCtrl* P)
/* Store the current output offset (%n format spec) */
{
    switch (P->LengthMod) {
        case lmChar:     *va_arg (P->ap, int*)       = P->BufFill; break;
```

this code treats a pointer to a char as a pointer to an int

demo test failure
```
    StrBuf sb = AUTO_STRBUF_INITIALIZER;
    char x[10];
    x[1] = 42;
    SB_Printf (&sb, "%d %hhn\n", 42 , &x[0]);
    assert (x[1] == 42);
```
x[1] [2] and [3] get overwritten by 0

Same error for short

This code is never used but still should be fixed

**Comment by mrdudz** [comment]
fixed via [9985ee7](https://github.com/cc65/cc65/commit/9985ee7f61f9c0e1b1256d16e3fb901c87531019)
