### ISSUE TITLE
ca65: scope created inside a macro doesn't affect files included inside it

### ISSUE THREAD

**Issue by tokumaru-x** [cc65/cc65#231]
The contents of the included file aren't placed inside the new scope when this macro is used:

```
.macro IncludeHidden FilePath
    .scope
        .include FilePath
    .endscope
.endmacro
```

**Comment by mckaygerhard** [comment]
that since are happened, to track what changes in the code?

**Comment by ReallyNiceGuy** [comment]
After application of patch #1477 , this will result in a compilation error.
The contents of a file referenced by an .INCLUDE is processed immediately, as if it was inline on the source code, so it has no access to the argument of the macro at expansion time.

Please close the issue.
