### ISSUE TITLE
Tests: Error in test case bug1178-struct-copy.c

### ISSUE THREAD

**Issue by kugelfuhr** [cc65/cc65#2330]
The tests [outputs data using printf and gives 5 format specifiers but only 4 arguments](https://github.com/cc65/cc65/blob/4343eebe678431bfbe0f2ea47b6235b2ba519ce6/test/val/bug1178-struct-copy.c#L65).

I'm wondering how this could have worked since the output will probably differ each time the test is run.

**Comment by mrdudz** [comment]
> I'm wondering how this could have worked since the output will probably differ each time the test is run.

Only the return value is actually checked - the printed value does not matter in this case :)
