### ISSUE TITLE
cc65: time.h header contains non standard identifiers in C89/C99 mode

### ISSUE THREAD

**Issue by kugelfuhr** [cc65/cc65#2337]
It includes `target.h` which in turn includes all the target specific headers.

This was broken in #2315.

See #1670 for previous problems and reasoning.

I would like to repeat my suggestion from #1670: 

> Since some of the problems have been introduced in recent PRs you might think about an additional "standard compliance check" step whenever standard headers are changed.

I agree that this is difficult to automate, but there's a list of rules to be checked when reviewing a PR. How about adding something like "If standard C headers are changed, make sure non standard identifiers are hidden in standard compliant mode" or similar?

**Comment by mrdudz** [comment]
It's really annoying that this can't be checked automatically.

**Comment by oliverschmidt** [comment]
@colinleroy: Can you please provide a pull request that adds the necessary #ifdef(s) to make everybody happy? Thanks in advance :sunglasses:

**Comment by colinleroy** [comment]
> @colinleroy: Can you please provide a pull request that adds the necessary #ifdef(s) to make everybody happy? Thanks in advance 😎

Done! (the best part was that including target.h there was unnecessary after reworks of #2315 and I just forgot to remove the include)

**Comment by oliverschmidt** [comment]
@colinleroy: Thank you!

**Comment by spiro-trikaliotis** [comment]
> It's really annoying that this can't be checked automatically.

You mean something like here: https://github.com/spiro-trikaliotis/cc65/tree/dumptables
