### ISSUE TITLE
test_gets.c fails on windows

### ISSUE THREAD

**Issue by mrdudz** [cc65/cc65#2388]
what the topic says. must be a LF vs CRLF problem - not sure how to fix it :)

@colinleroy could you have a look?

**Comment by colinleroy** [comment]
That's probably that. We don't want to fix it in the runtime of course so let me find an idea to #ifdef the test :)

**Comment by colinleroy** [comment]
Sent a tentative PR. If that does not work, can you send the output of
```
cd test/ref
./testwrk/ref/test_gets.host
```
and 
```
cd test/ref
../../bin/sim65 -x 200000000 ../../testwrk/ref/test_gets.g.6502.prg
```

They should be the same, of course, and be the same as test/ref/cf.in, only with no newlines.
