### ISSUE TITLE
CC65 "-W" option does not suppress the specified warnings.

### ISSUE THREAD

**Issue by BrainSlugs83** [cc65/cc65#2426]
Version 2.19 / Windows

Using the command `cc65 -Wconst-comparison -Oirs main.c --add-source` or even `cc65 -Oirs main.c --add-source -Wconst-comparison` still results in receiving warnings that should have been suppressed:
`main.c:8: Warning: Result of comparison is always false`

I've also tried putting a space after the -W before the error name or using quotes.  I've checked the repo source and this warning does appear to be associated with this message.

I've noticed the same behavior on other warnings as well.  I have been unable to suppress any warnings on CC65 with version 2.19 on Windows.

**Comment by BrainSlugs83** [comment]
Of course I've been struggling with this for over a week and as soon as I post this I figure it out.

You have to add "-" in front of the warning to suppress also; e.g.:
`cc65 -W -const-comparison -Oirs main.c --add-source`

I guess I'd like to change this request to update the help text as this is not clear at all from the documentation or the help text.

**Comment by mrdudz** [comment]
To me it sounds like the preferred solution would be to change it to work like you said above

**Comment by kugelfuhr** [comment]
This should probably be closed. The behavior is clearly documented. The following is from the documentation:

> **-W name[,name,...]**
>
>    This option allows to control warnings generated by the compiler. It is followed by a comma-separated list of warnings that should be enabled or disabled. To disable a warning, its name is prefixed by a minus sign. If no such prefix exists, or the name is prefixed by a plus sign, the warning is enabled.

**Comment by mrdudz** [comment]
Whats not so clear is the commandline help - its clearly misleading :)

`  -W warning[,...]              Suppress warnings`

It might also make sense to allow the more common "no-" prefix for disabling them, instead of just "-"

In any case - closing, since the original issue is solved. Should someone make a PR that does the above, i am totally willing to merge it :)
