### ISSUE TITLE
Bug shifting right

### ISSUE THREAD

**Issue by mojontwins** [cc65/cc65#244]
Hello.

I've been a cc65 user for quite a long time. I've been using 2.13.3 but today I decided to, finally, upgrade to the latest version, but I found something: This code:

```c
unsigned char uc;
signed int si;

...

void main (void) {
    [...]
    si = 160 << 6;
    uc = si >> 6;
    [...]
}
```
"pry" should equal 160, but the result is 224 instead with the latest "win32 snapshot". I was afraid this was an error on my side, but I double checked with some other values and asked other users in nesdev in this thread.

http://forums.nesdev.com/viewtopic.php?f=2&t=13616&p=160508#p160508

It seems that I found a bug, as the user **lidnariq** mentions:

> In the older release, the >>6 generates calls to asrax4 and asrax2. In the newer one, it instead generates a call to just asrax4 and then tries to inline the remaining >>2, but it does it wrong (it forgets about X and sign-extends A instead of copying the two remaining bits from X).

Thank you very much.

**Comment by drexegar** [comment]
I have this bug on the latest cc65 last week on the main website I downloaded it from https://cc65.github.io/ can someone update it?

Also i have no clue how to download cc65 from github.

**Comment by mrdudz** [comment]
The snapshot linked from the website is the latest one. If you think there is a bug, then open another issue.

However, what you describe looks like expected behaviour. When A is 1, and carry is set, then rotating right two times will result in $c0
