### ISSUE TITLE
Inline Optimize causes compilation error

### ISSUE THREAD

**Issue by markjfisher** [cc65/cc65#2457]
I'm getting a compiler error when I include the `-Oi` flag when compiling my code.

The code includes a library, and when it's including a function from it, I get the following error:

```
-------------------------------------
Building apple2
-------------------------------------
Removing build
Removing obj
mkdir -p obj
cl65 -t apple2 -c --create-dep obj/apple2/main.d --include-dir src/common --include-dir src/apple2 --include-dir src --include-dir ../_libs/4.1.1-apple2 -Oisr --listing obj/apple2/main.lst -o obj/apple2/main.o src/main.c
cl65 -t apple2 -c --create-dep obj/apple2/read_line.d --include-dir src/common --include-dir src/apple2 --include-dir src --include-dir ../_libs/4.1.1-apple2 -Oisr --listing obj/apple2/read_line.lst -o obj/apple2/read_line.o src/read_line.c
cl65 -t apple2 -c --create-dep obj/apple2/text.d --include-dir src/common --include-dir src/apple2 --include-dir src --include-dir ../_libs/4.1.1-apple2 -Oisr --listing obj/apple2/text.lst -o obj/apple2/text.o src/text.c
src/text.c:40: Warning: Control reaches end of non-void function [-Wreturn-type]
mkdir -p build
cl65 -t apple2 -C apple2-system.cfg -Ln build/netcat.apple2.lbl -o build/netcat.apple2 obj/apple2/main.o obj/apple2/read_line.o obj/apple2/text.o ../_libs/4.1.1-apple2/fujinet-apple2-4.1.1.lib
ld65: Error: apple2/src/bus/sp_dispatch.s:40: "jmp (abs)" across page border
make[1]: *** [../makefiles/build.mk:167: build/netcat.apple2] Error 1
make: *** [Makefile:13: all] Error 2
```

There are no errors if I remove the compiler optimization flag `-i`. I've tried all 8 combinations of flags `sir` and anytime `i` is included, it has the issue

The code where it errors is doing the following:
```s
        .export     _sp_dispatch

        .import     _sp_count
        .import     _sp_cmdlist
        .import     _sp_dispatch_fn
        .import     _sp_error

;

; int8_t sp_dispatch(uint8_t cmd)
;
; returns any error code from the smart port _sp_dispatch function
.proc _sp_dispatch
        sta     dispatch_data
        lda     #<_sp_cmdlist
        sta     dispatch_data+1
        lda     #>_sp_cmdlist
        sta     dispatch_data+2
        
        ; the SP dispatch alters the return address by 3 bytes to skip the data below.
        ; it returs with any error codes
        jsr     do_jmp

dispatch_data:
        .byte   $00             ; command
        .byte   $00             ; cmdlist low
        .byte   $00             ; cmdlist high

        ; A is error code. X,Y are the count of bytes
        sta     _sp_error
        stx     _sp_count
        sty     _sp_count+1

        ; convert to a return value
        ldx     #$00
        lda     _sp_error
        rts

do_jmp:
        jmp     (_sp_dispatch_fn)

.endproc
```
line 40 is the final indirect jmp.
sp_dispatch_fn is just a BSS word address defined https://github.com/FujiNetWIFI/fujinet-lib/blob/v4.1.1/apple2/src/bus/sp_data.s

Here is a URL to the codebase at the time of compiling the above that has the error:

https://github.com/FujiNetWIFI/fujinet-apps/tree/c4b669e8e41317279a65b4f5ac392fad4fdaf352/netcat/apple2/src

The library being included was at this point in time:

https://github.com/FujiNetWIFI/fujinet-lib/blob/v4.1.1/apple2/src/bus/sp_dispatch.s

The function that has the error (`sp_dispatch`) is only called from other places in the library, never from outside it directly. It is ultimately called by any of the `network_*` functions in the netcat application.

I have listing files for all the compiled source when working and not, also attached, but non of them refer directly to sp_dispatch either.

[broken.zip](https://github.com/user-attachments/files/16021691/broken.zip)
[working.zip](https://github.com/user-attachments/files/16021692/working.zip)

If there's any more debug or diagnostic I can give, please let me know.

**Comment by markjfisher** [comment]
I've found that the compiler error goes away if I add a return in the method that is mentioned in the output:

```
src/text.c:40: Warning: Control reaches end of non-void function [-Wreturn-type]
```

That's warning on this:
```cpp
unsigned char __fastcall__ inc(void)
{
    __asm__("sta $C082"); // page in ROM
    __asm__("jsr $FD35"); // Key into A
    __asm__("and #$7F");  // Mask strobe bit.
    __asm__("sta $C080"); // page in RAM
}
```

By adding "return 0;" to the end of that method, the compilation completes without errors.

However, I think the point of the code though was to return the Accumulator value by virtue of the RTS that would be added, and the A register would still contain the result of the previous assembly, so "return 0" would break its real return.
And again, the error is only happening when using `-i` optimization.

**Comment by mrdudz** [comment]
The problem you are seeing is that the indirect JMP instruction has a "bug". When the memory location used is on a page boundary, it will not work as expected. Eg JMP ($C0FF) will fetch the lowbyte from $C0FF, and the highbyte from $C000 (and not $C100 as you'd expect) - which is why the assembler/linker errors out.

So whatever you are doing there to produce the problem, its not directly causing it - its just causing _sp_dispatch_fn to be placed on a page boundary.

So the solution is to make sure this is not happening (eg by placing it at a fixed memory location, or at the start of a segment, or using .align ...)

**Comment by markjfisher** [comment]
So the return 0 is just adding enough bytes to shift the location over a boundary, and this was a 1 in 256 chance of happening?

**Comment by mrdudz** [comment]
yes, exactly. Whatever causes more (or less) bytes being emitted before _sp_dispatch_fn may cause this error (if nothing is done to make sure it is never placed on a page boundary)

**Comment by mrdudz** [comment]
> I'll byte align the dispatch function.

its not the function, its the _sp_dispatch_fn variable!

**Comment by markjfisher** [comment]
Ok, I'll fix the library. Thanks for your time!
