### ISSUE TITLE
Preprocessor ignores context: GEOS string fails because of header order

### ISSUE THREAD

**Issue by polluks** [cc65/cc65#2458]
```c
#include <geos/gsym.h>
#include <string.h>

void main()
{
}
```
```
$ cl65 -tgeos /tmp/a.c
/tmp/a.c(2): Error: Include file '(*(unsigned*)0x24).h' not found
```
See https://github.com/cc65/cc65/blob/0541b65aa48ea2508b218ff7097911e741b4bc12/include/geos/gsym.h#L73

**Comment by mrdudz** [comment]
iirc there was already a ticket about this...

in any case, are those GEOS internal things used for anything besides the libs themselves? in that case renaming that "string" to something else would be an acceptable workaround.

**Comment by polluks** [comment]
Maybe the preprocessor should pay attention of this statement: The C preprocessor does not allow for concatenation or construction of strings in a way that forms a valid #include directive.

**Comment by mrdudz** [comment]
Sure. Feel free to fix it :)

I think working around it in the library instead is way easier though :D
