### ISSUE TITLE
[atari7800] joystick driver is not safe for the console hardware

### ISSUE THREAD

**Issue by karrika** [cc65/cc65#2459]
When I wrote this driver originally I did not understand that adding a single button joystick and a dual button joystick at the same time may overheat a transistor and damage the console in the long run. The heating happens only when you keep the single button joystick pressed.

There is code for handling this case. But it turns both joysticks to single button joysticks if either stick is detected to be a single button joystick. The way it does this is to set the RIOT output pin from output to input. It may be enough to turn off the transistors. But I would rather drive to pins to state "1".

In any case I would like to update the driver to be safe for any mix of single or double joysticks.
![7800joysticks](https://github.com/cc65/cc65/assets/6996727/ea6b23bd-c4a5-4453-9809-ee3841250653)

The problematic case is you have a zero on both transistors. In this case 5V will go directly through both transistors via the single button joystick to the ground. There is no current limiting resistor so the transistors may break.

**Comment by mrdudz** [comment]
Whoops - and there is no fuse in the Plus4 either?

**Comment by karrika** [comment]
I will. After I receive the new transistors to my 7800. The previous one are toast after a few experiments.
