### ISSUE TITLE
Make test fails (gcc-14.1.0)

### ISSUE THREAD

**Issue by SvenMichaelKlose** [cc65/cc65#2460]
gcc -std=gnu17 -O2 -Wall -W -Wextra -funsigned-char -fwrapv -fno-strict-overflow -o ../../testwrk/ref/array.host array.c 
array.c:16:1: error: return type defaults to ‘int’ [-Wimplicit-int]
   16 | main() {
      | ^~~~
array.c:36:1: error: return type defaults to ‘int’ [-Wimplicit-int]
   36 | f() {
      | ^
array.c:49:1: error: return type defaults to ‘int’ [-Wimplicit-int]
   49 | g(x, y)
      | ^
array.c: In function ‘f’:
array.c:47:1: warning: control reaches end of non-void function [-Wreturn-type]
   47 | }
      | ^
array.c: In function ‘g’:
array.c:62:1: warning: control reaches end of non-void function [-Wreturn-type]
   62 | }
      | ^
make[3]: *** [Makefile:98: ../../testwrk/ref/array.ref] Error 1
make[2]: *** [Makefile:25: continue] Error 2
make[1]: *** [Makefile:19: test] Error 2
make: *** [Makefile:48: test] Error 2

**Comment by mrdudz** [comment]
damn, so it really happened. I have no good idea how to fix this right now :(

**Comment by mrdudz** [comment]
please try if you can compile it by adding -Wno-error=implicit-int (and if so, perhaps make a PR that adds it to the testbench args, so we can see if that will also work with the older GCC used by GHA)

**Comment by mrdudz** [comment]
Just to spare whoever some googling: https://gcc.gnu.org/gcc-14/porting_to.html "Turning errors back into warnings" has some more options

**Comment by mrdudz** [comment]
closed via #2462
