### ISSUE TITLE
Minus sign in identifiers following #pragma violate ANSI-C token rules

### ISSUE THREAD

**Issue by SvenMichaelKlose** [cc65/cc65#2470]
According to [ISO C standard (ISO/IEC 9899)](https://www.open-std.org/jtc1/sc22/wg14/www/docs/n2310.pdf), section 6.10.6.

Perhaps use underscores instead?

**Comment by mrdudz** [comment]
What is this ticket about?

**Comment by SvenMichaelKlose** [comment]
Pragmas like
`#pragma static-locals`
aren't valid according to the standard. The minus should be an own token. So the suggestion is to fix the preprocessor and use
`#pragma static_locals`

Would change quite a lot of pragmas though. *dug* 8)

Some time later maybe...

**Comment by SvenMichaelKlose** [comment]
BTW I hit this while messing around with clang-format which seems to work nicely otherwise. Nothing a sed script can't fix.

**Comment by mrdudz** [comment]
I see. This should indeed get fixed then. Not an unimportant thing either IMHO, as this way programs written for cc65 that use those pragmas aren't legal C anymore.

**Comment by kugelfuhr** [comment]
> According to [ISO C standard (ISO/IEC 9899)](https://www.open-std.org/jtc1/sc22/wg14/www/docs/n2310.pdf), section 6.10.6.
> 
> Perhaps use underscores instead?

Just out of curiosity: Could you explain which part of ISO/IEC 9899:1999 (E) 6.10.6 forbids the syntax used by cc65?

**Comment by SvenMichaelKlose** [comment]
Sure. It's the "pp-tokens" part in `# pragma pp-tokens(opt) new-line`. Preprocessor tokens are defined in section 6.4 as
`preprocessing-token: header-name identifier pp-number character-constant string-literal punctuator`.
Punctuators are defined in section 6.4.6. (-, --, -=, etc.); dentifiers have to start with a-z, A-Z, or _, followed by ny combination of letters, digits, and underscores (6.4.2).

I hope that helped.

**Comment by polluks** [comment]
short: a pragma name is like a function name :-)

**Comment by kugelfuhr** [comment]
> Sure. It's the "pp-tokens" part in `# pragma pp-tokens(opt) new-line`. 

Ok. So assuming we have 

```C
#pragma static-locals(on)
```

Which of

1. static
2. \-
3. locals
4. (
5. on
6. )

is not a valid preprocessing token?

**Comment by SvenMichaelKlose** [comment]
These are all perfectly valid tokens of course. There cannot be invalid tokens. And the heading of this isn't even saying that. But it makes such pragmas incompatible to tools like clang-format, which for example turn such a pragma into `#pragma stack - locals(on)`. No chance to fix that with another clang-format config. Also paves the way for more incompatibilites to whatever other software according to Murphy's law. And since there's the claim to be ANSI-C compatible in the first place...

**Comment by mrdudz** [comment]
What now? So it is not invalid according to the standard afterall?

**Comment by SvenMichaelKlose** [comment]
It is invalid and even worse: the whole preprocessor thing is non-standard SmallC legacy which shouldn't be string-matching on its own.

**Comment by SvenMichaelKlose** [comment]
Let's bring on another command-line option to switch to standards-compliant #pragma names and update the sources of cc65. So existing app's code won't break and outside tools work.

**Comment by kugelfuhr** [comment]
> These are all perfectly valid tokens of course.

The claim in the header is that the #pragma syntax violates ANSI-C token rules - which is wrong.

> But it makes such pragmas incompatible to tools like clang-format, which for example turns such a pragma into `#pragma stack - locals(on)`.

That's a different story.

**Comment by kugelfuhr** [comment]
> What now? So it is not invalid according to the standard afterall?

No, it is not. There might be good reasons to rename the pragmas, but "violates ANSI-C token rules" is not one of them.

If you really want to change it, I would recommend to add new names using underscores (or without) in addition to the old ones. This keeps for backwards compatibility while allowing people to use tools that cannot cope with the old names. It's also rather easy to implement.

**Comment by SvenMichaelKlose** [comment]
stack-locals is not a valid identifier according to the token rules. What the heck? Thanks for confirming the one and only sensible work-around.

**Comment by kugelfuhr** [comment]
> stack-locals is not a valid identifier according to the token rules.

So what? 

Please reread ISO/IEC 9899:1999 (E) 6.10.6. It doesn't even mention the term "identifier". For a valid #pragma all that is required is that the line contains valid preprocessor tokens. So even

```C
#pragma !!11+^|
```

would be a valid pragma according to the standard.

The #pragma implementation of cc65 requires valid preprocessor tokens after #pragma, so it adheres to the standard.

This does not mean it can't (or shouldn't) be changed. But not for the reason given in the title of this issue.

**Comment by SvenMichaelKlose** [comment]
Is there anything in particular you want so badly then?

**Comment by mrdudz** [comment]
> This does not mean it can't (or shouldn't) be changed. But not for the reason given in the title of this issue.

I agree

> I would recommend to add new names using underscores (or without) in addition to the old ones. This keeps backwards compatibility while allowing people to use tools that cannot cope with the old names. It's also rather easy to implement.

Also this :) perhaps also emit a deprecation-warning when the "old" version is seen in code.

**Comment by SvenMichaelKlose** [comment]
I've added ANSI-C-compatible identifiers in [a branch of my repo copy](https://github.com/SvenMichaelKlose/cc65/tree/pragmas_with_ansic_identifiers_as_names), together with warnings, should old versions hit, so no extra command-line arguments are required to keep things going.

The underscore versions are not recognized. Any idea what that's about? (Please clone to see for yourself.)

**Comment by kugelfuhr** [comment]
> The underscore versions are not recognized. Any idea what that's about? (Please clone to see for yourself.)

I would start by sorting the pragma table alphabetically. This increases the chance that `bsearch()` will find a pragma name by almost 100% 😉 There might be more problems but try this one first.

Next, the code is utterly complex for what it achieves. I would suggest to

1. completely remove the existing pragma names currently marked as obsolete. They are undocumented and have been tagged as obsolete for more than 10 years now. No need to carry this old cruft any longer.
2. remove all the `_OBSOLETE` constants and treat names with hyphens and underlines the same.
3. generate warnings depending on the pragma name containing a hyphen.

These measures will decrease the change size/complexity for pragma.c drastically and as a nice side effect will eliminate all the ugly `gotos`.

**Comment by SvenMichaelKlose** [comment]
Thanks. Time is running out for most of us, so I hoped for more of a definitive answer and to keep things compatible as there won't be a new wave of software for cc65.

In the end perhaps I'm on the wrong track with the clang-format idea. I'm enough of a bitch here to predict that the libraries will sooner or later be compiled with something else and that the preserved C versions of the code with get back in on the action.

**Comment by kugelfuhr** [comment]
> Thanks. Time is running out for most of us, so I hoped for more of a definitive answer

I'm sorry if "sort the pragma table alphabetically" is not definitive enough. The pragma table is searched using `bsearch` which needs a sorted table. Which other information do you need?

**Comment by SvenMichaelKlose** [comment]
Is there an increased chance to not communicate any more at all? Great.

**Comment by mrdudz** [comment]
I am closing this, this is going into a weird direction.

I am willing to merge a PR that implements the alternative names for the pragmas however
