### ISSUE TITLE
'longbranch.mac' is always included in the output asm but not found in CC65 NES

### ISSUE THREAD

**Issue by ltecheroffical** [cc65/cc65#2476]
In CC65 i've noticed that longbranch.mac is required even though it doesn't exist, the only workaround is creating the longbranch.mac in the object file directory

Platform: MacOS
CC65: cc65 V2.19 - Git feb502682

**Comment by polluks** [comment]
What are you compiling? The sample works fine.
```
$ make -C samples SYS=nes      
../bin/cc65  -Ors --codesize 500 -T -g -t nes hello.c
../bin/ca65 hello.s
../bin/ld65   -o hello -t nes -m hello.map hello.o nes.lib

**Comment by ltecheroffical** [comment]
Maybe it works different on macOS? For me it complains with ca65, the only fix being remove the macpack definition from the .s file

**Comment by ltecheroffical** [comment]
And I’m compiling an NES game:

OUTPUT = cart.nes

SRC_DIR = src
OUT_DIR = out

CC = cc65
AS = ca65
LD = ld65

CFLAGS = -Oirs --standard cc65 -t nes -v
AFLAGS = -t nes -v
LDFLAGS = -t nes -v

C_SOURCES = $(wildcard $(SRC_DIR)/*.c) $(wildcard $(SRC_DIR)/**/*.c)
ASM_SOURCES = $(wildcard $(SRC_DIR)/*.s)

C_OBJECTS = $(patsubst $(SRC_DIR)/%.c, $(OUT_DIR)/%.o, $(C_SOURCES))
ASM_OBJECTS = $(patsubst $(SRC_DIR)/%.s, $(OUT_DIR)/%.o, $(ASM_SOURCES))
OBJECTS = $(C_OBJECTS) $(ASM_OBJECTS)

all: $(OUTPUT)
.PRECIOUS: out/%.s # Why delete the .s files? They are used for debugging!

$(OUT_DIR)/%.s: $(SRC_DIR)/%.c
	mkdir -p $(dir $@)
	$(CC) $(CFLAGS) -I $(SRC_DIR) -o $@ $<

$(OUT_DIR)/%.o: $(OUT_DIR)/%.s
	mkdir -p $(OUT_DIR)
	touch $(dir $<)longbranch.mac
	$(AS) $(AFLAGS) -I $(SRC_DIR) -o $@ $<

$(OUT_DIR)/%.o: $(SRC_DIR)/%.s
	mkdir -p $(OUT_DIR)
	$(AS) $(AFLAGS) -I $(SRC_DIR) -o $@ $<

$(OUTPUT): $(OBJECTS)
	$(LD) $(LDFLAGS) -o $@ $(OBJECTS) nes.lib

clean:
	rm -rf $(OUT_DIR) $(OUTPUT)

.PHONY: all clean

**Comment by mrdudz** [comment]
longbranch.mac is a standard macro pack that really does exist and that the compiler/assembler should be able to find :) 

please try to reproduce polluks' example. if that does not work either, then something is wrong with your cc65 install. if it does work though, then something is wrong with how you build that game

**Comment by ltecheroffical** [comment]
Well I used `make install PREFIX=/usr/local` to install, it should work

**Comment by mrdudz** [comment]
> Well I used `make install PREFIX=/usr/local` to install, it should work

so does that example give the same error?

**Comment by mrdudz** [comment]
C64? Did you try to build the NES sample like polluks suggested?

**Comment by ltecheroffical** [comment]
> C64? Did you try to build the NES sample like polluks suggested?

Yes, it does give the same error with the cc65 in /usr/local/bin, however with the one in the cc65 dir then it works

**Comment by ltecheroffical** [comment]
> OK, so that really points to a problem with the installation. Does it find include files, linker configs, libraries etc? I really have a hard time to understand how only macropacks could be affected, that is really weird.

Didn't want to make a joint bug report but it affects everything else as well

**Comment by ltecheroffical** [comment]
Turns out adding cc65 directly to PATH fixes the ploblem, previously I was using make install

**Comment by mrdudz** [comment]
"make install" should work as well

**Comment by ltecheroffical** [comment]
> "make install" should work as well

# Well it doesn't #

**Comment by mrdudz** [comment]
could you post the output produced by that command? i wonder whats wrong on macOS then

**Comment by ltecheroffical** [comment]
Output:


BUILD_ID: Git feb502682
install -d /usr/local/bin
install ../bin/* /usr/local/bin
install -d /usr/local/share/cc65/lib
install -m0644 ../lib/*.* /usr/local/share/cc65/lib
install -d /usr/local/share/cc65/asminc
install -m0644 ../asminc/*.* /usr/local/share/cc65/asminc
install -d /usr/local/share/cc65/cfg
install -m0644 ../cfg/*.* /usr/local/share/cc65/cfg
install -d /usr/local/share/cc65/include
install -m0644 ../include/*.* /usr/local/share/cc65/include
install -d /usr/local/share/cc65/include/arpa
install -m0644 ../include/arpa/*.* /usr/local/share/cc65/include/arpa
install -d /usr/local/share/cc65/include/em
install -m0644 ../include/em/*.* /usr/local/share/cc65/include/em
install -d /usr/local/share/cc65/include/geos
install -m0644 ../include/geos/*.* /usr/local/share/cc65/include/geos
install -d /usr/local/share/cc65/include/joystick
install -m0644 ../include/joystick/*.* /usr/local/share/cc65/include/joystick
install -d /usr/local/share/cc65/include/mouse
install -m0644 ../include/mouse/*.* /usr/local/share/cc65/include/mouse
install -d /usr/local/share/cc65/include/sys
install -m0644 ../include/sys/*.* /usr/local/share/cc65/include/sys
install -d /usr/local/share/cc65/include/tgi
install -m0644 ../include/tgi/*.* /usr/local/share/cc65/include/tgi
install -d /usr/local/share/cc65/target/apple2/drv/emd
install -m0644 ../target/apple2/drv/emd/*.* /usr/local/share/cc65/target/apple2/drv/emd
install -d /usr/local/share/cc65/target/apple2/drv/joy
install -m0644 ../target/apple2/drv/joy/*.* /usr/local/share/cc65/target/apple2/drv/joy
install -d /usr/local/share/cc65/target/apple2/drv/mou
install -m0644 ../target/apple2/drv/mou/*.* /usr/local/share/cc65/target/apple2/drv/mou
install -d /usr/local/share/cc65/target/apple2/drv/ser
install -m0644 ../target/apple2/drv/ser/*.* /usr/local/share/cc65/target/apple2/drv/ser
install -d /usr/local/share/cc65/target/apple2/drv/tgi
install -m0644 ../target/apple2/drv/tgi/*.* /usr/local/share/cc65/target/apple2/drv/tgi
install -d /usr/local/share/cc65/target/apple2enh/drv/emd
install -m0644 ../target/apple2enh/drv/emd/*.* /usr/local/share/cc65/target/apple2enh/drv/emd
install -d /usr/local/share/cc65/target/apple2enh/drv/joy
install -m0644 ../target/apple2enh/drv/joy/*.* /usr/local/share/cc65/target/apple2enh/drv/joy
install -d /usr/local/share/cc65/target/apple2enh/drv/mou
install -m0644 ../target/apple2enh/drv/mou/*.* /usr/local/share/cc65/target/apple2enh/drv/mou
install -d /usr/local/share/cc65/target/apple2enh/drv/ser
install -m0644 ../target/apple2enh/drv/ser/*.* /usr/local/share/cc65/target/apple2enh/drv/ser
install -d /usr/local/share/cc65/target/apple2enh/drv/tgi
install -m0644 ../target/apple2enh/drv/tgi/*.* /usr/local/share/cc65/target/apple2enh/drv/tgi
install -d /usr/local/share/cc65/target/atari/drv/emd
install -m0644 ../target/atari/drv/emd/*.* /usr/local/share/cc65/target/atari/drv/emd
install -d /usr/local/share/cc65/target/atari/drv/joy
install -m0644 ../target/atari/drv/joy/*.* /usr/local/share/cc65/target/atari/drv/joy
install -d /usr/local/share/cc65/target/atari/drv/mou
install -m0644 ../target/atari/drv/mou/*.* /usr/local/share/cc65/target/atari/drv/mou
install -d /usr/local/share/cc65/target/atari/drv/ser
install -m0644 ../target/atari/drv/ser/*.* /usr/local/share/cc65/target/atari/drv/ser
install -d /usr/local/share/cc65/target/atari/drv/tgi
install -m0644 ../target/atari/drv/tgi/*.* /usr/local/share/cc65/target/atari/drv/tgi
install -d /usr/local/share/cc65/target/atari5200/drv/joy
install -m0644 ../target/atari5200/drv/joy/*.* /usr/local/share/cc65/target/atari5200/drv/joy
install -d /usr/local/share/cc65/target/atari7800/drv/joy
install -m0644 ../target/atari7800/drv/joy/*.* /usr/local/share/cc65/target/atari7800/drv/joy
install -d /usr/local/share/cc65/target/atarixl/drv/emd
install -m0644 ../target/atarixl/drv/emd/*.* /usr/local/share/cc65/target/atarixl/drv/emd
install -d /usr/local/share/cc65/target/atarixl/drv/joy
install -m0644 ../target/atarixl/drv/joy/*.* /usr/local/share/cc65/target/atarixl/drv/joy
install -d /usr/local/share/cc65/target/atarixl/drv/mou
install -m0644 ../target/atarixl/drv/mou/*.* /usr/local/share/cc65/target/atarixl/drv/mou
install -d /usr/local/share/cc65/target/atarixl/drv/ser
install -m0644 ../target/atarixl/drv/ser/*.* /usr/local/share/cc65/target/atarixl/drv/ser
install -d /usr/local/share/cc65/target/atarixl/drv/tgi
install -m0644 ../target/atarixl/drv/tgi/*.* /usr/local/share/cc65/target/atarixl/drv/tgi
install -d /usr/local/share/cc65/target/atmos/drv/joy
install -m0644 ../target/atmos/drv/joy/*.* /usr/local/share/cc65/target/atmos/drv/joy
install -d /usr/local/share/cc65/target/atmos/drv/ser
install -m0644 ../target/atmos/drv/ser/*.* /usr/local/share/cc65/target/atmos/drv/ser
install -d /usr/local/share/cc65/target/atmos/drv/tgi
install -m0644 ../target/atmos/drv/tgi/*.* /usr/local/share/cc65/target/atmos/drv/tgi
install -d /usr/local/share/cc65/target/c128/drv/emd
install -m0644 ../target/c128/drv/emd/*.* /usr/local/share/cc65/target/c128/drv/emd
install -d /usr/local/share/cc65/target/c128/drv/joy
install -m0644 ../target/c128/drv/joy/*.* /usr/local/share/cc65/target/c128/drv/joy
install -d /usr/local/share/cc65/target/c128/drv/mou
install -m0644 ../target/c128/drv/mou/*.* /usr/local/share/cc65/target/c128/drv/mou
install -d /usr/local/share/cc65/target/c128/drv/ser
install -m0644 ../target/c128/drv/ser/*.* /usr/local/share/cc65/target/c128/drv/ser
install -d /usr/local/share/cc65/target/c128/drv/tgi
install -m0644 ../target/c128/drv/tgi/*.* /usr/local/share/cc65/target/c128/drv/tgi
install -d /usr/local/share/cc65/target/c16/drv/emd
install -m0644 ../target/c16/drv/emd/*.* /usr/local/share/cc65/target/c16/drv/emd
install -d /usr/local/share/cc65/target/c16/drv/joy
install -m0644 ../target/c16/drv/joy/*.* /usr/local/share/cc65/target/c16/drv/joy
install -d /usr/local/share/cc65/target/c64/drv/emd
install -m0644 ../target/c64/drv/emd/*.* /usr/local/share/cc65/target/c64/drv/emd
install -d /usr/local/share/cc65/target/c64/drv/joy
install -m0644 ../target/c64/drv/joy/*.* /usr/local/share/cc65/target/c64/drv/joy
install -d /usr/local/share/cc65/target/c64/drv/mou
install -m0644 ../target/c64/drv/mou/*.* /usr/local/share/cc65/target/c64/drv/mou
install -d /usr/local/share/cc65/target/c64/drv/ser
install -m0644 ../target/c64/drv/ser/*.* /usr/local/share/cc65/target/c64/drv/ser
install -d /usr/local/share/cc65/target/c64/drv/tgi
install -m0644 ../target/c64/drv/tgi/*.* /usr/local/share/cc65/target/c64/drv/tgi
install -d /usr/local/share/cc65/target/cbm510/drv/emd
install -m0644 ../target/cbm510/drv/emd/*.* /usr/local/share/cc65/target/cbm510/drv/emd
install -d /usr/local/share/cc65/target/cbm510/drv/joy
install -m0644 ../target/cbm510/drv/joy/*.* /usr/local/share/cc65/target/cbm510/drv/joy
install -d /usr/local/share/cc65/target/cbm510/drv/mou
install -m0644 ../target/cbm510/drv/mou/*.* /usr/local/share/cc65/target/cbm510/drv/mou
install -d /usr/local/share/cc65/target/cbm510/drv/ser
install -m0644 ../target/cbm510/drv/ser/*.* /usr/local/share/cc65/target/cbm510/drv/ser
install -d /usr/local/share/cc65/target/cbm610/drv/emd
install -m0644 ../target/cbm610/drv/emd/*.* /usr/local/share/cc65/target/cbm610/drv/emd
install -d /usr/local/share/cc65/target/cbm610/drv/ser
install -m0644 ../target/cbm610/drv/ser/*.* /usr/local/share/cc65/target/cbm610/drv/ser
install -d /usr/local/share/cc65/target/creativision/drv/joy
install -m0644 ../target/creativision/drv/joy/*.* /usr/local/share/cc65/target/creativision/drv/joy
install -d /usr/local/share/cc65/target/cx16/drv/joy
install -m0644 ../target/cx16/drv/joy/*.* /usr/local/share/cc65/target/cx16/drv/joy
install -d /usr/local/share/cc65/target/cx16/drv/mou
install -m0644 ../target/cx16/drv/mou/*.* /usr/local/share/cc65/target/cx16/drv/mou
install -d /usr/local/share/cc65/target/cx16/drv/tgi
install -m0644 ../target/cx16/drv/tgi/*.* /usr/local/share/cc65/target/cx16/drv/tgi
install -d /usr/local/share/cc65/target/gamate/drv/joy
install -m0644 ../target/gamate/drv/joy/*.* /usr/local/share/cc65/target/gamate/drv/joy
install -d /usr/local/share/cc65/target/geos-cbm/drv/emd
install -m0644 ../target/geos-cbm/drv/emd/*.* /usr/local/share/cc65/target/geos-cbm/drv/emd
install -d /usr/local/share/cc65/target/geos-cbm/drv/joy
install -m0644 ../target/geos-cbm/drv/joy/*.* /usr/local/share/cc65/target/geos-cbm/drv/joy
install -d /usr/local/share/cc65/target/geos-cbm/drv/tgi
install -m0644 ../target/geos-cbm/drv/tgi/*.* /usr/local/share/cc65/target/geos-cbm/drv/tgi
install -d /usr/local/share/cc65/target/lynx/drv/joy
install -m0644 ../target/lynx/drv/joy/*.* /usr/local/share/cc65/target/lynx/drv/joy
install -d /usr/local/share/cc65/target/lynx/drv/ser
install -m0644 ../target/lynx/drv/ser/*.* /usr/local/share/cc65/target/lynx/drv/ser
install -d /usr/local/share/cc65/target/lynx/drv/tgi
install -m0644 ../target/lynx/drv/tgi/*.* /usr/local/share/cc65/target/lynx/drv/tgi
install -d /usr/local/share/cc65/target/nes/drv/joy
install -m0644 ../target/nes/drv/joy/*.* /usr/local/share/cc65/target/nes/drv/joy
install -d /usr/local/share/cc65/target/nes/drv/tgi
install -m0644 ../target/nes/drv/tgi/*.* /usr/local/share/cc65/target/nes/drv/tgi
install -d /usr/local/share/cc65/target/pce/drv/joy
install -m0644 ../target/pce/drv/joy/*.* /usr/local/share/cc65/target/pce/drv/joy
install -d /usr/local/share/cc65/target/pet/drv/joy
install -m0644 ../target/pet/drv/joy/*.* /usr/local/share/cc65/target/pet/drv/joy
install -d /usr/local/share/cc65/target/plus4/drv/joy
install -m0644 ../target/plus4/drv/joy/*.* /usr/local/share/cc65/target/plus4/drv/joy
install -d /usr/local/share/cc65/target/plus4/drv/ser
install -m0644 ../target/plus4/drv/ser/*.* /usr/local/share/cc65/target/plus4/drv/ser
install -d /usr/local/share/cc65/target/supervision/drv/joy
install -m0644 ../target/supervision/drv/joy/*.* /usr/local/share/cc65/target/supervision/drv/joy
install -d /usr/local/share/cc65/target/telestrat/drv/joy
install -m0644 ../target/telestrat/drv/joy/*.* /usr/local/share/cc65/target/telestrat/drv/joy
install -d /usr/local/share/cc65/target/telestrat/drv/tgi
install -m0644 ../target/telestrat/drv/tgi/*.* /usr/local/share/cc65/target/telestrat/drv/tgi
install -d /usr/local/share/cc65/target/vic20/drv/emd
install -m0644 ../target/vic20/drv/emd/*.* /usr/local/share/cc65/target/vic20/drv/emd
install -d /usr/local/share/cc65/target/vic20/drv/joy
install -m0644 ../target/vic20/drv/joy/*.* /usr/local/share/cc65/target/vic20/drv/joy
install -d /usr/local/share/cc65/target/vic20/drv/tgi
install -m0644 ../target/vic20/drv/tgi/*.* /usr/local/share/cc65/target/vic20/drv/tgi
install -d /usr/local/share/cc65/target/apple2/util
install -m0644 ../target/apple2/util/*.* /usr/local/share/cc65/target/apple2/util
install -d /usr/local/share/cc65/target/apple2enh/util
install -m0644 ../target/apple2enh/util/*.* /usr/local/share/cc65/target/apple2enh/util
install -d /usr/local/share/cc65/target/atari/util
install -m0644 ../target/atari/util/*.* /usr/local/share/cc65/target/atari/util
make[1]: Nothing to be done for `install'.
make[1]: Nothing to be done for `install'.
install -d /usr/local/share/cc65/samples
install -d /usr/local/share/cc65/samples/geos
install -d /usr/local/share/cc65/samples/tutorial
install -d /usr/local/share/cc65/samples/atari2600
install -d /usr/local/share/cc65/samples/atari5200
install -d /usr/local/share/cc65/samples/apple2
install -d /usr/local/share/cc65/samples/cbm
install -d /usr/local/share/cc65/samples/gamate
install -d /usr/local/share/cc65/samples/supervision
install -m0644 *.* /usr/local/share/cc65/samples
install -m0644 readme.txt /usr/local/share/cc65/samples
install -m0644 Makefile /usr/local/share/cc65/samples
install -m0644 geos/*.* /usr/local/share/cc65/samples/geos
install -m0644 tutorial/*.* /usr/local/share/cc65/samples/tutorial
install -m0644 atari2600/*.* /usr/local/share/cc65/samples/atari2600
install -m0644 atari5200/*.* /usr/local/share/cc65/samples/atari5200
install -m0644 apple2/*.* /usr/local/share/cc65/samples/apple2
install -m0644 cbm/*.* /usr/local/share/cc65/samples/cbm
install -m0644 gamate/*.* /usr/local/share/cc65/samples/gamate
install -m0644 supervision/*.* /usr/local/share/cc65/samples/supervision

**Comment by ltecheroffical** [comment]
It exists but I wish It would actually use it.

**Comment by mrdudz** [comment]
Mmmh and if you eg do "cat /usr/local/share/cc65/asminc/longbranch.mac" in the directory of your NES game, it can access the file?

**Comment by ltecheroffical** [comment]
It finds it whatever directory I am in.

**Comment by groessler** [comment]
Maybe the OP has some other cc65/cl65 in the path. What does "which cl65" say?

**Comment by mrdudz** [comment]
so does any of the other macOS users actually have cc65 "installed" who can check this?
