### ISSUE TITLE
Optimization bug (option -O only), breaking code.

### ISSUE THREAD

**Issue by SvenMichaelKlose** [cc65/cc65#2487]
In [TUNIX Lisp, branch cc65_optimization_bug](https://github.com/SvenMichaelKlose/tunix/tree/cc65_optimization_bug/src/lib/lisp):

To build:

~~~sh
git submodules update --init --recursive
# Do NOT use -j! Sorry.
make host # Has it's own copy of cc65 with glowing hot updates, not found in the regular repo yet. (GETIN for the Commodore Plus/4).
make clean world TARGET=vic20
~~~

To run in VICE + monitor labels:
~~~sh
cd tunix/vic20
xvic -moncommands lisp.lbl -autostartprgmode 0 lisp
~~~

In cc65-generated "src/lib/lisp/eval.o.S":294:  Jump goes to code that stores the accumulator as the pointer's low byte but it's never been read. The accumulator's value is undefined.

NOT_NIL() works further down eval.c, so writing a test isn't so much of an option due to time constraints/peeophole optimization side effects.

**Comment by SvenMichaelKlose** [comment]
That's the only spot that bombs the Lisp project (just as a side note for people who can come up with a quick fix).

**Comment by mrdudz** [comment]
Not sure what your point is - as a testcase it is not very useful like this. This file must be stripped down to the minimal case that still produces the problem

**Comment by SvenMichaelKlose** [comment]
Yes. I get it. Just need to rewind to system 2. 8)

**Comment by SvenMichaelKlose** [comment]
Am pretty sure it was one of my bugs, not cc65. Issue dealt with as far as I'm concerned.
