### ISSUE TITLE
c64: printf and consorts should be able to output at other screen memory not only at 0x400

### ISSUE THREAD

**Issue by MonteCarlos** [cc65/cc65#2488]
It seems printf does not react on setting memory address 648 (on C64 this is the high byte of the screen memory where writes should go).
Any chance of fixing this?
I don't know why this does not work. The print routines use BSOUT as far as I have seen, and so this should already take 648 into account, or?

**Comment by mrdudz** [comment]
It should work IMHO. *shrug*

**Comment by MonteCarlos** [comment]
My fault. When setting 648 from assembly/compiled code, then the basic loop is not running. Therefor the address of the cell under the cursor ($d1/$d2) must be manually recalculated. https://sta.c64.org/cbm64scrfunc.html
```
$E56C	

Set pointer at memory addresses $00D1-$00D2 to current line in screen memory and pointer at memory addresses $00F3-$00F4 to current line in Color RAM, according to current cursor row, at memory address $00D6, and column, at memory address $00D3.
Input: –
Output: –
Used registers: A, X, Y.
```
This fixes the issue.

**Comment by mrdudz** [comment]
i wonder if we should add a cbm specific function for this

**Comment by MonteCarlos** [comment]
Would be an honor for me.

**Comment by MonteCarlos** [comment]
Actually, I don't know how it works on machines other than C64. ;)

**Comment by mrdudz** [comment]
I'm sure its very similar on the other CBM machines :)

**Comment by MonteCarlos** [comment]
After looking around, I think calling $E56C directly may be a bad idea (not very compatible among systems).
More compatible way would be to get/set cursor position directly after each other using PLOT. PLOT then calls the $E56C routine on cursor set.

**Comment by MonteCarlos** [comment]
Closing, as it's not an issue with screen output functions.
