### ISSUE TITLE
Array size compile-time optimization stops halfway

### ISSUE THREAD

**Issue by clbr** [cc65/cc65#250]
The following file errors out on line 3. It compiles fine on gcc with -ansi -pedantic, which forces it to hard c89 mode.

```
#define LZO_MAX(a,b)        ((a) >= (b) ? (a) : (b))
unsigned char c[2*4];
unsigned char b[2*LZO_MAX(8,sizeof(int))];
```

**Comment by clbr** [comment]
The output:
bug.c(3): Warning: Result of comparison is constant
bug.c(3): Error: Constant integer expression expected

**Comment by greg-king5** [comment]
The cc65 function which compiles the `?:` operator has no code for constant expressions.  It always generates code.  It always claims that the code produces a variable result.  Therefore, we are unable to use it in array declarations.

**Comment by oliverschmidt** [comment]
Is a C89 compiler obligated to produce a constant expression from the `?:` operator with constant expressions? In other words: Is this issue to be considered a bug?

**Comment by fo-fo** [comment]
Workaround for the time being:

```c
#define TERNARY(cond,a,b)  (!!(cond)*(a) + (!(cond))*(b))
#define LZO_MAX(a,b)       TERNARY((a) >= (b), (a), (b))
unsigned char c[2*4];
unsigned char b[2*LZO_MAX(8,sizeof(int))];
```

**Comment by clbr** [comment]
> Is a C89 compiler obligated to produce a constant expression from the `?:` operator with constant expressions? In other words: Is this issue to be considered a bug?

Yes, see
http://port70.net/~nsz/c/c89/c89-draft.html#3.4

The syntax part explicitly includes the ?: operator.

**Comment by acqn** [comment]
Not only ternary, but also "&&" and "||", and even "!=", "==" etc. All fail to be treated as constant when they should by cc65.

**Comment by acqn** [comment]
Fixed in my working copy despite it exposes some more issues hidden in the code base....
