### ISSUE TITLE
Missing diagnostics "initialization of a flexible array member is invalid"

### ISSUE THREAD

**Issue by pmor13** [cc65/cc65#2506]
Sample code:
```
struct s { int n; int d[]; };
struct s t2 = { 1, { 4 } };
```
Expected diagnostics:
```
initialization of a flexible array member is invalid
```
Actual diagnostics:
```
<nothing>
```

**Comment by kugelfuhr** [comment]
From the [docs:](https://cc65.github.io/doc/cc65.html#s5):

> cc65 implements flexible array struct members as defined in the C99 ISO standard. As an extension, these fields may be initialized. 

If you compile with `--standard c99` you will get the required diagnostic.

**Comment by pmor13** [comment]
@kugelfuhr Thanks. Consider closing this issue as "not a problem" (or similar).

**Comment by kugelfuhr** [comment]
> perhaps it'd make sense to emit a warning "initialization of a flexible array member is invalid in C99" (or whatever) if std=cc65 ?

Very bad idea. This is perfectly legal code in cc65 mode. Why pester the user with warnings about it? If you really want to add a warning, please consider adding warnings for every other non standard feature in cc65 mode that violates the standard:

* Add a warning for `main()` not returning `int`.
* Add a warning when `asm`, `fastcall` or `cdecl` are used.
* Add a warning for embedded structs without a name.
* Add a warning when `void` variables are initialized.
* Add a warning when parameter names are left out in a function definition.
* ...

**Comment by mrdudz** [comment]
Right, bad idea :)

> Consider closing this issue as "not a problem" (or similar).

I wish you could actually give a proper reason for closing an issue :(
