### ISSUE TITLE
lastline.sh complains about empty files

### ISSUE THREAD

**Issue by kugelfuhr** [cc65/cc65#2514]
It should be possible to add empty files (for example for tests) but it is not:

```
$ cd test/val
$ echo "#include \"foo.h\"" > foo.c
$ touch foo.h
$ make -C ../.. --no-print-directory checkstyle
error: found following files that have no newline at the end:
./foo.h
./test/val/foo.h
make[1]: *** [Makefile:26: lastline] Error 255
make: *** [Makefile:44: checkstyle] Error 2
```

The problem is causes by the lastline.sh file that doesn't exclude empty files before checking that the last line contains a linefeed.

**Comment by mrdudz** [comment]
It should probably exclude the test directory instead (i don't see a reason to add empty files elsewhere - and in the test dir anything should be possible, i guess)

**Comment by kugelfuhr** [comment]
I don't think its a good idea to allow anything in the test directory. You don't want source files with cr/lf even in this directory and also checking for tabs and dangling white space does no harm.

**Comment by mrdudz** [comment]
Well, it doesn't. BUT the compiler also should be able to deal with it :)
