### ISSUE TITLE
Evaluation of constant expression in preprocessing directives may produce incorrect results

### ISSUE THREAD

**Issue by pmor13** [cc65/cc65#2520]
Compiling this code in C99 mode:
```
#if (1 ? 2 : 0) != 2
#error
#endif
```
leads to:
```
Error: #error
```
while `(1 ? 2 : 0) != 2` evaluates to false (zero).

**Comment by mrdudz** [comment]
If they are closely related like this, using one ticket for all is fine, i guess

**Comment by pmor13** [comment]
@mrdudz Compiling this code in C99 mode:
```
#if (0u - 1) < 0
#error
#endif

#if !1u - 1 > 0
#error
#endif

#if (1 & 1u) - 2 < 0
#error
#endif

#if (1 | 1u) - 2 < 0
#error
#endif

#if (1 ^ 1u) - 2 < 0
#error
#endif

#if (1u >> 1) - 2 < 0
#error
#endif

#if (0u << 1) - 1 < 0
#error
#endif

#if (1, 0u) - 1 < 0
#error
#endif
```
produces:
```
<source>:2: Error: #error
<source>:6: Error: #error
<source>:10: Error: #error
<source>:14: Error: #error
<source>:18: Error: #error
<source>:22: Error: #error
<source>:26: Error: #error
<source>:30: Error: #error
```
while in C99 all expressions evaluate to false (zero).

**Comment by mrdudz** [comment]
@pmor13 please make a new ticket (all of those in one), that will be less confusing (we already have a matching PR that closes this ticket)

**Comment by polluks2** [comment]
@pmor13 ISO C forbids evaluated comma operators in #if expressions.
