### ISSUE TITLE
Add bank numbers to dbgfile

### ISSUE THREAD

**Issue by clydeshaffer** [cc65/cc65#2537]
For anyone wanting to map addresses back to C sources, parsing the dbgfile from ld65 seems to be the way forward.

The approach in this comment describes a workable method
https://github.com/cc65/cc65/issues/1549#issuecomment-1221334899

However for systems with banked memory that use the `bank` attribute in the linker config, one would also need the bank number of the `seg` entries to connect them with a given address and bank configuration.

As a workaround, the linker config can be parsed to find the memory area for a given segment name. It would just be nice to be able to skip that step by having the bank number available in the `seg` entry like the `oname` already is.

**Comment by clydeshaffer** [comment]
Example use case: https://github.com/clydeshaffer/GameTankEmulator/issues/33

**Comment by mrdudz** [comment]
closed via #2538
