### ISSUE TITLE
../libwrk/apple2enh/strftime.s(494): Error: Illegal addressing mode

### ISSUE THREAD

**Issue by ssterling** [cc65/cc65#2543]
cc65 v2.19 fails to compile per instructions, throwing the following error:
```
../libwrk/apple2enh/strftime.s(494): Error: Illegal addressing mode
```

Originally reported on Gentoo Bugzilla: <https://bugs.gentoo.org/912925>

Build logs: <https://912925.bugs.gentoo.org/attachment.cgi?id=868585>

**Comment by mrdudz** [comment]
Where is the ebuild though? I don't have any such thing on my gentoo box?

Wonder what they are doing there, 2.19 should certainly compile (although i don't recommend using it - use git head instead)

**Comment by ssterling** [comment]
It’s in [GURU](https://wiki.gentoo.org/wiki/Project:GURU), so you’ll have to add that as an overlay.

v2.19 has an ebuild since it’s technically the most recent release.

**Comment by mrdudz** [comment]
One thing you probably want to do: make it NOT use -j at any place. That will screw things up.

Have you tried compiling it manually using just "make"? That should really work

**Comment by ssterling** [comment]
I can compile it just fine with `make -j8` on my box.  I’ve got a feeling, though, that `make -j56` as used in Sarubbo’s sandbox is causing some sort of ridiculous crap.  I’ll confer with him; if that fixes everything, I’ll close this issue as it’s obviously not an actual code problem.

**Comment by mrdudz** [comment]
It fails randomly with -j - do NOT use it at all. Its a known problem that only was fixed recently (hopefully)
