### ISSUE TITLE
sim65: CPURegs reserves space for a Z register (?)

### ISSUE THREAD

**Issue by sidneycadot** [cc65/cc65#2552]
Hi,

The CPURegs struct in src/sim65/6502.h reserves space for a Z register:

![image](https://github.com/user-attachments/assets/af8e5aeb-1342-4248-baf3-777b9a067b79)

This must be the black sheep of the XYZ family, because it is not mentioned anywhere else in the code. Does anybody know why it's there?

Can we remove it? I'd happily produce a PR that does just that.

**Comment by mrdudz** [comment]
Z is always zero ... in some variant, but i forgot which (65816 perhaps?). That wouldn't justify putting it into that struct though :)

**Comment by sidneycadot** [comment]
Well sim65 is only targetting 6502 and 65C02 at the moment anyway, so will we get rid of it?

**Comment by mrdudz** [comment]
Sure, go ahead :)

**Comment by sidneycadot** [comment]
PR submitted, accepted, merged, and *POOF*, no more elusive Z register ... :)
