### ISSUE TITLE
Atari: reading from stdin using gets/fgets is broken

### ISSUE THREAD

**Issue by sidneycadot** [cc65/cc65#2562]
The program below compiles but doesn't currently work as expected on the atari target. We never get to the second printf().

I also tried fgets(), same issue.

In the git log I see some work has been done on this early 2024, which seems to correspond to the time when this stopped working. But I still need to do a proper bisect.

```
#include <stdio.h>

int main(void)
{
    char s[100];
    for (;;)
    {
        printf("type a string.\n");
	gets(s);
        printf("you typed: %s", s);
    }
}
```

**Comment by sidneycadot** [comment]
Okay I looked into this a bit more.

It seems the root cause of the problem is in libsrc/common/fgets.s

The fgets read loop reads characters until it sees a newline character (0x0a).

However, on the Atari, the end-of-line character when reading from the console is oddly represented as 0x9b, and no routine in-between seems to be doing character translation.

So, what would be the best place to solve this?

**Comment by polluks** [comment]
Hmm, maybe Atari should define \n as \x9B?
C defines "\n", this is already an abstraction, we don't use "\x0A".

**Comment by sidneycadot** [comment]
> Hmm, maybe Atari should define \n as \x9B?

I just checked -- they already do. '\n' is 155.

> C defines "\n", this is already an abstraction, we don't use "\x0A".

Currently libsrc/common/fgets.s does, so that must have slipped by code review:

```
        inc     ptr4
        bne     :+
        inc     ptr4+1

:       cmp     #$0A            ; Stop at \n
        beq     done
        bne     read_loop
```
I'll test to make sure that comparing to '\n' fixes the problem and if so, I'll submit a PR.

Thanks for the suggestion!

**Comment by sidneycadot** [comment]
Question: what is the correct, target-independent way to compare to newline in ca65? "cmp EOL" perhaps?

**Comment by polluks** [comment]
The assembler should use the same rules for simplicity.

**Comment by sidneycadot** [comment]
I'm not going to touch ca65. Too much of a time investment, I have other dishes in the oven ...

**Comment by polluks** [comment]
I see, how about a macro?

**Comment by mrdudz** [comment]
shouldnt '\n' do what we want here (provided the right target with -t is used)?

**Comment by polluks** [comment]
At least in the past this was C
https://www.cs.bu.edu/~jappavoo/Resources/psml/RHCOLAB-LINUXCC/6502/ext/cc65/libsrc/common/gets.c

**Comment by sidneycadot** [comment]
@mrdudz - I think that would be the desirable solution. It is a bit of a trap though, most people would expect '\n' to be a value of 10 these days. It's one thing to do that for C, but when extending that syntax to the assembler it should be clearly documented that these escape characters are not necessarily ASCII, and carry their meaning from C for the same target.

The feature string_escapes is super close to what would be needed, except it doesn't currently extend to character constants.

The following works (when feature string_escapes is enabled), but its fugly.

```
        inc     ptr4
        bne     :+
        inc     ptr4+1

:       .byte   $c9, "\n"           ; This substitues for unsupported but desirable syntax: cmp #'\n'. TODO: fix once character escape codes are implemented.
        beq     done
        bne     read_loop
```

**Comment by sidneycadot** [comment]
Scratch that, it won't work. (Didn't really test it...)

This is how string excapes are currently implemented in ca65:

```
        if (C == '\\' && StringEscapes) {
            NextChar ();

            switch (C) {
                case EOF:
                    Error ("Unterminated escape sequence in string constant");
                    break;
                case '\\':
                case '\'':
                case '"':
                    break;
                case 't':
                    C = '\x09';
                    break;
                case 'r':
                    C = '\x0D';
                    break;
                case 'n':
                    C = '\x0A';
                    break;
                case 'x':
                    NextChar ();
                    if (IsXDigit (C)) {
                        char high_nibble = DigitVal (C) << 4;
                        NextChar ();
                        if (IsXDigit (C)) {
                            C = high_nibble | DigitVal (C);
                            break;
                        }
                    }
                    /* FALLTHROUGH */
                default:
                    Error ("Unsupported escape sequence in string constant");
                    break;
            }
        }
```

That's wrong. It presupposes ASCII. I'll make a new issue for the issue tracker. (Sigh why is it always like this ... https://www.youtube.com/watch?v=AbSehcT19u0)

**Comment by sidneycadot** [comment]
So that patch with the $c9, "\n" trick DOES work but now I'm thoroughly confused how that can be.

This is the code implementing the string_escapes feature:

```
        if (C == '\\' && StringEscapes) {
            NextChar ();

            switch (C) {
                case EOF:
                    Error ("Unterminated escape sequence in string constant");
                    break;
                case '\\':
                case '\'':
                case '"':
                    break;
                case 't':
                    C = '\x09';
                    break;
                case 'r':
                    C = '\x0D';
                    break;
                case 'n':
                    C = '\x0A';
                    break;
                case 'x':
                    NextChar ();
                    if (IsXDigit (C)) {
                        char high_nibble = DigitVal (C) << 4;
                        NextChar ();
                        if (IsXDigit (C)) {
                            C = high_nibble | DigitVal (C);
                            break;
                        }
                    }
                    /* FALLTHROUGH */
                default:
                    Error ("Unsupported escape sequence in string constant");
                    break;
            }
        }
```

First thing to note is that it only handles a smallish subset of the defined C escape sequences.

But the second thing is that this function here presumes ASCII encoding. So how can it work? Is the ASCII string perhaps subjected to target-specific character-by-character substitution afterwards to deal with the target-specific character set stuff? Must be something like that.

Well that's about as deep as I'm willing to dive into ca65. Handwritten scanners make me nervous.

**Comment by sidneycadot** [comment]
Okay, the possible ways forward:

(1) Leave the bug in as-is. Nobody noticed for a year, after all.
(2) I can make a patch with the ugly .byte $c9,"\n" hack, and a big comment explaining the why, and we accept it as technical debt.
(3) We wait until somebody willing and able steps up and implements a proper fix, such as handling character constants with target-specific translation in the assembler. I'm afraid this is in practice indistinguishable from option (1).

**Comment by mrdudz** [comment]
As i see it, we are looking at two separate problems here - 1) how should the assembler behave regarding string/character literals? and 2) how should the atari library behave regarding the native value of \n?

As for this issue, we should look only at 2), and solve it in a way that it does not depend on 1) (which likely means using some hardcoded values somewhere in the atari code)

That said, i am still willing to accept that ugly hack, but only because it mimics the previous behaviour of the implementation in C (this should be mentioned in a comment)

Also while at it, what about a test program (or sample) that checks for this problem and compiles for all (or most) targets? :) There might be similar problem(s) lurking elsewhere...

**Comment by sidneycadot** [comment]
As to (2), what I see is that the C compiler translates '\n' to 155 on the atari, and '\a' to 253 (a "bell"), in the generated assembly code. Those choices seem appropriate, given that the C standards don't mandate any specific character encoding, and just provide (rather vague) meanings to the character escape characters. And those two values are what they should be, on the Atari.

As to (1), I don't know, because I don't have the big picture about the way cc65 and ca65 are supposed to deal with the different character sets for the different targets.

The assembler has a '-t target' option.... Perhaps it does a character-translation pass over strings, before emitting bytes? Whatever it does, it seems intuitively right that the analogous operation should be applied for character constants, including escape sequence handling.

I strongly feel that handling string escape character translation in the assembler's input scanner (src/ca65/scanner.c) is not the correct place to do it; escape handling should be made in code shared by the compiler and the assembler, using the precise same implementation (including handling of backslash escape sequences). The fact that the scanner.c implementation only handles a subset of C escape sequences is a symptom of the fact that this feature was implemented in the wrong place, I think.

A third and separate question is what library functions should do. The direct comparison with #$0a in fget.s presumes an ASCII encoding, and that's just a bug as far as I can tell. Library code should have a way to access the byte value of the target-specific newline character; this could be implemented either by supporting C-like escaped characters, or to mandate that each target defines appropriate symbols for the character values that are needed to implement a functional library, that can be accessed by an .include directive in assembly.

The hack will work as a temporary fix for the bug, but taking on technical debt if there is no realistic plan to ever repay it feels wrong. the problem is that leaving a known bug unfixed is even more wrong.

As to testing: I think the ultimate way to catch these kinds of issues would be to have the ability to run automated tests using emulators for the major targets. Or, perhaps, to define a weird-by-design target based on sim65 with an unusual character encoding, like EBSDIC or something weirder still. But it will take significant effort to set that all up, and there's only so many hands. As indicated, I prefer to spend the little free time I have on other things (lately, fixing sim65).

**Comment by sidneycadot** [comment]
For now, I've created a pull request https://github.com/cc65/cc65/pull/2565 that contains the ugly fix (abundantly commented as such).

A suggested course of action would be to accept the patch, and open up a new issue to add escape character processing to ca65, with a reference to this issue and #2565. Then we can defer the proper solution to some other time, with the C library in a working state.

But if the fix is judged as too ugly, I will not be disappointed :)

**Comment by sidneycadot** [comment]
Closing issue; now subsumed in feature request #2571.

**Comment by GorillaSapiens** [comment]
#2562 #2565 #2571 #2581 all related.

**Comment by GorillaSapiens** [comment]
see #2642
