### ISSUE TITLE
cc65 is missing useful Apple 2 Text macros

### ISSUE THREAD

**Issue by Michaelangel007** [cc65/cc65#260]
On the Apple ][ //e //c programmers need a variety of way of controlling ASCII (high-bit off), APPLE (high-bit on), and Control characters ($0..$1F).

Since out-the-box cc65 doesn't have anything useful in `asminc/`, here is an `apple2text.inc` file that provides this functionality.

```assembly

; NOTE: There is no "standard" directive to set the high bit on ASCII text.
;
; * The assembler used in the redbook uses `msb on` and `msb off`
; * S-C Macro Assembler used
;     .AS for normal ASCII, and
;     .AT for normal ASCII but the last char has the high bit ON
; * Merlin uses yet another variation:
;     ASC 'Hello'   ; high bit is off
;     ASC "Hello"   ; high bit is ON
;   See the new Merlin-32 project
;   http://brutaldeluxe.fr/products/crossdevtools/merlin/
; 
; "The 'nice' thing about standards, is that there are so many to pick from!"

; Force APPLE 'text' to have high bit on
.macro AS text
    .repeat .strlen(text), I
        .byte   .strat(text, I) | $80
    .endrep
.endmacro

; Force ASCII 'text' but last character has high bit on
; Will display as FLASHING characters
; NOTE: There is no lowercase flashinng characters - they will appar as gibbersh!
.macro AT text
    .repeat .strlen(text)-1, I
        .byte   .strat(text, I) & $7F
    .endrep
    .byte   .strat(text, .strlen(text)-1) | $80
.endmacro

; Force APPLE 'text' with high bit on but last character has high bit off
.macro AR text
    .repeat .strlen(text)-1, I
        .byte   .strat(text, I) | $80
    .endrep
    .byte   .strat(text, .strlen(text)-1) & $7F
.endmacro

; Force ASCII 'text' to be control chars: $00..$1F
; Will display as INVERSE characters
.macro AC text
    .repeat .strlen(text), I
        .byte   .strat(text, I) & $1F
    .endrep
.endmacro
```

Example usage:

```assembly
AppleTextDemo:
    AR "ABC"            ; NORMAL : APPLE high-bit text, last char is ASCII (FLASHING)
    AS "Hello world"    ; NORMAL : APPLE high-bit text
    AT "XYZ"            ; FLASH  : ASCII text, last char is APPLE high-bit (NORMAL)
    AC "DEFM"           ; INVERSE: Force to be control chars0 $0..$1F (INVERSE)
```

**Comment by oliverschmidt** [comment]
See https://github.com/cc65/cc65/pull/259#issuecomment-172320233

**Comment by Michaelangel007** [comment]
I'd recommend keeping the historical info. to help people used to other (older) assemblers a clear migration path:

```assembly
; NOTE: There is no "standard" directive to set the high bit on ASCII text.
;
; * The assembler used in the redbook uses `msb on` and `msb off`
; * S-C Macro Assembler used
;     .AS for normal ASCII, and
;     .AT for normal ASCII but the last char has the high bit ON
; * Merlin uses yet another variation:
;     ASC 'Hello'   ; high bit is off
;     ASC "Hello"   ; high bit is ON
;   See the new Merlin-32 project
;   http://brutaldeluxe.fr/products/crossdevtools/merlin/
```

**Comment by oliverschmidt** [comment]
Okay. Please provide a pull request taking my other suggestions into account.

**Comment by Michaelangel007** [comment]
New branch created and file added: [asminc/apple2.mac](https://github.com/Michaelangel007/cc65/blob/cc65upstream/asminc/apple2.mac)

* [x] The file is renamed to apple2.mac.
* [ ] Documentation is added to http://cc65.github.io/doc/ca65.html#s13 .

In the process of updating [doc/ca65.sgml](https://github.com/cc65/cc65/blob/master/doc/ca65.sgml) -- will create new PR once both tasks are done.

**Comment by Michaelangel007** [comment]
Documentation done:

* [x] Apple2.mac documentation is added to [http://cc65.github.io/doc/ca65.html#s13](https://github.com/Michaelangel007/cc65/blob/cc65upstream/doc/ca65.sgml)

Preview of PR:

* https://github.com/cc65/cc65/compare/master...Michaelangel007:cc65upstream

What else needs to be changed before a PR can be created?

**Comment by Michaelangel007** [comment]
i.e. Does section 17 `Porting sources from other assemblers` need to mention:

* 17.2 Apple 2 assemblers

or should the MSB, ASC, stuff stay in apple2.mac ?

**Comment by oliverschmidt** [comment]
I personally think that replacing the comment section in the .mac file with an appropriate 17.2 section would be a nice improvement but I don't consider it obligatory.

**Comment by greg-king5** [comment]
Moving those comments into the document will make the macro file shorter, which means that it will be read and scanned more quickly; and, assembler listings will be shorter.

**Comment by mrdudz** [comment]
On Wednesday 20 January 2016, 08:15:17 greg-king5 <notifications@github.com> 
wrote:
> Moving those comments into the document will make the macro file shorter,
> which means that it will be read and scanned more quickly

how many nanoseconds? =)

-- 

http://www.hitmen-console.org    http://magicdisk.untergrund.net
http://www.pokefinder.org        http://ar.pokefinder.org

You think you know when you learn, are more sure when you can write, even more 
when you can teach, but certain when you can program. 
<Alan J. Perlis>

**Comment by greg-king5** [comment]
Also, you should remove one of the blank lines between each macro.

**Comment by Michaelangel007** [comment]
* [x] Documentation is added to http://cc65.github.io/doc/ca65.html#s13 - 13. Macro packages.
* [x] Documentation is added to http://cc65.github.io/doc/ca65.html#s17 - 17. Porting sources from other assemblers.

**Comment by oliverschmidt** [comment]
Given that you worked on the Macro packages section I presume you have noticed the ```scrcode``` macro in the Atari and CBM package. Maybe you want to use the same name on the Apple2 too - and choose names for the other macros which fit to ```scrcode```. In case you don't like that appoach you might consider to add ```scrcode``` as an alias to "your" name.

**Comment by Michaelangel007** [comment]
No, I never looked at the other platforms.  Taking a look now ...

**Comment by Michaelangel007** [comment]
OK, I see the screen code, `scrcode`, in [asminc/cbm.mac](https://raw.githubusercontent.com/cc65/cc65/master/asminc/cbm.mac) and [asminc/atari.mac](https://raw.githubusercontent.com/cc65/cc65/master/asminc/atari.mac) but I'm not quite following you.

Could you give an example of how you would expect this too look please? Thanks.

i.e.What would a user type to get the various normal, flashing, or inverse strings/characters?

**Comment by oliverschmidt** [comment]
> What would a user type to get the various normal, flashing, or inverse strings/characters?

I'm think along the lines of  ```scrcode```,  ```scrcode_fla``` and  ```scrcode_inv```. But maybe there are better ideas...
