### ISSUE TITLE
Missing 65SC02 opcode?

### ISSUE THREAD

**Issue by polluks** [cc65/cc65#265]
http://anyplatform.net/media/guides/cpus/65xx%20Processor%20Data.txt says
<pre>
  Opcodes: ..............................................................................
    Op  Format              6502 65c02 R65c02 65sc02 HuC6280 65ce02 65c816 Size Cyc References
    44  BSR  nearlabel      -    -     -      -      X       -      -      2    8
    63  BSR  farlabel       -    -     -      X      -       X      -      3    6   40
</pre>

**Comment by greg-king5** [comment]
Go to section 1 of that document; look at the family tree.  Uz and Mark Ormston use the model names differently.  The chip that Mark calls 65c02, Uz calls 65sc02.  The chip that Mark calls R65c02, Uz calls 65c02.  cc65 doesn't support the chip that Mark calls 65sc02.

**Comment by polluks** [comment]
I see. VICE says nothing about BSR
https://raw.githubusercontent.com/noop-dev/VICE_emu/367204c7fd598c791ba9a15d75e352b4a30ab971/vice/doc/html/plain/65C02.txt
How about this?
<pre>The WDC65C02 has 2 addtional instructions not present in the R65C02 and 65SC02,
STP (stops the cpu) and WAI (stops the cpu and waits for an interrupt to
reactivate the cpu):

opcode   mnemonic   bytes   cycles   comments
------   --------   -----   ------   --------
CB       WAI          1       3      on WDC65C02
DB       STP          1       3      on WDC65C02</pre>

**Comment by greg-king5** [comment]
Yes.  Those two mnemonic lines should be copied from the 65816 table into the 65C02 table.

**Comment by polluks** [comment]
done https://github.com/polluks/cc65/commit/cb120f1744e6f986a58ea6a9d6ba637f1815d558

**Comment by oliverschmidt** [comment]
@polluks: It would be nice if you could create a pull request with that change.

Thanks in advance, Oliver
