### ISSUE TITLE
Addition of an u8 and a func returning u8 -> wrong result

### ISSUE THREAD

**Issue by clbr** [cc65/cc65#268]
```
u8 rand8();

void play() {
    static u16 nextpow;
    nextpow = 180 + rand8();
    // print it on the screen
}
```

After this, var contains 9003, which is no way possible. rand8 returns 119 in this case. This happens both with and without -O.

If I write it in two lines, "var = 180; var += rand8();" the result is correct.

Asm with -O:
```
; ---------------------------------------------------------------
; void __near__ play (void)
; ---------------------------------------------------------------

.segment        "CODE"

.proc   _play: near

.segment        "BSS"

L0024:
        .res    2,$00
L0026:
        .res    5,$00

.segment        "CODE"

;
; nextpow = 180 + rand8();
;
        jsr     _rand8
        clc
        adc     #$B4
        bcc     L0029
        inx
L0029:  sta     L0024
        stx     L0024+1
;
; utoa4(scorebuf, nextpow);
;
...
```

**Comment by clbr** [comment]
Sorry, typo: var contains 9003.

**Comment by greg-king5** [comment]
Sometimes, cc65 expects functions to return (at least) 16 bits -- even when they are declared to return eight bits!  `_rand8` must put a zero into the X register before it returns.

**Comment by oliverschmidt** [comment]
@Greg: Thanks for the clarification:-)

This is by the way not specific to cc65. It's quite common that compilers
presume all functions to return "at least" an (unsigned) int. This is to
simplify the implicit promotion to int for expressions as described by the
C spec.
