### ISSUE TITLE
Documentation of calling conventions and requirements

### ISSUE THREAD

**Issue by bbbradsmith** [cc65/cc65#270]
I'm trying to find documentation of the calling conventions required for interaction between assembly and C code, but it doesn't seem to be explicitly documented anywhere.

There is a little bit about fastcall vs cdecl convention here, but it seems very incomplete:
http://cc65.github.io/doc/cc65.html#s5

In particular, there seems to be an unspoken requirement for the caller to set X to 0 if it returns an unsigned char type?
https://github.com/cc65/cc65/issues/263

That last one really surprised me; and I don't think it's something you'd easily catch from looking at the assembled call; it's just waiting for the right/wrong situation to manifest as a difficult bug. I think it would be very helpful to have this explicitly documented so it doesn't become a matter of finding these things out by accidentally failing, or having to study the compiler intensely.

If this all exists in the documentation already and I just couldn't find it, I apologize in advance. I did look for it before posting here.

So, here are some questions that I'd hope the documentation would address:

1. Requirements of the called function, and return values.

Which registers, A X or Y are the responsibility of the function? Are there any other states that it is responsible for? Does the responsibility depend entirely on the return type of the function, or are there other conditions?

If it returns void, does the function have any special return requirements, or will the compiler assume all registers are clobbered?

If it returns an unsigned char, is the callee expected to set X to 0? If it returns a signed char, is the callee expected to set X to 0 or $FF depending on the sign bit? Is there really no such thing as an 8-bit return type, and all return values are implicitly 16-bit?

The function is responsible for emptying the parameters placed on the C-stack. Are all return values in A/X or is there any case where it must leave a return value on the stack?

2. Argument passing.

For cdecl all arguments are passed on the C-stack.

The rightmost argument has the highest address on the C-stack.

The high byte of a 16-bit argument has an address 1 higher than its low byte.

For fastcall the rightmost argument will be placed into A (if 8-bit) or A/X (if 16-bit). The rest will use the C-stack as if the cdecl convention was used with one less argument.

Fastcall is the default convention, unless the --all-cdecl command line option is used.

The command line option --standard hides the "fastcall" and "cdecl" keywords, but "__fastcall__" and "__cdecl__" always remain available.

Is there anything missing here? Are any of these statement incorrect?

3. Use of internal ZP temporary variables.

Some of the CRT's temporary variables are allowed for use by C functions. It is unsafe to expect any of them to be preserved after any call to another C function, but can safely be used within any single function. Should the list of safe temporaries be documented?

Are there any other important details related to calling convention or implementing assembly functions callable from C?

**Comment by oliverschmidt** [comment]
Hi,

> If this all exists in the documentation already and I just couldn't find
> it, I apologize in advance. I did look for it before posting here.
>
I don't know if it's complete or even current but the "usual suspect" is
https://github.com/cc65/wiki/wiki/Parameter-passing-and-calling-conventions

> Some of the CRT's temporary variables are allowed for use by C functions.
> It is unsafe to expect any of them to be preserved after any call to
> another C function, but can safely be used within any single function.
> Should the list of safe temporaries be documented?
>
This is at least partly covered by
https://github.com/cc65/wiki/wiki/Using-runtime-zeropage-locations-in-assembly-language

Regards,
Oliver

**Comment by bbbradsmith** [comment]
Hmm, so there is separate documentation on a Wiki too? I did not know there was such a thing. Thank you.

I think those two links answer most of the questions I asked. The only thing I don't see is anything explicit about return values always being at least 16-bit.

There is: "if the function returns a value, it comes back in A/X." but I don't think that makes it clear that X may be used/expected even if the return value is declared as 8-bit.


If this is all the information I need, should I add the information to the HTML documents myself and submit a pull request? (Or would someone else prefer to write this instead?) Does the information belong in cc65.html or should calling conventions be its own HTML document?

**Comment by oliverschmidt** [comment]
Hi Brad,

> Hmm, so there is separate documentation on a Wiki too? I did not know
> there was such a thing.
>
At least it's linked everywhere the "official" documentation is linked:
- https://github.com/cc65/cc65/blob/master/README.md
- http://cc65.github.io/cc65/#Links

> There is: "if the function returns a value, it comes back in A/X." but I
> don't think that makes it clear that X may be used/expected even if the
> return value is declared as 8-bit.
>
I see your point. I just invited you to the 'Wiki Editors' team so you can
improve that section.

> If this is all the information I need, should I add the information to the
> HTML documents myself and submit a pull request?
>
I think even if it should turn out to be incomplete it would be a benefit
to have it as part of the "official" documentation.

> (Or would someone else prefer to write this instead?)
>
Nobody turned up in the last decade so I presume: No ;-)

> Does the information belong in cc65.html or should calling conventions be
> its own HTML document?
>
cc65.html wants to be the 'cc65 Users Guide'. I don't think calling
conventions belong here. I suggest a new document. I'd suggest the title
'cc65 Internals' and the filename cc65-intern.html.

Thanks in advance, Oliver

**Comment by oliverschmidt** [comment]
Given that the information in question is available in the Wiki it seems appropriate to me to close this issue.

**Comment by greg-king5** [comment]
The "official" project documentation is supposed to be written in LinuxDoc Tools format; and, it should sit in the "doc" subdirectory.  So, that new document should be named something like "`doc/cc65-intern.sgml`".

**Comment by bbbradsmith** [comment]
Yeah, I figured that out, thanks. Once I have time to boot up a linux machine to review, I'll submit for approval.

**Comment by bbbradsmith** [comment]
I've created a pull request, please review the document and let me know if anything is incorrect/missing.

**Comment by bbbradsmith** [comment]
On the subject of Wiki documentation, I notice there is an older copy of the Wiki here: http://wiki.cc65.org/

Should something be done about this (abandoned?) old copy? It's currently the second google result for "cc65 wiki" (after wikipedia), above the one hosted on github.

**Comment by oliverschmidt** [comment]
> On the subject of Wiki documentation, I notice there is an older copy of the Wiki here: http://wiki.cc65.org/

That's correct.

> Should something be done about this (abandoned?) old copy? It's currently the second google result for "cc65 wiki" (after wikipedia), above the one hosted on github.

I don't see anybody active in cc65@GitHub having an option to influence this unfortunate situation :-(
