### ISSUE TITLE
__asm__ volatile

### ISSUE THREAD

**Issue by dhustkoder** [cc65/cc65#275]
Hello, I know that cc65 doesn't support volatile variables.
But It can be very helpful to write NES games using cc65.
I'm trying to write a little api for NES with assembly and C.

Is there a way I can get something like __asm__ volatile ?
I have strong background in C and C++. and learning 6502 assembly
if someone guide me in the right direction I could try to implement that in the compiler.
But I've no experience in compiler source code yet. 
Thanks.

**Comment by mrdudz** [comment]
On Wednesday 02 March 2016, 12:53:54 Rafael Moura <notifications@github.com> 
wrote:
> Hello, I know that cc65 doesn't support volatile variables.
> But It can be very helpful to write NES games using cc65.
> I'm trying to write a little api for NES with assembly and C.
> 
> Is there a way I can get something like __asm__ volatile ?
> I have strong background in C and C++. and learning 6502 assembly
> if someone guide me in the right direction I could try to implement that in
> the compiler. But I've no experience in compiler source code yet.
> Thanks.

you can just use it as you are used to do - the compiler will ignore the 
"volatile" keyword, and it will not attempt to optimize your assembly if its 
in one multiline asm() statement.

-- 

http://www.hitmen-console.org    http://magicdisk.untergrund.net
http://www.pokefinder.org        http://ar.pokefinder.org

A scientist can discover a new star, but he cannot make one. He would have to 
ask an engineer to do that. 
<Gordon L. Glegg>

**Comment by dhustkoder** [comment]
well, for some reason my cc65 is not parsing and ignoring the volatile keyword.
version: cc65 V2.15 - Git 60958f0

source:
`
unsigned char x;

void main(void)
{
	__asm__ volatile ("LDA $4016");
	x = 10;	
	cputc(x);
}
`



error: 
t.c(7): Error: `(' expected
t.c(7): Error: `;' expected
t.c(7): Error: Expression expected
t.c(7): Error: Illegal function call

Ok, but even if cc65 parses and ignore the volatile, It would be very beneficial if
the optimizer do not erase the __asm__ instruction in there, as for NES the 
instruction LDA addr have important side effects

of course I can do something like 
`void main(void)
{
	__asm__ ("LDA $4016");
        __asm__ ("STA %v ; REMOVE ME ; ", x);

	x = 10;	
	cputc(x);
}
`
but these kind of tricks are not so reliable, and I would be doing this a lot.
And I don't feel like turning off the optimizer is a good idea, I like them.
So, volatile effects would be very welcome.

Is it too hard to implement volatile effects on cc65 compiler ?
I wish I knew how to do that.

**Comment by mrdudz** [comment]
On Wednesday 02 March 2016, 16:31:11 Rafael Moura <notifications@github.com> 
wrote:
> well, for some reason my cc65 is not parsing and ignoring the volatile
> keyword. version: cc65 V2.15 - Git 60958f0
> 
> source:
> `
> unsigned char x;
> 
> void main(void)
> {
> 	__asm__ volatile ("LDA $4016");
> 	x = 10;
> 	cputc(x);
> }
> `
> 
> 
> 
> error:
> t.c(7): Error: `(' expected
> t.c(7): Error: `;' expected
> t.c(7): Error: Expression expected
> t.c(7): Error: Illegal function call

interesting. i have to admit i never used it with __asm__ before..

> Ok, but even if cc65 parses and ignore the volatile, It would be very
> beneficial if the optimizer do not erase the __asm__ instruction in there,
> as for NES the instruction LDA addr have important side effects
> 
> of course I can do something like
> `void main(void)
> {
> 	__asm__ ("LDA $4016");
>         __asm__ ("STA %v ; REMOVE ME ; ", x);
> 
> 	x = 10;
> 	cputc(x);
> }
> `
> but these kind of tricks are not so reliable, and I would be doing this a
> lot. And I don't feel like turning off the optimizer is a good idea, I like
> them. So, volatile effects would be very welcome.

ok well, for things like this you will indeed have to disable the optimizer - 
but you can do this only for the assembly snippet:

#pragma optimize(push,off)
__asm__ ("LDA $4016");
#pragma optimize(pop)

.. which might be slightly more ugly than using __asm__ volatile, but would 
work pretty much like exactly that :)

> Is it too hard to implement volatile effects on cc65 compiler ?
> I wish I knew how to do that.

i cant answer that :) i think however that giving an error for __asm__ 
volatile is a bug (it should ignore volatile instead, or perhaps in this case 
even handle it properly and disable the optimizer automatically for the asm 
snippet) ...

-- 

http://www.hitmen-console.org    http://magicdisk.untergrund.net
http://www.pokefinder.org        http://ar.pokefinder.org

Irren ist menschlich. Aber wer richtigen Mist bauen will, braucht einen 
Computer.

**Comment by dhustkoder** [comment]
thank you. The pragma helped, sadly you have to apply the pragma to the hole function, and not just one expression. but that's good enough for now. Anyway if I want better code I should write them by hand in asm.

**Comment by greg-king5** [comment]
You could do what we did with a lot of the system library functions:  We wrote them in C, generated optimized Assembly code, then optimized that code even more by hand.

**Comment by greg-king5** [comment]
I think that the optimizer won't remove `bit` instructions.  Therefore, this should work:

```C
#include <nes.h>
#include <conio.h>

#define TICKLE(addr) __asm__("bit %w", (unsigned)&(addr))

static char x;

void main(void)
{
    TICKLE(JOYPAD[0]);
    x = 10;
    cputc(x);
}
```

**Comment by dhustkoder** [comment]
hey, thanks. I liked the trick you did there, plus the BIT instruction takes the same amount of cycles as LDA so if it have the same effect on the controller port ( getting the next button ) that would be very helpful. I'll try use that for some stuff. But I think that for reading input I probably should write a function in assembly that read from both pads and store into 2  8bits variables each bit for each button.

**Comment by dhustkoder** [comment]
I've tested and it does work nicely with emulators. 
I shouldn't extend this issue for too long, but there's one other thing that got my curiosity

take a look at this:
```
#define PPU_VRAM_DATA (*((unsigned char*)0x2007))
const char* str = "BARON";
void main(void)
{
    PPU_VRAM_DATA = str[0];
    PPU_VRAM_DATA = str[1];
    PPU_VRAM_DATA = str[2];
    return;
}
```

simple code, right ?
but even with optimizer on the compiler generates some strange thing.

```
.proc	_main: near

.segment	"CODE"

	lda     _str
	sta     ptr1
	lda     _str+1               ; remove this
	sta     ptr1+1               ; remove this
	ldy     #$00
	lda     (ptr1),y
	sta     $2007
	lda     _str                   ; remove this
	sta     ptr1                   ; remove this
	lda     _str+1               ; remove this
	sta     ptr1+1               ; remove this
	iny
	lda     (ptr1),y
	sta     $2007
	lda     _str                    ; remove this
	sta     ptr1                    ; remove this
	lda     _str+1                ; remove this
	sta     ptr1+1                ; remove this
	iny
	lda     (ptr1),y
	sta     $2007
	rts

.endproc

```
the comment ' ; remove this  ' are on these instruction I find strange..
there are 10 instruction doing nothing but waste time, removing them does not change the output at all...
is that a bug ?

anyway thanks for the help.

**Comment by oliverschmidt** [comment]
> the compiler will ignore the
"volatile" keyword, and it will not attempt to optimize your assembly if its
in one multiline asm() statement.

Unfortunately this isn't true. And it's even documented (http://cc65.github.io/doc/cc65.html#inline-asm):

_Note: Inline assembler statements are subject to all optimizations done by the compiler. There is currently no way to protect an inline assembler statement from being moved or removed completely by the optimizer. If in doubt, check the generated assembler output, or disable optimizations._

> #pragma optimize(push,off)
__asm__ ("LDA $4016");
#pragma optimize(pop)

Unfortunately this doesn't work. And it's even documented (http://cc65.github.io/doc/cc65.html#ss7.8):

_Please note that this pragma only effects whole functions._

The cc65 inline assembly as it stands is of limited use. The primary idea of inline assembly is to combine assembly and substantial amount of C code in a single function. And for a substantial amount of C code you want the optimizer. And if you can life with putting the assembly into a separate function (to limit the impact of the pragma) then you can write that function in pure assembly as well.

Things like `cli` and `sei` work afaik. The classic `lda` is a bad idea(tm). I don't know if `bit` is a good idea as it might influence the processor flags in a way the optimizer doesn't take into account - but I might be wrong here.

My personal take would be to avoid inline assembly for things like this and rather make use of the optimizer instead of battling with it. I see a header file with:

```
unsigned char trigger_dummy;
#define TRIGGER(addr) trigger_dummy = *(unsigned char*) (addr)
```

and usage like

```
TRIGGER(0x4016);
```

With the optimizer turned on this is supposed to translate to

```
lda $4016
sta <absolute>
```

Maybe you can shave off a cycle by placing the dummy in the zeropage...

**Comment by mrdudz** [comment]
On Thursday 03 March 2016, 00:21:37 Rafael Moura <notifications@github.com> 
wrote:
> hey, thanks. I liked the trick you did there, plus the BIT instruction takes
> the same amount of cycles as LDA so if it have the same effect on the
> controller port ( getting the next button ) that would be very helpful.
> I'll try use that for some stuff. But I think that for reading input I
> probably should write a function in assembly that read from both pads and
> store into 2  8bits variables each bit for each button.

doesnt that kind of function already exist in the library?

-- 

http://www.hitmen-console.org    http://magicdisk.untergrund.net
http://www.pokefinder.org        http://ar.pokefinder.org

I can always spot a programmer who has only worked on one architecture. He or 
she looks on the basic data types of that machine as God-given. The same goes 
for how the system names files, how it represents lines of text, and dozens of 
other arbitrary design decisions. There is a level of abstract thinking that 
comes only from writing code that is intended to be portable across 
architectures. 
<P.J.Plauger>

**Comment by mrdudz** [comment]
On Thursday 03 March 2016, 00:50:04 Oliver Schmidt <notifications@github.com> 
wrote:
> > the compiler will ignore the
> 
> "volatile" keyword, and it will not attempt to optimize your assembly if its
> in one multiline asm() statement.
> 
> Unfortunately this isn't true.
[...]
yeah, figured that much. apparently the assembler snippets i used so far could 
never be optimized by the compiler =)

-- 

http://www.hitmen-console.org    http://magicdisk.untergrund.net
http://www.pokefinder.org        http://ar.pokefinder.org

Die Furcht vor der freim�tigen Antwort kann auch robuste Charaktere befallen. 
<Jeanette Schmid>

**Comment by greg-king5** [comment]
> The comment "; remove this" is on those instructions that I find strange.  There are 10 instructions doing nothing but waste time; removing them does not change the output, at all.  Is that a bug?

The first two of those lines are needed because pointers are two bytes long.  The other eight are duplicates.  It isn't a bug; but, the optimizer isn't smart enough to see that the two-byte value in `_str` doesn't change.

**Comment by dhustkoder** [comment]
>  The first two of those lines are needed because pointers are two bytes long. The other eight are duplicates. It isn't a bug; but, the optimizer isn't smart enough to see that the two-byte value in _str doesn't change.

oh, of course. thanks
