### ISSUE TITLE
volatile keyword is not ignored when used with __asm__

### ISSUE THREAD

**Issue by mrdudz** [cc65/cc65#276]
```C
volatile int bla = 0; // works
int main(int argc, char *argv[])
{
    __asm__ volatile ("nop"); // gives an error
}
```
'volatile' should be ignored also in the second case.

**Comment by greg-king5** [comment]
Because of Oliver's request, `volatile` isn't ignored in `asm` statements.  Now, it does almost what mrdudz had thought that it does.

**Comment by oliverschmidt** [comment]
@greg-king5: Thanks for the fix !

**Comment by mrdudz** [comment]
i second this \o/
