### ISSUE TITLE
cc65 fails to warn about incorrect alignment in some cases

### ISSUE THREAD

**Issue by fo-fo** [cc65/cc65#278]
test.c:
```c
extern unsigned char aligned_to_256;
void main() {
    aligned_to_256 = 123;
}
```
test2.s:
```asm
.segment "BSS"
.align 256
.export _aligned_to_256 := *
.byte 0
```
Compilation:
`cl65 -t nes -m map.txt test2.s test.c`
This produces no warnings, but if you check the map file you'll see that `_aligned_to_256` ended up at 0x6029 -- not aligned to 256 bytes.

In contrast, when using the default C64 target:
`cl65 -m map.txt  test2.s test.c`
Result:
``ld65: Warning: Segment `BSS' is not aligned properly. Resulting executable may not be functional.``

My first hunch is that it might be caused by the `DATA` segment in `nes.cfg` specifying `run=RAM` (the `BSS` segment also goes in `RAM`), confusing the linker somehow. But that's purely a guess.

**Comment by mrdudz** [comment]
On Thursday 24 March 2016, 02:33:32 fo-fo <notifications@github.com> wrote:
> test.c:
> ```c
> extern unsigned char aligned_to_256;
> void main() {
>     aligned_to_256 = 123;
> }
> ```
> test2.s:
> ```asm
> .segment "BSS"
> .align 256
> .export _aligned_to_256 := *
> .byte 0
> ```
> Compilation:
> `cl65 -t nes -m map.txt test2.s test.c`
> This produces no warnings, but if you check the map file you'll see that
> `_aligned_to_256` ended up at 0x6029 -- not aligned to 256 bytes.
> 
> In contrast, when using the default C64 target:
> `cl65 -m map.txt  test2.s test.c`
> Result:
> ``ld65: Warning: Segment `BSS' is not aligned properly. Resulting executable
> may not be functional.``
> 
> My first hunch is that it might be caused by the `DATA` segment in `nes.cfg`
> specifying `run=RAM` (the `BSS` segment also goes in `RAM`), confusing the
> linker somehow. But that's purely a guess.

iirc the alignment is always relative to the respective section, not absolute 
address

-- 

http://www.hitmen-console.org    http://magicdisk.untergrund.net
http://www.pokefinder.org        http://ar.pokefinder.org

Das einzige intuitive User-Inferface ist der Nippel. Alles weitere musstest Du 
in Deinem Leben irgendwann mal lernen.

**Comment by fo-fo** [comment]
> iirc the alignment is always relative to the respective section, not absolute
> address

The point was that **no warning** is given about it. From the docs:

> The alignment of a segment must be equal or greater than the alignment used in the .ALIGN command. The linker will check that, and issue a warning, if the alignment of a segment is lower than the alignment requested in an .ALIGN command of one of the modules making up this segment.

**Comment by greg-king5** [comment]
ld65 aligns segments twice:
1. When object files are read and linked; and, the link addresses are generated.
2. When a binary program file is written (then, ld65 can determine how many fill bytes to write).
The misalignment check is done during only stage 2.

"nes.cfg" puts the BSS segment in a memory area that isn't written into a file; that's why ld65 didn't show the warning.

The previous version of "c64.cfg" puts BSS into a memory area that is written; that's why ld65 did show the warning (even though the BSS segment isn't written).  (The current version of "c64.cfg" puts BSS into an unwritten area; therefore, it wouldn't show that warning.)
