### ISSUE TITLE
Vic20: Invalid entries in the kernel jump table

### ISSUE THREAD

**Issue by OzHawk** [cc65/cc65#286]
The Vic20 does not have kernal table entries for the following functions.

;-----------------------------------------------------------------------------
; Functions which are not in the kernal jump table for VIC-20 but are for C64

CINT        := $E518
IOINIT      := $FDF9
RAMTAS      := $FD8D

All other kernal entries are the same as the C64, however, without this change, the startup code fails.

Without this change the vic20.lib builds incorrectly.

Propose that to keep the code consistent and backwards compatible, the entries in the jump table are replaced with the address of the actual function rather than the entry in the jump table.

**Comment by greg-king5** [comment]
OK, that makes sense.  Please give us a Pull Request with your patch.
