### ISSUE TITLE
pico]OS doesn't work on cc65 2.15

### ISSUE THREAD

**Issue by ssuukk** [cc65/cc65#293]
pico]OS doesn't work on cc65 2.15, but works when compiled with V2.13.3. See this issue: https://github.com/AriZuu/picoos/issues/1

**Comment by AriZuu** [comment]
After a few hours of binary search with git, it seems that compiler built from commit c30d87f0b7938ff3887dac2417324359b3fe8e12  still works with pico]OS, but newer ones doesn't.

**Comment by AriZuu** [comment]
I think that this is not compiler problem. It is just that default calling convention has changed to __fastcall__, which results in pico]OS creating incorrect initial stack for task.

**Comment by AriZuu** [comment]
When I compile pico]OS with "--all-cdecl" everything works even with new compiler.

**Comment by oliverschmidt** [comment]
@AriZuu: Thanks for answering this question :-)
