### ISSUE TITLE
Document the build process for cc65.

### ISSUE THREAD

**Issue by janrinze** [cc65/cc65#316]
The Makefile has several variables like 'prefix'.
Does the documentation have info on how to set up these variables so that target libraries and include files can be found by the executables?

As far as I can see if prefix is set to /home/user on linux the executables will be found in /home/user/bin/ and the libraries are installed in /home/user/share/cc65 but running cl65 won't find these after make install.

for example 

```
$ cat hello.c
/* hello world */

#include <stdio.h>

int main(int argc,char**argv)
{
    printf("hello world\n");
    return 0;
}
$ cl65 -o hello ./hello.c 
./hello.c(3): Error: Include file `stdio.h' not found
./hello.c(7): Error: Call to undefined function `printf'
./hello.c(9): Warning: Parameter 'argc' is never used
./hello.c(9): Warning: Parameter 'argv' is never used
$ cl65 --print-target-path
/home/user

$ export CC65_HOME=/home/user/share/cc65/
$ cl65 -o hello ./hello.c
./hello.c(9): Warning: Parameter 'argc' is never used
./hello.c(9): Warning: Parameter 'argv' is never used
$
```

According to the documentation of cl65 the CC65_HOME does not need to be setup if it is properly compiled. Unfortunately I cannot find in the documentation how to get it properly compiled.

**Comment by oliverschmidt** [comment]
> According to the documentation of cl65 the CC65_HOME does not need to be setup if it is properly compiled.

That's true - at least according to my understanding.

> I cannot find in the documentation how to get it properly compiled.

- One simple option is documented in http://cc65.github.io/cc65/getting-started.html#GNU
- How to build in order to make use of the 'install' target is currently indeed not documented.

**Comment by BPaden** [comment]
In the Arch User Repository PKGBUILD for cc65-git, prefix is only set during `make install`. This worked in the past, but doesn't currently.

It appears something changed to require prefix to be set during the build. It works as expected in that case.

**Comment by jeremyvisser** [comment]
As of today, the Arch User Repository build of cc65 is fixed, with `PREFIX=/usr` set for both `make` and `make install` steps:
https://aur.archlinux.org/cgit/aur.git/commit/?h=cc65&id=8f8709a6e6d60a4455ef6e0c9612e79955b591fc

**Comment by oliverschmidt** [comment]
Looks like a nice cleanup to me :-)

**Comment by janrinze** [comment]
Thanks!

**Comment by oliverschmidt** [comment]
I think it's appropriate to close this issue now...
