### ISSUE TITLE
Optimization chance: needless X negation

### ISSUE THREAD

**Issue by clbr** [cc65/cc65#337]
``` c
#include <stdint.h>

extern uint8_t a, b;

uint8_t inversion() {
        return !!(a & b);
}
```

``` asm
.proc   _inversion: near

.segment        "CODE"

        lda     _b
        and     _a
        jsr     bnega
        jsr     bnegax
        ldx     #$00
        rts
```

It's clearly pointless to negate X when the result is 8-bit.

**Comment by mrdudz** [comment]
``
return !!(a & b);

isnt that equivalent to not negating at all? or am i having a latenight brainfart here? :)

**Comment by groessler** [comment]
It returns 1 and not the bits which are still set from (a & b) when (a & b) is not zero. Also don't know a use case right now but I've seen such constructs before. Probably some modern oo paradigm :-)

**Comment by greg-king5** [comment]
It's a fancy way to convert from a bitfield-like value into a _pure_ boolean value.  It's equivalent to
```C
return (a & b) != 0;
```

**Comment by prandeamus** [comment]
I've been looking at this, and have a side question to ask. It may be a bug. Compiling the following with -Oi

```c
uint8_t a;
uint8_t b;
uint8_t test2(void) {
    return (a & b) != 0;
}
```
generates

```asm
lda     _b
and     _a
lda     #$00
jmp     boolne
```
Given that the first instruction of boolne is a condtional branch (as for all the corresponding functions in makebool.s) I'm not sure if this correct. Surely the lda #0 will guarantee the Z flag is set on entry to boolne?

```c
int main() {
    uint8_t c,d;
    
    a=0xff;
    b=0xff;
    c=test2();
    a=0x00;
    b=0x00;
    d=test2();

    printf("%d,%d\n", c,d);

    return EXIT_SUCCESS;
}
```
Compile with
```cfg 
cl65 -O --target sim6502 -l hello.lst -T hello.c
sim65 hello
```
Results "0,0" when I would have expected c to be non-zero. 

Take out the -Oi flag, and the result is "1,0".  It's much slower and bigger code, but it extends a to int, pushes to stack, loads primary register with b, then ands the TOS with primary register, does a 16 bit comparison and finally calls boolne. Bloated but probably correct.

```asm
ldx     #$00
lda     _a
jsr     pushax
ldx     #$00
lda     _b
jsr     tosandax
cpx     #$00
bne     L0007
cmp     #$00
jsr     boolne
ldx     #$00
jmp     L0004
L0004:	rts
```
Smells like an optimiser fault, what do we think?

**Comment by clbr** [comment]
Indeed, that's a bug separate from the possible new optimization I reported.

**Comment by oliverschmidt** [comment]
Fixed with https://github.com/cc65/cc65/pull/996.

**Comment by clbr** [comment]
Please reopen. This is not fixed. What was fixed was a bug commented by someone else, not the missing optimization I reported.

**Comment by oliverschmidt** [comment]
Thanks for the hint. As requested reopened for the original enhancement.

**Comment by acqn** [comment]
I did an attempt to resolved this by using some "intermediate" runtime functions to ease the optimizations:
https://github.com/acqn/cc65/tree/BoolOpt


The new optimization steps would optimize out the new runtime functon `bcastax` for `char`-/`int`-size objects, but would leave `bcasteax` for `long`-size objects as always. With these new optimization steps,  the compiler could optimize most of the logical calculation, but unfortunately it would usually leave a pair of PHA/PLA that could not be safely removed in general without tracking the usage of the Z/N flags (in some later commits):
.segment	"CODE"

```asm
.proc	_inversion: near

.segment	"CODE"

;
; return !!(a & b);
;
	lda     _b
	and     _a
	pha
	pla
	jmp     boolne

.endproc
```
```asm
.segment	"CODE"

.proc	_test2: near

.segment	"CODE"

;
; return (a & b) != 0;
;
	lda     _b
	and     _a
	pha
	pla
	jmp     boolne

.endproc
```
