### ISSUE TITLE
Introduce release tags

### ISSUE THREAD

**Issue by bclausdorff** [cc65/cc65#351]
Release tags would make it more comfortable to choose a specific state of the software (e.g. for teams or tutorials). 
Especially as the current master branch is not 100% backwards-compatible to former versions anymore.

The commits before bumping the version number are the best candidates for receiving a release tag.

Two examples:
`16b77658a7918c4363d22cc8663e406d2cedea92` for version `2.13.9`
`ec2195b4ecbca77432dbd1211cb8efb7cfd79585` for version `2.14`

As a bonus, a short summary about the most important enhancements and breaking changes could be added to the releases.

**Comment by oliverschmidt** [comment]
After "moving" cc65 to GitHub there was a (very) length discussion about the release strategy. As long as I'm maintaining this project I don't see a momentum for any change.
