### ISSUE TITLE
Update brew formula

### ISSUE THREAD

**Issue by bclausdorff** [cc65/cc65#352]
may depend on #351 

The current brew formula (popular package manager for macOS) installs version `2.13.3` which was released around the year 2012.

Should we update it and promote a newer version?

**Comment by mrdudz** [comment]
isn't "brew" a project completely unrelated to cc65? (some MAC OSX stuff iirc?)

**Comment by bclausdorff** [comment]
It's a package manager like apt-get but for macOS.

Before making any adjustments to the current cc65 brew formula/entry, I thought it would be a good idea to ask the current maintainers of cc65 how they would feel about updating it and which version they would like to be promoted. Isn't the brew entry maintained by one of the cc65 contributors?

**Comment by oliverschmidt** [comment]
This issue doesn't belong here.
