### ISSUE TITLE
cc65 misparses octal escapes in strings followed by digits 0-7

### ISSUE THREAD

**Issue by EtchedPixels** [cc65/cc65#357]
There is a funny quirk in C that, while a hex constant can be long, an octal constant is no more than 3 digits.  Thus, `"\0101"` is a two-byte string.

I hit this in [Fuzix](https://github.com/EtchedPixels/FUZIX/), as it builds some string arrays using `"123\000123"`.

**Comment by greg-king5** [comment]
Fixed by pull request #358.
