### ISSUE TITLE
Adding a CPU (SPC700)

### ISSUE THREAD

**Issue by kylophone** [cc65/cc65#362]
I'd like to add support for the [SPC700](https://en.wikipedia.org/wiki/Nintendo_S-SMP#SPC700) into cc65. I can write the code, but I was hoping someone could point me to a similar commit so I know where to start.

Here's the official CPU doc: [spc700.pdf](https://github.com/cc65/cc65/files/671918/spc700.pdf)

**Comment by mrdudz** [comment]
cant point to a specific commit right now - but this is going to be harder than previous additions, since this CPU isnt exactly a 6502 derivate

**Comment by kylophone** [comment]
Right now I'm working off of [this pull request](https://github.com/cc65/cc65/pull/343/commits/0538184699358b9f2f3427277cfe1c30d7c64fef) which added support for the 4510 cpu. I take a crack at it and see how far I can get. Also noteworthy, people have already been using ca65 to assemble SPC700 code with this [big macro set](https://github.com/Optiroc/libSFX/blob/master/include/SMP_Assembler.i). This works, but is not really ideal, which is why I'd like to add official support to cc65.

**Comment by oliverschmidt** [comment]
I don't want to be the spoil sport but...

If a pull request
- has a goal that deviates too much from the cc65 goal
- adds too much complexity (and therefore impedes maintenance too much)
I might not merge it although it meets all (never exactly formulated in the first place) requirements. I'm however not the (only) one to judge on those two aspects but nevertheless I think this heads-up is appropriate before large investments are made.

**Comment by pinobatch** [comment]
Disclosure: I was the one who gave "blargg" (Shay Green) the idea to make the SPC700 macro pack.

The Sony SPC700 is semantically almost identical to a 65C02, just with opcodes renumbered, and with a different official syntax to keep MOS/WDC/Rockwell lawyers from interfering.

**Comment by oliverschmidt** [comment]
It seems to me that this question was pretty much answered. In case there will be an actual SPC700 pull request we can refer to this conversation even if I close this issue here now.
