### ISSUE TITLE
TGI (Missing Text Functions)

### ISSUE THREAD

**Issue by MohicanFr** [cc65/cc65#364]
I have been trying to compile this old piece of code, which contains a demo of a TGI font:
http://www.cc65.org/mailarchive/2009-11/7553.html

However, cc65 complains that these functions have disappeared from the header files:
```
tgi-preview.c(58): Error: Call to undefined function `tgi_textwidth'
tgi-preview.c(72): Error: Call to undefined function `tgi_textstyle'
tgi-preview.c(73): Error: Call to undefined function `tgi_textheight'
tgi-preview.c(101): Error: Call to undefined function `tgi_textscale'
```
Could you please let me know how to get those functions back?
Many thanks in advance,
Anthony

**Comment by greg-king5** [comment]
Look in the "tgi.h" header file.  The names were changed, a little bit; they now have "set" and "get" in them.  For example, `tgi_textwidth()` now is `tgi_gettextwidth()`.

**Comment by MohicanFr** [comment]
Thaank you very much Greg for the quick reply!
