### ISSUE TITLE
Mouse support in TGI

### ISSUE THREAD

**Issue by MohicanFr** [cc65/cc65#366]
When switching to TGI video mode, it seems that the 1351 mouse pointer is not supported properly. Regardless of whether I initialise the mouse before or after TGI, sometimes I see nothing, sometimes I see 2 or 4 pixels moving around the screen as I move the mouse.
These 2/4 pixels convince me that it should be possible to support the mouse pointer fully in TGI video mode; is there an easy way to achieve this?

(P.S.: for now, I have implemented this very poor piece of code, in order to draw a poor-man's pointer)

```C
while (!kbhit()) {
	//Get new mouse position
	mouse_info(&info);
	if (abs(mouseX - info.pos.x) > 0 || abs(mouseY - info.pos.y) > 0) {
		//Reset screen
		tgi_setcolor(mouseMask[0][0]);
		tgi_setpixel(mouseX,  mouseY);
		tgi_setcolor(mouseMask[0][1]);
		tgi_setpixel(mouseX,  mouseY+1);
		tgi_setcolor(mouseMask[1][0]);
		tgi_setpixel(mouseX+1,mouseY);
		tgi_setcolor(mouseMask[1][1]);
		tgi_setpixel(mouseX+1,mouseY+1);
		tgi_setcolor(mouseMask[2][0]);
		tgi_setpixel(mouseX+2,mouseY+2);
		tgi_setcolor(mouseMask[2][1]);
		tgi_setpixel(mouseX+3,mouseY+3);

		// Draw something
		MyDrawingRoutine();

		//Save Screen
		mouseX = info.pos.x;
		mouseY = info.pos.y;
		mouseMask[0][0] = tgi_getpixel(mouseX,  mouseY);
		mouseMask[0][1] = tgi_getpixel(mouseX,  mouseY+1);
		mouseMask[1][0] = tgi_getpixel(mouseX+1,mouseY);
		mouseMask[1][1] = tgi_getpixel(mouseX+1,mouseY+1);
		mouseMask[2][0] = tgi_getpixel(mouseX+2,mouseY+2);
		mouseMask[2][1] = tgi_getpixel(mouseX+3,mouseY+3);

		//Show mouse
		tgi_setcolor(COLOR_FORE);
		tgi_bar(info.pos.x, info.pos.y, info.pos.x+1, info.pos.y+1);
		tgi_line(info.pos.x+2, info.pos.y+2, info.pos.x+3, info.pos.y+3);
	}
}
```

**Comment by MohicanFr** [comment]
I made an interesting finding:

When using back background color / white front color, I can see a big white square where the mouse should be (it is an improvement).

Same goes for font: I can draw text when using back background color / white front color.

In the inverse color selection, neither mouse pointer nor text are displayed.

**Comment by oliverschmidt** [comment]
Maybe it's different with TGI but the mouse (pointer) is known to generally work with the graphics mode. The Contiki web browser supports a soft80 mode (running in the graphics mode) and the mouse (pointer) works just fine.

**Comment by MohicanFr** [comment]
Thank you for the reply.
I will try to experiment with the soft80 mode directly, and see if I get a pointer.
I really wonder why the text can only be displayed when using white on black?

**Comment by greg-king5** [comment]
The mouse pointer now is supported for the C64's TGI.  It's done the Soft-80 way, which means that you must remember to link a special object file to your program.  See the ["Graphics drivers"](http://cc65.github.io/doc/c64.html#graphics-drivers) section of the C64 document.

**Comment by MohicanFr** [comment]
Dear Greg,
Thank you for this link, I had read the section but completely overlooked this point.
However, I do not understand what is this special object file "c64-tgimousedata.o"
Is there a template somewhere for this file's sources? (a google search returns 0 results).
Thanks, Tony

**Comment by oliverschmidt** [comment]
Hi Tony,

Greg has created that file "for you". You need to get the latest cc65 in order obtain it.

Regards,
Oliver

**Comment by MohicanFr** [comment]
Ok, thank you Greg!!
I will try to build cc65 then (been using the binary release up-till now), and let you know if it works.
While you are kindly helping me, do you have some ideas about the other issue: 
   ->  TGI can draw text when using white font on black background, but the opposite does not work (black on white).

**Comment by oliverschmidt** [comment]
> I will try to build cc65 then (been using the binary release up-till now)

There's no need for that. http://sourceforge.net/projects/cc65/files/cc65-snapshot-win32.zip (and the content at http://software.opensuse.org/download.html?project=home%3Astrik&package=cc65) is automatically updated a vew minutes after each change to cc65.

**Comment by MohicanFr** [comment]
I have managed to rebuild with the c64-tgimousedata.o file in the build command as follows:
`cl65 -o C64-Studio.prg -O -t c64 C64-Studio.c asm\sqrt8.s asm\sqrt16.s c64-tgimousedata.o`

However, the result is still the same: the mouse pointer looks like a big white square.
![capture](https://cloud.githubusercontent.com/assets/6440924/22181998/0745a27e-e0dd-11e6-9d9e-e58417c297fc.PNG)

I tried laoding+initializing TGI first then the mouse, and vice-versa, but result is always the same.
(My codebase is here: https://github.com/MohicanFr/C64-Studio)

**Comment by greg-king5** [comment]
When you upgrade to a newer version of cc65, you should upgrade the assets that are copied from cc65.

**Comment by MohicanFr** [comment]
Doh, I feel stupid for that one!  I upgraded the drivers, and got the pointer to work.  :-)
Thanks a lot Greg, you are really kind.

Though this leads me to a couple more questions (sorry to keep bothering you):
(1) When I switch the palette (white background, black text), I can now draw font (great!). But the pointer is still shown in white (see screenshot below, pointer is on the sphere button). Is there a way to make the mouse pointer black?

![capture1](https://cloud.githubusercontent.com/assets/6440924/22190049/e7391196-e163-11e6-85c9-23cdb1217e81.PNG)

(2) I can only use "correctly" the colours white and black. If I try to set TGI_COLOR_GREY2/3 for the background, then TGI does not output anything. If I use TGI_COLOR_GREY1, then some stuff gets drawn but results are unpredictable (see second screenie).

![capture2](https://cloud.githubusercontent.com/assets/6440924/22190053/f1d1a21c-e163-11e6-9146-672b1e22f525.PNG)

Thank you in advance for all your help!

**Comment by greg-king5** [comment]
> (1) When I switch the palette (white background, black text), I can now draw the font (great!). But, the pointer is still shown in white (see screenshot below, pointer is on the sphere button). Is there a way to make the mouse pointer black?

The mouse API doesn't have a (portable) color function.  Therefore, you must "poke" the video chip directly:
```C
#include <cbm.h>
...
    VIC.spr0_color = COLOR_BLACK;
```

**Comment by MohicanFr** [comment]
Yes, it worked!!!  👍

**Comment by greg-king5** [comment]
>>(1) When I switch the palette (white background, black text), I can now draw the font (great!). But, the pointer is still shown in white (see screenshot below, pointer is on the sphere button). Is there a way to make the mouse pointer black?
>
>The mouse API doesn't have a (portable) color function.  Therefore, you must "poke" the video chip directly:
>```C
>#include <cbm.h>
>...
>    VIC.spr0_color = COLOR_BLACK;
>```

I had assumed that you wanted to change the pointer's color several times -- while the program is running.  But, I see now that you want  to change only its initial color.  Your program already had that code in it -- I didn't need to give you the above code lines!  Remove them; and, adjust [line 29 in "cc65-libmouse.h"](https://github.com/MohicanFr/C64-Studio/blob/master/include/cc65-libmouse.h#L29).

**Comment by MohicanFr** [comment]
Yes, it was as simple as that, I need to pay more attention... I will also turn off the mouse pointer.
I will try to look through my TGI colours problem again, and report back.
