### ISSUE TITLE
Multiplication optimization issue

### ISSUE THREAD

**Issue by DarwinNE** [cc65/cc65#367]
Hi,
  first of all, thanks for the truly great compiler.

I think I stepped into a situation where the optimization yields incorrect results (or in any case, different from those I get without `-Oi`).

Here is a sample program:
```c
#include <stdio.h>

void main(void)
{
    unsigned int y=192;
    unsigned int d=y&0xFFF8;
    unsigned int e=d*32+d*8;
    unsigned int f=d*40;
    
    printf("value 1: %d value 2: %d", e, f);
}
```
I can compile it in two different ways:
```sh
#!/bin/bash
cc65 -Oi -t c64 bug.c
ca65 bug.s
ld65 -o bug -t c64 bug.o c64.lib

cc65 -t c64 bug.c
ca65 bug.s
ld65 -o bug_not -t c64 bug.o c64.lib
```
With `-Oi`, the two `*32` and `*8` multiplications are (correctly) obtained by means of shifts; but, it seems that something is wrong when the results are put together.

With no optimization, the result is as follows:
~~~~~
value 1: 7680 value 2: 7680
~~~~~
With `-Oi`, the results differ:
~~~~~
value 1: 3072 value 2: 7680
~~~~~

BTW, here is the revision of cc65 I am employing:
~~~~~
$ git log -1
commit 1fc2dfb64f6a02c30be199f22b1bd7fe123e3847
Merge: 5878155 1b4a7e3
Author: Oliver Schmidt <ol.sc@web.de>
Date:   Tue Dec 27 22:27:00 2016 +0100

    Merge pull request #363 from kylophone/master
    
    doc/ca65: fix typo
~~~~~

Hope it helps!
Cheers, Davide

**Comment by IrgendwerA8** [comment]
Problematic sequence:
Unoptimized:
```
        jsr     shlax4
	jsr     shlax1
	jsr     pushax
	ldy     #$03
	jsr     ldaxysp
	jsr     shlax3
	jsr     tosaddax
```
Optimized:
```
        jsr     shlax4
	stx     tmp1
	asl     a
	rol     tmp1
	sta     ptr1
	iny
	lda     (sp),y
	tax
	dey
	lda     (sp),y
	jsr     shlax3     ; <--- makes use of tmp1, where also the other operand is stored
	clc
	adc     ptr1
	pha
	txa
	adc     tmp1
	tax
	pla
```

A lazy fix would just change the usage of tmp1 to an other zp-var in shlax, but that's not what I would call substantial. Seems to me a general problem with tmp-var distribution while inlining.
