### ISSUE TITLE
rs232.h

### ISSUE THREAD

**Issue by MohicanFr** [cc65/cc65#372]
Dear Devs,

I am trying to compile this 4 years old piece of code (I want to get my C64 application talking to a central website): https://github.com/mrtos/protocols/tree/master/%E7%BD%91%E7%BB%9C%E5%8D%8F%E8%AE%AE_Network/TCPIP_stack/UIP/CODE/UIP-0.6/CC65

Unfortunately, the RS232.h header has disappeared from CC65 in the meantime... is there perhaps a more up-to-date version of uIP that is compatible with latest CC65?

(Also, where may I find drivers for the RR-Net, as available on the Chameleon?)

Many thanks in advance!
Tony

**Comment by oliverschmidt** [comment]
- From the perspective of the original uIP authors the standalone uIP project is dead for many years (way more than 4). uIP has become part of Contiki. See https://github.com/contiki-os/contiki/tree/master/core/net/ip and https://github.com/contiki-os/contiki/tree/master/core/net/ipv4. There it is maintained up to date.

- There is a port of Contiki for the C64. See https://github.com/contiki-os/contiki/tree/master/platform/c64. This is maintained by me. It is compatible (and in fact relies on) the latest cc65 available from this repo.

- Currently Contiki for the C64 doesn't support SLIP. Rather it requires an Ethernet cart. However there's right now work going on to bring back SLIP support to Contiki for the C64. Stay tuned to the Contiki repo updates if you are interested in this.

- cc65 support for RS232 is now in https://github.com/cc65/cc65/blob/master/include/serial.h. See http://cc65.github.io/doc/c64.html#ss7.5 for C64-specific infos. The upcoming SLIP support in Contiki for the C64 will be based on this API.

- The RR-Net driver used by Contiki for the C64 is maintained by me as part of Contiki. See: https://github.com/contiki-os/contiki/blob/master/cpu/6502/net/cs8900a.S

**Comment by MohicanFr** [comment]
Wow, that is a lot of info Oliver! But I am glad to see that you are actively supporting this matter.
It's gonna take me a while to extract what I need from Contiki though: a simple way (non-threaded) of sending a HTTP request and waiting for an answer back. It would be nice if cc65 offered such ability (HTTP lib) together with drivers for the various ways of accessing the internet (modem, ethernet modules).
In my case, I would like to make my application talk to a website (maybe via XML-RPC), to upload/download STL files. I am also pondering further down the line making some online game for the C64.

**Comment by oliverschmidt** [comment]
I must admit that I don't understand why you need /want to extract something from Contiki. Maybe you rather want to use Contiki ;-) The WGET example (https://github.com/contiki-os/contiki/blob/master/examples/wget/wget.c) seems to be pretty close to what you want to archive. 

Something like HTTP I/O is way beyond the scope of cc65. Apart from that I don't see how having the code in cc65 instead of Contiki would improve anything.

And what you say about 'simple': For your first use case simple would maybe mean some synchronous blocking API. But what if it doesn't work within a few seconds and you run into some timeout? Don't you want the user to be able to abort the operation? At this point you're already done with 'simple' ;-))

And if your online game does more than just upload / download high scores than you need to interleave game logic / video update with network I/O, don't you? I don't see how that works with a "simple (non-threaded)" approach. Anyhow your two use cases already show that there's for sure no one-size-fits-all when it comes to 6502 internet working. And that's another reason why that doesn't belong into cc65 which is intended to be generic.

Apart from that you'll very likely run into memory shortage when trying to combine uIP/Contiki with a substantial game in 64kB. I'm almost sure that https://github.com/oliverschmidt/ip65 much better fits your bill. In contrast to uIP/Contiki it's written in 6502 asm and supports just one TCP connection. Find a rudimentary HTTP client at https://github.com/oliverschmidt/ip65/blob/master/test/geturl.s. I've taken over maintenance of that thingy too but don't expect any support from my side.

**Comment by mrdudz** [comment]
for a game i'd just hack some simple rr-net specific code to send and recive UDP ... TCP is a bit much for the poor c64 to handle in reasonable amount of time :)

**Comment by oliverschmidt** [comment]
- IP65 comes in two flavors: One with TCP support an one without.

- When you "just hack some UDP code" then you neither have ARP nor DHCP nor DNS. Usually people want to have at least the first two but don't think about it ;-))

**Comment by MohicanFr** [comment]
Thanks for the good info again Oliver. I will go and check ip65 right now. 
I am making a simple 3d modelling app for the c64, and want to link it to a website on which people can share their models, perhaps even order 3D prints. So I am talking about securely uploading/downloading stl model files with some info (such as user login) using xml-rpc to a Drupal type website.

**Comment by MohicanFr** [comment]
Alright, I could build the IP65 lib and test samples, and run them in WinVICE.
I am super happy with this, though... I now gotta plunge into the assembly code of those samples next.
But thanks a lot for the very useful pointers Oliver!

**Comment by MohicanFr** [comment]
Sorry to be a pain... I need a little advice....
I was able to compile geturl.s and run it. So I copied the IP initialization code and put it into a new file of my project called "http.s" as follow:

`.import ip65_init
.import dhcp_init

.ifdef A2_SLOT_SCAN
.import a2_set_slot
.endif

.macro init_ip_via_dhcp
.ifdef A2_SLOT_SCAN
  lda #1
: pha
  jsr a2_set_slot
  jsr ip65_init
  pla
  bcc :+
  adc #0
  cmp #8
  bcc :-
:
.else
  jsr ip65_init
.endif
  php
  ;print_driver_init
  plp
  bcc :+
  ;print_failed
  sec
  jmp @end_macro
: ;print_ok
  ;print_dhcp_init
  jsr dhcp_init
  bcc :+
  ;print_failed
  sec
  jmp @end_macro
: ;print_ok
  clc
@end_macro:
.endmacro

.export init_network,_init_network

init_network:
.proc _init_network
  init_ip_via_dhcp
  rts
.endproc`

The try to recompile with: 

`cl65 -o C64-Studio.prg -O -t c64 C64-Studio.c asm\http.s asm\sqrt8.s asm\sqrt16.s c64-tgimousedata.o -L libs ip65_tcp.lib c64combo.lib c64.lib`

But I get the error:

> c64.cfg(15): Segment `BSS' overflows memory area `BSS' by 1595 bytes
ld65: Error: Cannot generate most of the files due to memory area overflow

Does that mean my program has become too big??

>

**Comment by MohicanFr** [comment]
After integrating the geturl.s code into my project, I get this error message when compiling:

> Segment `BSS' overflows memory area `BSS' by 2487 bytes
ld65: Error: Cannot generate most of the files due to memory area overflow

Does that mean my program has become too big for the c64's memory after adding the IP65 lib?

**Comment by MohicanFr** [comment]
Seems to be the case... :-(
I can compile with "ip65.lib c64rrnet.lib", but not with "ip65_tcp.lib c64combo.lib".

**Comment by oliverschmidt** [comment]
> I am making a simple 3d modelling app for the c64, and want to link it to a website on which people can share their models, perhaps even order 3D prints. So I am talking about securely uploading/downloading stl model files with some info (such as user login) using xml-rpc to a Drupal type website.

- I don't see how you'll fit a complex program + any type of internet working into a single program. My guess is that you'll have to resort to writing the files in question to disk and do the upload/download in a separate program.

- I guess "securely" refers to using https (in contrast to http). https (and in fact any type of modern crypto stuff) is __WAY__ out of bounds for the C64. Never ever. If https is obligatory you'll need some proxy. I see two viable options:
a) Cloud based: I.e. https://cloud.google.com/appengine/ offers 1 GB traffic for free per day. It allows for inbound http and outbound https. You could write a relatively simple app there.
b) Local: The usual suspect would be a Raspberry Pi. You could write some Python script or alike to pocess your inbound http and create outbound https. Using a RPi3 with integrated WLAN would allow to connect the RR-Net to its Ethernet port and do the outbound traffic via WLAN.

However the RPi brings you these thoughts. Is it necessary to do http at all to the RPi. No you can use any TCP protocol. But why TCP at all? UDP works as well in a local LAN. If you hook up the RR-Net directly to the RPi and use it WLAN for the outbound traffic then you have a point-to-point connection between the RR-Net and the RPi. Then you don't need IP at all. Just transmit raw Ethernet frames. And finally: Why use Ethernet at all? The RPi has GPIO and can be connected to the C64 in way more natural to the C64. See i.e. https://github.com/Flogistoni/raspbiec You could customize that in a way that some file written to the RPi triggers the file to be uploaded to some https site - or define custom IEC commands.

A side effect of such an approach would be that it reduces the memory footprint on the C64 in a way that your complex program might be able to archive it...

Just some thoughts,
Oliver

**Comment by oliverschmidt** [comment]
> But now... gotta plunge into the assembly code of those samples next.

Ooops. I wasn't aware that you're not into assembly already. The IP65 library was originally not compatible with cc65 C program at all. I removed two issues: a) Linker config / segment issues. b) Zero page usage issues. However there's at least one issue left: Interrupt usage. Iguess the way IP65 uses interrupts breaks the cc65 interrupt usage or the other way round, but I don't know and haven't tried. apart from that there's no C-callable interface in IP65. And IP65 provides incoming data to callback functions. Again not C-callable. So I'm not sure if integrating IP65 into a C program is the right task for an assembler newbie...

**Comment by oliverschmidt** [comment]
> I can compile with "ip65.lib c64rrnet.lib", but not with "ip65_tcp.lib c64combo.lib".

That's a pretty clear sign that you're not doing something generally wrong but actually running out of memory. Not surprising. The cc65 C compiler does some optimizations but the generated code is still pretty large. So a lot of C code means quite some memory alread used. You'll need something like:
- Overlays (see https://github.com/cc65/cc65/blob/master/samples/overlaydemo.c for the limited overlay support in cc65)
- Several programs (the C64 C libary supports http://cc65.github.io/doc/funcref.html#ss3.90)
- "Outsourcing" internetworking to another machine like a RPi

**Comment by MohicanFr** [comment]
From what you say here, it is clear to me now: I need to write the uploader/downloader as a separate application. I will use "exec" to switch back and forth between the two apps.
Thanks so much for the generous support you are giving me.
