### ISSUE TITLE
ca65 macro in scope namespace bug

### ISSUE THREAD

**Issue by ARM9** [cc65/cc65#403]
Calling a macro defined in a scope from outside of the scope has some surprising behaviour. It's as if macro definitions ignore scopes entirely, let me know if this is intended or a bug.

```
.scope Foo  ; same issue with .proc
    .macro Bar
        .assert 0, warning, "This doesn't work when called as Foo::Bar"
    .endmac

    Bar         ; works
.endscope

Bar         ; works
Foo::Bar    ; does not work, results in a 'Error: `:' expected'
```

**Comment by greg-king5** [comment]
It's intended.  Macroes have a separate namespace.

**Comment by oliverschmidt** [comment]
This issue was phrased as question and the question was answered so I close this.
