### ISSUE TITLE
C ZP vars regressed

### ISSUE THREAD

**Issue by clbr** [cc65/cc65#409]
The current master produces invalid assembly for C files that put variables in ZP. I have a known working version from Jan 2016, seeing if I could bisect this.

```c
#pragma bss-name (push,"ZEROPAGE")
#pragma data-name (push,"ZEROPAGE")

char oam_off;

#pragma data-name(pop)
#pragma bss-name (pop)
```

Today's master produces this:
```asm
;
; File generated by cc65 v 2.15 - Git fe59626
;
        .fopt           compiler,"cc65 v 2.15 - Git fe59626"
        .setcpu         "6502"
        .smart          on
        .autoimport     on
        .case           on
        .debuginfo      off
        .importzp       sp, sreg, regsave, regbank
        .importzp       tmp1, tmp2, tmp3, tmp4, ptr1, ptr2, ptr3, ptr4
        .macpack        longbranch
        .export         _oam_off

.segment        "DATA"

.segment        "ZEROPAGE"
.segment        "DATA"

.segment        "BSS"

.segment        "ZEROPAGE"
.segment        "BSS"
_oam_off:
        .res    1,$00
```

As you can see, the var does not go to ZP. Here's the correct output, from cc65 from Jan 2016.

```asm
;
; File generated by cc65 v 2.15 - Git 24c2da9
;
        .fopt           compiler,"cc65 v 2.15 - Git 24c2da9"
        .setcpu         "6502"
        .smart          on
        .autoimport     on
        .case           on
        .debuginfo      off
        .importzp       sp, sreg, regsave, regbank
        .importzp       tmp1, tmp2, tmp3, tmp4, ptr1, ptr2, ptr3, ptr4
        .macpack        longbranch
        .export         _oam_off

.segment        "DATA"

.segment        "ZEROPAGE"
.segment        "DATA"

.segment        "BSS"

.segment        "ZEROPAGE"
_oam_off:
        .res    1,$00
.segment        "BSS"
```

(note the git sha is wrong, because the build system does not force-update version.o when the git rev changes)

**Comment by clbr** [comment]
730d01a25f3440bd5bdca3a3cf8068287ff52f6a is the culprit. The parent produces correct code, that commit adds this bug.

**Comment by clbr** [comment]
Checking if I can ping @pfusik.

**Comment by pfusik** [comment]
I wasn't aware of these pragmas nor I've seen them in tests.

Before I come with the fix, can you explain which segment the variable should go into in the following case?

    char oam_off;
    #pragma bss-name (push,"ZEROPAGE")
    #pragma data-name (push,"ZEROPAGE")
    char oam_off;

(more generally: multple tentantive definitions, each in a different segment)
Perhaps that should give a compile-time error?

**Comment by clbr** [comment]
That should be a compile time error, like it is in gcc (sans pragmas).

**Comment by pfusik** [comment]
Another tricky case is:

#pragma bss-name (push,"ZEROPAGE")
    char x;
    char x = 1;

Here, x is NOT zeropage.
