### ISSUE TITLE
cprintf writes outside of the screen memory area

### ISSUE THREAD

**Issue by spektro** [cc65/cc65#413]
Conio library's cprintf() function writes outside of the screen memory area when it reaches the bottom of the screen. I've tested this with Commodore Plus/4.

Plus/4's BASIC RAM (0x1000) begins right after the screen memory area (0x0800-0x0fff). When you run the test program below, you can see that it corrupts the beginning of the BASIC RAM.  If you change the for loop condition to say 'counter < 280', cprintf corrupts the running program so badly that it jams.

```
#include <conio.h>
void main ( void );

void main ( void ) {
   unsigned int counter;
   clrscr ();
   for ( counter = 0; counter < 80; ++counter ) {
      cprintf ( "Hello wolrd! " );
   }
}
```

**Comment by mrdudz** [comment]
that is expected behaviour - conio does not support scrolling

**Comment by spektro** [comment]
OK. It would be good to mention that in the conio documentation.

**Comment by oliverschmidt** [comment]
> It would be good to mention that in the conio documentation.

https://github.com/cc65/wiki/wiki/Direct-console-IO
