### ISSUE TITLE
Inconsistent handling of code generation options ?

### ISSUE THREAD

**Issue by oliverschmidt** [cc65/cc65#415]
Looking at https://github.com/cc65/cc65/blob/master/src/cc65/codeseg.c#L484-L486, I'm wondering why exactly 2 of the 12 stackable options (see https://github.com/cc65/cc65/blob/master/src/cc65/global.h#L61-L73) are copied.

**Comment by greg-king5** [comment]
It isn't a general copying operation; it's done for the optimizer, which runs _after_ a function has been compiled.  `Optimize` and `CodeSizeFactor` are the only ones that are needed by the optimizer.  If those assignments weren't done, then the optimizer would use the `#pragma optimize()` and `#pragma codesize()` that were current at the end of the function.  I assume that Uz felt that it is more intuitive to use the ones that were current at the start of the function.

(Note that PR #285's "`__asm__ volatile`" is an exception.)

**Comment by oliverschmidt** [comment]
Hi Greg,

First of all thanks for the fast and helpful feedback :-)

> it's done for the optimizer, which runs _after_ a function has been compiled.

Ah, I see!

> Note that PR #285's "__asm__ volatile" is an exception.

I noticed the `CS->Code->Optimize = 0;` before. I'm not sure what it is an exception from. However I now seem to understand that it needs to override the previously made copy in order to be actually in effect as the optimizer will later look at that copy.

**Comment by greg-king5** [comment]
> I'm not sure what it is an exception from.

`__asm__ volatile` is an exception from the "rule" that says, "The lines within a function's definition cannot change that function's optimizer settings."

For example:
```C
#pragma optimize(on)
int squeeze(void)
{
    ...
#pragma optimize(off)
    ...
    return result;
}

int expand(void)
{
    ...
#pragma optimize(on)
    ...
    return result;
}
```
The optimizer was turned off while `squeeze()` was being defined; it was turned back on while `expand()` was being defined.  But, `squeeze()` will be optimized, and `expand()` won't be optimized.

**Comment by oliverschmidt** [comment]
> `__asm__ volatile` is an exception from the "rule" that says, "The lines within a function's definition cannot change that function's optimizer settings."

Thanks for the explanation! I was more thinking along the lines of an "exception to the usual implementation" than an "exception to the usual rule". That got me wondering...
