### ISSUE TITLE
ca65: Add support for Famicom Disk System (*.FDS) images

### ISSUE THREAD

**Issue by TheRealHamtaro126** [cc65/cc65#419]
Can it be possible to add support for building Famicom Disk System (*.FDS) images into CA65? it's viable for homebrewers to make and rewrite disks for that system. and is an important to add to CA65, too!

Also, make sure please tell people to get the FDS BIOS and the disk-based copy protection file (KYODAKU) files themselves, for copyright reasons!

**Comment by mrdudz** [comment]
thats not something the cc65 toolchain should do, imho. for example it does not contain tools to build C64 diskimages either.

**Comment by silverdr** [comment]
Exactly. Such things simply do not belong to cc65 yet are easily integrated on the build system level, using original, specialised tools, instead. 
--

**Comment by oliverschmidt** [comment]
@TheRealHamtaro126: Thanks for your interest in cc65. However I fully agree with the other comments - and therefore close this.

**Comment by nicklausw** [comment]
@TheRealHamtaro126 there's always the option to make a set of macros for things like this, or a cfg file.

**Comment by polluks** [comment]
@TheRealHamtaro126 indeed, you need a new config because of the ROM header.

**Comment by bbbradsmith** [comment]
I don't think there's any need for "support", you can already do everything you need with a suitable config file. I made an example here:
https://forums.nesdev.com/viewtopic.php?p=193241#p193241

**Comment by oliverschmidt** [comment]
@bbbradsmith:

Maybe you want to add (some of) that information to the cc65 Wiki on a new page (linked at https://github.com/cc65/wiki/wiki#target-platforms). You're already a cc65 Wiki editor.
