### ISSUE TITLE
Commodore 64 File Path

### ISSUE THREAD

**Issue by SpaceboyRoss01** [cc65/cc65#423]
I'm building a program, and I can't read the tmp, bin, and dev directories. I can only read the root. All that I know with the paths are that you can use . as getting the current directory, a number with : will get you a disk.

**Comment by SpaceboyRoss01** [comment]
Why is this clossed

**Comment by mrdudz** [comment]
short answer: those things do not exist

**Comment by SpaceboyRoss01** [comment]
Then why can I read the disk's folders and files
