### ISSUE TITLE
Why default to -O?

### ISSUE THREAD

**Issue by clbr** [cc65/cc65#428]
I wonder why the cc65 suite is built at -O1 by default. -O3 is perfectly safe for compliant code, and the speed difference even for a compiler is nice.

Test suite at -O1 (default): 66s
Test suite at -O3: 57s, 13.6% improvement

**Comment by nicklausw** [comment]
All I've heard is some arguments against usage of -O3 for creating more code than is actually necessary. -O2 seems perfectly safe, though.

**Comment by MonteCarlos** [comment]
Whats -O3 in terms of -Oirs?

**Comment by oliverschmidt** [comment]
> I wonder why the cc65 suite is built at -O1 by default.

Likely because it was considered more than fast enough so far.

> Test suite [...]

Indeed, the test suite make is long enough to make "faster" noticable or even desirable.

From what I read on the Net `-O3` seems reasonable.

**Comment by clbr** [comment]
> Whats -O3 in terms of -Oirs?
-Oirs ^ 15.

**Comment by greg-king5** [comment]
This issue is talking about building the tools.  `src/Makefile` puts `-O` into the `CFLAGS` variable.

**Comment by oliverschmidt** [comment]
Fixed with https://github.com/cc65/cc65/commit/298dda0e71646112f0d0a57146acbb3a62a145fd.
