### ISSUE TITLE
#pragma wrapped-call fails on fastcall with parameters and -O.

### ISSUE THREAD

**Issue by bbbradsmith** [cc65/cc65#432]
Functions with `__cdecl__` / `--standard` seem to be fine, since they do not use the registers to pass arguments, but the new wrapped-call feature seems to break the default `__fastcall__` convention when optimizations (`-O`) are used:
```
void trampoline(void);
#pragma wrapped-call (push, trampoline, 32)
int func_c(long arg)
{
   return arg +3;
}
#pragma wrapped-call (pop)

; without -O func_c(7) produces:
   ldx     #$00
   stx     sreg
   stx     sreg+1
   lda     #$07
   ldy     #32
   sty     tmp4
   ldy     #<(_func_c)
   sty     ptr4
   ldy     #>(_func_c)
   sty     ptr4+1
   jsr     _trampoline

; with -O func_c(7) produces:
   ldy     #32
   sty     tmp4
   ldy     #<(_func_c)
   sty     ptr4
   ldy     #>(_func_c)
   sty     ptr4+1
   jsr     _trampoline
```
Notice that somehow the optimizer had completely omitted the argument setup. It seems like it's not properly connected to the wrapped-call and it just drops them?

There is a similar problem with variadic functions. Since the wrapped-call preamble clobbers Y, they lose the information about the stack size that should be passed in Y. (Same for functions without prototype, but that's an obscure case.)

While I'm asking about this feature, I think the document could use some more description of the responsibilities of the trampoline function since it is a bit intimately tied with the calling conventions e.g. it will likely have to preserve arguments/return values from A/X while it does its bankswitching...

I left some notes about that at the NESDev forum here:
[https://forums.nesdev.com/viewtopic.php?p=196106#p196106](https://forums.nesdev.com/viewtopic.php?p=196106#p196106)

**Comment by clbr** [comment]
In my tests, variadic functions add the Y value after the preamble, and the code works without -O.

**Comment by clbr** [comment]
The guilty optimization functions are OptUnusedLoads and OptUnusedStores. Looking into them.

**Comment by bbbradsmith** [comment]
Ah, looking again at my test where the variadic function lost its Y it was also due to the optimizer, it seems. The Y value was coincidentally equal to the last pushed argument, and the Y setup got omitted. (I can provide an example if needed, though it's probably the same problem as with the fastcall functions.)
