### ISSUE TITLE
Question: Custom Linker CFG file without custom crt0 file.

### ISSUE THREAD

**Issue by OzHawk** [cc65/cc65#434]
I was not able to find a cc65 specific forum to ask this question, and it seems to be a change from the earlier behaviour, but...

Is it possible to have a custom CFG file but use the default crt0 file?  The VIC20 has lots of different memory configurations but the runtime file doesn't necessarily need to change, or if you use a custom CFG file, then you are by default using a custom platform and so need to do everything manually?

Hawk

**Comment by greg-king5** [comment]
> I was not able to find a cc65 specific forum to ask this question, and it seems to be a change from the earlier behaviour; but ...

You can ask questions like this on our mailing list.  You can learn about it at
http://cc65.github.io/cc65/mailing-lists.html#cc65-devel

> Is it possible to have a custom CFG file, but use the default crt0 file?  The VIC20 has lots of different memory configurations; but, the runtime file doesn't necessarily need to change; or, if you use a custom CFG file, then you are by default using a custom platform, and so need to do everything manually?

Yes, the start-up code isn't affected by the memory configuration.  It's independent of its location.  And, the linker tells it how much RAM that it should expect to be available.

The cc65 project has two CFG files for the VIC-20:

1. for the unexpanded machine (the default `vic20.cfg`),
2. for the fully expanded machine (`vic20-32k.cfg`).

Only some start addresses and the size of the `main:` memory area are different between those files.  The function library (including CRT0) is the same for both configurations.

**Comment by oliverschmidt** [comment]
@greg-king5: Thanks for explaining.
