### ISSUE TITLE
library source should be shared for C16 and Plus4

### ISSUE THREAD

**Issue by mrdudz** [cc65/cc65#461]
The C16 is basically the same as the Plus4, the Plus4 has more memory and a builtin ROM with (rather useless) applications. A C16 expanded to 64K RAM can run anything a Plus4 can. Most, if not all, library code can probably be used for both, and the only differences can be handled by a linker .cfg

**Comment by oliverschmidt** [comment]
Maybe / likely the best was to fix this issue would be to handle the targets `c16` and `plus4` as a pair in the same way the pairs `apple2`/`apple2enh`, `atari`/`atarixl` and `sim6502`/`sim65c02` are treated - see https://github.com/cc65/cc65/blob/master/libsrc/Makefile#L150

**Comment by groessler** [comment]
#612 is the same, and has better content.....
