### ISSUE TITLE
Segmentation Faults and assertions 2017-07-24

### ISSUE THREAD

**Issue by rwhitworth** [cc65/cc65#469]
Hello, I was using American Fuzzy Lop (afl-fuzz) to fuzz input to the `cc665` program on Linux. Is fixing the crashes from these input files something you're interested in? The input files can be found here: https://github.com/rwhitworth/cc65-fuzz/tree/master/2017-07-24

The files can be executed as `./cc65 id_filename` to cause seg faults and trigger assertions.  Details and sample backtraces can be found in the linked repo.

Let me know if I can provide any more information to help narrow down this issue.

**Comment by oliverschmidt** [comment]
Hi,

First of all thanks for your interest to improve cc65.

If you would have written 'Are fixes of the crashes ... something you're interested in?' I would have answered 'Yes' ;-) But for 'Is fixing the crashes ...' the answer is 'No'.

Regards, Oliver

**Comment by rwhitworth** [comment]
I completely understand and appreciate your frankness.

Feel free to close this, or leave it open in the hopes of another contributor finding it.  Your call.
