### ISSUE TITLE
Can't open or create a text file on Apple2 with fopen & default file type is wrong

### ISSUE THREAD

**Issue by gungwald** [cc65/cc65#470]
For Apple2 ProDOS fopen is hard-wired in open.s to open/create a file of type binary ($06). According to the C standard, the default file type should be text, not binary. Binary is specified by adding a "b" to the mode parameter. See https://en.wikibooks.org/wiki/C_Programming/stdio.h/fopen

So this creates two problems:
1. The default file type is wrong. It should be text, according to the standard.
2. It is impossible to open or create a text file. fopen actually fails with an error when attempting to open an existing text file.

I'm looking at what it would take to fix this. I think I can make the changes. To start, fcntl.inc will need an O_BINARY constant. This is how it's done on Windows, where there is a difference between text and binary file formats.

**Comment by oliverschmidt** [comment]
You write about two problems:

* Regarding 2. This isn't true. Check out https://github.com/cc65/cc65/blob/master/include/apple2.h#L142

* Regarding 1. I don't agree with you. The URL you refer to says that "although operating systems are not required to distinguish between the two". This is an interpretation that I don't see based on any standard. My interpretation is that the two should should look the same to the operating system. In my interpretation the mode should only - potentially - "translate" the data written to the file or read from the file. So one could argue that on the Apple II a text mode file should have \n translated to/from \r and/or that the MSB should be set/cleared. But I wouldn't want those translations as they are (too) slow/large to justify their use cases. Especially given that the linker could not decide to not include the translation code if not needed. Or seen from another perspective: That binary/text mode is about switching between two things, but there are many ProDOS file types without even talking about the auxtypes (see http://www.easy68k.com/paulrsm/6502/PDOS8TRM.HTM#B.4.2.4) so the binary/text mode just isn't the right approach to tackle the Apple file type problem.

**Comment by gungwald** [comment]
Great response. Thanks.

- Regarding 2. I was unaware of this, but after further thought, this is the best way to get around the fact that C doesn't have a way to specify the file type that Apple2 requires. I had read the doc, but I didn't look at the header. I had not connected the _filetype variable with the ability to specify that for an open or create operation. I would like to do 2 things to help with this:
1. Submit a documentation update that includes additional detail on how to use the _filetype in conjunction with fopen to open a file of any type, probably including some example code.
2. Submit a code update that adds the definitions of all the known file types to apple2.h.

- Regarding 1. I understand that your objection has to do with the binary/text mode in C relating to whether translation is done to the data, rather than a type property that is attached to a file by the operating system. And to claim that there was a text mode would also claim that translation would be done, which is not the case and is not desirable either. This is a good point. Although this leaves a confusing inconsistency between C's definition of text/binary and Apple2's definition of text/binary, you are probably right. From C's perspective, there is no translation, so it is binary mode, regardless of the Apple2 file type. I may propose an update to the documentation to call this out.

**Comment by oliverschmidt** [comment]
> I was unaware of this [...]

Which is no surprise as it isn't documented ;-)

> Submit a documentation update that includes additional detail on how to use the _filetype in conjunction with fopen to open a file of any type, probably including some example code.

That would be appreciated :-) I presume it would include _auxtype beside _filetype. Please understand (and document) that both open() and fopen() make use of those variables. I'd see the update as a new section in http://cc65.github.io/doc/apple2.html#s9 (and http://cc65.github.io/doc/apple2enh.html#s9).

> Submit a code update that adds the definitions of all the known file types to apple2.h.

That would be appreciated too. Please use https://github.com/cc65/cc65/blob/master/include/apple2.h#L111-L128 as template regarding the style.

> From C's perspective, there is no translation, so it is binary mode, regardless of the Apple2 file type.

That's basically the point.

Another aspect is that beside Windows nobody ever used that text mode thingy. It could have been used by Apple on MacOS too to translate between \r and \n - but (at least as far as I could investigate) was _not_. From that perspective I would even go so far to say that if cc65 would do a translation (and would do it by default to be fully consistent with Windows) than this would likely be more surprising to more users than doing it not.

> I may propose an update to the documentation to call this out.

I'm a little unsure about documenting "all the things that aren't" because that set is basically infinite ;-) However I follow you in that some people might be at least wondering if there's a translation and that it therefore might be worth pointing out that there's no. I'd see this statement in the same section as the one one the usage of the two variables.

**Comment by gungwald** [comment]
Great! I will follow your suggestions. Thanks.

**Comment by groessler** [comment]
On 07/25/17 20:12, Oliver Schmidt wrote:

> Another aspect is that beside Windows nobody ever used that text mode 
> thingy. It could have been used by Apple on MacOS too to translate 
> between \r and \n - but (at least as far as I could investigate) was 
> /not/.
>

Hmm,

DOS
OS/2
TOS (Atari ST)
(and, I think) MacOS9 and earlier (which conflicts with your statement, 
I think we need to try out to be sure... :-) )


regards,
chris

**Comment by oliverschmidt** [comment]
> DOS - OS/2

I was well aware of that but as the article linked in the original message (https://en.wikibooks.org/wiki/C_Programming/stdio.h/fopen) refers to Windows only so I kept that as placeholder for "all OSes with roots in DOS".

> TOS

That's interesting. What translation is done there for text files?

> MacOS9

That's what I explicitly presumed but didn't find any hint to.

**Comment by groessler** [comment]
On 07/25/17 20:33, Oliver Schmidt wrote:

>     DOS - OS/2
>
> I was well aware of that but as the article linked in the original 
> message (https://en.wikibooks.org/wiki/C_Programming/stdio.h/fopen) 
> refers to Windows only so I kept that as placeholder for "all OSes 
> with roots in DOS".
>


Ok. Didn't read the linked article before.


>     TOS
>
> That's interesting. What translation is done there for text files?
>


Same like for DOS (CR/LF <--> LF). I consider it as also having roots in 
DOS.


>     MacOS9
>
> That's what I explicitly presumed but didn't find any hint to.
>


If we really want to find out (somehow off-topic here on cc65), you know 
me :-) , I've got an Apple Mac which runs OS9 and also has CodeWarrior 
(C  compiler) installed. So I could check it out.

But, the bigger question is, do we want to support this?
On the Atari, there's this problem, too. It uses 0x9B as end-of-line. 
And all of the CBMs seem to use 0x0D as end-of-line.

I'd like to have it supported, but somehow don't like the memory penalty 
to pay....


regards,
chris

**Comment by spiro-trikaliotis** [comment]
I seem to remember that there historically systems that did not have newline at all. I could not find a web reference of it at the moment, only a "hint" here:

https://unix.stackexchange.com/questions/18743/whats-the-point-in-adding-a-new-line-to-the-end-of-a-file
> There are a few OSes out there which don't have a newline character, but instead have fixed- or variable-sized records; on these systems, the mapping from files to C source introduces a \n at the end of each record.

Oh, OpenVMS seems to use a record based format:

https://en.wikipedia.org/wiki/Newline
> OpenVMS uses a record-based file system, which stores text files as one record per line. In most file formats, no line terminators are actually stored, but the Record Management Services facility can transparently add a terminator to each line when it is retrieved by an application. The records themselves could contain the same line terminator characters, which could either be considered a feature or a nuisance depending on the application.

As far as I remember from the article I wanted to find, this also applies to VMS.

Note also the comment about fixed line length systems for early mainframe systems at the same place:

> Fixed line length was used by some early mainframe operating systems. In such a system, an implicit end-of-line was assumed every 72 or 80 characters, for example. No newline character was stored.

Of course, I doubt anyone will implement OpenVMS or an early mainframe system on a 6502, so, this is a theoretical thing only. But this could help to understand why the difference between text and binary fopen() is so important in C.

**Comment by gungwald** [comment]
The default fopen(filename, "r") assumes text translation. You have to add the "b" to stop the translation. This is how it works with Windows, DOS, and OS/2. I have written for all of these. So, right now the behavior of cc65 is inconsistent with the largest percentage of the world's systems. Of course, if you add translation, it would not make sends to translate Apple2 binary files. You would only want to do that to Apple2 text files.

**Comment by gungwald** [comment]
I understand that from a UNIX developer's (me) point of view, this is all nonsense. But, that is the way Windows is.

**Comment by spiro-trikaliotis** [comment]
>>>     TOS
>> That's interesting. What translation is done there for text files?
>Same like for DOS (CR/LF <--> LF). I consider it as also having roots in DOS.

As GEMDOS mimics MS-DOS, this is very likely. ;)

Examples for GEMDOS mimicing MS-DOS:

Terminate a program:
* GEMDOS ("old MS-DOS 1.x variant"):
    CLR.W -(SP)
    TRAP #1 

* MS-DOS ("old MS-DOS 1.x variant")
    MOV AX,0
    INT 21h

* GEMDOS ("new MS-DOS 2.x variant")
    MOVE.W #42,-(SP)   ; 42 being the returned value
    MOVE.W #$4C,-(SP) ; call function $4C for termination with a return code
    TRAP #1

* MS-DOS ("new MS-DOS 2.x variant")
    MOV AL,42h
    MOV AX,4Ch
    INT 21h

GEMDOS has the PSP, has the FCB blocks in it, stores the command-line in the PSP (which is overwritten by an FCB block once it is used), and so on. Thus, GEMDOS essentially was an MS-DOS clone for 68000 machines.

GEMDOS was built this way so that GEM could be held rather similar for MS-DOS and TOS.

**Comment by oliverschmidt** [comment]
> I'd like to have it supported, but somehow don't like the memory penalty
to pay....

Yep, me too. We didn't have this feature from day one and I can't remember people complaining about it missing until this issue. So I don't think it would be appropriate to pay the memory prize (and the performance prize on anything faster than the stock CBM DOS).

If we REALLY wanted it then from my pov we would need to start out with extending the build system to nicely build several C libraries per target. Then we would come up with the notion of "minimal" C libraries vs. "extended" C libraries. And then we could discuss adding text mode support to the "extended" C libraries (maybe together with some of the already existing C library compile time switches for the ATARI).

However I don't see a momentum for this effort so we're from my pov done with this topic...

**Comment by gungwald** [comment]
i think most people just figure out how it works and go with it, not worrying about whether it's correct or not. Most people probably don't know what the standard says anyway so they wouldn't be able to determine if it is correct or not. Without the true text mode with translation, I would say it violates the standard. But, I think that's OK if there is a good reason, which is that the performance penalty on an 8-bit, 1 MHz machine would be too great.
