### ISSUE TITLE
Simple boolean expression fails to parse

### ISSUE THREAD

**Issue by fo-fo** [cc65/cc65#474]
This simple code doesn't compile:
```
foo = 1
bar = 1
xyzzy = !foo || !bar
```
Producing:
```
expr-bug.s(3): Error: Syntax error
expr-bug.s(3): Error: Unexpected trailing garbage characters
```
This works, however:
```
foo = 1
bar = 1
xyzzy = !foo || (!bar)
```

**Comment by greg-king5** [comment]
Look at http://cc65.github.io/doc/ca65.html#ss5.5
Operator precedence isn't quite the same as in C.
> `xyzzy = !foo || (!bar)`

is the same as
`xyzzy = !(foo || (!bar))`.

**Comment by fo-fo** [comment]
I don't see how a different operator precedence would cause a syntax error.

**Comment by greg-king5** [comment]
After the parser recognizes an operator, it won't look for lower-precedence operators.  It won't recognize them.  Unrecognized characters are invalid -- they are syntax mistakes.

It's the same thing that occurs if you put two binary operators next to each other.
`baz = foo || bar && xyzzy`
works; but,
`baz = foo ||  && xyzzy`
won't work.  The parser doesn't expect to see the `&&` at that location in the expression.  Therefore, it yells,
"`Error: Syntax error`".

In
> `xyzzy = !foo || !bar`

the parser expects to see the unary operators **`~`**, **`+`**, **`<`**, **`>`**, **`^`**, and **`-`** after **`||`** -- they have higher precedence.  It doesn't expect to see **`!`**.

**Comment by fo-fo** [comment]
Thanks for the explanation.
