### ISSUE TITLE
New mouse driver for VIC-20 isn't getting compiled with unmodified makefiles.

### ISSUE THREAD

**Issue by sharpninja** [cc65/cc65#476]
I have started work on a joystick mouse driver for the VIC-20.  I have placed in ./libsrc/vic20/mouse/vic20-joy.s

For some reason the Makefile does not see it and thus doesn't attempt to compile the driver.  What do I need to do to get the Makefile to see the source and compile it?

**Comment by greg-king5** [comment]
List everything in `libsrc/c64`.  You will see how to spell the subdirectories that are used with all of the platforms.  `mou/` is the mouse driver directory.

**Comment by sharpninja** [comment]
Thank you.  Didn't notice the typo.  That fixed my issue.
