### ISSUE TITLE
Vic 20 may be broken in latest snapshots

### ISSUE THREAD

**Issue by Fabrizio-Caruso** [cc65/cc65#481]
My cross-system and cross-kit game (more than different targets from CC65 and Z88DK)
https://github.com/Fabrizio-Caruso/ASCII-CHASE
works for all targets with a previous version of CC65 (which I downloaded in May)
If I use the latest snapshot from
https://sourceforge.net/projects/cc65/

1. I get some easily fixable errors on all joystick.h about missing JOY_BTN_ functions and (for ATARI and ATARIXL) an error about missing JOY_FIRE... functions. 
Now portable code that used joystick.h is no longer working across CC65 targets.

2. Then everything works except the Vic 20 target which produces a broken binary that starts but goes straight to the basic prompt.

**Comment by oliverschmidt** [comment]
Regarding 1.:

> Now portable code that used joystick.h is no longer working across CC65 targets.

Maybe you want to elaborate. The recent changes regarding the the joystick handling intended to _improve_ the portability accross cc65 targets. You can now have a single source even for targets without a "fire" button: See https://github.com/cc65/cc65/blob/master/include/joystick.h#L63

Regarding 2.:

> Vic 20 [...] binary that starts but goes straight to the basic prompt

That's exactly what I experienced lately. I thought I did something stupid about my VICE settings, but now that you report the same behavior maybe there's really something broken.

**Comment by Fabrizio-Caruso** [comment]
Regarding 1: My code (for both Commodore and Atari targets) uses JOY_BTN_FIRE.
Now this no longer works. If I use JOY_FIRE, this only works for Commodore targets.

**Comment by oliverschmidt** [comment]
> My code (for both Commodore and Atari targets) uses JOY_BTN_FIRE.
Now this no longer works.

Yep. That's intended. You need to change your code.

> If I use JOY_FIRE, this only works for Commodore targets.

Yep. That's intended. The other targets don't have a fire button so there's no macro for that button.

You need to use https://github.com/cc65/cc65/blob/master/include/joystick.h#L63

**Comment by Fabrizio-Caruso** [comment]
ATARI and ATARIXL have fire buttons but these targets do not recognize JOY_FIRE.
If JOY_FIRE works for Commodore targets., then it should work on Atari and Atari XL, as well.

**Comment by oliverschmidt** [comment]
> ATARI and ATARIXL have fire buttons but these targets do not recognize JOY_FIRE.

I see. I just fixed that with https://github.com/cc65/cc65/commit/0deeccebf8bc0e7658213b12875efaad3abf216f.

**Comment by Fabrizio-Caruso** [comment]
I confirm Vic 20 target to be totally broken.
It is broken independenly of the cfg file. The very same code works fine with the previous snapshot.

**Comment by greg-king5** [comment]
Commit 51765c6e5c01cacda99621809e97dcd45ce295ff fixes the VIC-20 problem.  (The joystick driver had not been updated completely.)

**Comment by oliverschmidt** [comment]
There were two issues. Each issue was fixed (@Greg: Thanks). There was no additional feedback. Closing seems appropriate...
