### ISSUE TITLE
Atari 5200 with conio.h - How to compile/link?

### ISSUE THREAD

**Issue by Fabrizio-Caruso** [cc65/cc65#483]
It seems that conio.h should work with the Atari 5200 target
(https://cc65.github.io/doc/atari5200.html)
but I have not been able to get any program to compile/link.

For example:

```
#include <stdio.h>
#include <conio.h>
#include <unistd.h>
#include <atari5200.h>

int main()
{
	char ch;
	while(1)
	{
		if(kbhit())
		{
			ch = cgetc();
			printf("%c \n", ch);
		}
	}
}
```

compiled with 
cl65.exe -O -t atari5200 test_atari5200.c  -o test_atari5200.a52

will fail with:
"
Users\Brizio\Retro\ASCII-CHASE\merged"\deliverables\test_atari5200.a52
C:\Users\Brizio\Retro\ASCII-CHASE\merged\test_atari5200.c(17): Warning: Control reaches end of non-void function
Unresolved external `_cgetc' referenced in:
  C:\Users\Brizio\Retro\ASCII-CHASE\merged\test_atari5200.s(38)
Unresolved external `_kbhit' referenced in:
  C:\Users\Brizio\Retro\ASCII-CHASE\merged\test_atari5200.s(35)
Unresolved external `_write' referenced in:
  common/fwrite.s(87)
"

**Comment by mrdudz** [comment]
Am Sonntag, 10. September 2017, 00:13:07 CEST schrieb Fabrizio Caruso:
> It seems that conio.h should work with the Atari 5200 target
> (https://cc65.github.io/doc/atari5200.html)
> but I have not been able to get any program to compile/link.
> 
> For example:
> 
> #include <stdio.h>
> #include <conio.h>
> #include <unistd.h>
> #include <atari5200.h>
> 
> int main()
> {
> 	char ch;
> 	while(1)
> 	{
> 		if(kbhit())
> 		{
> 			ch = cgetc();
> 			printf("%c \n", ch);
> 		}
> 	}
> }
> 
> compiled with
> cl65.exe -O -t atari5200 test_atari5200.c  -o test_atari5200.a52
> 
> will fail with:
> "
> Users\Brizio\Retro\ASCII-CHASE\merged"\deliverables\test_atari5200.a52
> C:\Users\Brizio\Retro\ASCII-CHASE\merged\test_atari5200.c(17): Warning:
> Control reaches end of non-void function Unresolved external `_cgetc'
> referenced in:
>   C:\Users\Brizio\Retro\ASCII-CHASE\merged\test_atari5200.s(38)
> Unresolved external `_kbhit' referenced in:
>   C:\Users\Brizio\Retro\ASCII-CHASE\merged\test_atari5200.s(35)
> Unresolved external `_write' referenced in:
>   common/fwrite.s(87)
> "

i guess that is because 
- the 5200 has no keyboard (so no kbhit or cgetc)
- the 5200 has no peripherials (so no write)

you'll have to make a small test program that checks the controllers instead, 
and uses cprintf

-- 

http://www.hitmen-console.org    http://magicdisk.untergrund.net
http://www.pokefinder.org        http://ar.pokefinder.org

Twitter ist so ein wenig wie perl: Jeder Depp schreibt Zeug das keine Sau 
liest. 
<DasTier>

**Comment by groessler** [comment]
mrdudz was more or less correct.

But the controllers have numeric keypads. Which could be considered as a "keyboard". But there is no nice way to distinguish (return) left or right keypad press (or in the 4-controller version the other two), I didn't implement conio keyboard input. Probably a target specific function to the the key presses would be the solution, but it's not implemented.

**Comment by oliverschmidt** [comment]
I seem to remember that we already discussed this in detail - and that the results was, that we're not going create conio drivers for game-keypads.
