### ISSUE TITLE
ATARI 5200 binary - how to use it?

### ISSUE THREAD

**Issue by Fabrizio-Caruso** [cc65/cc65#484]
I am trying to write an ATARI 5200 version of my cross-system 8 bit game:
https://github.com/Fabrizio-Caruso/ASCII-CHASE
(which already supports most 8 bit Z80 and 6502-based computers)

I managed to compile my code with CC65 for the Atari 5200 target by using conio.h + joystick.h.

My problem now is:
- how to use the binary created by CC65? Can I use it as it is? Which extension should I use? Should I use it as a cartridge?
- how to set up the emulator? Which roms? Just the 5200 rom?
Atari800Win with the 5200 rom goes straight to the debugger when started.

**Comment by groessler** [comment]
1) The output binary can be used as it is. It's a plain cartridge ROM. Extenstion doesn't matter (maybe depending on the emulator you are using).

2) I don't know much about Atari800Win, I only know about the regular atari800 emulator (which, btw. also supports Windows). You need the 2K 5200 BIOS ROM image. Before loading the cc65 program you should set the system type to 5200 (it defaults to 800XL I think).

**Comment by oliverschmidt** [comment]
Regarding the binary: The cc65 documentation says in http://cc65.github.io/doc/atari5200.html#s2 "The standard binary output format generated by the linker for the Atari 5200 target is a cartridge image.".

Regarding the emulator: I don't think that cc65 is required to provide the information requested here - so it's no cc65 issue if it's missing. Therefore I'll close this issue.

If there should be however a momentum to provide such information for the ATARI 5200 it could go either in http://cc65.github.io/doc/intro.html#s6 or https://github.com/cc65/wiki/wiki#Target_platforms

**Comment by mrdudz** [comment]
> Regarding the emulator: I don't think that cc65 is required to provide the information requested here - so it's no cc65 issue if it's missing. Therefore I'll close this issue.

it still wouldnt hurt at all :)

**Comment by oliverschmidt** [comment]
> it still wouldnt hurt at all :)

Surely, therefore my statement above:

> If there should be however a momentum to provide such information for the ATARI 5200 it could go either in http://cc65.github.io/doc/intro.html#s6 or https://github.com/cc65/wiki/wiki#Target_platforms
