### ISSUE TITLE
ATARI 5200 target may be broken

### ISSUE THREAD

**Issue by Fabrizio-Caruso** [cc65/cc65#485]
I am getting a CPU crash at start-up with any program for the ATARI 52000 target, including this very simple hello world snippet:
```C
#include <stdio.h>
#include <conio.h>

int main()
{
	cprintf("Hello world\n");	
	while(1){}	
	return 0;
}
```
which I compile with
`cl65.exe -O -t atari5200 %mypath%\test_a5200.c -o %deliverables%\test_atari5200.rom`

I have tested it using KAT5200 and AtariWin, with both PAL and NTSC settings.

Which video standard am I supposed to use with CC65 binaries?

**Comment by groessler** [comment]
You program works over here.

The instructions to load the cartridge image into the atari800 emulator I gave in issue #484 were a bit incomplete: when asked for "cartridge type" you have to select "One chip 16 KB 5200 cartridge".

**Comment by groessler** [comment]
And, 5200 only exists for NTSC.

**Comment by Fabrizio-Caruso** [comment]
THANKS!
So does my game CROSS CHASE!
Atari 5200 is the 20th version of my game (13th CC65 version).
You can close this non-issue.

**Comment by oliverschmidt** [comment]
> You can close this non-issue.

Will do...

**Comment by greg-king5** [comment]
@Fabrizio-Caruso,
Github lets us close, re-open, and edit our own issues/pull-requests.  We even can change their titles!
(You don't need to ask the owner to do it.)
