### ISSUE TITLE
NES conio.h? How?

### ISSUE THREAD

**Issue by Fabrizio-Caruso** [cc65/cc65#486]
Which part of conio.h is implemented for the NES target?

Is it possible to display characters through gotoxy(x,y) + cputc(c)?
If yes, what needs to be done before to make it possible?
If no, which conio functions can be used to display characters?

I could no see anything shown on the screen.

**Comment by oliverschmidt** [comment]
A general guide is that if you can successfully build a program that calls a certain function then you can presume that it is supposed to work. In other words: Empty dummy implementations are not to be expected in cc65.

**Comment by Fabrizio-Caruso** [comment]
@oliverschmidt, I mean what should I do in order to see something on the screen with the NES target?
My game (which works with most 6502 and Z80 targets) uses conio.h and compiles fine but no video output is produced.
Do I have to write some code to turn on the text mode with the NES target?

**Comment by mrdudz** [comment]
the library should initialize itself automagically when the program is started when any (supported) conio features are being used. try with a trivial "hello world" thingy first, perhaps the problem is elsewhere

**Comment by Fabrizio-Caruso** [comment]
I have never been able to get any program to display someting with conio.h
Not even a simple hello world snippet:

  #include <stdio.h>
  #include <conio.h>
  int main()
  {
    cprintf("Hello world!\n");
    return 0;
  }
  
which I compile with
cl65.exe -t nes %mypath%\my_hello.c  -o %deliverables%\my_hello.nes

and then use with fceux -> File -> Open ROM -> BLANK SCREEN

On the other end I have been able to get something shown by other means (no conio.h).

**Comment by Fabrizio-Caruso** [comment]
If this is a real problem, then I can confirm that it is so since May when I started to try and gave up thinking that NES conio.h was not fully implemented or required some special initialization.

**Comment by greg-king5** [comment]
The problem is with `fceux`.  You probably aren't using it correctly.

Your minimal Chase game, built for NES, works on [Mednafen](https://mednafen.github.io/).  (Except that the player moves too fast.)

Mednafen emulates the `pce` (NEC PC-Engine) target, also. `-t pce` has conio support.

**Comment by mrdudz** [comment]
also that program quits immediatly, so it'd have a hard time displaying anything :) throw a while(0); in there or sth :)

**Comment by groessler** [comment]
> also that program quits immediatly, so it'd have a hard time displaying anything :) throw a while(0); in there or sth :)

This opens a question. To me, a console program (which is typically stored in a cartridge ROM) is never supposed to exit. There's nothing it could exit to. So the console targets I introduced or worked on (Atari5200 and Creativision) just enter an endless loop when main() exits. Some other targets do this, too (e.g. supervision, lynx), some other targets restart the program with "jmp start" or similar.

Should we make that consistent? I have no strong feeling about it, since, as I said, such a program should never "exit". The "exit" itself is probably a bug. :-)

**Comment by greg-king5** [comment]
> This opens a question. To me, a console program (which is typically stored in a cartridge ROM) is never supposed to exit. There's nothing it could exit to. So, the console targets I introduced or worked on (Atari5200 and Creativision) just enter an endless loop when main() exits. Some other targets do that, too (e.g., supervision, lynx); some other targets restart the program with "jmp start" or similar.
>
> Should we make that consistent? I have no strong feeling about it, since, as I said, such a program should never "exit". The "exit" itself is probably a bug. :-)

My opinion is that a "`jmp start`" is the only reason to exit from a console program.  It runs destructors and constructors.  It is somewhat similar to a "power cycle".

**Comment by oliverschmidt** [comment]
> Should we make that consistent?

Maybe we have again a case of target specific user expectations ;-)

> My opinion is that a "jmp start" is the only reason to exit from a console program.

I think here again we have once more the - from my perspective usual - question of "do I program for this cc65 target" or "do I program for many cc65 targets" or "do I program for many target in general".

1) If one programs for a specific console then the `jmp start` approach makes most sense. If the programmer just wants the program to end with an endless loop he can easily do that on his own. Not having run the destructors is not supposed to be a problem. So if the programmer wants a restart he can get it easily with exit().

2) If one programs for many cc65 targets then it would likely make most sense to make use of doesclrscrafterexit(). The default implementation just always returns false. This fits well for consoles doing an endless loop after exit. Consoles doing a restart after exit should have an own doesclrscrafterexit() implementation that just always returns true. Then the program can do what by now all cc65 samples do: https://github.com/cc65/cc65/blob/709ee6a28b1375222d44590a57e93d732966f8bf/samples/mandelbrot.c#L144-L148

3) If one programs for many targets in general then maybe the endless loop approach would make most sense as a C program tends to presume that its output is visible after exit - see i.e. Hello,World.

**Comment by Fabrizio-Caruso** [comment]
Thanks guys for the support!
