### ISSUE TITLE
c99 struct compatibility

### ISSUE THREAD

**Issue by leonicode** [cc65/cc65#488]
Hi,
I've tried the c99 option, to compile the following little piece of c99 code:

typedef struct {
	int one;
	union {
		int sx;
		int dx;
	} fun;
} my_struct_t;

int main() {
	my_struct_t variable = {10, .fun.sx=5};
	return 0;
}

but it not works ... Is it possible to add this c99 capability ? Is this feature planned ?
Thanks in advance 
Leonicode

**Comment by oliverschmidt** [comment]
I don't a momentum for that so let me close this.
