### ISSUE TITLE
da65: absolute to zero-page mode conversion leads to mismatch with original (65C02)

### ISSUE THREAD

**Issue by inexorabletash** [cc65/cc65#489]
Disassembling code that uses ProDOS-like calling conventions (`JSR MLI .byte CALL .addr DATA`), da65 ran into this:

```
...
20 00 40  JSR $4000
11        .byte $11
8A 6E     .addr $6E8A
20 00 40  JSR $4000
...
```
Normally this isn't a problem - random opcodes and `.byte` sequences get generated but eventually things get back in sync. (I have a .info generator that looks for such sequences. But it's not perfect.)

But in this case, da65 generated this:

```
...
20 00 40  JSR $4000
11 8A     ORA ($8A)y
66 20     ROR $20
40        RTI
...
```

Note that (1) the output bytes are different (`6E` &rarr; `66`) and (2) a byte is missing (`00`).

It looks like da65 converted `6E 20 00` internally into `ROR $0020` but output `ROR $20`, which is a different opcode/length.

(I'm quoting bytes from the listing file above after a pass through ca65 for clarity, but the short `ror $20` occurs in the da65 output)

Assuming the intent of da65 is to produce output that assembles back to the original, this is a bug.

**Comment by inexorabletash** [comment]
I should also note that I haven't tested what ca65 does if it encounters `ror $0020`; if it generates the shorter zp sequence then da65 should just output three `.bytes`. Or maybe it always should, for safety. I don't have a preference.

(FYI, it turns out I had a glitch in my info generator which had missed this. Once I corrected that, da65 ran across just a handful of instances like this in data blocks - strings which looked like opcodes with absolute long zp references. With just four more instances of manual RANGE tagging, it made it through 75k of data which reassembles to the match the original. Yay and thanks!)

**Comment by EtchedPixels** [comment]
for $00xx it should be attaching a type specifier ( ror a:$20) and then it'll assemble correctly.

The code actually appears to try and do the right thing was this fixed and not closed ?

**Comment by EtchedPixels** [comment]
I simply can't reproduce this bug with cc65

If I feed da65 6E 20 00 then it disassembles it correctly as

                ror a:$20

which then reassembles correctly

**Comment by inexorabletash** [comment]
Sorry, I apparently left out a critical detail: it requires specifying 65C02 CPU, either via info or on the command line. Try with `--cpu 65C02` and you should see `ror $20` instead of `ror a:$20`

**Comment by EtchedPixels** [comment]
Ahah.. that's indeed the important detail. There is indeed an error in the table for 65C02


[1.diff.txt](https://github.com/cc65/cc65/files/1800343/1.diff.txt)

**Comment by oliverschmidt** [comment]
> There is indeed an error in the table for 65C02

Thanks for the analysis :-)

> 1.diff.txt

Are you willing to create a pull request?

**Comment by EtchedPixels** [comment]
Given how tiny it is can you just apply it - I can do a pull req if you need but it'll probably be a few days
