### ISSUE TITLE
Building Debian/Ubuntu package

### ISSUE THREAD

**Issue by SvOlli** [cc65/cc65#491]
Hello,

I've been experimenting with building a Debian/Ubuntu package out of cc65. It's been much easier than my first attempts several years ago, since the installation now seems to need only a little "post-processing" by the packaging scripting.

My solution is to build a source package from the git repository hosted on github by using a very simple wrapper script that's placed additionally in the debian/ configuration directory. That source package can be used to build the binary package for the desired distro/platform combination using
sbuild or dpkg-buildpackage for self-hosted systems. As opposed to other attempts I've seen so far, the result will be a single package containing every platform and documentation. The ~32MB should fit on any current system, and it makes installation "by hand" much easier: only a single "dpkg" command is needed to install the binary package, and also only one to remove it as well. And I don't see any major advantage by separating it into several packages again.

Before commiting my work and filing a merge request there is at least one part where I can't do things right: the copyright file, as it is attached to this mail. It's more some kind of "paperwork", but since I want to offer my work for merging in the master tree, I think this should be filled out properly. ;-)

The template looks like this:
```
Format: https://www.debian.org/doc/packaging-manuals/copyright-format/1.0/
Upstream-Name: cc65
Source: <url://example.com>

Files: *
Copyright: <years> <put author's name and email here>
           <years> <likewise for another author>
License: <special license>
 <Put the license of the package here indented by 1 space>
 <This follows the format of Description: lines in control file>
 .
 <Including paragraphs>

# If you want to use GPL v2 or later for the /debian/* files use 
# the following clauses, or change it to suit. Delete these two lines
Files: debian/*
Copyright: 2017 Sven Oliver Moll
License: GPL-2+
 This package is free software; you can redistribute it and/or modify
 it under the terms of the GNU General Public License as published by
 the Free Software Foundation; either version 2 of the License, or
 (at your option) any later version.
 .
 This package is distributed in the hope that it will be useful,
 but WITHOUT ANY WARRANTY; without even the implied warranty of
 MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
 GNU General Public License for more details.
 .
 You should have received a copy of the GNU General Public License
 along with this program. If not, see <https://www.gnu.org/licenses/>
 .
 On Debian systems, the complete text of the GNU General
 Public License version 2 can be found in "/usr/share/common-licenses/GPL-2".

# Please also look if there are files or directories which have a
# different copyright/license attached and list them here.
# Please avoid picking licenses with terms that are more restrictive than the
# packaged work, as it may make Debian's contributions unacceptable upstream.
```

Since there are many contributors, I don't have a clue what to put in there. Any help would be very appreciated. Also note that declaring my contribution GPL2+ is only the default inserted by dh_make, it will be changed to any license fitting.

My first attempt is this:
```
Format: https://www.debian.org/doc/packaging-manuals/copyright-format/1.0/
Upstream-Name: cc65
Source: https://github.com/cc65/cc65

Files: *
Copyright: 1998-2012 Ullrich von Bassewitz
           2012-2017 cc65 development team

License: Custom
 This software is provided 'as-is', without any express or implied warranty.
 In no event will the authors be held liable for any damages arising from
 the use of this software.
 .
 Permission is granted to anyone to use this software for any purpose,
 including commercial applications, and to alter it and redistribute it
 freely, subject to the following restrictions:
 .
 1. The origin of this software must not be misrepresented; you must not
 claim that you wrote the original software. If you use this software in
 a product, an acknowledgment in the product documentation would be
 appreciated but is not required.
 .
 2. Altered source versions must be plainly marked as such, and must not
 be misrepresented as being the original software.
 .
 3. This notice may not be removed or altered from any source distribution.
```

So, what should the copyright-file look like? Once, this is decided, I'll file my merge request.

**Comment by mrdudz** [comment]
iirc the general consensus is/was that the cc65 tree does not contain any distribution/packaging specific things...

**Comment by spiro-trikaliotis** [comment]
You know that Debian/Ubuntu packages are already built automatically as soon as there is a checkin to github master?

Have a look here: https://build.opensuse.org/package/show/home:strik/cc65

**Comment by oliverschmidt** [comment]
> iirc the general consensus is/was that the cc65 tree does not contain any distribution/packaging specific things...

That's my understanding too.

> You know that Debian/Ubuntu packages are already built automatically as soon as there is a checkin to github master?

I didn't dare to mention that for fearing that I'm just to ignorant to see the difference but now that you do it ...

**Comment by spiro-trikaliotis** [comment]
BTW, @SvOlli: If you have anything to improve, I am open to accept suggestions, patches, and other things.

**Comment by SvOlli** [comment]
Will not be added, because distribution specific stuff will not be put in the development repo.

There's no reason to keep this open.

**Comment by sur5r** [comment]
*removes dust*
Just to make everybody aware of it: cc65 has just entered Debian proper.
See https://packages.qa.debian.org/c/cc65.html

**Comment by groessler** [comment]
Hi,

great!

Your description has an incomplete list of targets:


Package: cc65
Architecture: any
Depends: ${shlibs:Depends}, ${misc:Depends}
Suggests: cc65-doc
Description: complete cross development package for 65(C)02 systems
  cc65 is a complete cross development package for 65(C)02 systems, 
including
  a powerful macro assembler, a C compiler, linker, librarian and several
  other tools.
  .
  cc65 has C and runtime library support for many of the old 6502 machines,
  including
    - the following Commodore machines:
      - VIC20
      - C16/C116 and Plus/4
      - C64
      - C128
      - CBM 510 (aka P500)
      - the 600/700 family
      - newer PET machines (not 2001).
   - the Apple ][+ and successors.
   - the Atari 8 bit machines.
   - the Atari 5200 console.
   - GEOS for the C64, C128 and Apple //e.
   - the Nintendo Entertainment System (NES) console.
   - the Supervision console.
   - the Oric Atmos.
   - the Lynx console.
   - the Ohio Scientific Challenger 1P


And, how does one find out from which git revision the source tarball 
(cc65_2.16.orig.tar.gz) was generated?

regards,
chris

**Comment by sur5r** [comment]
> Your description has an incomplete list of targets:

Does the above list apply to 2.16 as well or only to master? If you don't know it from the top of your head I will look it up myself and file a bug report against cc65 in Debian.

> And, how does one find out from which git revision the source tarball (cc65_2.16.orig.tar.gz) was generated? 

It was not generated or modified in any way. It's the original 2.16 release tarball from github. That's why it's call "orig tarball" ;)
