### ISSUE TITLE
ATARI mode 1 color flicker (maybe ATMOS has a similar problem)

### ISSUE THREAD

**Issue by Fabrizio-Caruso** [cc65/cc65#492]
I am experiencing a weird problem with the Atari text mode 1 (and a somewhat similar problem with the Atmos target in text mode).
I don't know whether it is an emulator-related problem, something normal in the real hardware or something else coming from either my code or CC65 routines.

ATARI
Some of the characters on the screen flicker, i.e., they switch rapidly between two colors.
The flicker is sometimes triggered by a character to their left (e.g., if my character-hero moves next to the border, than the border flicker, and I do NOTHING to the border ever after displaying it).

ATMOS
Sometimes in the ATMOS target I get a somewhat similar problem: sometimes a single border character gets inverted (so it is displayed in inverted colors). Differently from the Atari target, there is no flicker and the character remains inverted until the screen is redrawn.

No similar problem found on any of the other 40 cases (half of which compiled with CC65).

In both cases it looks like as if bit 7 of a character were set or unset.

Any idea why this may happen??

**Comment by Fabrizio-Caruso** [comment]
You can see the flicker in this video
https://www.youtube.com/watch?v=1Fl63INsgew

**Comment by groessler** [comment]
Fabrizio,

I had downloaded the source code from github and wanted to take a look.

But, your source tree is somehow -- let's say -- strange.

Please take the following not as criticism, but as suggestions for improvement.

1) it's not quite obvious where the source code actually is located. It seems it's inside the "merged" directory.
2) There are no build instructions. I am on my own to find out. A top level text file "BUILDING" or "INSTALL" could describe how to build the project. This would also make my point 1) obsolete, since it could mention that the source code is in "merged".
3) It seems that the versions for the different targets are built by invoking the "compile_merged_xxx.bat" files in the "merged" directory. This is a show-stopper for me since my Linux doesn't understand *.bat files. Better would be to create a Makefile (preferably for GNU make) to build the versions. This can be done in a cross-platform way. And also would remove clutter, just one Makefile instead of one batch file for each target.

So, to follow up to your question: I have no idea why there is flicker. I haven't looked since I cannot build your project. But I'm willing to help your to create a Makefile for Cross-Chase. But this better be done in PM.

regards,
chris

**Comment by Fabrizio-Caruso** [comment]
Thanks! I was planning a BUILD file and makefile! The  Windows batches are reallly ugly and temporary. I was thinking of Cygwin + makefile. What makes the makefile complicated for me is the fact the multiple compilers and settings are used. Maybe I make a simplistic one that does the same thing as the Windows batches, i.e. , all object files are always rebuilt.

To build under Windows you can simply execute the same  single command as in the ugly batch .

I am going to write a BUILD file and let you know.

How can I talk to you privately? Facebook?  Whatsup?

**Comment by Fabrizio-Caruso** [comment]
BUILD INSTRUCTIONS

The game is compiled through different C cross-compilers (currently CC65's compiler and Z88DK's compilers). 

The different versions are produced thanks to the cross-compilers and parameters pased to these compilers
through the -D option.

PARAMETERS

General parameters:

- FULL_GAME [all systems]
If this parameter is passed to the compiler, then the full-fledged version of the game (different levels and enemies)
will be generated. Otherwise the "minimal" version (all levels look like the first one) will be generated.

- REDEFINED_CHARS [some systems]
This parameter activates redefined characters including the "animation" of the player's characters

- SOUNDS [some systems]
This parameter activates in-game sounds.

System-specific parameters:

- ATARI_MODE1 [for ATARI and ATARIXL]
It toggles 5-color 20x24 text mode for ATARI and ATARIXL.

- C128_80COL_VIDEO_MODE [for COMMODORE128]
It toggles VDC 80 column mode for COMMODORE128

- SPECTRUM_32COL / SPECTRUM_64COL [for SPECTRUM]
It toggles 32 and 64 column mode for SPECTRUM.

- MSX_MODE1 [for MSX]
It activates MODE1 for MSX

**Comment by Fabrizio-Caruso** [comment]
MYPATH ?= .

CC_PATH ?= /cygdrive/c/cc65-snapshot-win32/bin
DELIVERABLES ?= $(MYPATH)/deliverables
MYCC ?= cl65.exe

vic20exp_16k:
	$(CC_PATH)/$(MYCC) -O -t vic20 -DFULL_GAME -DSOUNDS --config $(MYPATH)/../cfg/vic20-16k.cfg $(MYPATH)/vic20/vic20_sounds.c $(MYPATH)/display_macros.c $(MYPATH)/enemy.c $(MYPATH)/invincible_enemy.c $(MYPATH)/level.c $(MYPATH)/character.c $(MYPATH)/text.c $(MYPATH)/missile.c $(MYPATH)/strategy.c $(MYPATH)/input_macros.c $(MYPATH)/main.c  -o $(DELIVERABLES)/FULL_cvic20-16k_sounds.prg

atari_mode1:
	$(CC_PATH)/$(MYCC) -O -t atari  -DREDEFINED_CHARS -DFULL_GAME -DATARI_MODE1 -DSOUNDS --config $(MYPATH)/../cfg/atari_mode1_redefined_chars.cfg $(MYPATH)/atari/atari_sounds.c $(MYPATH)/atari/atari_input.c $(MYPATH)/display_macros.c  $(MYPATH)/enemy.c $(MYPATH)/invincible_enemy.c $(MYPATH)/level.c $(MYPATH)/character.c $(MYPATH)/text.c $(MYPATH)/missile.c $(MYPATH)/strategy.c $(MYPATH)/input_macros.c $(MYPATH)/main.c  -o $(DELIVERABLES)/FULL_atari_mode1_redefined_chars.xex

	
.PHONY: vic20exp_16k atari_mode1

all: vic20exp_16k atari_mode1

**Comment by Fabrizio-Caruso** [comment]
I can fix the problem in ATMOS by replacing cputc with direct writes to video memory.

It looks like a general conio.h issue: cputc sometimes prints inverted characters (7th bit set/unset).

**Comment by IrgendwerA8** [comment]
Just a wild guess, but did you switched the cursor on the Atari platform off? It may fixes your problem (POKE 752,1)

**Comment by Fabrizio-Caruso** [comment]
Thanks for the suggestion but the cursor or something else is still causing characters to the right of displayed character to flash AS IF there were a cursor there, e.g, let us say on the screen we have

ABC

and I redraw something at B than C will flash as if the 7th bit were set or unset and this generates a different color on the Atari (and on the Atmos but the Atmos does not flash and the character gets stuck in the wrong colors).

**Comment by Fabrizio-Caruso** [comment]
I can remove the flashing by avoid conio calls in both Atari and Atmos.
POKE(752,1) is not enough because some conio function re-enables the cursor.
This is a general issue in conio.h.
Should I open a different issue? And close this one?

**Comment by Fabrizio-Caruso** [comment]
I am going to close this issue because
1.  it is now clear what it is causing it (conio.h cputc + gotoxy)
2.  there is an ugly workaround with direct writes onto video memory.
conio.h has a bug which tracked by #497.
