### ISSUE TITLE
PCE how to put code in a specific ROM bank?

### ISSUE THREAD

**Issue by Fabrizio-Caruso** [cc65/cc65#493]
Hi
I would like to support the PCE for my multi-system game CROSS CHASE.

In https://cc65.github.io/doc/pce.html I do not see any details on how to tell the code which bank to use.

I suppose this must be done by some pragmas or some parameters and maybe I will ned to tweak the .cfg file.

Where can I find a simple example?

  Fabrizio

**Comment by oliverschmidt** [comment]
I can't assess how relevant the following actually is for your scenario but nevertheless:

https://github.com/cc65/cc65/blob/master/samples/overlaydemo.c
https://github.com/cc65/cc65/blob/master/samples/Makefile#L163-L172
https://github.com/cc65/cc65/blob/master/cfg/apple2-overlay.cfg (as an example)

**Comment by Fabrizio-Caruso** [comment]
My problem is that I need to fit my game (>10k) into a rom image. The default ROM area is not enough.
What is the simplest solution?

**Comment by mrdudz** [comment]
Am Freitag, 22. September 2017, 18:21:25 CEST schrieb Fabrizio Caruso:
> My problem is that I need to fit my game (>10k) into a rom image. The
> default ROM area is not enough. What is the simplest solution?

use a larger ROM/Cartridge? PCE surely had bigger carts than just 8k? :)

-- 

http://www.hitmen-console.org    http://magicdisk.untergrund.net
http://www.pokefinder.org        http://ar.pokefinder.org

IBM is not a necessary evil. IBM is not necessary. 
<Ted Nelson>

**Comment by Fabrizio-Caruso** [comment]
How do I set up the config file to create a larger rom image?
I get a linker error about my program not fitting the ram area.

**Comment by mrdudz** [comment]
Am Freitag, 22. September 2017, 18:51:38 CEST schrieb Fabrizio Caruso:
> How do I set up the config file to create a larger rom image?
> I get a linker error about my program not fitting the ram area.

you'll have to create another ROM area in the MEMORY section of the config 
file, and then create another code segment.

can't really tell any details - i am not familiar with the possible memory 
layouts of a PCE cartridge, you'll have to do some research on this first and 
find out how larger cartridges work. i vaguely remember that you could have 
16K linear ROM space somehow - but i might mix things up with one of the other 
targets :)

-- 

http://www.hitmen-console.org    http://magicdisk.untergrund.net
http://www.pokefinder.org        http://ar.pokefinder.org

Twitter ist so ein wenig wie perl: Jeder Depp schreibt Zeug das keine Sau 
liest. 
<DasTier>

**Comment by Fabrizio-Caruso** [comment]
Let us say I create a new rom area in the memory section.
How do I tell the linker to use?
Do I have to do something the segment area?
Do I need to use pragmas in my code to select where my code is supposed to go?

I am trying to find examples on the Internet with PCE and CC65 but no luck so far.

**Comment by oliverschmidt** [comment]
> How do I tell the linker to use?
Do I have to do something the segment area?
Do I need to use pragmas in my code to select where my code is supposed to go?

As far as I understand these are the right questions :-) The links in my first comment are hints for finding the answers to those very questions.

**Comment by Fabrizio-Caruso** [comment]
If I wrote the right answers, then I only need:
- use a new memory section
- do something with the segment area
- somewhere in the code tell where that portion of the code should go
Then no overlays?
But then you say that I should look a your links about overlays...
So, I need overlays as well. 
I need to understand what an overlay is. 
Some targets have .cfg with overlays but not the PCE.

**Comment by oliverschmidt** [comment]
Okay, from the perspective of the tool chain usage of several memory banks and overlays are pretty similar: It's about using one and the same address for different purposes at different times during the run of a single program.

The "only" difference between memory banks and overlays are:
- How does the output of the linker get loaded.
- How does the switching between the memory banks/overlays work.
But those two questions aren't answered by the cc65 tool chain neither for memory banks nor overlays - so they don't matter from the tool chain perspective.

With that in mind it makes sense to point you to overlays when you ask about memory banks. That does by no means imply to do something with overlays.

**Comment by Fabrizio-Caruso** [comment]
Making ROM0 bigger from 8k to 16k does not seem to work:
    ROM0: file = %O, start = $C000, size = $3FF6, fill = yes, define = yes;

It seeems that the PCE maps 8k segments from the 64k addressable memory to some bigger real memory.
I wonder whether I will need to play with its MMU to use more than 8k for my game.

**Comment by mrdudz** [comment]
Am Dienstag, 26. September 2017, 09:15:50 CEST schrieb Fabrizio Caruso:
> Making ROM0 bigger from 8k to 16k does not seem to work:
>     ROM0: file = %O, start = $C000, size = $3FF6, fill = yes, define = yes;
> 
> It seeems that the PCE maps 8k segments from the 64k addressable memory to
> some bigger real memory. I wonder whether I will need to play with its MMU
> to use more than 8k for my game.

as said, you'll have to find some proper documentation on the PCE - i'd start 
at the nesdev forums, for example

-- 

http://www.hitmen-console.org    http://magicdisk.untergrund.net
http://www.pokefinder.org        http://ar.pokefinder.org

lex mihi ars

**Comment by Fabrizio-Caruso** [comment]
Thanks for the support! I will have to do some experiments which are not in the scope of this question.
