### ISSUE TITLE
ca65 question: can I concat macro parameters + " constant strings" to form a single label/identifier?

### ISSUE THREAD

**Issue by lgblgblgb** [cc65/cc65#495]
This is a question only ... I have a situation where I would like to do this (oversimplification in this example):

    .macro emulated_call label, condition
    label = call_opcode_emulator_ ## condition
    .endmacro

So then, if I write this (not an actual example with 90 and 91 ...):

    emulated_call     opcode_90, NZ
    emulated_call     opcode_91, NC

then, it would expand this:

    opcode_90 = call_opcode_emulator_NZ
    opcode_91 = call_opcode_emulator_NC

So basically I want to "form" label references from "parts". The reason is somewhat complicated, but it's a software Z80 emulator written in (4510 for Mega65) assembly basically, with the need to have generic "skeleton" for easier porting for the actual implementation of the opcodes on a given system (that's the reason it looks like an over-complicated scenario - some macro may even "decide" not to define the given label, so it must be generic). The other solution can be a generator (like in Python) to produce the asm source, but I would prefer a pure asm solution with ca65 features only :)

Can I do this somehow in ca65? It's something like the ## in C macro preprocessors, I guess, like this:

https://gcc.gnu.org/onlinedocs/cpp/Concatenation.html

Thanks a lot in advance.

**Comment by lgblgblgb** [comment]
Never mind, I could work it around "quite well" with scopes/.PROCs, ie:

    .PROC handler_JR
    IF_C: ...
    IF_NC: ...
    ALWAYS: ...
    .ENDPROC
    
    .MACRO JR_EMU label, condition
    label = handler_JR::condition
    .ENDMACRO
    
    JR_EMU opc_NN, IF_C
    JR_EMU opc_NM, IF_NC
    JR_EMU opc_NK, ALWAYS

So sorry for the noise here, anyway it can be interesting to know if the original question of mine is possible at all.

**Comment by fo-fo** [comment]
Yes, it's possible.

```
.macro emulated_call label, condition
  label = .ident(.sprintf("call_opcode_emulator_%s", .string(condition)))
.endmacro
```
