### ISSUE TITLE
[ATMOS] Bug in conio.h: inverted colors (maybe due to interference by invisible cursor)

### ISSUE THREAD

**Issue by Fabrizio-Caruso** [cc65/cc65#497]
This is general issue and it is the cause of #492 (which I will soon close in order to keep this one)

PROBLEM:
In some targets (see below) conio functions (gotoxy, cputc) trigger the cursor to appear for an instant.
(Trying to disable the cursor, e.g., POKE(752,1) will not work because the cursor is re-activated by the next conio call).

 This causes: 
- random rapid character flicker (in ATARI, ATMOS and most probably ATARI5200 and others) and 
- random inversed colors (in ATMOS)

IMPACTED:
- ATARI (in 20x24 text mode 1 and probably any other text mode)
- ATMOS (in standard text mode)
Most probably ATARI 5200 in its standard text mode (same as 20x24 text mode 1 in ATARI).
Probably other targets are impacted.

CURRENT WORKAROUND:
I have been able to solve #492 in both ATARI and ATMOS by removing conio.h gotoxy + cputc and substituting them with direct writes onto video memory.

**Comment by Fabrizio-Caruso** [comment]
```#include <cc65.h>
#include <conio.h>
#include <tgi.h>

int main(void)
{
	_graphics(1+16);
	_setcolor_low(0, TGI_COLOR_RED);
	_setcolor_low(1, TGI_COLOR_WHITE);
	_setcolor_low(2, TGI_COLOR_CYAN);
	_setcolor_low(3, TGI_COLOR_BROWN);
	_setcolor_low(4, TGI_COLOR_BLACK);
	while(1)
	{
	  char i; 
	  gotoxy(0,0);
	  for(i=0;i<8;++i)
	  {
		cputc('a'+64);
		cputc('b'+160);
	  } 
	  cgetc();
	  gotoxy(0,0); 
	  cprintf("4444");
	  cgetc();
	}
	return 0;
}
```

**Comment by polluks** [comment]
If you put `cursor(1);` after cprintf it will work, strange.

**Comment by Fabrizio-Caruso** [comment]
In my code for the Atari 8-bit I am using a workaround suggested by Christian.
The ATMOS case is more puzzling because I cannot reproduce it easily. It happens at random times.
So for the ATMOS version of my game I am not using conio.

**Comment by oliverschmidt** [comment]
As far as I understand the ATARI scenario is related to using a video mode not "officially" supported by conio. "Only" the ATMOS scenario is still present, correct? In that case please adjust the title of this issue accordingly.

**Comment by Fabrizio-Caruso** [comment]
@oliverschmidt I have updated the title. The issue remains under Atmos. I will try to reproduce it but I have not been able because it seems to happen randomly.

**Comment by Fabrizio-Caruso** [comment]
I cannot find any other explanation other than the cursor or some other mechanism that switches rapidly the bit 7 of a character.

**Comment by oliverschmidt** [comment]
Thanks for the change and the feedback.

**Comment by Fabrizio-Caruso** [comment]
I re-edited the title to make it even clearer: the cursor is not "visible" as a cursor. What I see (sometimes) is a "flashing" character, i.e., as if the bit 7 of such character were set and unset rapidly. 
This is why I am assuming that the cursor is the culprit.

**Comment by polluks** [comment]
@Fabrizio-Caruso Please check again!

**Comment by Fabrizio-Caruso** [comment]
I will run some tests. I need to play the game for a few minutes to be sure that the problem is gone.

**Comment by Fabrizio-Caruso** [comment]
It looks better bow. Please let me test it a bit more.

**Comment by Fabrizio-Caruso** [comment]
The issue is now either solved or mitigated to the point of not being visible most of the times.
I cannot exlude my code as being responsible.
I am closing this long standing issue.
