### ISSUE TITLE
absolute data buffer (for screen buffer) 

### ISSUE THREAD

**Issue by anchor76** [cc65/cc65#502]
hello,

i'm new with cc65. what is the best approach to allocate a 8k absolute buffer for a hi-res screen?

**Comment by Marrin** [comment]
I would say writing a linker config.

**Comment by anchor76** [comment]
well, yes, i see the configuration files ... and a __RESERVED_MEMORY__ symbol type. but i can't found documentation for this file format. so its not obvious what should i do there ...

**Comment by groessler** [comment]
What system are you using (targeted at)?

**Comment by anchor76** [comment]
thanks, i solved it with adjusting the ____HIMEM____ param
