### ISSUE TITLE
external required?

### ISSUE THREAD

**Issue by polluks** [cc65/cc65#509]
extern void *JOYSTICK_DRIVER;

https://github.com/cc65/cc65/blob/7f52a770d9c6a43dde67689032bb3a4848eb6b30/testcode/lib/joy-test.c#L34

**Comment by spiro-trikaliotis** [comment]
Note the #ifdef JOYSTICK_DRIVER: It is a preprocessor macro, thus, no external definition is needed (nor allowed!)

**Comment by polluks** [comment]
Well, I get
`$ cl65 -DJOYSTICK_DRIVER=foo joy-test.c`
`joy-test.c(34): Error: Undefined symbol: 'foo'`

**Comment by groessler** [comment]
Yes, there's no "foo" joystick driver.

Try
$ cl65 -DJOYSTICK_DRIVER=joy_static_stddrv  joy-test.c

And, please, in your reports, say what you mean, and not just throw some message at us where we need to figure out what you want to say...

**Comment by polluks** [comment]
I thought it was obvious, I'm not talking about
`cl65 -DDYN_DRV=1 joy-test.c`
or groessler's example
`cl65 -DDYN_DRV=0 joy-test.c`
but defining a _non standard_ static driver.

**Comment by oliverschmidt** [comment]
To me it seems that the joy-test program wants to allow to easily select one of the defined static joystick drivers. I don't see that it's purpose is to use an "unknown" static joystick driver.

Please reopen in case I'm missing the point.

BTW: I agree that it is in general not helpful to presume that "everything" is obvious to "everybody" ;-)

**Comment by polluks** [comment]
Please take a look, we define in joystick.h `joy_static_stddrv`. Perfect!
But want to test my "unknown" static joystick driver called `atmos_ijk_joy`.
joy-test's comment says "A statically linked driver was named on the compiler's command line".
But JOYSTICK_DRIVER has so far no external declaration...

Maybe the earth is flat, I cannot proof it. One thing is for sure, this single declaration is missing ;-)

**Comment by oliverschmidt** [comment]
Seems I'm still not there...

Me: "I don't see that it's purpose is to use an "unknown" static joystick driver."

You: "But want to test my "unknown" static joystick driver [...]"

I think that you want to use the program in a way the author didn't expect it to use. Therefore I don't think something is missing.

If you however say "See, if you just add that declaration to the program, its use can be extended to the use case I have without disturbing its original use." then I can probably follow you.

Apart from that: I presume that every new driver written is supposed to be added to cc65. Is there a specific reason why you don't just make your "unknown" static driver known by adding it to the appropriate header file. I mean, by the time the driver becomes available to others it needs to be added there anyway so adding it right-away means that you do a more realistic end-user test - which seems good to me.

**Comment by polluks** [comment]
I got it!
The platform header is the right place, not the demo file. Thanks for your patience!

**Comment by oliverschmidt** [comment]
Thanks for your open words :-)
