### ISSUE TITLE
Bug at _DE_ISLBL(t)

### ISSUE THREAD

**Issue by luckboy** [cc65/cc65#512]
When I use _DE_ISLBL(t) from dirent.h, compiler complains on undefined symbol _CBM_T_HDR for
c64 target. I defined macro _CBM_T_HDR as _CBM_T_HEADER, and then compile program.

Macro _DE_ISLBL(t) uses undefined macro _CBM_T_HDR instead of macro _CBM_T_HEADER.

**Comment by oliverschmidt** [comment]
Thanks for the report :-)

Fixed with https://github.com/cc65/cc65/commit/afcfba935594879742d85469d3cb1c38a25fa6f4.
