### ISSUE TITLE
No cbm_k_untlk

### ISSUE THREAD

**Issue by dmantione** [cc65/cc65#520]
Hello,

I am missing a cbm_k_untlk() in cbm.h. After studying the source code it appears you can put a:

void cbm_untlk();

... in your own source code as a workaround, but it puzzles me why you need to and why the naming is not consistent with other kernal calls such as cbm_k_unlsn(); (which does exist in cbm.h).

**Comment by oliverschmidt** [comment]
I certainly can't comment on this. If you however don't get feedback her in a reasonable time frame I suggest to additionally pose the question on the cc65 dev mailing list.

**Comment by spiro-trikaliotis** [comment]
I totally agree. cbm_untlk() should be named cbm_k_untlk() instead, and it should be included in cbm.h.

**Comment by oliverschmidt** [comment]
@dmantione: Thanks for the analysis.
@spiro-trikaliotis: Thanks for the feedback.

Fixed with https://github.com/cc65/cc65/commit/06794b221d0bd26c90baad71fbbd23ad5301fe16.

> If I could only remember the workflow on github myself... :(

Once you knew it ;-) https://github.com/cc65/cc65/pull/137
