### ISSUE TITLE
[creativision] [linker configs] Missing alternative creativision configs (?)

### ISSUE THREAD

**Issue by Fabrizio-Caruso** [cc65/cc65#522]
I am trying to compile for the creativision target and I would need 16k of available memory.

In 
https://cc65.github.io/doc/creativision.html
I read:
"The standard binary output format generated by the linker for the Creativision target is a 4 kbyte machine language program. It is of course possible to change this behaviour by using one of the different linker configs."
but I only found one config that provides 4k.

Where can I find the other configs?

Then I wrongly thought I could modify the cfg file by making room for 16k.
I did something like:
...
MEMORY {
    ZP:  file = "", define = yes, start = $0020, size = $00E0;
    RAM: file = "", define = yes, start = $01FA, size = $0206;
    ROM: file = %O, define = yes, start = $B000, size = $4000, fill = yes, fillval = $FF;
}
SEGMENTS {
    ZEROPAGE: load = ZP,             type = zp;
    ZP:       load = ZP,             type = zp,                optional = yes;
    VECTORS:  load = ROM, run = RAM, type = rw,  define = yes;
    DATA:     load = ROM, run = RAM, type = rw,  define = yes,                 start = $0204;
    BSS:      load = RAM,            type = bss, define = yes;
    ONCE:     load = ROM,            type = ro,                optional = yes;
    CODE:     load = ROM,            type = ro;
    INIT:     load = ROM,            type = ro;
    RODATA:   load = ROM,            type = ro;
    AUDIO:    load = ROM,            type = ro,                optional = yes, start = $EF00;
    SETUP:    load = ROM,            type = ro,                                start = $EFE8;
}
...

 but I got a frozen red screen.

On the same page I read:
"More ROM may need additional bankswitching code."

How can I do this in C? Any example/tutorial?

  Fabrizio

**Comment by groessler** [comment]
Ok. The documentation might not be 100% accurate. There are no other creativision config files currently.

> ROM: file = %O, define = yes, start = $B000, size = $4000, fill = yes, fillval = $FF;

This is definitely wrong. See http://www.madrigaldesign.it/forum/viewtopic.php?f=13&t=16&start=10#p528 for a memory map.

I got it (`joy-test.c`) to work with an 8K ROM with this config file change:


```
--- cfg/creativision.cfg        2017-10-14 00:28:02.692293698 +0200
+++ /tmp/creativision.cfg       2017-11-14 23:16:02.091828546 +0100
@@ -4,7 +4,7 @@
 MEMORY {
     ZP:  file = "", define = yes, start = $0020, size = $00E0;
     RAM: file = "", define = yes, start = $01FA, size = $0206;
-    ROM: file = %O, define = yes, start = $B000, size = $1000, fill = yes, fillval = $FF;
+    ROM: file = %O, define = yes, start = $A000, size = $2000, fill = yes, fillval = $FF;
 }
 SEGMENTS {
     ZEROPAGE: load = ZP,             type = zp;

```

According to the link above, up to 16K should work. But my emulator (cvemu2, 0.6.1) crashes when I try to load such a ROM.


> "More ROM may need additional bankswitching code."
> How can I do this in C? Any example/tutorial?

It depends on the cartridge hardware. I don't know enough about Creativision to tell whether such cartridges exist and how they work. Anyway, implementing this will not be trivial. You would have to be careful which function calls which function. If they reside in different banks, some housekeeping is needed. Typically globally accessible functions will be called thru a stub which enables the correct bank. Local functions inside a bank can call each other as usual.

**Comment by oliverschmidt** [comment]
@Fabrizio-Caruso: The "(?)" in the title of this issue implies that you are unsure if you maybe just didn't find "the different linker configs" mentioned in the doc. So let me first acklowledge that you are right - there aren't any different configs present.

So the actual issue here is that the doc is wrong. This is already fixed by now with https://github.com/cc65/cc65/commit/c99a36155b67505c64123e5ec5db158b1446f2b6 - thanks to Chris.

Therefore I close this issue - you're of course welcome to use it nevertheless to discuss Creativision linker configs...

**Comment by Fabrizio-Caruso** [comment]
@all @oliverschmidt @groessler 
In #590 I have found the way to create 16k roms... It is not a CC65 issue, at all. Just a stupid convention.
