### ISSUE TITLE
[supervision][lynx] Missing joystick masks

### ISSUE THREAD

**Issue by Fabrizio-Caruso** [cc65/cc65#523]
It seems to me that the supervision and lynx targets do not have joystick masks.
I am getting the following kind of errors:
src/input_macros.c(125): Error: Undefined symbol: `JOY_BTN_1_MASK'
src/input_macros.c(146): Error: Undefined symbol: `JOY_UP_MASK'
src/input_macros.c(150): Error: Undefined symbol: `JOY_DOWN_MASK'
src/input_macros.c(154): Error: Undefined symbol: `JOY_LEFT_MASK'
src/input_macros.c(158): Error: Undefined symbol: `JOY_RIGHT_MASK'
src/input_macros.c(162): Error: Undefined symbol: `JOY_BTN_1_MASK'

Is this the expected behavior for some reason?

**Comment by oliverschmidt** [comment]
* Regarding Lynx I can't follow you:
https://github.com/cc65/cc65/blob/7f52a770d9c6a43dde67689032bb3a4848eb6b30/include/lynx.h#L91-L96

* Regarding Supervision the reason is that there's no joystick support at all - see: http://cc65.github.io/doc/supervision.html#ss5.3

**Comment by Fabrizio-Caruso** [comment]
Sorry :-( This is an invalid report.
