### ISSUE TITLE
Feature request: wait beam function

### ISSUE THREAD

**Issue by spektro** [cc65/cc65#526]
I'm requesting a function for waiting the vertical beam to reach a given raster line on the Commodore Plus/4. I'd like to synchronize drawing with the vertical beam to avoid flickering.

**Comment by groessler** [comment]
Nice attitude "I'm requesting"...

Use `waitvsync()`...

**Comment by spektro** [comment]
Not making any demands, just asking.

I found the waitvsync() macro from the fire.c sample program, thanks!

Here is my C16/Plus/4 version of the macro:
`#define waitvsync() while(!(TED.rasterline_hi&0x01))`

It seems that drawing to bitmap takes so long that beam syncing doesn't eliminate flickering :(

**Comment by greg-king5** [comment]
`waitvsync()` is declared by `<cbm.h>`.

**Comment by polluks** [comment]
@spektro an alternative method may be double buffering...

**Comment by spektro** [comment]
@greg-king5
So it is :) I missed the `cbm.h`'s `waitvsync()` because I didn't have the latest cc65 version installed.

@polluks
I'm trying to avoid double buffering because it would require over 20kB of memory (two bitmap screens).
