### ISSUE TITLE
What is missing in "Missing memory area assignment for segment `EXP'" ?

### ISSUE THREAD

**Issue by Fabrizio-Caruso** [cc65/cc65#527]
I am trying to make a minimalist version of my game for the VIC20+3K.

I am using a modified cfg file with the extra 3K in $0400-$0BFF (which should be right) as follows:
```ini
MEMORY {
    ZP:       file = "", define = yes, start = $0002, size = $001A;
    EXP:      file = %O,               start = $0400, size = $0BFF;
    LOADADDR: file = %O,               start = $0FFF, size = $0002;
    HEADER:   file = %O,               start = $1001, size = $000C;
    MAIN:     file = %O, define = yes, start = $100D, size = $0DF3 - __STACKSIZE__;
}
SEGMENTS {
    ZEROPAGE: load = ZP,       type = zp;
    LOADADDR: load = LOADADDR, type = ro;
    EXEHDR:   load = HEADER,   type = ro;
    STARTUP:  load = EXP,     type = ro;
    LOWCODE:  load = EXP,     type = ro,  optional = yes;
    ONCE:     load = EXP,     type = ro,  optional = yes;
    CODE:     load = MAIN,    type = ro;
    RODATA:   load = EXP,     type = ro;
    DATA:     load = EXP,     type = rw;
    INIT:     load = EXP,     type = bss;
    BSS:      load = EXP,     type = bss, define   = yes;
```

All my .c files, except for "main.c",  start with

```C
#if defined(__VIC20__) && defined(TINY_GAME) && defined(EXP_3K)
	#pragma code-name (push, "EXP")
#endif
```

and, end with:

```C
#if defined(__VIC20__) && defined(TINY_GAME) && defined(EXP_3K)
	#pragma code-name (pop)
#endif
```

What is wrong?

**Comment by groessler** [comment]
I don't know the reason for the error right now, but your config file won't work anyway.

You're putting the new EXP segment before the LOADADDR and HEADER, resulting in a useless file which the VC20 won't be able to load.

What I gather from http://www.vex.net/~falco/commodore/vic20-memorymap.pdf and playing a bit with VICE is that for the 3K expanded VC20, the memory starts at $400 instead of $1000. So change the LOADADDR, HEADER, and MAIN memory areas to reflect that.

**Comment by Fabrizio-Caruso** [comment]
EXP starts at $400 in my cfg file. Is it just a problem of the order if the memory areas?

**Comment by Fabrizio-Caruso** [comment]
I got it maybe: I need to have  loadaddr and header start at the right locations.

**Comment by greg-king5** [comment]
RAM is contiguous in the VC20+3K.  Therefore, you don't need a special memory area.  The only things that need changing are the start addresses and main's size:

```ini
MEMORY {
    ZP:       file = "", define = yes, start = $0002, size = $001A;
    LOADADDR: file = %O,               start = $03FF, size = $0002;
    HEADER:   file = %O,               start = $0401, size = $000C;
    MAIN:     file = %O, define = yes, start = $040D, size = $1E00 - __MAIN_START__ - __STACKSIZE__;
}
```

**Comment by greg-king5** [comment]
The error message came from the fact that you named a segment in your `code-name` pragma; but, you didn't name it (as a segment) in your configure file.

**Comment by oliverschmidt** [comment]
I don't know enough about the VC20 RAM extensions to judge bu it seems to me that it would be easy who does to modify https://github.com/cc65/cc65/blob/master/cfg/vic20.cfg to allow to set those values from the linker cmd line. Maybe that would even make https://github.com/cc65/cc65/blob/master/cfg/vic20-32k.cfg unnecessary altogether.

**Comment by Fabrizio-Caruso** [comment]
Thanks everyone! I have managed to create a minimalistic version of my game even for a Vic20+3k!

@oliverschmidt vic20-32k is easy to create from the unexpanded cfg.
What I needed is slightly more complicated. I would also put vic20-3k in order to help the developers.
If a single short file makes the life of the developers easier, it is worthwhile IMHO.
