### ISSUE TITLE
ca65: Feature Request: Support escape sequences in strings

### ISSUE THREAD

**Issue by inexorabletash** [cc65/cc65#535]
It would be handy to be able to write:
```asm
    .byte   "Give us a hint, by ringing a bell!\x07"
```
Although it can be written as `"abc",$07,"def"` this makes string-processing macros far more complex, and impacts readability.

This would presumably require a new directive to enable escapes (`.STRINGESCAPES +` or some such) for backwards compatibility, and making it play nicely with `.LINECONT` would be important - I want both!

* The most important escape to include would be the C-style `\xNN` form (IMHO)
* `\\` for a literal backslash, of course.
* `\"` for embedded quotes
* `\t` ($09) and `\r` ($0D) are probably safe
* `\n` gets tricky. Is that platform specific ($0D on apple2) or generic ($0A) ?
* I've never been a fan of octal `\000` but presumably some folks are.

C has grown [others](https://en.wikipedia.org/wiki/Escape_sequences_in_C#Table_of_escape_sequences). No objections to including more, but not advocating for them either.

**Comment by spiro-trikaliotis** [comment]
I understand your wish, but this would add an imcompatibility with older sources that include a backslash.
Thus, from my point of view, there should be another pseudo-op for allowing escape sequences (or a "parameter" or something like this)

**Comment by inexorabletash** [comment]
Indeed:

> This would presumably require a new directive to enable escapes (.STRINGESCAPES + or some such) for backwards compatibility

**Comment by spiro-trikaliotis** [comment]
Ouch... I am sorry, it seems I have problems reading and understanding what I am reading. :)

**Comment by Fabrizio-Caruso** [comment]
Which sequences?
ADM3A, VT52, VT100? Any of them to be set by an option?

**Comment by greg-king5** [comment]
> Which sequences?
> ADM3A, VT52, VT100?  Any of them to be set by an option?

He wasn't talking about "terminal escape sequences".  He was talking about the single-character literals that can be used in C source code: `'\r', '\n', '\t',` and so on.
