### ISSUE TITLE
asminc/opcodes.inc has duplicate members if cpu is "65C02"

### ISSUE THREAD

**Issue by inexorabletash** [cc65/cc65#537]
```asm
.setcpu "65C02"
.include "opcodes.inc"
```
Result: **cc65/asminc/opcodes.inc(249): Error: Symbol `OPC_EOR_abx' is already defined**

```
$ grep EOR_abx asminc/opcodes.inc 
OPC_EOR_abx = $5D
OPC_EOR_abx = $5C
```

It's `OPC_EOR_abx = $5C` which appears bogus per http://www.6502.org/tutorials/6502opcodes.html

If "6502" is used, everything is fine.

**Comment by oliverschmidt** [comment]
Fixed with https://github.com/cc65/cc65/commit/947b09ad96902cc2a4d775660c77fd496a3bedbd.
