### ISSUE TITLE
[Optimizer] Call to empty function generates code

### ISSUE THREAD

**Issue by Fabrizio-Caruso** [cc65/cc65#538]
Calling an empty function (e.g., void foo() {}) generates some code, which takes up a few bytes (for nothing).

I thought this would be optimized by the compiler.

P.S.: Having empty functions is not always pointless for instance when doing some sort of object-oriented programming.

**Comment by oliverschmidt** [comment]
Are you aware that this could conceptually only work for functions defined in the same source file?

**Comment by Fabrizio-Caruso** [comment]
Yes and no: if a post-processing optimizer were invoked after the linker (e.g., some sort of peephole rules) it would probably remove the unnecessary code.

**Comment by oliverschmidt** [comment]
And if we could travel backward in time we could rectify all our mistakes ;-)

**Comment by greg-king5** [comment]
cc65 has only a peephole optimizer.  Each function is an island.  It knows nothing about how other functions are implemented; it cannot know when they are empty.  It always will call other functions.  Therefore, they always must be able to return from a call.

What you want are module and link-time optimizers -- which this project probably won't have.

**Comment by oliverschmidt** [comment]
@greg-king5: Thanks for the nice words :-)
