### ISSUE TITLE
No sound in CBM5x0

### ISSUE THREAD

**Issue by Fabrizio-Caruso** [cc65/cc65#539]
My game produces no sound on the CBM5x0.
I am using the very same code that uses the SID definitions. 
This code works on the C128 and C64 but not on the CBM5x0 (emulated by Vice 3.1)

I wonder whether there is a problem in the SID struct or in Vice 3.1.

**Comment by greg-king5** [comment]
See the _note_ at http://cc65.github.io/doc/cbm510.html#ss4.3.
