### ISSUE TITLE
cl65 doesn't seem to like paths contains spaces

### ISSUE THREAD

**Issue by lazarusr** [cc65/cc65#540]
**_"C:\Program Files (x86)\cc65\bin\cl65.exe" -C config.conf laz_mon.a65_** results in the following error **_Program: Don't know what to do with `(x86)\cc65\bin\ca65'_**

**_"C:\cc65\bin\cl65.exe" -C config.conf laz_mon.a65_** works just fine.

This doesn't seem to be a problem for ca65 or ld65. The following works without a problem
**_"C:\Program Files (x86)\cc65\bin\ca65.exe" laz_mon.a65 
"C:\Program Files (x86)\cc65\bin\ld65.exe" -C config.conf laz_mon.o_**

**Comment by mrdudz** [comment]
Am Mittwoch, 29. November 2017, 19:54:34 CET schrieb lazarusr:
> **_"C:\Program Files (x86)\cc65\bin\cl65.exe" -C config.conf laz_mon.a65_**
> results in the following error **_Program: Don't know what to do with
> `(x86)\cc65\bin\ca65'_**
> 
> **_"C:\cc65\bin\cl65.exe" -C config.conf laz_mon.a65_** works just fine.
> 
> This doesn't seem to be a problem for ca65 or ld65. The following works
> without a problem **_"C:\Program Files (x86)\cc65\bin\ca65.exe" laz_mon.a65
> "C:\Program Files (x86)\cc65\bin\ld65.exe" -C config.conf laz_mon.o_**

thats probably the retarded behaviour of the windows "shell", which requires 
the program to handle quoting. we had a similar bug in VICE a while ago.

-- 

http://www.hitmen-console.org    http://magicdisk.untergrund.net
http://www.pokefinder.org        http://ar.pokefinder.org

Jetzt sag nicht wir müssten unseren Kindern in der Schule Medienkompetenz 
beibringen? Können wir nicht lieber irgendwas verbieten?

**Comment by oliverschmidt** [comment]
http://cc65.github.io/cc65/getting-started.html#Windows says:

Download the current cc65 snapshot and unzip it to a path of your choice that doesn't contain spaces (let's presume 'c:\cc65' here).
