### ISSUE TITLE
OSIC1P: toupper() and related functions do not work correctly

### ISSUE THREAD

**Issue by jefftranter** [cc65/cc65#542]
I noticed that the functions like toupper() and tolower() do not work correctly on the OSI C1P platform. The cause is that the data in libsrc/osic1p/ctype.s is not correct. The OSI platform uses standard ASCII, but this table does not. A standard ASCII table like the one in libsrc/sim6502/ctype.s will work. I can submit a pull request for this if needed, or just copy the file from the sim6502 version to osic1p.

**Comment by oliverschmidt** [comment]
Thanks for the report incl. fix proposal :-)

Fixed with https://github.com/cc65/cc65/commit/563185998fd071e48682d1abb8f2a7925505ba76.

**Comment by jefftranter** [comment]
Thank! I can confirm that the fix works.

**Comment by oliverschmidt** [comment]
Thanks for the Feedback.
