### ISSUE TITLE
Enhancements to multiplication runtime - Booth's Algorithm for 6502

### ISSUE THREAD

**Issue by prandeamus** [cc65/cc65#544]
First time contributor - be nice, please!
It's been 30 years since I worked with the 6502 but it was a part of my life in those days. On thing I did when I was young was write an implementation of Booth's algorithm for integer multiplication, and it was somewhat faster than conventional multiplication algorithms (on average, there are a few corner cases).
For fun, I've recreated some of that work in some ca65 assembly code and done some simple benchmarks. Is anyone interested in refining this work? I lack the patience to figure out all the cycle times, but my implementation of an 8x8 signed multiply does seem faster that the built-in version in the standard runtime.
I would appreciate some guidance and maybe a collaborator. Yes, I know git moderately well, but am new to the project.

**Comment by spiro-trikaliotis** [comment]
I know the Booth's algorithm, as I wrote. But I always thought that the handling of 2 bits at a moment would need more cycles, even if you use something like a state machine where you just know what the previous bit was.

As far as you do not try to implement Schönhage-Strassen multiplication (https://en.wikipedia.org/wiki/Sch%C3%B6nhage%E2%80%93Strassen_algorithm), everything should be good ;)
Imay be biased, I had some courses from Prof. Schönhage.

I think the best way is to create a pull request, so we can use the mechanisms of Github for the review.

**Comment by prandeamus** [comment]
Ha. I didn't know git and github as well as I thought. I have a local branch with the files, but I can't push that branch. 
"remote: Permission to cc65/cc65.git denied to prandeamus"
I'm a new account; does that make a difference?

**Comment by mrdudz** [comment]
you'll have to create a pull request, you cant just push to the main repo

**Comment by silverdr** [comment]
> On 2017-12-12, at 00:17, prandeamus <notifications@github.com> wrote:
> 
> Ha. I didn't know git and github as well as I thought. I have a local branch with the files, but I can't push that branch.
> "remote: Permission to cc65/cc65.git denied to prandeamus"
> I'm a new account; does that make a difference?

The difference is most probably in your workflow expectations. The typical process looks as follows:

1. you "fork" the main repository to your account
2. you clone your forked repository to your local workstation
3. you make a "feature branch" in your cloned local copy
4. you make your changes/commits in the branch created in [3.]
5. you push changes to your repository
6. you create "pull request" from your feature branch to the upstream repository
7. people review your pull request, discuss it, comment and eventually accept or reject it.

It looks unnecessary complicated at first but once you get used to this workflow you won't want to work any other way :-)

-- 
SD!

**Comment by oliverschmidt** [comment]
@silverdr: Thanks for the nice explanation :-)

I'd like to add that the GitHub pull request approach perfectly fits the scenario at hand: The "casual contribution".

**Comment by prandeamus** [comment]
Thanks for your assistance with github. I've created a pull request for discussion. Enjoy.

**Comment by prandeamus** [comment]
Looks like I screwed up the tabs/spaces. Never mind, it should still compile. Given time, can fix.

**Comment by oliverschmidt** [comment]
Now that there's a pull request I close this issue.
