### ISSUE TITLE
C128 conio scrolls the screen when it shouldn't

### ISSUE THREAD

**Issue by mrdudz** [cc65/cc65#548]
what the topic says, a workaround is:

`*((unsigned char*)0xf8)=0xff; // disable all scrolling (workaround for buggy conio)`

it could perhaps be done in the constructor. this happens in both 40col and 80col (VDC) mode when printing to the character at the bottom right

**Comment by polluks** [comment]
@mrdudz Are you sure? hello.c works fine.
`cputc (CH_LRCORNER);` is printing to the character at the bottom right!

**Comment by mrdudz** [comment]
interesting, yes i am pretty sure - my tetris thingy will be completely messed up without that fix. have to admit that i didnt try to make a simple testcase though - perhaps it needs another CR or so to make it scroll?

**Comment by polluks** [comment]
Maybe. You know the old conio restriction: Don't force scrolling.

**Comment by mrdudz** [comment]
Am Samstag, 27. Januar 2018, 20:25:25 CET schrieb Stefan:
> Maybe. You know the old conio restriction: Don't force scrolling.

i am not aware of that restriction - is it documented like that? iirc all it 
says is that conio does not scroll

-- 

http://hitmen.eu                 http://ar.pokefinder.org
http://vice-emu.sourceforge.net  http://magicdisk.untergrund.net

If you look at scrollback and the last 30 lines are from you ... please shut 
up 
<Moloch/Arkanix Labs>

**Comment by oliverschmidt** [comment]
I seem to remember that Uz did something related to scrolling in 80 col mode as I had issue with Contiki back then. I checked the commits. Maybe something for this is relevant:
https://github.com/cc65/cc65/commit/4bf888aa623667580ad27ec4ee90fd8eb1ceace5#diff-83ab357e67ddfae1209141ceae688df8
https://github.com/cc65/cc65/commit/2bd1f2f69f194fc01804a3fccf9ef371845ffc4a#diff-83ab357e67ddfae1209141ceae688df8
https://github.com/cc65/cc65/commit/9656dde9e3e6a3ab9fd178d78b8fd115b875829d#diff-83ab357e67ddfae1209141ceae688df8
https://github.com/cc65/cc65/commit/21c38fa7db61cbc97a610cbea3664936c48d60b5#diff-83ab357e67ddfae1209141ceae688df8
Sorry for the noise this should be totally irrelevant for the issue at hand.

**Comment by polluks** [comment]
Thx. The scroll flag is already used, so please attach a snipped.

**Comment by oliverschmidt** [comment]
> Thx. The scroll flag is already used, so please attach a snipped.

Does this comment refer to my comment? If yes, please elaboate on "please attach a snipped" bcause I have no clue.

**Comment by mrdudz** [comment]
Am Sonntag, 28. Januar 2018, 00:53:35 CET schrieb Oliver Schmidt:
> I seem to remember that Uz did something related to scrolling in 80 col mode
> as I had issue with Contiki back then. I checked the commits. Maybe
> something for this is relevant:
> https://github.com/cc65/cc65/commit/4bf888aa623667580ad27ec4ee90fd8eb1ceace
> 5#diff-83ab357e67ddfae1209141ceae688df8
> https://github.com/cc65/cc65/commit/2bd1f2f69f194fc01804a3fccf9ef371845ffc4
> a#diff-83ab357e67ddfae1209141ceae688df8
> https://github.com/cc65/cc65/commit/9656dde9e3e6a3ab9fd178d78b8fd115b875829
> d#diff-83ab357e67ddfae1209141ceae688df8
> https://github.com/cc65/cc65/commit/21c38fa7db61cbc97a610cbea3664936c48d60b
> 5#diff-83ab357e67ddfae1209141ceae688df8 Sorry for the noise this should be
> totally irrelevant for the issue at hand.

it looks related. perhaps the problem is that i dont use videomode() to switch 
to VDC? i did something like this at the beginning of main():

```
    #if defined (__VDC__)
        puts("switching to VDC...\n\r");
        puts("\x1bx"); // send ESC-x to stdout (switch to VDC screen)
        puts("\x0e"); // send asc 14 to stdout (toggle lowercase, workaround 
for buggy conio)
        *((unsigned char*)0xf8)=0xff; // disable all scrolling (workaround for 
buggy conio)
    #endif
```



-- 

http://hitmen.eu                 http://ar.pokefinder.org
http://vice-emu.sourceforge.net  http://magicdisk.untergrund.net

They misunderestimated me. 
<George W. Bush>

**Comment by polluks** [comment]
No, it's rather trivial
- you start in VDC, you get VDC conio
- you start in VIC, you get VIC conio

Your code seems against UX. BTW ESC X is a toggle.
In an analogous manner Apple code should not force `PR#3`.

**Comment by mrdudz** [comment]
no idea what you are trying to say. the program can only work with VDC, so it will always switch to it. and no matter how much the user doesnt expect it to do that - it still shouldnt result in buggy behaviour =)

**Comment by oliverschmidt** [comment]
Is there a reason why a cc65 program that as far as I understand wants to show cc65 capabilities doesn't use videomode()?

Regarding the user expectation I'd personally say that if the machine was in VIC mode when the program starts the program should switch back to VIC mode when it ends. The return value of videomode() is supposed to make exactly that trivial.

**Comment by polluks** [comment]
@mrdudz Aha, VDC only, that is something different. You are on your own. This is not a bug IMHO. My suggestion: Output an error message and exit. Maybe the user didn't change the monitor because an 80 cols monitor is missing...

@oliverschmidt My //e simply has no 80 cols card.

**Comment by mrdudz** [comment]
> Is there a reason why a cc65 program that as far as I understand wants to show cc65 capabilities doesn't use videomode()?

no specific reason - perhaps that function didnt exist 10+ years ago when wrote this code?

that said, with videomode() it appears to work - perhaps that should be documented then? not sure what a c128 programmer would expect regarding this behaviour :=)

> Regarding the user expectation I'd personally say that if the machine was in VIC mode when the program starts the program should switch back to VIC mode when it ends.

i am willing to bet that on c128 the user expects the program not to exit to basic at all :=)

> My suggestion: Output an error message and exit.

thats just terrible. and certainly not what a user expects either. there are quite some programs that you would start in 40 cols and that then keeps using 80 cols.

**Comment by polluks** [comment]
> i am willing to bet that on c128 the user expects the program not to exit to basic at all :=)

You have done too many demos ;-)

> thats just terrible. and certainly not what a user expects either.

Well, we have a different definition of "terrible":
- a user has no VDC monitor, nothing happens and he waits forever...
- a programmer wants VIC conio and VDC stdio (e.g. debug output) but it doesn't scroll anymore because of your feature request
- an API should not allocate all resources

**Comment by oliverschmidt** [comment]
> Output an error message and exit.

Stupid question. My understand is that the scenario at hand is a C128 without a monitor connected to the VDC output. So how would a program detect that there's no monitor present? Or do you suggest to treat it as error that the program is started in VIC mode? The latter would turn videomode() pretty useless, wouldn't it?

> My //e simply has no 80 cols card, so videomode would crash.

What makes you think so? Have you tried it? My understanding is that it just wouldn't switch to 80 col mode. And that you could detect this using screensize() afterwards.

**Comment by oliverschmidt** [comment]
> no specific reason - perhaps that function didnt exist 10+ years ago when wrote this code?

Surely it didn't.

> that said, with videomode() it appears to work

:-) 

If "it" refers to switching from 40 cols to 80 cols in general then I'd say that it does not only appear to work but that it actually works. E.g. the Contiki web browser uses it for quite some time...

> perhaps that should be documented then?

What does "that" refer to? That videomode() appears to work? I guess that would pretty much blow up the cc65 doc to add to every function that it "btw appears to work" ;-))

> i am willing to bet that on c128 the user expects the program not to exit to basic at all :=)

Sorry I know so little about C128 user expectations that even don't understand if this is a joke. Maybe that users expect cc65 programs to crash at the latest when they exit - just trying to guess...

**Comment by oliverschmidt** [comment]
> a user has no VDC monitor, nothing happens and he waits forever...

Maybe it would be an idea to output a message to VIC before switching to VDC informing the user of the action the program is about to perform so he doesn't need to wait but knows that he needs to switch to VDC display (or kill the program).

**Comment by polluks** [comment]
videomode() is not useless, you could use both monitors at once.
My Apple doesn't run anymore (the psu caps) but in the source I saw an unconditional `jsr $C300`.

**Comment by oliverschmidt** [comment]
> in the source I saw an unconditional jsr $C300.

videomode() is only available for the enhanced //e. The 80 col board for that machine only contains the actual RAM chips. The ROM at $C300 is part of the base machine.

>  What about the return code of videomode()?

What is written at http://cc65.github.io/doc/funcref.html#ss3.235 - however, for you convenience: `The old mode is returned from the call.`

**Comment by mrdudz** [comment]
> If "it" refers to switching from 40 cols to 80 cols

that, and after it conio doesnt randomly scroll the screen up. vs after switching to 80 cols using ESC-X, then the scrolling is broken.

> Sorry, I know so little about C128 user expectations that even don't understand if this is a joke. Maybe that users expect cc65 programs to crash at the latest when they exit - just trying to guess...

most programs in the commodore world do not exit to basic. actually most do not exit at all - and if they exit, they would usually do that with a soft reset. (CBM machines have no concept of "shell" so exiting to basic has little practical use)

> Maybe it would be an idea to output a message to VIC before switching to VDC informing the user of the action the program is about to perform so he doesn't need to wait but knows that he needs to switch to VDC display (or kill the program).

yes - thats what my programs does. (mind you, a lot of other programs that run in 80 colums just give you a garbled VIC screen... because switching to 2mhz would do just that)

**Comment by silverdr** [comment]
"most programs in the commodore world do not exit to basic. actually most do not exit at all - and if they exit, they would usually do that with a soft reset." - it's getting off-topic but the fact that most non-BASIC programs do not exit back to BASIC or exit via soft reset is because most programmers were lazy in this regard or didn't have enough resources (memory) left in their games/demos or both. Programs I write (occasionally, I admit) these days using cc65/ca65 always do proper cleanup and return to BASIC. Whenever possible (most of the times) they can also be run again, and again, and again. Therefore the fact that people got used to being treated poorly in this regard doesn't mean that they wouldn't like a program that would exit cleanly and could possibly be run again without re-loading. Personally I find this way much more mature and elegant.

**Comment by mrdudz** [comment]
sure sure. i'm not saying you shouldnt do it. i am only saying that most users wouldnt expect you to do it :)

**Comment by polluks** [comment]
@mrdudz I expect "UX 2018" of a compiler of 2018 :blush:

**Comment by mrdudz** [comment]
This can be closed, yes? :)

**Comment by polluks** [comment]
Do it :blush:
