### ISSUE TITLE
C128 conio starts in uppercase mode

### ISSUE THREAD

**Issue by mrdudz** [cc65/cc65#549]
what the topic says, a workaround is:

`puts("\x0e"); // send asc 14 to stdout (toggle lowercase, workaround for buggy conio)`

it can perhaps be done in some other way (setting some zeropage flag or so) in the constructor. this only happens in 80cols (VDC) mode!

**Comment by polluks** [comment]
better `putchar(14);`

**Comment by mrdudz** [comment]
The original problem was that i switched from 40- to 80- columns and did not use videomode() for this. With videomode() it works fine -> closing :)
