### ISSUE TITLE
C16 linker config is wrong

### ISSUE THREAD

**Issue by mrdudz** [cc65/cc65#551]
the current c16 config uses too much memory, so the resulting files may not work. the fix looks like this:
```

-    MAIN:     file = %O,               start = $100D, size = $6FF3 - __STACKSIZE__;
+    MAIN:     file = %O,               start = $100D, size = $3FF3 - __STACKSIZE__;

```

**Comment by Fabrizio-Caruso** [comment]
C16 is C16/C116 with 32k of ram (max ram with no need for bank-switching). 
What makes the C16 target different from the PLUS4 target is the lack of bank switching.

**Comment by mrdudz** [comment]
are you sure? it may well be that VICE is wrong in this regard, but it shows 12277 bytes free, which equals $3fff as RAM end. and when trying to load a file that is longer than that its screws up.

that said, i couldnt find a proper memory map for c16 - its all for plus4 (which is obviously different)

**Comment by mrdudz** [comment]
ok asked around a bit, and the result is: its definately 16k, not 32k. no idea where the 32k come from.

see eg http://www.zimmers.net/anonftp/pub/cbm/schematics/computers/plus4/C16_Service_Manual_314001-03_(1984_Oct).pdf (page 1)
or https://archive.org/stream/Commodore_16_User_Manual_1984_Commodore#page/n6/mode/1up

the 32k config should be provided as an extra cfg for expanded C16s, but it shouldnt be the the default.

**Comment by oliverschmidt** [comment]
Could you imagine to extend this PR to include a new file named c16-32k.cfg (?) with the content of the current file?

**Comment by mrdudz** [comment]
ok someone cleared it up - 32k comes from the japanese C232: http://c128.com/commodore-c232-32k-ted-courtesy-rob-clark

oliver: this is no PR =) i am posting issues/bugs while i find them... i will fix them all at once in one PR later, i dont really feel like making a branch and PR and all that jizz for several one line patches

**Comment by oliverschmidt** [comment]
> oliver: this is no PR =)

Sorry, it's getting too late and/or I'm getting too old.

**Comment by oliverschmidt** [comment]
Fixed with https://github.com/cc65/cc65/pull/553.
