### ISSUE TITLE
Optimisation: Using Y register in leasp routines?

### ISSUE THREAD

**Issue by prandeamus** [cc65/cc65#558]
There's nothing as dangerous as a little knowledge. That said, I'd like to ask a question

From g_leasp() in codegen.c there is the following fragment:

        /* Full 16 bit offset inlined */
        AddCodeLine ("lda sp");
        AddCodeLine ("clc");
        AddCodeLine ("adc #$%02X", Lo);
        AddCodeLine ("pha");
        AddCodeLine ("lda sp+1");
        AddCodeLine ("adc #$%02X", Hi);
        AddCodeLine ("tax");
        AddCodeLine ("pla");

Given that PHA takes 3 cycles and PLA takes 4, but TAY and TYA both take 2 cycles, would it not be faster to do the following to store the lo byte sum in Y rather than on the stack?

        /* Full 16 bit offset inlined */
        AddCodeLine ("lda sp");
        AddCodeLine ("clc");
        AddCodeLine ("adc #$%02X", Lo);
        **AddCodeLine ("tay");**
        AddCodeLine ("lda sp+1");
        AddCodeLine ("adc #$%02X", Hi);
        AddCodeLine ("tax");
        **AddCodeLine ("tya");** 

The same logic change would apply for the code in runtime/leaaxsp.s 

I guess it depends on whether the code generated in g_leasp needs to preserve Y.

This enquiry comes from a bottom-up reading of some of the code generator. Under what circumstances does this routine get called? I see it's connected with loading the effective address relative to the stack, but if the stack size is limited would a 16-bit offset from a stack variable is make any sense?

**Comment by polluks** [comment]
At least most targets have 2 K stack, so we need the 16-bit offset.

**Comment by prandeamus** [comment]
Thanks for the explanation on stack size.  I think I was confusing it with the hardware stack. 
Regarding using tay/tya, I suppose I need to know if runtime expects Y to be saved across these calls.

**Comment by oliverschmidt** [comment]
> I suppose I need to know if runtime expects Y to be saved across these calls.

So let me close this until then...

**Comment by prandeamus** [comment]
Generically, I would say it does not preserve Y between calls, based on my reading of a lot of code. But yes we can close this and re-open it or create a new ticket when we have a clearer view.

**Comment by oliverschmidt** [comment]
Thanks for your feedback :-)
