### ISSUE TITLE
[cfg][info request][vic 20] Where to place __STACKSIZE__?

### ISSUE THREAD

**Issue by Fabrizio-Caruso** [cc65/cc65#559]
I have finally managed to use UDG in the Vic 20 (+8k and +16k) versions of CROSS CHASE.
The complication for me comes from the fact that memory has to be segmented, due to the fact that the VIC chip only sees the original 5k.

My cfg is a hack (that seems to work if the value of __STACKSIZE__ is exactly $104) 
but it must be wrong:
...
    __STACKSIZE__: type = weak, value = $0104; # 256 byte stack
...
MEMORY {
    ZP:       file = "", define = yes, start = $0002, size = $001A;
    SCREEN:   start =  $1000, size = $0200;
    LOADADDR: file = %O,               start = $11FF, size = $0002;
    HEADER:   file = %O,               start = $1201, size = $000C;
    MAIN:     file = %O, define = yes, start = $120D, fill = yes, size = $1C00 - $120D;
    CHARMEM:  file = %O, start = $1C00, size = $0400, type = rw,  define = yes, fill = yes;
    RAM1: 	  file = %O, start = $2000, size = $4000, type = rw;
}

SEGMENTS {
    ZEROPAGE: load = ZP,       type = zp;
    LOADADDR: load = LOADADDR, type = ro;
    EXEHDR:   load = HEADER,   type = ro;
    STARTUP:  load = MAIN,     type = ro;
    LOWCODE:  load = MAIN,     type = ro,  optional = yes;
    ONCE:     load = MAIN,     type = ro,  optional = yes;
    CODE:     load = RAM1,     type = ro;
    RODATA:   load = MAIN,     type = ro;
    DATA:     load = MAIN,     type = rw;
    INIT:     load = MAIN,     type = bss;
    BSS:      load = MAIN,     type = bss, define   = yes;
    UDCCHAR:  load = CHARMEM,  type = ro, define = yes, optional = no;
}
...

I have two memory areas MAIN and RAM1 for code and data.
I guess I should also take into account __STACKSIZE__. Where? Where is the stack placed?
Does it go to the DATA segment? to MAIN memory area?
With my current cfg the stack is writing onto the graphics area and causing display glitches in some characters.
If I use
	MAIN:     file = %O, define = yes, start = $120D, fill = yes, size = $1C00 - $120D - __STACKSIZE__;
then the game will compile but it won't start.

**Comment by oliverschmidt** [comment]
> Where to place __STACKSIZE__?

The answer to that question is: Usually on the cmdline, see https://github.com/cc65/cc65/blob/master/samples/Makefile#L72-L78 for examples on how to define values on the cmdline to be used in the cfg file.

**Comment by oliverschmidt** [comment]
> Where is the stack placed?

The answer to that question is:: Usually above the BSS (and hep if used), see https://github.com/cc65/wiki/wiki/Parameter-and-return-stacks#General_use and https://github.com/cc65/wiki/wiki/Parameter-and-return-stacks#Moving_the_stack.

**Comment by Fabrizio-Caruso** [comment]
So, I need to tell where the stack should start? Any cfg with an example of explicit stack?
All other cfg have an implicit stack, which was in the right place.
In my cfg, the stack is placed somewhere. I just want it to be placed whenever it is not causing troubles.

**Comment by Fabrizio-Caruso** [comment]
Writing
MAIN: file = %O, define = yes, start = $120D, fill = yes, size = $1C00 - $120D - __STACKSIZE__;
does not have the effect I expected, i.e., placing it at the end of the MAIN memory area.
It goes somewhere else.
If I want it to be at the end of MAIN, should I have it start at end of MAIN - __STACKSIZE__ ??
How do I compute the exact address of the stack?

**Comment by oliverschmidt** [comment]
> So, I need to tell where the stack should start?

I don't think so, I just answered your questions.

> MAIN: file = %O, define = yes, start = $120D, fill = yes, size = $1C00 - $120D - STACKSIZE;
does not have the effect I expected, i.e., placing it at the end of the MAIN memory area.

What does you make think so?

> It goes somewhere else.

If you don't know where your stack how do you know it isn't where it should be.

> If I want it to be at the end of MAIN, should I have it start at end of MAIN - STACKSIZE ??

Sorry but have you actually read the stuff I pointed you at? It says "stack that usually resides at the highest program data address and grows downwards (usually towards the heap)". So the stack has to  _start_ at the _end_ of the memory you want to reserve for it.

A final remark before I leave you to explore things on your own: The STACKSIZE thingie in the cfg file doesn't have any influence whatsoever on where the stack is actually placed. The actual placement is defined by the start value of `sp`. The STACKSIZE is only there to aid you in not having the stack destroy other areas of your program.

Good luck to go from here :-)

**Comment by Fabrizio-Caruso** [comment]
Thanks, I need to find where the value of "sp" is set in order to know where the stack is and how I should rewrite the cfg...

An example with an explicit STACK in the CFG (as the DOC says it should always be) would probably help.
The examples I find seem to have an implicit stack.

Writing
MAIN: file = %O, define = yes, start = $120D, fill = yes, size = $1C00 - $120D - __STACKSIZE__;
breaks the game but the game compiles, so I assume the stack is conflicting with the code in MAIN.
My assumption was that the line above means that the stack would be placed at the end of MAIN growing downwards and with max depth = __STACKSIZE__

**Comment by Fabrizio-Caruso** [comment]
I am trying to understand the doc:
"
The stack isn't put in a segment; it's put into a separate memory area. That area isn't named; it's implied by two expressions. The first one is in the ld65 configuration file. For example, 'c64.cfg' has size = $C7F3 - &#95;&#95;STACKSIZE&#95;&#95;. The second one is in the start-up code. For example, 'c64/crt0.s' has (&#95;&#95;RAM_START&#95;&#95; + &#95;&#95;RAM_SIZE&#95;&#95; + &#95;&#95;STACKSIZE&#95;&#95;)
"

So, the stack position is decided by the Assembly file crt0.s and not by whatever I write in the cfg file.

Once I know where it is place, I should be able to know how to adjust the cfg to make room for it.

**Comment by groessler** [comment]
> MAIN: file = %O, define = yes, start = $120D, fill = yes, size = $1C00 - $120D - STACKSIZE;
> breaks the game but the game compiles, so I assume the stack is conflicting with the code in MAIN.
> My assumption was that the line above means that the stack would be placed at the end of MAIN > growing downwards and with max depth = STACKSIZE

The line above just means that the size of MAIN is decreased by STACKSIZE, nothing else.

The stack pointer (sp) is initialized by the target's crt0.s startup file. VIC-20, e.g., does this:

        lda     #<(__MAIN_START__ + __MAIN_SIZE__ + __STACKSIZE__)
        ldx     #>(__MAIN_START__ + __MAIN_SIZE__ + __STACKSIZE__)
        sta     sp
        stx     sp+1            ; Set argument stack ptr

So if you want to be able to explicitly specifiy it in the config file, you need to define a STACK segment in your config file and adapt crt0.s to initialize sp to the end of this segment.

**Comment by groessler** [comment]
And be careful where your heap is...

**Comment by Fabrizio-Caruso** [comment]
Thanks @groessler ! I do not want to move it unless necessary. I just want to fix my cfg and avoid the stack from conflicting with my code or graphics data. 

If I write
MAIN: file = %O, define = yes, start = $120D, fill = yes, size = $1C00 - $120D - __STACKSIZE__;
the game compiles fine but crashes at start up.

If I avoid mentioning __STACKSIZE__, the game compiles and works but some characters are corrupted as if the stack were placed in the graphics area.
I want to have a CFG with no conflicts.

**Comment by groessler** [comment]
I don't know where on the VIC-20 the graphics memory resides, but if it's after MAIN, the case where you don't mention STACKSIZE in the config is clear.

        lda     #<(__MAIN_START__ + __MAIN_SIZE__ + __STACKSIZE__)
        ldx     #>(__MAIN_START__ + __MAIN_SIZE__ + __STACKSIZE__)

Since STACKSIZE wasn't subtracted in the config file, MAIN_SIZE is until end of MAIN, and then adding STACKSIZE puts sp beyond the end of MAIN.

**Comment by groessler** [comment]
> I have two memory areas MAIN and RAM1 for code and data.

Do you take the hole between MAIN and RAM1 into account? I guess you need to move the things after the hole into their correct location at runtime startup.

**Comment by Fabrizio-Caruso** [comment]
@groessler, the game works fine except for a couple of corrupted characters. I think MAIN and RAM1 are ok. I currently use pragmas to tell where the code should go.

The problem seems to be related to the stack probably writing the graphics area (CHARMEM below). The screen area has no issue.

I have
MAIN: file = %O, define = yes, start = $120D, fill = yes, size = $1C00 - $120D;
CHARMEM: file = %O, start = $1C00, size = $0400, type = rw, define = yes, fill = yes;

CHARMEM seems to be overwritten by the stack with the above setting.

From what you tell me, it seems that the stack is placed in CHARMEM (i.e., $1C00 + __STACKSIZE__, which is beyond $1C00 and inside CHARMEM)
So I should subtract __STACK_SIZE__ from the size of MAIN:
MAIN: file = %O, define = yes, start = $120D, fill = yes, size = $1C00 - $120D - __STACKSIZE__;

But if I do this, my game won't start. It does compile with no problems, though.
Maybe I am wrong by one byte??

**Comment by Fabrizio-Caruso** [comment]
If I follow the doc in https://github.com/cc65/wiki/wiki/Parameter-and-return-stacks#Moving_the_stack
and 

MAIN:     file = %O, define = yes, start = $120D, fill = yes, size = $1C00 - $120D - __STACKSIZE__;
STACK:    file="", define=yes, start=$1C00-, size=;

I get an 
ld65: Error: src/../cfg/vic20-16k_GFX.cfg(14): Invalid expression: 13
make: *** [Makefile:429: vic20_exp_16k_GFX] Error 1

Is there a typo in the doc?

**Comment by groessler** [comment]
Yes, this could be the problem. Since MAIN is now smaller (due to STACKSIZE), "fill=yes" doesn't fill all of MAIN (or the intended size of MAIN). Therefore CHARMEM and following segments are not placed correctly.

file=%O just appends to the output exe file. Unlike Atari, the CBMs don't have a notion of "holes" or "unused areas" in an exe file, everything is just loaded into memory in one chunk.

I think you could put an (unused) pseudo-memory area between MAIN and CHARMEM. It's size should be STACKSIZE, and start address just after MAIN.

**Comment by groessler** [comment]
And, use "fill=yes" for this memory area.

**Comment by groessler** [comment]
And #2, use the linker map file to double-check the addresses

**Comment by Fabrizio-Caruso** [comment]
Yes, it seems to work. What is really *misleading* is the mandatory start attribute, which is not taken into acount as start address. I wonder why it is there...

For the Vic 20 + 8k I am doing something like:
"
...
MEMORY {
    ZP:       file = "", define = yes, start = $0002, size = $001A;
    SCREEN:   start =  $1000, size = $0200;
    LOADADDR: file = %O,               start = $11FF, size = $0002;
    HEADER:   file = %O,               start = $1201, size = $000C;
    MAIN:     file = %O, define = yes, start = $120D, fill = yes, size = $1C00 - $120D - __STACKSIZE__;
    DUMMY:    file = %O,               start = $1C00 - __STACKSIZE__ - 1, fill = yes, size = __STACKSIZE__;
    CHARMEM:  file = %O, start = $1C00, size = $0400, type = rw,  define = yes, fill = yes;
    RAM1: 	  file = %O, start = $2000, size = $2000, type = rw;
}
SEGMENTS {
    ZEROPAGE: load = ZP,       type = zp;
    LOADADDR: load = LOADADDR, type = ro;
    EXEHDR:   load = HEADER,   type = ro;
    STARTUP:  load = MAIN,     type = ro;
    LOWCODE:  load = MAIN,     type = ro,  optional = yes;
    ONCE:     load = MAIN,     type = ro,  optional = yes;
    CODE:     load = RAM1,     type = ro;
    RODATA:   load = MAIN,     type = ro;
    DATA:     load = MAIN,     type = rw;
    INIT:     load = RAM1,     type = bss;
    BSS:      load = MAIN,     type = bss, define   = yes;
    UDCCHAR:  load = CHARMEM,  type = ro, define = yes, optional = no;
    CODE2:    load = MAIN,     type = ro;
}
...
"

Other things remain mysterious like why INIT has to be filled with RAM1 and not MAIN? (the game crashes otherwise)

**Comment by groessler** [comment]
> What is really misleading is the mandatory start attribute, which is not taken into acount as start address.

Why is it misleading? It tells the linker to which address it should relocate the program. If you think as "start address" the address, the program's loaded to, that's up to how you generate the exe file.

**Comment by Fabrizio-Caruso** [comment]
Thanks everyone for your help! I understand the linker a little bit more but there are still some remaining obscure parts.

**Comment by greg-king5** [comment]
The only thing that `DUMMY:` does is to pad the output file.  It isn't used by the program.  Therefore, its start address doesn't matter.  You can use `start = $0000`.

(That attribute is required because Uz didn't anticipate that we might use memory areas as _only_ padding.)

**Comment by Fabrizio-Caruso** [comment]
@groessler I am outputing the map file but I cannot see any information about the remaining available space in each memory area. Is there a way to know?

**Comment by groessler** [comment]
Look at the symbols for the memory areas, like `__MAIN_START__` and `__MAIN_LAST__`.
The "LAST" symbol points to the end of the memory area.

**Comment by greg-king5** [comment]
> Look at the symbols for the memory areas, like `__MAIN_START__` and `__MAIN_LAST__`.
> The "LAST" symbol points to the end of the memory area.

No.  Read [Other MEMORY area attributes](http://cc65.github.io/doc/ld65.html#ss5.5).
"`__MAIN_LAST__ - __MAIN_START__`" is the size of the `MAIN:` part that your program actually uses.
"`__MAIN_START__ + __MAIN_SIZE__  - __MAIN_LAST__`" is the size of what your program doesn't use.

**Comment by groessler** [comment]
Hmm, why "No"? What is wrong in my statement?

**Comment by greg-king5** [comment]
You wrote, 'The "LAST" symbol points to the end of the memory area.'
You didn't write, "... the end of the **_used_** memory area".
You didn't write, "... the end of the memory area **_that's occupied by the program_**".
