### ISSUE TITLE
[feature-request] command line option to dump search paths

### ISSUE THREAD

**Issue by bauen1** [cc65/cc65#563]
It would be nice to show the search paths the compiler and linker uses for debugging and scripting purposes.
Similiar to gcc's `-print-search-dirs` and `-print-file-name`

**Comment by oliverschmidt** [comment]
While I generally understand your perspective it should be noted that in contrast to gcc there's just one single built-in search path in cc65. All other search paths are provided by the user in one way or another.  That single built-in search path can easily be deducted from the output of `cl65 --print-target-path`. See http://cc65.github.io/doc/cl65.html#s2.
