### ISSUE TITLE
[help][linker][cfg][vic20] Loading UDG at $1C00 on a Vic20+3k

### ISSUE THREAD

**Issue by Fabrizio-Caruso** [cc65/cc65#578]
I am trying to load $400 of data (graphics) on a VIC20+3k at $1C00.
On such configuration, there is an expected overlap with ROM and video memory, which starts at $1E00.
So, I expect only a portion (64 chars = $100 bytes) of the graphics to be usable.
For some reason, I do not find the data at $1C00 when I use VICE monitor.

My config is not too different from the working one for other VIC20 configs:
```cfg
MEMORY {
    ZP:       file = "", define = yes, start = $0002, size = $001A;
    LOADADDR: file = %O,               start = $03FF, size = $0002;
    HEADER:   file = %O,               start = $0401, size = $000C;
    MAIN:     file = %O, define = yes, start = $040D, size = $1800 - __MAIN_START__ - __STACKSIZE__, fill = yes;
    DUMMY:    file = %O,               start = $1C00 - __STACKSIZE__ - 1, size = __STACKSIZE__, fill = yes;
    CHARMEM:  file = %O, start = $1C00, size = $0400, type = rw,  define = yes, fill = yes;
}
SEGMENTS {
...
    UDCCHAR:  load = CHARMEM,  type = ro, define = yes, optional = no;	
}
```

**Comment by oliverschmidt** [comment]
I suggest to not use an emulator monitor as primary way to test/debug a config file. Rather use the map file. Honestly, I personally never even think about loading a binary created with a new config file before having a close look at the map file to see if I got the config right and if the binary at least appears to be potentially correct.

**Comment by groessler** [comment]
@Fabrizio-Caruso, you know how CBM load files work?
They are just one binary blob which gets loaded to the load address. So it doesn't help if you put an address in the cfg file, it just tells the linker to resolve the program's addresses that they are correct for this address. So, unless you don't pad MAIN with "fill=yes" (which you have) until $1C00, DUMMY will be loaded just after main.

**Comment by Fabrizio-Caruso** [comment]
@groessler, indeed, that was my desperate and stupid attempt to get the UDG at $1C00.
I have tried without the fill=yes + dummy (for the stack) with the same result.
In any case, I do get the code at the right places: the game works but no graphics is loaded at $1C00.

**Comment by groessler** [comment]
Maybe include the graphics data into your program and just copy it to the correct location at program startup.

**Comment by Fabrizio-Caruso** [comment]
@groessler , that is what I want to avoid on such a memory-poor configuration.

**Comment by Fabrizio-Caruso** [comment]
I am starting to figure it out...
    ZP:       file = "", define = yes, start = $0002, size = $001A;
    LOADADDR: file = %O,               start = $03FF, size = $0002;
    HEADER:   file = %O,               start = $0401, size = $000C;
    MAIN:     file = %O, define = yes, start = $040D, size = $1C00 - $40D - __STACKSIZE__, fill=yes;
    DUMMY:    file = %O,               start = $1C00 - __STACKSIZE__ - 1, size = __STACKSIZE__, fill = yes;	
    CHARMEM:  file = %O, define = yes, start = $1C00, size = $0200, type = rw,  fill = yes;

seems better than what I had before.

**Comment by Fabrizio-Caruso** [comment]
Thanks everyone!
