### ISSUE TITLE
[supervision][info] How to display characters (or anything) on the screen?

### ISSUE THREAD

**Issue by Fabrizio-Caruso** [cc65/cc65#581]
Supervision comes with no TGI, nor conio support. Right?

How can I display characters or anything on the screen?

I found some structs on supervision.h that point to the lcd and the video but no comments on what they really mean.

How do I use SV_LCD?
defined in
```
struct __sv_lcd {
    unsigned char       width;
    unsigned char       height;
    unsigned char       xpos;
    unsigned char       ypos;
};
#define SV_LCD  ((struct __sv_lcd*)0x2000)
```
How do I use SV_VIDEO?
defined in
```
#define SV_VIDEO ((unsigned char*)0x4000)
```

**Comment by Fabrizio-Caruso** [comment]
If I try to compile a simple test example with
	$(CC65_PATH)$(MYCC65) -t supervision \
	$(SOURCE_PATH)/../experiments/supervision_test.c \
	-o $(BUILD_PATH)/supervision_test.bin
I get:

/cygdrive/c/cc65-snapshot-win32/bin/cl65.exe -t supervision \
src/../experiments/supervision_test.c \
-o build/supervision_test.bin
Unresolved external `__RAM_SIZE__' referenced in:
  supervision/crt0.s(34)
  supervision/crt0.s(35)
Unresolved external `__RAM_START__' referenced in:
  supervision/crt0.s(34)
  supervision/crt0.s(35)
ld65: Error: 2 unresolved external(s) found - cannot create output file
make: *** [Makefile:974: watara_test] Error 1

**Comment by oliverschmidt** [comment]
> `Unresolved external `__RAM_SIZE__' referenced in:`

> `Unresolved external `__RAM_START__' referenced in:`

This is clearly a bug. I've checked the history of the files in question and as far as I see it's "always" been there. 

I guess that replacing in https://github.com/cc65/cc65/blob/master/cfg/supervision.cfg#L11

`RAM:      file = "", start = $0200, size = $1E00 - __STACKSIZE__;`

with

`RAM:      file = "", start = $0200, size = $1E00 - __STACKSIZE__, define = yes;`

will solve the issue. Maybe you want to try and if it works I'll be willing to commit the change.

**Comment by Fabrizio-Caruso** [comment]
Indeed the line
```
    RAM:      file = "", start = $0200, size = $1E00 - __STACKSIZE__, define = yes;
```
fixes the error.
I don't know whether the code works.

**Comment by oliverschmidt** [comment]
Thanks for the feedback. Please let us know if you find out that the code does (seem to) actually work.

**Comment by Fabrizio-Caruso** [comment]
@oliverschmidt, if I write into the memory, which SV_VIDEO points to ($4000), I do see something on the screen.
Probably I can try to figure out how the pixel colors are encoded. 
This is pure reverse-engineering, though. 
It will be a length process.
Eventually I will have my universal game run even on this target.
I am crazy enough to support targets with no-compiler or partial compiler support. 
I am supporting more than 100 8-bit targets and use 6 cross compilers... (more to come)

**Comment by oliverschmidt** [comment]
> if I write into the memory, which SV_VIDEO points to ($4000), I do see something on the screen.

Thanks. I consider this enough evidence that the change in question is at least a improvement. I'll commit it shortly to all Supervision config files.

> Probably I can try to figure out how the pixel colors are encoded.
This is pure reverse-engineering, though.
It will be a length process.

While it's surely suboptimal to have cc65 targets with so limited support the alternative would be to have no support for them at all - which I presume would be considered worse.

**Comment by Fabrizio-Caruso** [comment]
@oliverschmidt, yes, little support is MUCH better than no support.
I don't complain. I am grateful for whatever we have. 

It would be nice to get some limited support for the BBC and Atari 7800 targets, as well as many others.
Just having a meaningful cfg and some pointers to access the chips would be a good starting point.

**Comment by oliverschmidt** [comment]
The bug is fixed with https://github.com/cc65/cc65/commit/38049d22ba54945e33d3b392fd4bb46b4b14773e.

**Comment by Fabrizio-Caruso** [comment]
Thanks @oliverschmidt !

**Comment by greg-king5** [comment]
e9cbd42b18510e0de5c7f6c563a6eed643db33ff fixes `<supervision.h>` so that you can access I/O registers in the same way that we access them on other targets.  That is, you would type `SV_LCD.width` instead of `SV_LCD->width`.

**Comment by Fabrizio-Caruso** [comment]
@greg-king5, I am not able to get anything shown on the screen. The supervision.h file contains no comments about the defined constants adn structures. Has anyone ever used this target and managed to display anything? I think I managed once (not sure anymore). I can't now, for sure.
