### ISSUE TITLE
[Supervision][joystick] inititq, joy_libref errors

### ISSUE THREAD

**Issue by Fabrizio-Caruso** [cc65/cc65#582]
When compiling my game for the Supervision target with joystick support I have
to explicitly include supervision.h not to get an error about undefined mask macros.
After forcing the include I still get the errors below:

```
Unresolved external `doneirq' referenced in:
  runtime/callirq.s(41)
Unresolved external `initirq' referenced in:
  runtime/callirq.s(40)
Unresolved external `joy_libref' referenced in:
  joystick/joy-kernel.s(60)
  joystick/joy-kernel.s(63)
ld65: Error: 3 unresolved external(s) found - cannot create output file
make: *** [Makefile:975: supervision_tiny] Error 1
```

**Comment by polluks** [comment]
Joystick support is not officially released, see documentation. Anyway conio is missing at all.

**Comment by Fabrizio-Caruso** [comment]
I am not using conio nor tgi (which I know are not available).
I will do barebones graphics by hitting on the video memory.

@polluks The documentation says that there is a jostick driver, which I ambtrying to use.

**Comment by oliverschmidt** [comment]
I'll take care of fixing the link errors.

**Comment by polluks** [comment]
@Fabrizio-Caruso I see, someone changed the documentation without testing.

**Comment by oliverschmidt** [comment]
With https://github.com/cc65/cc65/commit/27dacca4d38b54b7a44e9d0b1a7e4fc948c14df8 and https://github.com/cc65/cc65/commit/1976d6cd32f909babc5f6f26c9c068f47abb95bc the link errors should be fixed. Please test and report.

**Comment by oliverschmidt** [comment]
> When compiling my game for the Supervision target with joystick support I have
to explicitly include supervision.h not to get undefined mask macros.

That's the expected behavior.

**Comment by polluks** [comment]
@oliverschmidt No, see joy-test.c

**Comment by Fabrizio-Caruso** [comment]
Problem solved! Thanks anyone!

**Comment by oliverschmidt** [comment]
> No, see joy-test.c

@polluks: Now and then I'd prefer you were a bit more talkative ;-)

I guess you refer to my statement "That's the expected behavior.". But joy-test.c doesn't falsify my statement. Now we have target specific button masks so the target header file is necessary, isn't it?

If joy-test.c doesn't work anymore then __*it*__ needs to be adjusted, not my statement - or do I miss the point you want to make?

**Comment by polluks** [comment]
Please explain
`$ cl65 -tsupervision joy-test.c`
`joy-test.c(69): Error: Undefined symbol: 'JOY_UP_MASK'`
`joy-test.c(70): Error: Undefined symbol: 'JOY_DOWN_MASK'`
`joy-test.c(71): Error: Undefined symbol: 'JOY_LEFT_MASK'`
`joy-test.c(72): Error: Undefined symbol: 'JOY_RIGHT_MASK'`
`joy-test.c(73): Error: Undefined symbol: 'JOY_BTN_1_MASK'`

**Comment by oliverschmidt** [comment]
joy-test.c includes conio.h which includes the target header file which brings the button masks. supervision doesn't support conio, therefore conio.h doesn't include the supervision header. What does that mean?

* A program using the joystick but not conio needs to take care of including the target header on its own.
* joy-test.c actually uses conio so it can't work on the supervision anyway.

**Comment by polluks** [comment]
Thanks, I finally understand. Maybe funcref needs a hint.

**Comment by oliverschmidt** [comment]
> conio.h reads supervision.h but joystick.h reads no system specific files. Not very consistent.

Surely. I guess you'll like https://github.com/cc65/cc65/commit/d7afadb2fe62a2154ad5bcb949644da17e4ac7c6 ;-)

@Fabrizio-Caruso: The just built cc65 doesn't require the inclusion of supervision.h anymore.
