### ISSUE TITLE
unsigned long x = 1 << 30;

### ISSUE THREAD

**Issue by hpx1** [cc65/cc65#584]
Thanks for the great compiler

declaration		unsigned long x = 1 << 30;
generate message	Warning: Shift count too large for operand type
I can use		unsigned long x = 0x4000000;

It is not new issue, but it should be easy to correct.
Cheers Supaplex

**Comment by groessler** [comment]
Yes, ints are 16bit in cc65.
Use
`unsigned long x = 1ul << 30;`

**Comment by hpx1** [comment]
It's good to know that all constants are ints type
Cheers Supaplex
