### ISSUE TITLE
[creativision]The creativision target or its cfg seems broken (with example)

### ISSUE THREAD

**Issue by Fabrizio-Caruso** [cc65/cc65#589]
(Remark: The creativision target was working before)
Trying to compile a simple hello world example 
```
#include <stdio.h>
  int main()
  {
	printf("Hello world!\n");	
	while(1){};
    return 0;
  } 
```
produces the following error:
```
/cygdrive/c/cc65-snapshot-win32/bin/cl65.exe -O -t creativision \
src/../experiments/hello.c \
-o build/creativision_hello.bin
ld65: Warning: C:\cc65-snapshot-win32\cfg/creativision.cfg(6): Segment `BSS' overflows memory area `RAM' by 6 bytes
ld65: Error: Cannot generate most of the files due to memory area overflow
make: *** [Makefile:1690: creativision_hello] Error 1
```

**Comment by oliverschmidt** [comment]
As documented (http://cc65.github.io/doc/creativision.html) the unexpanded machine has only $206 bytes of RAM available to cc65 programs. So there are severe limits to what can be done.

Anyhow, https://github.com/cc65/cc65/commit/b65981fc3a0d4a7903c9b2800b03959c9f368b89 is supposed to be a significant improvement.

However, be prepare to have to customize the stacksize by re-defining a different value for `__STACKSIZE__` on the command line moving forward!
