### ISSUE TITLE
[PCE][function pointers](With isolated example) Crashes whenever pointers to functions are used.

### ISSUE THREAD

**Issue by Fabrizio-Caruso** [cc65/cc65#596]
My game crashes ONLY with the PCE target whenever in my code I call a function through a pointer to function.
I get different crash/freeze behavior depending on the size of the stack.
I have tried with stack size from 0x20 to 0x300.
The problem could be stack-related.
I will try to isolate this issue.
I use the standard cfg with cart size 16k and with different stack sizes:
```
SYMBOLS {
    __CARTSIZE__:  type = weak, value = $4000; # $2000, $4000, or $8000
    __STACKSIZE__: type = weak, value = $0300; # 3 pages stack
}
```
I compile and build my game with:
```
pce_16k:
	$(CC65_PATH)$(MYCC65) -O -t pce \
	-DFULL_GAME \
	-DEND_SCREEN -DBETWEEN_LEVEL \
	--config $(SOURCE_PATH)/../cfg/pce_16k_less_stack.cfg \
	$(SOURCE_PATH)/horizontal_missile.c $(SOURCE_PATH)/rocket.c \
	$(SOURCE_PATH)/item.c $(SOURCE_PATH)/end_screen.c \
	$(SOURCE_PATH)/display_macros.c \
	$(SOURCE_PATH)/enemy.c $(SOURCE_PATH)/invincible_enemy.c \
	$(SOURCE_PATH)/level.c $(SOURCE_PATH)/character.c $(SOURCE_PATH)/text.c \
	$(SOURCE_PATH)/missile.c $(SOURCE_PATH)/strategy.c \
	$(SOURCE_PATH)/input_macros.c $(SOURCE_PATH)/main.c \
	-o $(BUILD_PATH)/FULL_PCE.bin
	dd if=$(BUILD_PATH)/FULL_PCE.bin ibs=1 count=8192 of=$(BUILD_PATH)/FULL_PCE_LOW.bin
	dd if=$(BUILD_PATH)/FULL_PCE.bin ibs=1 skip=8192 of=$(BUILD_PATH)/FULL_PCE_HIGH.bin
	rm $(BUILD_PATH)/FULL_PCE.bin 
	cat $(BUILD_PATH)/FULL_PCE_HIGH.bin $(BUILD_PATH)/FULL_PCE_LOW.bin > $(BUILD_PATH)/FULL_PCE_SWAPPED.pce
	rm $(BUILD_PATH)/FULL_PCE_LOW.bin
	rm $(BUILD_PATH)/FULL_PCE_HIGH.bin	
```
(I know I am not using dd in the most efficient way but it is super fast anyway)

**Comment by Fabrizio-Caruso** [comment]
It seems PCE is broken. It is probably stack-related.

Even the following simple program will crash after some time:
```
#include <stdio.h>
#include <conio.h>
void hello(void)
{
	gotoxy(3,5);
	textcolor(COLOR_WHITE);
	cprintf("Hello world!\n");
}
struct objectStruct
{
	void (* foo) (void);
};
typedef struct objectStruct Object;
int main()
{
	Object obj;
	obj.foo = hello;
	obj.foo();
	while(1){};
	return 0;
}
```

Compiled with:
```
pointersToFunction:
	$(CC65_PATH)$(MYCC65) -t pce \
	$(SOURCE_PATH)/../experiments/pointerToFunction.c \
	-o $(BUILD_PATH)/pointersToFunctions.pce
```

**Comment by Fabrizio-Caruso** [comment]
I confirm that the problem existed before the recent change in PCE's cfg.

**Comment by Fabrizio-Caruso** [comment]
I can confirm that the issue is still present.

**Comment by Fabrizio-Caruso** [comment]
How can I re-open an issue?

The very simple test program still crashes.

I have seen the fix merged, so I thought the snapshot should contain it but the issue is still there.

**Comment by Fabrizio-Caruso** [comment]
The test program would show a flickering hello world (as if the program is continuously restarted?). It would eventually creash showing random characters on the screen.
My game simply hangs whenever the portion of the code with pointers to functions is entered.

**Comment by Fabrizio-Caruso** [comment]
@ALL, @oliverschmidt, @greg-king5 (sorry for double posting, I will only post here from now on)

The following example will prove that there is a problem: it displays just "world" and not "Hello"
```
#include <stdio.h>
#include <conio.h>

void hello(void)
{
	gotoxy(3,5);
	textcolor(COLOR_WHITE);
	cprintf("Hello\n");
}

struct objectStruct
{
	void (* foo) (void);
};

typedef struct objectStruct Object;



int main()
{
	Object obj;
	obj.foo = hello;
	obj.foo();
	gotoxy(3,7); cprintf("world!\n");
	while(1){};
	return 0;
}
```

**Comment by greg-king5** [comment]
I still don't see what you described.  I built your program with
```sh
$ cl65 --version
cl65.exe V2.17 - Git 8b3e12d
$ cl65 -t pce -o test-pce.pce test-pce.c
```
I ran the program in the Mednafen 0.9.48 emulator.  I saw ![test-pce-0000](https://user-images.githubusercontent.com/4145570/37403418-2d9278f6-2765-11e8-82a0-dad1aa6a2535.png)

Here is the compiled PCE image: 
[test-pce.zip](https://github.com/cc65/cc65/files/1813570/test-pce.zip)

**Comment by mrdudz** [comment]
different optimization options perhaps?

**Comment by Fabrizio-Caruso** [comment]
I am going to recheck with the latest version and the same emulator version

**Comment by Fabrizio-Caruso** [comment]
The problem seems now solved! I will test further but I close the issue for the moment.
Thanks everyone!
