### ISSUE TITLE
tgidrv_line.inc produces garbled lines.

### ISSUE THREAD

**Issue by SvenMichaelKlose** [cc65/cc65#610]
Found during port to VIC-20, also breaks C64 TGI.
![tgi_line_c64](https://user-images.githubusercontent.com/1219833/37254405-8eed7d46-253d-11e8-906a-cac5a6c3d80c.png)
![tgi_line_c64_generic](https://user-images.githubusercontent.com/1219833/37254406-8f12bd4a-253d-11e8-875d-80d4d1253e58.png)

**Comment by polluks** [comment]
Interesting, do you have any source code?

**Comment by SvenMichaelKlose** [comment]
Looks like the mail didn't make here, so here's a copy:

Kind of. The code is pretty easy to break.  Remove the LINE routine from libsrc/c64/tgi/c64-hi.s and add

.include "../../tgi/tgidrv_line.inc"

to the end of it.

The test code is just this:

```
#include "stdio.h"
#include "tgi.h"

extern const void tgi_static_stddrv[];

void
main ()
{
    tgi_install (&tgi_static_stddrv);
    tgi_init ();
    tgi_clear ();
    tgi_setcolor (1);
    tgi_circle (160, 100, 90);
} 
```

**Comment by oliverschmidt** [comment]
I built the program above for the C128 target - which uses a TGI driver leveraging tgidrv_line.inc by default. The output looks just fine - see below. Therefore I presume that tgidrv_line.inc was used "incorrectly" in one way or another. From that perspective it seems appropriate to close this issue. In case we merge the VIC20 TGI driver and see the issue there we'll tackle it there.

![image](https://user-images.githubusercontent.com/2664009/37679398-148342d4-2c81-11e8-8f32-fe8b763bc961.png)
