### ISSUE TITLE
[apple2/apple2enh] How to get a bootable disk with the new binary?

### ISSUE THREAD

**Issue by Fabrizio-Caruso** [cc65/cc65#618]
I have seen that the binary format has changed. I have tried to follow an example that was shown on the forum but it does not seem to cover my case.

I was previously building an auto-boot image with the my game inside it with:
```
apple2:	 
	$(CC65_PATH)$(MYCC65) -O -t apple2 -DFULL_GAME -DBETWEEN_LEVEL -DEND_SCREEN \
	...
	-o $(BUILD_PATH)/apple2.bin
	cp $(SOURCE_PATH)/../tools/MASTER_BOOT_ASCHASE.DSK $(BUILD_PATH)/FULL_apple2.dsk
	java -jar $(SOURCE_PATH)/../tools/ac.jar -cc65 $(BUILD_PATH)/FULL_apple2.dsk aschase B < $(BUILD_PATH)/apple2.bin
	rm $(BUILD_PATH)/apple2.bin
```
Replacing cc65 with -as and removing B produces something that, when loaded, just shows a screen with 
@@? characters.

How can I translate my build procedure into an equivalent one that expects the new binary format?

**Comment by oliverschmidt** [comment]
> How can I translate my build procedure into an equivalent one that expects the new binary format?

In theory you did everything right. I don't know where you actually go wrong.

What I did to analyze it:
* I downloaded https://github.com/Fabrizio-Caruso/CROSS-CHASE/releases/download/LotsOfFeatures/FULL_apple2.dsk. It's a DOS 3.3 disk as expected. It contains two files as expected.
* I removed the file ASCHASE.
* I built some small test porgram with `cl65 -O -t apple2 test.c -o apple.bin`.
* I added the result to FULL_apple2.dsk with `java -jar ac.jar -as FULL_apple2.dsk aschase < apple.bin`.

The result works just fine for me.

**Comment by Fabrizio-Caruso** [comment]
@oliverschmidt I am supposed to build the files with 
make apple2 and make apple2enh
Why delete ASCHASE? How can I do it (in my Makefile)? No need with the old binary.
One of the goals of my project is to make the Makefile do everything for me (building for more than 100 targets now...). So I would a solution that does not involve manual operations or a way to get the old binary format, which worked in a fully automatic fashion.

If I modify the above Makefile by replacing -cc65 with -as and by removing "B", i.e.,
```
	java -jar $(SOURCE_PATH)/../tools/ac.jar -cc65 $(BUILD_PATH)/FULL_apple2.dsk aschase B < $(BUILD_PATH)/apple2.bin
```
becomes
```
	java -jar $(SOURCE_PATH)/../tools/ac.jar -as $(BUILD_PATH)/FULL_apple2.dsk aschase < $(BUILD_PATH)/apple2.bin
```

I no longer get a working .dsk image.

**Comment by oliverschmidt** [comment]
> Why delete ASCHASE?

Because I didn't have your MASTER_BOOT_ASCHASE.DSK.

> No need with the old binary. One of the goals of my project is to make the Makefile do everything for me (building for more than 100 targets now...). So I would a solution that does not involve manual operations [...]

Sure. Because you do `cp $(SOURCE_PATH)/../tools/MASTER_BOOT_ASCHASE.DSK $(BUILD_PATH)/FULL_apple2.dsk` you have no need to remove a file. All this has nothing to do at all with the changed binary format!

> a way to get the old binary format, which worked in a fully automatic fashion.

The new binary format allows for a fully automatic process just as the old one. I understand that you don't like "unnecessary" changes "breaking" things on your side. However, I proofed to you in my last comment that things generally work - and you're not the only one using the stuff ;-)

**Comment by Fabrizio-Caruso** [comment]
You are right and I am wrong. Sorry for opening this stupid issue.
Maybe you are not exact onn just a minor detail: by cloning my repo, you should have MASTER_BOOT_ASCHASE.DSK at the right place (inside tools) but this is not relevant.

**Comment by Fabrizio-Caruso** [comment]
By the way, I am not against changes even if something maybe temporarily broken.

**Comment by oliverschmidt** [comment]
> by cloning my repo, you should have MASTER_BOOT_ASCHASE.DSK at the right place

Thanks for the hint. I somehow wasn't expecting it to be part of your repo.

**Comment by oliverschmidt** [comment]
> By the way, I am not against changes even if something may be temporarily broken.

:-)
