### ISSUE TITLE
getting a "range error" message for labels defined in .proc only

### ISSUE THREAD

**Issue by happyemi** [cc65/cc65#630]
I asked this question on stackoverflow as well, but this is probably a better place.

Given the following code:
```

.code

.proc test
loop:
    nop
    nop
    ...   ; Add around 300 nops in here
    nop
    cmp #0
    beq loop
    rts
.endproc
```

I get the following error when trying to build it:` test.s(323): Error: Range error (-321 not in [-128..127])`
line 323 is `beq loop`. It seems like my proc is too big (or the label is too far away from the `beq` instruction).

**Builds just fine if I get rid of `.proc` and `.endproc`**

Building line is: `cl65 -o test.prg -t c64 -C c64-asm.cfg -u __EXEHDR__ test.s`

Version is: `cl65 V2.17 - Git d869368`

**Comment by mrdudz** [comment]
that sounds odd, you should get that error no matter if there is proc/endproc or not

**Comment by groessler** [comment]
I'm getting a range error, regardless whether .proc/.endproc is present or not.
`cl65 V2.17 - Git 5fb55096`

**Comment by groessler** [comment]
Sorry, git hash is irrelevant since this was a local branch. But it's at the latest official git revision (305c6e7ae4f51a).

**Comment by happyemi** [comment]
Why should I get an error though? The address I jump to is an absolute 16 bit address, what's the reason?

**Comment by groessler** [comment]
Please learn 6502 assembly, sorry.

**Comment by happyemi** [comment]
ah relative addressing mode, got it. Sorry for asking :)

**Comment by groessler** [comment]
Ok, no problem. But back to your original question, can you give an example where the behavour (error/no error) is different if .proc is present?

**Comment by happyemi** [comment]
I'll retest my code this evening once I'm back from work.
If it helps, I'm using the windows version of the toolchain

**Comment by happyemi** [comment]
Ok, I can't reproduce it, I guess I got confused. Sorry about wasting your time guys, I'm closing this issue.
