### ISSUE TITLE
Compile wrong with -O -Cl

### ISSUE THREAD

**Issue by Ymhr6** [cc65/cc65#632]
This simple function loads a little-endian ushort from a buffer:
```C
unsigned short int load_le_ushort(unsigned char* buffer)
{
	unsigned short int aResult = buffer[1];
	aResult<<=8;
	aResult|=buffer[0];
	return aResult;
}
```
Compiling with latest cc65 v 2.17 with optimization and static locals gives me wrong assembler in the bit shift zone:
```asm
	lda     #$00
	sta     L0002+1
;
; aResult<<=8;
;
	sta     L0002
	sta     L0002+1
;
```
Clearly, this will build a 0 (zero) value, that is wrong.

This is the entire assembler function
```asm
; ---------------------------------------------------------------
; unsigned short __near__ load_le_ushort (__near__ unsigned char *)
; ---------------------------------------------------------------

.segment	"CODE"

.proc	_load_le_ushort: near

.segment	"BSS"

L0002:
	.res	2,$00

.segment	"CODE"

;
; {
;
	jsr     pushax
;
; unsigned short int aResult = buffer[1];
;
	jsr     ldax0sp
	sta     ptr1
	stx     ptr1+1
	ldy     #$01
	lda     (ptr1),y
	sta     L0002
	lda     #$00
	sta     L0002+1
;
; aResult<<=8;
;
	sta     L0002
	sta     L0002+1
;
; aResult|=buffer[0];
;
	jsr     push0
	ldy     #$03
	jsr     ldaxysp
	sta     ptr1
	stx     ptr1+1
	ldx     #$00
	lda     (ptr1,x)
	jsr     tosora0
	sta     L0002
	stx     L0002+1
;
; }
;
	jmp     incsp2

.endproc
```

**Comment by Ymhr6** [comment]
For a right compilation need option --disable-opt OptStore5

OptStore5 says:
/* Search for the sequence
**
**      lda     foo
**      ldx     bar
**      sta     something
**      stx     something-else
**
** and replace it by
**
**      lda     foo
**      sta     something
**      lda     bar
**      sta     something-else
**
** if X is not used later. This replacement doesn't save any cycles or bytes,
** but it keeps the value of X, which may be reused later.
*/

I'd say "if A is not used later".
After optimization, A contains bar, not foo!

**Comment by mrdudz** [comment]
A _and_ X :)

**Comment by spiro-trikaliotis** [comment]
It could change the order, couldn't it?

lda bar
sta something-else
lda foo
sta something

Then, A contains the expected value.

**Comment by greg-king5** [comment]
Hmm, maybe the words "new" and "old" are missing from that description:

** if the _new_ X is not used later. This replacement doesn't save any cycles or bytes,
** but it keeps the _old_ value of X, which may be reused later.

**Comment by greg-king5** [comment]
Hmm, maybe the words "new" and "old" are missing from that description:

** if the _new_ X is not used later. This replacement doesn't save any cycles or bytes,
** but it keeps the _old_ value of X, which may be reused later.

**Comment by greg-king5** [comment]
I confess that I wouldn't have suspected `OptStore5()`.
> It could change the order, couldn't it?

That change works:
```asm
; ---------------------------------------------------------------
; unsigned short __near__ load_le_ushort (unsigned char *)
; ---------------------------------------------------------------

.segment        "CODE"
.proc   _load_le_ushort: near

.segment        "BSS"
L0002:
        .res    2,$00

.segment        "CODE"
;
; {
;
        jsr     pushax
;
; unsigned short int aResult = buffer[1];
;
        jsr     ldax0sp
        sta     ptr1
        stx     ptr1+1
        ldy     #$01
        lda     #$00
        sta     L0002+1
        lda     (ptr1),y
        sta     L0002
;
; aResult <<= 8;
;
        tax
        lda     #$00
        sta     L0002
        stx     L0002+1
;
; aResult |= buffer[0];
;
        jsr     pushax
        ldy     #$03
        jsr     ldaxysp
        sta     ptr1
        stx     ptr1+1
        ldx     #$00
        lda     (ptr1,x)
        jsr     tosora0
        sta     L0002
        stx     L0002+1
;
; }
;
        jmp     incsp2
.endproc
```
(Now, I must write a regression test for that bug.)

**Comment by Ymhr6** [comment]
I'm also looking at the first two lines of the function:

jsr pushax
jsr ldax0sp

I think that the load is not necessary.
The value that is loaded in ax is the value just pushed.

Is correct?

**Comment by greg-king5** [comment]
> ```asm
> jsr pushax
> jsr ldax0sp
> ```
>
> I think that the load is not necessary.
> The value that is loaded in ax is the value just pushed.

Yes.  It is common in fastcall functions.  The first expression in the function immediately uses the last function parameter.  But, I don't know if they are put into the same "code segment"; `"jsr pushax"` is generated by the "prototype", while `"jsr ldax0sp"` is generated by the function body.  The optimizer might not be able to see that pattern.

**Comment by Ymhr6** [comment]
I'm looking also at the last three lines of the function: as we have the return value in ax, storing it in L0002 just before returning is not necessary.

**Comment by Marrin** [comment]
@Ymhr6 I don't think the compiler distinguishes between real static locals and those created by the `-Cl` switch, so it is ”necessary” to store the value in the static local variable.

**Comment by Ymhr6** [comment]
@Marrin, I don't think it's a matter of static locals. Compiling without -Cl give a similar pattern: the value in ax is stored on the stack, and the next line the stack is incremented!

jsr     tosora0
jsr     stax0sp
jmp     incsp4

This pattern, with the initial load after the push, and with a bad bit shift with not necessary store, and not counting the bug, give me not enthusiastic about it; this is a very simple 4 lines c function!

I found also another bug (in the compiler, not the optimizer), but I'm futher investigating and I will open a new issue about it.

**Comment by oliverschmidt** [comment]
@Ymhr6: Thanks for the detailed analysis :-)

@greg-king5: Thanks - as always - for the fix!
