### ISSUE TITLE
[info][feature request] cc65 snapshot download (sourceforge broken?) + prev vers for regressions

### ISSUE THREAD

**Issue by Fabrizio-Caruso** [cc65/cc65#635]
cc65 snapshot download in sourceforge seems not to work today
(tried on a pc with 2 browsers and on my smartphone)

By the way, it would be useful to keep some previous snapshots (one per month or week or day) to allow people to easily check regressions.

**Comment by oliverschmidt** [comment]
> cc65 snapshot download in sourceforge seems not to work today

Works like a charm over here...

> it would be useful to keep some previous snapshots (one per month or week or day) to allow people to easily check regressions

cc65 is built at pretty unregular intervals. Having versions around between the current HEAD and the releases doesn't seem worth the (manual) effort to me.

**Comment by Fabrizio-Caruso** [comment]
@oliverschmidt, for sure no manual action should be ever necessary to handle a couple of previous snapshots. The goal would be easy regression testing. 
Even keeping just the last previous snapshot (or just 2 or 3) could help a lot in figure it out quickly when and what was broken that used to work.
