### ISSUE TITLE
Have RUN/STOP + RESTORE call exit()

### ISSUE THREAD

**Issue by oliverschmidt** [cc65/cc65#650]
On the Apple II the cc65 startup code makes CTRL + RESET call exit(). See https://github.com/cc65/cc65/blob/master/libsrc/apple2/crt0.s for how it avoids re-entrance.

It seems desirable to have on CBM machines RUN/STOP + RESTORE work in the same way. Especially as the CBM C Library contains a destructor to close all open files (just like the Apple II C Library does).

**Comment by mrdudz** [comment]
Just stumbled about this... i wonder what the intend is. Usually runstop+restore "force exits" a basic program, in most ml programs it will do nothing (and in those that use NMI for something it will often cause a crash). Incase the respective pointer stays intact in low mem, it will even "close all files" (and do a general i/o reset) so there is nothing left to do as far as i can see.

**Comment by polluks** [comment]
A SIGKILL should be generated =)

**Comment by oliverschmidt** [comment]
As everybody knows, I'm no CBM insider. I understand that cc65 programs in general want to behave like BASIC programs. So from my perspective it seems totally normal to have that key combo "force exit" a cc65 just in the same way it "force exits" a BASIC program. And for that purpose calling exit() seems the totally normal approach. It doesn't matter too much if there are any built-in exit handlers in the C library which need to be called because the user can at any point use atexit() to add his own handlers, which should to be called.

**Comment by mrdudz** [comment]
> It doesn't matter too much if there are any built-in exit handlers in the C library which need to be called because the user can at any point use atexit() to add his own handlers, which should to be called.

OK - so we want runstop/restore call the atexit handlers, and then exit - and not just "force exit" like it would happen with a basic program (which really is a hard abort, more like what a segfault would do in a modern OS).

I am not sure this can be implemented in a 100% safe way though... the RESTORE key has quite some hardware bounce so the nmi triggering two or more times in a short time is to be expected (sometimes), which might screw up the exit code.

Other than that it should be trivial to implement, in the same way as in that apple2 code, just using the 0138/9 vector and doing a similar check for the runstop key as the ROM does: http://unusedino.de/ec64/technical/aay/c64/romfe43.htm

**Comment by oliverschmidt** [comment]
> OK - so we want runstop/restore call the atexit handlers, and then exit - and not just "force exit" like it would happen with a basic program (which really is a hard abort, more like what a segfault would do in a modern OS).

I see, I misinterpreted what you mean with "force exit". But now we're on the same page :-)

> the RESTORE key has quite some hardware bounce so the nmi triggering two or more times in a short time is to be expected (sometimes), which might screw up the exit code.

I sort of see. I guess the best thing to do is the same that is done on the Apple II: The very first thing the handler does is setting the vector from `_exit` to `exit` in order to minimize the risk of re-entering `_exit`.

**Comment by dmsc** [comment]
Hi!

At least in the Atari, handling the BREAK key in the interrupt handler is bad because you can interrupt I/O and mess with OS buffers, so what the OS does is set a flag that I/O (and the basic interpreter) checks to properly exit.

This is not easy to do in CC65, but perhaps the NMI could overwrite some I/O functions (like "putchar" and "setcursor") with a jump to exit - so next time your program does screen I/O it will terminate properly.

**Comment by mrdudz** [comment]
> but perhaps the NMI could overwrite some I/O functions (like "putchar" and "setcursor") with a jump to exit - so next time your program does screen I/O it will terminate properly.

That just doesnt work in a generic way - you never know what functions a program will actually use - it must always work without crazy hacks like this.

**Comment by oliverschmidt** [comment]
Please see discussion at https://github.com/cc65/cc65/pull/1515.
