### ISSUE TITLE
Binaries are now a bigger by a few bytes

### ISSUE THREAD

**Issue by Fabrizio-Caruso** [cc65/cc65#661]
Binaries are now a bigger by a few bytes (e.g., about 16 in my case) compared to previous versions.

Is this an expected behavior?

It is not a big deal, I know. I will have to cut a few bytes somewhere in my game to get it to work with the new snapshot.

I am compiling with:
```
	$(CC65_PATH)$(MYCC65) -O -Cl -t vic20
```

**Comment by Fabrizio-Caruso** [comment]
A problematic case for me is:
```
vic20_unexpanded: 
	$(CC65_PATH)$(MYCC65) -O -Cl -t vic20 \
	-DVIC20_UNEXPANDED \
	-DNO_PRINT \
	-DALT_PRINT \
	-DNO_SLEEP \
	-DLESS_TEXT \
	-DNO_SET_SCREEN_COLORS \
	-DTINY_GAME \
	-DNO_RANDOM_LEVEL \
	-DFORCE_KEYBOARD \
	-DNO_MESSAGE \
	-DNO_STATS \
	-DNO_INITIAL_SCREEN \
	-DFORCE_GHOSTS_NUMBER=8 \
	-DALT_DISPLAY_STATS \
	-DNO_DEAD_GHOSTS \
	-DALT_HIGHSCORE \
	-DFORCE_BOMBS_NUMBER=4 \
	--config $(SOURCE_PATH)/../cfg/vic20_unexpanded.cfg  \
	$(SOURCE_PATH)/display_macros.c $(SOURCE_PATH)/vic20/vic20_unexpanded.c \
	$(SOURCE_PATH)/enemy.c  $(SOURCE_PATH)/level.c $(SOURCE_PATH)/character.c $(SOURCE_PATH)/text.c \
	$(SOURCE_PATH)/strategy.c $(SOURCE_PATH)/input_macros.c \
	$(SOURCE_PATH)/main.c \
	-o $(BUILD_PATH)/TINY_vic20_unexpanded.prg	
```

**Comment by groessler** [comment]
> Binaries are now a bigger by a few bytes (e.g., about 16 in my case) compared to previous versions

Such a report should include the/a cc65 version you refer to with "previous versions".

**Comment by Fabrizio-Caruso** [comment]
@groessler is there a file in the snapshot directory that contains the version?
Locally I have both versions.
If the last couple of snapshots were available for download, I could easily tell.
I made a request to keep a couple of previous snapshots for cases such as this.

**Comment by groessler** [comment]
run `cc65 -V`

**Comment by oliverschmidt** [comment]
> Locally I have both versions.

Then you can tell what you have - see comment above.

> If the last couple of snapshots were available for download, I could easily tell.

Please elaborate where the difference would be - I can't follow you.

> I made a request to keep a couple of previous snapshots for cases such as this.

That isn't relevant at all.

**Comment by Fabrizio-Caruso** [comment]
previous cc65.exe V2.17 - Git 334e30c 
saves about 16 bytes compared to 
recent cc65.exe V2.17 - Git 746e3d1

**Comment by Fabrizio-Caruso** [comment]
@oliverschmidt in my humble opinion, just keeping a couple of recent snapshots would speed up non-regs checks when I suspect something is broken/bigger/slower.
Of course one can always rebuild at any point but this is a lengthy procedure that could be avoided in some cases.

**Comment by Fabrizio-Caruso** [comment]
@oliverschmidt let us say, now, I want to quickly know which snapshots starts making the binary bigger, I could easily download the last 2 or 3 previous snapshots and I could tell you exactly which snapshot is the culprit. I know the problem is recent but I don't know which snapshot has introduce the issue.

**Comment by oliverschmidt** [comment]
https://github.com/cc65/cc65/compare/334e30c40742027a942c7b2c9c6e39f548e21c57...746e3d1454c1d59ad9df69bc99d236900de6655b

**Comment by IrgendwerA8** [comment]
Depending on the usage of libraries the size change is expected. I've added a function ("popptr1") which will save some bytes when used by several functions but needs some if in use below 4 times.

**Comment by groessler** [comment]
@Fabrizio-Caruso: it could help if you create map files with both versions and compare what has changed.

**Comment by oliverschmidt** [comment]
And that map file would tell us if it's "just" about the binary or if it's about in-memory-size too.

**Comment by Fabrizio-Caruso** [comment]
Could you guys please tell exactly which command and options I should use?

**Comment by IrgendwerA8** [comment]
Another change: Multiplication makes use of the negation function now. Both together are several bytes smaller, but if you're using only the multiplication size is a bit increased then.

**Comment by groessler** [comment]
@Fabrizio-Caruso: add `-m filename.map -Wl -vm`to `cl65` command line

**Comment by Fabrizio-Caruso** [comment]
@IrgendwerA8 I am getting bigger binaries on the 3 different versions of my game ("universal" game) on different targets (Vic20, C16). The 3 different versions are different in size. The largest most probably performs more arithmetic operations than the smallest one. I am using unsigned types.

**Comment by oliverschmidt** [comment]
- mul.s + 2 bytes
- popptr1.s + 14 bytes (new file)

**Comment by groessler** [comment]
Looks like both the mul change and the popptr1 change are the reason. popptr1 is included because it's reference from mul and mul8.

**Comment by Fabrizio-Caruso** [comment]
@oliverschmidt do these changes bring some improvement in size/speed in other cases?

**Comment by groessler** [comment]
@oliverschmidt, why did you close the issue? Do we agree that this example is a corner case? I have no opinion on that, since I hadn't/haven't time to look at the changes.

**Comment by IrgendwerA8** [comment]
* popptr1 is faster than popsreg since accu is not stored and restored, it also helps to save at least 4 bytes for some library functions (and is useful for own written asm ones too)
* popptr1 woudn't be part of the executable if it wasn't in use (e.g. by multiplication)

**Comment by Fabrizio-Caruso** [comment]
@IrgendwerA8 is popptr1 included when multiplication by a constant (non-power of 2) is used?

**Comment by IrgendwerA8** [comment]
If the statement leads to a multiplication call, yes.
But if you have a little bit of patience: Applying the popprt1 change to umod and udiv is on my agenda too, this would makes popsreg superfluous in your case and will free the additional bytes again...

**Comment by Fabrizio-Caruso** [comment]
@IrgendwerA8 thanks! I am not in hurry. My "universal" game has been in development for about one year...
Concerning the multiplication and division of a non-constant by a (non-power-of-two) constant, I wonder whether a call to multiplication or division is the best solution in terms of speed and/or size.

**Comment by oliverschmidt** [comment]
> why did you close the issue?

You wrote:

> Is this an expected behavior?

Therefore I classified this issue as a question. And with...

> Depending on the usage of libraries the size change is expected. I've added a function ("popptr1") which will save some bytes when used by several functions but needs some if in use below 4 times.

...together with...

> Looks like both the mul change and the popptr1 change are the reason. popptr1 is included because it's reference from mul and mul8.

...it seemed to me that your question was answered with `yes`. Sorry if that wasn't clear.

**Comment by Fabrizio-Caruso** [comment]
@oliverschmidt everything's clear. Thanks guys!

**Comment by Fabrizio-Caruso** [comment]
@IrgendwerA8, just one extra byte compared to the old routine.
ca65.exe V2.17 - Git 95223be (today's version): 3300 bytes

recent cc65.exe V2.17 - Git 746e3d1: maybe 3299+16 bytes

ca65.exe V2.17 - Git 334e30c: 3299 bytes
ca65.exe V2.17 - Git 8886e6f: 3299 bytes

**Comment by Fabrizio-Caruso** [comment]
@IrgendwerA8 
On a different example I get 3 extra bytes compared to a previous version:
ca65.exe V2.17 - Git 95223be (today's version):  17844
ca65.exe V2.17 - Git 8886e6f: 17841

Example taken from my project and built by:
make vic20_exp_16k

**Comment by Fabrizio-Caruso** [comment]
@IrgendwerA8 I guess the reason of your change is not an improvement in space but an improvement in speed. With the latest pull request with my cases, the increase is just a couple of bytes.
Do you expect cases in which your routine makes the binary smaller than previous versions?

**Comment by Fabrizio-Caruso** [comment]
@IrgendwerA8 nice! I confirm that with the C16 compile I also get a 3-byte increase.
So, the increase is not target dependent:
1 byte for the TINY version of my game 
3 bytes for the FULL version of my game that must be using one or two extra math operations somewhere.
Even if single bytes count, 3 bytes for a 12k binary and 1 byte for a 3k are not significant.
16 bytes in a 3k binary generated by a very memory-tight code, was a bit annoying.

**Comment by IrgendwerA8** [comment]
Have a look at my latest pull request... (so your next version should be size-wise again "on-par")

**Comment by IrgendwerA8** [comment]
For your C16 and full version I need to do another inspection. I guess not today...

**Comment by IrgendwerA8** [comment]
Full and tiny C16 and tiny VIC 20 should work now. No idea when I have time to have another look for full VIC 20.

**Comment by oliverschmidt** [comment]
Thanks for your effort :-)

**Comment by IrgendwerA8** [comment]
The savings are target depending: 3 bytes for C16, 2 for VIC 20.

**Comment by Fabrizio-Caruso** [comment]
I thought you were optimizing the math routines.
Then I will check all other CC65 targets (my game is compiled for all CC65, Z88DK and CMOC targets with just a couple of exceptions).

**Comment by IrgendwerA8** [comment]
I _was_ optimizing math routines. I thought you have this size problem only for the mentioned targets, so I reduced size in library code of those.
Reducing the size of the math function is a different, more sophisticated story as these are already quite well written. While cc65 is still developed, size changes - also increases - are very likely...
