### ISSUE TITLE
Need blitting for custom text output in TGI for PLATOTerm.

### ISSUE THREAD

**Issue by tschak909** [cc65/cc65#664]
I need much faster text output, that takes the 6x5 font data in the character set, and transfers it to the display, but with transfer modes:

* Rewrite, black background, white foreground
* Inverse, white background, black foreground
* Erase, transparent background, black background
* Write, transparent background, white background

I can of course figure this all out on my own, and spend months doing so...would really like some help. 

-Thom

**Comment by mrdudz** [comment]
6x5 is going to be sloooow :) wouldnt 8x4 do the trick?

**Comment by oliverschmidt** [comment]
> [...] 6x5 font [...]

Isn't that dependent on the available screen resolution? Likely you're talking about the C64's 320x200, right? The only thing I can add to this is a hint to the existing soft80 CONIO library for the C64.

**Comment by tschak909** [comment]
it's 6x5 because the output of text aligned on character cells is 64 characters by 32 lines, BUT, text can be placed at any point on the PLATO screen, so you can't rely on this.

Do not treat this as a text terminal. It is a graphical terminal that can display text.

**Comment by oliverschmidt** [comment]
Maybe preshifted shapes for all chars for all in-byte-positions?

**Comment by tschak909** [comment]
https://github.com/jduerstock/tlp/blob/master/tlp.asm#L3826 <-- the draw_char from the original Atari PLATO cartridge.

**Comment by tschak909** [comment]
also https://github.com/jduerstock/tlp/blob/master/tlp.asm#L4250

**Comment by groessler** [comment]
Does this mean that the PLATO protocol implementation is working now?

If not, I'm suggesting to first get everything to work, and only then think about optimzations.

**Comment by tschak909** [comment]
That was my plan, 

but, I may have to side-step to just doing an ip65 implementation, because I am literally seeing the slow text output affect the incoming serial data.

-Thom

**Comment by mrdudz** [comment]
that shouldnt be a problem if the interface supports rts/cts (i wouldnt rely on emulation for this =P)

**Comment by groessler** [comment]
Hmm. Additionally, if you could get a Swiftlink version to work, this might not be a problem. I think it's interrupt based.

**Comment by tschak909** [comment]
PLATO does XON/XOFF flow control at the server. I have temporarily turned it off, so that I can deal with some of the low level protocol issues.

Normally, The way XON/XOFF is implemented is to have the network data come in asynchronously into a ring buffer, and when that ring buffer gets close to filling up, send an XOFF to the host, and do XON when the buffer is sufficiently drained.

But am not sure how to implement this here under CC65, no threads...so I have it turned off for now.

**Comment by tschak909** [comment]
I tried to use the swiftlink driver, but i can't get it to work under any circumstance with VICE. However, I know the swiftlink emulation works under vice, because CCGMS and StrikeTerm can both use it.

(Basically, the ser_open fails with error 8)

-Thom

**Comment by groessler** [comment]
I've looked at the Swiftlink driver source code, and the only place where this error is returned is if "handshake" is not set to SER_HS_HW.

**Comment by tschak909** [comment]
ok.

**Comment by tschak909** [comment]
was able to get it to work by setting ACIA IRQ to NMI, and specifying HW handshake...

Driver will talk to tcpser and connect, however, shortly after seeing the banner, I get a CPU JAM...

-Thom

**Comment by groessler** [comment]
Can you share your version?

**Comment by tschak909** [comment]
This version has the swlink driver statically built in.
[plato-swlink.zip](https://github.com/cc65/cc65/files/2040238/plato-swlink.zip)

**Comment by groessler** [comment]
Sorry, I meant source code.

**Comment by tschak909** [comment]
[platoterm64-swlink.zip](https://github.com/cc65/cc65/files/2040300/platoterm64-swlink.zip)

**Comment by groessler** [comment]
Doesn't work for me. I'm not getting any input ot output on the serial channel.  Here my settings:

![vice-rs232](https://user-images.githubusercontent.com/4138182/40568365-823c02b6-607a-11e8-860a-92ee6fddd79f.png)

**Comment by groessler** [comment]
Strange thing is that "nc" is not being started. Didn't saw one while running the program.

**Comment by groessler** [comment]
Tried your binary (plato-swlink.zip), the same. Did I already say that I don't like VICE... :-)

**Comment by Fabrizio-Caruso** [comment]
Ideally, generic software sprite APIs would be cool.
Even better if the APIs were the same as the ones used in Z88DK.
Software sprites are slow but they are cross-platform.

**Comment by greg-king5** [comment]
@groessler, you don't need to go through netcat.  You can connect Serial 1 directly to tcpser.  You must not click its "Browse" button (that's for physical devices, not networks)!  You must type the IP address manually.

Click in its text box.  Delete the "/dev/ttyS0".  Type:
ip4://127.0.0.1:25232
Tell the ACIA to use Device "Serial 1".

**Comment by greg-king5** [comment]
Speed isn't a problem; patience is your problem.  You can slow down the bit-rate.  You even can get a really retro retro feeling by choosing the 300 BPS rate that we had when the BBS craze began. :smiling_imp:

**Comment by groessler** [comment]
@greg-king5: This appears to be a reasonable method. No netcat needed. Is this documented somewhere and I just haven't found it?

@tschak909: Trying your source, compiled with latest cc65 as of today, I'm not getting anything. Typing ATDTetc doesn't show up on the screen and also tcpser's debug mode doesn't report any incoming data. Here are my settings:

![vice-rs232-2](https://user-images.githubusercontent.com/4138182/40874461-ca902556-666f-11e8-868a-69007b3351da.png)

What am I missing again right now? :-(

**Comment by tschak909** [comment]
Use base address $DE00.

-Thom

**Comment by spiro-trikaliotis** [comment]
@groessler, it seems I forgot to document it when I introduced this back then.

**Comment by groessler** [comment]
@spiro-trikaliotis: Would be good to have it documented. While browsing for a solution I found quite a few people with the same problem on Linux/Unix. That's how I came up with the "netcat" solution. It seems that nobody knows about this feature (to specifiy a net peer with ip4://xxxx).

@tschak909: Ah, ok, I'm getting "something" with port set to $DE00. But, probably best asked to lurking VICE devs, my VICE crashes now: I've tried both 3.2 (officail tarball) and latest SVN version. When I type something in Plato, VICE aborts with 
`...
reSID: MOS8580, filter on, sampling rate 44100Hz - resampling, pass to 19845Hz
RS232NET: rs232net_open(device=0).
RS232NET: Output ''.
archdep_unix.c:421: error: function archdep_signals_pipe_set() is not implemented yet, exiting

Exiting...
`

**Comment by mrdudz** [comment]
don't use the experimental GTK3 port :)

**Comment by groessler** [comment]
I've used this "configure" command: `./configure --prefix=/data/home/chris/tmp/vice-svn-bin --enable-native-gtk3ui --enable-ethernet --enable-cpuhistory --enable-debug`

So I should try w/o GTK3?

**Comment by spiro-trikaliotis** [comment]
@groessler , I just looked at the sources: ip6:// should work, also, if IPv6 is available.
Additionally, if you do not specify anything, it will guess and assume it is an IPv6 address.

Thus, the following should all work:
ip4://192.168.0.1:1234
192.168.0.1:1234

You should also be able to specify a with a pipe symbol (e.g. "|unixsocket") a unix domain socket for local communication.

In fact, that ip4:// prefix is used in samples in the documentation, when the MonitorServerAddress and when the IDE64USBServerAddress is specified.

Regarding the documentation of the feature, ask the current members of VICE to do it. ;)

**Comment by groessler** [comment]
Unfortunately, when I try the SDL or SDL2 versions, the keyboard emulation doesn't seem to be right. I cannot get to the '"' to load the program.

**Comment by Compyx** [comment]
VICE will default to a symbolic keymap, so the '"' should be the '"' on your keyboard. If you use a positional keymap, the '"' will be above the '2', like on the real machine. In SDL you can change the keymap settings in the menu under "Settings management", there you can switch the keymap with the "Active keymap" item.

**Comment by groessler** [comment]
> In SDL you can change the keymap settings in the menu

That's already my first problem. I don't know how to get to the menu in the SDL version. All I get is just the C64 screen. Haven't found a key or mouse operation to get to a menu...

**Comment by Compyx** [comment]
On Linux/Windows it will be 'F12', on same Macs it could be F10/Fn+F10 or something. Doesn't title bar say something like "Press F12 for menu"? It does on my Linux box.

**Comment by groessler** [comment]
People who can read have an advantage... :-)

Yes, there is written "Press F12 for menu", and it works.

But then, why I try to set the keymap to "positional", I'm getting a crash when I try to leave the keymap menu (either by typing ESC or F12):

`Keyboard: Loading keymap ``/data/home/chris/tmp/vice-svn-bin/lib64/vice/C64/sdl_pos.vkm'.
uimenu.c:567: Error: lib_debug_guard_remove(): Cannot find debug address 0x84acc20! (make sure to use functions from lib.h, do NOT use lib_free on pointers allocated by other functions.)
Segmentation fault (core dumped)
`

This is with svn version of VICE as of today.

**Comment by Compyx** [comment]
Looks like I was a little too enthusiastic trying to fix a leak in the SDL menu code. Try an svn up and run make again.

**Comment by groessler** [comment]
> I don't know how long the C64 tgi driver disables interrupts. Maybe too long, and the program gets garbeld input. I will try to remove SEI/CLI from the C64 tgi driver, and install an IRQ trampoline as it's done with the NMI.

Forgot that the ACIA emulation is set to use NMI. So disabled IRQs for too long don't seem to be the problem....

**Comment by mrdudz** [comment]
>     couldn't select a host dir as virtual drive 8 in the SDL menu. Got it to work by copying over the setting from the GTK vicerc.
you have to enable virtual device traps first, just like in the GTK version. copying over an older config - even from a different port - is a BAD idea.

>     Keyboard still strange. For example I couldn't enter ":" thru the keyboard. I could then enter it with the virtual keyboard setting (or how it was called). I've got a German kb layout, and the öäü keys don't give any input.)

it works just fine, i am willing to bet your config is screwed up. run with -default and then save config again. and do "make install" first, just running it from the build dir wont work either :)

**Comment by groessler** [comment]
> you have to enable virtual device traps first, just like in the GTK version.

Hmm. First I didn't find that. But it seems that I need to set drive 8 "type" to "directory" first. Then I can select a dir as a virtual drive.

> it works just fine, i am willing to bet your config is screwed up. run with -default and then save config again. and do "make install" first, just running it from the build dir wont work either :)

Tried this, and got it to work. Previously I had overlooked another setting, "Keyboard mapping". It was not set to German. With "German" it works as expected. As I said, people who can read....

Thanks. And sorry for the newbie questions, I'm using VICE just some very few times a year, when I have to test something.

One last point: Sometimes pressing ESC in the menu leaves the menu altogether, sometimes it goes one up in the menu hierarchy. I haven't found a pattern for that. I think it depends on the menu entry you're in. Is this an inconsisteny, or am I missing someting again?

**Comment by mrdudz** [comment]
i think ESC works to exit requesters/message boxes and textentry fields....

anyway, you might want to use the vice ml for these questions =)

**Comment by greg-king5** [comment]
@groessler, which Git branch of platoterm64 are you testing?  The master branch uses 2400 BPS.  But, in the more recent "protocol_debugging" branch, Tom boosted the bit rate to 19200 BPS!  You might need to set tcpser to the speed that plato.c64 is using.

**Comment by mrdudz** [comment]
19200? with a standard userport rs232? >_<

**Comment by greg-king5** [comment]
> 19200? with a standard userport rs232? >_<

With a Swiftlink.

**Comment by tschak909** [comment]
Yes, I've switched to ACIA serial usage in master. It runs a lot better. The text output is nowhere near fast enough, but will deal with that later, after things are working.

After two weeks of trying to debug strange protocol decoding errors, I've decided to take a known good PLATO protocol decoder (pad.c from the MacPAD source code on the IRATA website), and graft that into my code, replacing protocol.c. I am in the middle of doing all the major changes needed for that to work, and won't push up until I know this approach will work.

-Thom

**Comment by groessler** [comment]
> which Git branch of platoterm64 are you testing?

I tested the version in the zip file posted here.

**Comment by tschak909** [comment]
The latest build in protocol_debugging compiles and runs, but has a lot of weird parsing errors coming back, that I haven't been able to reconcile.

So I'm in the middle of ripping out protocol.c and replacing it with one from the PAD source code that is on the IRATA website.

-Thom

**Comment by tschak909** [comment]
I have now folded in the protocol decoder based on the original PAD emulator, and the results look a lot better now, if anyone wants to mess about.

Currently, I am seeing some odd runs of 0x7f characters, and sometimes the Y coordinate decoding is off, but... :)

-Thom

**Comment by tschak909** [comment]
Text output is fully implemented, with all modes, and mode selection is honored in line, dot, and erase, so the output routines are now usable.

They're just slow. ;)

now onto implementing the PLATO keyboard.
``
<img width="1920" alt="c64-working-better" src="https://user-images.githubusercontent.com/2759782/41187805-fb6aa0b8-6b77-11e8-97a4-a203b172da31.PNG">

**Comment by oliverschmidt** [comment]
Thanks for sharing the video.

I must admit that I imagined the text output being much slower from both your reports and the fact that it is composed totally in C from tgi_setpixel() calls.

Takling about speed...

Looking at the amount of local variables in your CharDraw() function (https://github.com/tschak909/platoterm64/blob/master/src/plato.c#L294) I could imagine that the perfomance would benefit noticeably from using `--static-locals`. Please read about the option in the cc65 docs. In case you need re-entrance in some areas of your code you can switch Static Locals off there via a pragma.

You're initializing all CharDraw() local variables "just in case". But with cc65 such things add up. I'd refrain from that at least in hot spots like CharDraw() and when its that obvious that there's no risk of using them without setting them. In case you follow my advice please keep the non-initialized local variable definitions together. Most people first define all non-initialized locals an then define all initialized locals.

CharDraw() contains quite some code of the form
```
if (my_expression)
  my_variable = my_value1;
else
  my_variable = my_value2;
```
I suggest to replace that with
```
my_variable = my_expression ? my_value1 : my_value2;
```

Without understanding CharDraw() completely I suggest to modify it for speed: You have two nested for() loops to set the pixels. But those loops shouldn't contain any if() statements. So if your protocol allows e.g. for for Bold and Rotate then there should be four variants of those nested loops: One for Normal, one for Bold, one for Rotated and one for Bold+Rotated. Maybe you can use C macros to avoid code duplication in one way or another. In case you consider this "too much" I strong suggest to have at least two variants of those nested loops. A fast one for normal output without any "specials" and a flexible one for the rest (basically the current one).

**Comment by tschak909** [comment]
is it possible to put some of this in zero page? I've already tried to put certain variables into ZP and compiler complains about running out of space....the compiler config shows ZP having a size of $1A, is there a reason for this? 

-Thom

**Comment by oliverschmidt** [comment]
> the compiler config shows ZP having a size of $1A, is there a reason for this?

That's different for different targets. Possible reasons:

- A target has limited "free" zero page locations. The other locations are used by the OS - and the OS __*is*__ (potentially) used by the cc65 library for that target.

- A target has limited "free" zero page locations. The other locations are used by the OS - and the OS is __*not*__ used by the cc65 library but the target maintainer didn't want to increase the number of zero page locations saved / restored by every cc65 program.

- The target maintainer just didn't care or know about the benefit of additional zero page locations.

- The target maintainer has read http://cc65.github.io/doc/cc65.html#s8 and followed Uz's opinion that more register variable space isn't necessary better.

I presume you talk about the C64 - and in that case I personally don't which reason applies here. I'm the maintainer of the Apple II targets and there's no additional zero page locations because of the reason given last.

**Comment by tschak909** [comment]
And now keyboard output is working... :) Playing some airfight :D 

![image](https://user-images.githubusercontent.com/2759782/41244361-6f47c792-6d6a-11e8-8b30-2119a8a550d6.png)

**Comment by oliverschmidt** [comment]
Nice !

**Comment by tschak909** [comment]
line drawing performance is good. Text is a teeny bit slow, but livable for now. I have my swiftlink emulation going at 19200 and you can really tell the difference between line/dot/text and especially erase (which uses tgi_bar versus erase screen which uses tgi_clear.)

If you attach a SuperCPU, performance is excellent (I'm sure that will get a duh and a snicker from a few of you.) :) but it's nice to know it works well.

-Thom

**Comment by oliverschmidt** [comment]
Looking at your GitHub history it seems that you took advantage of the tips we provided. Nice to read that they obviously helped to improve the performance :-)

**Comment by tschak909** [comment]
Yes, thank you so much. :) Once I get the keyboard mapped and working properly, I will try to hook up touch support using mouse/joystick. Hopefully the cursor will work.

Once I get everything working to a testable point, I will cut an alpha and start refactoring the code to be more portable and easier to wade through.

-Thom

p.s. using the sign bit to check for a pixel was actually the one thing that improved performance the most. (makes sense really, since it's at the very inner part of the loop)

I'm wondering if unrolling the text drawing routines will get me any more performance?

**Comment by oliverschmidt** [comment]
> I'm wondering if unrolling the text drawing routines will get me any more performance?

At least worth trying.

And looking at you current source I'd say that for `diet_chardraw` `deltaX` and `deltaY` are known to be one so you can write `++x` and `++y` instead.

And it seems unnecessary to compute `b=font[fontptr[a]+j]` again for every row of the char to be drawn. Rather have an `int8_t *p = &font[fontptr[a]]` once and only increment that pointer with `++p` for the next row. Then it's just `b = *p`.

And `a=a+offset` is better `a+=offset`.

And `x=scalex[(Coord->x&0x1FF)];` is constant for every row of the char, so just compute it once and store the result in a variable to retrieve it from for every row.

And __*MAYBE*__ it's faster to "unpack" the font data at startup so that every value you need has its own byte. Then `if (b<0)` becomes `if (*p)` and `b<<=1` becomes `++p`.

**Comment by oliverschmidt** [comment]
Okay, coming back to the original topic I see two points:

- With optimizations in the C code the "necessary" performance seems to be achievable without enhanced TGI functionality.

- If there were a blitting functionality it would be targeted towards larger regions and wouldn't necessarily perform that great with 5x6 (?) pixel objects.

From that perspective I'd like to declare this issue formally as closed now.

**Comment by oliverschmidt** [comment]
On the Apple II it's rather expensive to compute the position of a pixel in the video RAM (non-linear video RAM). Therefore it seems (too ?) much overhead to compute that for every pixel in one line of a char. We'll see...
