### ISSUE TITLE
[apple2enh][question/issue?] How to display Apple2e ASCII characters

### ISSUE THREAD

**Issue by Fabrizio-Caruso** [cc65/cc65#667]
How can I display Apple//e ASCII characters?
(as in https://en.wikipedia.org/wiki/Apple_II_character_set)

I run the AppleWin emulator and select Enhanced Apple //e
if I display, say, characters 75,76,77,78 with cputc(c), I get capital letters, which is what I should get on an Apple][.

**Comment by oliverschmidt** [comment]
> if I display, say, characters 75,76,77,78 with cputc(c), I get capital letters, which is what I should get on an Apple][.

No, that's what you should get in a portable C program (https://www.asciitable.com/) independently from the system the program runs on - and that's what cc65 is aiming at !

> How can I display Apple//e ASCII characters?

In general not via cc65 methods - intentionally, see above. However http://cc65.github.io/doc/funcref.html#ss3.70, http://cc65.github.io/doc/funcref.html#ss3.88 and https://github.com/cc65/cc65/blob/master/include/apple2enh.h#L106 might help you.

**Comment by Fabrizio-Caruso** [comment]
@oliverschmidt has this change after the recent conio changes for apple2enh?

**Comment by oliverschmidt** [comment]
> How can I display Apple//e ASCII characters? (as in https://en.wikipedia.org/wiki/Apple_II_character_set)

The page you are linking is pretty misleading. The charset shown there is _NOT_ the "Apple IIe" charset!

The screenshot below shows all characters an Enhanced Apple //e is in general capable of displaying!

![image](https://user-images.githubusercontent.com/2664009/44313925-4ee79800-a411-11e8-92be-41e60fbf66d9.png)

Given the numbers you gave as example (75,76,77,78) I guess you're interested in drawing boxes/grids. With https://github.com/cc65/cc65/commit/f8c6c58373426551eed096dcfab4eab137fc0430 you can now do that with the usual portable cc65 CONIO means (see upper right corner of the screenshot).

That screenshot was created by running https://github.com/cc65/cc65/blob/master/testcode/lib/conio.c so you can see what I refer to with "the usual portable cc65 CONIO means".

If you are however interested in other chars from https://en.wikipedia.org/wiki/MouseText you can now display them with `cputc(0x80+x);` with x from 0x40 through 0x5F.

**Comment by Fabrizio-Caruso** [comment]
@oliverschmidt  sorry... you are right!

**Comment by oliverschmidt** [comment]
Okay, so after having that sorted out... Do you understand that the grid in the upper right corner of the screenshot was created with:

```
static char grid[5][5] = {
    {CH_ULCORNER, CH_HLINE, CH_TTEE,  CH_HLINE, CH_URCORNER},
    {CH_VLINE,    ' ',      CH_VLINE, ' ',      CH_VLINE   },
    {CH_LTEE,     CH_HLINE, CH_CROSS, CH_HLINE, CH_RTEE    },
    {CH_VLINE,    ' ',      CH_VLINE, ' ',      CH_VLINE   },
    {CH_LLCORNER, CH_HLINE, CH_BTEE,  CH_HLINE, CH_LRCORNER}
};
```
[...]
```
        for (i = 0; i < 5; ++i) {
                gotoxy(xsize - 5, i);
                for (j = 0; j < 5; ++j) {
                        cputc(grid[i][j]);
                }
        }
```

So you get pretty much what you usually use "those chars" for - but without "those chars".

**Comment by Fabrizio-Caruso** [comment]
@oliverschmidt  that was clear to me, mousetext chars are meant for that but not for what I need. 
I need 4 characters that point to four different directions but I did not like the arrows, much. I will resort to the arrows. 
One day instead, I will use TGI + some sort of software sprites if they ever become available.

**Comment by oliverschmidt** [comment]
> that was clear to me, mousetext chars are meant for that but not for what I need.

I see.

> I need 4 characters that point to four different directions but I did not like the arrows, much. I will resort to the arrows.

I see. At least the arrows are now available via `cputc()`.

> One day instead, I will use TGI + some sort of software sprites if they ever become available.

;-)
