### ISSUE TITLE
ca65 mvp and mvn have wrong order

### ISSUE THREAD

**Issue by clbr** [cc65/cc65#669]
Every document and 65816 programming guide says mvn and mvp are "mvn source, dest". ca65 has them exactly in the wrong order, "dest, source". This is documented nowhere.

There's a further inconsistency as docs say the values are immediate, "#$12, #$34", but ca65 throws a syntax error, expecting direct values.

Please either fix this, add a mode that fixes this and keeps the current wrong default, or at least document this.

**Comment by polluks** [comment]
1. I cannot reproduce it, however 2. should be fixed first.
2. http://www.6502.org/tutorials/65c816opcodes.html#6.6 mentions only immediate.
My programming guide of 1987 mentions only direct values because the assembler should be smart enough to calculate the bank.
Here's some kind of workaround
```
	.P816
	mvn	<.BANK($AAAA),<.BANK($BBBB)
```

**Comment by oliverschmidt** [comment]
@polluks: Thanks for the hint.
