### ISSUE TITLE
[supervision][question/bug?] How to run the binary?

### ISSUE THREAD

**Issue by Fabrizio-Caruso** [cc65/cc65#671]
I am trying to get a simple test program to work. The test program should just show something on the screen by writing onto SV_VIDEO.
```c
#include <supervision.h>
int main(void)
{
	unsigned char i;
	unsigned short j;
	i = 0;
	do
	{
		for(j=0;j<40;++j)
		{
			SV_VIDEO[j*i]=i;
		};
		++i;
	}
	while(i!=200);
	return 0;
}
```
I can't  get it to run on the Wataroo emulator.

Which emulator can run the binary produced by CC65?
Which is the suggested emulator?
Has anyone tried to use this target?

**Comment by groessler** [comment]
I see that SV_VIDEO is pointing to 0x4000. Are you sure that your program ever worked? According to the memory maps I found this is ROM2 area. And, the video buffer on Creativision is not directy accessible by the CPU. In issue #614 you were already aware of that...

**Comment by Fabrizio-Caruso** [comment]
@groessler, you are probably right about the code probably never working.
I am not sure, any more. I remember that a compilation issue was solved.
This is not the Creativision target but a Watara/Supervision target.
What is SV_VIDEO supposed to be used for? and How?

**Comment by groessler** [comment]
Ah, I mixed up Creativision and Supervision. I cannot help, sorry.

**Comment by Fabrizio-Caruso** [comment]
@groessler Creativision works fine including the linker cfg.
The Supervision is an unlucky target. I would like to support it and even implement some minimal display output. 
Has anyone ever used it?

**Comment by Fabrizio-Caruso** [comment]
@groessler Has anything changed that may have broken this target?
I think I had able to see something on the screen by writing at SV_VIDEO. This is no longer possible or I simple forgot how I did it...

**Comment by Fabrizio-Caruso** [comment]
I managed to use the .bin only with the no longer supported potator emulator.
Therefore I guess, the only issue is the binary format. This issue is not a CC65 issue, even though it would be nice to have a binary format that is usable on Mame and Wataroo.
