### ISSUE TITLE
[bug][supervision][joystick] Joystick driver wrongly detects UP movement 

### ISSUE THREAD

**Issue by Fabrizio-Caruso** [cc65/cc65#674]
I have managed to understand how to display on the screen with the supervision target (screen memory mapped linearly at SV_VIDEO with some invisible pixels at the right end of each line).

I can, sort of, run my game even on this target, for which I will write some minimal display routines, that I will share with anyone who wants to do anything with them.

I see the player character move upwards without moving the joystick.
The buttons seem ok. At least the one that is mapped as Fire 1.

I will need to write a simpler example to prove this bug.

Currently the bug can be seen by cloning CROSS CHASE and running:
make supervision_full (or make supervision_tiny)
You can run the binary with Potator emulator
To start the game press the C key (which should be mapped to Fire 1) multiple times.
The game starts (all sprites are just black squares) and you see one square just go up and not respond to any commands.

Could you please take a quick look at the joystick driver?

**Comment by Fabrizio-Caruso** [comment]
@polluks , could you please take a look at the code that reads from the joystick port?
Something is working (FIRE 1 is recognized).
By looking at your code I see you read from sv_control.
Whatever is read is not compatible with the masks.

I can help you find the problem. It is enough to write in video memory at SV_VIDEO to get some visible output.

For example, you can use:
```
#define _DRAW(x,y,image) \
{ \
	unsigned char k; \
	for(k=0;k<8;++k) \
	{ \
		SV_VIDEO[2*x+48*k+48*8*y]=128+32+8+2; \
		SV_VIDEO[2*x+48*k+48*8*y+1]=128+32+8+2; \
	} \
}
```
to draw a square for size 8x8 at position x,y.

**Comment by Fabrizio-Caruso** [comment]
@oliverschmidt , @polluks  it may be the same kind of problem as the one I fixed for Gamate: all bits had inverted values with respect to the values expected by the masks.

**Comment by Fabrizio-Caruso** [comment]
I confirm that by inverting the bits, I get the joystick to work correctly.
So eor #$ff should do fix this issue.

**Comment by Fabrizio-Caruso** [comment]
@oliverschmidt , I have made the PR #676 to fix this issue (very same fix as the Gamate one).

**Comment by oliverschmidt** [comment]
Thanks for your analysis - and the PR :-)

**Comment by oliverschmidt** [comment]
Fixed with https://github.com/cc65/cc65/pull/676.
