### ISSUE TITLE
Wrapped GPL 3.0 license into a CC65 program

### ISSUE THREAD

**Issue by tschak909** [cc65/cc65#679]
I wrapped the GPL 3.0 license into a CC65 program, so that it can easily be distributed on distribution media for CC65 programs that are licensed under the GPL version 3 (such as PLATOTerm).

It's here: https://github.com/tschak909/cc65-gpl-3.0

It currently uses conio, and the Makefile by default uses the c64 soft80 conio driver to display the license on screen. The output is paginated for the 25 line screen.

I hope that others find this useful. It was one of those things I knew I needed to do, so I just spent an hour and knocked it out. :)

-Thom

**Comment by oliverschmidt** [comment]
> I just spent an hour and knocked it out.

I spent a little more time ;-) to optimize it: https://github.com/tschak909/cc65-gpl-3.0/pulls

I guess we agree that it doesn't make sense to keep this "issue" open...
