### ISSUE TITLE
(c64) Detecting CTRL-SHIFT key combinations

### ISSUE THREAD

**Issue by tschak909** [cc65/cc65#683]
Is there a way I can coax out detecting whether e.g. CTRL-SHIFT-S is pressed vs. CTRL-S? Or am I going to have to scan the keyboard manually?

-Thom

**Comment by tschak909** [comment]
nm/close. figured out how to use the kernal to scan, for now.. this is fine.. I can read the keycode and shift codes just fine. -Thom

**Comment by oliverschmidt** [comment]
Okay...
