### ISSUE TITLE
cmake compiler checks

### ISSUE THREAD

**Issue by Grandmother** [cc65/cc65#684]
Hello, I'm trying to adapt cmake to work with cc65 and have some issues on compiler checking stages.
I'm using [toolchain-file](https://github.com/fo-fo/ngin/blob/master/cmake/toolchains/cc65-toolchain.cmake) from [this](https://github.com/fo-fo/ngin) project, but I changed it to keep cmake check compiler and while checking it has some troubles:
- while checking compiler ABI
- while checking compiler ID.

While checking compiler identifier is a big theme on cmake side, compiler ABI check fails because of special behavior of cc65:
```
Building C object CMakeFiles/cmTC_e3ce8.dir/CMakeCCompilerABI.c.obj
/usr/bin/cl65    -o CMakeFiles/cmTC_e3ce8.dir/CMakeCCompilerABI.c.obj   -c /usr/share/cmake-3.11/Modules/CMakeCCompilerABI.c
/usr/share/cmake-3.11/Modules/CMakeCCompilerABI.c(25): Fatal: Cannot open output file `/usr/share/cmake-3.11/Modules/CMakeCCompilerABI.s': Permission denied
```
Why does it create temporary output files in directory where source is? Why not in output directory or in tmp directory?

**Comment by polluks** [comment]
BTW the link is broken.

**Comment by Grandmother** [comment]
I'm sorry, fixed it.

**Comment by greg-king5** [comment]
See issue #168.

**Comment by oliverschmidt** [comment]
In the issue Greg linked I wrote:

> I don't see why any write operation should be performed in the directory containing the input/source file(s).
