### ISSUE TITLE
PLATOTerm: tgi_line() "paint-drip"

### ISSUE THREAD

**Issue by tschak909** [cc65/cc65#685]
If I use tgi_line as the line drawing function for PLATOTerm, the lines draw very fast, but they have slight inaccuracies that manifest as noise in intricate line drawings. These are very noticeable on some screens more than others.

If I provide my own line drawing function that I've used e.g. in my Android terminal, the line draws are perfect, but they are very slow....

I've put the routine in here:
https://github.com/tschak909/platoterm64/blob/private_line_draw/src/plato.c#L343

what can be done? Where could the cause of the errors be?
-Thom

**Comment by tschak909** [comment]
<img width="924" alt="line_bad" src="https://user-images.githubusercontent.com/2759782/41505267-ab203164-71ca-11e8-80a3-24d0d3c7452c.png"> <-- tgi_line()

<img width="631" alt="line_good" src="https://user-images.githubusercontent.com/2759782/41505269-c0f57d64-71ca-11e8-92a0-2fbd21b6c55f.PNG">
<-- my slow_but_accurate_line()

**Comment by oliverschmidt** [comment]
I haven't seen those artifacts in other programs using the C64 tgi line code so far. Maybe you can create a simple test program with easy-to-understand constants where everybody can see that the actual result doesn't match the expectations one has from looking at the test source code.

**Comment by tschak909** [comment]
VOILA! :) 

I did a protocol dump and made a test harness which takes the above screen, with just the line-draw commands and draws it. 

linedraw_test.c
----------------
`
#include <tgi.h>

void
main (void)
{
  tgi_install (tgi_static_stddrv);
  tgi_init ();
  tgi_clear ();
  tgi_line (0, 30, 315, 30);
  tgi_line (0, 180, 315, 180);
  tgi_line (211, 24, 211, 10);
  tgi_line (211, 10, 212, 9);
  tgi_line (212, 9, 212, 9);
  tgi_line (212, 9, 212, 9);
  tgi_line (212, 9, 213, 8);
  tgi_line (213, 8, 214, 8);
  tgi_line (214, 8, 215, 8);
  tgi_line (215, 8, 215, 8);
  tgi_line (215, 8, 216, 8);
  tgi_line (216, 8, 217, 8);
  tgi_line (217, 8, 217, 9);
  tgi_line (217, 9, 218, 9);
  tgi_line (218, 9, 225, 20);
  tgi_line (225, 20, 225, 20);
  tgi_line (225, 20, 225, 8);
  tgi_line (225, 8, 230, 8);
  tgi_line (230, 8, 230, 23);
  tgi_line (230, 23, 230, 23);
  tgi_line (230, 23, 230, 24);
  tgi_line (230, 24, 230, 24);
  tgi_line (230, 24, 229, 24);
  tgi_line (229, 24, 229, 24);
  tgi_line (229, 24, 225, 24);
  tgi_line (225, 24, 224, 24);
  tgi_line (224, 24, 224, 24);
  tgi_line (224, 24, 217, 14);
  tgi_line (217, 14, 216, 14);
  tgi_line (216, 14, 216, 24);
  tgi_line (216, 24, 211, 24);
  tgi_line (245, 24, 242, 24);
  tgi_line (242, 24, 240, 24);
  tgi_line (240, 24, 239, 24);
  tgi_line (239, 24, 238, 23);
  tgi_line (238, 23, 237, 23);
  tgi_line (237, 23, 235, 21);
  tgi_line (235, 21, 235, 21);
  tgi_line (235, 21, 234, 20);
  tgi_line (234, 20, 234, 20);
  tgi_line (234, 20, 233, 18);
  tgi_line (233, 18, 232, 17);
  tgi_line (232, 17, 232, 16);
  tgi_line (232, 16, 232, 15);
  tgi_line (232, 15, 233, 15);
  tgi_line (233, 15, 233, 14);
  tgi_line (233, 14, 234, 13);
  tgi_line (234, 13, 234, 12);
  tgi_line (234, 12, 235, 12);
  tgi_line (235, 12, 236, 11);
  tgi_line (236, 11, 237, 11);
  tgi_line (237, 11, 237, 10);
  tgi_line (237, 10, 239, 10);
  tgi_line (239, 10, 239, 9);
  tgi_line (239, 9, 240, 9);
  tgi_line (240, 9, 242, 9);
  tgi_line (242, 9, 244, 8);
  tgi_line (244, 8, 247, 8);
  tgi_line (247, 8, 247, 8);
  tgi_line (247, 8, 249, 8);
  tgi_line (249, 8, 251, 8);
  tgi_line (251, 8, 253, 9);
  tgi_line (253, 9, 254, 9);
  tgi_line (254, 9, 254, 9);
  tgi_line (254, 9, 255, 10);
  tgi_line (255, 10, 256, 11);
  tgi_line (256, 11, 257, 11);
  tgi_line (257, 11, 258, 12);
  tgi_line (258, 12, 259, 13);
  tgi_line (259, 13, 260, 14);
  tgi_line (260, 14, 260, 15);
  tgi_line (260, 15, 260, 15);
  tgi_line (260, 15, 260, 16);
  tgi_line (260, 16, 260, 17);
  tgi_line (260, 17, 260, 18);
  tgi_line (260, 18, 260, 19);
  tgi_line (260, 19, 259, 20);
  tgi_line (259, 20, 259, 21);
  tgi_line (259, 21, 257, 21);
  tgi_line (257, 21, 257, 22);
  tgi_line (257, 22, 255, 23);
  tgi_line (255, 23, 254, 23);
  tgi_line (254, 23, 253, 24);
  tgi_line (253, 24, 252, 24);
  tgi_line (252, 24, 250, 24);
  tgi_line (250, 24, 245, 24);
  tgi_line (245, 12, 247, 12);
  tgi_line (247, 12, 249, 12);
  tgi_line (249, 12, 250, 12);
  tgi_line (250, 12, 251, 12);
  tgi_line (251, 12, 252, 13);
  tgi_line (252, 13, 253, 14);
  tgi_line (253, 14, 254, 15);
  tgi_line (254, 15, 254, 15);
  tgi_line (254, 15, 254, 16);
  tgi_line (254, 16, 254, 17);
  tgi_line (254, 17, 254, 18);
  tgi_line (254, 18, 254, 19);
  tgi_line (254, 19, 253, 19);
  tgi_line (253, 19, 252, 20);
  tgi_line (252, 20, 251, 20);
  tgi_line (251, 20, 250, 21);
  tgi_line (250, 21, 249, 21);
  tgi_line (249, 21, 248, 21);
  tgi_line (248, 21, 247, 21);
  tgi_line (247, 21, 245, 21);
  tgi_line (245, 21, 244, 21);
  tgi_line (244, 21, 243, 21);
  tgi_line (243, 21, 242, 20);
  tgi_line (242, 20, 241, 20);
  tgi_line (241, 20, 240, 20);
  tgi_line (240, 20, 239, 19);
  tgi_line (239, 19, 239, 18);
  tgi_line (239, 18, 239, 18);
  tgi_line (239, 18, 239, 17);
  tgi_line (239, 17, 239, 17);
  tgi_line (239, 17, 239, 16);
  tgi_line (239, 16, 239, 15);
  tgi_line (239, 15, 240, 14);
  tgi_line (240, 14, 240, 13);
  tgi_line (240, 13, 241, 13);
  tgi_line (241, 13, 242, 12);
  tgi_line (242, 12, 242, 12);
  tgi_line (242, 12, 242, 12);
  tgi_line (242, 12, 243, 12);
  tgi_line (243, 12, 244, 12);
  tgi_line (244, 12, 245, 12);
  tgi_line (265, 24, 265, 11);
  tgi_line (265, 11, 260, 11);
  tgi_line (260, 11, 260, 8);
  tgi_line (260, 8, 275, 8);
  tgi_line (275, 8, 275, 11);
  tgi_line (275, 11, 270, 11);
  tgi_line (270, 11, 270, 24);
  tgi_line (270, 24, 265, 24);
  tgi_line (278, 21, 278, 11);
  tgi_line (278, 11, 279, 10);
  tgi_line (279, 10, 279, 9);
  tgi_line (279, 9, 279, 9);
  tgi_line (279, 9, 279, 9);
  tgi_line (279, 9, 280, 9);
  tgi_line (280, 9, 280, 8);
  tgi_line (280, 8, 281, 8);
  tgi_line (281, 8, 292, 8);
  tgi_line (292, 8, 292, 12);
  tgi_line (292, 12, 284, 12);
  tgi_line (284, 12, 284, 14);
  tgi_line (284, 14, 291, 14);
  tgi_line (291, 14, 291, 17);
  tgi_line (291, 17, 284, 17);
  tgi_line (284, 17, 284, 21);
  tgi_line (284, 21, 292, 21);
  tgi_line (292, 21, 292, 24);
  tgi_line (292, 24, 282, 24);
  tgi_line (282, 24, 280, 24);
  tgi_line (280, 24, 280, 24);
  tgi_line (280, 24, 280, 24);
  tgi_line (280, 24, 279, 24);
  tgi_line (279, 24, 279, 23);
  tgi_line (279, 23, 278, 23);
  tgi_line (278, 23, 278, 21);
  tgi_line (295, 21, 295, 20);
  tgi_line (295, 20, 296, 20);
  tgi_line (296, 20, 297, 21);
  tgi_line (297, 21, 298, 21);
  tgi_line (298, 21, 299, 21);
  tgi_line (299, 21, 300, 21);
  tgi_line (300, 21, 301, 21);
  tgi_line (301, 21, 302, 21);
  tgi_line (302, 21, 303, 21);
  tgi_line (303, 21, 304, 21);
  tgi_line (304, 21, 304, 21);
  tgi_line (304, 21, 305, 21);
  tgi_line (305, 21, 306, 20);
  tgi_line (306, 20, 306, 20);
  tgi_line (306, 20, 306, 19);
  tgi_line (306, 19, 305, 18);
  tgi_line (305, 18, 304, 18);
  tgi_line (304, 18, 303, 18);
  tgi_line (303, 18, 302, 18);
  tgi_line (302, 18, 301, 18);
  tgi_line (301, 18, 300, 17);
  tgi_line (300, 17, 299, 17);
  tgi_line (299, 17, 299, 17);
  tgi_line (299, 17, 298, 17);
  tgi_line (298, 17, 297, 17);
  tgi_line (297, 17, 296, 16);
  tgi_line (296, 16, 296, 15);
  tgi_line (296, 15, 295, 15);
  tgi_line (295, 15, 295, 14);
  tgi_line (295, 14, 295, 13);
  tgi_line (295, 13, 295, 12);
  tgi_line (295, 12, 295, 11);
  tgi_line (295, 11, 296, 11);
  tgi_line (296, 11, 297, 10);
  tgi_line (297, 10, 297, 9);
  tgi_line (297, 9, 298, 9);
  tgi_line (298, 9, 299, 9);
  tgi_line (299, 9, 300, 8);
  tgi_line (300, 8, 302, 8);
  tgi_line (302, 8, 303, 8);
  tgi_line (303, 8, 305, 8);
  tgi_line (305, 8, 307, 8);
  tgi_line (307, 8, 309, 8);
  tgi_line (309, 8, 310, 9);
  tgi_line (310, 9, 310, 12);
  tgi_line (310, 12, 310, 12);
  tgi_line (310, 12, 309, 12);
  tgi_line (309, 12, 307, 11);
  tgi_line (307, 11, 306, 11);
  tgi_line (306, 11, 304, 11);
  tgi_line (304, 11, 303, 11);
  tgi_line (303, 11, 302, 12);
  tgi_line (302, 12, 302, 12);
  tgi_line (302, 12, 301, 12);
  tgi_line (301, 12, 301, 14);
  tgi_line (301, 14, 301, 14);
  tgi_line (301, 14, 302, 14);
  tgi_line (302, 14, 303, 15);
  tgi_line (303, 15, 304, 15);
  tgi_line (304, 15, 305, 15);
  tgi_line (305, 15, 305, 15);
  tgi_line (305, 15, 307, 15);
  tgi_line (307, 15, 308, 16);
  tgi_line (308, 16, 309, 16);
  tgi_line (309, 16, 310, 17);
  tgi_line (310, 17, 310, 17);
  tgi_line (310, 17, 311, 18);
  tgi_line (311, 18, 312, 19);
  tgi_line (312, 19, 312, 20);
  tgi_line (312, 20, 311, 21);
  tgi_line (311, 21, 310, 22);
  tgi_line (310, 22, 310, 23);
  tgi_line (310, 23, 309, 23);
  tgi_line (309, 23, 309, 24);
  tgi_line (309, 24, 307, 24);
  tgi_line (307, 24, 307, 24);
  tgi_line (307, 24, 306, 24);
  tgi_line (306, 24, 305, 24);
  tgi_line (305, 24, 303, 25);
  tgi_line (303, 25, 300, 24);
  tgi_line (300, 24, 298, 24);
  tgi_line (298, 24, 296, 24);
  tgi_line (296, 24, 295, 24);
  tgi_line (295, 24, 295, 21);
  tgi_line (226, 169, 226, 130);
  tgi_line (226, 130, 226, 129);
  tgi_line (226, 129, 227, 128);
  tgi_line (227, 128, 228, 126);
  tgi_line (228, 126, 229, 126);
  tgi_line (229, 126, 230, 125);
  tgi_line (230, 125, 231, 125);
  tgi_line (231, 125, 285, 125);
  tgi_line (285, 125, 286, 125);
  tgi_line (286, 125, 288, 125);
  tgi_line (288, 125, 290, 126);
  tgi_line (290, 126, 290, 127);
  tgi_line (290, 127, 292, 128);
  tgi_line (292, 128, 292, 129);
  tgi_line (292, 129, 292, 170);
  tgi_line (292, 170, 291, 171);
  tgi_line (291, 171, 290, 171);
  tgi_line (290, 171, 290, 172);
  tgi_line (290, 172, 289, 172);
  tgi_line (289, 172, 289, 173);
  tgi_line (289, 173, 288, 173);
  tgi_line (288, 173, 287, 173);
  tgi_line (287, 173, 233, 173);
  tgi_line (233, 173, 231, 173);
  tgi_line (231, 173, 230, 173);
  tgi_line (230, 173, 229, 172);
  tgi_line (229, 172, 227, 172);
  tgi_line (227, 172, 227, 171);
  tgi_line (227, 171, 226, 171);
  tgi_line (226, 171, 226, 170);
  tgi_line (226, 168, 226, 129);
  tgi_line (226, 129, 226, 129);
  tgi_line (226, 129, 226, 128);
  tgi_line (226, 128, 227, 128);
  tgi_line (227, 128, 227, 128);
  tgi_line (227, 128, 228, 126);
  tgi_line (228, 126, 229, 126);
  tgi_line (229, 126, 230, 125);
  tgi_line (230, 125, 232, 125);
  tgi_line (232, 125, 285, 125);
  tgi_line (285, 125, 287, 125);
  tgi_line (287, 125, 288, 126);
  tgi_line (288, 126, 289, 126);
  tgi_line (289, 126, 289, 126);
  tgi_line (289, 126, 290, 126);
  tgi_line (290, 126, 291, 128);
  tgi_line (291, 128, 292, 128);
  tgi_line (292, 128, 292, 129);
  tgi_line (292, 129, 292, 168);
  tgi_line (292, 168, 291, 169);
  tgi_line (291, 169, 290, 170);
  tgi_line (290, 170, 289, 170);
  tgi_line (289, 170, 288, 170);
  tgi_line (288, 170, 287, 171);
  tgi_line (287, 171, 232, 171);
  tgi_line (232, 171, 230, 170);
  tgi_line (230, 170, 229, 170);
  tgi_line (229, 170, 227, 169);
  tgi_line (227, 169, 226, 168);
  tgi_line (234, 123, 234, 129);
  tgi_line (240, 123, 240, 129);
  tgi_line (248, 129, 248, 123);
  tgi_line (255, 123, 255, 129);
  tgi_line (263, 129, 263, 123);
  tgi_line (270, 123, 270, 129);
  tgi_line (277, 129, 277, 123);
  tgi_line (284, 123, 284, 129);
  tgi_line (240, 123, 240, 122);
  tgi_line (240, 122, 239, 122);
  tgi_line (239, 122, 239, 121);
  tgi_line (239, 121, 237, 121);
  tgi_line (237, 121, 236, 121);
  tgi_line (236, 121, 235, 121);
  tgi_line (235, 121, 234, 122);
  tgi_line (234, 122, 234, 122);
  tgi_line (234, 122, 233, 123);
  tgi_line (240, 129, 240, 129);
  tgi_line (240, 129, 240, 130);
  tgi_line (240, 130, 239, 131);
  tgi_line (239, 131, 238, 131);
  tgi_line (238, 131, 237, 131);
  tgi_line (237, 131, 235, 131);
  tgi_line (235, 131, 234, 131);
  tgi_line (234, 131, 234, 130);
  tgi_line (234, 130, 233, 129);
  tgi_line (233, 129, 233, 129);
  tgi_line (255, 123, 255, 122);
  tgi_line (255, 122, 254, 122);
  tgi_line (254, 122, 253, 121);
  tgi_line (253, 121, 252, 121);
  tgi_line (252, 121, 250, 121);
  tgi_line (250, 121, 249, 122);
  tgi_line (249, 122, 249, 122);
  tgi_line (249, 122, 248, 123);
  tgi_line (255, 129, 255, 130);
  tgi_line (255, 130, 254, 131);
  tgi_line (254, 131, 254, 131);
  tgi_line (254, 131, 252, 131);
  tgi_line (252, 131, 251, 131);
  tgi_line (251, 131, 250, 131);
  tgi_line (250, 131, 249, 131);
  tgi_line (249, 131, 248, 130);
  tgi_line (248, 130, 248, 129);
  tgi_line (270, 123, 269, 122);
  tgi_line (269, 122, 269, 122);
  tgi_line (269, 122, 268, 121);
  tgi_line (268, 121, 267, 121);
  tgi_line (267, 121, 265, 121);
  tgi_line (265, 121, 264, 121);
  tgi_line (264, 121, 264, 122);
  tgi_line (264, 122, 263, 122);
  tgi_line (263, 122, 262, 123);
  tgi_line (262, 129, 263, 130);
  tgi_line (263, 130, 264, 131);
  tgi_line (264, 131, 264, 131);
  tgi_line (264, 131, 265, 132);
  tgi_line (265, 132, 267, 132);
  tgi_line (267, 132, 268, 131);
  tgi_line (268, 131, 269, 131);
  tgi_line (269, 131, 269, 130);
  tgi_line (269, 130, 270, 129);
  tgi_line (284, 123, 284, 122);
  tgi_line (284, 122, 283, 122);
  tgi_line (283, 122, 282, 121);
  tgi_line (282, 121, 281, 121);
  tgi_line (281, 121, 280, 121);
  tgi_line (280, 121, 279, 121);
  tgi_line (279, 121, 278, 122);
  tgi_line (278, 122, 277, 122);
  tgi_line (277, 122, 277, 123);
  tgi_line (284, 129, 284, 129);
  tgi_line (284, 129, 284, 130);
  tgi_line (284, 130, 283, 131);
  tgi_line (283, 131, 282, 131);
  tgi_line (282, 131, 280, 131);
  tgi_line (280, 131, 279, 131);
  tgi_line (279, 131, 278, 131);
  tgi_line (278, 131, 277, 130);
  tgi_line (277, 130, 277, 129);
  tgi_line (277, 129, 277, 129);
  tgi_line (285, 136, 287, 135);
  tgi_line (287, 135, 289, 134);
  tgi_line (289, 134, 290, 133);
  tgi_line (290, 133, 292, 133);
  tgi_line (292, 133, 295, 134);
  tgi_line (295, 134, 297, 134);
  tgi_line (297, 134, 299, 135);
  tgi_line (299, 135, 299, 136);
  tgi_line (299, 136, 300, 138);
  tgi_line (300, 138, 300, 139);
  tgi_line (300, 139, 299, 140);
  tgi_line (299, 140, 297, 141);
  tgi_line (297, 141, 295, 142);
  tgi_line (295, 142, 285, 136);
  tgi_line (282, 138, 288, 141);
  tgi_line (288, 141, 259, 158);
  tgi_line (259, 158, 254, 155);
  tgi_line (254, 155, 282, 138);
  tgi_line (287, 141, 292, 144);
  tgi_line (292, 144, 264, 161);
  tgi_line (264, 161, 259, 158);
  tgi_line (259, 158, 287, 141);
  tgi_line (254, 155, 252, 156);
  tgi_line (252, 156, 252, 158);
  tgi_line (252, 158, 259, 162);
  tgi_line (264, 161, 262, 162);
  tgi_line (262, 162, 259, 162);
  tgi_line (255, 155, 265, 161);
  tgi_line (252, 158, 252, 162);
  tgi_line (252, 162, 259, 162);
  tgi_line (259, 162, 252, 158);
  tgi_line (292, 144, 295, 142);
  tgi_line (282, 138, 285, 136);
  tgi_line (278, 140, 237, 140);
  tgi_line (237, 140, 237, 142);
  tgi_line (237, 142, 274, 142);
  tgi_line (274, 142, 277, 140);
  tgi_line (266, 147, 237, 147);
  tgi_line (237, 147, 237, 149);
  tgi_line (237, 149, 263, 149);
  tgi_line (263, 149, 266, 147);
  tgi_line (255, 153, 237, 153);
  tgi_line (237, 153, 237, 155);
  tgi_line (237, 155, 252, 155);
  tgi_line (252, 155, 255, 153);
  tgi_line (277, 153, 281, 153);
  tgi_line (281, 153, 281, 155);
  tgi_line (281, 155, 274, 155);
  tgi_line (274, 155, 277, 153);
  tgi_line (237, 162, 251, 162);
  tgi_line (251, 162, 251, 160);
  tgi_line (251, 160, 237, 160);
  tgi_line (237, 160, 237, 162);
  tgi_line (292, 144, 282, 138);
  tgi_line (282, 138, 285, 136);
  tgi_line (285, 136, 295, 142);
  tgi_line (295, 142, 292, 144);

  for (;;)

    {

      // Spin wheels.

    }
 }
`

If you want the slow linedraw, replace tgi_line with this function:

`
void
slow_but_accurate_line (unsigned int x1, unsigned int y1, unsigned int x2,
                        unsigned int y2)
{
  int dx, dy;
  int stepx, stepy;

  dx = x2 - x1;
  dy = y2 - y1;

  if (dx < 0)
    {
      dx = -dx;
      stepx = -1;
    }
  else
    {
      stepx = 1;
    }

  if (dy < 0)
    {
      dy = -dy;
      stepy = -1;
    }
  else
    {
      stepy = 1;
    }
  dx <<= 1;
  dy <<= 1;

  // draw first point
  tgi_setpixel (x1, y1);

  // check for shallow line

  if (dx > dy)
    {
      int fraction = dy - (dx >> 1);
      while (x1 != x2)
        {
          if (fraction >= 0)
            {
              y1 += stepy;
              fraction -= dx;
            }
          x1 += stepx;
          fraction += dy;
          tgi_setpixel (x1, y1);
        }
    }                           // otherwise steep line
  else
    {
      int fraction = dx - (dy >> 1);
      while (y1 != y2)
        {
          if (fraction >= 0)
            {
              x1 += stepx;
              fraction -= dy;
            }
          y1 += stepy;
          fraction += dx;
          tgi_setpixel (x1, y1);
        }
    }
}
`

Hope this helps, there is definitely an issue.

-Thom

**Comment by oliverschmidt** [comment]
There was a misunderstanding. The simple test program I was asking for contains something like three tgi_line() calls. Something like a horizontal line at `x` and a vertical line at `y` as a reference and then a third line that starts at `x,y` or ends at `x,y` but actually doesn't as seen on the screen.

From the screen output I'd guess that tgi_line() fails with very short lines. E.g. I could imagine that lines where the start and end pixel are identical draw two pixels. I see such cases in your test program (e.g. `tgi_line (240, 129, 240, 129);`).

**Comment by tschak909** [comment]
Would that also account for the cases e.g. with the extreme distortion with the pencil eraser?

-Thom

**Comment by oliverschmidt** [comment]
For sure I can't know but that area looks like it's built of many short lines in order to form a curve. And as I already wrote: You're not exactly the first C64 tgi user ;-) so it has to be something "unusual"...

**Comment by tschak909** [comment]
Yup, I figured, which is why I brought it here. :)

**Comment by greg-king5** [comment]
Oliver is correct about the cause of the "drip".  Attempts to draw lines of one dot actually draw vertical lines of two pixels.

The pencil eraser shows a different bug.  It looks like a rounding error.

**Comment by oliverschmidt** [comment]
> Attempts to draw lines of one dot actually draw vertical lines of two pixels.

Thanks for checking !

I guess we all agree that it might make sense to have PLATOTerm's LineDraw() check if if the start and end coords refer the same point on the screen and and just call tgi_setpixel() if they do. Beside being a workaround for the C64 tgi issue it might be even faster - obviously heavily depending on the screen content.

**Comment by polluks** [comment]
@oliverschmidt We all? ;-)
there is an axiom in graphics
tgi_line(x,y,x,y) == tgi_setpixel(x,y)
IMHO

**Comment by tschak909** [comment]
Changed code to:
https://gist.github.com/tschak909/26689366552eaef733edc3becfc8783c

and I now see the following:
<img width="852" alt="line_attempt_2" src="https://user-images.githubusercontent.com/2759782/41633053-785a59c8-7402-11e8-83b5-0cb9b1a48a8f.PNG">

**Comment by tschak909** [comment]
for reference, this is the output from a color PLATO display (PTERM):
<img width="785" alt="noterriffic" src="https://user-images.githubusercontent.com/2759782/41633522-f6a362c8-7404-11e8-89c6-f1fcea931d8b.PNG">

**Comment by oliverschmidt** [comment]
> We all? ;-) IMHO this is an axiom in graphics tgi_line(x,y,x,y) ≡ tgi_setpixel(x,y)

Okay, in somewhat more detail:

- I wrote "might". I wanted to invite Thomas to add the suggested check.
- The check is of course a workaround in the first place.
- I imagine that the check (even if written in C) speeds up the drawing of single pixel lines - totally independent from the question if they look right or wrong.
- I think that single pixel lines are "unusual" enough to not want tgi_line to be explicitly optimized for them - again talking of performance, not functional correctness.

So maybe even after tgi_line is fixed at some point in time to look correct the check in the PLATO C code might still make sense as it may speed up drawing "screens" with lots of single pixel lines - and screens without many single pixel lines maybe don't have that many lines anyhow so they don't suffer noticeably from the check.

**Comment by oliverschmidt** [comment]
> Changed code to: [...] and I now see the following: [...]

Thanks for checking. The result (especially at the "S" glyph in the upper right corner) shows very clearly that there are more issues - or a more general issue :-(

**Comment by polluks** [comment]
After this comment "If dy=0 it's just a point" something goes wrong.

**Comment by oliverschmidt** [comment]
> After this comment "If dy=0 it's just a point" something goes wrong.

...refering to https://github.com/cc65/cc65/blob/master/libsrc/c64/tgi/c64-hi.s#L544

**Comment by greg-king5** [comment]
OK, commit 4980fade7413f43f3822bf3e8955c5a876897b3c should fix the tgi_line() bug in c64-hi.tgi.

**Comment by tschak909** [comment]
Thanks for that. :)  I'll check later today when I am off work. 

I do suspect that the rounding problem that shows up with the pencil eraser, may be a bit more difficult to solve...

-Thom

**Comment by tschak909** [comment]
Pulled out my tgi_setpixel workaround in my draw line routine, and it just has tgi_line now:

$ cl65 -V

cl65 V2.17 - Git 86945a12

commit 86945a12705db53e63df41d97b254b9f56aff7c6 (HEAD -> master, origin/master, origin/HEAD)
Merge: 4980fade 6a70d1da
Author: Oliver Schmidt <ol.sc@web.de>
Date:   Thu Jun 21 22:37:29 2018 +0200

    Merge pull request #687 from polluks/patch-12

    Smaller driver code

<img width="631" alt="000" src="https://user-images.githubusercontent.com/2759782/41748230-96654ff2-7576-11e8-90c3-7094209ed2b0.png">

**Comment by tschak909** [comment]
I think this can be closed.
