### ISSUE TITLE
How to get status of serial buffer?

### ISSUE THREAD

**Issue by tschak909** [cc65/cc65#689]
(Regarding PLATOTerm) Am a bit confused actually, I need to be able to get the status of the serial buffer, so that I can assert XON/XOFF appropriately, as the user-port 2400 bps implementation I have occasionally overflows. 

In other implementations, I have threads, and I simply use the I/O thread to read the serial data into a ring buffer. When the buffer hits a threshold, I assert XOFF and keep processing data, draining the buffer until a another certain threshold, and subsequently re-assert XON....but not sure what I can do here with this given serial implementation...any ideas?

-Thom

**Comment by greg-king5** [comment]
The driver uses some Kernal subroutines and variables.  The two that you want are:
```c
#define RIDBE 0x029B
#define RIDBS 0x029C
```
They are described by "The C64 Programmers Reference Guide" and "Mapping the C64".  (They can be found at http://www.zimmers.net/anonftp/pub/cbm/manuals/ .)

**Comment by tschak909** [comment]
Also, for the swiftlink, am I correct in that ser_status will return the 6551 status register (SR) ?

-Thom

**Comment by oliverschmidt** [comment]
> When the buffer hits a threshold, I assert XOFF and keep processing data, draining the buffer until a another certain threshold, and subsequently re-assert XON....but not sure what I can do here with this given serial implementation...any ideas?

My two cents:

Serial I/O almost all of the times requires/uses an interrupt handler and flow control has to be done from within that interrupt handler. Trying to do flow control from the main program makes nearly no sense at all. The interrupt handler then does exactly what you describe above: One threshold triggers the flow-stop and another triggers the flow-start.

All this is totally independent from the question of hardware flow control vs. software flow control. The existing C64 SwiftLink/Turbo-232 driver only supports hardware flow control. It would make sense to either extend it to support software flow control too - or to add another driver only supporting software flow control.

According to my understanding the driver uses a 256 byte buffer and the threshold is 64 bytes (https://github.com/cc65/cc65/blob/master/libsrc/c64/ser/c64-swlink.s#L305) so if the buffer is 3/4 filled it triggers (hardware) flow stop.

**Comment by tschak909** [comment]
Yup, I've attempted to implement the flow control in the main part of the program, as a test. It's pretty clear I'm going to have to graft this into the serial handlers, themselves. There is a branch in platoterm, flow_control that is holding this...

will try to see if I can get software flow control into the up2400 driver itself, and try doing it for swlink.

**Comment by silverdr** [comment]
> On 2018-06-24, at 00:10, greg-king5 <notifications@github.com> wrote:
> 
> The driver uses some Kernal subroutines and variables. The two that you want are:
> 
> #define RIDBE 0x029B
> 
> #
> define RIDBS 0x029C
> They are described by "The C64 Programmers Reference Guide" and "Mapping the C64". (They can be found at http://www.zimmers.net/anonftp/pub/cbm/manuals/ .)

Or if you want searchable text versions with many errors corrected...

http://e4aws.silverdr.com/project64/

**Comment by tschak909** [comment]
Yup, I've used it, and if you look at: https://github.com/tschak909/platoterm64/blob/flow_control/src/io.c#L105

You'll see that I'm getting the buffer size there, and acting upon it.

What I'm trying to figure out is, when I reassert XON, I suddenly get a gap of missing information. You can see from the videos above. Am trying to wrap my way around the VICE monitor to see what in the hell is actually going on. Anyone who can help with debugging tips for real or emulated hardware, would be much appreciated, because again, I am not a native commodore 64 coder..I am just passing through trying to make a working terminal. :)

**Comment by tschak909** [comment]
I've increasingly tried to clamp down, doesn't seem to help, oddly enough...

current values are:
#define XOFF_THRESHOLD 64
#define XON_THRESHOLD  1

(if I set xon_threshold to 0, stuff fails for obvious reasons...)

-thom

**Comment by polluks** [comment]
Maybe the SER API should support handshaking like Enable/Disable, see http://cbm.ficicilar.name.tr/program/7/rs232-communication-library

**Comment by tschak909** [comment]
With that library, I see doing 9600bps basically involves turning VIC
off...wouldn't that ultimately result in a flickering mess, if you're
trying to display something?

-Thom

**Comment by polluks** [comment]
Indeed, for 9600 baud you should better use "UP9600".
https://www.c64-wiki.de/wiki/UP9600

**Comment by tschak909** [comment]
It looks like indeed what might be happening is the fact that no matter what, there is so much data being buffered (due to the host's extreme connection speed), that the poor 256 byte up2400 buffer just gets its butt kicked.

Problem here, is that with wifi modems, I don't see a way around this, save contacting every Commodore 64 wifi modem vendor and getting them to add a function that can adjust the TCP window size, or similar parameters.

<-- *utterly-dejected*

**Comment by tschak909** [comment]
What you're saying does make sense. Since modifying the code running inside the system would be an incredibly painful task (it's buried deep within the system, and is written in CDC 60-bit COMPASS assembler), i'll implement it outside.

I'll experiment with different approaches to specifying the window size, but with the goal of specifying said window size be as passive as possible, so that existing terminals will continue to work, as is.

@oliverschmidt  Does this mean though, that you're going to punt adding receive window size to IP65? ;)

-Thom

**Comment by oliverschmidt** [comment]
> Does this mean though, that you're going to punt adding receive window size to IP65? ;)

No, but as mentioned I've no idea when I'll get to actually doing it.

**Comment by polluks** [comment]
ESP8266 handshake is common, see PB1 and PB6
https://www.c64-wiki.de/wiki/Wifi-Adapter#Verdrahtung_Userport_.3C.3E_ESP8266_Node_MCU_V2

**Comment by oliverschmidt** [comment]
> ESP8266 handshake is common, see PB1 and PB6

Which should be read as "ESP8266 HW handshake". I read different things on different modules on ESP8266 sites but that doesn't matter if "the" WiFi Modem supports HW handshake :-)

Apart from that at least several alternative firmwares mentioned on the linked Wiki page seem to support XON/XOFF :-)

**Comment by greg-king5** [comment]
Maybe, double-buffering might alleviate the problem.  `io_recv_serial()` could implement a much bigger middle-level ring buffer.  It would work like this:

1. If the low-level buffer has passed its threshold, then send XOFF.
2. Transfer as much data as possible from the low-level buffer to the middle-level buffer.
3. Return the next byte from the middle-level buffer.
4. If the middle-level buffer is empty, then send XON.

**Comment by polluks** [comment]
Yeah, similar to our software stack.

**Comment by tschak909** [comment]
I think I may be able to facilitate this if in my main I/O loop, I try to drain the primary buffer as fast as possible, something like: (pseudo-code-follows)
`
 if (there_is_a_serial_byte)
   {
        if xoff_threshold
           send_xoff;
       else if xon_threshold
           send_xon;
 drain_primary_buffer:
       copy_to_secondary_buffer();
       if (there_is_a_serial_byte)
          goto drain_primary_buffer;
   }
`

(I apologize, if I am missing something obvious...)

-Thom

**Comment by greg-king5** [comment]
This will be simpler; but, it still might work well enough:
```sh
drain_first_buffer_into_second_one;

measure_second_buffer;
if xoff_threshold  // (in second buffer)
    then send_xoff;
else if xon_threshold
    then send_xon;

if byte_in_second_buffer
    then process_it;
```

**Comment by tschak909** [comment]
Ok, I will try that.

Have also discovered that these WIFI modems all attach their RTS lines to PB1 and use them if &K1 is enabled. 

I'm thinking if I replace the xon/xoff with POKEs to DD01 setting bit 1, it might be more effective.

I've got it in this snippet here (I did this before I read your last reply, @greg-king5 
https://gist.github.com/tschak909/2d28e65ef77532f8c7b246114e2857b7

C64 Memory Map:
http://sta.c64.org/cbm64mem.html

And this method should work, according to a conversation I'm having with Jim Drew:
"
Hi Thom!

Yes, this is my contact email address.

I don't support XON/XOFF.  It's simply too slow!  I do support RTS/CTS, so you can certainly stop 
the flow of data from the WiModem by just changing the RTS state ($DD01, bit 1).  This works at any 
baud rate.

The UP9600 hack is nice because it means much faster through put.  I have 38400 baud working with my 
new WHD program (a hard drive emulator for the WiModem), and I actually can do up to 57600 baud with 
a stock C64, it just takes a 2K table to do it.  Anything higher than 9600 baud requires the screen 
to be turned off.  Not very useful for a terminal program, but fine for loading/saving of files.

Let me know if you have any questions!


Jim
"

Thoughts?

**Comment by mrdudz** [comment]
Am Donnerstag, 12. Juli 2018, 01:14:46 CEST schrieb Thomas Cherryhomes:
> Ok, I will try that.
> 
> Have also discovered that these WIFI modems all attach their RTS lines to
> PB1 and use them if &K1 is enabled.
> 
> I'm thinking if I replace the xon/xoff with POKEs to DD01 setting bit 1, it
> might be more effective.
> 
> I've got it in this snippet here (I did this before I read your last reply,
> @greg-king5
> https://gist.github.com/tschak909/2d28e65ef77532f8c7b246114e2857b7
> 
> C64 Memory Map:
> http://sta.c64.org/cbm64mem.html
> 
> And this method should work, according to a conversation I'm having with Jim
> Drew: "
> Hi Thom!
> 
> Yes, this is my contact email address.
> 
> I don't support XON/XOFF.  It's simply too slow!  I do support RTS/CTS, so
> you can certainly stop the flow of data from the WiModem by just changing
> the RTS state ($DD01, bit 1).  This works at any baud rate.
> 
> The UP9600 hack is nice because it means much faster through put.  I have
> 38400 baud working with my new WHD program (a hard drive emulator for the
> WiModem), and I actually can do up to 57600 baud with a stock C64, it just
> takes a 2K table to do it.  Anything higher than 9600 baud requires the
> screen to be turned off.  Not very useful for a terminal program, but fine
> for loading/saving of files.
> 
> Let me know if you have any questions!
> 
> 
> Jim
> "
> 
> Thoughts?

other than that you shall take anything jimmy says with a huge grain of salt - 
its just logical that RTS/CTS will work a whole lot better better and has been 
the recommended thing to do since i have owned my first userport rs232 
interface :)

other than that local (!) xon/off handling "should" still work. if implemented 
properly - thats the part about salt =P

-- 

http://hitmen.eu                 http://ar.pokefinder.org
http://vice-emu.sourceforge.net  http://magicdisk.untergrund.net

Any sufficiently advanced technology is indistinguishable from magic. 
<Arthur C. Clarke>

**Comment by polluks** [comment]
Aha, I suppose a symetric buffer doesn't fit very well. Remember V.23: 1200/75
so we should have 480 tx buffer and 32 rx buffer.

**Comment by tschak909** [comment]
The problem I'm seeing now, is that once I pull RTS low, I lose ALL of my keystrokes. This includes my function keys to change color, the main loop screeches to a halt, am trying to debug why... :/

**Comment by polluks** [comment]
@tschak909 This sounds a little bit like #696 but there should be no conflict between keyboard and userport.

**Comment by mrdudz** [comment]
did you use dc01 instead of dd01 perhaps? :)

**Comment by tschak909** [comment]
nope. 
https://github.com/tschak909/platoterm64/blob/c64_up_flow_control/src/c64/io.c ;)

**Comment by mrdudz** [comment]
eeeks. what you are doing there cant work obviously - you should only modify bit1 - not all 8 bits, that will certainly not work. see eg http://unusedino.de/ec64/technical/aay/c64/cia21.htm

**Comment by tschak909** [comment]
oh shit, you're right. changing that to only modify bit 1 ;)

**Comment by tschak909** [comment]
Have amended the code, and keyboard is back, but flow control still not quite right... am working through it...

https://github.com/tschak909/platoterm64/blob/c64_up_flow_control/src/c64/io.c

**Comment by polluks** [comment]
No, boolean algebra says "& 0xFD"

**Comment by mrdudz** [comment]
or ~2 for readability

**Comment by tschak909** [comment]
Ok, hardware flow control seems to be starting to work, it needs to be tweaked a bit, because while the connection is suddenly 90% more reliable, it's not perfect, particularly on screens chock full of text...need to see what i can do better...maybe you guys have some ideas?

(again, thanks so much for helping me work through this)

Current code:
https://github.com/tschak909/platoterm64/blob/c64_up_flow_control/src/io_base.c

And i've cut an alpha release with d64 disk image if anyone wants to try:
https://github.com/tschak909/platoterm64/releases

Yay, so happy.. this one really was making me sick to my stomach...

-Thom
