### ISSUE TITLE
CC65 regression between 2.14 and 2.15 with short reproducer

### ISSUE THREAD

**Issue by EtchedPixels** [cc65/cc65#691]
The following code compiles correctly in 2.14 but errors incorrectly in 2.15

void foobar();

void foobar() {
}

**Comment by oliverschmidt** [comment]
I must admit that I don't know how to classify this issue. However, the following works:

```
void foobar(void);

void foobar(void) {
}
```

**Comment by EtchedPixels** [comment]
Yes the bug is in () not (void)

They are not quite the same things in C - but the first case should work. If I get a bit of time I'll have a dig and try to see whats changed and broken it

**Comment by oliverschmidt** [comment]
@polluks: Thanks for the clarification.

**Comment by EtchedPixels** [comment]
Added comments to #245 and will carry on investigating what I can do there

**Comment by oliverschmidt** [comment]
Thanks :-)
