### ISSUE TITLE
Feature request - tgi for C128 hires mode (VIC-II)

### ISSUE THREAD

**Issue by xlar54** [cc65/cc65#694]
We have VDC, but seems odd that we dont have a tgi for hires mode.

**Comment by oliverschmidt** [comment]
https://github.com/cc65/wiki/wiki/Reminders#C128_library already contains:

Make a VIC-II TGI driver -- needs different BASIC header and CFG files that open nine Kibibytes below the program (i.e., GRAPHIC 1).

**Comment by xlar54** [comment]
Trying to give back to the group here... Ive been working on this driver, and its coming along, but ive run into a snag that I cant seem to get around.  If anyone else can take a look at this and maybe figure out why its not behaving properly, it would be appreciated.

[c128hi.zip](https://github.com/cc65/cc65/files/2220105/c128hi.zip)

There is the tgi driver and a quick demo program.  tgi_clear() seems to not be working quite right.

**Comment by xlar54** [comment]
pull 706

**Comment by xlar54** [comment]
greg fixed my code to live properly under the ROM, closing this issue
