### ISSUE TITLE
kbhit and mouse driver - c128 target

### ISSUE THREAD

**Issue by xlar54** [cc65/cc65#696]
Seems the "1" and "2" keys are not detected when the kbhit is called and the mouse driver is loaded.

**Comment by xlar54** [comment]
As a temp fix, Im PEEKing location 212 to get the pressed keycode for keys 1 and 2.  But within a loop, this can register multiple times.

**Comment by oliverschmidt** [comment]
cc65 is a multi target tool chain. Therefore it might make sense to provide the machine you are experiencing the issue on.

**Comment by xlar54** [comment]
my apologies.. This issue was for the c128 target.  I havent tested the 64 target.

**Comment by oliverschmidt** [comment]
Hm, I was under the impression that these type of issues were solved with https://github.com/cc65/cc65/pull/114 ...

**Comment by polluks** [comment]
@xlar54 "3" works? "1" and "2" are some kind of special keys in the matrix.

**Comment by mrdudz** [comment]
also which mouse driver would be interesting... does this happen also with the regular 1531 driver?

i wouldnt call 1 and 2 "special" :) they are just used in parallel with joystick port 1 - some interferences are expected. however when the mouse is not being moved, nor mouse buttons are pressed, then those keys should work.

**Comment by xlar54** [comment]
Yeah, the normal std 1351 driver.  I have a work around, scanning for the keys via PEEK to 212.  If this isnt something that cam be fixed, then my solution will get me through.  I realize that some of these things are just the way they are as far as the hardware is concerned (Id have to do the same in assembly or basic, etc).  Thank you all for being responsive.  Im writing a web browser for the 128 and its coming along very nicely thanks to your work on cc65.    https://www.reddit.com/r/Commodore/comments/8w02m0/rhml_browser_is_coming_along/?st=jj6v0n5k&sh=58a33a17

**Comment by mrdudz** [comment]
as said, if it also happens when you dont touch the mouse (press buttons) then its clearly a bug. i think this "exorcism code" does too much, it disables some CIA line completely - which probably removes the phantom keys, by disabling those keys alltogether :)

**Comment by polluks** [comment]
@greg so we need the exorcist again :wink:

**Comment by mrdudz** [comment]
the proper solution is, btw, to a) toggle port A DDR between in/out (in for joystick,out for keyboard) and b) skip keyboard input when joystick input was detected while port A DDR was input.

**Comment by xlar54** [comment]
As noted in the pull request for 853, the 128 mouse driver has been reverted back to almost identical to the 64 one, and it seems to work fine for all keys and has no apparent issue with other code Ive written.  Thats not to say that an old bug hasnt been brought back into the picture - Im not sure what the code I removed was supposed to do.

**Comment by greg-king5** [comment]
Pull Request #109 tells why the "exorcism" code was added to the drivers.
> It seems that the "left-arrow", "1", "2", and space-bar keys are not detected when `kbhit()` and `cgetc()` are called and the mouse driver is loaded.

It seems to be a one-line bug in the drivers.  Try this patch on the **original** driver.  Please tell us if any keys still are blocked.
```diff
diff --git i/libsrc/c128/mou/c128-1351.s w/libsrc/c128/mou/c128-1351.s
index d06e942c4..d9bb84922 100644
--- i/libsrc/c128/mou/c128-1351.s
+++ w/libsrc/c128/mou/c128-1351.s
@@ -377,7 +377,7 @@ IOCTL:  lda     #<MOUSE_ERR_INV_IOCTL     ; We don't support ioctls,
 IRQ:    jsr     CPREP
         lda     KEY_COUNT
         sta     old_key_count
-        lda     #$7F
+        lda     #$FF
         sta     CIA1_PRA
         lda     CIA1_PRB                ; Read joystick #0
         and     #$1F
diff --git i/libsrc/c128/mou/callback.inc w/libsrc/c128/mou/callback.inc
index 9f1d749a7..bcd9a2915 100644
--- i/libsrc/c128/mou/callback.inc
+++ w/libsrc/c128/mou/callback.inc
@@ -16,7 +16,7 @@ callback:
         lda     OLD_BUTTONS             ; keypress before?
         bne     @discard_key            ; yes, discard key
 
-        lda     #$7F
+        lda     #$FF
         sta     CIA1_PRA
         lda     CIA1_PRB                ; Read joystick #0
         and     #$1F
```
