### ISSUE TITLE
c128 target - tgi_circle renders ellipse on VDC

### ISSUE THREAD

**Issue by xlar54** [cc65/cc65#699]
As stated.   Appears to be a set width issue

**Comment by oliverschmidt** [comment]
It works as designed as it doesn't take the pixel aspect ratio into account. Check out https://github.com/cc65/cc65/blob/master/samples/tgidemo.c#L83 to see how to get what you want.

**Comment by xlar54** [comment]
Is pixel aspect ratio the same as screen width?  The 128's VDC is 640x200 addressable pixels, as opposed to the more common 320x200 for most other targets.

I did check your link.  Will work on utilizing the example, thank you.

**Comment by xlar54** [comment]
Acutally I found that using two arcs solved the issue for me.  The code you provided actually did the same thing.

**Comment by oliverschmidt** [comment]
I rather wanted to point you to using `tgi_imulround(radius, tgi_getaspectratio())` to create a TGI-driver-independent circle.

**Comment by xlar54** [comment]
Yes, thanks Oliver.  Im sorry I didnt understand.  The code you mention above worked perfectly.
