### ISSUE TITLE
linking c64-tgimousedata.o in universal makefile for c64 target?

### ISSUE THREAD

**Issue by tschak909** [cc65/cc65#700]
As it says in the subject, how can I best link in c64-tgimousedata.o just for the c64 target?

How can I override this sprite data?

-Thom

**Comment by oliverschmidt** [comment]
The universal Makefile isn‘t official part of cc65. Nevertheless, I provide feedback here...

As you know of the universal Makefile I presume you read the Wiki content about it. So https://github.com/cc65/wiki/wiki/Project-Growing#Platform_specific_code seems like the answer to me, or do I miss your point?

**Comment by tschak909** [comment]
Cool, thanks! :)

-Thom
