### ISSUE TITLE
c16/plus4 TGI? ;) (feature request)

### ISSUE THREAD

**Issue by tschak909** [cc65/cc65#701]
How similar is the VIC graphics architecture to the TED? Could the TGI driver for the C64 be adapted for the TED machines?

-Thom

**Comment by mrdudz** [comment]
its pretty similar i think... basically TED is a VICII without sprites, but more colors.

**Comment by polluks** [comment]
Closed? I suppose "feature request" means: If possible, do it :)
See #694
