### ISSUE TITLE
Abs,X and Dir,X addressing modes get mixed up by assembler

### ISSUE THREAD

**Issue by georgjz** [cc65/cc65#702]
I'm not sure if this is a bug, but here is my problem:

I have a section of code where I want to use the X register as an offset into a table:
```
TableAddr = $affe 
lda TableAddr, X
```
This works fine and will assemble to `BD FE AF`. But when the high byte of my table address is zero/$00, the assembler will interpret it as Direct Indexed addressing instead of Absolute Indexed:
```
TableAddr = $00fe 
lda TableAddr, X
```
will assemble to `B5 FE`.

Is this by design? I find that behavior odd, since I would really like to control whether Absolute or Direct addressing is used in my code. There are workarounds to this, but again, I find it odd that the assembler 
will translate an Absolute address with a zero high byte to Direct addressing.

Put differently,
```
lda $0001, X
lda $01, X 
```
Will both translate to `B5 01` and I wonder why.

**Comment by mrdudz** [comment]
Am Samstag, 14. Juli 2018, 11:46:54 CEST schrieb georgjz:
> I'm not sure if this is a bug, but here is my problem:
> 
> I have a section of code where I want to use the X register as an offset
> into a table: ```
> TableAddr = $affe
> lda TableAddr, X
> ```
> This works fine and will assemble to `BD FE AF`. But when the high byte of
> my table address is zero/$00, the assembler will interpret it as Direct
> Indexed addressing instead of Absolut Indexed: ```
> TableAddr = $00fe
> lda TableAddr, X
> ```
> will assemble to `B5 FE`.
> 
> Is this by design? I find that behavior odd, since I would really like to
> control whether Absolute or Direct addressing is used in my code. There are
> workarounds to this, but again, I find it odd that the assembler will
> translate an Absolute address with a zero high byte to Direct addressing.

how is that odd? the assembler doesnt remember for any symbol you assign how 
many leading zeros it had. and i have yet to see one that does. if you want to 
force the adressing mode, use the respective prefixes for it.

-- 

http://hitmen.eu                 http://ar.pokefinder.org
http://vice-emu.sourceforge.net  http://magicdisk.untergrund.net

Universitäten sind schöne Misthaufen, auf denen gelegentlich einmal eine edle 
Pflanze gedeiht. 
<Albert Einstein>

**Comment by georgjz** [comment]
Again, I almost assumed this is by design. I'd simply find it more convenient if the assembler would derive the intended addressing mode by the provided data:
```
lda $0001, X    ; BD 01 00
lda $01, X      ; B5 01
```
Since something like
```
lda $1234, X    ; BD 34 12 
lda $12, X      ; B5 12
```
does work.

**Comment by mrdudz** [comment]
as said, leading zeros simply "do not exist". it would be super messy to handle this in the assembler too. and for those rare cases where it matters, using the explicit prefixes is more readable anyway.

**Comment by oliverschmidt** [comment]
> Again, I almost assumed this is by design.

Therefore it seems clean to classify this issue as a question.

> [...] leading zeros simply "do not exist".

This seems to be a clear answer.

**Comment by georgjz** [comment]
That clears it up at least, thank you.

**Comment by oliverschmidt** [comment]
You're welcome.

I understand your expectation. And if we could just decide if it behaves the one way ore the other I might be "on your side". However, there's - as already explained - no such decision to be made and therefore no point in a discussion.

**Comment by shipof123** [comment]
What assembler are you using?
