### ISSUE TITLE
SER_ERR_NO_DRIVER

### ISSUE THREAD

**Issue by xlar54** [cc65/cc65#703]
For the 64 target, I have the following code:

	err = ser_load_driver("c64-up2400.ser");
	if (err != 0)
	{
		ser_open(&serialParams);
		ser_ioctl(1, NULL);
	}
	else
	{
		cprintf("Error loading serial driver.\r\n");
		exit(EXIT_FAILURE);
	}

The c64-up2400.ser file is in the same directory but always returns with the error.  Any idea what this might be caused by?

**Comment by oliverschmidt** [comment]
According to the source code 
https://github.com/cc65/cc65/blob/master/libsrc/serial/ser_load.s the errror SER_ERR_NO_DRIVER can‘t be returned from ser_load_driver().

According to the source unfortunately the same error is returned both on issues with accessing the file and with the file „content“. So you may want to try to open() the file for testing purposes. If that fails the file isn‘t accessible. If that succeeds the file is corrupt.

**Comment by greg-king5** [comment]
Only `ser_unload()` returns `SER_ERR_NO_DRIVER`.  Recheck which error code you actually are getting.

**Comment by greg-king5** [comment]
If you get `SER_ERR_CANNOT_LOAD`, then `_oserror` will tell you why.

**Comment by xlar54** [comment]
Well, the value of err is 1 when that code above executes, so looking at the serial.h file, it seems to be the SER_ERR_NO_DRIVER error, maybe Im understandig it wrong.    I tried a basic program in the same directory:

10 open1,8,0,"c64-up2400.ser,p,r"
20 get#1,a$:if st<> 0 then 30
25 print a$;:goto 20
30 close 1

and it reads the file just fine.

**Comment by xlar54** [comment]
ok, please disregard.  You guys pointed me in a helpful direction so you can close this issue.  I still have a problem, but its most certainly on my side.  Thank you for your help.

**Comment by greg-king5** [comment]
> ```c
> if (err != 0)
> ```

Is that a typo in this Github issue; or, is it in your C code?
[It should be `if (err == SER_ERR_OK)`.]

**Comment by xlar54** [comment]
yes, thats my own typo.  Im getting a zero for the error value, so its loading properly.  The code still doesnt work when running, but that has to be my issue and not cc65.
