### ISSUE TITLE
Does tgi driver for c64 trash rs232 somehow?

### ISSUE THREAD

**Issue by xlar54** [cc65/cc65#704]
In my code, I have a loop which calls 

cbm_k_chkin(2);
cbm_k_getin();

from 128 mode VDC, this works fine, when using the VDC tgi driver to render a custom font.  On a 64 @ 1200 bps, this generally crashes or freezes up with little or no data received.   My repo which demonstates the issue:

https://github.com/xlar54/rhml

I can receive data though, if not using the 64's tgi driver and just cprintf()'ing the value to the text screen.  Im sorry if this is too specific to my project, but due to rendering with a custom font, I have had to implement my own version of tgi_outtxt (64 doesnt have one yet)

**Comment by polluks** [comment]
Did you read #639?

**Comment by xlar54** [comment]
I did.  I downloaded cygwin and the latest code from github for cc65, built cc65.  Rebuilt my project, but same issue unfortunately.  Ill keep looking.

**Comment by oliverschmidt** [comment]
> I downloaded cygwin and the latest code from github for cc65, built cc65.

I may very well be missing the point but I‘d like to state:

* The Windows Snapshot (http://sourceforge.net/projects/cc65/files/cc65-snapshot-win32.zip) is built automatically after each change to cc65. So there‘s no point in building the - unchanged - current cc65 on your own for Windows.

* There‘s no need for Cygwin to build cc65 for Windows: https://github.com/cc65/wiki/wiki/Microsoft-Windows

**Comment by xlar54** [comment]
Oh thats good to know.  But it seemed from the other thread that there may have been a minor code change that may have impacted the issue, so I wanted to try getting the latest and rebuilding.  Sounds like it wasnt necessary, but thank you.

**Comment by greg-king5** [comment]
We haven't added the NMI trampoline to the cc65 library yet.

You must get it from <https://github.com/tschak909/platoterm64/raw/master/src/c64/nmi-trampoline.s>.
You must link it into your program.  The program must call `install_nmi_trampoline()` (to start the interrupt trap) at some time before it starts to use TGI functions.

Note: the c128 library doesn't need the trampoline.

**Comment by polluks** [comment]
@greg-king5 Do you want to include the trampoline in the driver?

**Comment by oliverschmidt** [comment]
I thought we had agreed that the trampoline would be a cc65 constructor...

**Comment by greg-king5** [comment]
Yes.  Someday (there are a lot of "somedays" in this project :-), we might write a medium-resolution (multi-color) TGI driver for the C64.  And, we have the RAM-based extended memory driver.  So, it's best to put the trampoline outside of the drivers.

**Comment by xlar54** [comment]
That did it!!! Thank you guys very much!  I must have missed this part of the discussion in the other thread somehow, but its working fine now.  Very cool!

**Comment by polluks** [comment]
Fine. We should only close a ticket after the patch is checked in.
