### ISSUE TITLE
quickly check carry?

### ISSUE THREAD

**Issue by tschak909** [cc65/cc65#705]
Am curious, just as checking if a value is less than 0 can check the sign bit quickly, is there a similar optimization that can quickly check the carry of a bit shifted to the right?

-Thom

**Comment by oliverschmidt** [comment]
Afaik you need some inline asm or alike to do so.

**Comment by greg-king5** [comment]
>> Am curious, just as checking if a value is less than 0 can check the sign bit quickly, is there a similar optimization that can quickly check the carry of a bit shifted to the right?
>
> Afaik, you need some inline asm or alike to do so.

The cc65 code:
```c
static unsigned char var = 0x23;

void main(void)
{
    var >>= 1;
    __asm__("bcc %g", label1);
    // carry was set
    var = 0x00;
    goto label2;
label1:
    // carry was clear
    var = 0x34;
label2:
    ;
}
```
compiles to
```asm
.segment        "DATA"
_var:   .byte   $23

.segment        "CODE"
.proc   _main: near
;
; var >>= 1;
;
        lda     _var
        lsr     a
        sta     _var
;
; __asm__("bcc %g", label1);
;
        bcc     L000E
;
; var = 0x00;
;
        lda     #$00
;
; goto label2;
;
        jmp     L000D
;
; var = 0x34;
;
L000E:  lda     #$34
L000D:  sta     _var
;
; }
;
        rts
.endproc
```

**Comment by mrdudz** [comment]
it'd be a MUCH better idea to just make the entire function in assembly though - instead of relying on undefined behaviour.
