### ISSUE TITLE
ser_close/ser_unload/uninstall and subsequent ser_load/ser_open causes crash on apple2

### ISSUE THREAD

**Issue by tschak909** [cc65/cc65#709]
Just as it says, The result causes a ProDOS error $01.

Code which excites this bug: 
https://github.com/tschak909/platoterm64/blob/master/src/prefs_base.c#L483

does not happen with C64/C128's swlink or c64 up2400 driver. (atari serial driver has another problem, which I will file a seperate ticket.)

-Thom

**Comment by oliverschmidt** [comment]
Either ser_load()/ser_unload() __OR__ ser_install()/ser_uninstall().

**Comment by tschak909** [comment]
if I didn't, the C64 version would crash when it would try to reload drivers. Dude, you are unbelievably flippant, sometimes.

**Comment by greg-king5** [comment]
If a loaded driver is uninstalled, then it's "forgotten".  The unload function can't see it; the function can't unload that driver.  After another driver is loaded, both of them are sitting in RAM.  But, only the second one is usable -- the first one is wasted space.

Therefore, if a driver was loaded, then it should be unloaded, not uninstalled (the unload function will uninstall internally, then free the driver's RAM).

**Comment by tschak909** [comment]
As I am insinuating then, there seems to be a problem. 

I did actually read the documentation, and followed this. Initially I was only using ser_load and ser_unload, as well as mouse_load and mouse_unload.

But, the C64 version was crashing on ser_load when I would unload the existing driver, and load another one. 

When I explicitly added the ser_uninstall call, it stopped crashing.

Now, keep in mind, I'm not irritated at @oliverschmidt's response. I'm irritated that this ticket was closed outright as superfluous.

**Comment by oliverschmidt** [comment]
> But, the C64 version was crashing on ser_load when I would unload the existing driver, and load another one.

Then there needs to be a ticket about that problem. The problem reported here talks about a problem on the Apple2. And that problem is caused by wrong API usage. There it was to be closed with the hint about the wrong API usage.
