### ISSUE TITLE
Atari: serial + tgi = instant crash on ser_open()

### ISSUE THREAD

**Issue by tschak909** [cc65/cc65#711]
The test harness here will show the problem:
https://gist.github.com/tschak909/6207eca75e6594f8868826d31ad90039

Basically, if I initialize tgi and ser together, crash ensues.

-Thom

**Comment by groessler** [comment]
I'm looking into it...

**Comment by groessler** [comment]
Thom, please check your return codes.

I saw the crash when running on an emulator where the R: device was not enabled/available.

Try this (github's "insert code" doesn't seem to work correctly here, so formatting is wrong):

/*` Guaranteed to make the computer puke. */

#include <tgi.h>
#include <serial.h>
#include <stdio.h>

static struct ser_params params = {
  SER_BAUD_2400,
  SER_BITS_8,
  SER_STOP_1,
  SER_PAR_NONE,
  SER_HS_HW
};

void main(void)
{
  unsigned int err;

  tgi_install(tgi_static_stddrv);
  tgi_init();
  tgi_clear();

  err = ser_install(atrrdev_ser);
  if (err != SER_ERR_OK) {
    printf("cannot install serial driver: %u\n", err);
    x: goto x;
    return;
  }

  ser_open(&params);

  tgi_line(0,0,320,191);

  printf("init successful...\n");
  for (;;)
    {
    }
}

**Comment by tschak909** [comment]
(for the record, am testing in the latest Altirra):

I have the 850 interface and modem attached in Devices, and have a DOS 2.0s disk with the R: handler in, and it loads successfully (I hear the long beep where the relocatable handler is pulled out of the 850), but the program still crashes.


[serial_test.zip](https://github.com/cc65/cc65/files/2272444/serial_test.zip)

Attached is an ATR with DOS 2.0S, the serial autorun.sys, and the test program.

-Thom

**Comment by groessler** [comment]
Hmm. probably something stupid, but it doesn't seem to crash here (using atari800 emulator).

**Comment by tschak909** [comment]
What load address are you using? The default gives me a memlo error, and I have to move it up.

**Comment by tschak909** [comment]
Test program works in atari800, does not work in Altirra.
PLATOTerm does not work in atari800 or Altirra (causes a crash):
[plato.zip](https://github.com/cc65/cc65/files/2272520/plato.zip)
What about for you?
-Thom

**Comment by groessler** [comment]
I didn't have time to look into it today. Sorry. I'm going to come back to your within the next days...

**Comment by tschak909** [comment]
Thanks, I'm really stumped, and I _really_ do appreciate it. :)

**Comment by groessler** [comment]
I've tried both your serial_test.atr and plato.atr, but none of them seem to crash in my Atari800 emulator. I'm just getting a black screen, though.

I had entered the debugger of the emulator, and the code it's executing looks sane, it doesn't appear to be "in the woods".

I can also test on a real computer with 850. But for this I would need some programs where I can see whether it crashed or not. Maybe just a way to gracefully exit the program.

Btw., what's the AUTORUN.SYS files for? The main programs didn't start automatically, I had to start them with "L" from the DOS menu. Are they for loading the R: driver?

**Comment by tschak909** [comment]
The autorun.sys is the Atari 850 handler.

**Comment by groessler** [comment]
Ok.

How should we continue from here? My tests seem to work, but you appear to be blocked by this issue.
I'm using the Atari800 emulator more or less exclusively because I'm working on Linux. Can you tell me what version of Atari800 you were using and on which platform? I used the in my test the latest source code of it, compiled locally.

**Comment by tschak909** [comment]
I have to think on it.

Am using Altirra in Windows (it will run in Wine under Linux, as well), as
it has a much closer parity to real hardware than Atari800 does...

Very odd... The PLATOTerm binary literally causes a CIM when loaded... are
you passing any special switches?

-Thom

**Comment by groessler** [comment]
I'm not passing any special switches I believe: 

`$ ~/atari800/atari800-git/atari800-source/src/atari800.sdl -bilinear-filter -video-accel -vsync plato.atr`

**Comment by tschak909** [comment]
Not in its current implementation. I need to put that back in. Will spin
anpther build tonight.

Code is here
Http://github.com/tschak909/platoterm64

-Thom

**Comment by tschak909** [comment]
Yeah, I've been spending the last few hours basically going into src/plato.c and adding/removing function calls until things go sideways.

Basically, looks like when tgi_init() is called after tgi_install, things go sideways, the register pokes to force a background color after the tgi_* calls don't get called, and Altirra crashes, while atari800 hangs at black.

*head-in-hands*

-Thom

**Comment by greg-king5** [comment]
Avoid POKEs if you can; they're *very* platform-specific!

For example, you should attempt to set the frame color by using a conio function:
```c
bordercolor(config.color_border);
```

**Comment by tschak909** [comment]
Same thing happening with latest git on a brand new vm. I can't seem to make tgi initialize properly, at all. :(

-Thom

**Comment by tschak909** [comment]
Tried replacing the tgi_install call with tgi_load_driver and copying the driver over. resulting binary smaller by 21 sectors (same as the tgi driver), and I can see the driver load from the disk, but it fails when the tgi_init happens, with the same crashes in both atari800 and altirra... urgh.

(FWIW, I also did a fresh install of an older version v2.15, and get the same results)

-Thom

**Comment by groessler** [comment]
To build a version locally for me, I should just check out your gitpub repo and build?

**Comment by tschak909** [comment]
Yeah.

I've managed to figure out with a liberal application of tgi_geterror that
I am failing on tgi_install with error 8 (out of resources. My binary is
24K, I should have enough with 8K to hold the hi-res screen (I am not doing
any mallocs)... sigh.

-Thom

**Comment by groessler** [comment]
Thom, as I said before, always check the return codes of the functions :-)
Now the crash doesn't appear as strange as before...

Did you set RESERVED_MEMORY for your intended graphics mode? See http://cc65.github.io/doc/atari.html#ss6.1

**Comment by oliverschmidt** [comment]
>>Did you set RESERVED_MEMORY for your intended graphics mode?
> No, I did not,
Again wrong API usage - closed.
