### ISSUE TITLE
Where is the buffer pulled from for the atari ser driver?

### ISSUE THREAD

**Issue by tschak909** [cc65/cc65#713]
Where is the buffer being allocated from for the atari ser driver? It's not immediately evident from the code.

I'm running into issues where the serial driver isn't initializing when the official atari 850 handler is being loaded, and I need to see if I need to shuffle some bits around.

-Thom

**Comment by polluks** [comment]
Well, the buffer is hidden in the R: device
http://www.atarimania.com/documents/atari-850-interface-module-technical-manual.pdf

**Comment by tschak909** [comment]
That's what I thought, but I'm getting very weird behavior and interactions
when I start combining tgi and ser together, and I'm suspecting it's
because of memory collisions.

-Thom

**Comment by polluks** [comment]
Yeah, I suppose you are the first one who's combining tgi and ser on Atari. Good luck! :)

**Comment by tschak909** [comment]
@groessler  okay, so I've checked in the absolute latest code, and tried as hard as I could to make everything fit nicely. It seems to, Screen initializes, terminal starts.

If I use  the stubbed R: handler in Altirra, the terminal works. But real Atari 8-bits don't work like this, they need their handler.

If I set to full 850 emulation (which requires the handler) and load the handler, things go south when ser_open happens, so there is DEFINITELY an issue of some sort with ser_open and tgi (and possibly mouse). 

The plato.c main() can have calls quickly commented out to test various sections.

I'm at a loss here... :(

you can build with make and make dist-atari, which will make an ATR (using dir2atr) with all the bits needed, the drivers, everything.

-Thom

**Comment by groessler** [comment]
Your version doesn't compile for me:


[blasi:\~/atari800/platoterm64]$ make TARGETS=atari
cl65 -t atari -c --create-dep obj/atari/screen_base.d -Oris --static-locals -o obj/atari/screen_base.o src/screen_base.c
cl65 -t atari -c --create-dep obj/atari/protocol.d -Oris --static-locals -o obj/atari/protocol.o src/protocol.c
cl65 -t atari -c --create-dep obj/atari/prefs_base.d -Oris --static-locals -o obj/atari/prefs_base.o src/prefs_base.c
cl65 -t atari -c --create-dep obj/atari/terminal.d -Oris --static-locals -o obj/atari/terminal.o src/terminal.c
cl65 -t atari -c --create-dep obj/atari/config_base.d -Oris --static-locals -o obj/atari/config_base.o src/config_base.c
cl65 -t atari -c --create-dep obj/atari/keyboard_base.d -Oris --static-locals -o obj/atari/keyboard_base.o src/keyboard_base.c
cl65 -t atari -c --create-dep obj/atari/plato.d -Oris --static-locals -o obj/atari/plato.o src/plato.c
cl65 -t atari -c --create-dep obj/atari/io_base.d -Oris --static-locals -o obj/atari/io_base.o src/io_base.c
cl65 -t atari -c --create-dep obj/atari/touch_base.d -Oris --static-locals -o obj/atari/touch_base.o src/touch_base.c
cl65 -t atari -c --create-dep obj/atari/terminal_char_load.d -Oris --static-locals -o obj/atari/terminal_char_load.o src/atari/terminal_char_load.c
cl65 -t atari -c --create-dep obj/atari/io.d -Oris --static-locals -o obj/atari/io.o src/atari/io.c
src/atari/io.c(33): Error: Undefined symbol: `false'
src/atari/io.c(49): Error: Undefined symbol: `false'
src/atari/io.c(68): Error: Undefined symbol: `false'
src/atari/io.c(78): Error: Undefined symbol: `false'
Makefile:292: recipe for target 'obj/atari/io.o' failed
make: *** [obj/atari/io.o] Error 1
[blasi:~/atari800/platoterm64]$

**Comment by tschak909** [comment]
whoop, sorry, last moment change needed stdbool.h added to atari/io.h :)

**Comment by tschak909** [comment]
it's fixed now.

**Comment by tschak909** [comment]
Running an SIO monitor on my bench PC here, and besides the initial handler load from device 50 (R1:) there is no further access to R1:, so the handler seems to be crashing immediately upon ser_open.

**Comment by tschak909** [comment]
...is it crashing because it can't find a free IOCB? :/

-Thom

**Comment by groessler** [comment]
And, your test program doesn't call ser_close(). So after you had run your prog a few times there won't be any IOCB available anymore. Tststs...

**Comment by tschak909** [comment]
Please do not use Atari800 emu. Sigh. Its R: handling is nowhere near even remotely close to reality. Altirra handles the 850 as close to real hardware as one can in emulation.

I am testing this on an Atari 800 with a connected Atari 850., booting the resulting disk image over APE. 

I am also testing this on Altirra, both of which crash.

I'm running this by building the binary with make, and then running make dist-atari, which calls ataridir to build the distribution disk image.

[plato.zip](https://github.com/cc65/cc65/files/2287393/plato.zip)

Phaeron, who writes Altirra, had this to say:

"One thing I noticed trying to get this to work: there is a deferred VBI handler chaining through a vector table at $6F23. Looks like this makes the program fail under SpartaDOS X when extended memory is used."

**Comment by tschak909** [comment]
I've made a video demonstrating:
https://youtu.be/L3NgyudilOk

-Thom

**Comment by groessler** [comment]
It looks like your R: driver is bad. If you follow history before the crash, you'll notice that ser_put calls CIO function PUTCHR which crashes in the ROM when it wants to call the PUTCHR function of the R: handler.

**Comment by tschak909** [comment]
This is just a handler loader, which works as is under MyDOS. which is
ironic, because this is the loader on Atari's DOS disk.

**Comment by polluks** [comment]
BTW I'm missing src/atari/key.h

**Comment by tschak909** [comment]
committed. Keep in mind, the keyboard is still being mapped, so most keys
will not trigger, yet. I am working on that, right now.

You will also see that a handler installer has been added to the
distribution media, to select the appropriate RS232 handler.

-Thom

**Comment by groessler** [comment]
This simple program crashes in Altirra. I will only at Thursday have access to my read Atari to double check.
[sertst.tar.gz](https://github.com/cc65/cc65/files/2288793/sertst.tar.gz)

**Comment by tschak909** [comment]
Keyboard mapped enough for full use, build here: 
[platoterm-20180814.zip](https://github.com/cc65/cc65/files/2289003/platoterm-20180814.zip)

**Comment by tschak909** [comment]
@groessler sertst.com crashes on real hardware (Atari 800) under dos 2.0S and 2.5.
mydos on same hardware complains about memlo being too low. (my estimate is by about $0200 bytes)

-Thom

**Comment by tschak909** [comment]
[plato-20160816.zip](https://github.com/cc65/cc65/files/2294827/plato-20160816.zip)
Latest builld.

-Thom

**Comment by groessler** [comment]
@tschak909: You wrote in a previous email (or maybe AtariAge) that your program crashes in the serial routines on MyDOS. Your latests posts on AtariAge indicate that you've got it to work with MyDOS. What did you change?

**Comment by tschak909** [comment]
*rewinds-brain* :)

I can't get the routines to work at all in DOS 2.0S or 2.5. Straight up
crash. boom splat on ser_open.

I managed to get the routines to work well enough in MyDOS by calculating a
high enough start address (I am currently at $2600).
And my distribution disk that I am using now, is MyDOS 4.53/4 which loads
the requested handler, and then boots PLATOTerm.
This also made SpartaDOS 2.3, 3.2, and RealDOS, and all the close cousins
work,
SpartaDOS X does not work because of the issues we've run into discussed
elsewhere.

I was initially targeting DOS 2.0 because that was what I was intending to
use for my distribution disk. But since, MyDOS works, that's not really an
issue anymore.

-Thom

**Comment by groessler** [comment]
Hmm, this somehow "rings a bell" and/or gives me a "deja-vu experience".

Last week when I tried my sertst program I got mixed results. Sometimes it worked, sometimes it crashed. Where "sometimes" doesn't mean running the same program the same way multiple times, but running once from D1: and then from D2:, and using different DOSes.

My "guts feeling" back then was that the driver might not set MEMLO correctly. But that's a "guts feeling" which cannot be described for others to reproduce. But, if your "fix" was to increase the load address of the program, this is another hint into that direction.

OTOH, if the driver doesn't set MEMLO correctly, probably I shouldn't be the first one to notice (after ~30 years). I'm going to run some more tests in the next days to find out the problem.

regards,
chris

**Comment by polluks** [comment]
Use the source!
http://www.atarimuseum.com/archives/files/computers/8bits/peripherals/850.zip

**Comment by groessler** [comment]
@tschak909, I think this was resolved by having a "MEM.SAV" file. If this this is indeed the case, please close the issue.

**Comment by tschak909** [comment]
Yup. Pretty much. closing. :)
