### ISSUE TITLE
WDM not supported by ca65

### ISSUE THREAD

**Issue by fadden** [cc65/cc65#715]
The table of instructions in src/ca65/instr.c doesn't have WDM in it.  This causes assembly to fail when it encounters something like "WDM $00":

    Checkcc.S(3): Error: `:' expected
    Checkcc.S(3): Error: Unexpected trailing garbage characters

The disassembler sources know about WDM, treating it similarly to COP.  src/da65/opc65816.c has:

```
    {   "cop",  2,  flNone,                   OH_Implicit              }, /* $02 */
   ....
    {   "wdm",  2,  flNone,                   OH_Implicit              }, /* $42 */
```

I would argue that the assembler should treat it the same way.

**Comment by polluks** [comment]
```
000000r 1                       .setcpu "65816"
000000r 1  A9 11                lda #$11
000002r 1  00                   brk
000003r 1  EA                   nop
000004r 1  00 22                brk $22
000006r 1  02 33                cop $33
000008r 1  42 44                wdm $44
00000Ar 1  60                   rts
00000Ar 1               
```
