### ISSUE TITLE
atari: PLATOTerm crashes on startup, on systems with more than 128K of RAM.

### ISSUE THREAD

**Issue by tschak909** [cc65/cc65#718]
It took quite a while to narrow this down, but...

Phaeron (Altirra's lead developer) mentioned that when PLATOTerm starts, it chains itself through a deferred vertical blank interrupt, which crashes on systems that have more than 128K of RAM. I am not explicitly creating an interruptor, so where is this coming from? I don't see an IRQ in the serial driver, so I'm confused, where is this coming from?

[plato-crashes320k.zip](https://github.com/cc65/cc65/files/2295825/plato-crashes320k.zip)

-Thom

**Comment by polluks** [comment]
cc65 does not support any Atari memory >128K, so it seems not to be compiler related. Can you more cut down the problem?

**Comment by groessler** [comment]
On 08/17/18 11:54, Stefan wrote:
>
> cc65 does not support any Atari memory >128K, so it seems not to be 
> compiler related. Can you more cut down the problem?
>


That's not 100% correct. cc65 "atari" target uses 48K, "atarixl" target 
additionally the RAM under the ROM, so 64K. To use more memory
the extended memory driver *.emd is required.


Thom, just posting a binary is not the proper way to get support. A 
problem report should include

- pointer to the source code, along with build instructions
- step by step procedure how to reproduce the problem
- a compiled binary is handy, but not strictly required


I've compiled plato a few days ago, and looking at the map file I see 
that callirq.o is compiled in. I guess it's coming from the
serial driver framework.


Still, please explain why having a VBI handler should be harmful on a 
system with more than 128K of memory.


regards,
chris

**Comment by tschak909** [comment]
Phaeron said exactly:

"One thing I noticed trying to get this to work: there is a deferred VBI handler chaining through a vector table at $6F23. Looks like this makes the program fail under SpartaDOS X when extended memory is used."

So basically, e.g. in Altirra (or a real machine with more than 128K, e.g. a 320K RAMBO XL), if you try to run the main binary (AUTORUN.AR2), the program will immediately crash.

**Comment by tschak909** [comment]
from what I see in the runtime, there should be zero reason for IRQs to even be enabled:

* Serial driver does not use them
* a few mouse drivers do use them, but I've commented out mouse support as there are issues.

**Comment by tschak909** [comment]
I believe this can be closed.
-Thom
