### ISSUE TITLE
tgi_outtext does not work.

### ISSUE THREAD

**Issue by tschak909** [cc65/cc65#720]
I decided to try tgi_outtext using the test code that works on the apple2 target:

// cl65 -t apple2 -C apple2-hgr.cfg hgrtest.c werner.s

#include <tgi.h>
#include <conio.h>

#pragma code-name (push, "LOWCODE")

void say (const char* text)
{
    tgi_setcolor (TGI_COLOR_BLACK);
    tgi_outtextxy (41, 33, text);
}

#pragma code-name (pop)

void main (void)
{
    tgi_install (a2_hi_tgi);
    tgi_init ();
    cgetc ();

    say ("Hi Dude !");
    cgetc ();

    tgi_uninstall ();
}

I understand that werner.s is a dhgr image that gets loaded into the reserve space, but the text should still be visible, and there is a routine for it in the atari lib (which uses the ROM font at E000), but... it doesn't display anything.

-Thom

**Comment by oliverschmidt** [comment]
There seems to be no momentum to come up with an answer to this question.
