### ISSUE TITLE
Apple II: ftell() returns 512 at beginning of file

### ISSUE THREAD

**Issue by ppelleti** [cc65/cc65#722]
I am finding that immediately after I open a file for reading, `ftell()` returns `512` when I would expect it to return `0`.

This is on an unenhanced Apple //e running ProDOS 1.9.

Here is the test program I am using:

```
/* cl65 -W-unused-param -t apple2 -C apple2-system.cfg -o ftell.system test-ftell.c */

#include <stdio.h>
#include <conio.h>

int main (int argc, char **argv) {
    const char *fname = "/ram/foo";
    FILE *f;
    long pos;

    f = fopen (fname, "w");
    if (!f)
        goto err;

    fprintf (f, "Hello, World!");
    fclose (f);

    f = fopen (fname, "r");
    if (!f)
        goto err;

    pos = ftell (f);
    printf ("At offset %lu\n", pos);

    fclose (f);
    cgetc ();
    return 0;

 err:
    printf ("Couldn't open %s\n", fname);
    cgetc ();
    return 1;
}
```

This program prints `AT OFFSET 512`, when I would expect it to print `AT OFFSET 0`.

**Comment by ppelleti** [comment]
Looking at `libsrc/apple2/lseek.s`, it looks like the `lseek` function does not return a value, but it should.  (`ftell` in `libsrc/common/ftell.c` returns the value returned by `lseek`.)

I'll work on putting together a pull request for this.

**Comment by oliverschmidt** [comment]
> Looking at libsrc/apple2/lseek.s, it looks like the lseek function does not return a value, but it should. 

Thanks for the analysis.

> I'll work on putting together a pull request for this.

:-)
