### ISSUE TITLE
[atari5200][possible bug][joystick] It detects fire and down

### ISSUE THREAD

**Issue by Fabrizio-Caruso** [cc65/cc65#729]
It seems that the Atari5200 was broken some time ago.

Under Altirra emulator, it correctly detects the fire button and starts the game as expected
but in game, it just detects the down movement.

Has something been changed in the last months?

**Comment by groessler** [comment]
Not that I'm aware of.

**Comment by Fabrizio-Caruso** [comment]
I have not tested for quite some time. So, I cannot tell you when it was broken. 
The joystick code on my side is the same as for the rest of the CC65 targets. So I am assuming the problem is in CC65 or in the emulator settings.
I was once able to load it under Atari800Win but I am not longer able. So I am stuck with Altirra, which seems to detect the down movements only (and fire).

**Comment by Fabrizio-Caruso** [comment]
It is an Altirra issue (most probably my incompetence with Altirra)
