### ISSUE TITLE
[Atari5200][question] How to set the 5 colors and do graphics?

### ISSUE THREAD

**Issue by Fabrizio-Caruso** [cc65/cc65#730]
I would like to improve graphics in the Atari 5200 version of my game.
For the Atari 8-bit I can easily set colors with the provided APIs, which do not seem available for the Atari 5200:
```
	_graphics(GRAPHICS_MODE);
	_setcolor_low(0, TGI_COLOR_RED);
	_setcolor_low(1, TGI_COLOR_WHITE);
	_setcolor_low(2, TGI_COLOR_CYAN); 	
	_setcolor_low(3, TGI_COLOR_BROWN);
	_setcolor_low(4, TGI_COLOR_BLACK);
```

I could redefine the characters with
```
	extern char _FONT_START__[];
	unsigned char *CHBAS = (unsigned char *)0x2f4;

	memcpy(_FONT_START__, (void *)0xE000, 512);
	REDEFINE_AT(_FONT_START__);
	*CHBAS = ((int)_FONT_START__ >> 8);  /* enable the new font */		
```

How can I do something similar with the Atari5200.
The two systems are very similar. I thought I could use the same APIs or at least something similar.

**Comment by groessler** [comment]
> The two systems are very similar. I thought I could use the same APIs or at least something similar.

The two systems are a "computer" and a "video game console". They are only similar in that they are using the same hardware chips for graphics and sound. The "computer" has (IIRC) a 10K BIOS ROM, and the "video console" has a 2K ROM.

I had implemented the "setcolor" functions as a simple path for someone which wants to convert an AtariBASIC computer program (SETCOLOR function there). Since the 5200 doesn't have a BASIC, they aren't available in the 5200 target.

I think you could copy the the "setcolor.s" source file from cc65's "atari" lib to your project and compile it for atari5200. This might work (fingers crossed).

The "graphics" function (also an AtariBASIC) function won't work on the 5200 since the ROM doesn't provide that functionality. If you want to setup a different screen configuration, you need to create a custom display list and screen memory. See conioscreen.s in libsrc/atari5200 for how it is done there.

I think your question about redefining characters had been answered on AtariAge.

regards,
chris

**Comment by Fabrizio-Caruso** [comment]
Thanks for your reply!
I would like to use the CC65 default video Atari 5200 mode. 
So for the Atari 5200 I can avoid to switch video mode.
I just want to choose the 5 colors and keep all the rest as is. 

As far as the user-defined characters are concerned, I got some answers from the AtariAge forum but I still have no idea how to convert the Atari 800 code into Atari 5200 code since I miss many details like how should I replace _FONT_START__ for the Atari 5200?
In the Atari 800 code, rom definitions are copied at _FONT_START__. This is what I did, following the suggestion from some of the CC65 authors. I guess _FONT_START__ is defined by the linker configuration. I don't understand why the the new font definition are supposed to be place at this location. What should I do for the Atari 5200?

**Comment by groessler** [comment]
@Fabrizio-Caruso, I don't know where your __FONT_START__ is coming from. It's nowhere in the cc65 source base. Do you use a local linker script which defines a "FONT" memory area or segment?

**Comment by Fabrizio-Caruso** [comment]
@groessler, yes indeed:
```
FEATURES {
    STARTADDRESS: default = $2000;
}
SYMBOLS {
    __EXEHDR__:          type = import;
    __SYSTEM_CHECK__:    type = import;  # force inclusion of "system check" load chunk
    __AUTOSTART__:       type = import;  # force inclusion of autostart "trailer"
    __STACKSIZE__:       type = weak, value = $0800; # 2k stack
    __STARTADDRESS__:    type = export, value = %S;
    __RESERVED_MEMORY__: type = weak, value = $0000;
}
MEMORY {
    ZP:         file = "", define = yes, start = $0082, size = $007E;

# file header, just $FFFF
    HEADER:     file = %O,               start = $0000, size = $0002;

# "system check" load chunk
    SYSCHKHDR:  file = %O,               start = $0000, size = $0004;
    SYSCHKCHNK: file = %O,               start = $2E00, size = $0300;
    SYSCHKTRL:  file = %O,               start = $0000, size = $0006;

# "main program" load chunk
    MAINHDR:    file = %O,               start = $0000, size = $0004;
    MAIN:       file = %O, define = yes, start = %S + $0200,    size = $BC20 - __STACKSIZE__ - __RESERVED_MEMORY__ - %S - $0200;
    TRAILER:    file = %O,               start = $0000, size = $0006;

# font area
    FONT:       file = "", define = yes, start = %S,    size = $0200;
	
}
SEGMENTS {
    ZEROPAGE:  load = ZP,         type = zp;
    EXTZP:     load = ZP,         type = zp,                optional = yes;
    EXEHDR:    load = HEADER,     type = ro;
    SYSCHKHDR: load = SYSCHKHDR,  type = ro,                optional = yes;
    SYSCHK:    load = SYSCHKCHNK, type = rw,  define = yes, optional = yes;
    SYSCHKTRL: load = SYSCHKTRL,  type = ro,                optional = yes;
    MAINHDR:   load = MAINHDR,    type = ro;
    STARTUP:   load = MAIN,       type = ro,  define = yes;
    LOWCODE:   load = MAIN,       type = ro,  define = yes, optional = yes;
    ONCE:      load = MAIN,       type = ro,                optional = yes;
    CODE:      load = MAIN,       type = ro,  define = yes;
    RODATA:    load = MAIN,       type = ro;
    DATA:      load = MAIN,       type = rw;
    INIT:      load = MAIN,       type = rw,                optional = yes;
    BSS:       load = MAIN,       type = bss, define = yes;
    AUTOSTRT:  load = TRAILER,    type = ro;
	FONT:      load = FONT,       type = rw,                optional = yes;
}
FEATURES {
    CONDES: type    = constructor,
            label   = __CONSTRUCTOR_TABLE__,
            count   = __CONSTRUCTOR_COUNT__,
            segment = ONCE;
    CONDES: type    = destructor,
            label   = __DESTRUCTOR_TABLE__,
            count   = __DESTRUCTOR_COUNT__,
            segment = RODATA;
    CONDES: type    = interruptor,
            label   = __INTERRUPTOR_TABLE__,
            count   = __INTERRUPTOR_COUNT__,
            segment = RODATA,
            import  = __CALLIRQ__;
}
```

**Comment by Fabrizio-Caruso** [comment]
Should I then do something similar for the Atari5200?
I was considering something like:
```
void set_udg(void)
{
	
	unsigned char *CHBASE = (unsigned char *)0xD409;

	memcpy(_FONT_START__, (void *)0xF800, 512);
	
	/* modify your font at _FONT_START__, etc, then set the new font: */		
	REDEFINE_AT(_FONT_START__);
	
	*CHBASE = ((int)_FONT_START__ >> 8);  /* enable the new font */		
}
```

**Comment by Fabrizio-Caruso** [comment]
1k? I was hoping for a 512 byte boundary. 
I will need to put it at $3C00-$3DFF and waste the last 512 bytes? 
I was hoping for $3E00-$3FFF.

**Comment by groessler** [comment]
Hmm, yes, it's already late. 512-byte boundary should work, you're right.

**Comment by Fabrizio-Caruso** [comment]
@groessler So I place the fonts at $3E00 but 
https://cc65.github.io/doc/atari5200.html
says that that area is used for the text screen.
What is wrong?

**Comment by Fabrizio-Caruso** [comment]
Somewhere else I read that the screen memory is the area pointed to by SAVMSC ($1B)...

**Comment by Fabrizio-Caruso** [comment]
The font boundary is indeed 1k.
So I will have:
$3800-39FF: 512 bytes of font definitions
$3A00-3BFF: 512 unused bytes

$3E00-$3E1F: 32 unsused bytes
$3E20-... used for the screen (SAVMSC points here )

**Comment by Fabrizio-Caruso** [comment]
I got it!
I only need to figure out how to choose the 5 colors!
![atari5200](https://user-images.githubusercontent.com/29057615/44452261-603dc980-a5f6-11e8-8025-cf7e811917ce.jpg)

**Comment by Fabrizio-Caruso** [comment]
The setcolor code is not usable for the ATARI 5200 because the registers are mapped elsewhere but I found the locations of the registers and so I have managed to set the colors!

THANKS everyone! 
![atari5200_color](https://user-images.githubusercontent.com/29057615/44455790-33da7b00-a5ff-11e8-89bb-3f4fa96547af.jpg)

**Comment by Fabrizio-Caruso** [comment]
How do I prevent the attract/sleep mode on the Atari 5200?
On the Atari 8-bit, I do POKE(77,0).
Is POKE(4,0) the Atari5200-equivalent solution?

**Comment by groessler** [comment]
Why do you want to disable attract mode?

**Comment by Fabrizio-Caruso** [comment]
Because neither the Atari nor the Atari 5200 joystick/keyboard code in CC65 is resetting the sleep mode. This is sort of a bug/feature in CC65. If you don't do this, the console will enter attract/sleep mode after about 9 minutes. The console should only enter attract mode if no input is enter for 9 minutes.

**Comment by peteym5** [comment]
The 5200 has a different memory layout. Only thing in the same location are the Antic chip registers. What I did was made two separate header and equates files for the two separate systems. In 8-bit headers. ATRACT = 0x5D (or 77).  5200 header will have ATRACT = 0x04 (or 4). That way if a program is compiled to 8-bit or 5200 a POKE (ATRACT,0) or LDA #0 ... STA ATRACT will reset reset the ATRACT counter.
