### ISSUE TITLE
[nes][CHARS][question] How can I select a different charset then the default one?

### ISSUE THREAD

**Issue by Fabrizio-Caruso** [cc65/cc65#732]
I am trying to redefine the tiles for the nes target.
By looking at the cfg file it seems that the CHARS segment is filled with the default data (embedded in nes.lib?). I would like to use my own CHARS segment.

Can I override the default chars by linking with a file with a new definition for CHARS?
Something like:
```
		.segment "CHARS"
		.export _Charset
_Charset:
.byte ...
...
```

**Comment by Fabrizio-Caruso** [comment]
It works! (sort of)
I don't understand how the tiles are encoded but I may figure it out.

**Comment by Fabrizio-Caruso** [comment]
I am no longer sure it is really working and doing what I was expecting, i.e., replacing the segment with the default.
It looks like the rom characters are still there, somehow because if I disable the screen before setting the color attributes and then re-enable the screen, I get back the rom characters.
What is the correct way to tell the compiler/linker to use a different segment for the characters?
```
	PPU.control = 0;
	PPU.mask = 0;
(set some color attributes here)
	PPU.vram.address = 0;
	PPU.vram.address = 0;
	PPU.scroll = 0;
	PPU.scroll = 0;	
	PPU.control = 0x90;
	PPU.mask = 0x1e;
```

**Comment by Fabrizio-Caruso** [comment]
The problem comes from PPU.control = 0x90 which should rather be PPU.control = 0x80 in order to switch to the correct page. 
For some reason one page gets the default tiles.

**Comment by bbbradsmith** [comment]
If the library you're using fills in the "CHARS" segment already you can't do anything but append data to it. You seem to have solved this by placing data in the unused second half of the 8k CHR space and switching the PPU to use that second page for the background tiles instead?

Alternatively, if you do want to replace it but continue to use the default lib, you could make a modified copy of nes.cfg that does the following:
- Create a new memory region with file="" so it doesn't output.
- Redirect the CHARS segment to the new memory region.
- Create a new segment that gets placed where CHARS was previously (ROM2)
- Place your new tiles within that segment.

**Comment by Fabrizio-Caruso** [comment]
Thanks
