### ISSUE TITLE
[nes][tile][question] Is there a tile editor for NES that supports .s (.byte) files?

### ISSUE THREAD

**Issue by Fabrizio-Caruso** [cc65/cc65#733]
I am trying to edit the neschar.inc file to create my own tiles for the NES.
The neschar.inc is just a file with .byte definitions.

Is there a NES tile editor editor that supports this kind of format?
I mean something like CharPad.

**Comment by oliverschmidt** [comment]
I think questions no directly related to the code in this repo should rather go to the cc65 dev mailing list.

**Comment by Fabrizio-Caruso** [comment]
@oliverschmidt sorry, you are right

**Comment by oliverschmidt** [comment]
Thanks for your understanding :-)
