### ISSUE TITLE
[pce][characters][question] How does CC65 handle PCE font set? How to modify it?

### ISSUE THREAD

**Issue by Fabrizio-Caruso** [cc65/cc65#734]
I understand that the PCE target in CC65 differs in the way it loads the font set from the way the NES target does, by not using any linker config "magic". This remains too "magic" for me. 
Where are the tiles stored? Is it in RAM?
Can I modify them in my code? On which locations?

**Comment by polluks** [comment]
PCE and NES use both VROM (CHR-ROM) as far as I know.

**Comment by Fabrizio-Caruso** [comment]
NCE target imports neschars.inc which is loaded into the segment CHARS which one can override by linking a new segment (just a header that introduces the CHARS segment + .byte lines)

How can I do something similar with the PCE target?

**Comment by polluks** [comment]
"This effect is used even more intensely in platforms with dual-ported VRAM (TurboGrafx-16, Game Boy Advance) [...]"
https://wiki.nesdev.com/w/index.php/CHR_ROM_vs._CHR_RAM#Applications_2

**Comment by Fabrizio-Caruso** [comment]
@polluks ok, my question is how do I select a different font/tile set?

**Comment by oliverschmidt** [comment]
@Fabrizio-Caruso: Is your question still open?

**Comment by Fabrizio-Caruso** [comment]
@oliverschmidt I got some answers... but I am not sure I understand what I need to do.
@Does it mean that I can pass a different vga.inc file to the compiler?
https://github.com/cc65/cc65/blob/master/libsrc/pce/vga.inc 
I need to give it a try.
Why are the characters in a .inc file and not a .s file?

**Comment by polluks** [comment]
"inc" is just an informal hint for a data file without code.

**Comment by Fabrizio-Caruso** [comment]
@polluks, with other targets this is done through a .s file (https://github.com/cc65/cc65/blob/master/libsrc/nes/neschar.s), 
which I can just replace by passing an alternate one to the compiler.
Can I do the same thing with a .inc file? How?

**Comment by polluks** [comment]
It's just a hint: include this file, it's not standalone. We could rename the NES one.

**Comment by Fabrizio-Caruso** [comment]
@polluks  ok, thanks. I am going to add the .inc file to the list of source files. I thought it would not be possible to pass it to the compiler as I do with the equivalent .s NES file. Maybe you mean I need to include it with an include directive inside a .h source file?

**Comment by oliverschmidt** [comment]
> Maybe you mean I need to include it with an include directive inside a .h source file?

No. See https://cc65.github.io/doc/ca65.html#ss11.67 for instructions.

**Comment by greg-king5** [comment]
Only a "standalone" file can be replaced by you.  Currently, you need to duplicate the code of "libsrc/pce/conio.s".  Then, you need to substitute your own `.include` file, assemble it, and link the object file into your program.

In order to make the PCE library more like the NES one, we will need to change "vga.inc" into "vga.s", export a label (e.g., "pce_font"), and make "conio.s" import that label instead of including a file.  After that fix, you'll be able to replace the font simply by linking your own version of "vga.o".

**Comment by Fabrizio-Caruso** [comment]
@greg-king5  then the .s NES solution is much more convenient. Please keep the .s file for the NES target. I hope the PCE gets the same easy to use solution. It makes tile graphics so easy to implement in plain C.

**Comment by oliverschmidt** [comment]
Fixed with https://github.com/cc65/cc65/commit/ba0ef5938d267dc47ca6d30af18b596190b4f932.

**Comment by greg-king5** [comment]
> @greg-king5, then the .s NES solution is much more convenient. Please keep the .s file for the NES target. I hope the PCE gets the same easy-to-use solution. It makes tile graphics so easy to implement in plain C.

Done by commit ba0ef5938d267dc47ca6d30af18b596190b4f932.  You can define (and export) `_pce_font:` in Assembly, or  `pce_font[]` in C.

https://github.com/cc65/cc65/blob/master/libsrc/pce/vga.s is the source of the standard PCE font.

**Comment by Fabrizio-Caruso** [comment]
@greg-king5  THANKS a lot!

**Comment by polluks** [comment]
Maybe we should officially add the variables to the text screen section of the documentation?
Gamate is also wating ;-)

**Comment by Fabrizio-Caruso** [comment]
Indeed the Gamate target has the same "issue".
By looking at https://github.com/cc65/cc65/commit/ba0ef5938d267dc47ca6d30af18b596190b4f932
I could try to apply the same changes. I am not sure it will work, though. I need to give it a try.

**Comment by Fabrizio-Caruso** [comment]
@oliverschmidt, @greg-king5  I have just made the PR #1264 that does the same thing on the gamate target.
