### ISSUE TITLE
Atari (computers and 5200) should disable "attract mode" on user input

### ISSUE THREAD

**Issue by groessler** [cc65/cc65#736]
Only keyboard input currently disables attract mode (done by the BIOS). Joystick and mouse inputs should also disable attract mode.

**Comment by groessler** [comment]
This is a follow-up issue of #731.

**Comment by groessler** [comment]
An outline what I'm intending to do:

- In the joystick drivers, add a check if the input changed in the READJOY function. If input changed, disable attract mode.
- In the mouse drivers, add a similar check to the interrupt routine.

Since the joystick driver don't use interrupt, this has the (maybe not immediately obvious) effect, that if two joysticks are connected, but the program just queries one joystick, moving the other joystick won't exit attract mode.

**Comment by oliverschmidt** [comment]
> An outline what I'm intending to do: [...]

Great, thanks for sharing :-)

> Since the joystick driver don't use interrupt, this has the (maybe not immediately obvious) effect, that if two joysticks are connected, but the program just queries one joystick, moving the other joystick won't exit attract mode.

At least to me this is just what I'd expect: As far as I understand the attract mode still clearly shows the program which is running - in contrast to a usual screen saver. So to me it's obvious that the attract mode mode is quit by interacting with the running _program_ (in one of the ways the program accepts interaction) and not by interacting with the _system_.

**Comment by Fabrizio-Caruso** [comment]
@groessler Thanks a lot for the fix!
