### ISSUE TITLE
[ATARI5200][joystick][bug/question] Digital vs Analog?

### ISSUE THREAD

**Issue by Fabrizio-Caruso** [cc65/cc65#737]
The Atari5200 joystick driver seems to work fine under Atari800Win but fails miserably under Altirra 3.00 and 3.10 (which is supposed to be more accurate). Has anyone tested on real hardware?

Under Altirra the fire button is correctly recognized but in-game the driver just detects a down movement.

If I have understood well, the Atari 5200 console uses by default analog stick (values read from paddle ports). Is the CC65 joystick driver reading from the same ports (with some threshold to decide left vs right and up vs bottom)?

**Comment by groessler** [comment]
I did the original implementation and I only used the Atari800 emulator. I did have/still have a real 5200, but had no way back then to create a cartridge to test on real hardware.

I now have a flash cart and should be able to run programs on a real 5200. In fact, I think I have everything needed, also a NTSC->FBAS receiver, so I could hook it up to my TV to test. This is on my TODO list :-)

One person in the AtariAge thread mentioned that there exist another game for the 5200 written with cc65. I guess/hope, they have tested on real hardware, too.

But anyway, I'm going to test it. Not tomorrow, but also not in months or years, but days or weeks...

**Comment by groessler** [comment]
Of course does it read the POT values. See libsrc/atari5200/joy/atr5200std.s.

Maybe ask the other developer if he did something "special" and whether he tested on real hardware.

**Comment by Fabrizio-Caruso** [comment]
@groessler then, if there is a real issue, it may just be a calibration one: we would need to adjust the threshold. In my game, the character just goes down as if the down vs up pot would have a value beyond the down threshold.

It could be just a stupid configuration problem with Altirra. I have struggled with it and have not been able to get my game to work.

Could you please give it a try with my rom or any other test code?
https://github.com/Fabrizio-Caruso/CROSS-CHASE/releases/download/BombDance/FULL_atari5200.rom

**Comment by Fabrizio-Caruso** [comment]
@groessler It may be a calibration problem. Maybe some sort of software calibration initialization at driver startup is necessary. Trying to guess what may wrong...

**Comment by groessler** [comment]
"calibration problem" in an emulator? From guts feeling this doesn't appear to be the issue. But of course, the definitive answer will come from the test on the real hardware.

**Comment by groessler** [comment]
Did you try your Altirra setup with some other game? One of the "readily downloadable" classic 5200 games? If such a game works the problem probably is in the cc65 joystick driver.

**Comment by Fabrizio-Caruso** [comment]
@groessler Altirra works OK with other games (e.g., Bezerk).
The user "phaeron" says that it is a calibration issue because the bit 2 of the CONSOL is not set:
"...Bit 2 needs to be set to turn off trackball calibration mode so that the joystick can be read...".
So, there is something else that has to be done when initializing the joystick in order to have it work correctly.

**Comment by oliverschmidt** [comment]
> I think I have everything needed, also a NTSC->FBAS receiver, so I could hook it up to my TV to test. This is on my TODO list :-)

> I'm going to test it. Not tomorrow, but also not in months or years, but days or weeks...

Thanks for your dedication !

**Comment by groessler** [comment]
@Fabrizio-Caruso, could you link your program with the attached object file and check if it makes a difference?
[atr5200std-joy.zip](https://github.com/cc65/cc65/files/2318358/atr5200std-joy.zip)

**Comment by Fabrizio-Caruso** [comment]
@groessler , IT WORKS! :-)
Tested ONLY joystick behavior (no sleep mode) under 
OK: Altirra 3.10 64-bit 
OK: Atari800Win 4.0

What was wrong?

**Comment by groessler** [comment]
> What was wrong?

Exactly what you've cited from phaeron.

> Tested ONLY joystick behavior (no sleep mode)

No change here. This will come later.

This change will be part of the next snapshot. From then on you need not, and in fact, should not, manually link anymore the file I had sent to you.

**Comment by Fabrizio-Caruso** [comment]
@groessler 
Should we clone this issue? Do we wait for a test on the real hardware?

**Comment by groessler** [comment]
@Fabrizio-Caruso: who is "we"? "I" am waiting for you to close the issue after verification that the latest snapshot works without the file I had sent to you.
I cannot give an ETA for the test on real hardware right now. But I'm quite positive that it will work (Altirra is really great at emulating all bits and pieces). When powering up the real hardware my main goal is to implement support for the number pads on the joysticks, and I will definitively notice this problem in case it's still there...

**Comment by Fabrizio-Caruso** [comment]
Ok, then I close the issue. It works fine on both emulators.
