### ISSUE TITLE
plus4: cbm_kernal.inc

### ISSUE THREAD

**Issue by polluks** [cc65/cc65#747]
The include simply defines the C16 labels but ignores the plus4 kernel wrappers.

**Comment by oliverschmidt** [comment]
As you maybe guess I have no idea what you want to express - but I hope that the CBM gurus can...

**Comment by mrdudz** [comment]
i'd have seperate symbols for the wrapped functions... else a program that expects to call directly might not work as expected.

**Comment by spiro-trikaliotis** [comment]
@mrdudz, this seems to be the best solution.

**Comment by groessler** [comment]
I don't know enough about C16 and Plus4, but look at the "atari" vs. "atarixl" targets. On atarixl the ROM/KERNAL has to be banked in as well before calling it.
For example, CIOV (the most used ROM entry point), on atarixl it's mapped to a wrapper function, and on atari to the real address. This way, code which just want to call it doesn't need to know whether it's on atari or atarixl. There is a define with the real address, CIOV_org, for those functions which need to distinguish. See asminc/atari.inc.

**Comment by polluks** [comment]
@groessler full acknowledge!
If I replace .include by .import the linker is smart enough to include the wrapper. I suppose this was Uz' idea.

**Comment by oliverschmidt** [comment]
> If I replace .include by .import the linker is smart enough to include the wrapper.

The file cbm_kernal.inc deliberately doesn't contain any statements relevant to the linker like .import, .export or .global. Therefore linker smartness has nothing to do with it. Rather it's a question of constants vs. symbols.

> I suppose this was Uz' idea.

The file cbm_kernal.inc was introduced only few months ago so Uz has nothing to do with it. It's purpose is not to replace .import statements, it's purpose is to replace magic constants.

**Comment by groessler** [comment]
Hmm, probably I'm missing something. With my "Atari maintainer" hat on, I'd say atari.inc is for standalone ASM programs and for implementing the Atari C runtime.

That said, the "atarixl" target is not supposed to be used by an ASM-only program. Much of the magic is done in the C runtime. But atari.inc can be used to implement ASM subroutines which then are linked with an "atarixl" C program.

In the cbm_kernal.inc file I don't see any "Plus4" ifdefs. Are they in the "C16" ifdefs (iow, Plus4 target defines __C16__ as well)?

To me the main question is, would the Plus4 wrappers work if they are linked to an ASM-only program, and don't depend on anything else of the C library.

**Comment by groessler** [comment]
> That said, the "atarixl" target is not supposed to be used by an ASM-only program. Much of the magic is done in the C runtime. But atari.inc can be used to implement ASM subroutines which then are linked with an "atarixl" C program.

Of course, this C program could just call asm_routine() in main() and nothing else...

**Comment by oliverschmidt** [comment]
> To me the main question is, would the Plus4 wrappers work if they are linked to an ASM-only program, and don't depend on anything else of the C library.

I must admit that I don't understand how that is the main question. I'd say the main question is if one can just presume that what the wrappers do is what every standalone asm program wants. As far as I understand the answer is 'no'. Therefore the wrappers just don't belong to that file.

**Comment by groessler** [comment]
>  I must admit that I don't understand how that is the main question.

OK. Then we're looking at it from different perspectives. Since we both aren't CBM guys, let's leave it up for them to decide what they want...

**Comment by polluks** [comment]
@oliverschmidt I was talking about Uz' libsrc/plus4/k*.s, no underscores, pure assembler.

As I wrote tgi_lo.inc I needed 3 kernel calls, so cbm_kernal.inc was my friend. But plus4 (not c16) failed because this include file hides all of the wrappers.
My suggestion add some .ifndef __PLUS4__...

**Comment by oliverschmidt** [comment]
> Since we both aren't CBM guys, let's leave it up for them to decide what they want...

I was involved in quite some discussions during the introduction of this file so I feel sort of responsible to try to clarify things.

**Comment by oliverschmidt** [comment]
> My suggestion add some .ifndef PLUS4...

Hm, maybe I'm yet again not enough of a CBM guy but I seem to understand that the C library for the Plus4 uses banking. However not very asm program for the Plus4 _has_ to use banking. So cbm_kernal.inc is fine for those porgrams, isn't it? If that is true I don't see the benfit of precluding this use case. As I mentioned the file is not targeting your use case. Just don't use it.

**Comment by groessler** [comment]
> I was involved in quite some discussions during the introduction of this file so I feel sort of responsible to try to clarify things.

ok

**Comment by groessler** [comment]
> However not very asm program for the Plus4 has to use banking.

Ok, this shows my ignorance: I thought, the ROM/KERNAL is *always* banked out on the Plus4. Therefore, any program (ASM or C) needs to deal with the banking. If that's not the case, ignore my comments...

**Comment by oliverschmidt** [comment]
I just read http://cc65.github.io/doc/plus4.html#s1 saying...

"The difference between both cc65 targets is that the Plus/4 runtime uses banking to support full 64K RAM, while the C16 does not use banking and supports up to 32K RAM. **Because banking is not needed, most C16 programs will be somewhat smaller than the same program compiled for the Plus/4.** However, programs compiled for the C16 will always run on the Plus/4, while the reverse is not necessarily true."

...and interpreted it hopefully correctly.

**Comment by oliverschmidt** [comment]
> Use cbm.inc instead of cbm_kernal.inc which is for standalone asm programs which do not link lib.

Thanks! Very likely I over-complicated this whole thread unnecessarily by focusing on details instead of accepting the user perspective. So in short:

* cbm_kernal.inc is for standalone asm code. Therefore it lives in the public asminc folder.
* cbm.inc is for C library-related asm code. Therefore it lives in the C library folder.

Closing now...

**Comment by polluks** [comment]
Maybe cbm_kernal.inc should output a warning if someone uses it with target plus4?
**"Plus/4 KERNAL is banked out, please use the wrapper functions"**

**Comment by spiro-trikaliotis** [comment]
@polluks, no, it should not. In asm code, I want to decide myself if I want to bank something in or out. I do not have a ABI that I have to adhere to, so I am completely free.

Perhaps, I am doing some successive calls with ROM banked in? Why should the calls bank it in and out again and again? Perhaps... Perhaps...

The asm programmer should know what he is doing.

**Comment by polluks** [comment]
@spiro-trikaliotis I know what you mean but it's just a warning, nobody should fall into the same trap.
I was a slave of the o65 ABI ;-)

**Comment by oliverschmidt** [comment]
I think we don‘t want to confront users using something correctly with warnings to help users mis-using something.
