### ISSUE TITLE
specifying specific -D flags per target with the cc65 large project makefile?

### ISSUE THREAD

**Issue by tschak909** [cc65/cc65#750]
Since you guys want me to ditch having the cfg files in my build tree, how can I specify a specific -D option for a given target (atari, c64, etc.) as I need to specify a start load address and an amount of reserved memory for the atari target?

-Thom

**Comment by groessler** [comment]
I don't know the "large project makefile", but for the PLATOterm Makefile I'd do something like this:

`--- a/Makefile
+++ b/Makefile
\@\@ -35,7 +35,9 \@\@ ASFLAGS =

 \# Additional linker flags and options.
 \# Default: none
-LDFLAGS = -D__SYSTEM_CHECK__=1
+LDFLAGS = -D__SYSTEM_CHECK__=1 $(LDFLAGS.$(TARGETS))
+
+LDFLAGS.atari = --start-addr 0x2600 -Wl -D__RESERVED_MEMORY__=0x2000
  
 \# Path to the directory containing C and ASM sources.
 \# Default: src`

(The code quotation features of github are crappy, or I'm maybe just too stupid...)

**Comment by groessler** [comment]
Btw, what's the purpose of this __SYSTEM_CHECK__=1 define?

**Comment by tschak909** [comment]
that will be removed. I was trying something. :)

-Thom

**Comment by tschak909** [comment]
Ok, we're getting there. This built and runs mostly well. I am going to
track down additional testers.

I am trying to track down why when R-Verter is selected as interface, and
it is loaded, it hangs when booting from the disk, and in SDX the mouse
pointer doesn't display (am guessing it's out of memory)

also, you can create a bootable disk with make dist-atari, you just need
dir2atr in your path, as it will take the files from the dist.atari folder
and make a bootable distribution disk.

-Thom

**Comment by groessler** [comment]
> in SDX the mouse pointer doesn't display

simply doesn't display or displays as garbage? The P/M data for the mouse cursor is in page 6 by default.

> you can create a bootable disk with make dist-atari

I know already :-)

**Comment by tschak909** [comment]
Does not display at all, and not registering mouse presses, which means
it's not being loaded at all.

This is running from SDX, as trying to run it from MyDOS with RVerter hangs
upon trying to interact with the R-Verter.

(I am so sorry ahead of time, as I am trying countless combinations of
hardware and software trying to ferret out all the bugs.)

-Thom

**Comment by tschak909** [comment]
yup, good idea. will do that now. :)

**Comment by tschak909** [comment]
Letting it boot (MyDOS) makes it freeze with "LOADING TOUCH DRIVER..."
(which displays just before mouse_load_driver())

Loading it in SDX returns an error 2 (MOUSE_ERR_CANNOT_LOAD)

-Thom

**Comment by tschak909** [comment]
am guessing it's out of memory.

Thom

**Comment by groessler** [comment]
SDX returning an error is ok, although it could be investigated at some point in time.

MyDOS hanging is not ok. Can you give me instructions how to reproduce?

Btw., what's with #718? Can it be closed? If yes, please do so.

**Comment by tschak909** [comment]
Have closed #718.

First, build and make dist-atari, then

To reproduce in Altirra:

Set computer to have the following in devices:
* R-Verter
** Modem

The other parameters for the ocmputer don't matter, as this is consistant
across all of them, but to make it easier, simply set a standard XL/XE so
SpartaDOS X doesn't get in the way.

When the countdown appears, tap space, select 2 (R-Verter)
Let it copy and cold-start.

It may say out of memory on the next pass, SHIFT-F5 to cold start machine
again.

upon next reboot, you will see the terminal program start,
SERIAL DRIVER LOADED...
SERIAL DRIVER LOADED..
and freeze.

(temporarily pulled the messages, but the freeze happens when
mouse_driver_load() is done.)

-Thom

**Comment by tschak909** [comment]
did I.. one second.. :)

Ok, I just merged atari_irq back into master, and will delete that branch.
:)

-Thom

**Comment by tschak909** [comment]
it's about time for this code base to go on a diet...

**Comment by groessler** [comment]
Can this be closed?

**Comment by tschak909** [comment]
Yup. :)
