### ISSUE TITLE
ld65 after error

### ISSUE THREAD

**Issue by polluks** [cc65/cc65#752]
There's no clean-up, a partial **o65**  file is left over.

**Comment by groessler** [comment]
So what?

**Comment by polluks** [comment]
I didn't have the exact conditions anymore. It least it was o65 related.

**Comment by oliverschmidt** [comment]
> I didn't have the exact conditions anymore. It least it was o65 related.

Let me close this - and please open another issue when a known/reproducible scenario is at hand.
