### ISSUE TITLE
I don't know how else to request this

### ISSUE THREAD

**Issue by sharpninja** [cc65/cc65#753]
Please remove me from any cc65 groups.

Thanks,
Payton

**Comment by polluks** [comment]
From the mailing lists?
https://sourceforge.net/projects/cc65/lists/cc65-devel/unsubscribe
https://sourceforge.net/projects/cc65/lists/cc65-git/unsubscribe

**Comment by oliverschmidt** [comment]
@sharpninja: I'm afraid that I even couldn't if I wanted. Nowadayy you don't know anymore the subscribers of lists you manage -> data privacy.

@polluks. Thanks for links.
