### ISSUE TITLE
[Commodore] [time.h] Different behavior of time() with different targets

### ISSUE THREAD

**Issue by DarwinNE** [cc65/cc65#767]
Hi,
  first of all, thanks for this wonderful compiler that I really like.
I noticed a different behavior of the same C code compiled for different Commodore machines.
It is probably related to a different implementation of the standard library, regarding the `time()` function on different targets. Here's the example code (with a lot of fantasy, let's call this file code.c):
~~~C
#include <stdio.h>
#include <time.h>

void wait1s(void)
{
    unsigned int retTime = time(0) + 1;   // Get finishing time.
    while (time(0) < retTime);            // Loop until it arrives.
}

int main(void)
{
    printf("Here ");
    fflush(stdout);
    wait1s();
    printf("I ");
    fflush(stdout);
    wait1s();
    printf("am.\n");
    return 0;
}
~~~
And, here is the makefile:
~~~make
all: c128 c64 plus4 pet

c128:
	cc65 code.c -t c128 -o test-c128.s
	cl65 test-c128.s -t c128 -o test-c128.prg
	rm test-c128.s

c64:
	cc65 code.c -t c64 -o test-c64.s
	cl65 test-c64.s -t c64 -o test-c64.prg
	rm test-c64.s

plus4:
	cc65 code.c -t plus4 -o test-plus4.s
	cl65 test-plus4.s -t plus4 -o test-plus4.prg
	rm test-plus4.s

pet:
	cc65 code.c -t pet -o test-pet.s
	cl65 test-pet.s -t pet -o test-pet.prg
	rm test-pet.s
~~~
The program compiles correctly for the Commodore 64 and 128. The result is what's expected, i.e.
* it writes "Here "
* it pauses (less than) a second
* it writes "I "
* it pauses a second 
* it finally writes "am.", and then exits.

On the Plus4, the program is compiled; but when run, it writes "Here I am." without the pauses; so, the call to `time()` does not seem to work.

On the Pet target, I got an error when linking:
~~~
ld65: Error: 1 unresolved external(s) found - cannot create output file
make: *** [pet] Error 1
~~~
It seems to me that I got the same error when I tried to compile similar code targeting the VIC-20 with 16K.

I used Cc65 V2.17; and tested the results on VICE emulators version 2.4 running on MacOSX 10.13.6.

Cheers,
D.

**Comment by polluks** [comment]
Indeed, there's something wrong. In the past we used clock().
BTW you don't need the cc65 lines, cl65 is smart enough :-)

**Comment by DarwinNE** [comment]
Hi @polluks 

> BTW you don't need the cc65 lines, cl65 is smart enough :-)

You are right, I wanted to check the asm file generated and I continued to use that!

Cheers,
D.

**Comment by groessler** [comment]
maybe you could use the `clock()` function to generate such a short delay?

**Comment by DarwinNE** [comment]
> I presume that you didn't use an up-to-date version of cc65.

Most probably:

~~~~
$ cc65 --version
cc65 V2.17 - Git N/A
~~~~
 
> After August 15 the program won't link anymore for the Plus4 (identical to the Pet) which presumably is your expectation for a target without support for time().

Glad the issue was solved.
