### ISSUE TITLE
[atari]all file operations should default to DUNIT drive.

### ISSUE THREAD

**Issue by tschak909** [cc65/cc65#770]
When running PLATOTerm, I do not specify a device specifier for either driver loading, or config file saving. Regardless of this, drivers always attempt to load from D1: (even if the program is loaded e.g. from D2:), and the CONFIG file is always saved to D1. 

When e.g. opening a file for writing, I am doing:

`fp=fopen("CONFIG","w");`

or when opening a driver:

`ser_load_driver("ATRRDEV.SER");`

Is this okay? 

-Thom
Example binary attached.

[plato.zip](https://github.com/cc65/cc65/files/2451021/plato.zip)

**Comment by groessler** [comment]
This should already work since some weeks. Which cc65 version from when do you use?

**Comment by tschak909** [comment]
Oh ok, I'll grab the latest and check. :)

**Comment by groessler** [comment]
Your posted plato.zip doesn't crash, but also still saves to D1. Did you attach the right version?

**Comment by groessler** [comment]
I build latest PLATOterm (master branch) with latest cc65 version, and I don't see a crash. But it now properly uses D2: if started from D2:.

**Comment by tschak909** [comment]
Ok cool. I will test shortly, (am in the middle of bringing up the Apple
IIgs version.) thanks for testing, and I am deeply sorry for the false
alarm :)

-Thom

**Comment by tschak909** [comment]
Can be closed, as programmer had a derp moment. :)
