### ISSUE TITLE
[ca65] fails to build (and no error displayed) when there is a .byt ""

### ISSUE THREAD

**Issue by jedeoric** [cc65/cc65#775]
If you try this : 

.byt "C"
.byt "AB"

ca65 will build the file.

If you try this : 

.byt ""
.byt "AB"

ca65 does not output any error, but it refuses to build the file.

Of course it's a bit strange to have only .byt "" . But, it should output a warning or an error because when we have a big source code, it's difficult to find why ca65 refuses to build the source code

**Comment by oliverschmidt** [comment]
> But, it should output a warning or an error because when we have a big source code, it's difficult to find why ca65 refuses to build the source code.

For sure.

**Comment by greg-king5** [comment]
`.byte ""` is a no-op.  But, the old code expected `.byte` to create some data every time; it type-casts that data (for the debug-info file).  When there was no data, the old code tried to use a NULL pointer -- crash!

The new code doesn't type-cast when there's no data.

**Comment by vrubleg** [comment]
@mrdudz, It's not an error if you did it deliberately. The string can be from a define, for example. You can output a string and its length, and the string itself will be 0 bytes.
