### ISSUE TITLE
Unexpected trailing garbage characters

### ISSUE THREAD

**Issue by heyitswither** [cc65/cc65#785]
I'm sure that this is just me using the program wrong, but I can't find any information on a right way to do it.

When I run `cl65 -C 6502.cfg -o main main.c asm-entry.s` I get the error
```
asm-entry.s(7): Error: Unexpected trailing garbage characters
```

I am trying to call a c function from my asm file, I'm sure I'm missing a keyword or something simple, but I do not know what to use. My files are listed below.

```
// main.c
#include <stdlib.h>

void main(void)
{
    // TODO
    int i = 1 + 1;
}
```

```
; asm-entry.c
          .setcpu "6502"
          .segment "VECTORS"

          .word asm_entry

          .code
asm_entry: call _main
```

```
# 6502.cfg
MEMORY
{
  ROM: start=$a000, size=$6000, type=ro, define=yes, fill=yes, file=%O;
}

SEGMENTS
{
  CODE: load=ROM, type=ro;
  VECTORS: load=ROM, type=ro, offset=$5ffa;
}
```

Also, not sure if my config file is correct, I am trying to have my rom be from $a000-$ffff, with reset vector set. Hope you can help, thanks in advance!

**Comment by oliverschmidt** [comment]
1. What is `call` supposed to be? It isn't a 6502 opcode - see http://www.6502.org/tutorials/6502opcodes.html.

2. The code you present exposes quite some misconceptions regarding a C compiler in general and cc65 in particular. I suggest to read up on 'runtime library' and 'crt0' e.g. on Wikipedia to improve on the former and to explore the cc65 'none' target on the latter: `cl65 -t none main.c -m main.map` and read the generated main.map. This way you see what the minimum setup looks like to successfully do an `int i = 1 + 1;`.

3. You may want to subscribe to the cc65 development mailing list and explain what you want to archive. I can imagine well that you'd receive hints/help there.
