### ISSUE TITLE
[question][cfg][C16] UDG data polluted by random data (program data?)

### ISSUE THREAD

**Issue by Fabrizio-Caruso** [cc65/cc65#786]
I have:
```
Segment list:
-------------
Name                   Start     End    Size  Align
----------------------------------------------------
ZEROPAGE              000002  00001B  00001A  00001
LOADADDR              000FFF  001000  000002  00001
EXEHDR                001001  00100C  00000C  00001
STARTUP               00100D  00104E  000042  00001
ONCE                  00104F  00105A  00000C  00001
CODE                  00105B  003C2B  002BD1  00001
RODATA                003C2C  003CF5  0000CA  00001
DATA                  003CF6  003D3C  000047  00001
INIT                  003D3D  003D56  00001A  00001
BSS                   003D57  003D99  000043  00001
UDCCHAR               003E08  003FFF  0001F8  00001
```
but, when I run my game, the very last characters in UDCCHAR get some garbage (about 40 bytes are garbage).

My cfg:
```ini
SYMBOLS {
    __LOADADDR__:  type = import;
    __EXEHDR__:    type = import;
    __STACKSIZE__: type = weak, value = $0001; 
	__UDC_START__: type = weak, value = $3E08;
}
MEMORY {
    ZP:       file = "", define = yes, start = $0002, size = $001A;
    LOADADDR: file = %O,               start = $0FFF, size = $0002;
    HEADER:   file = %O,               start = $1001, size = $000C;
    MAIN:     file = %O,               start = $100D, size = __UDC_START__ - $100D - __STACKSIZE__, fill = yes;
	DUMMY:    file = %O,               start = __UDC_START__ - __STACKSIZE__ - 1, size = __STACKSIZE__, fill = yes;	
    CHARMEM:  file = %O, define = yes, start = __UDC_START__, size = $01F8, type = rw;	
}
SEGMENTS {
    ZEROPAGE: load = ZP,       type = zp;
    LOADADDR: load = LOADADDR, type = ro;
    EXEHDR:   load = HEADER,   type = ro;
    STARTUP:  load = MAIN,     type = ro;
    LOWCODE:  load = MAIN,     type = ro,  optional = yes;
    ONCE:     load = MAIN,     type = ro,  optional = yes;
    CODE:     load = MAIN,     type = ro;
    RODATA:   load = MAIN,     type = ro;
    DATA:     load = MAIN,     type = rw;
    INIT:     load = MAIN,     type = bss;
    BSS:      load = MAIN,     type = bss, define   = yes;
    UDCCHAR:  load = CHARMEM,  type = ro, define = yes, optional = no;	
}
...
```

**Comment by groessler** [comment]
The garbage bytes are from the stack.

The C16 startup file determines the available memory and puts the stack at the end of the memory. This is probably done to have all memory available when run on a Plus/4.

You'd need to change the crt0.s file to put the stack below your CHARMEM area. Best would be to get rid of the DUMMY area and merge it into MAIN. Then use end of MAIN as top of stack.

**Comment by Fabrizio-Caruso** [comment]
@groessler  The doc seems to say that the stack is placed at the end of MAIN (by default) and not at the end of the ram.  So the cfg has no control on the stack position? How do I need to change in the cfg? I had to include the dummy are to get it to work.

**Comment by groessler** [comment]
> The doc seems to say that the stack is placed at the end of MAIN (by default) and not at the end of the ram.

Where is this written in the docs?

> How do I need to change in the cfg?

Initialize "sp" to the end of MAIN.

> I had to include the dummy are to get it to work.

You could keep the DUMMY of course, but then you need to initialize the stack pointer to the end of "DUMMY". Using MAIN appears to be cleaner.
What did not work without DUMMY?

**Comment by greg-king5** [comment]
`DUMMY:` is padding in the program binary file.  Fabrizio uses it to make his custom font load directly to where it needs to be in RAM.

The start-up code does put the stack at the end of `MAIN:`.  The formula is the same as in most of the "crt0.s" files: `__MAIN_START__ + __MAIN_SIZE__ + __STACKSIZE__`
That sum equals `__UDC_START__`.

**Comment by greg-king5** [comment]
> The start-up code does put the stack at the end of `MAIN:`.  The formula is the same as in most of the "crt0.s" files: `__MAIN_START__ + __MAIN_SIZE__ + __STACKSIZE__`
> That sum equals `__UDC_START__`.

Oops, I was looking at the VIC-20 start-up when I wrote that.
You're right; the C16's start-up does measure the current amount of RAM.  It's done because the C16 can have either 16K or 32K of RAM.

@Fabrizio-Caruso, you need to link a custom version of "libsrc/c16/crt0.s".  It needs to set the `sp` variable in the same way that "libsrc/vic20/crt0.s" does it.  (Your custom version will be used instead of the one in the library.)

**Comment by Fabrizio-Caruso** [comment]
Why is the C16 different than the other targets? I cannot understand why that stack has to be at the end of ram and not at the end MAIN. This difference is not documented. Other targets with variable memory (Atari 400/800, Vic 20, Oric 1/Atmis) do not do the same.

**Comment by groessler** [comment]
> Other targets with variable memory (e.g., Atari 400/800, Vic 20, Oric 1/Atmos) do not do the same.

Not true. Atari (not the XL variant), at least, does it similar to the C16.

> Why is the C16 different than the other targets?

As @greg-king5 wrote: It's done because the C16 can have either 16K or 32K of RAM.

(Side question to @greg-king5): Why does the C16 crt0.s explicitly limit the RAM to 32K? If not more can be installed, the MEMTOP function cannot report more. If more can be installed, why is it limited to 32K?

> I cannot understand why that stack has to be at the end of ram and not at the end MAIN for the C16.

It doesn't have to be there, it's just implemented that way. Nevertheless, @greg-king5 told you how to modify the crt0.s so that it works the way you want.

> (@greg-king5 ) DUMMY: is padding in the program binary file.

I see now. Yes, it's needed. I suggest to rename the area to "STACK", then it would be more obvious what's there.

**Comment by oliverschmidt** [comment]
> I cannot understand why that stack has to be at the end of ram and not at the end MAIN for the C16.

When is the size of MAIN determined? At link time. So if a program is supposed to adapt to different memory sizes it *CAN'T* have the stack at the end of MAIN, can it?

> This difference is not documented. 

* Pull requests improving the documentation are in general always welcome.
* https://github.com/cc65/cc65/blob/master/cfg/apple2.cfg#L10 says "Presumed RAM end" and https://github.com/cc65/cc65/blob/master/doc/apple2.sgml#L55 says "The C runtime stack is located at HIMEM [...]" so at least for the Apple II there are hints that MAIN doesn't determine the the stack location.

> Other targets with variable memory (e.g., Atari 400/800, Vic 20, Oric 1/Atmos) do not do the same.

As I pointed out above the question rather needs to be the opposite: Why are there targets with variable memory which *DO* put the stack at the end of MAIN? I personally don't know the answer.

**Comment by groessler** [comment]
I think it's not that helpful to point at AppleII documentation :-)
https://cc65.github.io/doc/c16.html#s3 says about stack: "The C runtime stack is located at $3FFF ($7FFF in case of a machine with 32K of memory or more) and growing downwards."

> Why are there targets with variable memory which DO put the stack at the end of MAIN?

Which targets do that?

**Comment by oliverschmidt** [comment]
> I think it's not that helpful to point at AppleII documentation :-)

Why not? @Fabrizio-Caruso asked "Why is the C16 different than the other targets? [...] This difference is not documented." That implies for me that the documentation for other targets is relevant.

>> Why are there targets with variable memory which DO put the stack at the end of MAIN?

> Which targets do that?

According to @Fabrizio-Caruso "Other targets with variable memory (e.g., Atari 400/800, Vic 20, Oric 1/Atmos) do not do the same."

I haven't proved if @Fabrizio-Caruso is right. I only said that **IF** he is right then **HE** should ask why they do so - instead of asking why the C16 does it the way it does.

Anyhow, maybe I'm missing the point of this discussion altogether - then just ignore me ;-)

**Comment by groessler** [comment]
> Why not? @Fabrizio-Caruso asked "Why is the C16 different than the other targets? [...] This difference is not documented." That implies for me that the documentation for other targets is relevant.

Ok. So you wanted to point him to "other targets" which have that documented.
I wanted to point him to the documentation of the target at hand.

So, @Fabrizio-Caruso, how did you come to your conclusion? Is there somewhere (in the general documentation) mentioned, that stack is always at the end of MAIN?

> I haven't proved if @Fabrizio-Caruso is right. I only said that IF he is right then HE should ask why they do so - instead of asking why the C16 does it the way it does.

Agreed.

**Comment by greg-king5** [comment]
> (Side question to @greg-king5): Why does the C16 crt0.s explicitly limit the RAM to 32K? If not more can be installed, the MEMTOP function cannot report more. If more can be installed, why is it limited to 32K?

It allows programs that are built for the C16 to run on the +4.  MEMTOP reports an address that's higher than $8000 (usually $FD00).  But, the BASIC ROM starts at $8000; the C16 library doesn't disable that ROM.

(See also [the extended memory doc](https://cc65.github.io/doc/c16.html#ss5.2).)

**Comment by groessler** [comment]
Understood. Thanks

**Comment by groessler** [comment]
@Fabrizio-Caruso, is it clear now? Did you get it to work?

**Comment by Fabrizio-Caruso** [comment]
Yes, it is clear. Sorry for my late reply.
