### ISSUE TITLE
[Telestrat][question] Are atmos binaries compatible with the Telestrat? Why a Telestrat target?

### ISSUE THREAD

**Issue by Fabrizio-Caruso** [cc65/cc65#787]
Are Atmos binaries compatible with the Telestrat? Or do they use specific Atmos Basic routines?
And viceversa? 
Is the Telestrat target only meant to be used for the extra features like the Plus4 target?

**Comment by Fabrizio-Caruso** [comment]
@polluks but the Telestrat can run Atmos binaries. Can't it?
The Telestrat was sold as a compatible machine.
The main hardware is the same. Isn't it?

**Comment by polluks** [comment]
Indeed but not in cc65's point of view. The Atmos requires its BASIC (by jsr), the Telestrat runs without one (by brk).
http://wiki.defence-force.org/doku.php?id=oric:telestrat

**Comment by Fabrizio-Caruso** [comment]
@polluks  so is the Telestrat binary compatible with the Atmos?

**Comment by Fabrizio-Caruso** [comment]
@polluks  if the Telestrat target does not depend on the BASIC and only depends on the hardware, I wonder whether it can run on the entire Oric series.

**Comment by polluks** [comment]
Please take a look
1. BASIC
2. OS
3. Hardware

Telestrat's OS is called Telemon, the Atmos has no explicit OS.

**Comment by greg-king5** [comment]
The answer to your original question is "nope!"

Those two models have compatible hardwares; but, their firmwares are very different (the cc65 libraries use the firmware).

**Comment by oliverschmidt** [comment]
Thanks for the answers. It seems safe to consider this answered.

**Comment by Fabrizio-Caruso** [comment]
@polluks  Is there a working Telestrat emulator under Windows?
Oricutron crashes when you select Telestrat (I have also tried to set the Telestrat roms in the .cfg file)

**Comment by polluks** [comment]
Well, `oricutron -mt` should work out of the box. I don't use Windows.
