### ISSUE TITLE
c65 compound litterals supported?

### ISSUE THREAD

**Issue by zezba9000** [cc65/cc65#798]
Hi I'm trying to make a transpiler C output decision and I'd like the output to support this compiler.
Are compound litterals supported in the c65 compiler?

Example:
```c
typedef struct A A;

struct A
{
    int i;
};

A* Foo(A* a)
{
    return a;
}

void main()
{
    A* a = Foo(&(A){0});
}
```

**Comment by oliverschmidt** [comment]
Maybe I'm missing the point but what works is:

```
struct A
{
    int i;
};

A* Foo(A* a)
{
    return a;
}

void main()
{
    A b = {0};
    A* a = Foo(&b);
}
```

**Comment by oliverschmidt** [comment]
> Will download and test.

That seems like the appropriate approach to me.

> Also is "setjmp" supported?

https://github.com/cc65/cc65/blob/master/include/setjmp.h

**Comment by zezba9000** [comment]
Is "longjmp" also supported not finding it anywhere is the repo?

Trying to re-implement try catch like so (again sorry will download the compiler and test), just poking for any red flags with this:
```
#include <stdio.h>
#include <setjmp.h>

jmp_buf __threadExceptionBuff;

#define TRY switch(setjmp(__threadExceptionBuff)) { case 0: while(1) {
#define CATCH(x) break; case x:
#define FINALLY break; } default: {
#define TRY_END break; } }
#define THROW(x) longjmp(__threadExceptionBuff, x)

#define EXCEPTION (1)
#define NOT_IMPLEMENTED_EXCEPTION (2)

void Foo()
{
	THROW(NOT_IMPLEMENTED_EXCEPTION);
}

void main()
{
	TRY
	{
		printf("Start\n");
		Foo();
		printf("End\n");
	}
	CATCH (NOT_IMPLEMENTED_EXCEPTION)
	{
		printf("Catch Not Implemented Exception\n");
	}
	CATCH (EXCEPTION)
	{
		printf("Catch Exception\n");
	}
	FINALLY
	{
		printf("Finally\n");
	}
	TRY_END;
}
```

**Comment by oliverschmidt** [comment]
https://github.com/cc65/cc65/blob/master/libsrc/common/setjmp.s

https://github.com/cc65/cc65/blob/master/libsrc/common/longjmp.s

**Comment by zezba9000** [comment]
Ok thanks for the info.

So looks like the Try Catch stuff compiles just fine!!

Just have to use c89 local variable scoping rules though sadly. Will have to update the transpiler to support that then.

Sorry for all the questions

**Comment by oliverschmidt** [comment]
Likely not relevant for your use case, but nevertheless...

http://dunkels.com/adam/dunkels06protothreads.pdf is supported by cc65 via

https://github.com/contiki-os/contiki/blob/master/cpu/6502/sys/lc.h
https://github.com/contiki-os/contiki/blob/master/cpu/6502/sys/lc-asm.S

used by

https://github.com/contiki-os/contiki/blob/master/core/sys/pt.h

**Comment by zezba9000** [comment]
Interesting, however I probably wont support threads with the c65 compiler. Correct me if I'm wrong but all the platforms it supports are single core?

**Comment by spiro-trikaliotis** [comment]
Protothreads are not threads.

**Comment by zezba9000** [comment]
Sorry thinking in terms of the lang spec I'm transpiling. C# does have async which is similar but I'm transpiling a C# 3.0 subset which doesn't include that. Protothreads are a good thing to keep in mind though Thanks!

**Comment by oliverschmidt** [comment]
setjmp/longjmp is pretty heavyweight on the 6502. Therefore I pointed you to Protothreads as an extremely lightweight alternative. But nobody forces you to follow that thought ;-)

**Comment by zezba9000** [comment]
Heavyweight in terms of memory usage or execution performance? Try / catch is pretty slow even in C# when you throw something but not when you try.

Does setjmp run slow or just longjmp? Or just a mem usage issue?

**Comment by oliverschmidt** [comment]
Heavyweight in terms of exec performance both for setjmp and longjmp.

**Comment by zezba9000** [comment]
Ok tnx for the tip. For now will just get stuff working then look at a functionally similar way pthreads might solve the same issue. Try/Catch would really only be used to init stuff normally so it may not be an issue in the long run. Will know when I get there.
