### ISSUE TITLE
Compiler warnings about NULL in strbuf code and strcmp() call

### ISSUE THREAD

**Issue by Compyx** [cc65/cc65#801]
While compiling cc65 trunk, I get the following warnings:

```
cc65/main.c
In file included from cc65/main.c:51:
In function ‘SB_CopyStr’,
    inlined from ‘FileNameOption’ at cc65/main.c:306:5,
    inlined from ‘main’ at cc65/main.c:437:5:
common/strbuf.h:317:28: warning: argument 1 null where non-null expected [-Wnonnull]
     SB_CopyBuf (Target, S, strlen (S));
                            ^~~~~~~~~~
In file included from cc65/main.c:37:
cc65/main.c: In function ‘main’:
/usr/include/string.h:384:15: note: in a call to function ‘strlen’ declared here
 extern size_t strlen (const char *__s)
               ^~~~~~
```

```
da65/labels.c
In function ‘AddLabel’,
    inlined from ‘AddUnnamedLabel’ at da65/labels.c:129:5:
da65/labels.c:95:50: warning: argument 2 null where non-null expected [-Wnonnull]
             ((Name == 0 && SymTab[Addr] == 0) || strcmp (SymTab[Addr], Name) == 0)) {
                                                  ^~~~~~~~~~~~~~~~~~~~~~~~~~~
In file included from da65/labels.c:37:
da65/labels.c: In function ‘AddUnnamedLabel’:
/usr/include/string.h:136:12: note: in a call to function ‘strcmp’ declared here
 extern int strcmp (const char *__s1, const char *__s2)
            ^~~~~~
````

This happens with GCC 8.2.0, both using MSYS2 on Windows and in an Ubuntu 18.10 VM (the posted warnings are taken from the the Ubuntu VM).
I'm not familiar enough with the cc65 codebase, nor do I have the time to figure this out right now, but perhaps someone can take a look at this.

**Comment by groessler** [comment]
I'm seeing these, too. I had looked a bit into it, but I have to admit I didn't find the root cause.

**Comment by greg-king5** [comment]
The warning message is abbreviated; it actually means that the argument _can be_ NULL.

That cc65 bug could happen only if there were a typo in `OptTab[]` (in "main.c").  There is no typo; therefore, `LongOption()` won't create a NULL argument.  The warning is half bogus.  But, I added an "internal" error message, just in case someone mistypes a new entry in that table.  And, it stops the GCC warning.
Commit 5ac11b5e882d09e9e1dba34b76f536520a1c34fc.

Commit cd6e167982615cdf6cc529c8b15d4b84c0058fa3 fixed the da65 warning.
