### ISSUE TITLE
GEOS 128 - SetNewMode doesnt appear to exist in library

### ISSUE THREAD

**Issue by xlar54** [cc65/cc65#814]
SetNewMode allows the developer to switch between 40 and 80 column mode.  I could not locate a header for this function in the include files.  However, it does exist in an .inc file (libsrc\geos-cbm\jumptab.inc) as location $C2DD.  I also tried the following code, and it did not appear to work:

asm("lda $3f");  //graphMode
asm("eor #$80");  // toggle 40/80 col bit
asm("jsr $c2dd"); // call SetNewMode

**Comment by polluks** [comment]
`asm("eor #$80");`

**Comment by xlar54** [comment]
Yeah sorry, that doesnt work either.  (but youre right, it should be that)

**Comment by xlar54** [comment]
On a whim, I tried this, and it worked:

asm("lda $3f");
asm("eor #$80");
asm("sta $3f");
asm("jsr $c2dd"); // SetNewMode

The code I saw before didnt do the STA.  So this seems to solve the issue until we get a SetNewMode function.

**Comment by polluks** [comment]
@oliverschmidt I'm not sure if we should support functions not common for all GEOS targets, SetNewMode is rather private.

**Comment by xlar54** [comment]
Done.  As for the function, if Im not mistaken, GEOS library is only relevant to the 64 and 128 anyway, and in the Intro docs, it mentions support for both 40 and 80 columns.  If I could vote, Id suggest it being included.

**Comment by oliverschmidt** [comment]
> As for the function, if Im not mistaken, GEOS library is only relevant to the 64 and 128 anyway [...]

Certainly not. https://cc65.github.io/ says "GEOS for the C64, C128 and Apple //e". 

See below screenshots of https://github.com/cc65/cc65/blob/master/samples/geos/bitmap-demo.c running on the C64 and on the Apple //e.

![geos-bitmap-cbm](https://user-images.githubusercontent.com/2664009/49995416-59afd500-ff8c-11e8-9f49-b33642a1428a.png)
![geos-bitmap-apple](https://user-images.githubusercontent.com/2664009/49995427-62a0a680-ff8c-11e8-8104-cdd173fbbe1e.png)

**Comment by xlar54** [comment]
Ah yes, the Apple IIe version.  Youre right, forgot about that one.   Was referring to the lib documentation which seems to only mention the 64 and 128. https://cc65.github.io/doc/geos.html#ss4.1

**Comment by xlar54** [comment]
And yes, saw your link also.  I stand corrected and will now bow out gracefully :)

**Comment by oliverschmidt** [comment]
> @oliverschmidt I'm not sure if we should support functions not common for all GEOS targets, SetNewMode is rather private.

Are you aware of https://github.com/cc65/cc65/blob/master/libsrc/geos-common/symbols.txt ?

Especially if you add the Apple //e to the picture there are quite some routines not available on all three targets. So not being available on all targets likely doesn't qualify to be private.

In general I'd start out with the presumption that everything in that TXT file is to be considered part of the GEOS API - until we find out that this doesn't make sense for some reason for a specific entry.

There we have https://github.com/cc65/cc65/blob/master/libsrc/geos-common/symbols.txt#L448 and https://www.lyonlabs.org/commodore/onrequest/geos/geos-manuals/The_Hitchhikers_Guide_to_GEOS.pdf mentions SetNewMode on "external" page 36 / "internal" page 28.

https://www.lyonlabs.org/commodore/onrequest/geos/The_Official_GEOS_Programmers_Reference_Guide.pdf even explicitly says on "external" page 13 / "internal" Addendum page 7:

"If you're writing an application, add a "switch 40/80" option under the geos menu. The action for this should be to EOR graphicsMode with $80, store it back, and call the routine SetNewMode. You'll then need to redraw the screen, now in the new graphics mode."

So I'd say this is rather public.

**Comment by oliverschmidt** [comment]
This leaves us with the question of how to expose the functionality. I guess we agree that don't just want to make $3F and $C2DD public and have the user figure out the rest.

As far as I understand GEOS there's no generic way to have a program redraw the screen, so we need to leave that to the user. Apart from that general problem maybe the user wants to modify some internal data structures before redrawing the screen.

So it seems we want to encapsulate exactly what was given in https://github.com/cc65/cc65/issues/814#issuecomment-446933286.

Regarding the name I was toying with the idea to reuse videomode() - https://cc65.github.io/doc/funcref.html#ss3.268 but I see two issues:
* A GEOS programmer might not look for the functionality "there".
* The menu option "switch 40/80" proposed by the official programmers reference guide asks for a semantic different to videomode().

After all I propose a SetNewMode() without parameters. The prototype should live in https://github.com/cc65/cc65/blob/master/include/geos/ggraph.h inside a `#ifdef __GEOS_CBM__` and the implementation should live in a new directory `graph` created in https://github.com/cc65/cc65/tree/master/libsrc/geos-cbm. The file should be named `setnewmode.s`.

My understanding is that it isn't desirable to have something like a "GEOS128" target. Rather any code only relevant to GEOS128 should be enabled at runtime.

So we're left with the question what SetNewMode() should do if not running on GEOS128. I personally suggest to not take this into account at all (and have it crash when called on GEOS64). The official programmers reference guide proposes a menu option "switch 40/80" so this menu option has to be made dependent on GEOS128 being present. And if the menu option isn't present it's handled is known to be not called.

BTW: Detecting GEOS128 is supposed to be done via get_ostype().

**Comment by oliverschmidt** [comment]
The Apple //e GEOS support for sure has __LOADS__ of rough edges (aka bugs). I simply didn't have time/energy anymore at some point of the project.

**Comment by xlar54** [comment]
Agree with your approach, Oliver.  I can tackle this one based on the direction and will submit a pull req.  Still new to the contribution thing, so do let me know if im not doing something as needed by the team

**Comment by oliverschmidt** [comment]
> I can tackle this one based on the direction and will submit a pull req.

:-)

> They basically say calling setnewmode from a 64 is undefined behavior.

Exactly.

> Still new to the contribution thing, [...]

As surely expected it's best to start out with something existing and modify it. This way things like coding and formatting style are taken care of best. E.g. https://github.com/cc65/cc65/blob/master/libsrc/geos-common/graph/bitmapclip.s shows access to "jumptab.inc" and "geossym.inc". It demostrates the usual tail call elimination. Just remove the popa, popax stuff and you should be ready to go. Please don't forget to add something to https://cc65.github.io/doc/geos.html#ss3.1 by modifying https://github.com/cc65/cc65/blob/master/doc/geos.sgml
