### ISSUE TITLE
Question - GEOS Lib:  Sample for desk accessories?

### ISSUE THREAD

**Issue by xlar54** [cc65/cc65#817]
I havent seen much at all regarding creating desk accessories in the GEOS lib.  Do we have any information on this?

**Comment by oliverschmidt** [comment]
There's no additional information around on this that I'm aware of. However, you could be successful contacting the author of the library. And if you learn something useful from him you might consider adding it to the documentation here.

If the you consider https://cc65.github.io/doc/geos.html to "formal" for whatever content you come up with you can add it to the https://github.com/cc65/wiki/wiki which already contains some GOES pages. Just tell me and I'm happy to provide you with write access to the Wiki.

**Comment by xlar54** [comment]
Sounds good, thanks Oliver!
