### ISSUE TITLE
Atari ST, Amiga, Trackball mouse support doesn't work alongside serial.

### ISSUE THREAD

**Issue by tschak909** [cc65/cc65#818]
It looks like the routine which reads the mouse, is hammering POKEY interrupts, and significantly impacts the performance of serial I/O. I'm not quite sure what can be done to solve it, but maybe somebody has some insight? @groessler ?

I have attached the three versions of PLATOTerm Lite which all use this driver (trakball, ST, Amiga mouse), to demonstrate.

[PLATOTerm-mice-versions.zip](https://github.com/cc65/cc65/files/2692642/PLATOTerm-mice-versions.zip)

**Comment by polluks** [comment]
You could recommend: Use [Micromys](http://wiki.icomp.de/wiki/Micromys_V5#Modes_of_operation) and the touch tablet driver.

**Comment by tschak909** [comment]
Both.
-Thom

**Comment by groessler** [comment]
Hmm, I guess I need to get my local setup working on real hardware...

**Comment by groessler** [comment]
Are you seeing problems if you don't move the mouse? This should work ok.

**Comment by tschak909** [comment]
meanwhile, I am borrowing real hardware from a few sources to try and help work out the bugs.

This is yet another case of "I don't think we ever thought anyone was going to try and use every module at once" ;)

-Thom

**Comment by groessler** [comment]
Yes. You seem to be the first one to use serial I/O and mice in the same program. But, of course, the goal is that they should work nicely together.

**Comment by groessler** [comment]
Ok. This is kind of embarrassing. Problems with 1200 baud and mouse....
If you were using 9600 I kind of understand it. But with 1200... tsts...

**Comment by tschak909** [comment]
glad I'm not hallucinating. :)

**Comment by tschak909** [comment]
Putting this here. 

Sijmen Schouten (aka Mr. Atari) did an analysis of the ST/Amiga/Trackball driver, and came up with the following:

*snip*
```
Plato and mouse/ball problem.

Mouse/Ball driver uses same pokey-registers as R: for sending data.
Mouse/Ball driver sets to 15 counts, 15 kHz on init. So 1kHz mouse sampling.

The R-driver will change this to 1.79 Mhz and Baud_Low value....
With 1200 baud this will result in 227 counts or 8 kHz sampling.
Using timer1-irq, way to high to keep serial-IO working.

Since R has set pokey 1+2, we could use timer2 and abuse the baudrate as 16bit counter.
This will result in 739 counts 1.79 Mhz or 2 kHz sampling.
That might work.....

I made a hacked build, that seems to work at my place.


Change this:
enable/disble irq
#%00000001 -> #%00000010
#%11111110 -> #%11111101

all labels refering to:
timer1     -> timer2

and give it a swirl.
```
*snip*

**Comment by groessler** [comment]
Hmm. I have switched the timer use to poll the mouse to Pokey timer2. Seems to work with mouse-test.
But, still, with latest "master" branch of platoterm it doesn't work.
Needs more debugging...

**Comment by tschak909** [comment]
am wondering if i'm doing something stupid. you may also want to reboot
after changing the driver, just to see..

-Thom

**Comment by groessler** [comment]
There's probably something wrong in my setup. Not using a touch driver at all it still doesn't work, but it worked before I started to make my changes.
I will retry on a fresh day.

**Comment by oliverschmidt** [comment]
Thanks :-)

**Comment by polluks** [comment]
@oliverschmidt How about some credits for Thom?

**Comment by tschak909** [comment]
Yup, the corruption is an error on my part, I'll fix that soon (I'm getting the Mac version sewed up), Thanks SO much @groessler for this patch! 👍

**Comment by groessler** [comment]
> Thanks SO much @groessler for this patch!

You're welcome :-)
