### ISSUE TITLE
ATARI: cartstart needs XEGS banking support.

### ISSUE THREAD

**Issue by tschak909** [cc65/cc65#825]
Hi @groessler ... Hope you had a good Christmas :)

I've stumbled on something unexpected.

The cartridge board that Albert @ AA is using utilizes XEGS banking. It has a minimum ROM size of 32KB, of which it puts into banks 0-3, details of the bank switching are here:
https://www.atarimax.com/jindroush.atari.org/acarts.html

I have hit an issue where depending on the changes I make to my code, the startup code winds up in the wrong bank, and the cart won't start normally, (but if I load the cart from SDX, it starts)...the bank register (any address at d5xx) needs to have the correct banks set..and I am trying to manually patch my cartstart.s to get around this... but wanted to get your thoughts on how to more elegantly handle this?

-Thom

**Comment by groessler** [comment]
This seems to be a follow-up on #820. In what way is this different, as it seems XEGS carts also used 8000 area, while flash carts don't seem to support that?

> I have hit an issue where depending on the changes I make to my code, the startup code winds up in the wrong bank, and the cart won't start normally, (but if I load the cart from SDX, it starts)...the bank register (any address at d5xx) needs to have the correct banks set..and I am trying to manually patch my cartstart.s to get around this...

To me this appears to be two independent issues: "depending on the changes I make to my code, the startup code winds up in the wrong bank" and "the bank register (any address at d5xx) needs to have the correct banks set". Isnt't it? Please provide more information about each problem.

**Comment by tschak909** [comment]
Sorry, we'll probably have to untangle this. :)

See attached, I have two ROM images here. An original one, based on the PLATOTerm 1.1 Lite release, that works when burned to an EPROM.

and another, after I added a small chunk of code to fix a bug that I had accidentally introduced, which works fine in Altirra under emulation, but fails when burned to EPROM and run on the same cart board.

The only explanation that I can come up with, is that cart start is winding up in the wrong bank, somehow.

[plato-lite-eproms.zip](https://github.com/cc65/cc65/files/2713286/plato-lite-eproms.zip)

It's the only explanation that seems to make sense. I've checked in my code to the atari_cart branch:
https://github.com/tschak909/platoterm64/tree/atari_cart

-Thom

**Comment by groessler** [comment]
>  I've checked in my code to the atari_cart branch:
https://github.com/tschak909/platoterm64/tree/atari_cart

hey, just a short nitpick: the changes you did to your cfg file can be accomplished by giving ld65 command line arguments... :-)

**Comment by tschak909** [comment]
Ok. I'm sorry, I'll get it eventually :) I know this has been mentioned before, but I do really admit that I am stumbling about guessing 99.9% of the time :)

**Comment by groessler** [comment]
no problem :-) You can do it with a customized linker script or with linker command line arguments. Not using one's own linker script might be more future-proof (most of the time, or not, depending on what you've changed in the script).

**Comment by groessler** [comment]
Looking at your plato-lite-eproms.zip, it seems to me that both of them wouldn't work in all cases. Both have cartinit and cartstart vectors pointing to somewhere $9Cxx, which is dependent on the bank setting.
Ideally, these two routines should be at the end of the image (near $BFFF), or in the $A000..$BFFF range somewhere.
This isn't enforced in the current configuration. As a workaround, you could put these two routines into another segment which is loaded last into "ROM" in the "SEGMENTS" list in the cfg file. This should work in your case, but not generally (consider a 1K program put into a 16K cart, they will still end up in the $8000..$9FFF area).

**Comment by tschak909** [comment]
How would I best do that?
-Thom

**Comment by groessler** [comment]
> How would I best do that?

You are referring to "you could put these two routines into another segment which is loaded last into ROM"?

If yes, make copies of `cartinit.s` and `cartstart.s`, and add a `.segment "FOO"` directive there to compile the code for segment "FOO". And add them to the files to link.

Then change the linker cfg like this:
```
diff --git a/cfg/atari-cart.cfg b/cfg/atari-cart.cfg
index e903d4d7..59728751 100644
--- a/cfg/atari-cart.cfg
+++ b/cfg/atari-cart.cfg
@@ -25,6 +25,7 @@ SEGMENTS {
     CODE:     load = ROM,             type = ro,  define = yes;
     RODATA:   load = ROM,             type = ro,                optional = yes;
     DATA:     load = ROM, run = MAIN, type = rw,  define = yes, optional = yes;
+    FOO:      load = ROM,             type = ro,                optional = yes;
     INIT:     load = MAIN,            type = bss,               optional = yes;
     BSS:      load = MAIN,            type = bss, define = yes, optional = yes;
     CARTHDR:  load = CARTID,          type = ro;
```
Untested, but I hope you get the idea.

**Comment by tschak909** [comment]
Yup, I do. It worked! Thanks so much! :) slowly am starting to get the hang of the linker.. this will be _very_ useful once I do later versions of PLATOTerm (I am doing all the research I need to do to make a portable implemetnation of the Micro-TUTOR interpreter in C, so that it can be plopped onto either cart banks for the Atari, or onto disk overlays, and this helped me understand the linker, a bit more. :)

-Thom

**Comment by groessler** [comment]
Can this be closed?

**Comment by tschak909** [comment]
Yeah, I think so.
-Thom
