### ISSUE TITLE
Optimizer pass "OptStackOps" generates incorrect code for a ternary expression.

### ISSUE THREAD

**Issue by holmak** [cc65/cc65#830]
Minimal repro program:
```C
extern char *dst;

char repro()
{
    char src = 0;
    *dst = (src == 0) ? 0xAA : src;
    return *dst;
}
```
The line with the ternary expression is optimized into incorrect code. Specifically, the code for the "true" case is optimized out. The problem is introduced in the optimizer pass "OptStackOps". I used `--debug-opt-output` to see the effects of each optimizer pass. Here is the before and after of "OptStackOps":

Before:
```asm
;
; char src = 0;
;
	lda     #$00
	jsr     pusha
;
; *dst = (src == 0) ? 0xAA : src;
;
	lda     _dst
	ldx     _dst+1
	jsr     pushax
	ldy     #$02
	lda     (sp),y
	jne     L000B
	lda     #$AA
	jmp     L000C
L000B:	lda     (sp),y
L000C:	ldy     #$00
	jsr     staspidx
;
; }
;
	jmp     incsp1
```
After:
```asm
;
; char src = 0;
;
	lda     #$00
	jsr     pusha
;
; *dst = (src == 0) ? 0xAA : src;
;
	lda     _dst
	ldx     _dst+1
	sta     ptr1
	stx     ptr1+1
	ldy     #$00
	lda     (sp),y		; (A)
	ldy     #$02		; (B)
	jne     L000B		; (C)
	lda     #$AA
	jmp     L000C
	ldy     #$00
L000B:	lda     (sp),y
L000C:	ldy     #$00
	sta     (ptr1),y
;
; }
;
	jmp     incsp1
```
Before the optimization, line (A) loads the value of the ternary expression's "condition" sub-expression. Then, the following `jne` instruction on line (C) uses the zero-flag generated by line (A) to determine which of the ternary expression's branches are taken.

The optimization pass changes and adds several lines. The important change is that it inserts a `ldy` instruction on line (B), which overwrites the zero-flag from (A) that was intended to be used on line (C). Since `ldy #$02` always clears the zero-flag, only the false branch of the ternary expression will ever be used. Subsequent optimization passes remove all the code for the "true" branch of the ternary expression, since it is now dead code.

Please let me know if anything in this description is unclear.

**Comment by holmak** [comment]
It looks like issue #167 might be related; it also involves the "OptStackOps" pass.

**Comment by oliverschmidt** [comment]
Thanks for the qualified bug report !

**Comment by holmak** [comment]
@cacciatc uses a "bisect.sh" script to identify which optimizer pass is failing in this issue: https://github.com/cc65/cc65/issues/167#issuecomment-242609571

Is this script available anywhere? It would be very helpful for me when diagnosing issues like this.

**Comment by cacciatc** [comment]
Truthfully, I cannot remember why I did that instead of using ```--debug-opt-output``` or what the differences were...

**Comment by holmak** [comment]
I would guess that you used it because it is much faster than doing it by hand!

From what I saw, it looked like it was able to automatically determine exactly which optimizer pass caused the test to stop working. This would be much faster than the way I did it, looking through the output of `--debug-opt-output` and diffing each stage manually.

**Comment by holmak** [comment]
@cacciatc I was able to reproduce the behavior of your bisect script, so don't worry about looking for it. Mine is a Python script; I'd be happy to share it if anyone is interested. It's a bit messy, though.

Using this script, I was able to determine that bug #784 is also caused by `OptStackOps`. I posted the details in that bug's comments.

**Comment by oliverschmidt** [comment]
Fixed via https://github.com/cc65/cc65/commit/37f80534c9953e168f2bc512b7b6484aeec50e18.
