### ISSUE TITLE
Output user specified text from within assembler source

### ISSUE THREAD

**Issue by skeetor** [cc65/cc65#835]
I noticed that there is no way, one can add messages being printed from the assembler. You can add a warning for that purpose using '.warning' but this is kind of ugly because it creates a warning, which makes it appear like something is wrong.

Would it be possible to add a '.message' command so that the user can specify text which is printed when compiled?

I find this usefull for i.E. when testing features of the assembler and are not sure what exactly is going on during the assembly. Might also be usefull to print what variant one is building when changing certain parts using '.ifdef'.

Example:

```
.ifdef VC20
.message "Building VC20"
.elseif C64
.message "Building C64"
.else
.assert 0 = 1, error "No valid target defined"
.endif
```

If this is ok, I would implement it myself and add it via PR.

If there is already something like that, I haven't found it in the docs.

**Comment by silverdr** [comment]
.out ?
https://cc65.github.io/doc/ca65.html#ss11.79

**Comment by skeetor** [comment]
Ahh! Thx! I missed that one. :)
