### ISSUE TITLE
Atari 2600 .3E 32k roms for UnoCart?

### ISSUE THREAD

**Issue by zezba9000** [cc65/cc65#841]
I'm trying to test double buffering using the large memory pool in the UnoCart.
How do I compile for a .3e rom type? Does CC65 support this?

Trying to create this buffer: "unsigned char buffer[80 * 96];"
I get error: "Error: Cannot generate most of the files due to memory area overflow"

**Comment by polluks** [comment]
No surprise, atari2600.cfg doesn't support bank switching at all. You could use an overlay config as a template for .3E.

**Comment by zezba9000** [comment]
If I compile using CA65 and do this in asm would that work?
Using the sample "samples/tutorial" to mix asm and C I just need to find out how to store the memory in that location.

**Comment by polluks** [comment]
samples/tutorial? Nah... you know the size of printf?

**Comment by polluks** [comment]
Well, you cannot access any data if it doesn't compile. Use `cl65 -S` and every C source would be an example for you.
However .3E support would requiere some kind of em driver...

**Comment by zezba9000** [comment]
Looks like this doc says where it goes: http://kevtris.org/files/sizes.txt
"F4 - 'Standard' 32K; uses 1FF4 to 1FFB"

Because the UnoCart uses the same spec as Stella for 32k .3e roms that might work.

Maybe if I change line:
FROM: RAM: file = "", start = $0080, size = $0080 - __STACKSIZE__, define = yes;
TO: RAM: file = "", start = $1FF4, size = $1FFB - __STACKSIZE__, define = yes;

Will have to try when I get a chance.

**Comment by polluks** [comment]
Oh boy! You know the meaning of "size"?
Seriously, VCS bank switching is possible, see Supervision.
