### ISSUE TITLE
[QUESTION] What is wrong here?

### ISSUE THREAD

**Issue by silverdr** [cc65/cc65#842]
I have an assignment like this:

`number_of_tests = (tests_table_end - tests_table) / .sizeof(wfmh_test)`

but when I get to the point where I need to use it:

`cmp #number_of_tests`

I get `Error: Range error` in this line. When I replace assignment with `number_of_tests = 13` it works as expected. The result of expression evaluation should surely fit into eight bits as it is basically two labels for begin and end of the table filled 13 "wfmh_test" structs ten bytes each. Am I missing something obvious here?

**Comment by polluks** [comment]
How about casting with .LOBYTE?

**Comment by silverdr** [comment]
Yes - that helps - and I think I eventually understood the behaviour in general and have things working now, thanks.
