### ISSUE TITLE
Q: __ATARI__

### ISSUE THREAD

**Issue by polluks** [cc65/cc65#844]
Shouldn't atari5200 also define `__ATARI__`?
Target atari2600 of course not.

**Comment by groessler** [comment]
No. Why should it?

**Comment by polluks** [comment]
I was thinking about `__CBM__` (common jump table of the family) but this ROM is completely different.

**Comment by groessler** [comment]
Exactly. You can think of them as completely different systems which just happen to use the same hardware chips.
