### ISSUE TITLE
cc65 65816 cpu target support?

### ISSUE THREAD

**Issue by robin-raymond** [cc65/cc65#850]
Any chance that the cc65 compiler will add 65816 native instruction support? I know the ca65 has the assembly support.

**Comment by polluks** [comment]
In a first step we should support SNES SMC/SFC or GS/OS or expand sim65...
then AX may be replaced by the 16 bit accu, just stay tuned for version 3.0 ;-)

**Comment by mrdudz** [comment]
changing the compiler to emit (somewhat okish) 65816 code wont be a trivial task :) and yes, first there should be a way to test this :)

**Comment by oliverschmidt** [comment]
> Any chance that the cc65 compiler will add 65816 native instruction support?

I don't see a momentum for this. In fact I'm so sure that I'm even tempted to close this issue right away.

> [...] GS/OS [...]

That seems over-ambitious. But the ProDOS 16 API is supposed to be very doable. I committed many years ago to add ProDOS 16 support if there's 65816 support in the cc65 compiler.

> changing the compiler to emit (somewhat okish) 65816 code wont be a trivial task :)

Full ACK. I rather see a totally new compiler created with 65816 support. Likely independent of the cc65 project - which makes sense as the whole runtime library should be 65816 and as the C libraries would target different machines and/or different OSes.

**Comment by mrdudz** [comment]
Yep. jolze ported LCC to 65816 for "wingsos" - it might be easier to pick that up

**Comment by polluks** [comment]
> Yep. jolze ported LCC to 65816 for "wingsos" - it might be easier to pick that up

For example this [lcc](https://github.com/lcc-816/lcc-816).

**Comment by oliverschmidt** [comment]
Thanks for the hints - let's close this...
