### ISSUE TITLE
Load from array via constant pointer not optimized

### ISSUE THREAD

**Issue by sehugg** [cc65/cc65#856]
Declare an array at an absolute address (via macro, but doesn't have to be, also could be a char*):
```c
#define updbuf ((unsigned char[256])0x100)
```
Then, do a load/store:
```c
unsigned char i,y;
void main(void) {
    y = updbuf[i];
    updbuf[i] = y;
}
```
The load could be optimized to "lda $100,y"; but, it is not:
```asm
        ldx     #$01
        lda     #$00
        ldy     _i
        sta     ptr1
        stx     ptr1+1
        lda     (ptr1),y
        sta     _y
        ldy     _i
```
But, the store is optimized:
```asm
        lda     _y
        sta     $0100,y
```
If `updbuf[]` is declared as a regular array, both cases are optimized.

**Comment by groessler** [comment]
`#define updbuf ((unsigned char[256])0x100)` doesn't appear to be valid C.

**Comment by sehugg** [comment]
You're right, although cc65 groks it. The result is the same with this:

`#define updbuf ((unsigned char*)0x100)`

**Comment by mrdudz** [comment]
please post a complete example :)

**Comment by sehugg** [comment]
C source file:
```
#define updbuf ((unsigned char*)0x100)
unsigned char i,y;
void main(void) {
    y = updbuf[i];
    updbuf[i] = y;
}
```
Command line:
`$ cc65 -O <filename>.c`

**Comment by groessler** [comment]
You can workaround by putting updbuf into an asm file:

C file:
```
extern unsigned char updbuf[256];
unsigned char i,y;
void main(void) {
    y = updbuf[i];
    updbuf[i] = y;
}
```

asm file:
```
.export _updbuf
_updbuf = $100
.end
```

**Comment by polluks** [comment]
> ```c
> #define updbuf ((unsigned char[256])0x100)
> ```
> 
> doesn't appear to be valid C.

gcc eats it :)

**Comment by groessler** [comment]
which version?
My gcc 7.3.1, Sun C 5.13, and clang 5.0.2 didn't like it.

**Comment by polluks** [comment]
> which version?
> My gcc 7.3.1, Sun C 5.13, and clang 5.0.2 didn't like it.

gcc 8.2.1 https://tio.run/#c-gcc
