### ISSUE TITLE
How important is the speed of the "isalpha" function and friends?

### ISSUE THREAD

**Issue by IrgendwerA8** [cc65/cc65#858]
I always had the impression that "spoiling" a full page of data for these functions isn't justified and thought about an alternative implementation (preserving the principle of common code for all targets and target dependent tables).
Size would be reduced by approx. 100 bytes, while execution speed suffers quite a lot.

Any interest for an elaborated proposal?

**Comment by oliverschmidt** [comment]
I wondered many times too if the size-vs-speed decision made for the char classification matches the decisions made for the rest of the C library.

However, the benefit of the current approach seems to be that all char classification functions share that data page. So I imagine some break-even point being reached when more than n functions are used compared to alternative approaches.

From that perspective it seem especially interesting to know how many char classification functions are used by scanf().

**Comment by IrgendwerA8** [comment]
> However, the benefit of the current approach seems to be that all char classification functions share that data page.

That wouldn't change with my approach.
It could in this way:
I would introduce a second table with all possible masks which are used by the current ctype table ($00,$01,$02,$09,$0A,$0C,$10,$50,$A0,$D0) - many flags are exclusive so only 10 combinations remain (up to 16 would be possible).
The ctype table itself then carries two four bit nibbles in a single byte, choosing with this nibble index the final mask from the newly introduced table. So the ctype table is halved in size.
The general logic for this principle would be shared by all "is-"functions which then filter by their mask like today.
I don't think the "is"-functions are really performance critical, that's why I'm asking...

**Comment by oliverschmidt** [comment]
At least I personally am interested in a proposal. I fully agree that the char classification functions aren't performance critical. I see them used to process some type of program input. And that input is supposed to be "slow" anyhow in one way or another.

My only concern is that your approach complicates things too much. But I don't see myself being able to assess this without seeing the actual code. I hope you understand that.

**Comment by groessler** [comment]
@IrgendwerA8: ping?

**Comment by IrgendwerA8** [comment]
I'm currently very busy. 
The bad news: I will create a proposal, but need some time.
The good news: I have received a potential fix from Uz for #830.
Of course this has a higher priority - I try to handle it within the next week.

**Comment by groessler** [comment]
No problem. I was just curious if you're still interested in this. Take your time...

**Comment by oliverschmidt** [comment]
> The bad news: I will create a proposal, but need some time.

I don't see the "bad" in this ;-)

> The good news: I have received a potential fix from Uz for #830.

Cool :-)

**Comment by IrgendwerA8** [comment]
Starting with the work right now, I made so discoveries I like to verify:
Am I right that the only occurrence of `isascii()` is the documentation an there is no implementation at all? - I guess cc65 should supply an implementation?
Leaning the `is...` functions would mean to abstain from the in-lined version, forced be the "eagerly inline" mechanism. (Which IMHO isn't really a loss.) The documentation describes the eagerly inline has also effect regarding the `memcpy(),memset(),strcmp(),strcpy(),strlen()` - but I've found no indication for that behavior. Could it be/make sense to remove the "eagerly inline" setting/logic completely?

**Comment by oliverschmidt** [comment]
> Am I right that the only occurrence of isascii() is the documentation and there is no implementation at all?

Yes, I agree with your discovery.

> I guess cc65 should supply an implementation?

Yes, I think so. However I don't the implementation making use of any table whatsoever. As far as I understand it's just the question if the parameter is <= 0x7F. See e.g. https://pubs.opengroup.org/onlinepubs/9699919799/functions/isascii.html and https://github.com/cc65/cc65/blob/master/src/common/chartype.c#L73-L77.

> Could it be/make sense to remove the "eagerly inline" setting/logic completely?

I presume that checking out https://github.com/cc65/cc65/commit/02daf9f8b5c1ae2267561ee05ce67b2d0393c12d shows that this is _NOT_ the case.

**Comment by IrgendwerA8** [comment]
> However I don't the implementation making use of any table whatsoever.

Like all other "is"-functions you can find at that link. Question is, if this is still true across all cc65 targets...

> I presume that checking out [02daf9f](https://github.com/cc65/cc65/commit/02daf9f8b5c1ae2267561ee05ce67b2d0393c12d) shows that this is _NOT_ the case.

Ok, I found the usage. Thanks for pointing out.

**Comment by oliverschmidt** [comment]
> Like all other "is"-functions you can find at that link.

I'm afraid there's a misunderstanding. E.g. https://github.com/cc65/cc65/blob/master/libsrc/common/isalnum.s uses the bits CT_LOWER | CT_UPPER | CT_DIGIT. I don't see how the existing bits could be used for an isascii(). And I don't see us adding a new bit for an isascii(). Therefore I see a general difference between isascii() and all other is...() functions. And therefoe "our" isascii() implementation is likely simliar to "standard" implemenations (like the one I linked).

> Question is, if this is still true across all cc65 targets...

I'm afraid there's yet another misunderstanding. E.g. isalnum() is about the "abstract" idea of alphabetical chars plus numerical chars. This is dependent on the charset used. In contrast ASCII is a fixed specification. There's nothing charset-dependent whatsoever in isascii().

**Comment by IrgendwerA8** [comment]
See PR #997

**Comment by oliverschmidt** [comment]
Thanks :-)
