### ISSUE TITLE
Documentation on PETSCII/ASCII Conversion

### ISSUE THREAD

**Issue by everyfan** [cc65/cc65#859]
Documentation should be added on how compiling for CBM systems converts PETSCII and ASCII.

I'm trying to figure out where and when exactly CC65 converts between ASCII and PETSCII (I need to know this since I'm programming for the RS232 interface which generally uses ASCII bytes that need conversion in software). I'm having weird bugs despite that I think might be due to this conversion (that I assume is happening at compile time); but I can't find any documentation on it, and I can't find any info on it in the C64 or CBM headers.

**Comment by polluks** [comment]
cc65.sgml says: "Each literal string and each literal character in the source is translated by use of a translation table."
So no literal, no translation.

**Comment by oliverschmidt** [comment]
@polluks: Thanks.
