### ISSUE TITLE
Array Dereference Returns Garbage

### ISSUE THREAD

**Issue by sci4me** [cc65/cc65#860]
Is this a bug or am I just stupid? It seems to me that the two following snippets ought to behave exactly the same... but they don't. The first prints out my (zero-terminated) string as expected while the second just prints garbage and never stops. (Typically this garbage is a large number of the same value repeating with another value sprinkled in every once in a while for good measure :joy:)

```c
// works:
u8 *i = (u8*) str;
while(*i) {
	acia_putc(*i);
	i++;
}

// prints garbage (infinitely):
u16 i = 0;
while(str[i]) {
	acia_putc(str[i]);
	i++;
}
```

**Comment by mrdudz** [comment]
how is str declared and where? (a complete example would help, you could use cputc for demonstration).

**Comment by sci4me** [comment]
`str` is declared as such:
```c
static const u8 *str =  "<my-string-here>";
```
It's stored in the ROM of my computer.

I'll look into creating a full example...

**Comment by sci4me** [comment]
So I discovered that if I change the non-working snippet to the following, it prints _nothing_.
```c
u8 j = 0;
while(str[j]) {
	acia_putc(str[j]);
	j++;
}
```

Strange. It's almost as if the compiler isn't handling type promotion correctly?

**Comment by greg-king5** [comment]
> So, I discovered that, if I change the non-working snippet to the following, it prints _nothing_.
> ```c
> u8 i = 0;
> while(str[i]) {
> 	acia_putc(str[i]);
> 	i++;
> }
> ```
> 
> EDIT: But, this does work correctly?!
> ```c
> u8 j = 0;
> while(*(str + j)) {
> 	acia_putc(*(str + j));
> 	j++;
> }
> ```
> By the way, this issue exists on both V2.17 and master.

Those two snippets generate exactly the same Assembly language!  Therefore, I conclude that either you must have done the tests differently from each other, or your hardware has random faults.

**Comment by sci4me** [comment]
> > So, I discovered that, if I change the non-working snippet to the following, it prints _nothing_.
> > ```c
> > u8 i = 0;
> > while(str[i]) {
> > 	acia_putc(str[i]);
> > 	i++;
> > }
> > ```
> > 
> > 
> > EDIT: But, this does work correctly?!
> > ```c
> > u8 j = 0;
> > while(*(str + j)) {
> > 	acia_putc(*(str + j));
> > 	j++;
> > }
> > ```
> > 
> > 
> > By the way, this issue exists on both V2.17 and master.
> 
> Those two snippets generate exactly the same Assembly language! Therefore, I conclude that either you did the tests differently from each other, or your hardware has random faults.

Iiiiinteresting. They do indeed generate the exact same output. And when I tried it again, the first snippet worked. Huh...

However when I change to this:
```c
u16 i = 0;
while(brainfuck_code[i]) {
	acia_putc(brainfuck_code[i]);
	i++;
}
```

It still doesn't work; loops infinitely...

**Comment by polluks** [comment]
@sci4me What's your assembler code? What happens if you delete the function call?

**Comment by sci4me** [comment]
> @sci4me What's your assembler code? What happens if you delete the function call?

This is the startup assembly code:
```
			.importzp sp
			
			.import zerobss
			.import copydata

			.import __CSTACK_START__
			.import __CSTACK_SIZE__

			.import _start

			.segment "VECTORS"

			.word nmi
			.word reset
			.word irq

			.code

.proc reset
			sei
			cld
			ldx #$FF
			txs

			jsr zerobss
			jsr copydata

			ldx #0
:			stz $00,x
			inx
			bne :-

			lda #>(__CSTACK_START__ + __CSTACK_SIZE__)
     		sta sp
     		lda #<(__CSTACK_START__ + __CSTACK_SIZE__)
     		sta sp+1

     		cli
     		jmp _start
.endproc

.proc nmi
			rti
.endproc

.proc irq
			rti
.endproc
```
And here's my ACIA code:
```
.proc acia_init
            lda #%00011111
            sta ACIA_CONTROL
            lda #%00001001
            sta ACIA_COMMAND			
            rts
.endproc
.export _acia_init = acia_init

.proc acia_putc
			phx
            ldx #$68
:           dex
            bne :-
            plx
            sta ACIA_DATA
            rts
.endproc
.export _acia_putc = acia_putc
```

If I delete the function call? You mean to acia_putc? ... Actually, to my amazement, it doesn't infinitely loop... hmmmh...

**Comment by polluks** [comment]
Aha, 65C02 but I see no side effects in acia_putc.

**Comment by sci4me** [comment]
> Aha, 65C02 but I see no side effects in acia_putc.

Yeah, which is why I'm so confused :joy:
I don't really see how it could be my hardware or testing setup; it's been very consistent for me (when working in pure assembly...)

I'll continue to mess with it, but, I don't know. It's been frustrating as all progress has been blocked on whatever issue I'm running into...

**Comment by groessler** [comment]
I haven't followed the discussion, and I don't knw the environment, but this

```
		lda #>(__CSTACK_START__ + __CSTACK_SIZE__)
     		sta sp
     		lda #<(__CSTACK_START__ + __CSTACK_SIZE__)
     		sta sp+1
```

definitely looks wrong.

**Comment by sci4me** [comment]
> I haven't followed the discussion, and I don't knw the environment, but this
> 
> ```
> 		lda #>(__CSTACK_START__ + __CSTACK_SIZE__)
>      		sta sp
>      		lda #<(__CSTACK_START__ + __CSTACK_SIZE__)
>      		sta sp+1
> ```
> definitely looks wrong.

How so? My understanding of that code is that it should set the C parameter stack pointer to the top address of the segment I have designated for said stack. High byte first then low byte. Am I mistaken? (I very well may be lol)

**Comment by groessler** [comment]
Yes. Low byte first, and then high byte.

**Comment by sci4me** [comment]
> Yes. Low byte first, and then high byte.

OH GOD I am so sorry to waste everyone's time :joy:
I still mix the endiannesses up apparently! Just swapped those two and it worked first try. DOH!
