### ISSUE TITLE
C Dispatch Tables

### ISSUE THREAD

**Issue by sci4me** [cc65/cc65#864]
GCC supports using labels as values in order to implement dispatch tables: https://gcc.gnu.org/onlinedocs/gcc/Labels-as-Values.html in the interest of a slight performance improvement over using a switch statement.

Does CC65 have any way to do this or similar? Or is it only possible in ASM?

**Comment by polluks** [comment]
How about something like this `__asm__ ("jmp %w", *array[i])`?

**Comment by sci4me** [comment]
> How about something like this `__asm__ ("jmp %w", *array[i])`?

Yes but how do I put the C labels in the array?

**Comment by polluks** [comment]
Well, if you don't use a label it's not included but you got the idea
````
int array[10];
void main()
{
mylabel:;
__asm__ ("lda #<%g", mylabel);
__asm__ ("sta %v", array);
__asm__ ("lda #>%g", mylabel);
__asm__ ("sta %v+1", array);
__asm__ ("jmp (%v)", array);
//goto mylabel;
}
````

**Comment by sci4me** [comment]
What would be necessary to be able to use a label as a value in this compiler? Is it feasible or is the compiler not structured to support such an extension?

**Comment by greg-king5** [comment]
It's possible; but, I think that it isn't better than `switch` statements.
```c
#define SET_LABEL(here,label) \
    __asm__ volatile ("lda #<%g", label); \
    __asm__ volatile ("ldx #>%g", label); \
    (here) = __AX__

/* This array must be global! */
static unsigned int labels[9];

static void example(unsigned char n)
{
    /* The array index must be a constant expression! */
    SET_LABEL(labels[1], mylabel1);

  mylabel1:
    SET_LABEL(labels[2], mylabel2);

  mylabel2:
    SET_LABEL(labels[3], mylabel3);

  mylabel3:
    SET_LABEL(labels[4], mylabel4);

    /* a "computed goto" */
    __AX__ = labels[n];
    __asm__ ("jmp callax");

  mylabel4:
    return;

    /* This is "dead code"; but, these GOTOs must exist,
    ** or cc65 won't generate these labels.
    */
    goto mylabel1;
    goto mylabel2;
    goto mylabel3;
    goto mylabel4;
}

void main(void)
{
    example(3);
}
```
At least one of those `__asm__` statements must have a `volatile` qualifier, so that the function won't be optimized.  Otherwise, the labels would be removed from the Assembly code.

**Comment by clbr** [comment]
Nice coincidence, I just need computed goto for a project. For a prev project I did it manually in asm, but that's a pain since it becomes hard to edit that way. If it's not massively complex to add, should happen soon.

**Comment by sci4me** [comment]
> Nice coincidence, I just need computed goto for a project. For a prev project I did it manually in asm, but that's a pain since it becomes hard to edit that way. If it's not massively complex to add, should happen soon.

Yeah, proper support for computed goto would be nice.
