### ISSUE TITLE
hello.c for Atari 5200

### ISSUE THREAD

**Issue by polluks** [cc65/cc65#866]
We have conio support but hello does not compile.
By the way how about adding a .CAR header?

**Comment by groessler** [comment]
which "hello" does not compile? Please post source code.

**Comment by polluks** [comment]
samples/hello.c our reference.

**Comment by groessler** [comment]
Yes, you're right. I'm getting this (why didn't you post that as well?):

```
$ cl65 -tatari5200 -o /tmp/x.bin samples/hello.c 
samples/hello.c(51): Error: Undefined symbol: 'CH_ULCORNER'
samples/hello.c(53): Error: Undefined symbol: 'CH_URCORNER'
samples/hello.c(59): Error: Undefined symbol: 'CH_LLCORNER'
samples/hello.c(61): Error: Undefined symbol: 'CH_LRCORNER'
$
```

After adding these defines, I'm getting:

```
$ cl65 -tatari5200 -o /tmp/x.bin samples/hello.c 
Unresolved external '_bgcolor' referenced in:
  samples/hello.s(51)
Unresolved external '_bordercolor' referenced in:
  samples/hello.s(49)
Unresolved external '_cgetc' referenced in:
  samples/hello.s(128)
Unresolved external '_textcolor' referenced in:
  samples/hello.s(47)
Unresolved external 'screensize' referenced in:
  conio/scrsize.s(20)
ld65: Error: 5 unresolved external(s) found - cannot create output file
$
```

The `cgetc` error should be fixed in `hello.c` I guess. Extend the `#if defined(__NES__) || defined(__PCE__) || defined(__GAMATE__)` line.

For the rest, you're invited to provide implementations. :-)

**Comment by polluks** [comment]
C'mon, it's your baby! :-P

**Comment by groessler** [comment]
Which does't mean that I'm the only one to make changes :-)

**Comment by groessler** [comment]
How do you think that the fact that there is no difference between "border color" and "background color" be handled? Atari5200 uses Antic mode #6 (BASIC GRAPHICS mode #1) for its conio.

**Comment by oliverschmidt** [comment]
I presume this is an "open" question to everybody, right?

I'm not sure I understand you right. I presume you want to express that there's no way to have the background and the border to have different colors...

In that case I'm in fact pretty sure that the "right" way to handle this is that bordercolor() does nothing while bgcolor() sets the color in question. Reasons:

* The term 'background' can easily be understood as all screen areas not colored with the text color. On the other hand the term 'border' is pretty clearly only the area outside the text area.

* A program might set the border color identical to the text color. Having bordercolor() set the background color would turn the text unreadable.

**Comment by polluks** [comment]
...and add a hint in the doc.

**Comment by groessler** [comment]
@oliverschmidt: ok
@polluks: hinst about what exactly?

**Comment by oliverschmidt** [comment]
I guess that bordercolor() does nothing. Maybe as brief as https://cc65.github.io/doc/apple2.html#ss8.2 ...

**Comment by mrdudz** [comment]
mmmh somehow i remember from previous discussions that adding empty functions just to satisfy the api is unwanted in cc65 environment. perhaps some kind of general rule shut be set up for this :)

**Comment by oliverschmidt** [comment]
In general a good point. The CONIO color dummies were added back then by Uz. I'm personally fine with removing all CONIO color dummies - and adding one more #if to hello.c.

**Comment by groessler** [comment]
The behaviour of bodercolor() should be documented, I agree.

I sort of remember the discussion about unimplemented/empty functions. But in this case I'd prefer to add a bodercolor() stub. Otherwise we would force people to add an '#if' to their programs. And I don't see that an unimplemented bordercolor() would change program behaviour.
But bordercolor() cannot do nothing since it has a return value. I'd return the current background color.

Another thing: The 5200 conio screen, different from the atari conio screen, is not monochrome, but allows for 4 foreground colors. The top two bits of the character code in screen memory point to four color registers, and the char is displayed in the color of the color registers.
So defines like "COLOR_BLACK", "COLOR_WHITE", etc. are not that meaningful. The four color registers are initialized by the startup code to have the same values as they have on the Atari computers, where they are initialized by the ROM.
So I can add "COLOR_<color>" defines for the default contents of the color registers (if I manage to, I'm color blind). But as soon as an user program changes the color registers, the names are no longer meaningful.
So I propose to add another set of defines (to the atari5200 include files), like "COLOR_0", "COLOR_1", ..., "COLOR_3" to specify the color register.
What do you think?

**Comment by oliverschmidt** [comment]
I wrote before that I'm fine with removing the CONIO color dummies - and that's still true.

However, I'm with @groessler that I prefer them to be kept in place.

@groessler: Are you aware that there's infrastructure in place to get rid of call sites for CONIO color functions on targets that don't support them? See: https://github.com/cc65/cc65/blob/master/include/conio.h#L193-L214 I presume this approach to be beneficial here.

It's used on the Apple II. See: https://github.com/cc65/cc65/blob/master/include/apple2.h#L203-L209

**Comment by oliverschmidt** [comment]
To me the 4-color-problem looks very similar (identical ?) to the problem we have on several targets with TGI. The COLOR macros are meaningless as soon as someone changes the palette.

I'm (too) well aware that we had "lively" discussion on TGI colors in the past. But as far as I remember nobody disagreed so far with the current TGI approach with regards to this specific aspect:

_We have COLOR macros trying to allow/simplify cross target programming. Some targets have changeable palettes, others don't. So as soon as a program starts to use palettes it's not cross target anymore anyway. And such a program will likely not use any macros whatsoever but rather know "its" numeric values._

To me it seems to make sense to adapt that approach to the CONIO situation at hand. The result would be for me to have the four color registers initialized with "nice" values, not values trying to emulate another machine. And add COLOR macros "addressing" those default values.

If I got it right that the background color can be changed to e.g. white I'd propose these four colors:
* black
* white
* red
* green

**Comment by groessler** [comment]
> Are you aware that there's infrastructure in place to get rid of call sites for CONIO color functions on targets that don't support them? See: https://github.com/cc65/cc65/blob/master/include/conio.h#L193-L214 I presume this approach to be beneficial here.

I don't think that's applicable here (Atari 5200 conio). But it could be used for the "atari" (computers) target, where `_textcolor()` maps to `return1`.

**Comment by oliverschmidt** [comment]
Why? Because of the return value? I don't think it's a good idea to return the current background value anyway.

**Comment by groessler** [comment]
> If I got it right that the background color can be changed to e.g. white I'd propose these four colors:

We have 5 colors here, one background color and four possible colors for the text.

Each of them can be changed by changing the respective palette register.

The current COLOR_ values in `_gtia.h` are the values to be written to the palette registers. But I think in conio-land the COLOR_ values should indicate what to write into the screen buffer. Which in this case would be the values 0..3.

**Comment by groessler** [comment]
> Why? 

"Why" to which piece I've said?

> Because of the return value? I don't think it's a good idea to return the current background value anyway.

You're talking about `bordercolor()`? It's defined to return something.

**Comment by oliverschmidt** [comment]
To "I don't think that's applicable here".

We have a different perspective. You say there's a border but it can't be set with `bordercolor()`. I saw, there's no border, just background. And as there's no border, there's no valie border color so `bordercolor()` can just always return 0.

Think of it, what will somebody do with the return value of `bordercolor()` other than save it to use it as parameter to `bordercolor()` at a later time - nothing.

You can for sure have a different opinion, that's fine with me. But I say, you only make the the resulting program larger by implementing `bordercolor()` to be a read-only facility.

**Comment by groessler** [comment]
Generally I tend to agree. But 0 is a valid color code. Ideally `bordercolor()` should be able to return an error. But let's not discuss this further. I can live with that, and I understand your perspective. Although the behaviour is not critically correct :-) .

**Comment by mrdudz** [comment]
i'd make it a macro.... #define bordercolor(x) ((unsigned char)0) - should give best code in most situations

**Comment by groessler** [comment]
That's more or less what Oliver suggested with https://github.com/cc65/cc65/blob/master/include/conio.h#L193-L214

**Comment by mrdudz** [comment]
that doesnt work either :)

**Comment by groessler** [comment]
explain

**Comment by mrdudz** [comment]
i misunderstood what it does, ignore :)

**Comment by groessler** [comment]
A proposal is in #870

**Comment by groessler** [comment]
#870 has been committed. Closing this issue.
