### ISSUE TITLE
ca65: Chars in `.byte "string"` are mangled

### ISSUE THREAD

**Issue by mdpye** [cc65/cc65#876]
Lower case chars are shifted to upper case, upper case to garbage.

Works with absolutely minimal reproduction. Am I missing some config?

`board.cfg`:
```
MEMORY
{
  ROM: start = $FC00, size = $0400, type = ro, define = yes, fill = yes, file = %O;
}

SEGMENTS
{
  CODE: load = ROM, type = ro;
}
````

`test.a65`:
```
.code
.byte "abcdefghijklmnopqrstuvwxyz123456789890ABCDEFGHIJKLMNOPQSTUVWXYZ !£$%^&*()-_=+"
```

command:
```
cl65 -C board.cfg test.a65
```

`hexdump -C test`:
```
00000000  41 42 43 44 45 46 47 48  49 4a 4b 4c 4d 4e 4f 50  |ABCDEFGHIJKLMNOP|
00000010  51 52 53 54 55 56 57 58  59 5a 31 32 33 34 35 36  |QRSTUVWXYZ123456|
00000020  37 38 39 38 39 30 c1 c2  c3 c4 c5 c6 c7 c8 c9 ca  |789890..........|
00000030  cb cc cd ce cf d0 d1 d3  d4 d5 d6 d7 d8 d9 da 20  |............... |
00000040  21 62 a3 24 25 5e 26 2a  28 29 2d a4 3d 2b 00 00  |!b.$%^&*()-.=+..|
00000050  00 00 00 00 00 00 00 00  00 00 00 00 00 00 00 00  |................|
*
00000400
```

`hexdump -C test.o`:
```
00000000  55 7a 6e 61 11 00 00 00  60 00 00 00 09 00 00 00  |Uzna....`.......|
00000010  69 00 00 00 07 00 00 00  70 00 00 00 b3 00 00 00  |i.......p.......|
00000020  23 01 00 00 01 00 00 00  24 01 00 00 01 00 00 00  |#.......$.......|
00000030  25 01 00 00 02 00 00 00  28 01 00 00 0b 00 00 00  |%.......(.......|
00000040  33 01 00 00 5e 00 00 00  91 01 00 00 01 00 00 00  |3...^...........|
00000050  27 01 00 00 01 00 00 00  92 01 00 00 01 00 00 00  |'...............|
00000060  02 02 04 40 af a2 c2 e5  05 01 03 2c 91 b0 5c 5c  |...@.......,..\\|
00000070  06 06 00 00 00 06 00 00  01 02 00 06 00 00 00 07  |................|
00000080  00 00 01 02 00 7c 00 00  00 08 00 4e 01 02 0a 00  |.....|.....N....|
00000090  08 41 42 43 44 45 46 47  48 01 01 00 08 49 4a 4b  |.ABCDEFGH....IJK|
000000a0  4c 4d 4e 4f 50 01 01 00  08 51 52 53 54 55 56 57  |LMNOP....QRSTUVW|
000000b0  58 01 01 00 08 59 5a 31  32 33 34 35 36 01 01 00  |X....YZ123456...|
000000c0  08 37 38 39 38 39 30 c1  c2 01 01 00 08 c3 c4 c5  |.789890.........|
000000d0  c6 c7 c8 c9 ca 01 01 00  08 cb cc cd ce cf d0 d1  |................|
000000e0  d3 01 01 00 08 d4 d5 d6  d7 d8 d9 da 20 01 01 00  |............ ...|
000000f0  08 21 62 a3 24 25 5e 26  2a 01 01 00 06 28 29 2d  |.!b.$%^&*....()-|
00000100  a4 3d 2b 01 01 06 00 00  00 09 00 00 01 02 00 06  |.=+.............|
00000110  00 00 00 0a 00 00 01 01  00 06 00 00 00 0b 00 00  |................|
00000120  01 02 00 00 00 00 00 00  02 00 00 00 00 00 02 00  |................|
00000130  00 00 00 0c 00 07 5f 5f  43 42 4d 5f 5f 07 5f 5f  |......__CBM__.__|
00000140  43 36 34 5f 5f 08 74 65  73 74 2e 61 36 35 19 63  |C64__.test.a65.c|
00000150  61 36 35 20 56 32 2e 31  37 20 2d 20 47 69 74 20  |a65 V2.17 - Git |
00000160  37 38 64 61 66 38 34 66  05 2e 73 69 7a 65 04 43  |78daf84f..size.C|
00000170  4f 44 45 06 52 4f 44 41  54 41 03 42 53 53 04 44  |ODE.RODATA.BSS.D|
00000180  41 54 41 08 5a 45 52 4f  50 41 47 45 04 4e 55 4c  |ATA.ZEROPAGE.NUL|
00000190  4c 00 00                                          |L..|
00000193
```

**Comment by mdpye** [comment]
I see `C64` in the object file. It's being mapped to PETSCII, isn't it?

**Comment by groessler** [comment]
try `-t none` in the `cl65` command line. The default target, if not specified, is C64

**Comment by mdpye** [comment]
Wonderful, thank you!

I didn't find anything in the docs to point in this direction. I wonder where it should be mentioned.

**Comment by groessler** [comment]
It's written in https://cc65.github.io/doc/intro.html#toc5

But, maybe, the default target should be changed to "none"? Why should c64 be the first among peers in this regard?

**Comment by mdpye** [comment]
> -t sys, --target sys
> The default for this option is different from the compiler and linker, in the case that the option is missing: While the other tools (compiler, assembler, and linker) will use the "none" system settings by default, cl65 will use "c64" as a target system by default. That was chosen because most people seem to use cc65 to develop for the C64.

It's there, but the behaviour is somewhat confusing when you're supplying your own `-C` already.

**Comment by mdpye** [comment]
> But, maybe, the default target should be changed to "none"? Why should c64 be the first among peers in this regard?

That is a good question. It might be a convenience too far.

Regardless, thanks for the extremely quick answer, I wish I'd posted here earlier!

**Comment by greg-king5** [comment]
> It's there, but the behaviour is somewhat confusing when you're supplying your own `-C` already.

`-C` is for the linker, not for any other tool.  A `-t` is needed for the compiler and the assembler.

**Comment by greg-king5** [comment]
> `test.a65:`
> ```asm
> .code
> .byte "abcdefghijklmnopqrstuvwxyz123456789890ABCDEFGHIJKLMNOPQSTUVWXYZ !£$%^&*()-_=+"
> ```
> command:
> ```sh
> cl65 -C board.cfg test.a65
> ```
> `hexdump -C test:`
> ```
> 00000000  41 42 43 44 45 46 47 48  49 4a 4b 4c 4d 4e 4f 50  |ABCDEFGHIJKLMNOP|
> 00000010  51 52 53 54 55 56 57 58  59 5a 31 32 33 34 35 36  |QRSTUVWXYZ123456|
> 00000020  37 38 39 38 39 30 c1 c2  c3 c4 c5 c6 c7 c8 c9 ca  |789890..........|
> 00000030  cb cc cd ce cf d0 d1 d3  d4 d5 d6 d7 d8 d9 da 20  |............... |
> 00000040  21 62 a3 24 25 5e 26 2a  28 29 2d a4 3d 2b 00 00  |!b.$%^&*()-.=+..|
> 00000050  00 00 00 00 00 00 00 00  00 00 00 00 00 00 00 00  |................|
> *
> 00000400
> ```

Notice that `£` is Unicode, not ASCII.  Your editor put _two_ "strange" bytes into the source file.

**Comment by mdpye** [comment]
Heh, utf-8/latin1 confusions I can recognise immediately, petscii was new to me...

**Comment by oliverschmidt** [comment]
>> But, maybe, the default target should be changed to "none"? Why should c64 be the first among peers in this regard?

> That is a good question. It might be a convenience too far.

* This decision goes back to the creator and initial maintainer of cc65. I wouldn't have done it this way for sure. However, changing it now would cause a lot of confusion. There are quite some cc65 users seemingly not even knowing that there are other 6502 machines (supported by cc65). You can see this i.e. from their bug reports not mentioning the machine they have their issue on.

* cl65 was in general meant as convenience feature. The actual compiler, assembler and linker do _NOT_ default to the C64. If this makes sense to you or if you consider this causing even more confusion is up to you ;-)

**Comment by denzuko** [comment]
Also  going to add, since after three days of researching into this, if one is using PETSCII they should be using KERNEL rom functions. If they're using direct SCREEN ram then you'll need to use the SCREEN codes table not the CHR$ codes table.

For for the correct vector values be sure to review Appendix B on page 396 of the [Programmer's Reference Guide](http://cini.classiccmp.org/pdf/Commodore/C64%20Programmer's%20Reference%20Guide.pdf)
