### ISSUE TITLE
Linker doesn't throw error for multiply defined symbols

### ISSUE THREAD

**Issue by groessler** [cc65/cc65#878]
Is there a reason that only a warning is generated? Other compilers (linkers) throw an error.

main.c:
```c
#include <stdio.h>
#ifdef __CC65__
#include <conio.h>
#endif

extern int testfun(void);

int main(void)
{
        printf("testfun returned %d\n", testfun());
#ifdef __CC65__
        cgetc();
#endif
        return 0;
}
```
t1.c:
```c
int testfun(void)
{
        return 1;
}
```
t2.c:
```c
int testfun(void)
{
        return 2;
}
```
compile:
```sh
$ cl65 -tatari -o t.com main.c t2.c t1.c 
ld65: Warning: Duplicate external identifier: '_testfun'
$ ls -l t.com
-rw-r--r--. 1 chris chris 3129 Apr 25 13:17 t.com
$ 
```

**Comment by groessler** [comment]
No opinions or comments?
So I've created a PR (#880) to go ahead....

**Comment by silverdr** [comment]
Not an opinion but.. maybe the standard has something to say about it?

**Comment by spiro-trikaliotis** [comment]
The standard does not care about linking, IIRC.

**Comment by oliverschmidt** [comment]
What about this scenario? You start out with

mainc.c:
```
#include <stdio.h>

extern int testfoo(void);
extern int testbar(void);

int main(void)
{
        printf("testfoo returned %d\n", testfoo());
        printf("testbar returned %d\n", testbar());
        return 0;
}
```

t1.c:
```
int testfoo(void)
{
        return 1;
}

int testbar(void)
{
        return -1;
}
```

So you can do:
```
cl65 -t sim6502 main.c t1.c
sim65 main
testfoo returned 1
testbar returned -1
```

Now you want to change the behavior of `testfoo()` without modifying `t1.c`. Right now that's easy:

t2.c:
```
int testfoo(void)
{
        return 2;
}
```

This allows for:
```
cl65 -t sim6502 main.c t2.c t1.c
ld65: Warning: Duplicate external identifier: '_testfoo'
sim65 main
testfoo returned 2
testbar returned -1
```

With the change you propose that's not possible anymore. Therefore I personally think the current warning is just right.

**Comment by groessler** [comment]
Do you really consider your example to be a valid use case? If yes, how would you do the same with other compilers?

**Comment by oliverschmidt** [comment]
> Do you really consider your example to be a valid use case?

Yes, I do. I even know projects making use of it.

> If yes, how would you do the same with other compilers?

I don't know - and I don't care for cc65 projects.

**Comment by groessler** [comment]
If you say so. I'm considering this feature more dangerous than good.

**Comment by mrdudz** [comment]
isnt this "overloading" something even libraries that come with cc65 make use of? (like the soft80 conio). without it, we'd need an entire different mechanism for this.

**Comment by oliverschmidt** [comment]
@mrdudz: Actually not. A library is just an "offer" to the linker where it can get symbols it's looking for. If a symbol is already found in an object file (or another library), the library is just ignored.

Only if an object from a library is "pulled in" because it offers a needed symbol, any other symbol exported from the same object could trigger the issue discussed here.

**Comment by mrdudz** [comment]
so the above mentioned scenario could result in a "symbol declared twice" error, without breaking the mechanism used to link those libraries?

if that is the case, please make it so.

**Comment by oliverschmidt** [comment]
@mrdudz: Unfortunately I don't understand you. To help avoid misunderstandings: The soft80 conio does _not_ trigger the warning in question. So turning that warning into an error as suggested by @groessler wouldn't affect it.

**Comment by mrdudz** [comment]
> The soft80 conio does not trigger the warning in question. So turning that warning into an error as suggested by @groessler wouldn't affect it.

Thats what i said - if that is the case, please make the warning an error. You could make it a warning and allow the overloading using some commandline switch (thats the behaviour i have seen elsewhere)

**Comment by oliverschmidt** [comment]
I see. I agree with that approach:

Treating double symbols as error by default but having an option to suppress the error (no warning as well) would be fine with me. I'd consider this an improvement over the current "compromise".

**Comment by mrdudz** [comment]
i'd rather still have the warning and even make it more verbose and tell where the symbol comes from that is actually used. because in a large project it might not be obvious. like:

ld65: Warning: Duplicate external identifier: '_testfun', using symbol from t2.o

**Comment by oliverschmidt** [comment]
* If a specific option is necessary to generate a binary then the user is supposed to know what he's doing.
* The information which symbols are taken from where is in the map file.

**Comment by oliverschmidt** [comment]
I wanted to express that I don't see the need for a warning. But I don't have an issue with a warning either.

**Comment by groessler** [comment]
Ok. I'd be willing to implement the command line swicth. Any idea how it should be called?
As proposal: "--allow-dup-syms"

**Comment by groessler** [comment]
@mrdudz: I agree that a more verbose warning would be better, but I don't intend to implement it at this time. I had just stumbled over this issue, and am now investing time which wasn't planned.
Feel free to provide a PR which improves the warnings/errors.

**Comment by oliverschmidt** [comment]
> Ok. I'd be willing to implement the command line swicth.

:-)

> Any idea how it should be called? As proposal: "--allow-dup-syms" (and no short option for it).

It seems that GNU ld calls it `--allow-multiple-definition`. I suggest to just adopt that.

**Comment by groessler** [comment]
I've updated the PR.

**Comment by oliverschmidt** [comment]
Thanks :-)
