### ISSUE TITLE
"Error: Conflicting types" with no difference.

### ISSUE THREAD

**Issue by bastetfurry** [cc65/cc65#882]
I have the following files in ./src with the generic Makefile for cc65:

main.c:
```c
#include <conio.h>
#include <stdint.h>

#include "eltesto.h"

void main()
{
	uint8_t lastkey;
	eltesto();

	while(1)
	{
		clrscr();
		lastkey = cgetc();
	}
}
```
eltesto.c:
```c
#include "eltesto.h"

unsigned char foo[32][32];

void eltesto()
{
}
```
eltesto.h:
```c
#ifndef __ELTESTO_H
#define __ELTESTO_H

extern unsigned char foo[32][32];
void eltesto();

#endif
```
Running make, i get the error:
```
src/eltesto.c(6): Error: Conflicting types for 'eltesto'
```
But, i see no difference between the declarations in eltesto.c and eltesto.h; what is the problem, or did i stumble upon a bug?

I am using:
```
cc65 V2.17 - Git 37f80534
```

**Comment by clbr** [comment]
It's an old C thing. Your eltesto.h should have "void eltesto(void);", otherwise it thinks it has varargs.

**Comment by bastetfurry** [comment]
Then it seems that cc65 got stricter over the years, in an older version this worked. Thanks for the help! :smile_cat:

**Comment by Fabrizio-Caruso** [comment]
@bastetfurry C is different from C++ in some respects.
void argument is not the same as no argument.

**Comment by Compyx** [comment]
In standard C `int foo()` means an unspecified number of arguments, which can also be none, (basically allowing pre-ANSI/ISO or K&R C). This is different from varags, which takes the form of `int foo(some_type name, ...)`.

In C++, AFAIK `int foo()` means the same as `int foo(void)` . I do not currently have the C standard handy, so I can't quote chapter and verse. So basically use proper prototypes, if a function doesn't accept arguments. use `int foo(void)`, if using varags, use `int foo(<type> bar, ...)`.

**Comment by greg-king5** [comment]
Commit a0db846a9772ef82cf7163670e7a2fc109ec4b53 fixes the issue.  "Normal" K&R programs should compile (with warnings about obsolete features).  Also, cc65 should be able to compile programs that have a mixed use of K&R and ANSI styles.
