### ISSUE TITLE
[question] Passing a macro to Assembly through -D? How?

### ISSUE THREAD

**Issue by Fabrizio-Caruso** [cc65/cc65#887]
In: https://github.com/Fabrizio-Caruso/C64_Multiplexer_C_LIB

I use DEBUG through IFDEF to enable/disable some debug lines in an Assembly file.

I would like to pass the value of DEBUG through the -D but I have not managed so far:
```
...
debug:
	$(CC65_PATH)$(MYCC65)$ $(CCFLAGS) main.c -o main.s
	$(CC65_PATH)$(MYCL65)$ $(CCFLAGS) $(MYCFG) -DDEBUG=1 main.s $(ASMFILES) -o multiplexer.prg
...
```
will not pass DEBUG=1 to the Assembly file.

How can I use macros in combination of IFDEF (or something similar)?

**Comment by mrdudz** [comment]
use --asm-define

**Comment by Fabrizio-Caruso** [comment]
Thanks!
