### ISSUE TITLE
[question] How to have c64.inc definitions in Asesmbly?

### ISSUE THREAD

**Issue by Fabrizio-Caruso** [cc65/cc65#888]
If I compile my C/Assembly project with -t c64, I would like to have the definitions in c64.inc.
I thought they would be included with -t c64, but this is not the case.

What do I need to do to import those definitions?

**Comment by oliverschmidt** [comment]
Just some alternatives to opening an issue for this type of question:

1. Read documentation: https://cc65.github.io/doc/ca65.html#ss11.67

2. Abtract from things already known: C, `#include` -> asm, `.include`.

3. Look for examples: Just about any cc65 source file, e.g. https://github.com/cc65/cc65/blob/master/libsrc/c64/bordercolor.s

**Comment by Fabrizio-Caruso** [comment]
Sorry, I tried to grep c64.inc but I was stupid enough to do it in the precompiled distribution...
