### ISSUE TITLE
[C128][sp?][question] Random writes at $2bf8-$2bff. Is the stack the culprit? 

### ISSUE THREAD

**Issue by Fabrizio-Caruso** [cc65/cc65#891]
In: https://github.com/Fabrizio-Caruso/C64_Multiplexer_C_LIB/blob/master/cfg/c128_multiplexer_sid_at_2400_gfx_at_3000.cfg
Because of the way interrupts and banks work on the C128, I need to have the interrupt routines at visible bank and I have defined two code segments:
```
MEMORY {
    ZP:       file = "", define = yes, start = $0002, size = $001A;
    LOADADDR: file = %O,               start = $1BFF, size = $0002;
    HEADER:   file = %O, define = yes, start = $1C01, size = $000C;
    MAIN:     file = %O, define = yes, start = __HEADER_LAST__,  size = __SIDSTART__ - __HEADER_LAST__, fill = yes, fillval=$2A;
    SID:      file = %O, define = yes, start = __SIDSTART__,     size = __SIDSIZE__, type = rw,  fill = yes, fillval=$2B;   
    GFX:      file = %O, define = yes, start = __GFXSTART__,     size = __GFXSIZE__, type = rw,  fill = yes, fillval=$2C;
    EXTRA:    file = %O, define = yes, start = $4000, type = rw, size = $8000 - __STACKSIZE__; 
}
SEGMENTS {
    ZEROPAGE: load = ZP,       type = zp;
    LOADADDR: load = LOADADDR, type = ro;
    EXEHDR:   load = HEADER,   type = ro;
    STARTUP:  load = MAIN,     type = ro;
    LOWCODE:  load = MAIN,     type = ro,  optional = yes;
    ONCE:     load = MAIN,     type = ro,  optional = yes;
    CODE:     load = MAIN,     type = ro;
    CODE2:    load = EXTRA,    type = ro;
    SID:      load = SID,      type = ro;
    RODATA:   load = EXTRA,    type = ro;
    DATA:     load = EXTRA,    type = rw;
    INIT:     load = MAIN,     type = bss;
    GFX:      load = GFX,      type = rw;    
    BSS:      load = MAIN,     type = bss, define   = yes;
```
The code is compiled with: -O -Cl. So I expect no sofwtare stack but it seems I am wrong because the binary is using $02 (I guess the software stack pointer) to address and overwrite locations $2bf8-$2bff where some sid code is located. I see STA ($02),Y writing in those locations.
I am guessing $02=sp from https://github.com/cc65/wiki/wiki/Using-runtime-zeropage-locations-in-assembly-language but I am not sure.

How can I avoid the software stack in those locations?
I would like to have the software stack at the end of the memory area that starts at $4000 (currently named EXTRA) and not in the middle of the SID memory area.

Maybe I need to move the stack and find some other way to avoid this issue.
I do not understand and cannot find an example on how to follow:
https://github.com/cc65/wiki/wiki/Parameter-and-return-stacks#Moving_the_stack
Is the stack position hard-coded and infered in a way that is not user-configurable with the .cfg?
Should I write something like?
STACK: file="", define=yes, start=$d000-__STACKSIZE__, size=__STACKSIZE__;
No .crt file is distributed with the CC65 snapshot. I guess it is only in the source code. It looks like something the user should not fiddle with. I can try to modify it but I would like to know if there is a simpler/smarter way.

**Comment by oliverschmidt** [comment]
> the binary is using $02 (I guess the software stack pointer)

That's correct. The software stack pointer is the first zero page variable - and the zero page segment starts at $0002 according to your .cfg file.

> [...] overwrite locations $2bf8-$2bff where some sid code is located. I see STA ($02),Y writing in those locations.

https://cc65.github.io/doc/c128.html#s3 says

_The C runtime stack is located at $BFFF, and growing downwards._

so if $0002 is pointing to $2Bxx I'd say something in your program is already very broken.

> Is the stack position hard-coded and infered in a way that is not user-configurable with the .cfg?

Yes. The startup code contains: https://github.com/cc65/cc65/blob/master/libsrc/c128/crt0.s#L59-L62

**Comment by Fabrizio-Caruso** [comment]
Thanks! The code is OK but the cfg is not good because the stack is hard-coded at an offset of main_start and I made a very small MAIN. Maybe I need do invert the name of the c code areas MAIN and EXTRA.
By the way, why is the stack location not freely configurable?

**Comment by oliverschmidt** [comment]
> By the way, why is the stack location not freely configurable?

According to my knowledge that's (only?) because of https://github.com/cc65/cc65/blob/master/libsrc/common/_heap.s

The heap is hard-coded to reside between the BSS and the stack. However, I'm aware that there are quite some programs not using the heap at all. At least for them it might make sense to allow to have the stack somewhere else.

There's even more to it: On the ATARI the lowest address a program can use isn't fixed but depends on the OS (and its config). On the other hand the highest address a program can use is fixed. So when I'm actaully right it would be preferable to load programs so that they end just below the highest address and then have the heap and stack use space below the program. This way the user could choose between a larger heap and a "richer" OS.

**Comment by Fabrizio-Caruso** [comment]
The doc is a bit misleading in that it seems tonsay one should declare the STACK.
Maybe the stack should be user-definible at least when the heap is not used (common case)

**Comment by Fabrizio-Caruso** [comment]
I have fixed my specific issue by inverting MAIN and EXTRA and keeping STARTUP in MAIN
