### ISSUE TITLE
How can I use plain ASCII charset/encoding for string literals in C programs instead of PETSCII for C64 programs?

### ISSUE THREAD

**Issue by lgblgblgb** [cc65/cc65#894]
Sorry for the possible lame question, but I couldn't figure out how to do this. I have several cross-platform projects, ie where I want the (almost the) same source to be compiled for C64 and for a native build (for Linux, but it does not matter too much) as well. I want to use ASCII even on C64, with my custom charset and/or "mangled" charset in the RAM copied/mangled from the ROM. However it seems I couldn't find a way to tell cc65 toolchain not to translate string literals to PETSCII but leave it as they are in the source byte-by-byte (as in the source, so what gcc/clang/etc compilers would do as well), without any PETSCII conversion. Since I don't use any stdio / etc functionality of cc65, it should not cause problem. For CA65 I can use .CHARMAP maybe, but now I'm interested in the C compiler of CC65 package more.

Thanks!

**Comment by oliverschmidt** [comment]
> For CA65 I can use .CHARMAP maybe, but now I'm interested in the C compiler of CC65 package more.

https://cc65.github.io/doc/cc65.html#ss7.3

I haven't tried it but I guess the following works and I personally would maybe prefer it if it actually works:

- Compile your C source files for the 'none' target (`-t none`) and defining the two macros `__CBM__` and `__C64__` (`-D__CBM__` and `-D__C64__`).

- Link your object files for the C64 target (`-t c64`) against `c64.lib`.

**Comment by groessler** [comment]
To extend what Oliver said, if you want to use C64-specific things, spit out the charset handling routines into separate C files and compile them with `-t none`, and the rest with your target.

I'm using e.g. this in a separate file to convert ASCII chars received over the serial line to upper case:

```
/* used by uprcas.c
 * compiled separately with "-t none" to use plain ASCII charset
 */
void work(char *buf, int len)
{
    while (len--) {
        if (*buf >= 'a' && *buf <= 'z')
            *buf = *buf - 'a' + 'A';
        ++buf;
    }
}
```

**Comment by oliverschmidt** [comment]
>  [...] if you want to use C64-specific things [...]

This sort of implies that it isn't possible to call into C64-specific library code from a module compiled with `-t none`. However, that isn't true from what I understand. The only things to take care of I see:
- Char classification and string comparison may behave unexpected.
- Functions exchanging strings with the OS like fopen() require PETSCII.

**Comment by lgblgblgb** [comment]
Thanks for the suggestions, I've quickly tried this approach and seems to work nicely. I'm not sure if it can be done, but it would be superb to have some kind of pragma directive or such to modify the encoding even within a single source, or at least a command line switch for cc65 (maybe for cl65 too, as for the whole project) to set these kind of things. Maybe for other purposes than ASCII too, ie there can be a project with direct "screen codes" used to "poke" into the video RAM instead of using PETSCII or ASCII (though indeed, that one is not the best idea, as '@' has screen code of zero, which is used to terminate strings ... ). In fact, I even had the idea to put .CHARMAP into __asm__(...) but certainly it does not work too much since I cannot put that outside of a function into the "global scope" too much ...

**Comment by oliverschmidt** [comment]
> Maybe for other purposes than ASCII too, ie there can be a project with direct "screen codes" used to "poke" into the video RAM instead of using PETSCII or ASCII (though indeed, that one is not the best idea, as '@' has screen code of zero, which is used to terminate strings ... ).

https://github.com/cc65/cc65/blob/master/include/cbm_petscii_charmap.h
https://github.com/cc65/cc65/blob/master/include/cbm_screen_charmap.h

**Comment by groessler** [comment]
Maybe we could create an `ascii_charmap.h' in similar vain with 1:1 mappings?

**Comment by oliverschmidt** [comment]
Absolutely!

**Comment by lgblgblgb** [comment]
Aaaa ... OK, thanks. No more questions :)

**Comment by groessler** [comment]
@lgblgblgb, you're welcome to make that contribution :-)

**Comment by lgblgblgb** [comment]
Probably I will, currently I am busy with Mega65/Commodore65 specific things (in fact, I use cc65 for that purpose now needing ASCII based workflow for native SD-card access FAT32-level stuff ... so I can test FAT32 "driver" with both of "native" build on my Linux and on the "real thing" as well). But sounds interesting, indeed, if I do such a thing at cc65 source level, i try to to push it back to the cc65 mainstream for sure. Thanks again.
