### ISSUE TITLE
Memory ZP is very small in most targets?

### ISSUE THREAD

**Issue by bbbradsmith** [cc65/cc65#904]
This is a question about the various default CFG files found in targets. I am noticing that quite a few of them have a ZP memory defined as size $1A or $1B.

Why is this not $100? (...or maybe $FE for C64 which starts at $0002.)

It seems like this just makes most of the zero page unusable without a custom CFG, and I don't understand why we'd want to do that. Especially if a project contains an assembly component, it's very helpful to be able to place variables on the zero page.

**Comment by bbbradsmith** [comment]
Looking at it, it seems like the purpose of the ZEROPAGE segment is supposed to be reserved for cc65 internals only, and not intended to be used at all, otherwise?

**Comment by bbbradsmith** [comment]
(I'll close this, I guess I have enough of an answer for myself with that.)

**Comment by oliverschmidt** [comment]
At least on the Apple II there are two reasons:

1. The zero page locations used are saved at program startup and restored on program shutdown. Increasing the amount of zero page locations used increases the size of that save area.

2. The C library calls into ROM and OS functions to perform things like user I/O and mass storage I/O. Those ROM / OS functions use (on the Apple II most) zero page locations. Using them by the program would require to dynamically save and restore zero page values. That would make the C library function in question larger and slower.

Apart from that - as you noticed - the memory areas in a CFG file don't reflect the hardware properties but reflect the hardware resource the environment in question is willing to reserve for the cc65 program. Otherwise there would never be a reason to have more than one CFG file for a certain hardware.

**Comment by PeterCamilleri** [comment]
It seems to me that cfg files lacking a usable zero page are of no value. In order to get anything
done with the simulator I need to restore the full zero page. I can see no reason that a simulated
processor would need a crippled zero page.

**Comment by bbbradsmith** [comment]
I can't think of a benefit for keeping the ZP in sim6502.cfg small, either. Since discovering sim65 a few months ago, I've used a custom CFG with the ZP memory size increased to 256 bytes every time I've used it.

Do any of the cc65 internal unit tests rely on ZP being small for sim6502.cfg?

I can't really comment on the CFG for any other platform, though. More or less universally I use custom CFGs anyway.

**Comment by oliverschmidt** [comment]
https://github.com/cc65/cc65/commit/d5c804f851c2dcf187a640b320cc49d466bfc76d

**Comment by dmsc** [comment]
Hi!

> [d5c804f](https://github.com/cc65/cc65/commit/d5c804f851c2dcf187a640b320cc49d466bfc76d)

Sorry for not replying earlier, but I thought that the purpose of SIM65 was to test the compiler and run-time library, so the allocated ZP space would need to be the same as the smaller of any target.

This way, if some future change overflows the ZP it will fail the regression tests.

By having a big ZP area, you won't catch any of those errors.

Have Fun!

**Comment by groessler** [comment]
One can always use his/her own linker script. As @dmsc said, it makes sense to have a "small" ZP area by default.

**Comment by mrdudz** [comment]
i agree, the default zeropage should provide what cc65 needs. for anything else you will most likely need a custom config anyway.

**Comment by PeterCamilleri** [comment]
I dunno, maybe the cc65 cfg file could be called cc65_test.cfg?  I mean it does not seem right to need a custom cfg just to test generic code.

**Comment by bbbradsmith** [comment]
I can't think of any consequence it can catch other than ZP overflow, but that's a build-time error that any of the platform build tests should catch already. I don't think any of the sim65 tests have much added potential there? Their purpose is to test run-time errors.

I do understand the desire for symmetry with the default C configs on other platforms. Regressions often come from unknown sources... but the potential for this particular mismatch to hide a useful error seems vanishingly small? I can't even think of how to write a piece of code that fits into the cc65 project that could generate this error only in the sim65 tests.


The reason I'd suggest making ZP larger for sim65's default config is so that it can be more useful as a tool for others, rather than just being a private internal test for cc65 itself.

Other real platform targets are something that users can be expected to have knowledge of and can reference their experience with, which is needed when preparing custom configurations. However for the sim65 platform, only cc65 maintainers should really be expected to have the requisite internal knowledge of the sim65 platform.

So really that's why I think increasing its default ZP is valuable: it makes it easier for a non-expert cc65 user to write a unit test with. It's normal for 6502 code to make use of the zero page, and the default sim65 config could facilitate this.

Conversely I think the lost error coverage for internal use is insignificant.
