### ISSUE TITLE
Question: structure addresses within asm statements

### ISSUE THREAD

**Issue by Wrathchild70** [cc65/cc65#915]
Could a statement such as:
asm("lda %v", GTIA_READ.pal);
ever be possible?

**Comment by greg-king5** [comment]
> Could a statement such as:
> ```c
> asm("lda %v", GTIA_READ.pal);
> ```
> ever be possible?

`GTIA_READ.pal` isn't the name of a variable; it's an expression.  It expands to
```c
*(unsigned char *)(0xD000 + 0x14)
```
Maybe, we could create another format specifier that does this work-around:
```c
asm("lda %w", (unsigned)&GTIA_READ.pal);
```

**Comment by Wrathchild70** [comment]
Thanks for the work-around, I'd tried with the ampersand but not the unsigned cast.

**Comment by oliverschmidt** [comment]
This was explicitly classified in the title as question. The question is answered with a successful workaround (thanks @greg-king5). I'd say it's appropriate to close this issue...
