### ISSUE TITLE
[question][bug?] Missed optimization with unsigned short? Or just lucky optimization when using extra variables?

### ISSUE THREAD

**Issue by Fabrizio-Caruso** [cc65/cc65#916]
I have already reported this unexpected behavior in the mailing list.
I don't know which is the best place where to report this. Please close this issue if you think that the mailing list is the only place where to discuss this.

In my mini-project in: https://github.com/Fabrizio-Caruso/Primitive-Pythagorean-Triples
I am getting a faster binary by using "worse" source code.
I need to set an unsigned short with some computed value, but I get significantly faster code if I first store the value in a variable, i.e., something like this:
```c
  c1 = da+tc-db;
  *(foo) = c1; 
```
is faster than
```c
  *(foo) = da+tc-db; 
```
Why is that possible? Is the optimizer missing an optimization with the code without the extra variable?

The actual code is in:
https://github.com/Fabrizio-Caruso/Primitive-Pythagorean-Triples/blob/master/PPT.c
where I select the two alternatives with:
```c
#if defined(USE_MORE_VARIABLES)
		a2 = a+db+dc;
		a3 = a2-da;
		b1 = da+dc-b; 
		b3 = (dc<<1)-b1;
		c1 = da+tc-db;
		c3 = s-da;
		enqueue(a1); enqueue(b1); enqueue(c1);
		enqueue(a2); enqueue(b1+db); enqueue(da+s);
		enqueue(a3); enqueue(b3); enqueue(c3);
#else
		a2 = a1 + (db<<1);	
		b1 = da+dc-b; 
		enqueue(a1); // a1
		enqueue(b1); // b1
		enqueue(da+tc-db); // c1		
		enqueue(a2); // a2
		enqueue(b1+db); // b2
		enqueue(da+s); // c2
		enqueue(a2-da); // a3
		enqueue((dc<<1)-b1); // b3
		enqueue(s-da); // c3	
#endif
```
where `enqueue()` is just a macro:
```c
#define enqueue(item)  \
               *(tail++) = (number_t)(item)
```
Remark: I get the same unexpected speed-up even if I remove the `++` operator from the enqueue macro. The problem is not related to the `++` operator IMHO.

**Comment by acqn** [comment]
When you write
```c
*(foo) = da+tc-db; 
```
the compiler has to backup the left-hand-side (lhs) expression `*(foo)` before dealing with the right-hand-side (rhs) expression `da+tc-db`. Since the evaluation of rhs could use up the very limited supply of registers and built-in ZPs, the lhs has to be backed up on the cc65 stack.

However, when you write
```c
c1 = da+tc-db;
*(foo) = c1;
```
then the compiler can use `c1` the lhs on the first line directly and no longer need to back it up before evaluating `da+tc-db`, and when it is evaluating `*(foo)` on the second line, `da+tc-db` is already "backed up" in `c1` and can be loaded back directly too.

**Comment by polluks** [comment]
Maybe we should document that compact expressions will not always lead to compact code?

**Comment by Fabrizio-Caruso** [comment]
@acqn Thanks for allow for explaining the reason of the problem. 
For me this is not the expected behavior a C compiler should have, though. Clearly better written code should not produce worse binary in a very common situation such as an assignment. It is not a even a very rare case where such unexpected behavior appears. Basically all assignments of this type should be split into two assignments and the user should now about it as this is not uncommon.
If we cannot easily fix this, we should document it to invite people to write such workarounds when using CC65.
I do not get this behavior on other 8-bit cross compilers (e.g., Z88DK) for the reasons you explained.

**Comment by MonteCarlos** [comment]
@acqn 
Hmm, normally i would guess the compiler evaluates expressions according to the precedence and left right order. As according to the c precedence, the "+" and "-" has priority over "=" it would be expected that the rhs is evaluated first, then backed up, then the lhs is evaluated and then the backup is assigned to the lhs. I would make me really wonder if the lhs is evaluated first.

**Comment by acqn** [comment]
I was talking about the problem in general with some old impression. In fact, PR #1053 (some time after this issue) improved the optimizer dealing with storing via a pointer. So the performance could be increased.

**Comment by acqn** [comment]
> 
> 
> @acqn
> Hmm, normally i would guess the compiler evaluates expressions according to the precedence and left right order. As according to the c precedence, the "+" and "-" has priority over "=" it would be expected that the rhs is evaluated first, then backed up, then the lhs is evaluated and then the backup is assigned to the lhs. I would make me really wonder if the lhs is evaluated first.

I am one of the few "Left-to-Right-Evaluation-Order-for-All" advocators. ;)
What about `a + b = c`?

**Comment by MonteCarlos** [comment]
@acqn 
I see your point: `m[a +b] = c` vs. `c = m[a + b]`. How should the compiler decide which is evaluated left and right and which right to left. Seems to be a matter of convention.
