### ISSUE TITLE
MVN/MVP are broken in v2.18

### ISSUE THREAD

**Issue by fadden** [cc65/cc65#925]
In v2.17 the args for MVN and MVP were switched.  In v2.18 the args are ignored:

```
% PATH=$PATH:$HOME/cc65-2.17/bin/ cl65 --target none Simple.S           
% xxd Simple
00000000: 4401 0254 0304 60                        D..T..`
% PATH=$PATH:$HOME/cc65-2.18/bin cl65 --target none Simple.S
% xxd Simple
00000000: 4400 0054 0000 60                        D..T..`
```

Code is:

```
        .setcpu "65816"
        mvp 1,2
        mvn 3,4
        rts

```

Tested with the "Windows snapshot" (cl65.exe V2.18 - Git 3d63a8b) and tip-of-tree on Linux (cl65 V2.18 - Git 3d63a8bb).

**Comment by greg-king5** [comment]
ca65 can accept two types of operands for those instructions: "immediate" and "far address".  It will extract bank numbers from far addresses.
```
$ ca65 -l test-mvp.lst test-mvp.s
$ cat test-mvp.lst
ca65 V2.18
Main file   : test-mvp.s
Current file: test-mvp.s

000000r 1               	.setcpu	"65816"
000000r 1               	.import	label1:far, label2:far
000000r 1               
000000r 1  44 02 01     	mvp	#1, #2
000003r 1  54 04 03     	mvn	#3, #4
000006r 1               
000006r 1  44 rr rr     	mvp	label1, label2
000009r 1  54 rr rr     	mvn	label2, label1
00000Cr 1               
00000Cr 1  60           	rts
00000Cr 1               
```

**Comment by fadden** [comment]
Interesting.  Assuming two labels with 24-bit addresses:

`mvp 1, 2` - works in Merlin 32, 64tass, ACME; generates zeroes in cc65
`mvp #1, #2` - works in Merlin 32, 64tass, cc65; errors in ACME
`mvp label1, label2` - works in Merlin 32, cc65; errors in 64tass, ACME
`mvp #label1, #label2` - works in Merlin 32; errors in 64tass, ACME, cc65

Life would be easier if you guys spoke to each other. :-)

FWIW, the assembler used for the examples in "Programming the 65816" by Eyes & Lichty, and the Orca/M assembler that Apple shipped as part of the IIgs tools, did not use '#' for immediate arguments on MVN/MVP.  So you've strayed a bit from the "official" form.
