### ISSUE TITLE
Compiler now mishandles pointer comparison rules (regression)

### ISSUE THREAD

**Issue by EtchedPixels** [cc65/cc65#935]
An older compiler was OK but it now errors

void faulty(void)
{
    unsigned char foo[8];
    const unsigned char *bar = foo;
    
    while(bar < foo + 8) {
    }
}

You can stick a cast in but pointer to pointer comparison of const v no const is not a type error, it's valid C and it happens all sorts of places.

**Comment by oliverschmidt** [comment]
The program
```
void main(void)
{
  unsigned char foo[8];
  const unsigned char *bar = foo;

  while(bar < foo + 8) {
  }
}
```
built as
```
cl65 test.c
```
builds just fine for me with
```
cl65 --version
cl65 V2.18 - Git c53b1673
```

Please clarify and re-open if appropriate.

**Comment by EtchedPixels** [comment]
Sorry it took time - but confirm this got fixed already - Fedora 30 ships a cl65 with this bug and it seems a few others. Current git head is working great.
Thanks

**Comment by oliverschmidt** [comment]
Thanks for the feedback.
