### ISSUE TITLE
Compiled C64 apps only work on first RUN.

### ISSUE THREAD

**Issue by 3vi1** [cc65/cc65#936]
I've noticed that even the simplest apps will nor run a second time without being reloaded.  Even a Hello world example has this issue.

```
#include <stdio.h>
#include <stdlib.h>

int main (void)
{
    printf ("Hello World 2!\n");
    return EXIT_SUCCESS;
}

```
This runs fine the first time you load and run it in VICE, but fails if you 'RUN' it again.

Since there's nothing in the main assembly that's self modifying:

```
;
; File generated by cc65 v 2.17 - Ubuntu 2.17-1
;
	.fopt		compiler,"cc65 v 2.17 - Ubuntu 2.17-1"
	.setcpu		"6502"
	.smart		on
	.autoimport	on
	.case		on
	.debuginfo	off
	.importzp	sp, sreg, regsave, regbank
	.importzp	tmp1, tmp2, tmp3, tmp4, ptr1, ptr2, ptr3, ptr4
	.macpack	longbranch
	.forceimport	__STARTUP__
	.import		_printf
	.export		_main

.segment	"RODATA"

L0003:
	.byte	$C8,$45,$4C,$4C,$4F,$20,$D7,$4F,$52,$4C,$44,$20,$32,$21,$0D,$00

; ---------------------------------------------------------------
; int __near__ main (void)
; ---------------------------------------------------------------

.segment	"CODE"

.proc	_main: near

.segment	"CODE"

	lda     #<(L0003)
	ldx     #>(L0003)
	jsr     pushax
	ldy     #$02
	jsr     _printf
	ldx     #$00
	lda     #$00
	jmp     L0001
L0001:	rts

.endproc

```
This would seem to indicate the _printf routine is doing something with memory it doesn't actually initialize?  Or does it generate self-modifying code?

Is this expected behavior?  I've looked through the FAQ and not seen an answer there so I'm wondering if this isn't a bug - seeing as how I'd think being able to run the same program twice without reloading would be the norm and not an exception.

**Comment by Marrin** [comment]
This is ”expected” behaviour.  Not by a C64 user but from cc65.  It's not any broken code but the linker configuration which has a segment for startup code that gets reused for variables after that startup code has run once, so that startup code portion is destroyed.  Look for the `ONCE` segment in the linker config.

**Comment by 3vi1** [comment]
Ah, I suspected something like that could be the case but wasn't sure (hence looking through the FAQ before posting here).  Thank you for confirming the behavior!

**Comment by oliverschmidt** [comment]
@3vi1: If you are interested, I can grant you write access to the Wiki and you can add the content to the FAQ you were looking for.

**Comment by 3vi1** [comment]
> @3vi1: If you are interested, I can grant you write access to the Wiki and you can add the content to the FAQ you were looking for.

Sure - I don't mind doing that, and it might help others looking for the answer who don't happen upon this closed issue.

**Comment by oliverschmidt** [comment]
Cool :-) You should have received an invitation. Please note that the cc65 Wiki is maintained in the MediaWiki format, not in the MarkDown format.
