### ISSUE TITLE
Enable all address sizes for CPU none

### ISSUE THREAD

**Issue by pinobatch** [cc65/cc65#939]
I sometimes use ca65 to write code in assembly language for an obscure CPU for which I do not want to write a whole assembler from scratch (example: #362). When I do this, I `.setcpu "none"` and implement every mnemonic as a ca65 macro.

However, I get `Error: Range error` when the assembler cannot statically prove that a particular value is less than $100. When I use `.globalzp` to assert that the value is less than $100, I get ``Warning: Symbol `memset_tiny' is absolute but exported zeropage``. When I do `.segment "LOWCODE0": zeropage` to make a label not absolute, I get `Error: Invalid address size specification for current CPU`.

What would be the drawbacks of making all three address size specifications (`zeropage`, `absolute`, and `far`) valid for the `none` CPU?

**Comment by polluks** [comment]
This is the particular code https://github.com/cc65/cc65/blob/153bb295010e2dc75ffd544d7091870ff563338d/src/common/cpu.c#L98

**Comment by greg-king5** [comment]
I think that the original idea is that the `none` CPU has no instructions; therefore, it has no addressing modes.  But, that makes it useless!  I agree with you; we should go in the opposite direction.  `none` should have no limits -- even "long" addresses should be allowed.

**Comment by oliverschmidt** [comment]
I fully agree. @greg-king5: Thanks for taking care.

**Comment by greg-king5** [comment]
Done: 2e5fbe89cd3f67b06b292936dfdf4fdb104b7112.
