### ISSUE TITLE
[bug][gamate][conio] Text is displayed in inverted colors

### ISSUE THREAD

**Issue by Fabrizio-Caruso** [cc65/cc65#941]
Text is displayed with inverted characters in REAL hardware but clrscr is correct.
Maybe an issue with one of the bitplanes.

Test code:
```
#include <conio.h>
int main()
{
    clrscr();
    gotoxy(4,4);
    cprintf("hello world");
    while(1){};
    return 0;
}
```

![gamate](https://user-images.githubusercontent.com/29057615/66042415-ad3fdf00-e51c-11e9-9d47-fed541090d1d.jpeg)

**Comment by Fabrizio-Caruso** [comment]
The problem could be in https://github.com/cc65/cc65/blob/master/libsrc/gamate/cputc.s where I see:
```
        eor     RVS
        sta     LCD_DATA
```
twice (for both bit-planes).

Mame is NOT accurate and you do not see this error but you do see it on real hardware.

**Comment by Fabrizio-Caruso** [comment]
I have made a pull request with a fix:  #942

**Comment by Fabrizio-Caruso** [comment]
This PR also contains a commit about a hello world example for the Supervision target.
I know I should have created two separate PRs. I hope this is not a problem.

**Comment by greg-king5** [comment]
`eor RVS` is needed by conio's `revers()` function.

I think that the bug is in "gamate/conio.s".  The `initconio` subroutine doesn't initiate the `RVS` variable to `$00`.  At "power on", the zero page RAM seems to settle to `$FF`, which is equivalent to calling `revers(1);`.

**Comment by Fabrizio-Caruso** [comment]
@greg-king5  thanks! So sta RVS in conio.s (with zero in A) would fix the problem. Wouldn't it?
Should I close or update the PR?
P.S.: The PR also has commits about a Supervision helloworld example.

**Comment by groessler** [comment]
Try this:

```
diff --git a/libsrc/gamate/crt0.s b/libsrc/gamate/crt0.s
index 5a5bb3aa..94d1f19c 100644
--- a/libsrc/gamate/crt0.s
+++ b/libsrc/gamate/crt0.s
@@ -8,6 +8,7 @@
         .import         __RAM_START__, __RAM_SIZE__
 
         .include        "zeropage.inc"
+        .include        "extzp.inc"
         .include        "gamate.inc"
 
 Start:
@@ -19,6 +20,7 @@ Start:
 
         ldx     #0
         stx     ZP_IRQ_CTRL     ; disable calling cartridge IRQ/NMI handler
+        stx     RVS
 
         ; Set up stack and memory mapping
         ;ldx     #$FF            ; Stack top ($01FF)
```

**Comment by Fabrizio-Caruso** [comment]
@groessler  why not in sta RVS in conio.s?

**Comment by groessler** [comment]
> @groessler why not in sta RVS in conio.s?

Where would you want to put it there? It should be initialized once (at startup). If you unconditionally set it in conio.s, the revers() function would crease to work.

**Comment by groessler** [comment]
Sorry. Hadn't looked at the actual code. So conio.s should be fine, even better than in crt0.s.

**Comment by Fabrizio-Caruso** [comment]
I have made PR #945 (tested by @PlamenVaysilov on real hardware) with a hopefully good fix in conio.s.

**Comment by oliverschmidt** [comment]
As far as I see fixed by https://github.com/cc65/cc65/pull/945.

@Fabrizio-Caruso: Thanks for your contribution.
