### ISSUE TITLE
[Supervision] missing screen init in crt

### ISSUE THREAD

**Issue by Fabrizio-Caruso** [cc65/cc65#943]
I propose to have supervision crt file iniialize the screen (on and res set to 160x160) as I have done in the tentative PR #942 

I would like to do a PR with this.

**Comment by greg-king5** [comment]
It's a good idea.

I'm curious about the "bank" value.  Is there any documentation about it, on the internet?

**Comment by Fabrizio-Caruso** [comment]
@greg-king5 Where exactly in crt0.s for Supervision should I put the init code?
I was thinking of something as simple as:
```
LDA #$0A
STA $2000
STA $2001
LDA #$C9
STA $2026
```
Should I put this lines just after `jsr donelib` ?

@PlamenVaysilov is the expert. He has provided me with some docs (attached here).
[Supervision_Tech.txt](https://github.com/cc65/cc65/files/3687261/Supervision_Tech.txt)
[EQU_Watara.zip](https://github.com/cc65/cc65/files/3687263/EQU_Watara.zip)

**Comment by Fabrizio-Caruso** [comment]
@greg-king5 I have tried to put that code in different places but it does not work for some reasons.
I am not able to inspect the crt0.o file and see whether the code is generated.
If I put the very same code as inlined Assembly in my special helloworld test, it does work so I fear something else rewrites on those registers.

**Comment by Fabrizio-Caruso** [comment]
I have made the PR #944 with a helloworld example for Supervision.
This helloworld example contains the init code.
I have not moved it to crt0.s (I have tried).

**Comment by Fabrizio-Caruso** [comment]
The helloworld code is now a unit-test for the screen init code in crt0.s. :-)

**Comment by Fabrizio-Caruso** [comment]
@greg-king5  is this OK for you?
@oliverschmidt  are there any guidelines for new examples? Supervision had none.

**Comment by oliverschmidt** [comment]
@greg-king5 wrote:
> It's a good idea.

Unfortunately I have to disagree: Either the target has CONIO support then it belongs in a CONIO constructor. Or the target has no CONIO support then it's up to the user to do everything necessary in his program - which seems to work just fine here.

**Comment by Fabrizio-Caruso** [comment]
@oliverschmidt does the user have to tell the video control it is attached to a Supervision display?160x160 is the only possible case for the Supervision.
Other values make sense for othe consoles with the same video control that may have existed.

**Comment by PlamenVaysilov** [comment]
Values must be from 0 to 0xFF , but if value is 0x00 nothing is show on screen . 0x00 is a default value on Power Up and if you forget to init this values with value different from 0x00 Watara screen will be blank .

**Comment by Fabrizio-Caruso** [comment]
@PlamenVaysilov  yes, now my understanding is that the video controller could handle other displays but for the Supervision only 160x160 makes sense.

**Comment by Fabrizio-Caruso** [comment]
@oliverschmidt  anyway I remove the lcd setting from crt if you think so. Coild you please tell me how to proceed?

**Comment by oliverschmidt** [comment]
@Fabrizio-Caruso:

I think I understand your argument well: 160 is the only viable value, so why not "just set it".

My reasons against it:

* I think the environment the C programmer sees should be either 'blank' and 'complete'. With 'complete' I refer to something like fully working CONIO. As long as we don't have that I prefer 'blank' meaning just the bare minimum to be able to transfer control to main() with nothing initialized or taken care of. It's a matter of consistency.

* It seems that neither you nor me have really understood how the startup code and the linker configuration works. When there's a momentum to implement CONIO it makes sense to invest into understanding it. But I don't want to invest that effort now just for the LCD init.

**Comment by Fabrizio-Caruso** [comment]
Perfect! I will do as you say. What about the helloworld example? Is it OK? Should I just put the lcd init there and leave it in thus PR? Or should create a second one?

**Comment by Fabrizio-Caruso** [comment]
@oliverschmidt why just init with conio? It should be initialized with stdio as well. A simple printf statement should print something on the screen. Should't it?

**Comment by groessler** [comment]
> Unfortunately I have to disagree: Either the target has CONIO support then it belongs in a CONIO constructor.

I tend to disagree with you. Screen output is not just CONIO. The startup code should setup the screen to sane values, especially in this case where anyway apparently just one value makes sense.

**Comment by greg-king5** [comment]
> Why just init with conio? It should be initialized with stdio, as well. A simple printf() statement should print something on the screen. Shouldn't it?

No.  Traditionally, stdio is for cc65 platforms that already have firmware (or operating systems) that supports input and output.  Stdio connects to those ROM functions.  The ROM does most of the work.

Most of conio's functionality is in the cc65 libraries.  In theory, all of cc65's targets can have conio; but, only some of them can have stdio.

**Comment by Fabrizio-Caruso** [comment]
@greg-king5 Don't Atari5200 and Gamate have stdio? I see stdio almost as part of the C language.
If stdio becomes available on a target, then I would expect:
```
#include <stdio.h>
int main(void){
  printf("hello, world\n");
}
```
to produce the same screen on the screen for any stdio-enabled target.

**Comment by oliverschmidt** [comment]
> No. Traditionally, stdio is for cc65 platforms that already have firmware (or operating systems) that supports input and output. Stdio connects to those ROM functions. The ROM does most of the work.

Full ACK. Thanks for explaining.

**Comment by groessler** [comment]
> I see stdio almost as part of the C language.

Not officially. The C99 standard states:

5.1.2.1 Freestanding environment
...
Any library facilities available to a freestanding program, other than the minimal set required by clause 4, are implementation-defined.

Clause 4 mentions the headers <float.h>, <iso646.h>, <limits.h>, <stdarg.h>, <stdbool.h>, <stddef.h>, <stdint.h>.

stdio is not part of this list.

**Comment by spiro-trikaliotis** [comment]
> > I see stdio almost as part of the C language.
> 
> Not officially. The C99 standard states:
> 5.1.2.1 Freestanding environment

Note that most people would not consider a freestanding environment as C, but a hosted.
A freestanding environment is somewhat special.

And: Yes, I know that cc65 does not completely qualify for a hosted environment.

**Comment by groessler** [comment]
> Note that most people would not consider a freestanding environment as C, but a hosted.

Nitpicking, it doesn't matter what "most people" think, but what is defined by the language.
I can write boot loaders in C without any "C" libraries, for example. I think I'm using C for that.

> cc65 does not completely qualify for a hosted environment.

Yep. And it depends on the target. In my eyes the "bigger" machines (Apple, Atari, CBMs) would more or less qualify as hosted environment (even if cc65 cannot run on them).

**Comment by greg-king5** [comment]
> Don't Atari5200 and Gamate have stdio? I see stdio almost as part of the C language.
> If stdio becomes available on a target, then I would expect:
> ```c
> #include <stdio.h>
> void main(void) {
>   printf("Hello, world!\n");
>   for (;;) {}
> }
> ```
> to produce the same thing on the screen for any stdio-enabled target.

It does produce the same thing on all cc65 targets that have stdio.  And,
```c
#include <conio.h>
void main(void) {
  clrscr();
  cprintf("Hello, world!\r\n");
  for (;;) {}
}
```
gives us the same thing on all targets that have conio.

Atari5200 and Gamate have only conio.
You can look at the subdirectories of ["libsrc/"](https://github.com/cc65/cc65/tree/master/libsrc).  If a subdirectory has a file named "cputc.s", then that target has conio.  If it has files named "read.s" and "write.s", then that target has stdio.

**Comment by oliverschmidt** [comment]
Clarified in https://github.com/cc65/cc65/pull/944.
