### ISSUE TITLE
[creativision][bug?] Lack of COLOR_BLACK and COLOR_WHITE (samples/hello.c won't compile)

### ISSUE THREAD

**Issue by Fabrizio-Caruso** [cc65/cc65#948]
If I try to compile samples/hello.c for the Creativition target, I get an error about missing COLOR_BLACK and COLOR_WHITE definitions.

**Comment by polluks** [comment]
Well, no conio, therefore no colours.

**Comment by oliverschmidt** [comment]
Hm, looking at https://github.com/cc65/cc65/tree/master/libsrc/creativision there seems to be CONIO stuff...

**Comment by greg-king5** [comment]
The macro names are prefixed with `C_` instead of `COLOR_`.

**Comment by Fabrizio-Caruso** [comment]
@pollucks I am using conio with the Creativision
