### ISSUE TITLE
Semicolon comment in .cfg file breaks error handling

### ISSUE THREAD

**Issue by white-flame** [cc65/cc65#954]
Accidentally starting a ld65 config file with a semicolon comment (instead of hash) breaks the error reporting, yielding only this:

`ld65: Check failed: SPtr != 0, file 'common/xsprintf.c', line 571`

The printout of `"%s expected, got '%s'"` appeared to be called with "Block identifier" and a NULL for its parameters, the NULL being rejected by the printf mechanism as above.

A mitigation would be to have a `|| "NULL"` somewhere in the CHECK mechanism's reporting.

**Comment by greg-king5** [comment]
Fixed by 4f24a06f0e06ea420ef6ec995ed86260aba8749a.
