### ISSUE TITLE
[tgi][lynx][bug] Last column in characters is shown with black foreground color

### ISSUE THREAD

**Issue by Fabrizio-Caruso** [cc65/cc65#957]
The last column in characters is shown with black foreground color:
```c
#include "display_macros.h"
#include "graphics_settings.h"
#include <tgi.h>
#define CLI() asm("\tcli")
int main(void)
{
    tgi_install (tgi_static_stddrv);
    tgi_init ();        
    CLI();
    tgi_clear();
    while (tgi_busy())  {  };
    tgi_setpalette(tgi_getdefpalette());
    tgi_setbgcolor(TGI_COLOR_GREY);
    tgi_setcolor(TGI_COLOR_RED);
    tgi_outtextxy(8*6,8,"** ##"); 
    tgi_setcolor(TGI_COLOR_WHITE);
    tgi_outtextxy(8,8,"** ##"); 
    while(1){};
    return 0;
}
```
![image](https://user-images.githubusercontent.com/29057615/66701852-04a23400-ed01-11e9-8b5a-49452eba7669.png)

**Comment by greg-king5** [comment]
That suggests an answer to my question:  The Suzy bug shows at the right edge of the sprite.

Probably, we'll need to squeeze the font: 7 x 8 instead of 8 x 8.

**Comment by Fabrizio-Caruso** [comment]
Squeeze but print it in 8x8 blocks.
This bugs was not present in the previous code.

**Comment by Fabrizio-Caruso** [comment]
Having a ninth transparent 1-pixel column would avoid the tedious work on the fonts.
This would re-introduce the previous bug on just a single 1-pixel wide column if no extra bit planes are used.

**Comment by Fabrizio-Caruso** [comment]
@greg-king5 I ran `\$.(0|2|4|6|8|A|C|E)` on the font bytes and only find 11 characters with even bytes, namely:
13, 23, 31, 
35, 38, 42, 47, 52, 
237, 247, 255

If you accept my help, I could redesign those 11 fonts. It is tedious but it is just 11 characters. Not such a big deal.

**Comment by Fabrizio-Caruso** [comment]
@greg-king5 I have made the PR #958 with a tentative fix for you to tell if it is OK.
I can fix the remaining 6 characters if this PR is OK for you.

**Comment by Fabrizio-Caruso** [comment]
@greg-king5 My pull-request now contains fixes for the 11 characters. It could already be merged as is. It could be improved later but I see no problems. 
Could you please take a look at it?
