### ISSUE TITLE
[lynx][bug][cgetc] cgetc does not consume the input

### ISSUE THREAD

**Issue by Fabrizio-Caruso** [cc65/cc65#959]
It seems that `cgetc()` does not consume the input; i.e., if a key is pressed, then subsequent `cgetc()` will still read the same value (or a non-zero value).

The problem may be in the debouncing detection in `kbhit()`:
https://github.com/cc65/cc65/blob/master/libsrc/lynx/kbhit.s

This problem can be reproduced with:
```c
#include <tgi.h>
#include <conio.h>
#define CLI() asm("\tcli")
int main(void)
{
    tgi_install (tgi_static_stddrv);
    tgi_init ();        
    CLI();
    tgi_clear();
    while (tgi_busy())  {  };
    tgi_setpalette(tgi_getdefpalette());
    tgi_setbgcolor(TGI_COLOR_GREY);
    tgi_setcolor(TGI_COLOR_RED);
    tgi_outtextxy(8,8*0,"step 0"); 
    cgetc();   
    tgi_outtextxy(8,8*1,"step 1"); 
    cgetc();   
    tgi_outtextxy(8,8*2,"step 2"); 
    cgetc();   
    tgi_outtextxy(8,8*3,"step 3"); 
    while(1){};
    return 0;
}
```
There is no wait to go through step 1 and 2. 
You can only get one of the two pictures below:
![image](https://user-images.githubusercontent.com/29057615/66718640-62f51280-ede6-11e9-875d-7957c9002820.png)

![image](https://user-images.githubusercontent.com/29057615/66718634-596baa80-ede6-11e9-8b6b-4d16f5a1b03c.png)

**Comment by Fabrizio-Caruso** [comment]
@greg-king5 the pull-request seems ready to me. Could you please review it? I have tested it and followed @pollucks advice. "cgetc" waits for input with my fix as it should.

**Comment by Fabrizio-Caruso** [comment]
@greg-king5, @polluks is there any problem or things left to do for this PR to be merged?

**Comment by Fabrizio-Caruso** [comment]
@brianpeek let us discuss the cgetc issue here

**Comment by BrianPeek** [comment]
Ok, a fairly tiny repro is at https://github.com/BrianPeek/SpriteTestLynx .  This sample uses the kbhit()/cgetc() combo as described earlier.

With the changes made to cgetc(), I don't believe there's a way to determine in a non-blocking/per-frame way that one of the Lynx's special keys was pressed.  cgetc() blocks for input, and first testing with kbhit() swallows the character as cgetc() no longer checks if the previous kbhit() set keys.

In the above sample, the game will block at cgetc() if I press Opt1, then will continue if I press it a 2nd time, where the kbhit() being called in side cgetc() captures the input.

Hope that helps explain what I'm seeing.  Thanks!

**Comment by Fabrizio-Caruso** [comment]
@BrianPeek could you please point me to the tiny example? I do not find it in your .c files.

I understand there is a problem now... I might revert the changes but cgetc will be wrong, anyway.

**Comment by BrianPeek** [comment]
This should link to the specific line:

https://github.com/BrianPeek/SpriteTestLynx/blob/master/src/main.c#L120

**Comment by oliverschmidt** [comment]
Just to be sure I'd like to mention that the goal of any kbhit()/cgetc() implementation mustn't be to expose "some" useful behavior, but to expose the defined behavior.

At least according to my perspective the basic idea is:
* kbhit() never blocks.
* cgetc() never blocks when called once after kbhit() returned 1.

The second point implies some sort of buffering on whatever level (hardware, firmware, C library). Otherwise the keystroke could disappear after having called kbhit() but before calling cgetc().

**Comment by Fabrizio-Caruso** [comment]
@oliverschmidt maybe this is fixed by having `cgetc` check `KBEDG` instead of calling `kbhit` inside `cgetc`

**Comment by greg-king5** [comment]
> Maybe this is fixed by having `cgetc()` check `KBEDG` instead of calling `kbhit()` inside `cgetc()`.

`kbhit()` must do that.  If `KBEDG` is non-zero, then return it immediately -- don't check the buttons.  (All non-zero values mean "true"; therefore, the function always can return `KBEDG`; it doesn't need to use the `return1` function.)

`cgetc()` must clear `KBEDG` after the function has finished using it.

**Comment by Fabrizio-Caruso** [comment]
@greg-king5 I am not sure I understand how I can modify `kbhit()` as you say. The code is also setting other stuff which is needed (apparently)...
![image](https://user-images.githubusercontent.com/29057615/67704008-a3db5280-f9b4-11e9-966e-a006c1cb0fcf.png)

**Comment by Fabrizio-Caruso** [comment]
@greg-king5 @BrianPeek I am going to try this solution:
`kbhit` sets `KBSTL` and `KBEDG` and other variables (as it currently) and returns with the value of `KBEDG` in A. I suppose I must set X as well (with `TAX`) in order to have `kbhit` work correctly.

`cgetc` will check A, if zero it calls `kbhit `and loops indefinitely, if different from zero it will run its current code to detect the pressed key. It will also have to sey KBEDG to zero before returning.

**Comment by Fabrizio-Caruso** [comment]
@greg-king5 could you please take a look at PR #966?
