### ISSUE TITLE
unable to link files created with ar65

### ISSUE THREAD

**Issue by alytle** [cc65/cc65#962]
I'm positive this is something I'm doing incorrectly, but I cannot seem to understand the issue. If I link my program against the raw object files, it works correctly. If I compile objects into a library with `ar65` I get `Unresolved external` errors.

Here's a trivial example:

lib-part1.c:
```
void function1(void) {}
```

lib-part2.c:
```
void function2(void) {}
```

lib.h:
```
void function1(void);
void function2(void);
```

main.c
```
#include <lib.h>

void main(void) {
    function1();
    function2();
}
```

Compiling Library Code:
```
$ cc65 -t cx16 -O -I. lib-part1.c
$ cc65 -t cx16 -O -I. lib-part2.c
```

Assembling:
```
$ ca65 -t cx16 lib-part1.s
$ ca65 -t cx16 lib-part2.s
```

Compiling and Linking Against Object Files:
```
$ cl65 -t cx16 --lib lib-part1.o --lib lib-part2.o -I. main.c
```

Archiving:
```
$ ar65 r test.a lib-part1.o lib-part2.o
```

Compiling and Linking Against Archive:
```
cl65 -t cx16 --lib test.a -I. main.c
Unresolved external '_function1' referenced in:
  main.s(28)
Unresolved external '_function2' referenced in:
  main.s(29)
ld65: Error: 2 unresolved external(s) found - cannot create output file
```

Any thoughts on what I'm doing incorrectly?

**Comment by oliverschmidt** [comment]
> `cl65 -t cx16 --lib lib-part1.o --lib lib-part2.o -I. main.c`

This should rather read `cl65 -t cx16 -I. main.c lib-part1.o lib-part2.o`.

> `cl65 -t cx16 --lib test.a -I. main.c`

This needs to read `cl65 -t cx16 -I. main.c test.a` instead.

Reason: The order of the files given does matter. By the time `test.a` is processed the symbols to be found must already been known in order to have them found there.

**Comment by alytle** [comment]
Argh, I knew it was something simple. Thanks for the assist.
