### ISSUE TITLE
[ca65][question] Macros syntax for operations on parameters

### ISSUE THREAD

**Issue by Fabrizio-Caruso** [cc65/cc65#963]
I am trying to handle the x-coordinate in multiplexed C64/C128 sprites, and I need to do this 16 times.
So, I am trying to do this with a macro, but I am not sure about the syntax for the operations on the parameters of the macro.  (`spr_number` is the virtual sprite number and `spr_number & 7` is the corresponding real sprite).
Is `& 7` OK to compute the modulo 8 of the parameter `spr_number`?
Does the macro below make any sense?
```asm
    .macro handle_x spr_number 
        LDA SPRX+spr_number
        ASL                                 ; multiply by 2
        STA VIC_SPR0_X+(spr_number & 7)*2   ; weird effects when sprite
        LDA VIC_SPR_HI_X                    ; Load actual VIC_SPR_HI_X value        
        BCS :+                              ; if > 255 set sprite MSB in VIC_SPR_HI_X
        AND ANDTBL+(spr_number & 7)         ; Do a logic AND operation to set actual sprite bit OFF
        JMP :++
    :
        ORA ORTBL+(spr_number & 7)          ; Do a logic OR operation to set actual sprite bit ON
    :
        STA VIC_SPR_HI_X                    ; and store new value back to the VIC_SPR_HI_X register.
    .endmacro
```

**Comment by greg-king5** [comment]
> Does the macro below make any sense?
> ```asm
> .macro handle_x spr_number 
>     LDA SPRX+spr_number
>     ASL                                 ; multiply by 2
>     STA VIC_SPR0_X+(spr_number & 7)*2   ; weird effects when sprite
>     LDA VIC_SPR_HI_X                    ; Load actual VIC_SPR_HI_X value        
>     BCS :+                              ; if > 255, set sprite MSB in VIC_SPR_HI_X
>     AND ANDTBL+(spr_number & 7)         ; Do a logic AND operation to set actual sprite bit OFF
>     JMP :++
> :
>     ORA ORTBL+(spr_number & 7)          ; Do a logic OR operation to set actual sprite bit ON
> :
>     STA VIC_SPR_HI_X                    ; and store new value back to the VIC_SPR_HI_X register.
> .endmacro
> ```

It should work.
You don't need to use `ANDTBL` and `ORTBL` there; ca65 can create the bit masks in the operand expressions:
```asm
    AND #<~(%1 << (spr_number & 7))     ; Do a logic AND operation to set actual sprite bit OFF
    JMP :++
:
    ORA #%1 << (spr_number & 7)         ; Do a logic OR operation to set actual sprite bit ON
```

**Comment by Fabrizio-Caruso** [comment]
Thanks a lot!

**Comment by MonteCarlos** [comment]
use bit instead of jmp.
