### ISSUE TITLE
_afailed does not reset screen and kernal resources before outputting debug message

### ISSUE THREAD

**Issue by MonteCarlos** [cc65/cc65#972]
_afailed should be usable also from grafics mode and redirected irq's / nmi's. So instead of just outputting a debug message, the _afailed function should 
1.) disable irq
2.) reset screen, irq/nmi pointers and zeropage etc.
3.) output debug message
4.) reenable irq
5.) terminate

I could do this for the c64 target. however, the _afailed code is in the common directory. So there needs to be some means to add target dependent code to the assertion. Maybe a target depended function resetResources() which is called before outputting the debug message.

**Comment by oliverschmidt** [comment]
In general I see see here conceptual problems:
* Code that resets irq/nmi pointers and zeropage is supposed to live in crt0.
* Code that sets/resets "the screen" etc. is supposed to live in TGI drivers.

Apart from that the issue isn't really limited/specific to _afailed(). You could i.e. generally expect exit() to "somehow" call tgi_done() "if necessary".

**Comment by MonteCarlos** [comment]
i see this objections. the afailed code calls exit, which could be a starting point. however the screen needs to be reset before the ouput of the debug message is done. also other preconditions need to be met so that the print statement is able to perform correctly. f.e zeropage io locations, vic registers, ram vectors of rom routines and so on. if exit would perform this it would come too late. 
it would greatly enhance the usability of the assert if one could rely on proper output of the debug message and proper exit. there are many cases in which the print of the afailed would just lead to crash.

**Comment by oliverschmidt** [comment]
Likely there's a misunderstanding. I very well understand the issue. It's just that I don't see a good-enough solution (incl. your proposal).

**Comment by polluks** [comment]
@oliverschmidt I agree, printf is printf, no system has a fallback.

**Comment by greg-king5** [comment]
Actually, `assert()` has a bug.  It fails to send the `SIGABRT` signal if the assertion fails.  (It's supposed to call `abort()`, but ours calls `exit()` so that it can return a different exit code [`2` instead of `3`].)  Commit ac4866c027b881b9cde2b4195cac0988eb3ca411 added an explicit call to `raise()` that signal.  Now, a programmer can catch the signal, and do whatever clean-up is needed to make `stderr` work.

**Comment by oliverschmidt** [comment]
@greg-king5: Thanks :-)

I suggest to consider Greg's commit a fix and close this issue.

**Comment by MonteCarlos** [comment]
Ok, i see that there is no easy solution and the sigabrt provides a clean hook for a custom solution.
So i close this issue, now.

**Comment by MonteCarlos** [comment]
Btw. are there some named constants for those exit codes?

**Comment by polluks** [comment]
@MonteCarlos Nothing but EXIT_SUCCESS and EXIT_FAILURE
