### ISSUE TITLE
Hardcoded values for exit codes

### ISSUE THREAD

**Issue by MonteCarlos** [cc65/cc65#974]
Searching the codebase many exit commands use already the named symbols EXIT_SUCCESS and EXIT_FAILURE, but some of them return 0 or 1. I would offer of regexing them and replacing them by the appropriate named constants for consistency. However there are also exit codes -1, 2, 3 being used. What is their meaning and what would be appropriate named constants.

**Comment by oliverschmidt** [comment]
> I would offer of regexing them and replacing them by the appropriate named constants for consistency.

That would be appreciated.

> What is their meaning and what would be appropriate named constants.

Personally I'm not aware of named constants for those values.

**Comment by polluks** [comment]
Maybe we should define 0..127 as user return code and 128..255 as system return code?
So `PRINT STATUS` in BASIC is negative.

**Comment by MonteCarlos** [comment]
i won't change the existing codes and values 2 as well as 3 are already used for abort and assert failed. that's why the range of system exit codes, if this is not going too far, should include at least the values 2 and 3.

**Comment by MonteCarlos** [comment]
i replaced all the hardcoded 0,1 exit code with EXIT_SUCCESS and EXIT_FAILURE respectively. however in the following i was unsure if the momentary exit code represents the correct situation?
dbg.c, line 1583 : shouldn't this be 0(EXIT_SUCCESS ) instead?
yacc.c, line 412: shouldn't be a failure returned on error?

would it be appreciated to add an enum to cc65.h holding the custom cc65 exit codes?

**Comment by polluks** [comment]
Well, you may say DbgEntry is always abnormal.
Done yacc myself #976. Enums are welcome :-)

**Comment by MonteCarlos** [comment]
ok, in this case i would leave a comment that debugger returns with failure intentionally because of that reason you told. just hitting quit would not be a reason to return failure itself.

**Comment by MonteCarlos** [comment]
i will add that enum and make a pull request, then

**Comment by MonteCarlos** [comment]
am i right to close this issue, as the corresponding pull request has been merged?

**Comment by oliverschmidt** [comment]
Yes, thanks :-)
