### ISSUE TITLE
[Atari] Calls to SIOV can hang due to disabled interrupts.

### ISSUE THREAD

**Issue by tschak909** [cc65/cc65#983]
The test program I have written here:
https://github.com/tschak909/atariwifi/blob/master/tests/scanwifi/atari/src/main.c

Fails if using _sys(&r); to JSR to SIOV due to a disabled interrupt.

I have worked around the problem for now by doing

```
asm("CLI; JSR $E459");
```

but maybe there is something that needs to be fixed?

-THom

**Comment by polluks** [comment]
Do you know who disables the interrupt?

**Comment by tschak909** [comment]
nope, am guessing that the I flag that gets passed in may be undefined due
to it being on the stack. (Jon Halliday suggested this.), and it's being
explicitly set due to the PLP that happens as part of the _sys() cmd.

-Thom

**Comment by flashjazzcat** [comment]
> Do you know who disables the interrupt?

The regs struct in this case was allocated off the stack and the caller did not initialise the 'flags' field (to zero) first. I don't think there's actually any problem.

**Comment by dmsc** [comment]
Hi!

> The test program I have written here:
> https://github.com/tschak909/atariwifi/blob/master/tests/scanwifi/atari/src/main.c
> 
> Fails if using _sys(&r); to JSR to SIOV due to a disabled interrupt.

I don't understand, in that code, at line 271 there is an explicit SEI(): 
https://github.com/tschak909/atariwifi/blob/4db7c9bffeaa75cca0fb8a88962a70ddf11f57b6/tests/scanwifi/atari/src/main.c#L271

You can't call into OS routines with the I flag set.

**Comment by flashjazzcat** [comment]
The code has been revised somewhat since the problem was encountered; SEI() wasn't there before but in any case it's contradicted by the CLI() in sio_wifi_scan, so is redundant anyway. I guess both can be removed.

**Comment by greg-king5** [comment]
> > Do you know who disables the interrupt?
> 
> The regs struct in this case was allocated off the stack, and the caller did not initialise the `flags` field (to zero) first. I don't think there's actually any problem.

You're correct.  The bug was in the program, not the library.
