### ISSUE TITLE
[atari] What is actually happening, here? Is there a bug?

### ISSUE THREAD

**Issue by tschak909** [cc65/cc65#984]
Apologies for the lack of a description, but this is a bit of an unusual use case for CC65, to the point where I am not sure what may be malfunctioning:

I am trying to write a CIO handler for Atari, to do a new device for a network adapter.

In order for this to work, I am prototyping a CIO handler in C. There are three main parts to it:

The main(), which injects a new device table with pointers to the new N: device:
https://github.com/tschak909/atariwifi/blob/master/tests/cio2/atari/src/main.c

The assembler stubs, which call back into the C code:
https://github.com/tschak909/atariwifi/blob/master/tests/cio2/atari/src/cio-stubs.s
It also handles putting the return values into the right registers before the return to CIO.

And the C functions themselves, the problem code is here:
https://github.com/tschak909/atariwifi/blob/master/tests/cio2/atari/src/cio-get.c#L16

If I use a variable index into the array, the return values get corrupted (both ret and err, causing BASIC to spew an error), however, if I use a constant (e.g. [0] [1] [2] whatever, then my ret and err values get returned correctly.

The test program I am using once AUTORUN.SYS is loaded, is this

```
OPEN #1,4,0,"N:"
GET #1,A
```

What could be happening, here?
-Thom

**Comment by dmsc** [comment]
Hi!

You can't mix BASIC and C compiled code with the default linker script.

The problem is that the C code uses a few zero page locations, and those interfere with BASIC usage of the locations. So, you have to tell the linker (via a modified linker script) the portion of ZP that is available for code called from BASIC.

**Comment by tschak909** [comment]
I have a modified linker script anyway, which entries do I need to change?
-Thom

**Comment by tschak909** [comment]
ok, so I scooted the ZP up to $CB-$FF, and that seems to work.
Thanks! Good catch, that makes perfect sense.
-Thom
