### ISSUE TITLE
Incorrect code of pi in cputc

### ISSUE THREAD

**Issue by luckboy** [cc65/cc65#988]
Cputc function for c64 and other cbm platforms prints pi for $fe code. Pi has $ff code in petscii.

**Comment by greg-king5** [comment]
$DE is the PetSCII code for Pi.  $FF is BASIC's _token_ for Pi -- it really should have been implemented there, not in Kernal (it causes that kind of confusion)!

**Comment by greg-king5** [comment]
RUN this BASIC program:
```BASIC
10 get c$
20 if c = "" goto 10
30 print asc(c$);
40 goto 10
```
 Type the Pi character.  You will see `222`, not `255`.

**Comment by luckboy** [comment]
Also, pi code is $ff  in petscii. See https://en.wikipedia.org/wiki/PETSCII.

**Comment by luckboy** [comment]
Run command in basic:
`printchr$(255)`
Also, prints pi.

**Comment by greg-king5** [comment]
> Run command in BASIC:
> `printchr$(255)`
> Also, prints pi.

As I wrote: "it _should_ have been implemented in the BASIC interpreter, not in the Kernal ROM".

**Comment by luckboy** [comment]
Cputc directly prints character to screen without kernal. I checked putchar function and this function correctly print character with $ff code or putchar prints pi. But, cputc incorrectly prints character with $ff code.

> I don't want that bug in cputc().

This is bug of cputc function.

**Comment by polluks** [comment]
> As I wrote: "it _really should have been_ implemented in the BASIC interpreter, _not_ in the Kernal ROM". It's a bug in Kernal [`printchr$(255)` _should_ show the same glyph that `printchr$(191)` shows]. I don't want that bug in `cputc()`.

@greg-king5 Well, right now we have a bug, the 254, in the bug fix. So this issue should be reopened...

**Comment by mrdudz** [comment]
the correct petscii code to use for printing text is the one asc() gives you. 255 in this case.

**Comment by greg-king5** [comment]
> The correct petscii code to use for printing text is the one `asc()` gives you. 255 in this case.

It's 222.  See https://github.com/cc65/cc65/issues/988#issuecomment-560229435.

The keyboard scanner produces the proper PetSCII code.  The bug is that Kernal's screen editor then does a job that _should_ be done by the BASIC interpreter:

PetSCII|BASIC Token|Comment
-|-|-
`+`|170, $AA|converted by BASIC
`-`|171, $AB|converted by BASIC
`*`|172, $AC|converted by BASIC
`/`|173, $AD|converted by BASIC
`^`|174, $AE|converted by BASIC
`>`|177, $B1|converted by BASIC
`=`|178, $B2|converted by BASIC
`<`|179, $B3|converted by BASIC
`π`|255, $FF|(incorrectly) converted by the screen editor

**Comment by mrdudz** [comment]
what do you expect cputc(255) to print then? and shouldnt it be somewhat compatible to existing petscii files (which most certainly use 255 for pi)?

**Comment by greg-king5** [comment]
@polluks, yes, I agree that the current implementations are broken.  But, I say that the bug isn't that they make an exception for the wrong character; the bug is that they make an exception, at all.

> What do you expect `cputc(255)` to print then? And, shouldn't it be somewhat compatible to existing petscii files (which most certainly use 255 for pi)?

Those PetSCII files are broken.

I expect this program to produce two lines that are _exactly_ the same:
```C
#include <conio.h>

void main(void)
{
    char c;

    cbm_k_bsout(0x8E);
    clrscr();
    cputc('\n');
    for (c = 0xA0; c < 0xC0; ++c) {
        cputc(c);
    }
    cputs("\r\n");
    for (c = 0xA0 + 0x40; c != 0x00; ++c) {
        cputc(c);
    }
    cputc('\n');
}
```

**Comment by mrdudz** [comment]
> Those PetSCII files are broken.

uh. so is the kernal. thats not an answer at all. so you prefer a "correct" implementation which will not work correctly with pretty much all files "out there"? that makes no sense to me.

**Comment by greg-king5** [comment]
> So, you prefer a "correct" implementation which will not work correctly with pretty much all files "out there"? That makes no sense to me.

`cputc()` doesn't work with most control codes.  And, it shouldn't work with BASIC tokens.

**Comment by mrdudz** [comment]
*sigh* another function that has to be monkey patched to work as expected :(

**Comment by polluks** [comment]
@mrdudz The 255 may be a hint in the documentation.

**Comment by mrdudz** [comment]
I'd like to understand what the problem really is here. 255 is used in files in the real world (often!). That means if cputc does no more understand it, every program that deals with real world files must implement a special case check for 255.

On the other hand, the 255 being "wrong" is purely academical. Nothing breaks if cputc() produces a pi for 255.

So WHY would you not do this? Makes no sense to me.

**Comment by polluks** [comment]
> and shouldnt it be somewhat compatible to existing petscii files (which most certainly use 255 for pi)?

Our implementation is broken for many years, so the issue seems to be academical at all ;-)

**Comment by mrdudz** [comment]
coming back to this...

> Our implementation is broken for many years, so the issue seems to be academical at all ;-) It's not a critical runtime function, you know what I mean.

Again, that is irrelevant. The question is "what is the correct code". I don't see a good reason not to use the table from the C64 manual as a reference - but "fix" the function based on someones pet theories. The original issue still needs to be fixed for that matter - And my proposal would still be to fix it according to the official documentation AND common usuage in the past 30 years or so.

That said, the issue still exists, the first answer contains the fix, it should get merged and this issue closed.

**Comment by polluks** [comment]
Well, Greg said the manual is buggy... However I will be happy if you just mention the value in the documentation.

**Comment by mrdudz** [comment]
> Greg said the manual is buggy

No, he didnt say that - and it is not. There is no need to mention the value in the documentation either, because 255 _is a valid petscii code for pi_. Every CBM related documentation will tell exactly that. The only actual bug is the one that the first answer fixes.

**Comment by polluks** [comment]
Save two bytes
````
--- cputc.s.bak	2020-07-06 23:00:27.000000000 +0200
+++ cputc.s	2020-07-06 23:00:47.000000000 +0200
@@ -68,8 +68,7 @@
 L10:    and     #$7F
         cmp     #$7E            ; PI?
         bne     L11
-        lda     #$5E            ; Load screen code for PI
-        bne     cputdirect
+        lda     #$1E            ; Load screen code for PI
 L11:    ora     #$40
         bne     cputdirect
````

**Comment by mrdudz** [comment]
brilliant. why fix it when you can make it shorter? ;_;

**Comment by oliverschmidt** [comment]
Okay, again - I'm no CBM guy but it seem necessary that I understand a bit here so please explain...

https://en.wikipedia.org/wiki/PETSCII shows pi both for 220 and 255.

However, https://github.com/cc65/cc65/blob/master/libsrc/c64/cputc.s#L76-L79 seems to print pi for 254.

So do I interpret the discussion here so far correctly that everybody agrees in that the current code needs to be changed?

But @greg-king5 thinks it should be changed to print pi for 220 while the others think it should be changed to print pi for 255, correct?

And finally, several comments refer to "the fix", that means https://github.com/polluks/cc65/commit/f584244f6a63dad267966f39ec4360182ced1220 I guess. In that case I ask @polluks to provide a PR (ideally incl. the optimization mentioned in https://github.com/cc65/cc65/issues/988#issuecomment-654464752).

**Comment by mrdudz** [comment]
Actually, that fix is also not 100% correct - because $7f is NOT pi (sorry, i didnt see this before). That said, i wouldn't trust wikipedia for this either :)

First we need to agree on what gives the authorative answer to "what character belongs to what charactercode". In my book this is the CBM kernal function CHROUT ($ffd2 on C64), ie what basic "print" will use. If we agree on this, a simple BASIC program can print the encoding:

~~~
10 print"0123456789abcdef"
20 fory=0to15
30 forx=0to15
40 c=y*16+x
50 if (c<32) or ((c>127)and(c<160)) then
 c=32: rem control chars
60 print chr$(c);
70 next x:print" ";y:next y
~~~

(never mind the inverted [ in the third row after the 2... thats another kernal quirk)

we can then easily verify its correct by making a simple c-program that does the same thing

**Comment by oliverschmidt** [comment]
First of all thanks for your comprehensive reply.

> That will also match the tables you will find pretty much in all documentions (and i dare to say: that is what users expect)

Maybe I'm again missing the point, but if the Kernal and/or BASIC behave "strange" / "inconsistent" and users are used to that behavior then I think it's appropriate to be compatible to that behavior even if it's conceptually "wrong".

I'm no C64 BASIC programmer. Can you maybe include a screenshot of the output of that BASIC program? That would help at least me to understand where you are heading to.

**Comment by mrdudz** [comment]
Here is the output of the C program i linked in the previous post:

![bug988](https://user-images.githubusercontent.com/8898802/86802976-daa25600-c075-11ea-82b7-ce6058711c15.png)

left side is putchar() output (which uses the CBM kernal directly) and right side is the cputc() function. as you can see, codes 254 and 255 are different between the two

**Comment by oliverschmidt** [comment]
Thanks - at least to me it seems a reasonable approach to want the right side look identical to the left side. I'm ready to merge a PR achieving just that.

**Comment by mrdudz** [comment]
This works:

~~~
diff --git a/libsrc/c64/cputc.s b/libsrc/c64/cputc.s
index d6b49607..b893f210 100644
--- a/libsrc/c64/cputc.s
+++ b/libsrc/c64/cputc.s
@@ -74,10 +74,9 @@ L5:     inc     CURS_Y
 ; Handle character if high bit set
 
 L10:    and     #$7F
-        cmp     #$7E            ; PI?
+        cmp     #$7F            ; PI?
         bne     L11
         lda     #$5E            ; Load screen code for PI
-        bne     cputdirect
 L11:    ora     #$40
         bne     cputdirect
~~~ 

that said, the other CBM targets (c128, cbm510, cbm610, plus4, vic20) all require the same patch in this function. if only this PR stuff wouldnt be such a $swearword =P

**Comment by mrdudz** [comment]
PS: i can do a direct commit if you dont mind :)

**Comment by oliverschmidt** [comment]
Yes, please go ahead....

**Comment by mrdudz** [comment]
done, see d1833cc4
