### ISSUE TITLE
[bug][cygwin?] When only compiling "-c" the option "-o" is disregarded in some cases

### ISSUE THREAD

**Issue by Fabrizio-Caruso** [cc65/cc65#991]
Under my Cygwin environment when only compiling "-c" the option "-o" is disregarded in some cases. (cl65.exe version is the recent V2.18 - Git 4dda5d2)

KO: `cl65.exe -t bbc -c  empty42.c -o foo.o` -> object file created is `empty42.o`
OK: `cl65.exe -t bbc -c -o foo.o empty42.c` -> object file created is `foo.o`

Remark1 : No problem when compiling and linking
Remark2 : I am inside a symbolically linked directory in Cygwin environment

```
$ rm *.o

fabri@LAPTOP-N0E6U869 ~/Retro/CROSS-CHASE/src/test
$ cl65.exe -v -t bbc -c -o foo.o empty42.c
0 errors, 0 warnings
Opened output file 'empty42.s'
Wrote output to 'empty42.s'
Closed output file 'empty42.s'

fabri@LAPTOP-N0E6U869 ~/Retro/CROSS-CHASE/src/test
$ ll *.o
-rwxrwxr-x+ 1 fabri fabri 731 Dec  6 00:06 foo.o*

fabri@LAPTOP-N0E6U869 ~/Retro/CROSS-CHASE/src/test
$ rm *.o

fabri@LAPTOP-N0E6U869 ~/Retro/CROSS-CHASE/src/test
$ cl65.exe -v -t bbc -c  empty42.c -o foo.o
0 errors, 0 warnings
Opened output file 'empty42.s'
Wrote output to 'empty42.s'
Closed output file 'empty42.s'

fabri@LAPTOP-N0E6U869 ~/Retro/CROSS-CHASE/src/test
$ ll *.o
-rwxrwxr-x+ 1 fabri fabri 731 Dec  6 00:06 empty42.o*
```

**Comment by mrdudz** [comment]
thats because it works strictly from left to right - so it works as expected :)

**Comment by groessler** [comment]
Hmm. Is this desired behaviour? Other compilers are smarter in this regard....

**Comment by mrdudz** [comment]
its quite common actually - and the only way to make it possible to have options given more than once

**Comment by groessler** [comment]
Sure. And I agree with the behaviour to overreide former parameters by later parameters.

But I don't see what in Fabrizio's example "voids" the given output file name.

**Comment by mrdudz** [comment]
its just not known, the output filename must be known before input files are given
