### ISSUE TITLE
Wrong code optimization on loop (char) condition?

### ISSUE THREAD

**Issue by acqn** [cc65/cc65#992]
```c
int wrong(int);
char i;

int main(void)
{
	i = 10;
	while (--i) ;
	return wrong(0);
}
```
Compiled with any "-O" option, the generated code becomes something like (only the relevant part quoted here) :
```asm
.segment	"CODE"

	lda     #$0A
	sta     _i
L0004:	dec     _i
	ldx     _i
	bne     L0004
	jmp     _wrong
```
CC65 with optimization on seems to errorneously assume that register A must be 0 after the loop that checks against 0, and will pass it to any function that takes 0 as the parameter right after the loop.

This issue goes away if optimization is turned off, as expected.

**Comment by acqn** [comment]
Could the culprit be Line 1474 in cc65\coptind.c?
It is supposed to check whether a REG is not being used (that is not marked with certain bit-flags), but in a seemingly wrong way:
`GetRegInfo (S, I+2, E->Chg) != E->Chg`
I think the correct way to check the flags should be:
`(GetRegInfo (S, I+2, E->Chg) & E->Chg) == 0`

**Comment by oliverschmidt** [comment]
Fixed with https://github.com/cc65/cc65/pull/996.
