### ISSUE TITLE
Avoiding running the built binaries during build time?

### ISSUE THREAD

**Issue by NateDogg1232** [cc65/cc65#993]
Hello! I am trying to make a package for this program for Void Linux, and they require support for cross compiling for their programs. The problem with this is that the way this program is built, is the libraries are assembled/compiled during the make process. Is there any way we can avoid this problem, as this makes cross compilation impossible?

Also, more out of curiosity, why compile/assemble them during make of cc65 instead of compiling/assembling them during compile time for the programs?

Thank you!

**Comment by greg-king5** [comment]
> I am trying to make a package for this program, for Void Linux, and they require support for cross compiling for their programs. The problem with this is that, the way this program is built, the libraries are assembled/compiled during the make process. Is there any way we can avoid this problem, as this makes cross compilation impossible?

The project has some support for cross-building for Windows.  When we push changes up to Github, it uses Travis CI to test for fatal regressions.  Then, it cross-builds a Windows package.  The command lines for that are: https://github.com/cc65/cc65/blob/cab4910a7d07029b3cc0ffd8abd4355f0365f5b7/.travis.yml#L11-L14
`make bin` builds only the tools.  `make lib` builds only the libraries.  There are other useful rules in the top-level Makefile.

> Also, more out of curiosity, why compile/assemble them during make of cc65 instead of compiling/assembling them during compile time for the programs?

**cc65** is like **gcc** and **clang**, it links your programs to pre-built libraries.  That method allows your programs to be built and rebuilt faster.
