### ISSUE TITLE
(atari) Creating Relocatable CIO driver

### ISSUE THREAD

**Issue by tschak909** [cc65/cc65#998]
Hey, guys.

I posted this here for some input, because I'm scratching my head a bit.

For those that don't know, I've been knee deep in writing software for the #FujiNet project, a network adapter for Atari 8-bit systems, and lots of the code for now has been coded in CC65.

I've proven that a CIO driver can be written in C:
https://github.com/FujiNetWIFI/atariwifi/tree/master/tests/cio3/atari/src 

but it's currently loaded in at a fixed location ($1D00, which assumes a clean 2 drive DOS 2.5), and I would like to figure out how to make this a proper relocatable object.

I've studied the code for the Atari 850 handler, which uses page-level relocation, and that makes sense, I guess I can ultimately handle that myself, by making a headerless binary, linking at a start address one page apart, and then writing a chunk of code that knows the addresses and fixes them up...

 But am wondering if something like o65 can't be used for this purpose? Using the same mechanisms used by e.g. TGI?

**Comment by polluks** [comment]
By the way SpartaDOS also has some relocation support, but I suppose it's better to reuse the o65 relocator somehow.

**Comment by groessler** [comment]
I guess it could (and should) be done with the o65 object format. I haven't looked at the o65 relocator before though.

**Comment by mrdudz** [comment]
I'd first check if compiling a few different binaries wouldnt solve it - the o65 loader adds a lot of overhead.

**Comment by groessler** [comment]
But this should be just on-disk. Yeah, one should keep an eye upon this.
